### ISSUE TITLE
can not open terminal on windows with postgres

### ISSUE THREAD

**Issue by ldwqh0** [cweijan/vscode-mysql#1000]
- Database type and version:  
![image](https://github.com/cweijan/vscode-database-client/assets/9332016/e71e886b-9d3b-4199-b0b5-3c2679da9d3e)

**Comment by cweijan** [comment]
Thanks for the feedback, I will fix it in the next version, currently you can solve it by setting the default terminal to cmd.

**Comment by cweijan** [comment]
Fixed in version 6.9.1.
