### ISSUE TITLE
sqlite3 on a remote machine

### ISSUE THREAD

**Issue by mercurykd** [cweijan/vscode-mysql#1001]
sqlite3 on a remote server - is this possible?

**Comment by cweijan** [comment]
Yes, you need to install sqlite3 on your remote machine.

**Comment by mercurykd** [comment]
> Yes, you need to install sqlite3 on your remote machine.

only local. how to select on a remote server? perhaps via ssh option?
![image](https://github.com/cweijan/vscode-database-client/assets/30900414/3dde609e-fb77-4a32-b1ae-e7c211291e12)

**Comment by cweijan** [comment]
You can only connect to the remote machine through [remote-ssh](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) and then create a sqlite connection through the extension. It is impossible to directly connect to the remote sqlite.
