### ISSUE TITLE
[BUG] Query Execution Timing floating in sqlbook and table column types not showing!

### ISSUE THREAD

**Issue by rahulmasal** [cweijan/vscode-mysql#1002]
- Database type and version: PostgreSQL 16
Per the title, we are facing issues while working with the SQL book!

https://github.com/cweijan/vscode-database-client/assets/22212803/0ccca447-1c06-41b0-81eb-0348b497ba20

**Comment by cweijan** [comment]
Thanks for the feedback. Have you bound the sql book to the schema of the corresponding connection?

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/0d4830d9-62af-420b-9a6d-9deed27029a8)

**Comment by rahulmasal** [comment]
not bounded directly using!

**Comment by cweijan** [comment]
You can try binding. Without binding, the extension will read the public schema data by default.

**Comment by rahulmasal** [comment]
tried using binding also but same issue, and why showing double entries in database selection options i am new with database learning please help me!


https://github.com/cweijan/vscode-database-client/assets/22212803/b4e6b485-5187-492b-bd82-775cb88f9815

**Comment by cweijan** [comment]
You need to bind the level to the schema.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/619ed25f-aafb-4227-956f-9aa8603f7644)


What do you mean by "double entries"? I can't see it in the video.

**Comment by rahulmasal** [comment]
what is public and normal named of same database?
that column type issue resolved but query execution time is still floating!


https://github.com/cweijan/vscode-database-client/assets/22212803/eefe66e2-bb66-4623-950e-bcd9eb765ddb

**Comment by cweijan** [comment]
PostgreSQL databases can have multiple schemas, the default is public, and data in different schemas are isolated.

I will try to fix the query execution time floating in the next version.

**Comment by rahulmasal** [comment]
Try to provide the premium trial option if possible to test the premium features, so if someone needs those they will buy after testing the features!

**Comment by cweijan** [comment]
After registering on the [official website](https://database-client.com/#/home),  will get a 7-day trial. The biggest difference with premium is that there is no limit on the number of connections.

**Comment by rahulmasal** [comment]
yes, thanks !

**Comment by cweijan** [comment]
Fixed in version 6.9.1.

**Comment by rahulmasal** [comment]
thanks!
