### ISSUE TITLE
[BUG] fetch clause not working!

### ISSUE THREAD

**Issue by rahulmasal** [cweijan/vscode-mysql#1003]
- Database type and version: Postgresql 16 

as per the title fetch clause is not working in sqlbook but same working in pgadmin 4.

https://github.com/cweijan/vscode-database-client/assets/22212803/6e90d94e-2f8b-4ce7-ad00-df90373d8b62

**Comment by cweijan** [comment]
Thanks for the feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed in version 6.9.1.

**Comment by rahulmasal** [comment]
thanks
