### ISSUE TITLE
No primary key found.

### ISSUE THREAD

**Issue by cweijan** [cweijan/vscode-mysql#1004]
When the extension does not recognize a table's primary key, the changes you make may affect more records than expected(The performance is that the column type cannot be displayed).
![2](https://github.com/cweijan/vscode-database-client/assets/27798227/0fd5ec61-bf6c-4360-a8bf-9ca44c22d799)

This is usually because no schema was selected when binding the connection, therefore, please select the corresponding schema when you bind the connection.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/1ecd59a3-2f96-4062-8e37-70110a5f13ba)

**Comment by devLucasCBMelo** [comment]
But where do I find this schema?

**Comment by cweijan** [comment]
@devLucasCBMelo Through `Active Connection` command.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/3240d911-b4c1-44df-a9f0-13270027bc93)

**Comment by mizanmahi** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/49094616/061d54cb-9805-479b-a3fd-c09e260ba5aa)


![image](https://github.com/cweijan/vscode-database-client/assets/49094616/ac74d0b0-7f09-4e5a-a035-933e86e681e3)


same error even after binding the schema!

**Comment by cweijan** [comment]
Hi @mizanmahi , your error is not a problem of not finding the primary key. Maybe there is duplicate data in your table data, so the creation of a unique index is not allowed.
