### ISSUE TITLE
Open Query Default location must be user choose i think!

### ISSUE THREAD

**Issue by rahulmasal** [cweijan/vscode-mysql#1005]
Hi,

as per title issue with open query > public.sql file storage location which is inside globalStorage>cweijan.vscode-postgresql-client2>xxxxxxxxxx@127.0.0.1@532@xx@xx , need to save this file as per user choice i think!

https://github.com/cweijan/vscode-database-client/assets/22212803/94ba6ca2-7fd8-427e-8905-1b3a7feb3ea3

**Comment by cweijan** [comment]
It is recommended to create a query in query node. The query here will be saved in the user directory.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/fd8062f6-4ebf-4a26-a8ef-6ca53caf95d6)

**Comment by rahulmasal** [comment]
still not getting folder location where my current folder opened!

https://github.com/cweijan/vscode-database-client/assets/22212803/317d8891-edc1-4898-9e44-bffbe1fbde49

**Comment by cweijan** [comment]
Right click on editor tab, then:
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/7c77ec62-0416-4633-afaf-c9e99c3c082b)

**Comment by rahulmasal** [comment]
Yes, I know but why no option to save files to user opened directory only?

like current opened directory in vs code ! so extension must take that location only to save the file!

**Comment by cweijan** [comment]
The extension identifies connections through path rules, this is equivalent to a shortcut. 
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/d1cef21e-11db-40f3-87dc-13e42464a53f)

If you want to create in your own folder, you just create the sql file and bind the connection.
