### ISSUE TITLE
[BUG] I have the sqlite library installed but it is not recognizing the extension

### ISSUE THREAD

**Issue by Mateuskjk** [cweijan/vscode-mysql#1007]
I am using the sqlite with my database to my project, when I was trying to connect my archive .db with sqlite, He is not recognizing the sqlite library installed in my PC, I tried reinstalling Node.js and the libraries, I checked my dependencies in package.json (package-lock too), I Restarted my PC and don't worked.
- Database type and version: sqlite, 6.9.1 2023-12-13, 20.10.0 (node.js)
![Screenshot 2023-12-13 131611](https://github.com/cweijan/vscode-database-client/assets/118078588/fa037f58-7c17-4fab-8248-508476ca6b9d)
![Screenshot 2023-12-13 131647](https://github.com/cweijan/vscode-database-client/assets/118078588/263abe79-acaa-4109-9509-86a728711c5d)
![Screenshot 2023-12-13 131707](https://github.com/cweijan/vscode-database-client/assets/118078588/a3d5fa9b-8569-48b8-8c75-f4866cae54d0)
![Screenshot 2023-12-13 131730](https://github.com/cweijan/vscode-database-client/assets/118078588/c86bf3be-74c3-4478-ab8c-42f75514218f)
![Screenshot 2023-12-13 131748](https://github.com/cweijan/vscode-database-client/assets/118078588/d37eedf1-1829-4d24-81e1-5b7e0835662d)

**Comment by cweijan** [comment]
The extension does not use nodejs, please click the link to download sqlite and add it to the environment variables.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/53541c70-0670-4ceb-899a-dd21d1f429c3)

**Comment by Mateuskjk** [comment]
Thank you for your help, I just forget add SQlite in my environment variables. lol

**Comment by TechQuery** [comment]
> I just forget add SQlite in my environment variables.

@Mateuskjk SQLite's environment variables will be configured automatically, if you install it with `winget`.
