### ISSUE TITLE
Move panel to new window

### ISSUE THREAD

**Issue by bbysoft** [cweijan/vscode-mysql#1008]
It would be very useful if the panel could be moved to a new window, which I can display on another monitor if necessary.

I am currently receiving this message.
 "This type of editor cannot be opened in other windows yet."

**Comment by cweijan** [comment]
Hi, moving to a new window is implemented by VS Code, and I can't interfere. The current view of the extension is webview, and I believe VS Code will support it in future versions, microsoft/vscode#195715.

**Comment by cweijan** [comment]
Hi, VS Code currently supports moving webview to new window, and the extension has been adapted in version 7.2.6.

**Comment by bbysoft** [comment]
> Hi, VS Code currently supports moving webview to new window, and the extension has been adapted in version 7.2.6.

Hello! This is happy news for me. I checked and there are still some errors in it. If I move it to a new window and want several tabs (multiple table queries) in the same new window, it does not work properly.
Since I also develop on several monitors and want to display the database in a new window on one of the monitors, it is important for this to work.
I think most of us are like that.
The direction is very good and thank you for your work!

**Comment by cweijan** [comment]
Hi, do you mean that multiple windows cannot edit SQL? If so, the SQL editing panel will be displayed in a new window in the next version.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/45d54a91-bdcc-4189-9e7d-016e78f3b0e7)

**Comment by bbysoft** [comment]
> Hi, do you mean that multiple windows cannot edit SQL? If so, the SQL editing panel will be displayed in a new window in the next version. 

Hello! Yes, I think we mean the same thing. I'll see it in the next version.
All the best to you.
