### ISSUE TITLE
[BUG] Snowflake Lib does not install

### ISSUE THREAD

**Issue by travisbusen** [cweijan/vscode-mysql#1009]
- Database type and version:

VS Code:

Version: 1.85.1 (Universal)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:48:06.308Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.2.0

Trying to install the Snowflake driver and I only shows downloaded.  The status does not change to installed and I don't get any indication in the terminal it actually installed.

![image](https://github.com/cweijan/vscode-database-client/assets/12953607/3de1e67e-4ab8-4a75-aaae-16f9c8b43968)

**Comment by cweijan** [comment]
Try clicking back to the connection page, it should get updated.

**Comment by travisbusen** [comment]
No that doesn't do anything.  I've restarted VS Code.  The output only says download successful.  Nothing indicates installation.

**Comment by cweijan** [comment]
Fixed in version 6.9.6.
