### ISSUE TITLE
[BUG] Error when i try to Manual Lock Record using FOR UPDATE Statement

### ISSUE THREAD

**Issue by yazid2021** [cweijan/vscode-mysql#1011]
OS = Windows 10,
DBMS = MySQL,
Extension Version = 6.9.2

When I change the data of the table for LOCKING, I don't know why using this extension get error when I'm using **FOR UPDATE** statement to Locking the data. Even though in Windows Terminal and MySQL Workbench it works, there is no error.

This extension :

![vscode_extension](https://github.com/cweijan/vscode-database-client/assets/85673380/9889f0af-bd01-461c-8684-c8cd367f4b47)

Windows Terminal :

![windows_terminal](https://github.com/cweijan/vscode-database-client/assets/85673380/6d99510c-fdb3-4592-be0d-a5e778407975)

MySQL Workbench :

![mysql_workbench](https://github.com/cweijan/vscode-database-client/assets/85673380/6db2cfcf-ea46-4f8e-baaa-42095976eb35)

Thanks for making this extension, very helpful for me :zap:

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

You can solve this problem by disabling automatic paging.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/59064b61-d01c-49b1-80a3-e212f3882d1b)

**Comment by yazid2021** [comment]
Thanks!
