### ISSUE TITLE
[BUG] Can't perform Ctrl+V in SQL editor and connection configuration

### ISSUE THREAD

**Issue by anton-fjg** [cweijan/vscode-mysql#1012]
In some version ago, it is appeared that the command Ctrl+V doesn't work in SQL editor and connection configuration.

- Database type and version:
MySQL

**Comment by cweijan** [comment]
Are you using the web version of VS Code?

**Comment by anton-fjg** [comment]
Oh, sorry! Yes. Because, I have switched to Gitpod.io recently. Gitpod.io suggests the web version of VSCode.

**Comment by cweijan** [comment]
Ok, the web version of VS Code requires you to authorize its clipboard permissions in the browser, you can find how to authorize it from Google.

**Comment by anton-fjg** [comment]
@cweijan Actually, permissions for clipboard in the browser are enabled. And, it doesn't help.

Maybe you can have any other ideas?

(Probably, you can easily reproduce it in gitpod.io.)

**Comment by cweijan** [comment]
I tried Gitpod.io and the clipping worked fine, so I'm sure it's a browser issue.

**Comment by anton-fjg** [comment]
Sorry, maybe I missed something.
I use Chrome latest version. And, disabled all extensions.

Also, I tried Crtl+V on mobile Chrome - also doesn't work.

**Comment by anton-fjg** [comment]
Version of MySQL client v6.9.4

**Comment by cweijan** [comment]
Hi, clipboard and extensions are unrelated, I can't help you with anything, just from my experience I know it's a browser issue.

If you cannot paste, then even if you edit a plain text, you cannot paste.

**Comment by erandelax** [comment]
Experienced somewhat similar issue on Windows 11 in Chrome 126.0.6478.127, Firefox 128.0, Edge 126.0.2592.87 and Opera 111.0.5168.61 with Visual Studio Code Server (web version UI).

Copy command works, paste does not, both for RMB popup menu and hotkeys. No errors in console or any noticeable reaction. 

Happens in "Create/edit connection" configuration form, extension settings form, database client login form, database viewer SQL edit row and search field, update column popup... Basically for most of single line text inputs in any of the extension UI forms. 

At the same time multiline .SQL editor and query results table view individual cell value editor fields operate normally, same for the rest of the app including forms of other extensions.

**Comment by cweijan** [comment]
Thanks feedback, I fixed this issue in version 7.5.6 using the new API
