### ISSUE TITLE
[BUG]The new workspace encryption is broken

### ISSUE THREAD

**Issue by pmathbliss** [cweijan/vscode-mysql#1014]
- Database type and version: SSH
Please give the option to turn the encryption of password "security feature" off. This is breaking the password on connections. And preventing the saving of the password in the connection.

**Comment by cweijan** [comment]
Sorry, I misunderstood your issue, I have now released version 6.9.5 to fix it.

**Comment by pmathbliss** [comment]
I dont need the password encrypted. The implementation is breaking the
form's ability to save the password. I try to save an ssh password and it
clears the password. I am also getting an error that all authentication
methods have been exhausted. The connection works fine in other ssh
applications. I have one project where myself can connect via ssh tunnel,
but the direct ssh does not work.

**Comment by cweijan** [comment]
Hi, the failure to save the password is not caused by encryption, but I used the wrong fields. I have released version 6.9.5 to fix it.

**Comment by pmathbliss** [comment]
Ok, thanks.

**Comment by pmathbliss** [comment]
Just tried it and its all working. Thanks for your help.

**Comment by cweijan** [comment]
Thanks feedback!
