### ISSUE TITLE
[BUG]SQLServer跨服务器进行CTE查询时, 数据显示缺失或不显示

### ISSUE THREAD

**Issue by Kyufuru** [cweijan/vscode-mysql#1015]
- Database type and version: Microsoft SQL Server 2014 - 12.0.2000.8 (X64)

```sql
SELECT ID FROM (
    SELECT ID FROM [ip].schemaA.dbo.t1
) A1
``` 
这样子是没问题的

```sql
WITH A1 AS (
    SELECT ID FROM [ip].schemaA.dbo.t1
)
,A2 AS (SELECT ID FROM A1)
SELECT * FROM A2
``` 
但是这样子数据查询结果会缺失

似乎是由于 #1004 的原因, 使用链接服务器找不到表的主键导致的, 这个问题会修复吗?

**Comment by cweijan** [comment]
数据显示缺少是什么表现呢? 跨服务器没办法获取主键, 可以查询数据, 但不建议进行编辑或者删除数据.
