### ISSUE TITLE
Change the default cursor shape for the SSH client.

### ISSUE THREAD

**Issue by lmovse** [cweijan/vscode-mysql#1017]
If the default cursor shape is currently a vertical line, it is inconvenient when editing files in vim mode as it's challenging to quickly distinguish between vim mode and insert mode. Could it be set to a default shape of a block, similar to the cursor shape in the terminal on macOS? Additionally, it would be ideal if the shape changes to a vertical line when in vim insert mode.

### Current
![image](https://github.com/cweijan/vscode-database-client/assets/19148311/24b464cf-90be-4574-b620-eac82431065d)

### Mac
<img width="563" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/19148311/d4aae14e-98bd-4779-8737-45974fcd48ac">

**Comment by cweijan** [comment]
Hi, I plan to make the cursor style of the ssh terminal follow the vscode terminal in the next version. Will this help you?

**Comment by lmovse** [comment]
> Hi, I plan to make the cursor style of the ssh terminal follow the vscode terminal in the next version. Will this help you?

Yes, this will be very helpful.

**Comment by cweijan** [comment]
Already followed VS code terminal cursor style in version 6.9.9.
