### ISSUE TITLE
[BUG] SSH Client cannot clear screen.

### ISSUE THREAD

**Issue by lmovse** [cweijan/vscode-mysql#1018]
![image](https://github.com/cweijan/vscode-database-client/assets/19148311/fa24f3f7-6773-45ed-9936-7444a0953490)

Looks like the interval between the two command executions is too short?

**Comment by cweijan** [comment]
Your screenshot clearly shows that you did not enter the clear command correctly.

**Comment by cweijan** [comment]
It seems that you clicked the clear button from the toolbar, I will check this.

**Comment by lmovse** [comment]
> It seems that you clicked the clear button from the toolbar, I will check this.

Yes, i clicked that.

**Comment by cweijan** [comment]
This happens when your server TTL is high, I added an execution delay in the latest version, please see if it works for you.

**Comment by lmovse** [comment]
It looks much better than before, tks.
