### ISSUE TITLE
[BUG] too much result total 

### ISSUE THREAD

**Issue by MoreMeng** [cweijan/vscode-mysql#1019]
![image](https://github.com/cweijan/vscode-database-client/assets/6345490/c850f315-1b03-4a85-bec6-23da9a6761fd)

clear cache and reset config, but not work.

- Database type and version:
- PostgreSQL 14.6 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-15), 64-bit

**Comment by cweijan** [comment]
If you don't want to display the total, you can turn off the setting to automatically get the total.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/c1af0e34-3d12-459a-96f7-7361b0c1cc74)

**Comment by MoreMeng** [comment]
thank you! 😊
