### ISSUE TITLE
[BUG] always install libpq when dumping table, but have installed libpq and configured PATH

### ISSUE THREAD

**Issue by NingGelin** [cweijan/vscode-mysql#1021]
- Database type and version: pg
<img width="158" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/42860920/e9dab356-2fee-454b-a199-075e1ddd2a5c">

<img width="625" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/42860920/270aff9b-b722-464f-8ef3-57fbe4893b63">

**Comment by cweijan** [comment]
Hi, this is because the extension cannot find the location of pg_dump. Please tell the location of pg_dump on your machine.

**Comment by NingGelin** [comment]
> Hi, this is because the extension cannot find the location of pg_dump. Please tell the location of pg_dump on your machine.

/opt/homebrew/opt/libpq/bin/pg_dump

**Comment by cweijan** [comment]
The extension can find this location, try updating the extension.

**Comment by NingGelin** [comment]
restarted the vscode, it works now. sorry my bad. thank you very much.
