### ISSUE TITLE
Is there a way to remove the column comments in result page?

### ISSUE THREAD

**Issue by mty713** [cweijan/vscode-mysql#1023]
this was introduced in version 6.7.8, but I haven't been able to find a way to disable this feature. Thanks

**Comment by cweijan** [comment]
Hi, I have modified the display logic in the latest version 7.0.0. Now only Chinese comments will be displayed by default. You can also control its display logic in the console.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/7e7e9d8f-9a56-447a-ad3b-d61f075d2022)
