### ISSUE TITLE
[BUG] 单击table弹出的窗口报错

### ISSUE THREAD

**Issue by WIZeaz** [cweijan/vscode-mysql#1024]
- Database type and version:
单击Database视图中具有特殊名称的table会产生一个报错，由于SELECT命令没有考虑到table名字里可能存在特殊符号（例如+）
![图片](https://github.com/cweijan/vscode-database-client/assets/34786011/434447c7-8336-42a5-9393-a50596cb8b76)

我测试了一下，通过在table名称两侧添加"`"可以解决这个问题：
![图片](https://github.com/cweijan/vscode-database-client/assets/34786011/a7a9b18e-3d30-4bc9-bd4c-b0274898d318)

希望这个问题能够得到修复，多谢~

**Comment by cweijan** [comment]
已发布版本6.9.10修复.
