### ISSUE TITLE
[BUG] Recently, ssh changed to this font. It was normal a few days ago

### ISSUE THREAD

**Issue by NightmareZero** [cweijan/vscode-mysql#1026]
Version 6.9.10 2024-1-11
Using ssh
The following code terminal works fine, but the plugin's ssh looks like this

![Screenshot 2024-01-12 104349](https://github.com/cweijan/vscode-database-client/assets/17422155/563bbb7c-56d8-4c63-abe0-8420f2dc9ebd)

**Comment by NightmareZero** [comment]
like this issue
https://github.com/cweijan/vscode-database-client/issues/609

```json
{
"terminal.integrated.fontFamily": "Consolas",
}
```

now it seems to be not working properly

**Comment by cweijan** [comment]
Can you show me your "editor.fontFamily" and "terminal.integrated.fontFamily" settings?

**Comment by NightmareZero** [comment]
> Can you show me your "editor.fontFamily" and "terminal.integrated.fontFamily" settings?

![Screenshot 2024-01-12 112501](https://github.com/cweijan/vscode-database-client/assets/17422155/2166e804-eea0-4ef9-aba1-11ccf762c99c)
![Screenshot 2024-01-12 112527](https://github.com/cweijan/vscode-database-client/assets/17422155/6bdee691-a551-45f1-8901-f7ad1c41a9c8)

all changed to 'Consolas', still the same.

**Comment by cweijan** [comment]
This seems to be because you are using a custom font, which you can currently solve by configuring the font without single quotes, such as Consolas.

I will no longer use custom fonts in `editor.fontFamily` in the next version.

**Comment by NightmareZero** [comment]
> This seems to be because you are using a custom font, which you can currently solve by configuring the font without single quotes, such as Consolas.
> 
> I will no longer use custom fonts in `editor.fontFamily` in the next version.

After I changed it to Fira Code Retina, it worked fine. (Instead of 'Fira Code Retina')
Currently, `editor.fontFamily` is being used, but it should be `terminal.integrated.fontFamily`.

**Comment by cweijan** [comment]
Hi, "editor.fontFamily" is no longer read in version 7.0.0.

**Comment by NightmareZero** [comment]
> Hi, "editor.fontFamily" is no longer read in version 7.0.0.


I have already started using it on January 16th, thank you
