### ISSUE TITLE
[BUG] Cannot authenticate using "Log In On Browser"

### ISSUE THREAD

**Issue by chrisptree** [cweijan/vscode-mysql#1028]
I bought a one year prenium licence today (2024-01-15) but I cannot login.

When I work on remote via ssh, I cannot use the simple Login method because our server cannot access to internet even with a proxy. So I tried with the Log In On Browser method, but the redirected link is not allowed as shown the following image.
![image](https://github.com/cweijan/vscode-database-client/assets/8090476/564e34fe-1405-49d9-b3ed-9f5c1b76a250)
Could you help me to resolve thist?

**Comment by cweijan** [comment]
Login in VS code requires you to open VS Code (non-remote environment mode) first, and then use remote-ssh after you activate premium.

**Comment by chrisptree** [comment]
> Login in VS code requires you to open VS Code (non-remote environment mode) first, and then use remote-ssh after you activate premium.

I tried it but with the same result. I tried the button "Log In VS Code" from the website and it worked. So, I close the ticket.
