### ISSUE TITLE
[BUG] S3 Bucket connection issue

### ISSUE THREAD

**Issue by BikashWhitehat** [cweijan/vscode-mysql#1029]
- Database type and version:
S3 storage

when i try to connect to s3 storage in us-east-2 region (selection from service) it throws the error

> Connection error! The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-east-2'

but can connect us-east-1

**Comment by cweijan** [comment]
Thanks feedback, this problem will be fixed in the next version.

**Comment by BikashWhitehat** [comment]
thanks, much appreciated

**Comment by cweijan** [comment]
Fixed in version 7.0.1.
