### ISSUE TITLE
[BUG] When double click on a table an error message "Actual command not found, wanted to execute mysql.table.find /329" show up periodically

### ISSUE THREAD

**Issue by cdong8812** [cweijan/vscode-mysql#1030]
Instead of running select query I get this error periodically at the bottom right of the window

- Database type and version:
Operating system: Ubuntu 20.04
Database type and version: Postgres 11.16

**Comment by cweijan** [comment]
This problem occurs when you click on a node that is being refreshed. This is a VS Code bug.

**Comment by cdong8812** [comment]
Thanks I will close it
