### ISSUE TITLE
[BUG]Opening tables (queries) by clicking the table-name under "Tables" doesn't work when the table is not in the public schema

### ISSUE THREAD

**Issue by tvstetten** [cweijan/vscode-mysql#1032]
- Database type and version:  PostgreSQL on supabase
- Errormessage 'relation "<tablename>" does not exist' under the query-string and the toolbar.

Error:
The schema-name isn't automatically added in front of the table-name

**Comment by cweijan** [comment]
Hi, the schema is automatically switched. What is your PostgreSQL version?

**Comment by tvstetten** [comment]
Hi, 
Thanks for the quick answer.
The version is 15.1.1 on supabase.
When I manually add the schema to the query string it works

I only get the error when using a connecting instead of the standard credentials. I think that's the problem. After I filled the standard credentials completely and disabled tho connection string everything worked.
When I enable the connection string again the error is back again.

Additionally I am not able to dump data/schema.
1. According to the output log the standard credentials  are used. If i doesn't provide them it won't work.
2. After I completed my credentials I got an errormessage that the versions of the server and the pg_dump don't match. But I think that's a supabase problem.

**Comment by cweijan** [comment]
Hi, I tried supabase. This is a bug of supabase. Modifying the connection schema does not always take effect. This has nothing to do with whether you use a connection string. I will add an option to query with the schema.

As for dump, the extension relies on pg_dump for dumping. Please check whether your local pg_dump and supabase's pg version are consistent: `pg_dump --version`

**Comment by tvstetten** [comment]
Thanks,
that is consistent with my observations. The schema-error does not appear every time :-)

Yes, you are right. my local pg_dump has an old version (12.17). 
But I'm not a Linux-Crack and I can't upgrade my postgres version. I removed the current version and installed the newest version according to descriptions on the internet but, the version of my pg_dump is still 12.17. I have no idea how I can upgrade to 15.1 or 16.xy. 

If you don't have a tip regarding uninstalling/installing (which isn't your bussiness) you can close the ticket.

**Comment by cweijan** [comment]
Hi, in the latest version 7.0.3, schema will always be included for schema that is not public. If you want to also with schema for public, you can check the following configuration in the console:

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/0ea7973e-5e62-4ad3-9abd-fa3ceee18e6f)
