### ISSUE TITLE
希望ssh tunnel能支持ssh-agent来连接

### ISSUE THREAD

**Issue by iciness** [cweijan/vscode-mysql#1033]
我现在ssh连接都通过ssh 代理来管理私钥，希望能实现对ssh-agent的支持

**Comment by cweijan** [comment]
你试试auth为auto, 这个会启用ssh-agent
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/f0510188-fc86-4423-8325-ab310b5f9e64)

**Comment by iciness** [comment]
> 你试试auth为auto, 这个会启用ssh-agent ![image](https://private-user-images.githubusercontent.com/27798227/298496386-f0510188-fc86-4423-8325-ab310b5f9e64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NzI4MjEsIm5iZiI6MTcwNTk3MjUyMSwicGF0aCI6Ii8yNzc5ODIyNy8yOTg0OTYzODYtZjA1MTAxODgtZmM4Ni00NDIzLTgzMjUtYWIzMTBiNWY5ZTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDAxMTUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZWMxYjhkOTZiMWVkNDkwMzNkNzlkZTE5NDhiNzdjNmZmYTM1NjdmMTFmMWIxODMzZWY5NDZjOTExYjY0NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SRoT9iajzkEI15sT1o4GUE5iOoaYPIhuxfTC75abe2g)

尝试用auto，连接超时
我是windows下用gpg-agent来替代ssh-agent的
windows系统下的ssh能正常依赖gpg-agent来登录的

**Comment by cweijan** [comment]
windows不计划支持, 无论是安装还是针对gpg-agen单独处理, 都太麻烦了.
