### ISSUE TITLE
[BUG]Data Edit 下 JSON Format 会导致 number 类型的 ID 丢失精度

### ISSUE THREAD

**Issue by Przeblysk** [cweijan/vscode-mysql#1035]
![CleanShot2024-01-29at10 06 48@2x](https://github.com/cweijan/vscode-database-client/assets/18001272/a6c06f47-df02-4ac7-835f-3cd9e0df3751)
如图所示

- Database type and version:Database Client v7.0.4

**Comment by cweijan** [comment]
你是指格式化后丢失了小数吗

**Comment by Przeblysk** [comment]
是的



---- 回复的原邮件 ----
| 发件人 | Weijan ***@***.***> |
| 日期 | 2024年02月04日 16:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [cweijan/vscode-database-client] [BUG]Data Edit 下 JSON Format 会导致 number 类型的 ID 丢失精度 (Issue #1035) |

你是指格式化后丢失了小数吗

**Comment by Przeblysk** [comment]
是最后两位精度没了都变成00了 因为js的number长度不够



---- 回复的原邮件 ----
| 发件人 | Weijan ***@***.***> |
| 日期 | 2024年02月04日 16:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [cweijan/vscode-database-client] [BUG]Data Edit 下 JSON Format 会导致 number 类型的 ID 丢失精度 (Issue #1035) |

你是指格式化后丢失了小数吗

**Comment by Przeblysk** [comment]
因为js的number长度不够



---- 回复的原邮件 ----
| 发件人 | Weijan ***@***.***> |
| 日期 | 2024年02月04日 16:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [cweijan/vscode-database-client] [BUG]Data Edit 下 JSON Format 会导致 number 类型的 ID 丢失精度 (Issue #1035) |

你是指格式化后丢失了小数吗

**Comment by cweijan** [comment]
谢谢反馈，我会在下版本修复



在 2024-02-04 17:37:52，Przeblysk ***@***.***> 写道：


因为js的number长度不够



---- 回复的原邮件 ----
| 发件人 | Weijan ***@***.***> |
| 日期 | 2024年02月04日 16:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [cweijan/vscode-database-client] [BUG]Data Edit 下 JSON Format 会导致 number 类型的 ID 丢失精度 (Issue #1035) |

你是指格式化后丢失了小数吗

**Comment by cweijan** [comment]
已在版本7.0.5修复.
