### ISSUE TITLE
set sql_mode=´´

### ISSUE THREAD

**Issue by grafenocarbono** [cweijan/vscode-mysql#1036]
Hello,

I would like to execute the sentence **set sql_mode=´´** in order to use functions (AVG, COUNT,....)  without GROUP BY.

I have gone the .vscode/extensions folder but I don't know that file json I have to modify.

I use the extension MySQL v 7.0.4 (Weijan Chen) for visual studio code :+1: 

Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:19.222Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.6.6-76060606-generic

Thanks in advance

**Comment by cweijan** [comment]
You can configure this in the advanced options in the connection panel.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/a6042eb2-4355-4087-a8d0-a21a93f0f18d)
