### ISSUE TITLE
[BUG] Error inserting a row when there is a column called 'database'

### ISSUE THREAD

**Issue by marcosgomesneto** [cweijan/vscode-mysql#1037]
- Database type and version:
MySql / MariaDB  (all versions)

The word `database` is reserved by Mysql, so to insert rows into tables that have a column named "database", you need to escape them using backticks (`).

The "Database MySQL Client" extension for Visual Studio Code currently encounters an issue when attempting to insert rows through the extension's user interface into a table that includes a column named "database." This error hinders the successful insertion of the row.

To solve the extension you need to escape reserved words with backticks (`).

**Comment by cweijan** [comment]
Thanks your feedback, I will fix it in the next version. For now, you can fix it by checking "Escaped all object name.".

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/43d1d8df-ea76-4597-be09-9899b1309e95)

**Comment by marcosgomesneto** [comment]
Great, thanks for the answer.

**Comment by cweijan** [comment]
Fixed in version 7.0.5.
