### ISSUE TITLE
[BUG] Column is not updated after ALTER COLUMN

### ISSUE THREAD

**Issue by vanngoh** [cweijan/vscode-mysql#1038]
- Database type and version: MySQL 8.2.0

I have successfully updated the column from `VARCHAR(10)` to `VARCHAR(20)` by using `alembic` migration tool.
But it's still showing `VARCHAR(10)` in this pluggin, and I have downloaded both MySQL Workbench and TablePlus for verification, both showed the latest `VARCHAR(20)`.

**Comment by cweijan** [comment]
If you have modified the table structure through other programs, you need to click the refresh button or restart VS Code to update.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/dc973fac-0602-4492-8f3b-6a1ca21fa9af)
