### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dfg727** [cweijan/vscode-mysql#1039]
Can not connect to mssql
![image](https://github.com/cweijan/vscode-database-client/assets/131731632/316e293e-65b8-4535-a571-6d2a4719c956)
- Database type and version:
mssql

**Comment by cweijan** [comment]
Uncheck "Encrypt".
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/866a0d89-cb22-41f8-8e1c-c82272d79ea0)

**Comment by dfg727** [comment]
:heartbeat:  it's success when i checked Encrypt.Thanks
