### ISSUE TITLE
[BUG] Unable to connect to ipv6 only SSH service

### ISSUE THREAD

**Issue by dark2star** [cweijan/vscode-mysql#1040]
- Database type and version:
ssh 连接  v7.0.4

使用ssh 连接仅IPv6支持的域名时无法正常连接，用ssh 工具termius连接则可以正常使用

**Comment by cweijan** [comment]
谢谢反馈, 我会尝试支持Ipv6

**Comment by cweijan** [comment]
我测试了两台ipv6的机器, ipv6是可以正常连接的. 你的连接场景是什么呢?
