### ISSUE TITLE
[BUG] Can't copy integer cell to clipboard

### ISSUE THREAD

**Issue by GTonehour** [cweijan/vscode-mysql#1041]
In the result view, when I right-click a cell and choose "Copy", it works in general. But when it's an integer, it doesn't seem to set anything to the clipboard.

![2024-02-03_18h15_38](https://github.com/cweijan/vscode-database-client/assets/86954612/d6951940-d00f-426d-addb-43cc9b00411e)

- PG 15
- v7.0.4
- Windows

**Comment by cweijan** [comment]
Thanks feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed in version 7.0.5.
