### ISSUE TITLE
Better UI for filtering

### ISSUE THREAD

**Issue by digital-cuttlefish** [cweijan/vscode-mysql#1042]
Hello!
Great plugin, thanks for the good work.
I've noticed that you've given us a way to filter the tables and views that we see on the sidebar. However, its a little cumbersome to use: I have to click on the filter button, make a query, press Enter, then see the changes. Even then, it's also only for that specific schema, not global.

The company I work for has a lot of tables and it'd be useful to have a more quicky accessible and editable filter feature to find certain tables.

Could you please add a little search bar at the top of the sidebar that acts as a global filter across schemas? It would be helpful if it filters as we type as well.

**Comment by cweijan** [comment]
I think you are referring to global search of data in all tables. I have plans to launch it, but because it requires a new UI interface, it will not be launched so soon.

**Comment by digital-cuttlefish** [comment]
I'm not specifically looking for global search of data _within_ tables, but rather being able to search for tables by name easier.
This would help with my workflow a lot so if you need help implementing it, i can assist.

**Comment by cweijan** [comment]
Try this.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/806acf7d-0796-4268-a873-cc66b24fd11b)

**Comment by digital-cuttlefish** [comment]
Yes, this is what I was taking about. I find this way of doing it cumbersome. I'd prefer it to be a persistent search bar at the top the sidebar, instead of that button i have to keep pressing

like this:
![image](https://github.com/cweijan/vscode-database-client/assets/141751473/fdcc2ce3-0362-4d1b-8a5f-2b68740c6359)

It's an ugly preview but you can see what I mean now right 😄
If it's up here and does the filtering as we type (like most search bars in VS code), it would make things much faster

**Comment by cweijan** [comment]
You can press ctrl+f to search and then filter, this is the only method provided by vscode.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/0e7a7e06-7b6d-4891-885a-d594f6593be1)

**Comment by digital-cuttlefish** [comment]
Wait wait sorry I still have some followup questions!

> his is the only method provided by vscode.

What do you mean by this though? Other sidebars have thier own search bar the top that can filter things that's separate from the ctrl+f feature
![image](https://github.com/cweijan/vscode-database-client/assets/141751473/4be08ea1-9ea2-45ab-8289-82735af941e2)

I think making one like this would be better, especially since if you use the crtl+f serachbar, you still have to scroll down to find the matches since it doesn't actually filter anything.

**Comment by cweijan** [comment]
Unfortunately, vscode does not provide input boxes to the extension tree view API.

https://github.com/microsoft/vscode/issues/161753
