### ISSUE TITLE
Postgres scripts with unsorted order in database client

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#1043]
## Bug Report for database client

**Title:** Postgres scripts with unsorted order in database client

**Description:**

When using the VS Code extension to generate postgres scripts from two different databases, different scripts are generated for each database, even though the structure of both databases is the same.

**Steps to Reproduce:**

1. Open VS Code.
2. Navigate to postgres connection.
3. Right-click on both postgres database and select the "Dump Struct" option from the database menu.
4. Review the generated scripts.

You will see that the generated scripts for the two databases have different orders, even though the structure is the same.

**Cause:**

This issue is because the database client uses the order of table creation in the postgres database to generate the script.

**Proposed Solution:**

It is suggested that the database client uses the order of **table names** instead of the order of table creation to generate the script. This will ensure that the generated scripts for two databases with the same structure have the same order.

**Considerations:**

* This issue only occurs when tables are created in a different order in the two databases.
* Using the order of table names to generate the script makes it easier to read and compare scripts.

**Request:**

Please add the order of table names as an option for generating scripts in the database client.

**Additional Information:**

* **Extension version:** 
Version: 1.85.2 (system setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19044
* **VS Code version:** 7.0.4 2024-1-24

**Thank you**

Thank you for your attention to this bug report. We hope that you will resolve this issue as soon as possible.

```sql
select *
from pg_catalog.pg_class c
    join pg_catalog.pg_namespace n on n.oid = c.relnamespace
    join pg_catalog.pg_attribute a on a.attrelid = c.oid and a.attnum > 0
    join pg_catalog.pg_type t on a.atttypid = t.oid
where n.nspname = 'ahe_s'
order by c.oid
```
convert to this :

```sql
select *
from pg_catalog.pg_class c
    join pg_catalog.pg_namespace n on n.oid = c.relnamespace
    join pg_catalog.pg_attribute a on a.attrelid = c.oid and a.attnum > 0
    join pg_catalog.pg_type t on a.atttypid = t.oid
where n.nspname = 'ahe_s'
order by c.relname
```

**Comment by mbtolou** [comment]
sample test senario :

Script of first database :
```sql
CREATE TABLE backup.ztest_table_one(
    id int8 NOT NULL,
    title_txt varchar NOT NULL
);

CREATE TABLE backup.ztest_table_two(
    id int8 NOT NULL,
    title_txt varchar NOT NULL
);



ALTER TABLE backup.ztest_table_two
ALTER COLUMN id
ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME backup.ztest_table_two_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
```



Script of second database :
```sql
CREATE TABLE backup.ztest_table_one(
    id int8 NOT NULL,
    title_txt varchar NOT NULL
);

CREATE TABLE backup.ztest_table_two(
    id int8 NOT NULL,
    title_txt varchar NOT NULL
);



ALTER TABLE backup.ztest_table_two
ALTER COLUMN id
ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME backup.__ztest_table_two_id_seq START
    WITH
        1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
```

**Comment by cweijan** [comment]
Hi, the sorting of pg_dump is uncontrollable, but the version 16 table names of my pg_dump on Windows will dump in order. You can try to upgrade your pg_dump.
