### ISSUE TITLE
connect to SQL Server using Windows Authentication without keep entering password

### ISSUE THREAD

**Issue by mckfc** [cweijan/vscode-mysql#1044]
Hi,

In my organization the only way to connect to our internal MS SQL server is by windows authentication rather than username/password. 

The current "Connect to server" feature already providing a "NTLM (Windows Auth)" option which is great. but as a lazy worker I really hate to keep entering password every time connecting to saved db server. so is there a way to allow connect to database with windows auth without entering username/password? 

Thank you.

**Comment by cweijan** [comment]
Hi, what do you mean by entering a password? By default the extension will always save the username and password.

**Comment by mckfc** [comment]
I think it's because of this:
![image](https://github.com/cweijan/vscode-database-client/assets/1018313/fc2e7375-f02b-4b21-bd19-dc01bc33673a)

Well I think my true expectation is not to enter username/password at all when the Windows Auth option is selected since I've signed in with my domain account already. 
![image](https://github.com/cweijan/vscode-database-client/assets/1018313/fe2a2d83-2945-4118-b536-b429c8e98bde)

**Comment by cweijan** [comment]
Hi, this is not possible. The extension is written using node.js and cannot obtain the windows credentials.

**Comment by mckfc** [comment]
I see. no worries then. thank you.
