### ISSUE TITLE
[BUG] Autocompletions are not working properly

### ISSUE THREAD

**Issue by anvesh9652** [cweijan/vscode-mysql#1048]
Database type and version:
- Postgres and 16-bullseye (docker image)

I noticed that quick suggestions are working in a weird way at some places for Postgres.

I have two tables: dummy and dummy2.

1. No table suggestions for the `truncate` command.

	<img width="843" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/83718454/1f2704d3-87ba-41f9-87f5-3a8eefcbdeb6">

2. No suggestions for Common Table Expressions (CTE) created with the "WITH" clause.

	<img width="755" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/83718454/75bcd1a6-58eb-4538-b476-542276c58c29">

3. Continuing from 2nd point, in the SELECT statement, no suggestions were showing for table columns after a comma; instead, it is suggesting other table names.

	 <img width="701" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/83718454/252abc0e-4429-4615-8341-616bb3bf2911">

   However, if don't add a comma, it is suggesting column names

	 <img width="757" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/83718454/46f02da5-6afc-492f-a97b-33d9d73af684">

**Comment by cweijan** [comment]
Thanks feedback, I will fix the points you mentioned in future versions.

**Comment by cweijan** [comment]
Fixed in version 7.4.5.
