### ISSUE TITLE
[BUG] Adds an invalid LIMIT clause in CTE UPDATE

### ISSUE THREAD

**Issue by GTonehour** [cweijan/vscode-mysql#1049]
This kind of queries fail with an invalid LIMIT syntax, that seems to be added by your extension.

![image](https://github.com/cweijan/vscode-database-client/assets/86954612/9853b296-7f69-43ad-924e-1585093fbf80)

- PG 15.3
- v7.0.4
- Windows

**Comment by cweijan** [comment]
Thanks feedback, I will fix it in the next version. You can currently handle it by disabling automatic paging.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/b3da4ba7-3e5a-4c8f-8d1e-3b8636455246)

**Comment by cweijan** [comment]
Fixed in version 7.0.5.
