### ISSUE TITLE
[BUG] SSH - No Active Connection Found

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#1050]
- Database type and version:
MySQL

When connected to a server where MySQL DB is hosted through SSH, I am getting the error No Active Connection Found while executing queries

The connection was successful and it is listing all users in the DB while connecting the DB.  

In between one or two times, I got the connection and was able to execute queries.  Most of the time the message No Active Connection found message is coming.  In the taskbar of VS Code also, the connection details are displayed. In the mean time, I can access all the files of MySQL server through VS Code

**Comment by cweijan** [comment]
Hi, what is the network condition of the SSH server you are connected to? Maybe the connection was killed due to unstable network.

**Comment by franklinkf** [comment]
Sir,

The network condition is very stable.  Now I checked from my home network also.  Not working. Same error coming

**Comment by franklinkf** [comment]
Got the issue.

In the first line of my file the below line exists, due to which the error is coming. When I removed it, it is working

-- Active: 1669965190436@@192.168.1.249@3306@cbs_annex

Sorry to trouble you.

Regards

Franklin

**Comment by cweijan** [comment]
Thanks feedback!
