### ISSUE TITLE
Mongodb Data Views

### ISSUE THREAD

**Issue by melihkucuknazli** [cweijan/vscode-mysql#1053]
As in Robo 3T, this plugin should also have the option of displaying the backs. The data should be shown in whichever view was set last time, and the data should be shown in whichever view was set last time when the next query or program is opened.

Robo 3T or Studio 3T programs have these features. You can take these programs as reference.
In addition, I share what I am talking about visually below.

<img width="1284" alt="Ekran Resmi 2024-02-22 21 39 37" src="https://github.com/cweijan/vscode-database-client/assets/22034296/bbe67f16-e53e-4444-a075-21d6a4298bb6">
<img width="1314" alt="Ekran Resmi 2024-02-22 22 00 19" src="https://github.com/cweijan/vscode-database-client/assets/22034296/221f8c34-0b59-476d-b6d5-681d7293ea66">
<img width="1234" alt="Ekran Resmi 2024-02-22 22 01 13" src="https://github.com/cweijan/vscode-database-client/assets/22034296/ec1d2e05-9765-4cfb-8788-f96f1b8b9997">

**Comment by cweijan** [comment]
In the latest version, you can now click the expand button to expand the data in a tree mode.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/2b817eaa-c3ce-463b-bb28-0f2eccfd1afc)
