### ISSUE TITLE
Table view: Default-Reverse shortcut combine key

### ISSUE THREAD

**Issue by melihkucuknazli** [cweijan/vscode-mysql#1054]
I usually use Reverse view and it is really tiring to click and change this button with the mouse after each query. I defined a shortcut in datagrip as Shift+Cmd+P key combination. There should be such an option in this plugin. We should be able to define shortcuts with the key combinations we want.

**Comment by cweijan** [comment]
Thanks for the feedback, I will try to add shortcut keys for it in the next version, and you can add \G after SQL, then the data will be automatically reversed.

**Comment by Thomas-JiangWu** [comment]
Also want such a shortcut. DBeaver has a default `Tab` shortcut for the Reverse view, which I used frequently.

**Comment by cweijan** [comment]
@Thomas-JiangWu , tab is a good suggestion, I have supported it in version 7.5.5.

**Comment by Thomas-JiangWu** [comment]
> @Thomas-JiangWu , tab is a good suggestion, I have supported it in version 7.5.5.

Thank you! You made a wonderful extension. I switched from DBeaver to this extension and I enjoy using it so far.

**Comment by brunolamegolino** [comment]
> @Thomas-JiangWu , tab is a good suggestion, I have supported it in version 7.5.5.

Is it possible to remove this shortcut local?
It interferes with switching tabs, I use "CTRL+TAB" to switch tabs in the editor. I use a single editor window

**Comment by cweijan** [comment]
@brunolamegolino Thanks for reporting, this issue has been fixed in version 7.6.0.

**Comment by qqwqert007** [comment]
@cweijan I found that the Reverse view didn't support field update, and I can only update fields in Default view. I wonder if the field update can be supported in Reverse view?
