### ISSUE TITLE
[BUG]Hive Connection error

### ISSUE THREAD

**Issue by changyuanxu** [cweijan/vscode-mysql#1055]
Connection error!
java.lang.RuntimeException: org.apache.hive.service.cli.HivesOLException: COMPILE FAILED: Parse error: (Error 1101)
line 1:7 cannot recognize input near '1' in statement

**Comment by cweijan** [comment]
In the old version, the extension verifies the Hive connection by executing `select 1`, which has been changed to "SHOW DATABASES" in the new version to fix this.
