### ISSUE TITLE
[BUG] AffectedRows Returns 0 Despite Successful Row Updates in Version 7.0.6

### ISSUE THREAD

**Issue by ViniciusResendeDaCruz** [cweijan/vscode-mysql#1057]
![image](https://github.com/cweijan/vscode-database-client/assets/102707525/5e9c0415-48e7-4442-88e5-d907cc2085dd)

I've encountered an issue with the version 7.0.6 (released on 2024-02-24) where, after executing an UPDATE SQL command, the `AffectedRows` property incorrectly reports 0, even though the operation successfully modifies a significant number of rows in the database. This behavior is consistently observed across different queries that should affect multiple rows. 

I have confirmed that the database itself is correctly processing the UPDATE commands by verifying the data before and after the operations.

Could you please investigate this discrepancy? Let me know if you need any further information or logs that could assist in resolving this issue.

**Comment by cweijan** [comment]
What database are you using? AffectedRows works fine for me.

**Comment by ViniciusResendeDaCruz** [comment]
> What database are you using? AffectedRows works fine for me.

I'm using SQL Server

**Comment by cweijan** [comment]
Fixed in version 7.1.1.
