### ISSUE TITLE
Is there a keybinding to execute the current sql code block?

### ISSUE THREAD

**Issue by SebastianBehrens** [cweijan/vscode-mysql#1059]
Is there a keybinding to what clicking on "Execute" does?
<img width="319" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/51058351/d7797eef-2448-4f28-a385-15b627350ea0">

**Comment by cweijan** [comment]
Hi, the default shortcut key is ctrl/cmd+enter. I think this shortcut key is assigned to other functions. You need to configure the execution shortcut key again.
```json
{
                "command": "mysql.runSQL",
                "key": "ctrl+enter",
                "mac": "cmd+enter",
                "when": "editorLangId == sql"
 }
```

**Comment by SebastianBehrens** [comment]
Right, thank you!
Why does it say mysql, even though this is the keybinding for ".sql" files that are not necessarily mysql files?
