### ISSUE TITLE
Font size to use default vscode configuration

### ISSUE THREAD

**Issue by vavrecan** [cweijan/vscode-mysql#1060]
It would be best to use 

    font-family: var(--vscode-font-family);
    font-weight: var(--vscode-font-weight);
    font-size: var(--vscode-font-size);

rather than setting static font size.

**Comment by vavrecan** [comment]
https://github.com/search?q=repo%3Acweijan%2Fvscode-database-client%20font-size&type=code :/

**Comment by vavrecan** [comment]
created at least basic pull request to address font issue

**Comment by vavrecan** [comment]
Oh. I see that the library is also using some package https://github.com/u-fish-bubble/umy-ui/ to render tables. It seems to be Chinese only and I am not quite sure if its even possible to override font size there :D Well, hopefully it will get improved :) thank you!

**Comment by cweijan** [comment]
Thanks for the feedback, I will try this proposal.

**Comment by cweijan** [comment]
Adapted to vscode font in version 7.0.9.
