### ISSUE TITLE
[BUG] Postgre - Connection error!database "<user>" does not exist

### ISSUE THREAD

**Issue by kostejnv** [cweijan/vscode-mysql#1063]
I am attempting to connect to a PostgreSQL database using an SSH tunnel. It appears that all the fields are filled correctly, but I encounter an error: "Connection error! The database "<username>" does not exist!" I have only entered the <username> in the Username field, and in the Database field, I have provided the actual database name. However, it seems that the client is not recognizing this field.

- Database type and version: PostgreSQL

**Comment by cweijan** [comment]
It seems that your database or user configuration is entered incorrectly. You can try using other credentials or other postgresql connection tools.
