### ISSUE TITLE
How is the password encrypted?

### ISSUE THREAD

**Issue by peechyfloof** [cweijan/vscode-mysql#1064]
When I save the configuration to a workspace, a database-client-config.json with all information is created.  
When I save the password inside the connection, it is saved to the json file too, but it seems to be kind of encrypted?

How does this encryption work?
We have multiple users that will use the same connections. The best way would be to NOT save the password inside the json file (Which will be in the git repo) and make every user enter the password one time which will then be saved somewhere on the drive or whatever with a private key.

Back to my question:
- Who can read the saved password?
- Which algorythm is used?
- Where are any private keys stored
- Is the key shared in any way? It must be otherwhise, other people could not use the workspace-saved connections without always setting the  password

**Comment by cweijan** [comment]
In the previous version, the password for the workspace connection was in clear text, which caused complaints from users.

So now the password will be AES encrypted, just a basic layer of protection, it will only be read by the Database Client.

**Comment by peechyfloof** [comment]
Thank you for your response!
This means ANYBODY can read this by just installing the extension, right?

Is there any plan to encrypt it with a locally saved key inside the user data so its not readable for anyone with access to the git repo and the free extension?

**Comment by cweijan** [comment]
Thanks for the advice, I will try to increase the encryption level in the future.
