### ISSUE TITLE
[BUG] Syntax error when updating an interval with UI

### ISSUE THREAD

**Issue by GTonehour** [cweijan/vscode-mysql#1066]
When changing an interval value from the UI, a syntax error happens on commit.

![2024-03-03_18h29_01](https://github.com/cweijan/vscode-database-client/assets/86954612/ec315512-d797-4441-9b0a-ad1b1b8c637a)

- PG 15.3
- v7.0.7
- Windows 11

**Comment by cweijan** [comment]
Thanks for the feedback. interval is a type I don’t know. I will adapt it in the next version.

**Comment by cweijan** [comment]
Fixed in version 7.1.0.
