### ISSUE TITLE
[BUG] Disable automatic escaping for backslash '\' in field values

### ISSUE THREAD

**Issue by m0nochr0me** [cweijan/vscode-mysql#1067]
Backslash is being escaped every time upon saving: \ -> \\ -> \\\\ -> ...

Thank you!

![image](https://github.com/cweijan/vscode-database-client/assets/31232338/8bfecb31-21b1-4664-9903-38bbe41bd01c)
![image](https://github.com/cweijan/vscode-database-client/assets/31232338/0c9e4e7f-4b06-4f77-a323-36a10c5b30a7)

- Database type and version:
Database Client v7.0.9
PostgreSQL 11

VSCode:
Version: 1.86.2
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:41:37.860Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.7.6-arch1-1

**Comment by cweijan** [comment]
Thanks feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed in version 7.1.0.
