### ISSUE TITLE
[BUG] cannot access into RDS with IAM authentication token

### ISSUE THREAD

**Issue by pyq** [cweijan/vscode-mysql#1068]
I am trying to use the **database client** to login our database in `AWS RDS` which is using **IAM authentication**. However, it is not working even though I manually copy those generated tokens in required fields in **add connection** section

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.AWSCLI.html

- Database type and version:
[AWS RDS](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.Connecting.AWSCLI.html)
Server version: 8.0.23 Source distribution

Can you help to guide how I can connect the RDS with such authentication.

**Comment by cweijan** [comment]
Thank you for your feedback. I will try to support this connection method. What is your database service type?

**Comment by cweijan** [comment]
Hi, I created an aws mysql. By checking SSL, I was able to successfully connect using IAM Token.

<img width="1041" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/27798227/84aef650-4108-4114-829d-b10300cdc3af">
