### ISSUE TITLE
[BUG] - Very inefficient query use for counting rows in MySQL

### ISSUE THREAD

**Issue by PCreations** [cweijan/vscode-mysql#1070]
- Database type and version: MySQL 5.5

Hello,

We are using a very old version of MySQL, we have huge tables with dozens of millions of rows.

When clicking on a table, the tools make a very inefficient query : 
```sql
SELECT count(*) count
                FROM (SELECT * FROM appels_in
) temp;
```

It took 425 seconds !

Why not simply use a simple SELECT COUNT(*) FROM ?

**Comment by cweijan** [comment]
Thanks for the feedback, it has been fixed in version 7.1.0, now the subquery count will no longer be used for simple queries.
