### ISSUE TITLE
Support for libSQL 

### ISSUE THREAD

**Issue by tdortman** [cweijan/vscode-mysql#1071]
At the moment the only way to add a sqlite database is via a file local file, but we now have also have [libSQL](https://github.com/tursodatabase/libsql) which essentially allows you to interact with a sqlite database over the network. 

With providers like [turso](https://turso.tech/) getting more popular it would be a shame not to be able to interact with those databases via this client. Especially since one should be able to reuse most of the code that's already there for sqlite.

**Comment by cweijan** [comment]
Thanks for the feedback, I will try to support libsql, but since the sdk of libsql is not cross-platform, it will not be completed in a short time.

**Comment by cweijan** [comment]
LibSQL (Turso) has been supported in version 7.2.8. 

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/8611ce89-3fac-455b-8020-e6566fe35518)

To obtain the connection token, please refer to: https://docs.turso.tech/sdk/http/quickstart
