### ISSUE TITLE
Case sensitivity of the Filter

### ISSUE THREAD

**Issue by Frogley** [cweijan/vscode-mysql#1073]
Database: MS SQL Server 2019

Currently, when filtering tables and views using the Filter, it is case-sensitive. However, in my scenario, the database's collation(Chinese_PRC_CI_AS) is case-insensitive. There are mixed-case usage when creating tables. For example, there are three tables: TIN_Collection, tin_collection_getin, and TIN_Conserve, currently it's not possible to filter out these three tables at the same time.

Suggestion: Is it possible to provide some form for users to toggle case sensitivity? Or decide the case sensitivity based on the database's collation?

Additionally, unless I'm mistaken, there currently isn't a filter feature for stored procedures and functions. Is there any plan to incorporate this feature in the future?

数据库：MS SQL Server 2019

目前使用过滤器对表和视图进行过滤时，是大小写敏感的。但我这边的情况是，数据库的collation(Chinese_PRC_CI_AS)是大小写不敏感的。建表的时候也有大小写混用的情况。例如有三张表TIN_Collection、tin_collection_getin和TIN_Conserve，目前无法把这三张表同时过滤出来。

建议：能否以某种形式提供让用户切换大小写敏感的开关。或者根据数据库的collation来决定大小写敏感。

另外，如果我没弄错的话，存储过程和函数是没有Filter的，后续是否考虑加上这部分功能呢？

**Comment by cweijan** [comment]
已在版本7.1.0修复, 表名搜索是不需要区分大小写的, 之前没注意到这一点.

**Comment by Frogley** [comment]
赞！
