### ISSUE TITLE
SSH Agent from Password Managers

### ISSUE THREAD

**Issue by jochman** [cweijan/vscode-mysql#1074]
Hey, I'm using a password manager that supply an ssh-agent. The extension is unable to use that ssh agent.

Is there any way to configure it?

**Comment by cweijan** [comment]
Try to use auto to connect SSH, which will automatically use the agent.

<img width="728" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/27798227/fe811c11-97d5-407f-9919-e0b67434d7a7">

**Comment by jochman** [comment]
I tried it already and got `Connection error!All configured authentication methods failed`.

I have configured a default host * to use that ssh-agent.

**Comment by cweijan** [comment]
Fixed in version 7.1.1.
