### ISSUE TITLE
[BUG]AffectedRows is always 0 in SQL Server

### ISSUE THREAD

**Issue by Frogley** [cweijan/vscode-mysql#1075]
- Database type and version: MS SQL Server 2019

- When I perform operations in MS SQL Server 2019, the returned AffectedRows is always 0. For example:

  - Insert: 

  <img width="257" alt="ba139e0df3e398fec358c43c6af59bb" src="https://github.com/cweijan/vscode-database-client/assets/47624001/67a8354f-834c-415e-b95a-3ae13ed5ec59">

  - Data has been successfully inserted: 
  <img width="239" alt="d8fc2f0660b6b613326f53a1cad0e2f" src="https://github.com/cweijan/vscode-database-client/assets/47624001/98faeee2-c305-469f-a96b-291cb7047d7b">

  - Similarly, Update:
  <img width="287" alt="b86eec717b33e523db2307b263268a1" src="https://github.com/cweijan/vscode-database-client/assets/47624001/f849994d-3627-44a8-8f46-81c3ec8aa1ff">

  - Delete:
  <img width="210" alt="d8e9fe3885db8761877aa360eb23c6d" src="https://github.com/cweijan/vscode-database-client/assets/47624001/2323df75-9ae5-455b-86b5-e18546b7aaac">

**Comment by cweijan** [comment]
Thanks feedback, this problem will be fixed in the next version.

**Comment by cweijan** [comment]
Fixed in version 7.1.1.

**Comment by Frogley** [comment]
Now it works fine, thank you!
