### ISSUE TITLE
[BUG] error: syntax error at or near "\"

### ISSUE THREAD

**Issue by blk-raffy** [cweijan/vscode-mysql#1076]
- Database type and version: Postgresql 16.2

2 postgresql db 16.2, if I dump the data and import it to another db with same version, I receive the error:
```error: syntax error at or near "\"```

I have the last version of the extension, didn't touch the exported data

**Comment by cweijan** [comment]
Hi, tried version 7.1.1, will now always use psql to import SQL.

**Comment by cweijan** [comment]
If you are using a windows system, pg_dump can be downloaded automatically after version 7.1.2.

**Comment by blk-raffy** [comment]
Nice thank you so much, glad to pay the plan 🙏
