### ISSUE TITLE
Disable Autocomplete in Comments

### ISSUE THREAD

**Issue by ptyork** [cweijan/vscode-mysql#1077]
Apologies if I'm missing a setting somewhere, but is it possible to disable autocomplete in comments? As a teacher, I write a LOT of comments (and expect my students to do so, as well). The autocomplete suggestions are not appropriate in comments and can really hamper productivity.

I don't want to change activation triggers globally as autocomplete is quite helpful in the SQL itself.

Thanks!

**Comment by cweijan** [comment]
Thanks for the feedback. SQL completion should not be done in comments. I have disabled it in version 7.1.1.
