### ISSUE TITLE
[BUG]Redis客户端数据显示错误

### ISSUE THREAD

**Issue by MagicYang** [cweijan/vscode-mysql#1078]
- Database type and version: v7.1.1

通过Redis客户端（图1）查看数据，Long型数据与真实值少了4，换其他客户端（图2）能正确显示

图1：
![WechatIMG47](https://github.com/cweijan/vscode-database-client/assets/639319/d44cef88-bb1a-4a94-9b2c-18daa43d959d)

图2：
![WechatIMG48](https://github.com/cweijan/vscode-database-client/assets/639319/d6dd9ec2-e9ad-4f39-ab0e-58ef420da885)

**Comment by cweijan** [comment]
谢谢反馈, 会在下个版本修复.

**Comment by cweijan** [comment]
已在7.1.2版本修复.
