### ISSUE TITLE
cannot coonnect to postgres database on render

### ISSUE THREAD

**Issue by petre-enciu** [cweijan/vscode-mysql#1082]
I get theis message:
Connection error!read ECONNRESET

**Comment by cweijan** [comment]
Please try to enable SSL, or check whether the service is started correctly.

**Comment by petre-enciu** [comment]
I got the same error. Actually:
 1. when i try to connect using url string SSL enabled I get: Connection error!read ECONNRESET
 2. when i try to connect with host/user/password/port SSL enabled I get: database "mysite" does not exist (mysite is the username)

**Comment by cweijan** [comment]
Hi, this seems to be able to connect to the database, try correcting your database.

**Comment by petre-enciu** [comment]
There's a problem with the connection. the username is "mysite"

![Screenshot 2024-03-21 090051](https://github.com/cweijan/vscode-database-client/assets/17352332/8d57510e-85a3-4e6f-a3c4-fd7bec92af26)

**Comment by cweijan** [comment]
Thanks feedback. The database parameters are lost. I will release a new version to fix it as soon as possible.

**Comment by cweijan** [comment]
Is this connection string not empty? If not empty, the database parameters will be cleared.

<img width="978" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/27798227/ee385e31-0f28-48b1-ba7a-bf0028fb8651">

**Comment by petre-enciu** [comment]
I have enabled url string -> i have removed the string form  the text field ->i have disabled Url string -> I have saved everything -> Connect -> got the same error: Connection error!database "mysite" does not exist

**Comment by cweijan** [comment]
This is strange. Please try to open a new connection page connection, or modify the database parameters.

**Comment by petre-enciu** [comment]
It worked, after I have recreated a new connection. Thanks

**Comment by cweijan** [comment]
Thanks feedback, I will check why the database parameters are losing.
