### ISSUE TITLE
[BUG] Filter function not working

### ISSUE THREAD

**Issue by ch-qwe** [cweijan/vscode-mysql#1087]
Previously, when using the filter function, the query would automatically include %SearchValue%. However, this seems to be missing now, and the filter function is no longer working as expected.

#### PREVIOUS
![image](https://github.com/cweijan/vscode-database-client/assets/45938634/797aaaaa-6491-4ec2-bd17-05388502bc30)
#### NOW
![image](https://github.com/cweijan/vscode-database-client/assets/45938634/09e63946-af22-4c21-8c93-c3ef97340774)

- Database type and version: v1.3.4

**Comment by cweijan** [comment]
filter has been fixed in version 7.1.6.
