### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by m15ha** [cweijan/vscode-mysql#1089]
Could you please add a separate font size configuration? After one of the updates, the default font size became the same as in VS code, which makes the layout in tables uncomfortable. So, the font size becomes big, but the layout stays the same.

**Comment by cweijan** [comment]
Thanks feedback! I will no longer follow VS Code fonts in the next version, and add independent font settings.

**Comment by Ansave** [comment]
Same problem.
The ability to edit the font size would be very helpful.

![Снимок экрана 2024-04-01 223533](https://github.com/cweijan/vscode-database-client/assets/47891365/23b3f73a-bb59-4807-96ff-44375f7abe9c)

**Comment by mercurykd** [comment]
> Thanks feedback! I will no longer follow VS Code fonts in the next version, and add independent font settings.

The font is now very large. where can I change it now?

**Comment by cweijan** [comment]
Thanks for the feedback, I've released version 7.1.8, falling back to following VS Code's font sizes, custom font sizes will be supported in the future.

**Comment by cweijan** [comment]
Configurable font size has been supported in version 7.2.0.

<img width="942" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/27798227/784e183a-4af7-4075-9c82-f5713bbde526">
