### ISSUE TITLE
[BUG] Result maximum column width

### ISSUE THREAD

**Issue by m15ha** [cweijan/vscode-mysql#1090]
Can you please look into fixing the 'Result maximum column width' feature? It seems to be malfunctioning and not working as intended. Thank you.

**Comment by cweijan** [comment]
Thank you for your feedback, the view interface is being redesigned and will be supported in future versions.

**Comment by cweijan** [comment]
The maximum column width has been improved in version 7.3.1.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/8c5ebfc4-31e6-48f1-9ccb-f793175269bf)
