### ISSUE TITLE
Show error line

### ISSUE THREAD

**Issue by alper-turkmen** [cweijan/vscode-mysql#1091]
Can we add error line number like in PgAdmin?
Now, the error does not include which line has error.

<img width="768" alt="Screenshot 2024-03-31 at 14 24 33" src="https://github.com/cweijan/vscode-database-client/assets/25075594/03679234-4c16-461d-a0de-6ab9b4d8c395">

**Comment by cweijan** [comment]
Thanks for the feedback, I will try to support it in future versions.

**Comment by cweijan** [comment]
Support in version 7.2.1.
