### ISSUE TITLE
[BUG] For auto-completion, the tables are not always visible

### ISSUE THREAD

**Issue by Ansave** [cweijan/vscode-mysql#1092]
Problem: For auto-completion, the tables become visible only after being mentioned in the `FROM `statement.

![image](https://github.com/cweijan/vscode-database-client/assets/47891365/9148f0ad-29d4-4d48-8152-8bc4a0a229fe)
![image](https://github.com/cweijan/vscode-database-client/assets/47891365/b128e45e-54a0-4cdd-8236-797755db29db)

The ability to auto-complete tables in `SELECT` statement  would be very useful, because:
1. Fields are usually specified in the format `table_name.field_name`
2. `SELECT `statement is written before `FROM `statement

Additionally, sometimes even after mentioning the table in `FROM`, table remains invisible to the autocomplete for some reason.

![image](https://github.com/cweijan/vscode-database-client/assets/47891365/f121be07-8355-4786-85be-3aec2494f134)

- Database type and version: MySQL 8.0

**Comment by cweijan** [comment]
Thanks for the suggestion! I will support it in future versions.

**Comment by cweijan** [comment]
Supported in version 7.3.3.
