### ISSUE TITLE
i cannot see my submited data, it doesnot safe [BUG]

### ISSUE THREAD

**Issue by Justina2-tech** [cweijan/vscode-mysql#1093]
- Database type and version:

**Comment by cweijan** [comment]
Hi, please describe your problem in detail.

**Comment by Justina2-tech** [comment]
i have migrated my form on django admin using vs code after submitting the form i cannot see the inputted data on the form just only the form details that is seen

**Comment by Justina2-tech** [comment]
SQlite
db.sqlite3

**Comment by cweijan** [comment]
I have never used django admin. What do you mean by "submitting form"? You'd better give a screenshot.
