### ISSUE TITLE
Not possible to use 2 differents ports at the same time?

### ISSUE THREAD

**Issue by GreenFlag31** [cweijan/vscode-mysql#1094]
Hi Chen,

First of all, thank you for your extension. I have a little question: is it not possible to set 2 connections open in the same time using different ports? 

In my.ini, the SQL configuration file, if I add a new connection on 3307:
![image](https://github.com/cweijan/vscode-database-client/assets/84795623/82b673f9-be85-475e-a6a9-6b4c102837ce)

Then the 3307 works, but the 3306 is not working anymore (and the database on 3306 got migrated to 3307).

If it's possible, how to achieve this?

Thank you

**Comment by cweijan** [comment]
Hi, as far as I know it is not possible, a service can only be bound to one port.
