### ISSUE TITLE
Ability to view text logs from server

### ISSUE THREAD

**Issue by alancnet** [cweijan/vscode-mysql#1095]
I depend on logging for debugging procedures, such as:

```sql
raise notice 'Hello World';
select * from mytable;
raise notice 'Foo Bar';
```

As far as I can tell, there is no way to view these logs.

**Comment by cweijan** [comment]
Thanks for the feedback, I will support it in the next version.

**Comment by cweijan** [comment]
Supported in version 7.3.2.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/c12a9193-400a-41b2-aae0-df5dc6bca011)
