### ISSUE TITLE
[BUG] Viewing table content with longblobs from Amazon RDS MySQL

### ISSUE THREAD

**Issue by rbouhal** [cweijan/vscode-mysql#1096]
I have an Amazon RDS MySQL database (version: 8.0.35) with a table that has two longblob atributes along with other attributes. But when data is entered into that table (especially the longblob data) the table takes a long time to view from this extension and this extension ends up crashing. I am on the free tier but i have been able to see entries with longblob data before, but after it is recently inserted it crashes the extension.

**Comment by cweijan** [comment]
Thanks for the feedback, I will improve support for binary types in the latest version.

**Comment by cweijan** [comment]
Try version 7.2.0, binary data is no longer loaded.
