### ISSUE TITLE
[BUG] Error when editing line in view

### ISSUE THREAD

**Issue by brunolamegolino** [cweijan/vscode-mysql#1097]
- Database type and version: MYSQL 5.6
- Database Client v7.2.0

I define the current connection, make a query (with or without filter) and try to edit a line and get this error

![image](https://github.com/cweijan/vscode-database-client/assets/25511732/207b6e9b-e8e9-4ba2-a478-78f575298440)

**Comment by cweijan** [comment]
Thanks feedback! Currently, SQL with comments cannot be parsed correctly. I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed in version 7.2.1.
