### ISSUE TITLE
Is there a way to export the query's result to a csv file

### ISSUE THREAD

**Issue by mty713** [cweijan/vscode-mysql#1099]
Thanks.

**Comment by cweijan** [comment]
Exporting is only available to paid users, but you can range-select cells to copy.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/e1af5b73-9bca-4b65-95a1-0214eba826e3)

**Comment by VCOSTA-Dev** [comment]
How can I export all query results to CSV, not just the first 100?

**Comment by cweijan** [comment]
Check remove pagination SQL.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/c61776b6-130c-4d9f-8fd0-a81bbefad366)

**Comment by VCOSTA-Dev** [comment]
> Check remove pagination SQL. ![image](https://private-user-images.githubusercontent.com/27798227/324143040-c61776b6-130c-4d9f-8fd0-a81bbefad366.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3ODE3NjEsIm5iZiI6MTcxMzc4MTQ2MSwicGF0aCI6Ii8yNzc5ODIyNy8zMjQxNDMwNDAtYzYxNzc2YjYtMTMwYy00ZDlmLThmZDAtYTgxYmJlZmFkMzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDEwMjQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzY2ZmYTRiMjc0N2NmYzVjMDJlM2E2ODIzZTkzZTdjNDAwMTZhYjFlZDE4YzlhZTdjYmQwNWQ2MGFhYTMyYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ku_veDfKzCPWejGMTvqMZ3bCmn_irQI6clNFEsSZjtk)

Thanks, that worked!
