### ISSUE TITLE
[BUG] cannot copy values from fields

### ISSUE THREAD

**Issue by jjelier** [cweijan/vscode-mysql#1100]
select a field from a result of a query, double click, select the text (for example) and use combination command c (copy) (working on a Mac M1 - 14.3.1 (23D60)

**Comment by cweijan** [comment]
Thanks feedback. This is a known issue. Please use the right-click menu to copy it now. I will try to fix it in the next version.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/96a4205a-e40c-46e5-95b5-b46dd611db09)

**Comment by cweijan** [comment]
Fixed in version 7.2.2.

**Comment by jjelier** [comment]
You're great! Thank you for this great tool. Use it daily with pleasure

Op vr 12 apr 2024 11:47 schreef Weijan Chen ***@***.***>:
