### ISSUE TITLE
[BUG] Error messages getting cut randomly

### ISSUE THREAD

**Issue by yuzokamoto** [cweijan/vscode-mysql#1101]
The error text in console gets cut randomly. Even the text on hover. Why?

- Database type and version: Sqlite3 (3.45.2)
- Windows 11

Screenshots of the same query being executed 3 times, each generating incomplete error messages:
First
![image](https://github.com/cweijan/vscode-database-client/assets/29845719/8e845a32-086a-4d56-a8fd-3633ac4755a2)
Second
![image](https://github.com/cweijan/vscode-database-client/assets/29845719/f451a0d3-2c59-4c3c-a5cd-e6a73ca66c76)
Third
![image](https://github.com/cweijan/vscode-database-client/assets/29845719/eaf708ca-1a60-4bb4-a114-8dba354c297d)

**Comment by cweijan** [comment]
Fixed in version 7.2.2.
