### ISSUE TITLE
Hability to execute query in same window

### ISSUE THREAD

**Issue by dicaetano** [cweijan/vscode-mysql#1102]
Currently it exists a config called `Created result view for each query`, which creates a new result window for each query. But it would be nice an option/shortcut to execute the query in a different window, as an alternative of this existing config, which enables it for all queries. Most of my time I want to execute in the same window, but for some queries I need a new window, so I can compare the results for example. 

For example, Cmd + Shift + Enter could, by default, execute the query and create a new result window.

**Comment by dicaetano** [comment]
Just saw the lock panel button. But still, it would be nice to have a shortcut to execute in a new window, so I don't have to go and click the lock 😅

**Comment by Frogley** [comment]
I'd like to offer a suggestion regarding this issue. The current configuration, "Create result view for each query," keeps opening new windows, quickly leading to an excess that forces me to go back and close some. Consequently, I usually disable this option. The user interface then consists of several locked windows and one refreshable window. Is it possible to adopt Toad's UI logic here and change it to locked windows + n refreshable windows? That is, open a new refreshable window for each query, but once the number of refreshable windows reaches n (Toad defaults to 5), new results would cycle through these n windows. For example, the sixth query would refresh in window 1, the seventh would cycle to window 2, and so on, thereby avoiding the problem of too many windows. Of course, users could also use the lock button to switch between locked and refreshable windows. What do you think about this suggestion?

关于这一点，我也提一点建议。
目前"Created result view for each query"这个配置会一直打开新窗口，很快就会打开太多窗口以致于我不得不回头去关闭掉一部分。所以我通常会选择关闭这个选项。
此时的UI是若干个锁定窗口+1个可刷新窗口。这里能否可能借鉴Toad的UI逻辑，改为锁定窗口+n个可刷新窗口呢？也就是说，为每次查询打开一个新的可刷新窗口，但当可刷新窗口数量到达n(Toad的默认值是5)后，新的结果就会在这n个窗口中循环，例如第6次查询会在窗口1刷新，第7次循环在窗口2刷新...这样就避免了窗口数量太多的问题。当然，用户也可以通过锁定按钮实现锁定窗口和可刷新窗口间的切换。
不知道作者觉得如何？

**Comment by cweijan** [comment]
"Created result view for each query" is indeed not a recommended option. I will add new codelen and command to open a new result page in the next version.

**Comment by cweijan** [comment]
New codelen and command have been added in version 7.2.2 to support opening new tabs.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/9bd364d2-5180-455a-aa2c-2cd4e27d200c)
