### ISSUE TITLE
[BUG] Not showing all columns when using SQLite

### ISSUE THREAD

**Issue by trollfalgar** [cweijan/vscode-mysql#1103]
When using SQlite not all columns are shown in the tree.

![image](https://github.com/cweijan/vscode-database-client/assets/441455/373a4962-5622-424e-9648-11dcabc8e985)

- Database type and version:
SQLite 3.19.1
Windows 11

**Comment by cweijan** [comment]
Hi, does this problem occur occasionally? You can try clicking the refresh button.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/31cce602-6cab-4ee7-a7b6-7d9c0b6f6880)

**Comment by trollfalgar** [comment]
> Hi, does this problem occur occasionally? You can try clicking the refresh button.
> 
> ![image](https://github.com/cweijan/vscode-database-client/assets/27798227/31cce602-6cab-4ee7-a7b6-7d9c0b6f6880)
> 

Yes, I clicked to refresh.
In Linux works fine.
I believe this problem starts with the last update.

**Comment by cweijan** [comment]
The recent updates are all about the interface and are not covered here.

I think this is due to your table changing externally and the cache not being updated, if you encounter this situation in the future, please click the refresh button.
