### ISSUE TITLE
[BUG]  Can not copy data with "Cmd+C"

### ISSUE THREAD

**Issue by MagicYang** [cweijan/vscode-mysql#1105]
Mac OS，Copy function dosen't work.

- Database type and version:
MySQL version: v7.2.3
VSCode version: 1.88.0 (Universal)

![WechatIMG64](https://github.com/cweijan/vscode-database-client/assets/639319/44f18d6b-4f8b-455b-8dd4-9dad1303d9b1)

**Comment by MagicYang** [comment]
It works after reloading the extension.

**Comment by cweijan** [comment]
Yes, the latest version has fixed this issue.
