### ISSUE TITLE
[BUG] REPEAT() in Stored Procedure

### ISSUE THREAD

**Issue by mend9112** [cweijan/vscode-mysql#1106]
Using the REPEAT function in a query while in a stored procedure throws a syntax error while the same code as a query outside the procedure runs as expected. Presumably an error because of the similar syntax as REPEAT LOOP. ![image](https://github.com/cweijan/vscode-database-client/assets/89863735/97d06eec-b4d7-4666-8668-bc5a924e324b)

**Comment by cweijan** [comment]
This is due to the database you are using and has nothing to do with the client.
