### ISSUE TITLE
Spatial data viewer

### ISSUE THREAD

**Issue by ttrubel** [cweijan/vscode-mysql#1107]
It would be great to have a spatial data viewer:
- Interactive map for visualizing spatial data
- Support for various map features (points, lines, polygons)

It is the main reason why I keep using DBeaver

**Comment by cweijan** [comment]
Thanks for your suggestion! I will support it in future versions.

**Comment by cweijan** [comment]
In version 7.3.1, spatial data is displayed as WKT, but sorry, there are no plans to support graphical display like DBeaver.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/16342104-7582-4830-aca2-f5ba0b38759b)

**Comment by ttrubel** [comment]
thank you!
