### ISSUE TITLE
Please add support for Cassandra

### ISSUE THREAD

**Issue by itsamit108** [cweijan/vscode-mysql#1109]
Hi, currently the extension does not support the Cassandra database. Please add support for it.

**Comment by cweijan** [comment]
Have you tried creating a jdbc connection with Cassandra dialect?

<img width="1015" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/27798227/5c9d689e-40f6-4d8a-bbaa-a82b9373d240">

**Comment by cweijan** [comment]
Creating Cassandra connections has been supported in version 7.3.1

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/d3562425-5e4d-4fa7-b83a-61cee649e575)

**Comment by itsamit108** [comment]
Thanks, Cweijan

**Comment by itsamit108** [comment]
Could we have a single VSCode extension for this instead of the two that we currently have?
