### ISSUE TITLE
[BUG] wrong total with PostgreSQL 16.2

### ISSUE THREAD

**Issue by kdefarge** [cweijan/vscode-mysql#1110]
Hi
Missing one entry in the total displayed on the screenshot :
![bug](https://github.com/cweijan/vscode-database-client/assets/1819360/f71713a8-ae96-4b43-a145-196392be7db2)

I just try on PostgreSQL 16.2 and on all my tables one is missing in to the total

I use VSCodium 1.88.1 

best regards

**Comment by cweijan** [comment]
Fixed in version 7.2.6.
