### ISSUE TITLE
wrong autocomplete

### ISSUE THREAD

**Issue by GreenFlag31** [cweijan/vscode-mysql#1111]
Hi, 

Just to report an autocomplete bug. When typing 'UPDATE table_name SET ... ' there is no auto complete on 'SET' and if you press 'tab' it will create the following : 
![image](https://github.com/cweijan/vscode-database-client/assets/84795623/ede5ff64-05bb-4c82-a36e-e4f4cf3bf9bb)

cheers

**Comment by cweijan** [comment]
Thanks feedback, set completion has been added in version 7.2.7
