### ISSUE TITLE
[BUG] duckdb connections with read-only enabled in the UI are not able to list tables, execute queries, and accurately respect the request to connect with `-readonly` enabled

### ISSUE THREAD

**Issue by cameronraysmith** [cweijan/vscode-mysql#1112]
When enabling read-only mode under "Advance" -> "Read Only" for a duckdb connection, database-client is unable to list tables. I wonder if the [readonly option is not being passed to the duckdb cli correctly](https://duckdb.org/docs/api/cli/overview.html#options) or if the connection is being managed in such a way that this is not possible.

If read-only mode is disabled it functions as expected with the same database and connection.

Database type and version: duckdb `0.10.1`

#262 #961

**Comment by cweijan** [comment]
Hi, the read-only option is not passed to the cli, I think an unexpected error occurred, please try the latest version 7.2.8, the error can be displayed correctly.

**Comment by cameronraysmith** [comment]
Thank you @cweijan . Now Database Client can connect and list tables if no other process is connected in readonly mode, but it simply ignores and thus does not respect the readonly toggle in the UI at "Advance" -> "Read Only" for its own connection. For example with the readonly toggle set to enabled/on we have Database Client creating the connection via

```sh
$ ps aux | grep duckdb
18146   0.0  0.0 410701488  22144   ??  S    10:24AM   0:00.04 duckdb -header -nullvalue DB_CLIENT_NULL -cmd .mode
```

however, when readonly is enabled/on this should instead resolve to something that connects via a command like

```sh
$ ps aux | grep duckdb
18146   0.0  0.0 410701488  22144   ??  S    10:24AM   0:00.04 duckdb -readonly -header -nullvalue DB_CLIENT_NULL -cmd .mode
```

including the `-readonly` flag rather than ignoring the request to do so

https://duckdb.org/docs/api/cli/overview.html#options .

Without this, Database Client holds the write lock and other applications cannot read from the database despite having been able to request to connect in readonly mode via the Database Client UI. Many thanks!

**Comment by cweijan** [comment]
Thanks for the reminder, I will add it in the next version

**Comment by cameronraysmith** [comment]
Sounds great! Thank you again for Database Client. Presumably this will be able to be closed after the next release.

**Comment by cweijan** [comment]
Already passed -readonly option in version 7.3.1.

**Comment by cameronraysmith** [comment]
`7.3.1` works perfectly now. Many thanks @cweijan !

**Comment by fflores97** [comment]
Hi! It seems like this isn't working anymore. The extension retuns:
```
Error: unable to open database "--readonly": IO Error: Cannot open database "--readonly" in read-only mode: database does not exist
```
Which completely goes away when I toggle readonly mode off. Currently on version 8.3.6
