### ISSUE TITLE
Avoid override configs accidentally by could sync

### ISSUE THREAD

**Issue by qazwsxedckll** [cweijan/vscode-mysql#1113]
1. Having lots of configs on A with cloud sync off.
2. Turn on cloud sync on B.
3. Turn on cloud sync on A.
4. All configs are lost on A.

Maybe add some merging machenism or at least some warnings.

**Comment by cweijan** [comment]
Auto sync is controlled by vscode, and the extension cannot merge it. To avoid this situation, it is recommended that you synchronize manually.
