### ISSUE TITLE
[BUG] Remove activated License

### ISSUE THREAD

**Issue by hanc2006** [cweijan/vscode-mysql#1114]
Hi, I copied a wrong machine id from my laptop, and I cannot activate the extension. How I can delete this wrong machine id?

<img width="907" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/4517251/80cd5f8b-dc46-4874-8929-d377ae45b8be">

**Comment by cweijan** [comment]
Hi, it is currently not possible to delete it manually. I have deleted your wrong machine ID.
