### ISSUE TITLE
[BUG] Cannot show field content on long content

### ISSUE THREAD

**Issue by dsantoso-ibs** [cweijan/vscode-mysql#1115]
- Database type and version:
MySql 8.0.35

I have a field type json in a table.
If the content is long. In my case its 124k, it is only showing 
[1k of 124k] .....

There is no possibility to click the cell to see the content.

**Comment by cweijan** [comment]
Thanks for the report, big data viewing is supported in version 7.2.6.

<img width="425" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/27798227/9b0e8401-ab06-493e-aa4e-7aa8471f3a8b">
