### ISSUE TITLE
[BUG] "Login In VS Code" button does not work

### ISSUE THREAD

**Issue by alancnet** [cweijan/vscode-mysql#1116]
The website at `https://database-client.com/#/plan?ext=true` seems to be attempting to connect to local development tools, so I cannot activate the extension in my VS Code.

![image](https://github.com/cweijan/vscode-database-client/assets/2042102/f711c83c-3766-49ce-b551-ea9ee385dc70)
![image](https://github.com/cweijan/vscode-database-client/assets/2042102/aaffdd6a-7ebc-4af8-ae4c-2c7a58892852)

**Comment by cweijan** [comment]
If login fails, please click Login on browser within the extension.

<img width="963" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/27798227/2833c5bf-dddf-4ecc-82f0-38c0d855c090">
