### ISSUE TITLE
[BUG]Oracle Procedures can not open

### ISSUE THREAD

**Issue by Kizun** [cweijan/vscode-mysql#1117]
some long Oracle Procedures can not open,Error: ORA-01489: 字符串连接的结果过长

    at /Users/xxx/.vscode/extensions/cweijan.vscode-mysql-client2-7.2.5/out/extension.js:145333:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
- Database type and version
oracle 12

**Comment by cweijan** [comment]
Fixed in version 7.4.5.
