### ISSUE TITLE
[BUG] Row selector and copy row option missing

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#1119]
Dear Sir,

- Database type and version: MySQL 8.0.28

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/b42ef26f-14e1-4240-9ed7-085784787537)

Data grid row selection option and copy row option missing now.

Request you to please look into and do the needful

Thank you

**Comment by cweijan** [comment]
Column selection copying is canceled in the new version, now you can drag to select cells, can you try it?

**Comment by cweijan** [comment]
Select and press ctrl/cmd+c to copy.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/a27e6231-4599-4e19-a4d6-1b0d105f4495)

**Comment by franklinkf** [comment]
Great.  Thank you

**Comment by cweijan** [comment]
After version 7.3.0, in addition to shortcut keys, a right-click menu is also provided for copying.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/7e6388da-4b30-4401-85f0-c3eea2d8620f)
