### ISSUE TITLE
数据显示和total显示有问题

### ISSUE THREAD

**Issue by zhanghoufu** [cweijan/vscode-mysql#1120]
- Database type and version:
![image](https://github.com/cweijan/vscode-database-client/assets/20350789/a221e86f-01a3-48ee-a41c-b7e65fc6a5e1)
总共24条数据，total显示23

表结果和树形结构数据不一致
![image](https://github.com/cweijan/vscode-database-client/assets/20350789/59b3cbba-6cf9-458c-a061-af31c9576ab7)
![image](https://github.com/cweijan/vscode-database-client/assets/20350789/d0b6c2d2-019f-4421-8a97-1118e3411c89)

![image](https://github.com/cweijan/vscode-database-client/assets/20350789/29f64e6e-2ce0-4b83-a7c7-54cdfd17f8d3)

**Comment by cweijan** [comment]
总数问题已在版本7.2.6修复, 另外, 树形节点的总数是MySQL的一个估算值, 并不是准确的.
