### ISSUE TITLE
[BUG] duckdb doesn't work in linux

### ISSUE THREAD

**Issue by Tint0ri** [cweijan/vscode-mysql#1121]
- Database type and version:
ducckdb

copy linux duckdb into ~/.dbclient.  And use vscode remote connect. When create duckdb connection. Show duckdb is not installed. Extension SQLTools works fine.

![屏幕截图 2024-04-27 205030](https://github.com/cweijan/vscode-database-client/assets/64587482/567cf8c0-66cd-4dd3-ad27-6d544800c9df)

**Comment by cweijan** [comment]
Hi, you need to add the path of duckdb to the environment variable.

**Comment by Tint0ri** [comment]
I put duckdb into ~/.dbclient. duckdb works in terminal.

**Comment by cweijan** [comment]
Hi, try version 7.3.1, which supports finding duckdb in the ~/.dbclient directory.
