### ISSUE TITLE
[BUG] Cannot select "🔒 Active Connection" from code editor

### ISSUE THREAD

**Issue by alancnet** [cweijan/vscode-mysql#1123]
- Database type and version:
PostgreSQL  12.14

1. Install extension, create a connection, yadda yadda.
2. Create a new file
3. Set the language of the editor to "SQL"
    - inline interface appears:
    - ▶️ Run | New Tab | 🔒Active Connection
4. Click on 🔒Active Connection
5. Select server
    - Interface switches to, and hangs on "🔄️ Loading schemas..."

![image](https://github.com/cweijan/vscode-database-client/assets/2042102/898f1faf-99f8-43d7-9d48-58080d08085b)

Error appears in terminal:

```
2024-05-01 16:04:31 error: pg_hba.conf rejects connection for host "x.x.x.x", user "xxx", database "xxx", SSL off
    at gj.parseErrorMessage (~/.vscode-server/extensions/cweijan.vscode-database-client2-7.2.7/out/extension.js:69448:70)
    at gj.handlePacket (~/.vscode-server/extensions/cweijan.vscode-database-client2-7.2.7/out/extension.js:69320:23)
    at gj.parse (~/.vscode-server/extensions/cweijan.vscode-database-client2-7.2.7/out/extension.js:69261:24)
    at Socket.<anonymous> (~/.vscode-server/extensions/cweijan.vscode-database-client2-7.2.7/out/extension.js:69471:34)
```

**Comment by cweijan** [comment]
This is your postgresql configuration problem, you need to modify the server configuration.

reference:
https://stackoverflow.com/questions/52197486/fatal-pg-hba-conf-rejects-connection-for-host-127-0-0-1-user-postgres-dat

**Comment by alancnet** [comment]
My apologies @cweijan. The database in the error is not the same database in the connection properties. Thank you for pointing out it was a server error which drew my attention to that fact.

The functionality for selecting a schema connects to the server without selecting a database. I encounter this because my user does not have access to the default database, but can still list schemas within the configured database.

**Comment by alancnet** [comment]
@cweijan Did you see my correction? The "🔒 Active Connection" > "🔄️ Loading schemas..." does not use the configured database name when querying schemas.

**Comment by cweijan** [comment]
Thanks feedback, because when reading the schema, the extension must switch databases, I will add fault tolerance in the next version.

**Comment by alancnet** [comment]
This works now! 🤯 Thank you for the fast fix!!
