### ISSUE TITLE
How can I import csv data?

### ISSUE THREAD

**Issue by Ethan-Crisp** [cweijan/vscode-mysql#1124]
I right clicked on every button I could find, and it shows no way to import csv data. I'm spending many days importing data with sql and it has thousands of bugs.
怎么导入csv数据？没有找到任何地方右键可以导入csv数据。别的同学用mac系统的postgre直接右键就把数据导入进去了，我花了额外几天时间都做不到最简单的功能，这个作业没法做了...

**Comment by cweijan** [comment]
在结果页有个上传按钮, csv文件内容首行设置为表的列名.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/e0950efa-e73e-4b7b-92b8-91bfb4aa7cf5)
