### ISSUE TITLE
Open results view to the right (horizontal split)

### ISSUE THREAD

**Issue by johan-maes-kathondvla** [cweijan/vscode-mysql#1125]
Current workarounds: 

1. Run query, then toggle vertical/horizontal editor layout (Ctrl+Alt+0).
2. Disable database client setting `split editor when query` and move the results view to the next group after executing the query.

But it would be nice to have an extra option to select the position of the results panel (horizontal/vertical) if it is split.

**Comment by cweijan** [comment]
Hi, in the new version 7.3.2, you can display the results horizontally by canceling the vertical display option.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/a4786b53-3286-4033-99a2-6884a3434274)
