### ISSUE TITLE
关于TDEngine

### ISSUE THREAD

**Issue by Carson-yy** [cweijan/vscode-mysql#1127]
URL填啥？咋填都是127.0.0.1:6041 连接异常

**Comment by cweijan** [comment]
你试试http://127.0.0.1:6041, 忘记生成模板了.

**Comment by Carson-yy** [comment]
> 你试试http://127.0.0.1:6041, 忘记生成模板了.

也不行，我连接的不是本地的，是远程的，IP和端口都换掉了，一直提醒

**Connection error!connect ECONNREFUSED 127.0.0.1:6041**

**Comment by cweijan** [comment]
非常抱歉, 确实有问题, 等我下版本修复.

**Comment by cweijan** [comment]
已发布版本7.3.2修复.
