### ISSUE TITLE
找不到控制查询结果展示位置的设置选项

### ISSUE THREAD

**Issue by DyCheer** [cweijan/vscode-mysql#1128]
Type: <b>Feature Request</b>

本来sql查询结果在vscode下方展示, 更新之后默认在右侧展示, 应该提供一个选项

Extension version: 7.3.2
VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by cweijan** [comment]
你重启一下vscode, 然后看看这个选项有没有勾选, 默认是垂直的.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/683112fc-6267-4441-9b2c-f7c67fe5627e)
