### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by init5god** [cweijan/vscode-mysql#1130]
- Issue Type: `Performance`
- Extension Name: `vscode-database-client2`
- Extension Version: `7.3.3`
- OS Version: `Darwin arm64 21.6.0`
- VS Code version: `1.89.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/5b/gczjk27x42j9h_573hw3xp5c0000gn/T/cweijan.vscode-database-client2-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by cweijan** [comment]
When did the high usage occur? And please provide the cpuprofile.txt file.

**Comment by cweijan** [comment]
Performance has been optimized in version 7.3.6.
