### ISSUE TITLE
Clearing query history

### ISSUE THREAD

**Issue by Anarchist779** [cweijan/vscode-mysql#1131]
I would like it to be possible to clear the query history

**Comment by cweijan** [comment]
Hi, in the latest version 7.3.8, the history records have been reversed. Now the latest records will be displayed at the top. The number of history records is fixed at 300, and deletion is not planned to be supported.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/dd58d291-fca6-47d6-8bbc-a589030592d0)
