### ISSUE TITLE
Missing tab unlock

### ISSUE THREAD

**Issue by michaldurovic** [cweijan/vscode-mysql#1132]
Type: <b>Bug</b>

- Database type and version: Clickhouse DB conneciton
Missing unlock tab, I can have only one result from DB not multiple tabs like before.

Extension version: 7.3.4
VS Code version: Code 1.89.0 (Universal) (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:10:10.196Z)
OS version: Darwin x64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.84GB free)|
|Process Argv|--crash-reporter-id d7c82601-897b-482d-b8ad-c72c5b57f4c9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaat:30438848
c4g48928:30535728
azure-dev_surveyonecf:30548226
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
showvideoc:31016891
dsvsc021:30996838
f3je6385:31013174
pythonprt:31039817
dwnewjupytercf:31039676

```

</details>

**Comment by cweijan** [comment]
Hi, have you tried "New Tab" codelen? In order to reduce the number of toolbars, the new version hides it.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/4e8c03ca-9f0c-42c7-adc7-a611167e4966)

**Comment by michaldurovic** [comment]
Hello, I used it in quickly opening multiple tables in database (without writing SQLs). I see now that I can use the "menu" icon on each table. It will do, thanks for quick reply.

![image](https://github.com/cweijan/vscode-database-client/assets/43437313/51c9f128-0068-42aa-a577-6baddde40ec1)
