### ISSUE TITLE
[BUG] Updating Procedures and Functions -  Now not displaying update status

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#1133]
- Database type and version: MySQL 8.0.28

Earlier, when I create or update a procedure or function in MySQL, the result window will show the status of its update.  Whether it is successfully updated or not updated due to any syntax errors.

From today onwards, this feature is missing.  I am getting the following window as result page

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/1167e73a-6483-4fe5-ab40-b9254d6395f7)

Request your attention

Thank you

**Comment by cweijan** [comment]
Sorry, in the latest version, batch execution SQL is parsed, but an error occurs. I have released version 7.3.5 to fix it, please try it.

**Comment by franklinkf** [comment]
Now perfect.  Thanks

Now a new scenario evolved.  When creating/updating a procedure, the result is coming in three result pages - result1, result2, result3.

Earlier it used to come in single result sheet

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/2f160b61-56d4-42c0-8136-8942b7a781bb)

Result1

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/9bbdf21d-ed0a-4b99-8a91-0b4e8b220aac)

Result2

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/dd0c58ce-1003-4449-a039-48137d92441a)

Result3

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/64467a78-409b-4600-9b21-86b08f2abd4e)

Request your attention

Thank you

**Comment by cweijan** [comment]
Yes, the new version parses batch execution. It seems that DDL is not necessary. I will cancel it in the next version.

**Comment by franklinkf** [comment]
Thank you Sir

**Comment by franklinkf** [comment]
Database type and version: MySQL 8.0.28

Earlier, when I create or update a procedure or function in MySQL, the result window will show the status of its update. Whether it is successfully updated or not updated due to any syntax errors.  The issue was conveyed on 07-05-2024 and was rectified.

Now, whenever I update a procedure, I am getting an additional window opened - OUTPUT in the bottom.  This was not there earlier.  Can you please disable this.

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/ceb14a6c-1dbb-4ba9-a6b8-76aa7f4d981d)

Thanks

**Comment by franklinkf** [comment]
Also can you please provide an option to disable multiple result views in settings.  For example, if I execute the following query, I am getting three result views:

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/a2f28282-775c-485f-9fb7-c01f39f4c3ad)

Request your consideration

**Comment by cweijan** [comment]
Thanks for the report, I have found the problem and will fix it in the next version.

**Comment by cweijan** [comment]
Hi, I released a new version 7.4.2. Now a new view will be created only when new data appears. Can you try it?

**Comment by franklinkf** [comment]
> Hi, I released a new version 7.4.2. Now a new view will be created only when new data appears. Can you try it?

Perfect.  Issue resolved.

Thank you Sir

**Comment by franklinkf** [comment]
> Also can you please provide an option to disable multiple result views in settings. For example, if I execute the following query, I am getting three result views:
> 
> ![image](https://private-user-images.githubusercontent.com/8948123/334044527-a2f28282-775c-485f-9fb7-c01f39f4c3ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTg3NzgsIm5iZiI6MTcxNjk1ODQ3OCwicGF0aCI6Ii84OTQ4MTIzLzMzNDA0NDUyNy1hMmYyODI4Mi03NzVjLTQ4NWYtOWZiNy1jMDFmMzlmNGMzYWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMDQ1NDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2JlZGY3M2EwZGI4Yzg5MjJjZjAzMTI3ZmQyOTc3MDVmOWMwZTk0MGRmM2JkMzgwYzQ1MzUzYmE3MDRiNjA5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IAZIXBrcIXZA8s7Qd9OPFs0yuJMKM8sBTqYtno3a6dU)
> 
> Request your consideration

Now only one result view is coming.  But the result of the last action only is displayed.

For example for the following query,

DROP TABLE IF EXISTS FRANKLIN;
CREATE TABLE FRANKLIN (GDATA1    LONGTEXT);

The result of the second query is only displayed

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/fb1972db-1110-46db-b095-88c67f90762a)


Execution status of first query is not displayed, even if it is failed.  

It will be nice, results of all the queries are displayed.

Thanks

**Comment by cweijan** [comment]
Thanks feedback, I plan to display multiple execution statuses in one result page in the next version.

**Comment by franklinkf** [comment]
Thank you Sir
