### ISSUE TITLE
Option to skip checking foreign keys when deleting row(s) in MySQL

### ISSUE THREAD

**Issue by paweldepta** [cweijan/vscode-mysql#1134]
It would be very helpful to have an option to skip checking of foreign keys while performing delete actions on rows.

Right now we have an option to just delete selected rows (screenshot below)
![image](https://github.com/cweijan/vscode-database-client/assets/16735338/63f706a0-50a4-45a8-850a-06bfca2bd900)

Maybe there should be a checkbox in this dialog or special shortcut key (SHIFT or CTRL) to hold when clicking "Delete" button.

```mysql
SET FOREIGN_KEY_CHECKS=0;
-- DELETE FROM ...
SET FOREIGN_KEY_CHECKS=1;
```

This feature could probably be added to truncating table(s) as well

**Comment by cweijan** [comment]
Interesting proposal, I will support it in future versions!

**Comment by cweijan** [comment]
Supported in version 7.3.8.
