### ISSUE TITLE
[BUG] Column selection is reset when you update the table

### ISSUE THREAD

**Issue by mercurykd** [cweijan/vscode-mysql#1135]
https://github.com/cweijan/vscode-database-client/assets/30900414/cf6d3229-2f19-4bda-975b-fe749c316c82

**Comment by cweijan** [comment]
Thanks for the feedback, I will fix it in the next version

**Comment by cweijan** [comment]
Strange, I can't reproduce your issue. Can you try the latest version 7.3.6?

**Comment by mercurykd** [comment]
> Strange, I can't reproduce your issue. Can you try the latest version 7.3.6?

7.3.5 - reproduce 
7.3.6 - not reproduce

**Comment by cweijan** [comment]
Thanks feedback!
