### ISSUE TITLE
How to save the connections in .vscode/settings.json file

### ISSUE THREAD

**Issue by tobiasz-gleba** [cweijan/vscode-mysql#1136]
Hi, I've managed to export my connection, but I can not include it in the `.vscode/settings.json` file. Can you guide me on how to do it?

I don't mind the security, because it is my local docker dev container-based setup.

**Comment by cweijan** [comment]
Hi, the name of the setting is database-client-config.json. Note that work-level connections only take effect for premium.

**Comment by tobiasz-gleba** [comment]
ok, thanks
and where the global-level config file is stored?

**Comment by cweijan** [comment]
There is no configuration file for global configuration, you can only import it in the console.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/5dde344c-4024-4f20-96b9-e7d7e92c33ca)

**Comment by tobiasz-gleba** [comment]
is it possible to automate it? to do it from the command line?

**Comment by cweijan** [comment]
If you want to synchronize automatically, you can log in to your VS Code account and check Auto Sync.

**Comment by tobiasz-gleba** [comment]
but I would like to automate it on the dev container level in git repo, not using my vscode account

**Comment by cweijan** [comment]
Then you need to upgrade to Premium to get this feature🥲.
