### ISSUE TITLE
Run sql code block by block like dbeaver.

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#1137]
Hi.
Creating a feature that helps us execute a sql file block by block .
For example, this feature exists in DBeaver and it helps us to run it block by block in databases that do not have the ability to run an SQL file at the same time (such as clickhouse).

```sql
create database a1;

create database b1;
```

For example, in the example above, each command must be executed separately in the **clickhouse** database.

**Comment by cweijan** [comment]
Coincidence! I am currently developing this part 😂, and it will be supported in the next version.

**Comment by cweijan** [comment]
Supported in version 7.3.6.
