### ISSUE TITLE
字段的搜索框没有了

### ISSUE THREAD

**Issue by MiddleTier98** [cweijan/vscode-mysql#1138]
Type: <b>Feature Request</b>

- Database type and version: 
为什么现在没有字段的搜索框了？

Extension version: 7.3.7
VS Code version: Code 1.81.1 (Universal) (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:20:33.924Z)
OS version: Darwin arm64 22.5.0
Modes:

**Comment by MiddleTier98** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/41611755/c582904b-b02a-44ce-a0a3-2f9458232d19)
以前在这下方是有一个搜索框的，突然没有了。
![image](https://github.com/cweijan/vscode-database-client/assets/41611755/057f8f1b-e6db-4ee4-a742-d32a366d0cc7)
设置也没有对应的选项

**Comment by cweijan** [comment]
你是说字段筛选吗, 悬浮放大镜就可以看到了
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/1ec06f1a-f010-4bd8-9ef9-132cb928551e)
