### ISSUE TITLE
Suggestion for Enhancing Table Update Features

### ISSUE THREAD

**Issue by itsamit108** [cweijan/vscode-mysql#1139]
There is currently no way to automatically update the tables when they are modified. The only way to see the updated data is to reopen the table. 

I suggest adding an option to auto-update the database and table, or including a refresh button in the table view for easily viewing the updated changes. 

Thank you.

**Comment by cweijan** [comment]
Do you mean that the table data has changed externally? At this time, you can click the run button to refresh the data.
<img width="833" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/27798227/2ff03ffd-5458-4c0e-837b-4ec2f1fadb11">

**Comment by itsamit108** [comment]
> Do you mean that the table data has changed externally? At this time, you can click the run button to refresh the data. <img alt="image" width="833" src="https://private-user-images.githubusercontent.com/27798227/330418803-2ff03ffd-5458-4c0e-837b-4ec2f1fadb11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODkxMDAsIm5iZiI6MTcxNTY4ODgwMCwicGF0aCI6Ii8yNzc5ODIyNy8zMzA0MTg4MDMtMmZmMDNmZmQtNTQ1OC00YzBlLTgzN2ItNGVjMmYxZmFkYjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDEyMTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ZGY1NDQ3NGMyZDE3NDEzNDM4M2M2ZDU5ZTc5NmI2NzU0M2Y1YmRjY2JiYzk0YjA4NGUwNGVjNTZjZWE0Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FPSCyzrNch_Jmwrl-rOvG0NrGYYYgQJIOgU_RLwh5yw">

Exactly, wouldn't it be better if the data is automatically refreshed, as it happens in other Database clients like Datagrip and DBeaver?

**Comment by cweijan** [comment]
Ok, thank you for your suggestions, I will refer to their functions.

**Comment by cweijan** [comment]
Hi, I added a refresh button in version 7.3.9. After evaluation, automatic refresh is unnecessary and I do not plan to add it.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/783265d2-0599-45d4-9d1f-e2d5f11c5518)
