### ISSUE TITLE
[BUG] Paging Issue / Incorrect Result Range for SQL Query with LIMIT Clause

### ISSUE THREAD

**Issue by josef-kyrian** [cweijan/vscode-mysql#1141]
- Database type and version:
Database: MySQL
Extension version: 7.3.7

Hello,

I'm experiencing an issue with the extension when executing the following two SQL queries in sequence. The second query displays an incorrect result range, ignoring the LIMIT clause specified in the SQL statement.

**Steps to Reproduce:**

1. Execute the following SQL query:
`SELECT * FROM product LIMIT 2;`
2. Immediately execute the following SQL query
`SELECT * FROM product LIMIT 2, 2;`

**Expected Result**:
The second query should display **next** 2 rows.

**Actual Result**:
The second query ignores the offset in the LIMIT clause.

**Comment by cweijan** [comment]
Thanks for your report, I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed in version 7.3.8.
