### ISSUE TITLE
[BUG] Open query button on database disappeared

### ISSUE THREAD

**Issue by josef-kyrian** [cweijan/vscode-mysql#1142]
Database type and version:
Database: MySQL
Extension version: 7.3.8

Hello,

in the new version 7.3.8 disappered the button Open query on database item in the databases list.

**Comment by cweijan** [comment]
Thanks feedback, in order to reduce the number of icons in the database node, I hide it. I will hide other buttons and add it back in the next version.

**Comment by josef-kyrian** [comment]
I use it to select database as active, so that I can run queries from file...

Btw is there any better way to select active database?

**Comment by cweijan** [comment]
You can change the active connection with the command "Change active connection"

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/5933411c-8b16-4426-a179-ca0da12c16a2)

**Comment by josef-kyrian** [comment]
OK, good to know, thanks!

But if possible, it would be nice to keep the Open query button...

**Comment by cweijan** [comment]
The Query button has been added back in version 7.3.9.
