### ISSUE TITLE
[BUG] new payment option

### ISSUE THREAD

**Issue by melihkucuknazli** [cweijan/vscode-mysql#1143]
- Database type and version:

PayPal cannot be used in Turkey for legal reasons.  A new payment type should be developed. I could not buy a license. There are companies like iyzico in Turkey, you can look at them.

**Comment by cweijan** [comment]
Please try "Second Choice Payment" or "buymeacoffee".

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/2fced1c3-385a-4df5-868a-1c947d74575b)
