### ISSUE TITLE
Connection error using unknown plugin auth_gssapi_client

### ISSUE THREAD

**Issue by Gtomazini** [cweijan/vscode-mysql#1144]
When trying to use for the first time:

Connection error!Server requests authentication using unknown plugin auth_gssapi_client. See TODO: add plugins doco here on how to configure or author authentication plugins.

Any thoughts?

PS: using MySQL

**Comment by cweijan** [comment]
It looks like you are using mariadb, please try to connect using mariadb.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/56603813-8ad6-4f1d-a12c-9b59d556a327)

**Comment by Gtomazini** [comment]
It worked, thank you.

Basically my MYSQL wasn't installed correctly, so the MYSQL was not recognized and he try to use another.
After reinstall all dependencies it works fine.

**Comment by cweijan** [comment]
It seems that in some Linux package managers, MySQL is replaced by MariaDB by default🥲.
