### ISSUE TITLE
Time connected when downloading or uploading big files via FTP

### ISSUE THREAD

**Issue by gzlo** [cweijan/vscode-mysql#1145]
i just recently download a bkp .tar file via FTP, but the connection stops after a few hours when de file was downloading. It was a big file 235G compressed and only downloaded 15G of 235G ... so i used FileZilla instead ... my question is ... there's a feature to stay connected while downloading or uploading big files via ftp to a local machine ? or a download pannel to check how my ftp downloads or uploads status ? 

i hope to be my self clear. 

Thanks for your work !!! it's a awesome plugin use it every day un may daly work

**Comment by cweijan** [comment]
Sorry, this extension only provides limited support for FTP, the situation with large files is complicated and I would not consider supporting it.
