### ISSUE TITLE
Dialog for editing a column doesn't appear

### ISSUE THREAD

**Issue by DarrellBrogdon** [cweijan/vscode-mysql#1146]
- Database type and version: sqlite3

Steps to Reproduce:

1. Click "Edit Table"
2. Double-click a column name

Expected Behavior:

A dialog to edit the column should appear

What Actually Happens:

The editor window goes dark but otherwise nothing changes.  If you hit the "Escape" key then you can briefly see the dialog appear and then disappear.

https://github.com/cweijan/vscode-database-client/assets/196196/8b05cb5e-5cbc-4de8-b112-798017ef738c

**Comment by cweijan** [comment]
SQLite does not support editing columns, I will display an error message in the next version.
