### ISSUE TITLE
grouping connections

### ISSUE THREAD

**Issue by mty713** [cweijan/vscode-mysql#1147]
Is it possible to add a feature, to be able to group the database connections? As the number of connections goes up, it looks a bit overwhelming. Thanks.
E.g.
Dev
  -- connection 1
  -- connection 2
Test
    -- connection 1
    -- connection 2

**Comment by cweijan** [comment]
The group feature already exists.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/b37baecc-57ec-499c-99d6-4dc418864a53)

**Comment by mty713** [comment]
Oh great! Sorry I missed it. Thanks a lot. Your extension is fantastic.
