### ISSUE TITLE
Executing multiple statements

### ISSUE THREAD

**Issue by alancnet** [cweijan/vscode-mysql#1148]
Was there a recent change that would affect the behavior when executing multiple statements? For example, if I select all of:

```sql

-- Small table, executes in 5ms:
alter table user add column foo int;

-- Small table, executes in 5ms:
alter table profile add column bar int;

-- Large table, executes in 15 minutes:
alter table session add column baz int;

```

and press Ctrl-Enter, it opens two Result windows for the first two statements, but doesn't open a third window for the third statement.

Since the third statement takes a long time to run, I might not expect a result right away, but I would expect a way to cancel the long running statement. I recall being able to do that, but I can't do that now.

From what I recall, the results of all the statements would appear in the same tab, or at least the result from the last statement.

**Comment by cweijan** [comment]
Thanks feedback, I've released version 7.3.9 with the fix.

**Comment by alancnet** [comment]
@cweijan I just updated to 7.4.2 and it is opening multiple Result tabs when executing multiple statements.

**Comment by cweijan** [comment]
Hi, after version 7.4.2, result pages will only be created when data exists, such as executing a select query. This is to prevent a large number of result pages from appearing when batch insert is executed.

For DML, the execution status is displayed on the right side of the SQL.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/96f147c6-494d-46ab-bd67-d80df2038bd9)

For your feedback, I plan to display multiple execution statuses on the same result page in the next version.

**Comment by alancnet** [comment]
@cweijan v7.4.3, still opening a result tab per statement. In my case, I'm executing on PostgreSQL:

```sql
set role some_role;

alter table some_table
  drop column some_column,
  add column other_column int8 not null;
```

I then `Ctrl+A` then `Ctrl+Enter` to execute

**Comment by cweijan** [comment]
Thanks feedback, I will fix it in the next version.
