### ISSUE TITLE
Duplicate an existing row

### ISSUE THREAD

**Issue by eml-c2829** [cweijan/vscode-mysql#1150]
Your extension is amazing, no doubt about it. I came from DBeaver which is also a great database client.
There's one feature I use a lot on DBeaver but Database Client does not have.

It's the ability to duplicate an existing row.
Here's how it works:
1/ Select a row from the query result.
2/ Click the duplicate row button.
3/ The selected row is duplicated
4/ I can edit some fields, and then submit the change.

This is a screenshot from DBeaver.
![image](https://github.com/cweijan/vscode-database-client/assets/150407077/9b1be89b-18d4-4c0c-b814-7bafd51bcfad)

**Comment by cweijan** [comment]
You can copy row through the context menu.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/0f53730b-389a-4281-9014-93f93a439360)

**Comment by eml-c2829** [comment]
My bad. It's very nice. Thank you!
