### ISSUE TITLE
运行大sql文件以后结果tab太多

### ISSUE THREAD

**Issue by superceix** [cweijan/vscode-mysql#1151]
类似初始化sql这种，大概几百个语句吧。选了New Tab还是一样，会打开很多result tab导致整个ui都卡住了。

这种初始化sql其实不需要结果窗口，直接一个窗口输出成功失败这些message就行了

**Comment by cweijan** [comment]
谢谢反馈, 我会在下个版本处理, 不过导入SQL更推荐通过右键菜单的导入SQL.
<img width="331" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/27798227/6d55c0a7-55a7-494f-9263-97301d6c9158">

**Comment by cweijan** [comment]
已在版本7.4.0优化
