### ISSUE TITLE
[BUG] I'm unable to update field values

### ISSUE THREAD

**Issue by aproli90** [cweijan/vscode-mysql#1154]
- Database type and version: Postgres 12.14

I tried updating field values using these two methods:
1. Double click on the cell, update value, hit enter
2. Click on zoom-in icon that appears on cell hover, update value, click save

But I'm unable to update values via either method

**Comment by cweijan** [comment]
Hi, now after modification, you need to click the save button or press ctrl/cmd+s to save the data.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/f04fd303-9276-4bff-8385-cac449d28678)

**Comment by aproli90** [comment]
Wonderful. It's working now. Thanks a lot for the prompt response ☺️
