### ISSUE TITLE
How to store connection configs in git and autoload them on other machines?

### ISSUE THREAD

**Issue by AliOsm** [cweijan/vscode-mysql#1155]
Thanks for working on this great extension!

I want to save the configs to my git repo, and allow other developers to autoload them when they clone the repo and open it in VSCode, is this possible?

Other extensions allow to save connection configs in VSCode settings, but this is not possible using this extension.

Thanks!

**Comment by cweijan** [comment]
Yes, but this is a paid feature.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/cd03b5ce-f7ed-47c9-97a7-ff15eec7dbff)
