### ISSUE TITLE
添加类似于datagrip的diagram功能

### ISSUE THREAD

**Issue by WindDancerUBI** [cweijan/vscode-mysql#1157]
![image](https://github.com/cweijan/vscode-database-client/assets/41536285/b779589c-9531-4990-b841-a805d66322a9)

可以添加如图所示的功能吗，即直观显示数据库表

**Comment by cweijan** [comment]
有这个计划, 不过是计划成付费功能, 且短时间内无法完成.

**Comment by cweijan** [comment]
已在7.5.0上线.
