### ISSUE TITLE
[BUG] Stop Execute button breaks off the connection but doesn't actually terminate the query

### ISSUE THREAD

**Issue by johan-maes-kathondvla** [cweijan/vscode-mysql#1159]
- Database type and version: Postgres 15.5

![image](https://github.com/cweijan/vscode-database-client/assets/167075126/ddf669d4-c395-48f4-a160-04d426c3221a)

Clicking `Stop Execute` will terminate the connection but that does not mean that the query is terminated: https://dba.stackexchange.com/questions/81408/is-a-postgres-long-running-query-aborted-if-the-connection-is-lost-broken.

I think this is a dangerous situation since users might not be aware that their query is still running and taking up resources on the database.

My suggestion to implement this would be to retrieve the `pid` from `pg_stat_activity` and then kill the process with `pg_terminate_backend`.

**Comment by cweijan** [comment]
Thanks for the report, I'll try to fix it in the future.

**Comment by cweijan** [comment]
Fixed in version 7.4.2.

**Comment by johan-maes-kathondvla** [comment]
This bug seems to be back, I'm currently using version 7.5.5. @cweijan

**Comment by cweijan** [comment]
This function has not been modified recently. If the stop fails, you can click on any table node and enter the monitor to manually stop.

![image](https://github.com/user-attachments/assets/f474aa41-c319-4b7c-a6fc-f18645df6fed)
