### ISSUE TITLE
Mongodb count 之后的结果在哪里显示?

### ISSUE THREAD

**Issue by ShijayHuo** [cweijan/vscode-mysql#1160]
![image](https://github.com/cweijan/vscode-database-client/assets/36189354/76eb46ab-fda9-4e2c-b3be-601411b59b3a)

**Comment by cweijan** [comment]
谢谢反馈, 目前不行, 会在未来的版本支持.

**Comment by ShijayHuo** [comment]
> 谢谢反馈, 目前不行, 会在未来的版本支持.

好的，静候佳音
