### ISSUE TITLE
[BUG] SSH files not saving changes 

### ISSUE THREAD

**Issue by gzlo** [cweijan/vscode-mysql#1161]
after last update all files changes not saving when i use the ssh conection. 

https://www.loom.com/share/e96aa49dbbce4fec8a07c2c6bf48200a?sid=7488b81d-d440-49aa-875f-a6d1f15c7581

- Database type and version: 7.4.2 2024-5-29

**Comment by cweijan** [comment]
Thanks feedback, I have fixed it in version 7.4.3.
