### ISSUE TITLE
Show Table DDL - Show definition of generated columns

### ISSUE THREAD

**Issue by onwardmk** [cweijan/vscode-mysql#1164]
Thank you for this excellent extension.

When I select Show Table DDL for a table that has a [PostgreSQL generated column](https://www.postgresql.org/docs/current/ddl-generated-columns.html), the definition only specifies the expression result type instead of the entire expression.

Actual:
```sql
example_generated_column text
```

Desired:
```sql
example_generated_column text COLLATE pg_catalog."default" GENERATED ALWAYS AS (
CASE
    WHEN (another_column IS NOT NULL) THEN 'foo'::text
    ELSE 'bar'::text
END) STORED
```

**Comment by cweijan** [comment]
Suported in version 7.4.4.
