### ISSUE TITLE
Lock unavailable [BUG]

### ISSUE THREAD

**Issue by GTonehour** [cweijan/vscode-mysql#1165]
Hello, I hope you're doing well.

I can't see the "lock" symbol in the result pane anymore.

![image](https://github.com/cweijan/vscode-database-client/assets/86954612/202def64-7068-4ac8-a090-a8f70424a243)

- v7.4.3
- PG 15
- VS Code 1.89.1
- Windows 11

**Comment by cweijan** [comment]
In order to reduce unnecessary buttons, the lock is removed. Now you can create a new tab through the code lens or the context menu.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/fc10e7d9-73af-40fc-a665-083a89a06b01)

**Comment by GTonehour** [comment]
Oh, ok. I had read what you added in issue [#1102](https://github.com/cweijan/vscode-database-client/issues/1102), but didn't realize you also intended to remove the icon (SQL clients like DBeaver do include a possibility to "Pin", which you'd call "Lock" to avoid ambiguity with VS Code's "Pin", an existing result tab).

![image](https://github.com/cweijan/vscode-database-client/assets/86954612/ad28d2aa-bcbd-427f-9b00-c87121b7cd21)

But ok, why not :) Thanks for your answer.
