### ISSUE TITLE
AWS Athena

### ISSUE THREAD

**Issue by sharon-clue** [cweijan/vscode-mysql#1166]
I really like the extension so Kudos to everyone who's working on it.
It would be great to have AWS Athena dialect added, I use for now Hive and it somehow works but some things don't.

Would be great if you could add it.

Thanks.

**Comment by cweijan** [comment]
Suported in version 7.4.4.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/54df1cb3-62fb-4d39-8758-6988678cbafb)
