### ISSUE TITLE
etcd支持

### ISSUE THREAD

**Issue by lsm4ming** [cweijan/vscode-mysql#1167]
能否支持一下etcd

**Comment by cweijan** [comment]
已在版本7.4.4支持.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/8e82812b-817f-4525-b241-ae203c4abb75)

**Comment by lsm4ming** [comment]
提个小建议，支持一下key的模糊匹配，目前没有搜索功能，key多的话看起来很费劲

**Comment by cweijan** [comment]
会在下个版本支持.
