### ISSUE TITLE
[BUG] The space of password will be auto removed

### ISSUE THREAD

**Issue by pilanocatu** [cweijan/vscode-mysql#1169]
I tried to connect to my mysql database and got an access denied error.

I found it's because if the password is end up with space, the space will be auto removed when connecting.

I can connect successfully if my password is end up with other character.

**Comment by cweijan** [comment]
OK, I will fix it in the next version. Currently, the form content will be automatically cleaned of spaces.

**Comment by cweijan** [comment]
Fixed in version 7.4.4
