### ISSUE TITLE
PostgreSQL - Include Triggers in Table DDL

### ISSUE THREAD

**Issue by onwardmk** [cweijan/vscode-mysql#1170]
The extension currently doesn't display table triggers. 

It would be nice if:

- Table definitions in the Explorer listed triggers
- Selecting "Show Table DDL" included trigger definitions

**Comment by cweijan** [comment]
You can set the show triggers, after version 7.4.5, the DDL will include the triggers.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/a3a7f9d4-5287-45aa-8613-f9801110a5ee)

**Comment by onwardmk** [comment]
Thank you! 

It's working, but I see an issue with this feature. The trigger definition is duplicated 3 times in both the tree view and the DDL when I right-click on the table and select "Show Table DDL."
<img width="1571" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/126278601/1f0ef5d8-37ba-48d4-baf6-dd6462c30e83">

**Comment by cweijan** [comment]
Try executing this SQL. This is the SQL for the extension to get the trigger.
```sql
SELECT TRIGGER_NAME "TRIGGER_NAME" FROM information_schema.TRIGGERS 
    WHERE trigger_schema = 'public' AND event_object_table='table_name' ORDER BY TRIGGER_NAME ASC
```

**Comment by onwardmk** [comment]
> Try executing this SQL. This is the SQL for the extension to get the trigger.
> 
> ```sql
> SELECT TRIGGER_NAME "TRIGGER_NAME" FROM information_schema.TRIGGERS 
>     WHERE trigger_schema = 'public' AND event_object_table='table_name' ORDER BY TRIGGER_NAME ASC
> ```

Ah okay, I wasn't aware that PostgreSQL defines a trigger per event type (INSERT, UPDATE, DELETE). I'm more familiar with MS-SQL, where you define a single trigger for all event types. Thanks again.

**Comment by cweijan** [comment]
Hi, after investigation, there is actually only one trigger. I will perform deduplication in the next version.
