### ISSUE TITLE
[BUG] Error InvalidStateError: Failed to register a ServiceWorker since Visual studio version 1.90.0

### ISSUE THREAD

**Issue by borriglione** [cweijan/vscode-mysql#1171]
Since the update to Visual studio 1.90.0 I get the error: `Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..`
when opening table results.

Database type and version:

- Visual studio 1.90.0
- Database Client v7.4.4
- Postgres 14.12
- Ubuntu Ubuntu 22.04.4 LTS

```
Error on loading the webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

**Comment by cweijan** [comment]
Just restart VS Code.

**Comment by borriglione** [comment]
Unfortunately not. Still fails also after VS Code restart:
![grafik](https://github.com/cweijan/vscode-database-client/assets/465544/fe4b8861-1401-42b4-95c5-cc0769ec41bd)

**Comment by cweijan** [comment]
This problem is caused by VS Code, not extension. The previous solution was to completely close VS Code, and then reopen VS Code.

**Comment by alisherafat01** [comment]
close and reopen worked for me. thanks
