### ISSUE TITLE
[BUG] SQL Query executes even when user clicks "Cancel"

### ISSUE THREAD

**Issue by GitTorres** [cweijan/vscode-mysql#1173]
SQL queries execute even when user clicks "Cancel" when prompted to confirm the execution.

Example:

Query:
`delete from fin.task`

Prompt:
You are executing an UPDATE statement without a WHERE clause.  Are you sure you want to continue?

Action after user clicks "Cancel":

> 2024-06-08 08:19:42 [ INFO] Executing: delete from fin.task

- Database type and version:
postgres 15.1

**Comment by cweijan** [comment]
Thanks feedback, I will fix it in next version.

**Comment by cweijan** [comment]
Fixed in version 7.4.6.
