### ISSUE TITLE
[提问] 我有一些关于实现 database 插件的问题

### ISSUE THREAD

**Issue by kurt-steiner** [cweijan/vscode-mysql#1174]
大佬你好，我最近对开发vscode 插件很感兴趣，想尝试做一个数据库插件，想从这个项目中找到一些帮助，
我的项目构想很简单，就简单的做个 postgresql 的插件，只查看数据库的信息和数据表的信息，相当于
1. `show databases`
2. `desc table`

我不知道这个项目是怎么查看数据库中有哪些数据表，数据表中有哪些字段的
我原先的想法是通过 ORM 来查询，结果发现没有对应的接口，是该用原始字符串查询吗？

**Comment by cweijan** [comment]
这个仓库是开源的, 你可以自己看源码.. 字段信息获取在[postgreSqlDialect](https://github.com/cweijan/vscode-database-client/blob/main/src/service/dialect/postgreSqlDialect.ts)里.
