### ISSUE TITLE
[BUG]Setting default value error

### ISSUE THREAD

**Issue by SoFTCureOrigin** [cweijan/vscode-mysql#1175]
setting CURRENT_TIMESTAMP to datetime using ix is set like this : "current_timestamp()"  --> (conn:32, no: 1067, SQLState: 42000) Invalid default value for ....

Sould be "CURRENT_TIMESTAMP"

MariaDB 10.11.6

**Comment by cweijan** [comment]
This is not a client problem, you need to change the "current_timestamp()" in your SQL to "CURRENT_TIMESTAMP"
