### ISSUE TITLE
[BUG] Duplicate "" in query

### ISSUE THREAD

**Issue by tmario1508** [cweijan/vscode-mysql#1176]
- Database type and version: PostgreSQL 12.8
zero-length delimited identifier at or near """"

**Comment by cweijan** [comment]
Please provide the complete SQL and tell me how to trigger it.

**Comment by tmario1508** [comment]
> Please provide the complete SQL and tell me how to trigger it.


https://github.com/cweijan/vscode-database-client/assets/31420112/75c4de2c-4fa7-4796-b1a2-044c5b1d14ce

`DELETE FROM ""LabelCharges"" WHERE "id"=1`

**Comment by cweijan** [comment]
Thanks, I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed in version 7.4.8
