### ISSUE TITLE
Wrong @@collation_connection

### ISSUE THREAD

**Issue by MrkikouLIF** [cweijan/vscode-mysql#1177]
On connection to my database, with both the server collation and database collation set to **utf8mb4_0900_ai_ci** the connection collation is **utf8mb4_unicode_ci**.

When I create views or procedures, it results in an "illegal mix of collation" error. 
I need to execute `SET @@collation_connection = @@collation_database;` before creation to avoid this error.

I think this is a bug because the connection collation should match the server or database collation.

### Database type and version:
* Database Client 7.4.4
* mySQL 8.0.30

**Comment by cweijan** [comment]
Thanks for the feedback, I will try to fix this.

**Comment by cweijan** [comment]
This problem is not caused by the client. In version 7.4.9, the startup SQL configuration was added, in which you can configure `SET @@collation_connection = @@collation_database;`

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/eb53ad83-c15d-478c-a5ca-34a7dd57c4ab)
