### ISSUE TITLE
[FEATURE] Remote -> Local Path Mapping

### ISSUE THREAD

**Issue by lankhaar** [cweijan/vscode-mysql#1178]
Hi and thanks for this amazing extension you delivered! :-D

I wondered, would it be possible to provide a path mapping from local to remote so that when the user tries to up-/download a file or directory, it will automatically map the item to the respective location in the application.

![image](https://github.com/cweijan/vscode-database-client/assets/107768491/5d68e3c1-25b4-4694-b93b-dfbbc7e31f47)

Perhaps this could then go hand in hand with new features like an "open in remote" and "upload to remote" context item when right clicking a file in the project tree.

# How it works
- Map a local path to a deployment path ([example](https://www.jetbrains.com/help/phpstorm/creating-a-remote-server-configuration.html#mapping));
- Now you should be able to [upload](https://www.jetbrains.com/help/phpstorm/uploading-and-downloading-files.html#manually)/[download](https://www.jetbrains.com/help/phpstorm/uploading-and-downloading-files.html#download_file_folder) a file without providing local path because it should use the auto mapping if exists;
- So when a mapping is provided, this window should no longer pop up (or it should be prefilled with the mapped path):
![image](https://github.com/cweijan/vscode-database-client/assets/107768491/69e2b878-b905-4212-88b4-d3e3d29825c7)

## Example
- Configure Root of remote project and specify a Deployment path relative to the remote root;
  - Root: `/home/user/sites`;
  - Deployment: `/mysite`;
![image](https://github.com/cweijan/vscode-database-client/assets/107768491/99a1faca-2189-4091-b491-b1b5cc5e2ad4)

**For download:**
- Download file `/mysite/public/index.php` from remote;
- Open dialogue and prefill `vscode-cwd/public/index.php` as download path.

**For upload:**
- Right click file or directory in vscode project tree (eg. `/public/index.php`)
- Select: `Upload to > My connection`
- Upload file to `/home/user/sites/mysite/public/index.php`

**Comment by cweijan** [comment]
I don't understand what this feature does. Is there any other software that provides this feature?

If the path is too deep, you may consider using the favorite.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/4a3f0d23-7504-430e-8f0c-a46b5151cab9)

**Comment by lankhaar** [comment]
Hi @cweijan and thanks for your quick response!

Yes there's other software that provides this functionality. All JetBrains IDE's do for instance.

I have updated the issue with a how it works, I hope it's more clear now :-)

**Comment by cweijan** [comment]
Thanks for the detailed addition, but sorry I don't plan to develop this feature, I think git should be used for code synchronization.

**Comment by lankhaar** [comment]
Hi @cweijan ,
Although I completely respect your desicion on this topic, I'm not really sure why you mention using git for code synchronization. I obviously do and am not requesting this feature so I could deploy entire features to a remote server. There's a lot of use cases where you'd want to sync a file from local to remote or vice versa which doesn't actually involve a replacement of continues deployment. Why support upload/download at all if this is your point of view?

Only reason I requested this feature is because I knew it from Jetbrains products and it was a huge quality of life. I thought perhaps you could also include this since it expands on an existing feature, introducing a huge quality of life to everyone who does use the upload/download for whatever reason.

Again; I completely respect your decision if you indeed decide not to implement it, I love the extension and your work. I just wanted to clear the air the on misconception that this feature is only for code synchronization as a replacement of CD
