### ISSUE TITLE
[BUG]执行页面内全部sql功能无效

### ISSUE THREAD

**Issue by linzefei** [cweijan/vscode-mysql#1179]
- Database type and version:  v7.4.7

感觉更新后bug越来越多了。。。
上次更新后， 执行sql自动新标签功能无效了，被砍掉了？ 这也就算了。凑合用

这次更新后，发现无法执行 【页面内全部sql】了，永远只能执行【第一个分段sql】，吐血了啊

**Comment by cweijan** [comment]
SQL创建新标签这个功能是取消掉了. 你这个无法执行全部SQL是怎么触发的.

新版创建新标签的方式:
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/2be29648-5d9e-4670-9e1c-53a46a6befaf)

**Comment by linzefei** [comment]
假如一个页面内 存在多段sql正常你是支持  每个分开点击【run】

但假如我本身是一个sql 只是间隔开了， 选择执行【全部sql】 就会 分开执行，然后挂掉
![image](https://github.com/cweijan/vscode-database-client/assets/3400820/f6fb205b-16cc-4cb8-9070-f99bb1314912)
我得消除空格，让他们变成一个sql，才能执行
![image](https://github.com/cweijan/vscode-database-client/assets/3400820/08d3158b-08d6-4f81-a62a-3a3795dba424)

即使我选择后， 点击  【执行选中sql】 也会变成 分开执行，然后挂掉
![image](https://github.com/cweijan/vscode-database-client/assets/3400820/b6617f50-524b-4c26-813d-1ecb090442dd)

**Comment by linzefei** [comment]
以前   【执行整个页面sql】  -- 会当做一个sql 来执行
以前  【执行选中sql】  -- 也会把选择部分当做一个sql来执行

**Comment by linzefei** [comment]
还有一个问题。  现在感觉sql改着就突然实时执行了？ 
但这并不一定是我们预期的功能

万一这个sql是一个实验性的  或者 耗时超大的。  并不想执行
你给人家突然执行了。  可能会把 数据库卡爆了

**Comment by linzefei** [comment]
还有一个问题。  现在感觉sql改着就突然实时执行了？ 
但这并不一定是我们预期的功能

万一这个sql是一个实验性的  或者 耗时超大的。  并不想执行
你给人家突然执行了。  可能会把 数据库卡爆了。特别是 现在分段无效的情况下，  后面的 where having等 可能因为分段 没有合并执行，更会卡爆数据库

**Comment by cweijan** [comment]
你是很久没用这个扩展了吧, 这个改动已经改了很久了.

1. 通过换行分割SQL默认启用, 可以在控制台中关闭.
2. SQL默认情况会加分页, 所以不会存在卡爆的情况, 你应该是习惯ctrl+enter来换行, 但是安装扩展后会执行SQL, 这个也可以关闭.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/f70847e8-1e1c-4c1f-8193-30a84eaac7ce)

**Comment by linzefei** [comment]
我说的卡爆是 把数据库卡爆。。。  有些sql没写好，可能数据库就要爆了

**Comment by linzefei** [comment]
我最近也有用啊。。  

我知道  换行可以分割sql ， 但是以前  ctrl+shift+enter的 效果和现在不一样了。  肯定是近期版本修改了

**Comment by linzefei** [comment]
包括执行选中sql 肯定也改了
---

 【执行整个页面sql】 【执行选中sql】 
以前是 把  【整个页面】 或者 【选中部分】 当做一个 完整的sql，即使他们有分段 也合并起来来执行
现在改成了  执行内容里 的  【每一个分段sql】？

能不能把 原来的功能弄回来， 或者拆分出多个不同功能
【整个页面的每个sql分开执行】
【整个页面sql 合并执行】 
【选中的每个sql分开执行】 
【选中sql 合并执行】

**Comment by cweijan** [comment]
哦哦，我明白你的意思了, 以前执行全部SQL不会进行解析, 现在会对SQL进行解析, 解析是为了让批量查询结果显示更准确, 但SQL就不能随意换行了

**Comment by linzefei** [comment]
因为实际上使用时，我们会存储很多sql片段， 然后给各个部分 增加注释，分段方便查看维护。

现在跑起来 就全挂了，  需要把 所有空行全部消除， 变成 挤在一起


本身分段功能 也是会用到。并不想全部关闭
只是在上述场景下， 我们会用 【选中sql】 或者 【全部sql执行
】

**Comment by cweijan** [comment]
那等我下个版本加个新的命令来执行无解析的原始SQL.

**Comment by linzefei** [comment]
就是 以前那种 合并起来不分段的 也是有使用场景的，很多人可能也习惯那样用，增加很多注释换行
这样一搞。一大堆sql就废弃了， 去掉换行 也很丑陋  难维护

新功能支持 批量执行 没错，肯定也有便利的地方，就是旧的最好保留

**Comment by cweijan** [comment]
已在版本7.4.9增加不解析SQL进行执行的命令.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/0ec6df19-1631-4f6f-b1a7-375c4578121d)

**Comment by linzefei** [comment]
验证有效
