### ISSUE TITLE
复制查询结果时带上表头

### ISSUE THREAD

**Issue by zyb284629791** [cweijan/vscode-mysql#1180]
目前针对MySQL或mongodb的查询结果，虽然可以直接复制内容，但是无法和表头一起复制下来，请问后续能否支持此类操作？
另外每条记录都可以展开这个功能也很实用，但是展开之后的内容无法复制，如下图所示，能否在后续功能中也开放复制？谢谢！
![image](https://github.com/cweijan/vscode-database-client/assets/11675735/ed8e02ad-db40-4727-832c-d72da1e47702)

**Comment by cweijan** [comment]
谢谢反馈, 展开有bug复制不了, 会在下个版本修复.. 表头复制无法支持, 这种情况应该使用导出功能.

**Comment by zyb284629791** [comment]
感谢回复，展开复制静待下个版本更新。
表头复制主要应对的场景是有时查询出来了10条结果，但只想复制前几行的部分字段就行，此时若使用导出需要重新编写sql，感觉有点麻烦，还是想偷懒。。。

**Comment by zyb284629791** [comment]
另外请问大佬有支持idea的计划吗？

**Comment by cweijan** [comment]
不会支持, idea插件是Java的, 没办法直接迁移过去, idea自带的data grip就已经很强了.

**Comment by cweijan** [comment]
复制问题已在版本7.4.8修复.
