### ISSUE TITLE
[BUG] command 'mysql.connection.add' not found

### ISSUE THREAD

**Issue by gyeongminK** [cweijan/vscode-mysql#1181]
- Database type and version: MySQL 8.3.0

I've been using this extension for the last few years but today my connections have gone suddenly. when I try to add connection, I got 'command 'mysql.connection.add' not found' error. So I've reinstalled it, but still it dosen't work. 

![스크린샷 2024-06-13 오전 11 33 54](https://github.com/cweijan/vscode-database-client/assets/66426083/e35b14cf-400d-4072-afa5-afbc9a09f511)
![스크린샷 2024-06-13 오전 11 33 59](https://github.com/cweijan/vscode-database-client/assets/66426083/31cdf819-49d3-48f0-a3d0-d198e2494a3a)

**Comment by cweijan** [comment]
Hi, please tell me what version of VS Code you have. The latest version will cause errors in older versions of VS Code, and you can try update VS Code.

**Comment by gyeongminK** [comment]
I updated VS Code and it works! Thank you so much.

**Comment by cweijan** [comment]
Ok, I released version 7.4.8 to fix this issue.

**Comment by davidawon** [comment]
I'm having the same issue, VSC is updated though
