### ISSUE TITLE
授权未过期显示尚未激活

### ISSUE THREAD

**Issue by my57575757** [cweijan/vscode-mysql#1182]
![image](https://github.com/cweijan/vscode-database-client/assets/60951130/e19af6c3-a020-4b1b-91a2-8a51c6deb429)
![image](https://github.com/cweijan/vscode-database-client/assets/60951130/36ff8951-bab7-4ca7-8c19-5236d92bbb8d)
授权未过期显示尚未激活

**Comment by cweijan** [comment]
这个是扩展报错了... 你先安装旧版本, 或者更新下VS Code

**Comment by my57575757** [comment]
感谢已经解决
