### ISSUE TITLE
[FEATURE REQUEST] Parameter behaviour

### ISSUE THREAD

**Issue by LeonISKopp** [cweijan/vscode-mysql#1183]
I really like this extension, but unfortunately i can't really make a use of it because there are really no options to define sql parameter behaviour.

For example at my work, we have many many sqls that have parameter that starts with "@" or "$". It would be great if there is an option to change the indicator of a parameter instead of only ":".

Another thing is, maybe i'm just stupid, you can't really use the parameter in a "in" clause. For example "WHERE visitNr IN (:param)". The behaviour of the parameter is kind of weird, because i can only type one value. If for example i want to type two values, which is intended for the "IN" clause, it would be great if it would work when i do it like this 567, 432 (Two values seperated by a comma). Right now, if i type two values seperated by a comma, it will behave like one value. Also the same with strings 'test1', 'test2'. Please correct me if there is a way to parse two values for one parameter.

**Comment by haiku-p** [comment]
totally agree :D I have this issue for a very long time, thanks for pointing out

**Comment by cweijan** [comment]
Hi, I added the variableIndicator setting in version 7.5.0, you can use it to configure the variable indicator.
```json
{
	"database-client.variableIndicator": [
		":",
		"$"
	]
}
```

**Comment by LeonISKopp** [comment]
Thank you very much for adding this feature. It works like a charm!

**Comment by haiku-p** [comment]
Thank you for the quick response, it is really nice of you
