### ISSUE TITLE
Display Connection Name in public.sql

### ISSUE THREAD

**Issue by onwardmk** [cweijan/vscode-mysql#1185]
Our PostgreSQL database is hosted in Heroku, so the database URL is not human-readable. The comment at the top of `public.sql` looks something like this:
```sql
-- Active: 1234567890987@@ec2-111-22-333-444.compute-1.amazonaws.com@5432@abc123xyz567@public
```

It would be nice if this comment included the connection name, so I can more easily tell which host I'm connected to.

**Comment by cweijan** [comment]
Supported in version 7.4.9.
