### ISSUE TITLE
[BUG]初始化报表或视图不存在问题

### ISSUE THREAD

**Issue by Pumaly** [cweijan/vscode-mysql#1186]
发现最近的版本在初始化连接时会报表或视图不存在，发现是在初始化时会执行“SELECT SID, SERIAL# as SERIAL FROM V$SESSION”，但是用户没有V$SESSION的权限，这样就会导致连接无法使用了
- Database type and version:
- oracle 11g

**Comment by cweijan** [comment]
谢谢反馈, 会在下个版本修复, 执行这个查询是为了能终止正在执行的SQL.

**Comment by cweijan** [comment]
已在版本7.4.9修复.
