### ISSUE TITLE
支持 comment hint 的能力？

### ISSUE THREAD

**Issue by edocevol** [cweijan/vscode-mysql#1187]
https://cloud.tencent.com/document/product/557/47559

```sql	
MySQL [test]> /*sets:allsets*/repair table test.t1;
```

现在注释会被丢弃

**Comment by cweijan** [comment]
谢谢反馈, 现在注释确实会被丢弃, 我会在下个版本解决

**Comment by cweijan** [comment]
目前你可以通过创建一个新的文件, 填入你的SQL, 然后选择下面这个右键菜单来执行
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/bb70254b-e349-4609-975c-fd8ef8114a68)

**Comment by cweijan** [comment]
Hi, 在新版本7.5.0版本保留了MySQL的注释.

**Comment by edocevol** [comment]
<img width="1016" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/9777120/5925f3d8-57ed-4de5-b33d-b36e189ee097">

好像注释和 SQL 被识别成 2 个独立的可执行单元了。

**Comment by cweijan** [comment]
是的, MySQL中注释中执行的SQL是对当前session一直生效的, 能解决你的问题吗

**Comment by edocevol** [comment]
> 是的, MySQL中注释中执行的SQL是对当前session一直生效的, 能解决你的问题吗

不行的，按照腾讯云 TDSQL 的透传语法，需要将 SQL 和注释一起送到服务端才可以的，这个有点类似于 select comment hint，但是要放在 SQL 前面。

<img width="942" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/9777120/0f8bb37d-9172-44bb-92de-c7eecad991e7">

**Comment by cweijan** [comment]
好的, 那等未来的版本支持.

**Comment by cweijan** [comment]
在版本7.5.1中新增了命令`mysql.runSQLWithoutParse`不解析运行SQL, 你可以自行配置快捷键或者通过右键菜单执行.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/c4d468e8-0944-4101-8d30-57c2ba3145f7)

**Comment by edocevol** [comment]
牛的，可以了~
