### ISSUE TITLE
[BUG]在些SQL语句时，按回车键只是想换行，结果老是会自动打出sql关键字，无法回车换行，请尽快修复

### ISSUE THREAD

**Issue by FireWeyyy** [cweijan/vscode-mysql#1188]
VS Code版本为1.90.1

**Comment by cweijan** [comment]
这个并不是bug, 你可以通过completionTriggerKey设置项配置需要触发补全的按键, 你可以尝试移除空格.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/118a7ce9-d04b-4f0d-8235-c96fbecd22ae)

**Comment by FireWeyyy** [comment]
> completionTriggerKey

移除掉空格了，还是不行。只要我空格一次，再回车，就无法换行，一直给我补全关键字。非常奇怪，现在我只能禁用自动补全后再用了。但我大概一两个月使用的时候并无发现此问题。

**Comment by FireWeyyy** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/152156450/f16e5a88-fcf7-4f6e-8e44-493b7dc1a6d5)

**Comment by cweijan** [comment]
原来你说的是面板的, 我以为你说VS Code的编辑器呢, 这个我下版本修复.

**Comment by FireWeyyy** [comment]
OK

**Comment by cweijan** [comment]
已在7.5.0修复.
