### ISSUE TITLE
表索引怎么不见了？

### ISSUE THREAD

**Issue by FireWeyyy** [cweijan/vscode-mysql#1190]
昨天连接了一个数据库做查询，顺带给一些表建了索引，今天重启VScode之后，再连同一个数据库，发现昨天建的表索引都不见了，这是啥子原因？

**Comment by cweijan** [comment]
扩展不会自动删除索引, 你昨天是否开启了事务呢. 或者你在界面右键切换开发者工具, 看看扩展有没有报错.

<img width="483" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/27798227/1fbae6ff-8d8d-474c-b050-baa695e3d57b">

**Comment by FireWeyyy** [comment]
没有发现什么报错。 现在建了索引，重启VScode之后又还在了，奇了怪...  再观察看看，谢谢

**Comment by FireWeyyy** [comment]
没有发现什么报错。 现在建了索引，重启VScode之后又还在了，奇了怪...  再观察看看，谢谢
