### ISSUE TITLE
Add "Run Sql (with Json)" shortcut

### ISSUE THREAD

**Issue by iblea** [cweijan/vscode-mysql#1192]
Please add the "Run Sql with Json" shortcut function.

![image](https://github.com/cweijan/vscode-database-client/assets/25794008/ebe2cd07-abaf-4cd6-8f38-4a6582bc4a1a)

![image](https://github.com/cweijan/vscode-database-client/assets/25794008/74b175d3-0765-4130-8726-af47695552fd)

**Comment by cweijan** [comment]
Thanks feedback, I will support it in the next version.

**Comment by cweijan** [comment]
The command `mysql.runSQLAsJSON` was added in version 7.5.1. You can configure a shortcut key for it.
