### ISSUE TITLE
PG x::typename syntax

### ISSUE THREAD

**Issue by GTonehour** [cweijan/vscode-mysql#1193]
https://www.postgresql.org/docs/current/sql-createcast.html mentions the `x::typename` syntax. For instance:
~~~sql
SELECT '1'::int;
~~~

But your extension interprets "int" as a variable name.

![image](https://github.com/cweijan/vscode-database-client/assets/86954612/83e6d805-dd2b-460a-900c-068b0d1f9036)

Version : PG 15.

**Comment by cweijan** [comment]
Thanks feedback, I will fix it in the next version, you can fix it now by setting the following.

```json
"database-client.variableIndicator": [],
```

**Comment by cweijan** [comment]
Fixed in version 7.5.4.
