### ISSUE TITLE
[FEATURE REQUEST] Add support for 1Password

### ISSUE THREAD

**Issue by wallacewinfrey-spectralogic** [cweijan/vscode-mysql#1194]
At our company, we try to employ [1Password](https://1password.com) wherever we can.

1Password has both an [extension](https://github.com/1Password/op-vscode) for VSCode as well a [Node.js library](https://github.com/1Password/connect-sdk-js). Would it be possible to add support for retrieving passwords from 1password by specifying a reference to the Vault secret in `database-client-config.json`, something like:

`password: "op://vault/item/field"`

FWIW, I am a paying customer. Thanks for your consideration.

**Comment by cweijan** [comment]
I have no plans to do this, it would probably require 1password to support this extension.
