### ISSUE TITLE
在SQL编辑器中取消浅蓝色选中状态

### ISSUE THREAD

**Issue by deyu9999** [cweijan/vscode-mysql#1196]
当鼠标在这个块中时，图中的SQL就好像是选中状态，影响注意力，建议添加是否添加块背景的开关。
![image](https://github.com/cweijan/vscode-database-client/assets/49182673/dc625a73-22f1-4ecb-8523-6d50e300950b)
这个图是鼠标移出块时的显示，才会清爽。
![image](https://github.com/cweijan/vscode-database-client/assets/49182673/f8e16bbb-e5b0-42f7-a38f-2a223b1bcf4a)

**Comment by cweijan** [comment]
这个是你自己启用的, 默认是关闭.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/8e3101b7-286e-4bef-902b-a63fdcfc399f)

**Comment by deyu9999** [comment]
我没有开启啊
![image](https://github.com/cweijan/vscode-database-client/assets/49182673/9bc8b645-efa7-46c5-a4a7-22ab2ac4b419)

**Comment by cweijan** [comment]
那你要检查你是否安装了其他扩展, 不是这个扩展高亮的
