### ISSUE TITLE
[BUG]新创建建表语句时，会不加提示的覆盖已有文件

### ISSUE THREAD

**Issue by deyu9999** [cweijan/vscode-mysql#1198]
- Database type and version:
MySQL

![image](https://github.com/cweijan/vscode-database-client/assets/49182673/37ad81c5-c2d8-41eb-9cd3-183925b25ac5)
已经编辑的文件，覆盖后就丢失了

**Comment by cweijan** [comment]
版本7.5.4更新后不会再自动覆盖.
