### ISSUE TITLE
[BUG] 连接达梦数据库无法显示数据

### ISSUE THREAD

**Issue by pheotry** [cweijan/vscode-mysql#1199]
![image](https://github.com/cweijan/vscode-database-client/assets/43376740/71d1360f-aeed-4a8a-abda-1b1079af0b1c)

可以看到所有的表，甚至可以看到列名，但是无法打开，打开就显示Execute fail : select ....

**Comment by cweijan** [comment]
权限问题, 等我下版本兼容, 你现在点击表的话, 能看到数据吗, 还是只是无法加载列.

**Comment by pheotry** [comment]
> 权限问题, 等我下版本兼容, 你现在点击表的话, 能看到数据吗, 还是只是无法加载列.

记混了，是只能看到表名，别的啥也看不到

**Comment by cweijan** [comment]
试下最新版本7.5.4, 现在不再查询dba_objects.

**Comment by pheotry** [comment]
> 试下最新版本7.5.4, 现在不再查询dba_objects.

可以了
