### ISSUE TITLE
[BUG] Does not abort previous requests

### ISSUE THREAD

**Issue by mirkadev** [cweijan/vscode-mysql#1201]
- PostgreSQL 15

Hey! I think there might be a problem (but I'm not sure). So, when I send a hard request something like `select * from people` - it can take a lot of time. But if I send then something like `select * from people where id = 1` - it can take a lot of time too after the first one

**Comment by cweijan** [comment]
Hi, the extension does not automatically abort SQL queries. If you want to cancel the last long query, you must abort it.

There are two ways to abort:
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/e3eeacbd-88c0-49bd-a331-cda639cd184a)

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/755f55cd-0c0e-4c0d-b0c3-568928bd85ca)

**Comment by mirkadev** [comment]
Hm, looks good. Can you tell me please how I can get to the button `monitor`?

**Comment by cweijan** [comment]
Maybe you disabled the extension's automatic update, please consider upgrading the extension

**Comment by mirkadev** [comment]
My version is v1.3.5, but I don't understand where I can find the button :(

**Comment by cweijan** [comment]
Please update your VS Code and extensions, this issue is meaningless.

**Comment by mirkadev** [comment]
I have this extension 
<img width="522" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/45996373/0fc6a115-aa21-47b9-9263-dd91416ad6eb">

Now I installed this one

<img width="537" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/45996373/7f5e7835-e0fe-4aa4-b56a-f004833f3f7a">


Can you tell me where I can find the button you send me above?

Because I can see this as result:

<img width="951" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/45996373/f70ead47-763e-4145-9455-4d30db376c9f">

But where the button `Monitor`?

**Comment by cweijan** [comment]
Click any table node in the tree view.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/2366ad44-f7ca-446d-9688-4b3c5e4d1605)

**Comment by mirkadev** [comment]
Ah, I see. But it's not convenient as I need to open table in the list. If I have 100+ tables it's unreal. Can you please consider adding this `Monitor` button to the current query result page?

**Comment by cweijan** [comment]
this is a good idea, I will support it in the next version.
