### ISSUE TITLE
Disable MySql

### ISSUE THREAD

**Issue by ldvosdg** [cweijan/vscode-mysql#1205]
- Database type and version:  MySql 7.5.4
Me aparece Disable para urtilizar en Visual Studio Code, por tanto no puedo utilizarla.
![2024-07-09](https://github.com/cweijan/vscode-database-client/assets/87022740/108baf2a-40ae-474a-b22a-d8bbd76c4d26)

**Comment by cweijan** [comment]
This is because you do not trust this extension, please refer to the link below.

https://code.visualstudio.com/docs/editor/workspace-trust
