### ISSUE TITLE
[BUG] Capitalize text when I paste it

### ISSUE THREAD

**Issue by chrisptree** [cweijan/vscode-mysql#1206]
- Database type and version:
When I'm editing a sql file and I copy/paste text, it capitalizes the text even if it is between quotes even if the settings "Capitalize keywords when formatting" if off, but when it is on, it does not capitalize the text.

To reproduce the problem, create a sql file and add it a command like this:

CREATE USER 'username'@'1.2.3.4' IDENTIFIED BY 'BigPassWordWithDifferentLetterCase';

Select the password, and then press Ctrl+X and Ctrl+V. The password will be capitalized. For now, I just do Ctrl+Z to undo the capitalization action.

**Comment by cweijan** [comment]
Please check your VS Code settings or other extensions you installed, Database Client will not process when you paste.

**Comment by chrisptree** [comment]
You were right, it was the Oracle Developer Tools for VS Code does this with its keywordCasing setting. Big thanks. I close the issue.
