### ISSUE TITLE
[BUG] Error: Invalid object name 'WeeklyDashboard.WeeklyDashboard.Authorization'.

### ISSUE THREAD

**Issue by geekox86** [cweijan/vscode-mysql#1207]
Greetings,

Thank you for the amazing and feature rich extension.
I get an annoying error every time I try to save to the database (e.g. after editing a field then clicking on Save).
The error seems to duplicate the schema name. Maybe it should add the database name as a full qualified name.

Error: Invalid object name 'WeeklyDashboard.WeeklyDashboard.Authorization'.

The database name is DbtOEM01, while the schema is WeeklyDashboard and the table is Authorization.

Thank you

- Database type and version:
SQL Server 16.0.4100.1 (Developer Edition)

- Extension version:
v7.5.4

**Comment by cweijan** [comment]
Thanks feedback, fixed in version 7.5.6.
