### ISSUE TITLE
[BUG] Using a SSH tunnel to connect to mysql/mariadb: All configured authentication methods failed

### ISSUE THREAD

**Issue by Offerel** [cweijan/vscode-mysql#1208]
When i enable the SSH Tunnel, to connect to a MariaDB/MySQL server gives me a error message:  `Connection error! All configured authentication methods failed`. However, when i open a SSH Tunnel manually on the shell (Windows/Linux) with `ssh -L 3306:localhost:3306 username@serverhost`, i can connect fine. When im using the shell to open the tunnel, it uses the available ssh-agent without any issues. The server uses elliptic curve keys.

Pluginversion: 7.5.5 2024-7-11

**Comment by cweijan** [comment]
Please try enabling the CBC algorithm.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/28201b09-cc82-4f38-9ed2-41c589d52810)
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/6dc488a9-bb7f-4f48-a63b-259229408ff1)

**Comment by Offerel** [comment]
I have tried that, but it didn't help. The specified algo, key and ciphers are also supported by the server, regardless of whether I additionally activate the cbc keys or not. I have now extracted the private key and saved it as a file. A connection works immediately. I therefore assume that the plugin probably cannot find the key agent. This is the same, not matter, if i use VSCode on Linux or Windows. On Windows i have tried using KeeAgent (Plugin for KeePass) and PAgent from putty suite. On Linux KeePassXC.

Update: using `ssh-add -l` gives me on both system a list of the available keys. So this basically works just fine.

**Comment by Offerel** [comment]
I have retested Linux (since im at home now). There the connection via SSH is working. But the issue on Windows remains. Is there something, i can try to simulate the connection to the SSH Agent?

**Comment by cweijan** [comment]
Thanks feedback. I didn't notice that you were using Windows. Windows environment does not support ssh agent.

**Comment by Offerel** [comment]
I'm using both. But good to know. In this case, i will open the SSH tunnel via shell and ssh-agent on WIndows and using this existing tunnel to connect the db.

**Comment by cweijan** [comment]
Another option is to connect via a configuration private key.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/d34aea32-cfa1-45bc-98c3-fe77f4fd20b0)

**Comment by Offerel** [comment]
yes, this works, but i don't want to save my private key at the windows workstation. But maybe im using a different key, specially for this purpose. Many thx for the hint.
