### ISSUE TITLE
I want a new ID to be automatically assigned when doing "Copy Row"

### ISSUE THREAD

**Issue by tam8** [cweijan/vscode-mysql#1209]
I want a new ID to be automatically assigned when doing "Copy Row"

By the way, as a side note, if there is a number that is missing after deleting a row,
Will that missing number be assigned? I feel like

**Comment by cweijan** [comment]
If you need the id to be auto-incremented, please set the column to be auto-incremented, I don't plan to support it in the client.

Usually auto-incremented columns will not fill deleted rows.
