### ISSUE TITLE
Unable to open terminal for Oracle database[BUG]

### ISSUE THREAD

**Issue by vedrk5672** [cweijan/vscode-mysql#1210]
- Database type and version: Oracle 19c
- getting following error when opening the terminal in oracle database.
TypeError: Invalid URL
	at new URL (node:internal/url:775:36)
	at r.parseUrl (/Users/xxxxxxx/.vscode/extensions/cweijan.vscode-database-client2-7.5.5/out/extension.js:123952:13)
	at r.getCommonInfo (/Users/xxxxxxx/.vscode/extensions/cweijan.vscode-database-client2-7.5.5/out/extension.js:128765:99)
	at Mt.openTerminal (/Users/xxxxxxx/.vscode/extensions/cweijan.vscode-database-client2-7.5.5/out/extension.js:128349:16)

connection is made via connection string as the service type is not option is not available in new connection page foe oracle DB.

**Comment by cweijan** [comment]
Hi, please give me your JDBC URL example, I will support it in future versions

**Comment by vedrk5672** [comment]
jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL= XXXX)(HOST=XXXXX)(PORT=XXXX)))(CONNECT_DATA=(SID/SERVICE=XXXX)))

**Comment by vedrk5672** [comment]
it will be great if it is possible to add the TNS support for the oracle database, something like the database navigator plugin of jetbrains.


I really loved your plugin. It's really great and helpful.
Keep up the good work.

**Comment by vedrk5672** [comment]
any update on this ??

**Comment by cweijan** [comment]
Hi, I added the custom terminal command function in version 7.6.0. Please solve this issue by configuring the terminal command.

![image](https://github.com/user-attachments/assets/562a678c-e335-4a68-9b98-8d0594e38a2f)
![image](https://github.com/user-attachments/assets/86f88993-cc6d-4ff3-82bf-95a759abf9d4)

**Comment by vedrk5672** [comment]
Thanks for the prompt fix, keep up the good work mate, really helpful extension.
