### ISSUE TITLE
[BUG] Deleting documents from elasticsearch index does not work

### ISSUE THREAD

**Issue by EistenGaming** [cweijan/vscode-mysql#1211]
- Database type and version: 8.14

When selecting rows for deletion, the statement shown shows 'undefined' for the '_id' of the document, thus the delete fails for all documents (see screenshot):

<img width="351" alt="Screenshot 2024-07-15 at 09 33 47" src="https://github.com/user-attachments/assets/9a7a09f8-557a-4bb7-b6ac-bc4f7f1a0320">

Can I amend the command template to fix this?

**Comment by cweijan** [comment]
Thanks feedback, fixed in version 7.5.6.

**Comment by EistenGaming** [comment]
Can confirm, works for me now.
