### ISSUE TITLE
[BUG] Oracle 数据库 如果视图的长度太长，查看视图的ddl时候会报错

### ISSUE THREAD

**Issue by joyous-coder** [cweijan/vscode-mysql#1212]
- Database type and version: v7.5.5
![image](https://github.com/user-attachments/assets/db7b2189-e95d-42b7-af29-443adb47380e)

**Comment by joyous-coder** [comment]
个人觉得可以不在sql中进行拼接，而是单独查出TEXT_VC字段后，在js中进行拼接

**Comment by joyous-coder** [comment]
而且从all_views里面取视图定义的时候，这个字段会截取4000个定义的字符，导致定义不完整

**Comment by joyous-coder** [comment]
建议使用
```sql
SELECT DBMS_METADATA.GET_DDL('VIEW', '视图名', '视图所有者') AS VIEW_DDL
FROM DUAL;
```

**Comment by joyous-coder** [comment]
这个获取的是clob，没有4000个字符的限制

**Comment by joyous-coder** [comment]
并且这个获取的语句可以直接执行，修改视图。不需要添加drop了

**Comment by cweijan** [comment]
感谢提供, 已集成到版本7.5.6.
