### ISSUE TITLE
[BUG] clickhouse 多行字符串不支持

### ISSUE THREAD

**Issue by akkuman** [cweijan/vscode-mysql#1213]
- Database type and version: clickhouse

当使用 Heredoc 风格多行字符串时
https://clickhouse.com/docs/en/sql-reference/syntax#heredoc

sql query 上面不会显示 Run

样例
![image](https://github.com/user-attachments/assets/5a598782-c194-412a-8428-fb97dbef4c7c)

**Comment by cweijan** [comment]
谢谢反馈, 我会在未来的版本适配, 目前你可以通过如下右键菜单执行.

![image](https://github.com/user-attachments/assets/3ba8ecb9-e8f4-45bb-9022-1074116f1651)

**Comment by cweijan** [comment]
已在版本7.5.7修复.
