### ISSUE TITLE
[BUG] 根本无法登录

### ISSUE THREAD

**Issue by xiangsx** [cweijan/vscode-mysql#1214]
- Database type and version:
Database Client JDBC v1.3.5
![image](https://github.com/user-attachments/assets/bad74459-155c-4e81-8072-714a56bed154)

密码确定正确，并且试过重置几次密码，都无法登录，点击Login in 始终报 400 错误，并且 github 登录和Login on browser 都无法登录

**Comment by cweijan** [comment]
登录接口是正常的, 可能是被你的代理影响了, 麻烦你在浏览器用开发者工具查看接口的响应情况.

![image](https://github.com/user-attachments/assets/d28f9269-c555-43f3-bb54-6cd6d51db11c)
