### ISSUE TITLE
can not copy password in connections

### ISSUE THREAD

**Issue by Fardin-Rashidifar** [cweijan/vscode-mysql#1216]
Hello and thank you to the dear developers. Recently, it is not possible to copy the password of a connection in the database client connections. If possible, please bring back this feature.

- Database type and version: v7.5.6

**Comment by cweijan** [comment]
What is your operating system? Even in previous versions, it does not support copying passwords (Mac OS and Windows)

**Comment by Fardin-Rashidifar** [comment]
my operating system is Windows 10 and previous versions this bug does not exist...
