### ISSUE TITLE
[BUG] VS Code plugin cannot directly open MySQL client in docker container

### ISSUE THREAD

**Issue by IJing-WishSnow** [cweijan/vscode-mysql#1217]
- Database type and version:

When using the VS Code plugin (Database Client), I found that I couldn't directly open the MySQL client terminal in the MySQL container and was prompted to install MySQL with yum. However, the Redis container can open the Redis client terminal normally. I hope to solve this problem so that MySQL connections can be opened directly in the container like Redis.

**Comment by IJing-WishSnow** [comment]
![image](https://github.com/user-attachments/assets/098539b0-8ae4-4b0a-b0ea-8fb02ce1950c)

**Comment by cweijan** [comment]
Redis client is implemented because there is no other way to execute commands directly for Redis, so it is necessary.

As for the database terminal, it is only used to execute SQL, but executing SQL is the main function of this extension, so I have no plan to implement it.
