### ISSUE TITLE
[BUG] Import SQL not working

### ISSUE THREAD

**Issue by J-Michalek** [cweijan/vscode-mysql#1220]
- Database type and version: PostgreSQL 15

Recently I found out that importing a SQL file no longer works. All it does is opening a new terminal window and running the following command: `brew install libpq` but the SQL is not executed afterwards. Repeated attempts do the same but it outputs: _Warning: libpq 16.3 is already installed and up-to-date._.

**Comment by cweijan** [comment]
Fixed in version 7.5.7.
