### ISSUE TITLE
Linked SQL Folder Sorting

### ISSUE THREAD

**Issue by achmed13** [cweijan/vscode-mysql#1227]
I love the linked folder support under the Query tab, but it is not clear how the files are sorted. Can the files be sorted by name?

Thanks!

**Comment by cweijan** [comment]
Link folders are sorted by file name.

**Comment by achmed13** [comment]
The contents of the folder are not sorted though, see attached screenshot.

![Code_2024-07-26_13-51-11_5eBaWJsCUe](https://github.com/user-attachments/assets/83cf6bd5-9022-4f64-a403-e6fbf75e4a7f)

**Comment by cweijan** [comment]
Oh, I thought you meant folder sorting🥲. File sorting is currently sorted by creation time. I will modify it in the next version to sort linked files by name.

**Comment by cweijan** [comment]
Adjusted to sort by file name in version 7.5.7.
