### ISSUE TITLE
新建或修改表字段的时候如果勾选了不能为null,而默认值又没填的话,麻烦生成的SQL语句默认值为空字符串而不是null,不然总是报错

### ISSUE THREAD

**Issue by flytkgl** [cweijan/vscode-mysql#1228]
新建或修改表字段的时候如果勾选了不能为null,而默认值又没填的话,麻烦生成的SQL语句默认值为空字符串而不是没有默认值,不然总是报错

**Comment by cweijan** [comment]
在最新的版本7.6.1中, 可在添加行的时候, 先输入任意字符串, 然后再删掉, 此时保存就会以空字符串的形式保存.
<img width="628" alt="image" src="https://github.com/user-attachments/assets/7d78aaad-1601-4c0a-b058-c66c36bbaf81">
