### ISSUE TITLE
[BUG] Wrong count rows

### ISSUE THREAD

**Issue by mercurykd** [cweijan/vscode-mysql#1232]
![image](https://github.com/user-attachments/assets/60c39c2a-7551-425c-85a8-fb127c2e777f)

- Database type and version: ubuntu, mariadb

**Comment by cweijan** [comment]
The total number of tables is an estimate provided by MySQL.

```sql
SELECT TABLE_NAME "name",TABLE_ROWS "table_rows" FROM information_schema.tables
```
