### ISSUE TITLE
Which extension is real

### ISSUE THREAD

**Issue by KarChung-Konstant** [cweijan/vscode-mysql#1233]
I found many extensions are the same under you but not sure which one is the correct one?

https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-postgresql-client2
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-ssh

So which one should I install?

**Comment by cweijan** [comment]
Either one will do, they are always updated.
