### ISSUE TITLE
[BUG] Redshift connection uses malformed jdbc string

### ISSUE THREAD

**Issue by bikehead** [cweijan/vscode-mysql#1237]
Database Client JDBC 1.3.5.  Free Tier

I have a postgress connection that is working.
I've added a redhshift connection and entered all my info, but the client uses the postgres jdbc connection string: postgresql://user:password@127.0.0.1:5432/postgres. Even when I enter a custom string: jdbc:redshift://redshift-db.foo.com:5439/temp_db it uses the erroneous postgress one.

No matter how I enter the connection information and then try to connect I get
`connect ECONNREFUSED 127.0.0.1:5432`
showing that it is always trying localhost with the postgres port.

- Database type and version:

**Comment by cweijan** [comment]
The extension does not support connecting to Redshift via jdbc.
