### ISSUE TITLE
DDEV support / new/edit connection via CLI

### ISSUE THREAD

**Issue by Morgy93** [cweijan/vscode-mysql#1238]
Hello,

is there some way to create or update a connection via CLI?
Or is the config stored somewhere to be accessed via CLI?

I am using https://github.com/ddev/ddev which uses a different port for the database on every container start.
Currently, it would require reading the new port after start, go into connection settings from this extension and set the new port.
That's tedious and makes me use different tools which can be launched simply by running `ddev sequelace` for example.

Speaking of it, DDEV offers global variables in those bash scripts that are launching DB clients. (e.g. `$DDEV_HOST_DB_PORT`)
That's why I'd love to know if there is any possibility to edit or change a connection from this extension using bash scripts.

**Comment by cweijan** [comment]
If you are a Premium user, you can create a Workspace-level connection, which will create a settings file in the currently opened folder.

![image](https://github.com/user-attachments/assets/01d91400-3e49-4715-83a8-4c3168055367)
