### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MajorTomMan** [cweijan/vscode-mysql#1242]
- Database type and version:
- elasticsearch version:8.2.0
当我连接elasticsearch以后通过javaapi插入几个数据后,试图通过noSql的显示菜单来进入该index的查询菜单,但是该菜单什么都没有加载出来,并显示以下错误
当前插件版本是7.5.7
加载 Web 视图时出错: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

**Comment by cweijan** [comment]
vscode问题, 重启下vscode
