### ISSUE TITLE
查询结果集能否调整列的顺序？

### ISSUE THREAD

**Issue by vt-rli** [cweijan/vscode-mysql#1243]
<img width="762" alt="image" src="https://github.com/user-attachments/assets/b83a1841-838d-4a1c-a719-057034cd7b78">

比如，只是为了对照方便，想把`day`列移动到`user_id`之前。请问在插件中是否可以如此操作？

**Comment by cweijan** [comment]
在7.5.9支持了列拖拽功能, 需要手动开启, 启用后将无法复制列名.
![image](https://github.com/user-attachments/assets/f0366983-a75d-42f4-94d5-743d701f6d50)

**Comment by damekolla2** [comment]
请问，这个"Darggable Columns" 开关，所在的配置页面，应该如何访问？
谢谢！
