### ISSUE TITLE
Options for ssh

### ISSUE THREAD

**Issue by mercurykd** [cweijan/vscode-mysql#1245]
like
```
    ServerAliveInterval 120
    TCPKeepAlive no
```

exists?

**Comment by cweijan** [comment]
Hi, Database Client enables keep alive by default. I think the connection is interrupted due to network problems. In version 8.0.7, a toolbar is added to quickly reconnect.

<img width="1032" alt="image" src="https://github.com/user-attachments/assets/9dee55af-5f4e-402a-90ee-0d70c7f94f7f" />
