### ISSUE TITLE
[BUG] Can't select MySQL spatial column

### ISSUE THREAD

**Issue by achmed13** [cweijan/vscode-mysql#1246]
- Database type and version:
MySQL 8.0.31

When I try to query a spatial column named `shape`, it looks like there is some sort of search and replace that isn't working properly in DB Client.

This occurs both when I query with an SQL window and when I try to Open Table in New Tab.

Example without the geometry column:
``` select sbid from section_map; ```

> 2024-08-19 13:20:41 [ INFO] Executing: select sbid from section_map LIMIT 500
> 2024-08-19 13:20:41 [ INFO] Result: 500 rows retrieved in 5ms
> 

Example with geometry:
``` select sbid, shape from section_map;```

> 2024-08-19 13:20:45 [ INFO] Executing: select sbid, shape from section_map LIMIT 500
> 2024-08-19 13:20:45 [ERROR] Cannot read properties of undefined (reading 'replace')

However, it works as expected when I reference the column without returning it:
``` select sbid, ST_AsText(shape) from section_map; ```

> 2024-08-19 13:23:13 [ INFO] Executing: select sbid, ST_AsText(shape) from section_map LIMIT 500
> 2024-08-19 13:23:13 [ INFO] Result: 500 rows retrieved in 18ms

I have tried renaming the spatial column with the same results.

Ideally, displaying a spatial column could be one of:
- A placeholder, such as `<blob>`
- The binary data of the geometry
- ST_AsText representation of the geometry

Thanks for a great tool!

**Comment by cweijan** [comment]
Hi, can you provide me the shape text that caused the error?

**Comment by achmed13** [comment]
Upon further research, it looks like it is only a few specific polygons that are causing the problem, so probably not anything to worry about. Thanks!
