### ISSUE TITLE
button for close all connection

### ISSUE THREAD

**Issue by mercurykd** [cweijan/vscode-mysql#1249]
or option "close all connection" on exit

**Comment by cweijan** [comment]
Already supported in version 7.6.1.

<img width="842" alt="image" src="https://github.com/user-attachments/assets/e5adc94a-d0cd-4885-9a5d-5ec677ee0e12">

**Comment by mercurykd** [comment]
I meant the command or toggle icon in the panel where the settings icon is located. If this option is enabled, opening database/nosql tabs will not automatically update connections. That is, all connections will be closed at startup.
![image](https://github.com/user-attachments/assets/beacf233-3d3f-4a2e-8b4c-a60765f80c66)

**Comment by cweijan** [comment]
You can click the collapse button above, and when the links are collapsed, they will not automatically create links.

<img width="690" alt="image" src="https://github.com/user-attachments/assets/94898b5d-9b4e-40bf-8602-365ecae35687">
