### ISSUE TITLE
[BUG] Connections do not exist

### ISSUE THREAD

**Issue by scottmont** [cweijan/vscode-mysql#1250]
- Database type and version: 

Says I have 3 connection but none exist.

**Comment by scottmont** [comment]
![image](https://github.com/user-attachments/assets/a846522d-e284-4b0c-9910-4423e69aacde)

**Comment by cweijan** [comment]
Try editing the configuration in settings.

![image](https://github.com/user-attachments/assets/1ef7f180-3d7b-40ed-8e12-aae11f27d2d2)
![image](https://github.com/user-attachments/assets/0536d273-aaeb-45be-9983-d96e54a4b552)
