### ISSUE TITLE
[BUG]Connection Setting Cannot Export

### ISSUE THREAD

**Issue by tom-miy** [cweijan/vscode-mysql#1251]
I cannot export connection setting to file .
All connection setting scope is `workspace`.
I use it on dev container. but  often connection setting are cleared when rebuild container.  
So it's a problem if you can't export the settings.
```json
{
  "database": {},
  "nosql": null,
  "$schema": "https://cdn.database-client.com/dbclient/schema.json"
}
```

- Database type and version: Postgres 15.5

**Comment by tom-miy** [comment]
Earlier, I displayed the contents of the DB table and when I returned from another vscode(another workspace), it had disappeared.
It wasn't the right time to rebuild the dev container.
I can't export it so I have to recreate it again.
All the connection settings for the 5 connections have disappeared and not a single one remains.

**Comment by cweijan** [comment]
The workspace-level connection will create a file database-client-config.json in the workspace folder. You can back it up manually.

![image](https://github.com/user-attachments/assets/f913d029-622c-4bda-9322-87543184daf6)

**Comment by tom-miy** [comment]
I exported same path in .vscode/database-client-config.json. 
I put it here because I want to exclude it from git.
```
{
  "database": {},
  "nosql": null,
  "$schema": "https://cdn.database-client.com/dbclient/schema.json"
}
```

but now , it not empty.

Although it is not possible to export work space level connection settings, are they output to a file?

I'd like the workspace level settings to be output as well.
If you're not using pro version, you can't use them from the extension, right?

**Comment by cweijan** [comment]
Sorry, I don't understand what you mean by unable to export. The workspace-level connection is stored in .vscode/database-client-config.json. You can only back it up manually. 

If you don't have Premium, it won't take effect.
