### ISSUE TITLE
[BUG] oracle数据库点击跳转到控制台，因为密码中有特殊字段导致登录失败

### ISSUE THREAD

**Issue by joyous-coder** [cweijan/vscode-mysql#1252]
- Database type and version:

![image](https://github.com/user-attachments/assets/c0d84234-211d-49c7-bc36-3c319d8af6ac)
密码中有特殊字符!@#
这个时候登录的时候需要在密码两侧添加上三个双引号，可以成功  """XXX"""
![image](https://github.com/user-attachments/assets/41f462cf-f163-4041-a913-7c5b98d25bbc)

**Comment by cweijan** [comment]
单个双引号能成功吗

**Comment by joyous-coder** [comment]
> 单个双引号能成功吗

必须加三个

**Comment by cweijan** [comment]
Hi, 在7.6.0版本中增加了自定义终端命令的功能, 请自行配置.
![image](https://github.com/user-attachments/assets/562a678c-e335-4a68-9b98-8d0594e38a2f)
![image](https://github.com/user-attachments/assets/86f88993-cc6d-4ff3-82bf-95a759abf9d4)
