### ISSUE TITLE
Oracle Routines (Function/Procedure/Package)

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#1254]
2 year back I took up a issue stating that Oracle routines cannot be updated using Run Selected SQL Command (Ctrl + E)

Now when I checked the same, I found that the same is working now.  

But with one issue. It updates the routine, even if the routine has errors.  

If I execute through sqlplus, it throws error stating the error.

Is it possible to provide a solution for this.  

This is the only negative I see while connecting to Oracle databases.

A video demonstrating the issue is attached.

https://github.com/user-attachments/assets/083dda8e-9b76-4bab-b0c7-9e71c19b9fc8

**Comment by franklinkf** [comment]
Please consider it as a suggestion.  We are using this extension as an IDE for Oracle and MySQL DB related work.  In oracle this is the only handicap we are facing.  At present we are using terminal to update packages.

Thank you

**Comment by cweijan** [comment]
In the latest version 8.0.0, I have rewritten the SQL parser to support PL/SQL parsing. If you are still using this extension, please give it a try. If you encounter any issues, please let me know and I will do my best to resolve them. Thank you!
