### ISSUE TITLE
MySQL Code Completion

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#1255]
While writing MySQL queries and if I select the field names in intellisense, the field is surrounded by a single quote like character.

I am not sure whether this is done by your extension or not.  If it is done by this extension, can you please disable this.

A video showcasing the issue is enclosed

https://github.com/user-attachments/assets/d50a455e-f92f-4944-8d06-0eaa61b06cbe

**Comment by cweijan** [comment]
You can disable it by setting "database-client.escapedAllObjectName". There is currently no visual interface provided. You need to go to VS Code settings to modify it.

<img width="794" alt="image" src="https://github.com/user-attachments/assets/b904dfc1-9b5f-432a-91e3-9dbc27253284">

**Comment by franklinkf** [comment]
Great.  Thank you
