### ISSUE TITLE
Settings to disable prompt

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#1258]
![image](https://github.com/user-attachments/assets/91df98ad-4d6b-436b-8c3e-990de09ea66d)

Can you please provide a settings to disable this message

**Comment by cweijan** [comment]
I will add it to the settings page in the next version, currently you can change it through VS Code settings.
![image](https://github.com/user-attachments/assets/fd59914d-e603-4de3-a2b6-cdb1e086cf71)

**Comment by franklinkf** [comment]
Thank you Sir
