### ISSUE TITLE
[BUG] Query view ctrl+tab keybinding is not configurable

### ISSUE THREAD

**Issue by Jaakkonen** [cweijan/vscode-mysql#1259]
- Database type and version:
   Postgres 15

When opening a a table to view from the sidebar and pressing ctrl+tab I'm supposed to go to the next editor tab in VSCode. However vscode-database-client captures this keyboard press and swaps the rows/columns with its `tab` keybinding.

The plugin doesn't expose this keybinding in the vscode keyboard shortcuts configuration.

**Comment by cweijan** [comment]
Fixed in version 7.6.0.
