### ISSUE TITLE
[BUG]  Large files will be truncated after formatting (大文件格式化后会被截断)

### ISSUE THREAD

**Issue by stfujnkk** [cweijan/vscode-mysql#1262]
- Database type and version: mysql 8.0

![image](https://github.com/user-attachments/assets/4447f41c-99a8-4185-b237-ec4dd0e7f14b)

**Comment by cweijan** [comment]
Hi, 之前是限制解析20万字符, 在最新版本7.6.1中, 将默认限制修改为100万字符, 同时可在设置页修改最大的字符限制.

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/a3fcee87-8fcf-49a4-af78-77ef39b06cf4">
