### ISSUE TITLE
SQL statement for table import is not correct   

### ISSUE THREAD

**Issue by mahakal** [cweijan/vscode-mysql#1263]
When importing data for the table using a JSON file, the following insert statement is emitted:
 
**Execute fail : INSERT INTO category("id","category")  VALUES (nextval(''category_id_seq''::regclass),'Electronics');**

Should be **INSERT INTO category ("id", "category") VALUES (nextval('category_id_seq'::regclass), 'Electronics');** without two single quotes around the sequence.

- Database type and version:
Postgres (PostgreSQL) 15.6

**Comment by cweijan** [comment]
Thanks for the feedback, fixed in version 7.6.5.
