### ISSUE TITLE
[BUG] Unable to get Premium License in `cursor` editor.

### ISSUE THREAD

**Issue by mnioc** [cweijan/vscode-mysql#1267]
- Database type and version:
![image](https://github.com/user-attachments/assets/63a99e4b-6ec3-4254-b8b6-efda61de678f)

![image](https://github.com/user-attachments/assets/15803e24-20a1-4f3f-93e0-4737e688dcda)

How can I get Premium License in `cursor` editor?

**Comment by cweijan** [comment]
Please refer to the link below:
https://database-client.com/#/login/guide

In the next version I will add support for cursor login.

**Comment by mnioc** [comment]
> Please refer to the link below: https://database-client.com/#/login/guide
> 
> In the next version I will add support for cursor login.

Good! thanks!
