### ISSUE TITLE
[BUG] Window settings not kept

### ISSUE THREAD

**Issue by mybigman** [cweijan/vscode-mysql#1268]
- Database type and version:
`Mysql 8`

Doesn't keep window settings. After dragging handle down to make the editor window with more space and clicking pin button, the moment you open the window back up it returns to a single line.

![CleanShot 2024-09-11 at 22 39 33@2x](https://github.com/user-attachments/assets/75c865a1-079a-4504-aa89-a604c7e890e8)

**Comment by cweijan** [comment]
"the moment you open the window", what did you do? After I re-execute the SQL, the editor window will not be reset.

**Comment by mybigman** [comment]
if i stretch the window down to give more space as per below

![CleanShot 2024-09-13 at 16 36 18@2x](https://github.com/user-attachments/assets/2cadbfc2-3569-4817-adcc-a5a0f770d0ff)

Close it and reopen it goes back to default

![CleanShot 2024-09-13 at 16 37 16@2x](https://github.com/user-attachments/assets/acfd753f-32c0-40ff-9f6b-d416bd598c32)

**Comment by cweijan** [comment]
Support remembering editor height settings in version 7.6.1.

**Comment by cweijan** [comment]
Sorry I removed this feature in 7.6.2, because it affected the automatic height of the panel.
