### ISSUE TITLE
[BUG] Explain plan results not adjustable

### ISSUE THREAD

**Issue by mybigman** [cweijan/vscode-mysql#1269]
- Database type and version:
`MySQL 8`

The result of the explain plan window cant be adjusted so its not possible to analyze.

![CleanShot 2024-09-11 at 22 43 34@2x](https://github.com/user-attachments/assets/e6ac1260-55d8-43dc-bb2b-e4a1ae273353)

**Comment by cweijan** [comment]
How did you generate this result? The result I explained is different from yours.
<img width="470" alt="image" src="https://github.com/user-attachments/assets/8309c41a-6619-4730-8628-6628ebdccca2">
<img width="969" alt="image" src="https://github.com/user-attachments/assets/2715402a-0fb5-4d1a-a01f-4aa0c0faad8a">

**Comment by mybigman** [comment]
![CleanShot 2024-09-13 at 16 33 08@2x](https://github.com/user-attachments/assets/aea3d343-b351-4269-888b-2f5792b78959)

**Comment by cweijan** [comment]
Hi, I don't know why your explain result is different, but you can adjust the column width by hovering your mouse over the edge of the column.

<img width="523" alt="image" src="https://github.com/user-attachments/assets/c9805df5-b15d-436f-a7ea-6d3fd96f146d">

**Comment by mybigman** [comment]
yup, your right... I was hovering over the bottom part of the line which doesnt have a handle.

thanks
