### ISSUE TITLE
Records with numbers look ugly.

### ISSUE THREAD

**Issue by shinebayar-ya** [cweijan/vscode-mysql#1270]
![2024-09-12-120105_154x507_scrot](https://github.com/user-attachments/assets/87127a87-905d-463b-9d6d-74bd52ea0430)
Please tell me how to resolve it.

**Comment by cweijan** [comment]
Thanks to your suggestion, the row number has been hidden in version 7.6.1, and an option is provided to control its display. You can also hide the control column.

<img width="1037" alt="image" src="https://github.com/user-attachments/assets/5842dae1-4775-4be7-a142-072d01adea84">
