### ISSUE TITLE
Export Connection to another installed instance

### ISSUE THREAD

**Issue by terrypearson** [cweijan/vscode-mysql#1272]
Hello and thank you for this software. 

I would like to suggest a feature that would be useful. 

**Exporting database connection settings:**
If we could backup a database connection and send it to another user of this extension so they could import the database settings automatically, that would be super helpful.

Thank you again for this software.

**Comment by cweijan** [comment]
Hi, the extension provides configuration export and import in the settings page.

<img width="1052" alt="image" src="https://github.com/user-attachments/assets/c5d13e88-b1ad-4d33-8424-6de5db76e7d7">

For automation, you need to purchase Premium to create a workspace connection and collaborate through shared folders.
<img width="1131" alt="image" src="https://github.com/user-attachments/assets/f6d31d00-dca5-4c9e-ba64-70c02ac04f74">
