### ISSUE TITLE
Font Rendering in MySQL Result View

### ISSUE THREAD

**Issue by shinebayar-ya** [cweijan/vscode-mysql#1273]
The problem occurs when running Arch Linux with i3wm; the values displayed in the result cells look distorted or "ugly." However, this issue wasn't present when I was using Ubuntu 22.04.5 LTS (Jammy Jellyfish), where the font was rendered correctly.

Could someone clarify the font requirements for this extension? Are there any specific fonts that need to be installed to ensure proper rendering? This extension is incredibly useful.

**Comment by shinebayar-ya** [comment]
![result](https://github.com/user-attachments/assets/89042dd2-45cb-49c8-a57c-e259601b8c24)

**Comment by cweijan** [comment]
Are all the pages with abnormal fonts, or just the tables?

**Comment by shinebayar-ya** [comment]
No, it’s only the text with numbers that was affected. But it’s fine now. Did you make any changes? It might be a good idea for someone else to look into making it work reliably in case others run into the same issue.

**Comment by cweijan** [comment]
Thanks for your feedback, the font of the table in the old version was overwritten, I fixed it in the new version.

**Comment by shinebayar-ya** [comment]
I’m really happy with the result. Thank you so much for your help. Wishing you continued success in your work!
