### ISSUE TITLE
[BUG] table format changes when pressing tab when inserting a new record

### ISSUE THREAD

**Issue by stephaneminisini** [cweijan/vscode-mysql#1274]
- Database type and version:
Postgres 16

here is a video: 
https://www.loom.com/share/f7872078d0cd4e2e85b5c3421d2dec95

I'm trying to insert a new row, Click on +, get into a cell, modify, press enter, press tab once or twice to move to next cell and table format is now vertical and not able to change the cell values.

**Comment by cweijan** [comment]
Fixed in version 7.7.3.
