### ISSUE TITLE
SSH Tunneling Issue

### ISSUE THREAD

**Issue by mwinder08** [cweijan/vscode-mysql#1275]
![mysql-ssh-screen](https://github.com/user-attachments/assets/00f7c07c-a978-43cc-9993-be4fe7459c0e)

Hoping someone can provide some insight. I'm able to connect via SSH in the "Main" config without issue, but I receive an error when attempting to SSH tunnel to connect to a remote MySQL database.

I'm on a Windows 11 machine, remote server is Ubuntu. I'm using an SSH key.

Thanks!

**Comment by cweijan** [comment]
You need to switch back to the MySQL panel.

<img width="945" alt="image" src="https://github.com/user-attachments/assets/581585c9-c8c6-41cb-8b44-d1d12e08f226">

**Comment by mwinder08** [comment]
Thanks for the quick response!

I should have clarified that I have the same issue when attempting to connect via the MySQL panel.

**Comment by cweijan** [comment]
Hi, please tell me what operating system you are using, this extension cannot support all ssh tunnels.

**Comment by mwinder08** [comment]
I'm using Windows 11 Home connecting to Ubuntu 22.04.5 server.
