### ISSUE TITLE
[BUG]Loki Connection: selected label isn´t used in generated logql query

### ISSUE THREAD

**Issue by alpex8** [cweijan/vscode-mysql#1276]
- Database type and version: loki

Steps to reproduce:
1. Connect to a loki Database
2. Open Labels Folder 
3. Open a label-folder and see all existing label values in the tree view 
4. Click on a label value

Expected Behavior:  
- A tab opens
- A LogQL Query is generated: {`<label>`="`<label value>`"} |= ``
- log messages are shown where the label with the selected label value is applied.

Actual Behavior:  
- A tab opens
- A LogQL Query is generated: {`job`="`<label value>`"} |= `` (always the label `job` is used instead the selected label)
- There might appear log messages if there are such where the job label with the chosen label value is applied.

Thanks

**Comment by cweijan** [comment]
Thanks for the feedback, it has been fixed in version 7.6.3.

**Comment by alpex8** [comment]
> Thanks for the feedback, it has been fixed in version 7.6.3.

Thanks!
