### ISSUE TITLE
[BUG] Don't Execute Query 

### ISSUE THREAD

**Issue by ljavierrodriguez** [cweijan/vscode-mysql#1280]
- Database type and version:

MySQL v8 
mac os sonoma 
mac m1

I have MySQL installed on docker, i'm connected to MySQL using extension but when i write a query run command doesn't work over query, the command run over query is gone

![image](https://github.com/user-attachments/assets/a35a35af-24e9-40c1-94d4-321bbc11847e)

**Comment by cweijan** [comment]
Check below setting.

<img width="1150" alt="image" src="https://github.com/user-attachments/assets/c7fc2073-136b-4212-8d64-452b6deeb4f0">
