### ISSUE TITLE
为什么redis只能查询结果，而不是根据key去查看

### ISSUE THREAD

**Issue by Jianqing001** [cweijan/vscode-mysql#1281]
为什么redis只能查询结果，而不是根据key去查看，我们常用的方式是根据key来查询结果，而不是根据结果来查key
![企业微信截图_17271657846699](https://github.com/user-attachments/assets/730dcafc-01f7-49ad-9d43-6ac214e15bee)

**Comment by cweijan** [comment]
已在版本7.6.6中支持搜索Field.

<img width="831" alt="image" src="https://github.com/user-attachments/assets/2f153083-49b4-410d-b46d-9896bdfe20c5">
