### ISSUE TITLE
执行存储过程没有返回查询的数据

### ISSUE THREAD

**Issue by abc2809** [cweijan/vscode-mysql#1286]
你好，我刚开始使用扩展，还不太熟悉；
我的存储过程最后会返回数据，但是当我执行后，返回结果只显示了“Execution completed in 51ms”，而没有select的数据，这个是有意设计成这样的吗，还是我哪里的设置需要修改？

**Comment by cweijan** [comment]
抱歉前段这间比较忙没看到, 请问是什么数据库

**Comment by cweijan** [comment]
已在版本7.7.3修复.
