### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LinaGolubeva** [cweijan/vscode-mysql#1289]
When upgrading to a new version, all database connections (and there were 6 of them) were erased and now there is a need to reconnect.
Is this correct?
And the extension header has changed to something strange.

![image](https://github.com/user-attachments/assets/0ce923de-aa2d-4018-b6e7-1fdb3cdb944c)
v7.6.2

**Comment by cweijan** [comment]
It looks like you have duplicate extensions installed (I have multiple extensions published), please check and remove the duplicates.
