### ISSUE TITLE
[BUG] Wrong query generated for enum type columns in Insert New Row By Dialog \ Copy Row

### ISSUE THREAD

**Issue by thatkookooguy** [cweijan/vscode-mysql#1290]
- Database type and version: Postgresql14

When having a table with a column of type enum, insert using dialog or copying row doesn't work correctly.

Example:
<img width="802" alt="image" src="https://github.com/user-attachments/assets/37a45268-807c-41bc-be4d-6169a4e52dfc">

Correct query:
```
INSERT INTO "integrations"("system","systemEmails","systemUsername","systemAvatar","accessToken") VALUES('github','{mock@mock.com}','mocky','https://mock.avatar.com','mock_token');
```
Where `system` (which is an enum) should be passed as a string in single quotes

**Comment by cweijan** [comment]
Thanks for the feedback, it has been fixed in version 7.6.3.
