### ISSUE TITLE
How do I get rid of the intrusive "If you are an premium user, can show definition by hover" popup?

### ISSUE THREAD

**Issue by alexolog** [cweijan/vscode-mysql#1291]
The "If you are an premium user, can show definition by hover" popup is extremely intrusive since it masks the query that the mouse is on.

How do I get rid of it?

Example:
![image](https://github.com/user-attachments/assets/513e118a-3196-4175-bcba-bb097f2b4945)

**Comment by cweijan** [comment]
Only payment.
