### ISSUE TITLE
SSH root priviledges

### ISSUE THREAD

**Issue by madzid** [cweijan/vscode-mysql#1292]
Hi,

I'm trying to setup SSH connection which should be able to elevate user to root at connection since direct root is prohibited.
I need this because I can't browser root owned files when I connect. I tried using "Agent" but it seems it doesn't work since my connection fails.
I've bought this plugin mainly for this purpose and now I don't know what to do?

**Comment by cweijan** [comment]
This plugin lists files via sftp, so permissions are limited to logged in users, I can't help.

If this makes the plugin useless, you can send an email to support@database-client.com to request a refund.
