### ISSUE TITLE
[BUG] 在wsl中安装database client后,无法卸载

### ISSUE THREAD

**Issue by kerojiang** [cweijan/vscode-mysql#1293]
- Database type and version:
database client v7.6.2

在wsl中安装了database client,点击卸载，重新启动程序或重新加载窗口，插件仍然存在，无法卸载掉
![插件卸载](https://github.com/user-attachments/assets/062a5c3d-caab-47b3-b393-428924a4dd29)

**Comment by cweijan** [comment]
跟这个扩展没关系。

**Comment by kerojiang** [comment]
那为什么其他扩展是正常的，就这个扩展不可以？  其他扩展都是可以正常卸载

**Comment by cweijan** [comment]
还真是, 但我没做什么阻止卸载的操作, 这是vscode的bug.

---

提交了问题, 等官方回应: https://github.com/microsoft/vscode-remote-release/issues/10371
