### ISSUE TITLE
Option to display sql and nosql database in one panel

### ISSUE THREAD

**Issue by robinpecha** [cweijan/vscode-mysql#1294]
Option to display sql and nosql database in one panel. Instead of splitting it into two icons.
![image](https://github.com/user-attachments/assets/2e143f6a-bb6b-4bba-8cdd-c2a0db410af7)

Thanks - Robin

**Comment by cweijan** [comment]
You can merge them together by dragging.

<img width="430" alt="image" src="https://github.com/user-attachments/assets/47744925-c0c3-42d2-aac8-e8b76ad7251e">
