### ISSUE TITLE
[BUG] Paid premium version fails to login

### ISSUE THREAD

**Issue by steven-varga** [cweijan/vscode-mysql#1296]
Renewed licence for 30USD, when clicking on 'Login with GITHUB' goes through the notion, then it breaks down at some point. Please see right upper corner. 
 
![image](https://github.com/user-attachments/assets/e6921136-e0f3-47d1-859f-db7c9a89696c)

**Comment by cweijan** [comment]
请参考下面的链接: Please refer to the link below.
https://database-client.com/#/login/guide

If login fails, using the following:
1. Open console:

![](https://database-client.com/resources/console.png)
2. Then Click Login
<img width="561" alt="image" src="https://github.com/user-attachments/assets/1775549a-3d45-482d-a0b1-64976c323b9f">

**Comment by steven-varga** [comment]
Thanks for the quick reply, the suggested steps checked out!  BTW: I am a big fan of your work, even if rarely get to use it. 
![image](https://github.com/user-attachments/assets/30305164-4fc6-468a-ba30-06a2fef45d3f)
