### ISSUE TITLE
[BUG] Conflict with Docker extension

### ISSUE THREAD

**Issue by vedrk5672** [cweijan/vscode-mysql#1298]
- Database type and version: Postgres 16

- While working in Docker Compose file, the docker extensions provides a play button in the editor gutter are for running compose up command, but the database client extension picks up the signal and throws an error

2024-10-14 23:54:47 [ERROR] TypeError: e.getClient is not a function
	

Uploading Screen Recording 2024-10-14 at 11.54.45 PM.mov…

at iWe (/Users/vedant/.vscode/extensions/cweijan.vscode-database-client2-7.6.3/out/extension.js:165507:54)

**Comment by vedrk5672** [comment]
<img width="1440" alt="Screenshot 2024-10-14 at 11 57 05 PM" src="https://github.com/user-attachments/assets/3f228555-bb94-4641-9d5e-0c16ce5328a7">
<img width="1440" alt="Screenshot 2024-10-14 at 11 57 12 PM" src="https://github.com/user-attachments/assets/9056b449-f0af-4306-9e1c-8b09ef587ee3">
<img width="1440" alt="Screenshot 2024-10-14 at 11 57 20 PM" src="https://github.com/user-attachments/assets/732095f0-ebbd-43fb-b71a-abdd6a8c7ec7">

**Comment by cweijan** [comment]
Thanks for the feedback, the latest version 7.6.4 supports configuring connections. Note that you need to create a connection through the database client first.

<img width="1239" alt="image" src="https://github.com/user-attachments/assets/5e2584f6-47c6-4ec7-a5ac-1b79ce3ed0cd">
