### ISSUE TITLE
[BUG] Cant Dump Struct And Data

### ISSUE THREAD

**Issue by Ningthem-Singh** [cweijan/vscode-mysql#1301]
- Database type and version: PostgreSQL ver : 15.5

When Clicking on <kbd>Dump Struct and Data</kbd> on the database it executes this code
```
Executing: set"PGPASSWORD=222222222" && pg_dump -h 127.0.0.1 -w -p 5432 -U postgres ning_laravel >"c:\Users\HP\Desktop\ning_laravel_2024-10-18_154856.sql"
```
which is wrong command as there should not be any <kbd>set"PGPASSWORD=222222222" &&</kbd> for dumping the entire database and so i get error like this
```
Command failed: set"PGPASSWORD=222222222" && pg_dump -h 127.0.0.1 -w -p 5432 -U postgres ning_laravel >"c:\Users\HP\Desktop\ning_laravel_2024-10-18_154856.sql"
'set"PGPASSWORD=9089"' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by cweijan** [comment]
Thanks for the feedback, fixed in version 7.6.4.
