### ISSUE TITLE
[BUG] CTRL + Enter shortcut to run queries doesn't work

### ISSUE THREAD

**Issue by thelinuxlich** [cweijan/vscode-mysql#1303]
If I click on the `Run` link above the query it works, if I use the shortcut I get a error saying "You don't have any connections defined yet. Use the '+' button to add one"

**Comment by cweijan** [comment]
Which extension are you using? It doesn't seem to be this one.

**Comment by thelinuxlich** [comment]
Yeah, I checked and it was SQLTools messing with config. Thanks!
