### ISSUE TITLE
[BUG]Fora do ar

### ISSUE THREAD

**Issue by JohannPDaniel** [cweijan/vscode-mysql#1304]
Estou tentando criar um banco na extensão do VS Code no entanto, quando clico não aparece nada na pagina de conexão.

![image](https://github.com/user-attachments/assets/07c742ec-0f0b-4fee-b1f4-977f3b4922e0)

**Comment by cweijan** [comment]
Your image is not displayed properly.

**Comment by JohannPDaniel** [comment]
Era assim mesmo que estava, sem aparecer nada quando eu clicava para criar uma conexão, parece que já foi resolvido. Agora parece que voltou.
