### ISSUE TITLE
I can't log in to localhost

### ISSUE THREAD

**Issue by tangybluff** [cweijan/vscode-mysql#1305]
I'm trying to use DB Client to log into my local SQL Server; I've tried all possible combinations, checked ports and permissions, but I can't log in. with the mssql extension in vscode I can log in without any issues. I use windows authenticate to login. Is this a bug or am I doing something wrong?

**Comment by cweijan** [comment]
To use this extension, you need to connect through the TCP port. You can check the following link:

https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/configure-a-server-to-listen-on-a-specific-tcp-port?view=sql-server-ver15#SSMSProcedure

**Comment by cweijan** [comment]
Hi, please use windows auth in version 7.6.6.

<img width="1035" alt="image" src="https://github.com/user-attachments/assets/f5d188ba-ecb9-4982-8992-3c2f5ad9e963">
