### ISSUE TITLE
MySQL把数据导出为SQL时对于空值的判断有点问题

### ISSUE THREAD

**Issue by flytkgl** [cweijan/vscode-mysql#1306]
比如我在建表时的语句是``city` varchar(255) NOT NULL DEFAULT '' COMMENT '城市'`,已经设置了NOT NULL和默认值为空字符串,但是导出数据为SQL时city字段对应的值会导出成null,导致我无法使用SQL导回去

**Comment by cweijan** [comment]
谢谢反馈, 已在版本7.6.5修复.
