### ISSUE TITLE
CMD + F in the result of a column like datagrip

### ISSUE THREAD

**Issue by bqrkhn** [cweijan/vscode-mysql#1307]
Datagrip has this feature where if you have a column (like JSONB in postgres) with lot of content, you can do a search within its content only. Example:

![Capture-2024-10-25 at 23 03 12](https://github.com/user-attachments/assets/f55d715e-a8a3-4100-8f40-41a5bba9bbb2)

Do consider it in future releases.

**Comment by cweijan** [comment]
Sorry I won't consider it, please create a new editor via ctrl/meta+n, copy the content and process it.
