### ISSUE TITLE
[BUG] Naive PostgreSQL Timestamps get changed

### ISSUE THREAD

**Issue by pkludig** [cweijan/vscode-mysql#1308]
```
DROP TABLE IF EXISTS timestamp_test;
CREATE TABLE IF NOT EXISTS timestamp_test (
    timestamp TIMESTAMP,
    "list[timestamp]" TIMESTAMP[]
);

INSERT INTO timestamp_test (timestamp, "list[timestamp]")
VALUES ('2024-09-01 00:00:00', '{2024-09-01 00:00:00, 2024-09-01 00:00:00}');

SELECT *
FROM timestamp_test
```

Results in a readout of (2024-09-01 00:00:00, ["2024-08-31T22:00:00.000Z","2024-08-31T22:00:00.000Z"]) despite the list being naive and no conversion to UTC is applicable.

- Database type and version:
PostgreSQL 16.3

**Comment by cweijan** [comment]
Thanks for the feedback, fixed in version 7.6.5.
