### ISSUE TITLE
[BUG] with SQLite, App cannot read, and then deletes, all inserts from other SQlite editors

### ISSUE THREAD

**Issue by edward-jazzhands** [cweijan/vscode-mysql#1310]
- Database type and version: SQLite3

Hello. So I noticed a very serious problem where if I make inserts to a table using a different SQLite editor (ie liteCLI, harlequin, DB Browser, etc), and then I open that sqlite file using Database Client, it **destroys** the existing data. Not only is it not able to see any rows inserted by the other editors, it will _delete_ everything they inserted as soon as Database Client inserts a row.

Unfortunately this is a really serious bug and makes the problem unsafe to use. I will help if I'm able to

**Comment by cweijan** [comment]
I have tested it on both MacOS and Windows, and I did not find this problem. I think it is your client problem, they do not save data in real time, please try DBeaver Datagrip or Navicat.
