### ISSUE TITLE
Configure for Oracle with TSNAMES.ORA file

### ISSUE THREAD

**Issue by javifelices** [cweijan/vscode-mysql#1311]
I know it's not easy to contemplate all the ways of connection, and the extension tries, but is there any way to configure it so that Oracle can pull a TSNAMES.ORA file?

For a certain project we set it up that way, and I was wondering if there was an option for that.

Thanks.

**Comment by cweijan** [comment]
Sorry I don't plan to support TSNAMES. ORA, you can customize the JDBC URL of the connection by enabling "Use Connection String".

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/00cb16df-edc6-4a0f-a7cd-684d4be60a0a">
