### ISSUE TITLE
ER Diagram option not available

### ISSUE THREAD

**Issue by j1nx3d** [cweijan/vscode-mysql#1312]
Hi, I was checking if your extension can create an ER diagram, and found this request:

https://github.com/cweijan/vscode-database-client/issues/1157
from your reply it seems that feature has been added from v7.5.0, I've checked the changelog and it says it's on that version.
https://github.com/cweijan/vscode-database-client/issues/1157#issuecomment-2177225886

but, I have v7.6.3 but it does not show an option to generate a diagram. 

can you tell me where can I found it? 
I'm using code-server v4.93.1, also tried v4.91.1 and vscode on windows.

thanks in advance

**Comment by cweijan** [comment]
Diagram in the navigation bar is currently automatically generated based on foreign key constraints.

<img width="894" alt="image" src="https://github.com/user-attachments/assets/9f8773d9-d44e-46fa-b4d4-c09a4ed26ff8">
