### ISSUE TITLE
[BUG] Mongo 中，在数据展示表格中修改两个及两个数据以上时报错

### ISSUE THREAD

**Issue by simiooo** [cweijan/vscode-mysql#1314]
- Database type and version:
在数据展示区域，同时修改多个表格中数据后，保存提示“db is not defined”
![image](https://github.com/user-attachments/assets/e23fc99e-ba40-4285-9af7-25bdfcff3f88)

**Comment by cweijan** [comment]
谢谢反馈, 已在版本7.6.5修复.
