### ISSUE TITLE
[BUG] Restoring redis dump data fails

### ISSUE THREAD

**Issue by ghost** [cweijan/vscode-mysql#1316]
- Database type and version: redis 7.4.1

- after successful dump a json created with random name: 0_2024-11-06_183718.json
- restore process returns message in terminal: "2024-11-07 11:55:24 [ INFO] Restoring data complete, 208 keys are imported, cost time: 7ms"
- nothing imported / row count still 0
- tried in redis gui / db working regularly
- I'm really need to understand how to decode this format: please just give me a keyword, my db approx~ 1.2GB and i need really
- 
<img width="804" alt="image" src="https://github.com/user-attachments/assets/4687b1e0-cdf6-4981-a097-d14388b11c4f">

**Comment by ghost** [comment]
i need understand how to decode manually

**Comment by cweijan** [comment]
The backed up data is a JSON array, you can parse it very easily, and use the redis restore api to restore the data after reading it.

https://redis.io/docs/latest/commands/restore/

**Comment by ghost** [comment]
> The backed up data is a JSON array, you can parse it very easily, and use the redis restore api to restore the data after reading it. (redis function: async restore(e))
> 
> https://redis.io/docs/latest/commands/restore/

Thanks for your reply cweijan, at last hours i tried and modified extension code to read in stream. Not perfect but working.

`
   ...

    let count = 0
    try {

        let length = 1024 * 1024 * 10
        let remained = ""
        let parseable = ""
        let match = ',{'

        let o = t[0].fsPath,
            a = o.match(/\.json$/i),
            c = [],
            l = (d) => {
                let {
                    key: h,
                    value: p,
                    ttl: E
                } = d, m = n.pipeline().debug(h).restore(h, E < 0 ? 0 : E * 1e3, Buffer.from(p, "hex")).exec();
                c.push(m);

                count++
            };

        new Promise(async (d, h) => {

            let done = false

            let readNext = async (start) => {

                c = []
                let p = c0.createReadStream(o, {
                    start,
                    end: start + length
                });
                let E = Aze.default.createInterface({
                    input: p,
                    crlfDelay: 1 / 0
                });
                let m;
                let lastIndex = -1

                for await (m of E) {
                    try {
                        lastIndex = m.lastIndexOf(match)
                        parseable = remained

                        if (lastIndex !== -1) {
                            parseable = parseable + m.substring(0, lastIndex)
                            remained = m.substring(lastIndex + 1)
                        } else {
                            parseable = remained + m
                            remained = ""
                        }


                        if (parseable.charAt(0) !== "[") {
                            parseable = `[${parseable}`
                        }
                        if (parseable.charAt(-1) !== "]") {
                            parseable = `${parseable}]`
                        }

                        parseable = parseable.replaceAll("::", ":")

                        JSON.parse(parseable).forEach(l)
                        await Promise.all(c)

                    } catch (_) {
                        Te.debug(`${_}`);
                    }

                }

                e.refresh(!0)
                p.close();

                if ((lastIndex !== -1)) {
                    Te.log(`Restoring data continues, ${count-1} keys are imported..`);
                    return readNext(start + length)
                } else {
                    let f = Ea(( /* @__PURE__ */ new Date()).getTime() - s);
                    fg.window.showInformationMessage(`Restoring data complete, ${count-1} keys are imported, cost time: ${f}`);
                    return d(null);
                }
            }

            readNext(0)
        })

    } catch (o) {
        Te.log(o);
    }

    ...
`

**Comment by ghost** [comment]
also i need to say, vscode turned crazy. it's saying possible leak listener etc. i don't know what's meaning but it says hundreds ... :)
