### ISSUE TITLE
[BUG] Timezone setting is not respected

### ISSUE THREAD

**Issue by deiansp** [cweijan/vscode-mysql#1317]
- Database type and version: MySQL 8.0.35

My database is set in the UTC timezone.
I use in the config:
"timezone": "+02:00"
And I expect to see the dates in my local time.

Unfortunately, they are still shown in UTC (VScode restarted).

As an addition, it would be great improvement to have this setting with a timezone string like "Europe/Athens" as we change the time twice per year (+02:00 in the winter and +03:00 in the summer)

![1](https://github.com/user-attachments/assets/88164755-98d5-47b5-a601-b4f891f8dcaf)
![2](https://github.com/user-attachments/assets/c2bd26e2-d79d-4d9c-be36-792aae70817a)

**Comment by cweijan** [comment]
Hi, timezone is a deprecated option, please use startupSQL instead

`SET time_zone = '+02:00';`

<img width="1034" alt="image" src="https://github.com/user-attachments/assets/d668c8d9-37b8-43c8-8cdc-e3e68f77c3b1">
