### ISSUE TITLE
[BUG]SQL scripts with DDL failing on first statement;

### ISSUE THREAD

**Issue by wrishel** [cweijan/vscode-mysql#1318]
Several SQL scripts consisting of DDL are failing on the first line with a syntax error. Other scripts seem to work. The same sql files work with no problem in the MySQL workbench.

The scripts are attached.

- Database type and version:
- # SQL
```sql
SHOW VARIABLES LIKE "%version%"
```
# Data
|Variable_name|Value|
|-------------|-----|
[add_reporting_database_design - Copy.sql.txt](https://github.com/user-attachments/files/17692928/add_reporting_database_design.-.Copy.sql.txt)
[create_database_design - Copy.sql.txt](https://github.com/user-attachments/files/17692929/create_database_design.-.Copy.sql.txt)

|admin_tls_version|TLSv1.2,TLSv1.3|
|immediate_server_version|999999|
|innodb_version|8.0.34|
|original_server_version|999999|
|protocol_version|10|
|replica_type_conversions||
|slave_type_conversions||
|tls_version|TLSv1.2,TLSv1.3|
|version|8.0.34|
|version_comment|MySQL Community Server - GPL|
|version_compile_machine|x86_64|
|version_compile_os|Win64|
|version_compile_zlib|1.2.13

**Comment by wrishel** [comment]
It is also reporting a syntax error on a comment. In "-- Dump completed on 2024-11-08 14:56:18" it complains about the leading zero in '08'.

**Comment by cweijan** [comment]
I executed the SQL file you provided and it was executed successfully. Please tell me what the error you displayed is.

**Comment by wrishel** [comment]
[image: image.png]

-- Wes

**Comment by cweijan** [comment]
Hi, if you want to provide pictures, you can only go to GitHub.

**Comment by cweijan** [comment]
In version 8.0.7, SQL syntax parsing has been better supported.
