### ISSUE TITLE
[BUG] Database Client Dump Postgress Not Work in Windows

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#1319]
Hi

Command failed: set"PGPASSWORD=aaaaaa" && "C:\Users\m\.dbclient\dependency\postgresql\pg_dump16.exe" -h 10.

'set"PGPASSWORD=aaaaaa"' is not recognized as an internal or external command,
operable program or batch file.

**Comment by cweijan** [comment]
Please update to the latest version 7.6.4.

**Comment by mbtolou** [comment]
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2

7.6.3 !!

**Comment by cweijan** [comment]
Thanks for your feedback. The release of version 7.6.4 failed. I have re-released it.

**Comment by mbtolou** [comment]
Hello and good day. This error has occurred again.

**Comment by mbtolou** [comment]
سلام و روز بخیر

در اکسپورت گرفتن اشکال بوجود آمده است.
لطفا بررسی کنید

![image](https://github.com/user-attachments/assets/cead3f6b-14eb-498c-a330-7b530aa0d996)

pg_dump16.exe
liblz4.dll
zlib1.dll
libzstd.dll

**Comment by cweijan** [comment]
Try to delete pg_dump16.exe. The ddl files will be downloaded again during the dump process.

**Comment by mbtolou** [comment]
Only one file is downloaded and it encounters an error again. I tried several times.


pg_dump16

**Comment by cweijan** [comment]
Is your network located in mainland China? This may be due to network problems. You need to download the cli from the postgresql official website.

https://www.postgresql.org/download/windows/
