### ISSUE TITLE
[BUG] Can't import using CSV:  Table does not have the identity property. Cannot perform SET operation.

### ISSUE THREAD

**Issue by code-n-go** [cweijan/vscode-mysql#1320]
Not all tables have an identity property; however, your internal script calls:

SET IDENTITY_INSERT "{TABLE_NAME}" ON

This is causing the imports to fail.  You should make the above an optional flag.

- Database type and version:
MSSQL 16.0.4150.1 Developer Edition

**Comment by cweijan** [comment]
Thanks for the feedback, I will fix it in the next version

**Comment by cweijan** [comment]
Thanks for the feedback, fixed in version 7.6.5.
