### ISSUE TITLE
[BUG] oracle unique index flag

### ISSUE THREAD

**Issue by frtino** [cweijan/vscode-mysql#1321]
Oracle UNIQUEness of index not properly shown in  Properties of table  on which column is unique index set

Index Name	IDX_CSD_DKP
Index Type	NORMAL
**Uniqueness	UNIQUE**
Status	VALID

![image](https://github.com/user-attachments/assets/8a9fe787-922d-468d-ad17-43e655fe5161)

from oracle index table 

`  <DATA_RECORD>
    <OWNER>XYZ</OWNER>
    <INDEX_NAME>IDX_CSD_DKP</INDEX_NAME>
    <INDEX_TYPE>NORMAL</INDEX_TYPE>
    <TABLE_NAME>CASH_DEF</TABLE_NAME>
    <TABLE_TYPE>TABLE</TABLE_TYPE>
    **<UNIQUENESS>UNIQUE</UNIQUENESS>**
    <COMPRESSION>DISABLED</COMPRESSION>`

**Comment by frtino** [comment]
you also generate wrong source code for index

-- index create sql
create **unique** index idx_csd_orp_sn on CASH_DEF(csd_orp_sn)


-- your export
-- Active: 1717504536719@@nectstd-ha-cl.st.sk@1525@flxtstp1@FLEX
CREATE INDEX CASH_DEF_CSD_ORP_SN ON CASH_DEF(CSD_ORP_SN)

-- correct export som Toad
CREATE UNIQUE INDEX IDX_CSD_ORP_SN ON CASH_DEF(CSD_ORP_SN)

**Comment by cweijan** [comment]
Fixed in version 7.6.6.
