### ISSUE TITLE
[BUG] Query stuck on "Loading Foreign Keys" in PostgreSQL

### ISSUE THREAD

**Issue by sersh88** [cweijan/vscode-mysql#1324]
-  Database Type and Version: PostgreSQL 15.4  

When querying any table, the query gets stuck with the status `"Loading database_name#database_name ForeignKeys"` and never completes. If I disconnect from the database and reconnect, sometimes queries work normally.  

This issue happens only in databases with a large number of tables (over 350), mainly partitioned tables. Disabling the Foreign Key feature does not fix the problem.  

Additionally, when trying to list tables for the first time, I often get a `"connection timeout"`. On the second attempt, the tables load, but querying any of them leads to the issue.

**Comment by cweijan** [comment]
Thanks for your report! I will optimize the performance in the next version. Can you provide the log?

<img width="1268" alt="image" src="https://github.com/user-attachments/assets/159a0868-735f-4d33-801c-f07f42bbc641">

**Comment by sersh88** [comment]
![image](https://github.com/user-attachments/assets/6dbc6580-c0e7-4df9-bb84-5a86e3c8ef73)

Nothing in the log.

**Comment by cweijan** [comment]
Hi, in version 7.6.6, metadata loading will use new connections, so it won't affect your queries. Also, you can disable metadata loading through advanced options.

<img width="968" alt="image" src="https://github.com/user-attachments/assets/ddcf36d8-2c25-4b3a-8689-8e01888149f6">
