### ISSUE TITLE
Add multi level table grouping

### ISSUE THREAD

**Issue by sersh88** [cweijan/vscode-mysql#1325]
![image](https://github.com/user-attachments/assets/ac0214fd-7ce6-48e6-8b6f-7b2a0c508fbf)

When working with databases containing many tables (e.g., partitioned tables), even grouping by the first prefix (e.g., content_) does not provide sufficient clarity, as shown in the screenshot.

I propose implementing multi-level grouping. After the initial grouping by the first prefix, the extension should check if additional prefixes within the group (e.g., content_custom_data_parted) are eligible for further grouping and apply it where necessary.

This would significantly improve usability and organization for databases with large numbers of partitioned tables.

**Comment by cweijan** [comment]
Hi, in version 7.6.6 now changed to multi-level grouping.

**Comment by sersh88** [comment]
Hi, thanks for update! But I think it will be better to take into account grouping threshold for all levels. Overwise may be too many levels.
