### ISSUE TITLE
[BUG]ocean database connect failure

### ISSUE THREAD

**Issue by skywalkboy** [cweijan/vscode-mysql#1328]
- Database type and version: 5.7.25 ocean database
- bother use string connection or ui connect ob ,it failure

**Comment by skywalkboy** [comment]
when connect it always show loading metadata...

**Comment by cweijan** [comment]
What database type did you use to connect to the ocean database?

**Comment by cweijan** [comment]
I tried oceanbase and it works fine, you can also disable metadata loading through advanced options.

<img width="951" alt="image" src="https://github.com/user-attachments/assets/3bb23db3-afdf-4edb-8916-fc167960c527">
