### ISSUE TITLE
[BUG] Redis search broken

### ISSUE THREAD

**Issue by Enubia** [cweijan/vscode-mysql#1329]
- Database type and version: Redis (Keydb) latest, DB Client v7.6.5

Redis search breaks with

`TypeError: E.includes is not a function`

weirdly this doesn't happen on all occasions

<img width="867" alt="image" src="https://github.com/user-attachments/assets/675f4752-4a5e-4dea-84ef-291d51af080a">

**Comment by cweijan** [comment]
Fixed in version 7.6.6.
