### ISSUE TITLE
Failed to delete and update for scylla(cassandra) db

### ISSUE THREAD

**Issue by iashraful** [cweijan/vscode-mysql#1330]
### How to produce?
Producing is pretty simple. Let's assume you have a casandra/scylla db. You are connected. So, follow the steps.
1. View a table's data
2. Select one or many and press delete button.
3. You should see the magic of error.

**In Short**: Queries are treating as SQL. But this is not SQL. It's CQL.

**Comment by cweijan** [comment]
Fixed in 7.6.7 version.

**Comment by iashraful** [comment]
Thank you. Working

**Comment by iashraful** [comment]
@cweijan But update is not working while multiple partition key OR partition key along with clustering key.

**Comment by cweijan** [comment]
Thanks for the feedback, I will try to solve it.

**Comment by cweijan** [comment]
Fixed in version 7.6.9.
