### ISSUE TITLE
no sql treeview

### ISSUE THREAD

**Issue by suhli** [cweijan/vscode-mysql#1333]
add no sql(mongo/es) tree view

**Comment by cweijan** [comment]
Please describe your problem in detail.

**Comment by cweijan** [comment]
<img width="449" alt="image" src="https://github.com/user-attachments/assets/5caf7a0d-22dc-4b14-82e7-2ebf0b147d79">

**Comment by suhli** [comment]
> <img alt="image" width="449" src="https://private-user-images.githubusercontent.com/27798227/388474857-5caf7a0d-22dc-4b14-82e7-2ebf0b147d79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDA4NDgsIm5iZiI6MTczMjI0MDU0OCwicGF0aCI6Ii8yNzc5ODIyNy8zODg0NzQ4NTctNWNhZjdhMGQtMjJkYy00YjE0LTgyZTctMmViZjBiMTQ3ZDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDAxNTU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2YmMwMjE5MmU2NDQwNzllZWE0NTA4ZjY2ODE5NjJlNWQ5ZDU3NGIyMGMzNGIzMmZjY2NiYWYzMDAzZWMzY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.71-uqzlS2J6CyRluQwlPWlZZbKkSf9ytCHBdBEeniPQ">

data tree view like datagrip:
![image](https://github.com/user-attachments/assets/9c6999e3-c9cd-4806-b6d4-1449b0654f7a)
