### ISSUE TITLE
[BUG] TimeOut to connect to DuckDB data base

### ISSUE THREAD

**Issue by sinvaldomoreno** [cweijan/vscode-mysql#1335]
- Database type and version: DuckDb 1.1.3 size 2.2GB with 14 tables
- After update the database client MySql from v7.6.5 to v7.6.8 it was unable to open the DuckDB database after creating a connection. Below the image just working fine with v7.6.5 and also an image with connection issue with v7.6.8.

![image](https://github.com/user-attachments/assets/d0bec0fd-e5ef-4ea7-ad15-9c081b83a6c8)

Error with v7.6.8
![image](https://github.com/user-attachments/assets/9bb3e83c-38d3-4337-b60b-b4026eaad5bb)

**Comment by cweijan** [comment]
Thanks for the feedback, fixed in version 7.69

**Comment by sinvaldomoreno** [comment]
Thank you. I just updated and its working fine with the latest version! Congrats for this handy extension!!

![image](https://github.com/user-attachments/assets/572fdacb-ca30-4c04-9230-1103024a3397)
