### ISSUE TITLE
[BUG]HIVE数据库之前正常链接，现在无法链接，显示链接超时

### ISSUE THREAD

**Issue by mxtao12345** [cweijan/vscode-mysql#1336]
HIVE数据库之前正常链接，现在无法链接，显示链接超时
- Database type and version:
包括trino链接也一样

**Comment by mxtao12345** [comment]
使用其他工具正常链接

**Comment by cweijan** [comment]
Hi, 试下重启VS Code, 今天JDBC插件更新了版本.

**Comment by mxtao12345** [comment]
不行，重启后还是不行，没有提示需要更新

**Comment by mxtao12345** [comment]
我用的是 Database Client v7.6.8

**Comment by mxtao12345** [comment]
确实应该是更新了，但是倒退版本仍然不行

**Comment by cweijan** [comment]
你前几天还有用这个扩展吗, 倒退版本后需要把Java进程给关闭下

**Comment by mxtao12345** [comment]
重启电脑成功了……

**Comment by cweijan** [comment]
请问你的JDBC插件是倒退版本的, 还是最新版本的, 我怕扩展自动更新后又出问题了😂.

**Comment by mxtao12345** [comment]
最新版本的，我重启电脑就可以了

**Comment by cweijan** [comment]
好，谢谢反馈
