### ISSUE TITLE
About cloud sync

### ISSUE THREAD

**Issue by jw-cpnet** [cweijan/vscode-mysql#1337]
A little bit worried about the security of this feature. Will the db credentials be synced online? Where will it be stored? Is it encrypted?

**Comment by cweijan** [comment]
Data synchronization of course includes credentials. It is not encrypted by default. You can select an encrypted file for synchronization. After selecting it, AES encryption will be performed when syncing.

<img width="423" alt="image" src="https://github.com/user-attachments/assets/aa39b872-cb45-483b-9f00-8dfb4d1f815c">

**Comment by jw-cpnet** [comment]
Is this documented somewhere? It's an important feature and I believe it deserves proper documentation for those who have the same concerns.

**Comment by cweijan** [comment]
Thanks feedback! I have added sync instructions to the wiki, and will also add a wiki link to the cloud sync in the next version.

https://github.com/cweijan/vscode-database-client/wiki/About-Cloud-Sync
