### ISSUE TITLE
By default when selecting a table make it possible to sort by id DESC.

### ISSUE THREAD

**Issue by Aminadav** [cweijan/vscode-mysql#1338]
I really want this option since most of the time users want to see the latest rows that has been added.
(The column ID is the AUTO_INCREMENT field, or the field with timestamp),

**Comment by cweijan** [comment]
Supported in version 7.7.5.

<img width="1065" alt="image" src="https://github.com/user-attachments/assets/8e5aa86f-77c8-4e98-b4f5-fbbc09bf0d0f">
<img width="778" alt="image" src="https://github.com/user-attachments/assets/f8be11cf-ae0e-4b2a-a7fe-6000cfb9938e">

**Comment by Aminadav** [comment]
King! Thank you.
