### ISSUE TITLE
希望增加阿里云maxcompute支持

### ISSUE THREAD

**Issue by ianzhy** [cweijan/vscode-mysql#1339]
1. 现在的jdbc支持里面无法增加阿里云的maxcompute连接
2. dbeaver能通过jdbc连接maxcompute（参考https://help.aliyun.com/zh/maxcompute/user-guide/connect-dbeaver-to-maxcompute?spm=a2c4g.11186623.help-menu-27797.d_2_0_8_1.6b6a2093TDRKHS），功能实现应该不复杂

**Comment by cweijan** [comment]
Hi, 我看max compute用的是sqlite方言, 在最新版jdbc增加了sqlite方言, 你试试看, 这个太贵我没法开通, 没有测试.

<img width="1151" alt="image" src="https://github.com/user-attachments/assets/5d157457-8423-47a3-bd5c-f5351bd8610c">
