### ISSUE TITLE
[BUG] rendering text values as hexadecimal

### ISSUE THREAD

**Issue by burakozturk16** [cweijan/vscode-mysql#1340]
the result view table shows text values as hexadecimal

- Database type and version: mysql

<img width="719" alt="resim" src="https://github.com/user-attachments/assets/d7029502-6987-4b5a-8bb0-ee2e65f7ce46">

**Comment by cweijan** [comment]
Hi, does this only appear after updating to v7.7.0?

**Comment by burakozturk16** [comment]
I installed v7.7.0 today, i don't know other versions.

**Comment by cweijan** [comment]
Can you try version 7.6.9? I released a new version today, which adds support for binary data. I'm not sure if text is affected by this feature.

<img width="527" alt="image" src="https://github.com/user-attachments/assets/2f205a08-8c8b-43de-b6f6-57f8b141e188">
<img width="685" alt="image" src="https://github.com/user-attachments/assets/da16254f-011d-4be7-88d6-69e8a7ce164e">

**Comment by cweijan** [comment]
Fixed in version 7.7.2.

**Comment by burakozturk16** [comment]
thank you
