### ISSUE TITLE
正常情况下如何打开工具页面

### ISSUE THREAD

**Issue by hnl1** [cweijan/vscode-mysql#1341]
在付费说明界面，有一些工具很好用。正常情况下该如何快速找到这些工具进行使用呢？

<img width="1086" alt="image" src="https://github.com/user-attachments/assets/8c20443b-dbdc-408d-a2a5-27797b7e0b2e">

**Comment by cweijan** [comment]
在设置页里.
<img width="757" alt="image" src="https://github.com/user-attachments/assets/46b37276-dc9e-45ac-88ab-5f315140547c">
