### ISSUE TITLE
Dont Recognize Query Files from Different Profiles

### ISSUE THREAD

**Issue by lerime** [cweijan/vscode-mysql#1343]
When i try to execute queries a query file from another workspace connection. It can not execute. I demands from a database file. I can not see data by clicking table name directly. But executing sql is not possible in my case.
<img width="613" alt="Screenshot 2024-12-05 at 14 41 38" src="https://github.com/user-attachments/assets/858b63d3-85b5-458d-9cb5-28d9a84ebf62">

**Comment by lerime** [comment]
Additionally, this dialog does not close when pressing ESC.

**Comment by cweijan** [comment]
Please check other extensions you have installed. This dialog box is not created by Database Client.

**Comment by lerime** [comment]
It works great right now. I dont know why that happened.
Thanks for interest. Great job as well.
