### ISSUE TITLE
Auto Completion for nosql like mongodb

### ISSUE THREAD

**Issue by shafayetejaman** [cweijan/vscode-mysql#1344]
There is an SQL suggestion for auto-complete but not for NoSQL. For this, the code has to be written in plain Javascript.
it would be better if there were support for auto-complete for NoSQL as well.

**Comment by cweijan** [comment]
Thanks for the feedback, I will support it in the future.

---

Basic completion has been added in version 7.7.5, and the completion capability will be continuously enhanced in the future.

**Comment by cweijan** [comment]
Hi, in version 8.x, we added support for MongoDB collection field completion.

**Comment by shafayetejaman** [comment]
![{4F4EF7CD-DCC3-4DAE-8DC2-3BD6C3E279B9}](https://github.com/user-attachments/assets/f982a9cf-a81c-4220-9317-f12f6fc7d84a)
![image](https://github.com/user-attachments/assets/e82f54ea-4bf3-461f-8864-c8c89693e664)
where are the auto suggestions?
@cweijan

**Comment by cweijan** [comment]
Hi, only field completion is provided, function completion is not supported.

<img width="589" alt="image" src="https://github.com/user-attachments/assets/cc1e91ec-db5e-48da-86b1-446c63bcec5d" />

**Comment by shafayetejaman** [comment]
Why? Is it not easier to implement the function suggestion?
@cweijan

**Comment by cweijan** [comment]
Sorry, actually some collection methods are provided for completion, but there is a bug that prevents it from displaying properly. I will release a version to fix it next Monday.

**Comment by cweijan** [comment]
Hi, I released version 8.0.9 with fixes, providing method completion for databases and collections.

<img width="786" alt="image" src="https://github.com/user-attachments/assets/f07a0b24-ce68-465e-946d-b20737d456fe" />
<img width="1035" alt="image" src="https://github.com/user-attachments/assets/5ed5a64f-b6a8-49e7-a471-88b3a87ace9b" />
