### ISSUE TITLE
Opening SQLite database from link

### ISSUE THREAD

**Issue by JCKodel** [cweijan/vscode-mysql#1345]
When using a local SQLite database on IOS Simulator (in Flutter), I can get a link to my local machine file system where this database resides.

If I use any tool, including this extension, I can see the database, do queries, etc.

But, that folder is random each time I reinstall the app (which happens A LOT during development).

So, I print the current database path in the debug console, where I can Option+Click it:

<img width="1099" alt="image" src="https://github.com/user-attachments/assets/930c537e-3277-4611-8360-8efcb743c159">

The problem is: this will open the file on VSCode itself and since the file is not recognized, it will try to pick a default editor:

![image](https://github.com/user-attachments/assets/d25f3556-6aa9-4d9b-8073-f65bbebb29fa)

The SQLite Viewer extension, by Florian Klampfer, register itself as a valid editor for SQLite and opens the database (problem is: that extension is read-only and don't even allow queries).

So, it would be nice if this extension would register itself as a .db or .sqlite editor and automatically open the database, so we can see the tables, do queries, etc.

**Comment by cweijan** [comment]
Hi, in version 8.0.7, an icon is added to the db file. Click it to quickly add a link to the Database Client.

<img width="877" alt="image" src="https://github.com/user-attachments/assets/6948830d-618a-49b7-8039-84df6d656f31" />
