### ISSUE TITLE
[BUG] Not query table with schema when clicking table node

### ISSUE THREAD

**Issue by htth2820** [cweijan/vscode-mysql#1347]
- Database type and version: **Trino JDBC 464**
- I ticked into option "Query all table with schema when clicking table node" but when I click a table node, table schema not add to query and cause error: Schema must be specified when session schema is not set
- Ex: 
![image](https://github.com/user-attachments/assets/0122b7e2-2867-4b49-9dd7-932ea1637fd1)
![image](https://github.com/user-attachments/assets/2137a9c2-f210-4530-860f-5d08b72d65ab)

Please update or tell me if i'm wrong.

Thanks.

**Comment by cweijan** [comment]
Previously this config was only effective for PostgreSQL and SQL Server, but now supports all databases in the latest version 7.7.6.

**Comment by htth2820** [comment]
> Previously this config was only effective for PostgreSQL and SQL Server, but now supports all databases in the latest version 7.7.6.

Thanks for quickly support.
