### ISSUE TITLE
[Suggest] Quickly view data in table when using Ctrl + Click

### ISSUE THREAD

**Issue by htth2820** [cweijan/vscode-mysql#1350]
Hi @cweijan,

I want to suggest a feature based on BigQuery feature like picture below.
![image](https://github.com/user-attachments/assets/b7960760-e467-48f2-88b8-4471509d5df2)

I hope you can develope this feature to make user more easier when using Database Client.

Thanks!

**Comment by cweijan** [comment]
This is a good idea, I will try to support this in the future, currently you can query data by hovering, but note that this is only available for Premium.

<img width="1056" alt="image" src="https://github.com/user-attachments/assets/92271a65-f70e-4bce-8cb2-7491c6f5c2bd" />

**Comment by htth2820** [comment]
I hope that will be developed soon.
Thanks for your support.

**Comment by cweijan** [comment]
Hi, it is not possible to view data directly by ctrl+click. After version 8.0.0, when you ctrl+click to view the ddl, a codelens of view data will be displayed, which will support quick viewing of data.

<img width="722" alt="image" src="https://github.com/user-attachments/assets/a3c490cf-7d23-4c13-986a-e0653f359ee5" />
