### ISSUE TITLE
[BUG] Queries (except select) in clickhouse over http not working

### ISSUE THREAD

**Issue by mieczkowski** [cweijan/vscode-mysql#1351]
- Database type and version: ClickHouse 23.3.1.2823 with LB before

I noticed that direct connection over TCP works fine (both doing queries and viewing tables/details in left panel).

With connection over HTTP in left panel I can see tables and preview of data for table:
![image](https://github.com/user-attachments/assets/8e59e912-b4ac-42c2-9bd7-0839a90bb905)

But query execution **except select** in editor returns error:

![image](https://github.com/user-attachments/assets/07c186e9-883c-4db6-92bf-d5345b19a133)

Select queries works:

![image](https://github.com/user-attachments/assets/3c6c0600-9aa8-4003-a75c-3132a7aa4dd5)

**Comment by cweijan** [comment]
Thanks for your report. It seems that there is an error when the extension parses the response. Can you confirm whether the SQL is actually executed successfully?

**Comment by mieczkowski** [comment]
Yes, I didn't noticed that query is successfully executed.

Now I can see that problem is when I create table on cluster:
![image](https://github.com/user-attachments/assets/349b6ed9-33a5-46ba-b55e-610c6e338283)

![image](https://github.com/user-attachments/assets/d760dfa9-bb1f-4778-8232-df505bfe0ecf)

Insert is ok:

![image](https://github.com/user-attachments/assets/b87add71-b2e2-42d0-a026-70aee1b157d2)

Without cluster create is successful:

![image](https://github.com/user-attachments/assets/9c8c12c4-9315-49e3-a8a7-4f4ecbec8c1c)

**Comment by cweijan** [comment]
Thanks for the feedback! I'll try to fix this bug as soon as possible.

**Comment by cweijan** [comment]
Fixed in version 8.0.3.
