### ISSUE TITLE
[BUG] bigint类型插入和更新操作导致后三位变为000

### ISSUE THREAD

**Issue by ming2882** [cweijan/vscode-mysql#1355]
- Database type and version:
- mac里表id是bigint时增加和更新都会出错，bigint的后三位变成了000

**Comment by cweijan** [comment]
你的bigint是不是有zerofill呢.

<img width="691" alt="image" src="https://github.com/user-attachments/assets/dcd5b3f1-330c-47ae-ab52-b33df0d9c57a" />

**Comment by ming2882** [comment]
<img width="339" alt="image" src="https://github.com/user-attachments/assets/3c40b8a3-b1d8-4514-9286-981e4872802c" />

**Comment by cweijan** [comment]
请问数据库版本是多少呢, 我去测试下.

**Comment by ming2882** [comment]
<img width="353" alt="image" src="https://github.com/user-attachments/assets/f3b90252-eb2e-4d76-af2e-e3f64c9ce6a0" />

**Comment by ming2882** [comment]
<img width="878" alt="image" src="https://github.com/user-attachments/assets/8a283368-084a-452b-9260-503c77f5665e" />
这是另一个问题，修改后不能提交；主键id也是bigint，不知道是不是也是这个问题引起的

**Comment by cweijan** [comment]
找到问题了，是因为bigint超出int精度，会在下版本修复

**Comment by cweijan** [comment]
已发布版本8.0.7修复.
