### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by Ren842487118** [cweijan/vscode-mysql#1357]
深夜加班暴躁已平复，建议下方描述hhhhh

**Comment by cweijan** [comment]
想反馈问题就好好反馈, 你反馈了几个不错的点, 但github issue不是像你在贴吧和人对线的场所, 你这描述让人看了生理不适.

**Comment by Ren842487118** [comment]
> 想反馈问题就好好反馈, 你反馈了几个不错的点, 但github issue不是像你在贴吧和人对线的场所, 你这描述让人看了生理不适.

大半夜加班搞的气急败坏了，一只在找哪里问题没想到是插件bug

**Comment by Ren842487118** [comment]
> 想反馈问题就好好反馈, 你反馈了几个不错的点, 但github issue不是像你在贴吧和人对线的场所, 你这描述让人看了生理不适.

深夜日常挠头暴躁，多担待hhhhh
1.  改行数据会保存后会保存到其他行
2. 快捷修改一列选中数据
3. 快捷新增行 例如 enter 和 pgdn
4. 部分字段默认值该有的空操作没有
5. 多个sql query文件应该多session而不是单session 有时候想测试性能时还得再打开哥vscode项目然后再链接一次
6. 属性列表缺少字段上下更换位置操作
7. 快捷copy数据 例如选中三行 copy后粘贴快捷添加
8. 链接除了分组建议增加颜色区分或者其他显著区分，最好可以在打开的标签上也做上显著区分，作为技术干活时间长了有时候脑子会混一迷就改错了库的数据

**Comment by cweijan** [comment]
好的好的, 谢谢你的反馈, 我现在全职开发这个扩展, 有价值的反馈都会在未来持续实现和修复的.

**Comment by Ren842487118** [comment]
> 好的好的, 谢谢你的反馈, 我现在全职开发这个扩展, 有价值的反馈都会在未来持续实现和修复的.

项目很好，刚深夜加班暴躁了hhh，后续会持续购买支持希望越来越好👍
