### ISSUE TITLE
why "不再创建单独的筛选器行。"？

### ISSUE THREAD

**Issue by Zemelee** [cweijan/vscode-mysql#1359]
为什么要取消 单独的筛选器行  此功能，我好需要这个功能的😭😭😭
恳求作者大大添加此功能，经常需要对某个数据手动修改😭😭😭

**Comment by cweijan** [comment]
移到表头了, 之前的filter行影响美观, 且容易产生编辑行号异常的bug.

<img width="885" alt="image" src="https://github.com/user-attachments/assets/a98bcd00-5505-40f5-abea-ccf2db613e6a" />
