### ISSUE TITLE
[BUG] Error compiling MySQL Procedure

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#1360]
- Database type and version: MySQL Version 8.0.28

After todays update, we are facing issues in compiling MySQL procedures.  A sample procedure is enclosed.  The same was working till yesterday.

Request your attention

[111.txt](https://github.com/user-attachments/files/18176104/111.txt)

**Comment by cweijan** [comment]
Sorry for this situation. In the latest version 8.0, I rewrote the SQL parser (now supports Oracle). The SQL you used as an example caused parsing exceptions because of the use of the tag `GCODE:BEGIN`. Are there other SQL parsing failures besides this?

**Comment by franklinkf** [comment]
No. Only this only we noted. As we are solely using this extension for MySQL, we are now working by installing a previous version of the extension.  Once the above issue was settled we will proceed with the latest version and check for other errors, if any

Thanks

**Comment by cweijan** [comment]
Thanks for the feedback, I've released version 8.0.4 with the fix, please try it!

**Comment by franklinkf** [comment]
Thanks. Now working fine.

Have you added any auto formatting options to the SQL File.  Nowadays my SQL files formatting got changed automatically.

**Comment by cweijan** [comment]
Please check the link below, this is because your vscode settings cause SQL to be automatically formatted, not controlled by the extension:

https://github.com/cweijan/vscode-database-client/issues/987

**Comment by cweijan** [comment]
I will specify in the next version that SQL will not be automatically formatted by default, now you need to configure it yourself.

**Comment by franklinkf** [comment]
Thanks.  One more issue. 

Database Client - Change Active Connection option not showing the connection names. Instead it is showing some junk numbers

![image](https://github.com/user-attachments/assets/df40313e-46b9-43d4-9d92-493e384695e0)

**Comment by cweijan** [comment]
Thanks for the report, fixed in version 8.0.8.

**Comment by franklinkf** [comment]
Now OK. One more doubt.  Whether VS Code settings sync will sync DB Connections also?  If so, please provide an option to disable the same.  Because, I am working in two envionments and the connection settings are different for the same database in two environments

**Comment by franklinkf** [comment]
One more issue found. Under the option, change active connection - System is displaying full users under a mysql DB, even if we specify one user name in show databases

![image](https://github.com/user-attachments/assets/7ba9a2c3-af82-4874-a765-fddd77ccca4b)
![image](https://github.com/user-attachments/assets/595232dc-ebd2-4675-9805-7d794e1f5593)

**Comment by cweijan** [comment]
Hi, regarding your question:
1. The connection will only be automatically synchronized if you enable autoSync in the settings panel, which is disabled by default.
2. I will hide the redundant database in the next version.

<img width="1057" alt="image" src="https://github.com/user-attachments/assets/2c48c326-a176-47bd-b26c-dd7b62b093bc" />

**Comment by franklinkf** [comment]
One more issue.  In Cursor AI, I cannot invoke the connection.  I am getting the message Dashboard (Dead)

![image](https://github.com/user-attachments/assets/04b895f2-dc3f-4f9b-b193-1432e283bdc0)

**Comment by franklinkf** [comment]
> Hi, regarding your question:
> 
> 1. The connection will only be automatically synchronized if you enable autoSync in the settings panel, which is disabled by default.
> 2. I will hide the redundant database in the next version.
> 
> <img alt="image" width="1057" src="https://private-user-images.githubusercontent.com/27798227/398400502-2c48c326-a176-47bd-b26c-dd7b62b093bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwNDA1ODksIm5iZiI6MTczNTA0MDI4OSwicGF0aCI6Ii8yNzc5ODIyNy8zOTg0MDA1MDItMmM0OGMzMjYtYTE3Ni00N2JkLWIyNmMtZGQ3YjYyYjA5M2JjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDExMzgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZjAzZWI5MzlhZjA0YzJmNGQxYzUxZmYwODg0MTI4NmY2MTdhZDhlZDJlMDhjOGM0NTcyZWM0ZTY2MDhkYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WKHXlsnJDQnDlLQjrJL0vW-Etdkhp9Q0HrsuUchvkFc">

Thanks

**Comment by franklinkf** [comment]
![image](https://github.com/user-attachments/assets/0ec0f74c-1a7f-4e48-bb02-3ec91f152aef)

I am getting this message while connecting (Dashboard - Dead).  What might be the reason.  The DB is up and running

**Comment by cweijan** [comment]
Thanks, it seems that the active status detection is inaccurate, I will fix it in the next version.

**Comment by franklinkf** [comment]
Thanks

**Comment by franklinkf** [comment]
After the latest updates, formatting of mysql procedures updated using the extension disappears.  

A sample procedure is created to demo the scenarios. Please see the video given below:

https://github.com/user-attachments/assets/569c12eb-4a06-4107-9614-9db15b8cfec8

Think that blank lines are omitted during update.  This change happened after the update somewhere during last week

Request your immediate intervention

Thank you

**Comment by cweijan** [comment]
Thank you for your feedback. This is also a problem caused by version 8.x. Maybe you should go back to version 7.7.6 temporarily. I will fix it in the next version.

**Comment by franklinkf** [comment]
OK. Thanks

**Comment by cweijan** [comment]
Hi, I have released 8.0.9 fixes. I am sorry that 8.x version brought you so many bugs. I would like to give you two years of Premium. Please tell me your email address. You can reply directly or send an email to support@database-client.com.

**Comment by franklinkf** [comment]
> Hi, I have released 8.0.9 fixes. I am sorry that 8.x version brought you so many bugs. I would like to give you two years of Premium. Please tell me your email address. You can reply directly or send an email to [support@database-client.com](mailto:support@database-client.com).

Thank you for your generous offer.  My eMail address is franklinkf@gmail.com.  I am already a premium user

**Comment by franklinkf** [comment]
8.0.9 still not visible in the updates

**Comment by cweijan** [comment]
Hi, I have added two years of Premium to your account, I will continue to check this issue.

**Comment by franklinkf** [comment]
> Hi, I have added two years of Premium to your account, I will continue to check this issue.

Thank you
