### ISSUE TITLE
SSH terminal reconnect

### ISSUE THREAD

**Issue by elmenshawy90** [cweijan/vscode-mysql#1361]
when I leave an opened terminal and it timeout, I need to search in servers to open a new session, if you can add a reconnect feature for the timeout session, it will be valuable

**Comment by cweijan** [comment]
Supported in version 8.0.7.

<img width="1032" alt="image" src="https://github.com/user-attachments/assets/8887cb64-0906-46ad-8317-61819fa53b73" />
