### ISSUE TITLE
[BUG] Remove the ndjson language

### ISSUE THREAD

**Issue by remcohaszing** [cweijan/vscode-mysql#1362]
Remove the `ndjson` language.

This extension registers the `ndjson` language ID. In the upcoming version of Visual Studio Code, `.ndjson` files will use the `jsonl` language ID. (https://github.com/microsoft/vscode/pull/235921)

**Comment by cweijan** [comment]
Thanks for your report. Since Database Client will try to keep compatibility with older versions of VS Code, I will remove ndjson in the next version and point ndjson to jsonl by defining the default settings. In the future, this configuration will be completely removed.

```json
{
  "contributes": {
    "configurationDefaults": {
      "files.associations": {
        "*.ndjson": "jsonl"
      }
    }
  }
}
```

**Comment by cweijan** [comment]
Removed in version 8.0.5.
