### ISSUE TITLE
Unable to open file in .dbclient

### ISSUE THREAD

**Issue by robinpecha** [cweijan/vscode-mysql#1363]
Hi, I was not able to connect to elasticsearch thanks to this error:
![image](https://github.com/user-attachments/assets/0628d0f7-5bd3-43fb-8fa3-78d2e37e766a)

I have deleted connection,recreated and problem appears again. Other Elastic connections are working fine.
Problem was solved by creating mentioned path and file manually.

**Comment by cweijan** [comment]
Sorry for this issue, I have released version 8.0.5 with a fix.
