### ISSUE TITLE
Output TypeError Logs

### ISSUE THREAD

**Issue by akce1** [cweijan/vscode-mysql#1364]
Hi,

I hope you're well.

I've been using the vscode-mysql-client2 extension to connect to my work database, and it has been incredibly useful and functions as intended. However, every time I open VS Code, I encounter numerous error logs related to the extension. Below is a snippet of the errors displayed in the Output panel:

```
[ERROR] TypeError: Invalid URL
    at new URL 
    at r.parseUrl
    at Lt.getConnectTarget
    at Lt.bindToolTip
```
 
Details:
- Extension Version: 8.0.5
- Operating System: Windows 10

Steps to Reproduce:
- Open VS Code.
- Observe the error logs in the Output panel under the extension's logs.

What I've Tried:
- Verified Connection Settings: My MySQL connection details are correctly formatted and the database functions as expected.
- Updated the Extension: Ensured that I'm using the latest version of vscode-mysql-client2.
- Reinstalled the Extension: Uninstalled and reinstalled the extension to rule out corruption.
- Despite these attempts, the error logs continue to appear, although they don't seem to impact the functionality I rely on. I wanted to address these errors to ensure long-term stability and prevent potential issues down the line.

Could you please assist me in resolving these error logs? If more information is needed, I'm happy to provide it.

Many thanks for your support and for developing such a helpful extension.

Best regards,
Anis

**Comment by cweijan** [comment]
Sorry for this problem, I will fix it in the next version, now you can fix it by following the steps below:
1. Open Settings, then Edit Configuration.
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/a11d908e-99a7-4170-9361-00e668ead86c" />
2. Search for connectionUrl, find the wrong url, if you don't need it, delete it.

**Comment by cweijan** [comment]
In version 8.0.7, the log of failed URL parsing will output the wrong connection url, please check and fix it yourself.
