### ISSUE TITLE
SECURITY OF MY PERSONNAL DATA 

### ISSUE THREAD

**Issue by xds74** [cweijan/vscode-mysql#1367]
Hello, I would like to know what guarantees that our personal data is not sent and remains private?

**Comment by cweijan** [comment]
Hi, this extension follows VS Code's telemetry settings, if you set it, then your data will not be sent.

https://code.visualstudio.com/docs/getstarted/telemetry

For a description of Database Client telemetry, please see here:
https://github.com/cweijan/vscode-database-client?tab=readme-ov-file#telemetry-reporting
