### ISSUE TITLE
feat: Maintain line selection visibility while scrolling horizontally

### ISSUE THREAD

**Issue by zhanghoufu** [cweijan/vscode-mysql#1368]
When a line is selected and the user scrolls horizontally using the bottom scrollbar, the selected line should remain visually highlighted. Currently, the line selection highlight disappears after horizontal scrolling, making it difficult to track the selected line.

This feature enhances user experience by:
- Maintaining visual feedback of the selected line during horizontal scrolling
- Improving code navigation and readability
- Preventing loss of context when reviewing wide lines of code
![image](https://github.com/user-attachments/assets/5e736b6a-3986-495c-babc-4923b3e3ac3d)
![image](https://github.com/user-attachments/assets/58d12652-6622-4806-a1df-3c5d14f940d1)

**Comment by cweijan** [comment]
Selected rows are highlighted in version 8.0.7, note that since the table uses virtual scrolling, the highlighting will be lost when you scroll quickly.
