### ISSUE TITLE
Feature: SSH session duplication

### ISSUE THREAD

**Issue by elmenshawy90** [cweijan/vscode-mysql#1369]
when troubleshooting something using SSH, I need to duplicate the current session but this feature doesn't exist yet, 
if possible add a session duplication button to allow me to open another session

**Comment by cweijan** [comment]
Hi, In version 8.0.8, a new button is added for duplicate connection session.

<img width="1079" alt="image" src="https://github.com/user-attachments/assets/2a132896-2aca-4c3e-a01d-4e3d3c5ce35c" />
