### ISSUE TITLE
[BUG] Windows环境下SQLite无法正常使用

### ISSUE THREAD

**Issue by Mafa-Qyc** [cweijan/vscode-mysql#1370]
- Database type and version: sqlite
- sqlite数据库提示"sqlite is not installed" ,下载后提示"dowload success",之后无法打开数据库，重新下载
- 数据库无法打开
- 
![image](https://github.com/user-attachments/assets/e909642a-5282-4dea-b86b-a239382ebb67)

**Comment by cweijan** [comment]
感谢报告, 已在版本8.0.8修复.
