### ISSUE TITLE
MongoDB auto generate query

### ISSUE THREAD

**Issue by YanRong0717** [cweijan/vscode-mysql#1376]
I click "Open in New Tab" in my collection, it help me generator query 
`db('MyDbName').collection('MyDbName.CollectionName').find({}).limit(100).toArray()`

but I can't see data result, until, I edit this query code to 
`db('MyDbName').collection('CollectionName').find({}).limit(100).toArray()`

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version. Currently you can fix it by unchecking "Query all table with schema when clicking table node"

<img width="966" alt="image" src="https://github.com/user-attachments/assets/a922546b-45d4-44a5-b56a-84d86e114245" />

**Comment by cweijan** [comment]
Fixed in version 8.0.9.
