### ISSUE TITLE
hope to have a function executing one sql with ';' separated in sql file

### ISSUE THREAD

**Issue by cvster** [cweijan/vscode-mysql#3]
Great addin! and I hope to have the following function.

assuming a sql file like this:
```sql
select * from a;
select * from b;
abc
```

when the mouse cursor is in the second line, press 'ctrl + enter' will execute 'select * from b'.

Thank you very much!

**Comment by cvster** [comment]
besides, could the query result page's backgroup color be dark?

**Comment by cweijan** [comment]
You can select the code to be executed with the mouse, then run query

**Comment by cweijan** [comment]
New version 1.6.35 has bean supports running SQL with semicolon split.
Dark mode will adapt later.
