### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kmescharikov** [cweijan/vscode-mysql#302]
- OS INFO :
macOS arm64 version 11.6
When I try to execute any findOne on local mongoldb, query will stuck.

**Comment by cweijan** [comment]
How do you execute?

**Comment by kmescharikov** [comment]
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/78717318/133710948-a0f25c03-46c0-4848-8297-a279d7d75c45.png">


> How do you execute?

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/78717318/133710961-10591b90-cf81-41fa-99b2-94bd4cd0bc6e.png">

**Comment by cweijan** [comment]
Fix at version 4.1.6.

**Comment by kmescharikov** [comment]
Thank you!
