### ISSUE TITLE
[BUG] Incorrect query results for duplicate column names

### ISSUE THREAD

**Issue by maslade** [cweijan/vscode-mysql#304]
- OS INFO : maxOC Big Sur 11.4 (20F71)
- database-client v4.1.5

Consider this example query:

    SELECT f.id, s.f_id, t.id
    FROM first f
      INNER JOIN second s ON f.id = s.f_id
      INNER JOIN third t ON t.s_id = s.id

Note that `f.id` and `t.id` refer to different columns that share the same name. If I run this query from a MySQL shell, it works as expected. My first column is called "id" and reflects the data in table `first`. My third column is called "id" and reflects the data in table `third`.

When I run that using this extension, the results panel shows incorrect information for column `f.id`, which it fills with data from the `t.id` column. That is -- for each row of results, `f.id` and `t.id` show the same value despite having different values.

**Comment by cweijan** [comment]
This extension develop by JavaScript, and the JavaScript not allow data has same property.

**Comment by maslade** [comment]
That seems like an implementation detail. Can't the underlying data structure use different objects for different tables? Or automatically generate unique keys when it encounters duplicates? If it truly can't be solved within the extension, then I'd recommend some helpful warning or messaging to let people know their query had duplicate columns and so they're seeing a broken view.

I don't think this issue should be closed as this extension is essentially a database client that is displaying incorrect information for valid queries.

**Comment by cweijan** [comment]
The only solution is to automatically generate aliases when there are duplicate columns, but it is not good to query columns with the same name without using aliases, so I do not plan to implement this feature.

**Comment by maslade** [comment]
It's not good practice, but it's a valid query. I accept your decision to only support a subset of queries, in that case surely the extension can produce an error for queries that it doesn't support. An error message would be a better user experience than showing correct columns with incorrect data.

If nothing else you can leave this open for someone to submit a PR against in the future.
