### ISSUE TITLE
Is it possible to store config.json file in custom location?

### ISSUE THREAD

**Issue by juliuzfan** [cweijan/vscode-mysql#305]
Hello Chen,

Yesterday I've installed your extension. Nice work!

I wonder if there's a way to store the config file in a custom path.

I would try to put that file(s) in my encrypted volume partition (along with other secured credentials in my dev environment), because I saw the database connection passwords are stored in plain text.

Also, it would help maybe syncing the settings.

Thank you very much!

**Comment by cweijan** [comment]
The configuration does not actually exist in config.json, it will only be generated when you click the settings button, so it does not make sense to modify the configuration file path.

**Comment by cweijan** [comment]
The configuration actually exists in ExtensionContext.globalState, and other extensions cannot be read. You can delete config.json at any time.

**Comment by juliuzfan** [comment]
Yeah makes sense, that config.json file path is temp.

Thats nice, so my main concern was that passwords are stored in disk as plain text.

Thank you Chen!
