### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KaminskiDaniell** [cweijan/vscode-mysql#306]
- OS INFO :
Win10 Education 21H1
VSC: 1.60.1
Database-client: 4.1.0
MySQL

Cannot set charset to utf8 (default is latin2)
![image](https://user-images.githubusercontent.com/27357868/133479243-fdc6e75b-165e-427f-8b65-b7004b4a17aa.png)
![image](https://user-images.githubusercontent.com/27357868/133479362-1e2098c4-5dbf-4a2d-8025-42f273b0aab2.png)
![image](https://user-images.githubusercontent.com/27357868/133480578-29a8dd28-8a05-4bc3-9ca6-0789e4d2fe4f.png)
![image](https://user-images.githubusercontent.com/27357868/133480719-76494370-3215-48ba-bfcc-3364c444b193.png)

**Comment by cweijan** [comment]
This extension does not provide the ui to modify the charset, you need to modify it manually.

**Comment by KaminskiDaniell** [comment]
![image](https://user-images.githubusercontent.com/27357868/133627423-3f5d6a04-b156-473e-b885-2540d7be76dc.png)
But charset in config is set to utf8

**Comment by KaminskiDaniell** [comment]
Second question. Can I choose config.json path? I want to have this in my workspace in .vscode folder.

Thanks for help :D

**Comment by cweijan** [comment]
Encoding is ftp connection setting, not mysql, if you want change mysql charset, can reference this [page](https://stackoverflow.com/questions/5906585/how-to-change-the-character-set-and-collation-throughout-a-database)

**Comment by cweijan** [comment]
The configuration does not actually exist in config.json, it will only be generated when you click the settings button, so it does not make sense to modify the configuration file path.

**Comment by KaminskiDaniell** [comment]
![image](https://user-images.githubusercontent.com/27357868/133657058-77c05bbb-5e76-4b08-8058-7719f86e0f2c.png)
MySQL DB which I created has utf8 collation. After change from your link the problem still exist, so I think that problem is not with my database.

About second question I have project, which is hosted on GitHub and I am working on few platforms. So configuration file for your plugin in .vscode path would help me with taking information about connection with DB without manual rewriting host, login, password, database etc.

Thanks for fast answers :)

**Comment by cweijan** [comment]
1. Because many people upload configuration files to git, I don't put the configuration files in .vscode, which is very insecure
2. I repeat, the character set is only related to your own database configuration, you should find the answer from Google.
