### ISSUE TITLE
MySQL - Facility to store procedures and Functions with Comments

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#307]
- OS Info: Windows 10

Dear Sir,

I am using this extension for MYSQL DB Management.  Most of the scripts are implemented by way of Functions and Procedures.  The issue is that while updating functions and procedures the comments are stripped off.

Can you please provide an option to update functions and procedures retaining the comments

Thank you for making my life simple with this beautiful extension

**Comment by cweijan** [comment]
This is indeed a problem, but it cannot be achieved in a short time.

**Comment by franklinkf** [comment]
Thank you for your response.  Request you to please include the same in your future roadmap
