### ISSUE TITLE
Elasticsearch self-signed certification error

### ISSUE THREAD

**Issue by ttbadr** [cweijan/vscode-mysql#308]
It would be better to add an option like ignore SSL error when creating an ES connection to support self-signed certification

**Comment by cweijan** [comment]
Ignore at version 4.1.6.

**Comment by ttbadr** [comment]
After upgrade to 4.1.6, I get this error:
![image](https://user-images.githubusercontent.com/3127447/133912814-09924fa3-2659-49d9-b7e9-2544770d7bd7.png)

**Comment by ttbadr** [comment]
@cweijan can you check this issue?

**Comment by cweijan** [comment]
I am busy now and will be resolved in the future.

**Comment by cweijan** [comment]
Fix at version 4.1.7.

**Comment by ttbadr** [comment]
> Fix at version 4.1.7.

works fine now
