### ISSUE TITLE
[BUG] SQLite not working when interacting with the table

### ISSUE THREAD

**Issue by GoBoopADog** [cweijan/vscode-mysql#309]
When trying to save a change I made in a table, I always get one of two issues:
- The change goes through, but any other change I make reverts the most recent change I've done
- I get an error (Image below) when trying to save _any_ change
![image](https://user-images.githubusercontent.com/25517283/133944467-69eab99f-949c-4b34-941a-26cf3fb000c7.png)

I noticed that this issue seemed to be fixed in a previous version, but I checked my version and it doesn't seem to have been fixed #266

Version:
![image](https://user-images.githubusercontent.com/25517283/133944539-b414b708-eac0-4bea-a28f-ff909dbe50d3.png)

I've only tried this with SQLite so far, but that seems to be the only db that causes issues

**Comment by cweijan** [comment]
This is because your column name is called index, and the program has not processed it .

**Comment by GoBoopADog** [comment]
Is there anything I can do to fix it? I'm just a little confused as I was trying to edit the id column and am not sure how index plays into all of this.

**Comment by cweijan** [comment]
Fix at version 4.1.7.
