### ISSUE TITLE
[FEATURE] Run query using command + enter

### ISSUE THREAD

**Issue by alberto-bottarini** [cweijan/vscode-mysql#313]
It will be useful if query will be performed when user click command + enter in query textarea

**Comment by cweijan** [comment]
Already have this function, try to upgrade the extension version .

**Comment by alberto-bottarini** [comment]
How can i upgrade? I did not found anything

**Comment by ctmay4** [comment]
I just installed and was looking for the same thing.  Control+Enter doesn't work.

**Comment by cweijan** [comment]
Which extension are you using, I am sure that the latest version can work normally, maybe you have installed other extensions that I released.

**Comment by cweijan** [comment]
Try using [mysql](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2) and uninstall other.

**Comment by alberto-bottarini** [comment]
I confirm it works
