### ISSUE TITLE
Support `cmd + v` to paste the table name to filter the table list on the sidebar

### ISSUE THREAD

**Issue by Mr--WhaT** [cweijan/vscode-mysql#315]
Currently you can filter the table list by typing the table name. 
But If the table name is very long, it will be cumbersome to type it to hit your desired table. 
So I suggest to support `pasting` the table name to filter the list.
If pasting is not applicable, adding a `search box` on the top of the sidebar is also a great help.

**Comment by cweijan** [comment]
I had this idea for a long time, but unfortunately vscode cannot provide this feature .

**Comment by Mr--WhaT** [comment]
What about adding a search box on the top of the sidebar ?

**Comment by cweijan** [comment]
VSCode does not support adding input boxes to sidebars.
