### ISSUE TITLE
Add support for Ed25519 SSH keys

### ISSUE THREAD

**Issue by shaneparsons** [cweijan/vscode-mysql#316]
Upon trying to add a connection with a SSH tunnel / private key I get the following error:
```
2021-09-28 13:59:11 Ssh tunel occur error : Error: Cannot parse privateKey: Unsupported key format
```
The key I'm using is `id_ed25519` which implements the newer / recommended Ed25519 standard.

Please add support for these keys.

**Comment by cweijan** [comment]
Duplicate #264, Unfortunately, there is no effective way to support it.

**Comment by shaneparsons** [comment]
Ah, sorry about that.
