### ISSUE TITLE
Feature Request: Add default value field in row edit in table builder.

### ISSUE THREAD

**Issue by luckcolors** [cweijan/vscode-mysql#317]
- OS Info: VScode on Windows x64.

Hello.
Thanks for your extension, i've been using it more laterly and it's being helpfull. 😄 

It seems that currently you can't change the default value from a table from the table design page.
Unless i'm looking in the wrong place.
This is definetely has a low prority since i can make an alter table statement, but i wanted to report it so that i could ask you whether you think it would be a good addition.

Screenshot:
![immagine](https://user-images.githubusercontent.com/3228598/135372281-115cdd47-5d71-4d1f-bf0b-41ecf833c549.png)

**Comment by cweijan** [comment]
Support MySQL change default value on version 4.1.8.
