### ISSUE TITLE
[BUG] Support for citext columns in Postgres

### ISSUE THREAD

**Issue by jonatino** [cweijan/vscode-mysql#318]
Can we get support for citext columns in Postgres databases? When u try and edit a citext column on the table ui, it does not wrap your input with quotes and causes a malformed query.

Query after attempting to change column value to "testing sql ext":
```
2021-10-04 19:58:18 Execute sql fail : UPDATE "characters" SET "name"=testing sql ext WHERE id=1;
2021-10-04 19:58:18 error: syntax error at or near "sql"
```

**Comment by cweijan** [comment]
What is the full name of the type of citext? If the type contains text, it will be quoted.

**Comment by jonatino** [comment]
@cweijan https://www.postgresql.org/docs/9.1/citext.html

**Comment by cweijan** [comment]
I think you are using [postgresql-extension](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-postgresql-client2), it's a deprecate extension , you need uninstall it and install [Database Client](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2).

**Comment by jonatino** [comment]
This is broken with database client too.

![image](https://user-images.githubusercontent.com/1808569/144004643-d9a61795-aa31-46fb-ae51-c71593216836.png)

citext is built into postgres so it should be treated as a text column.

**Comment by cweijan** [comment]
@Jonatino Have you upgraded database-client to the latest version?

**Comment by cweijan** [comment]
The newest version is 4.3.0.
