### ISSUE TITLE
FTP conection not show hidden files (like .env) on tree view

### ISSUE THREAD

**Issue by washopilot** [cweijan/vscode-mysql#321]
FTP conection not show hidden files (like .env) on tree view

![image](https://user-images.githubusercontent.com/69498743/136707019-cc4b46f5-689a-47e3-a2c1-08272827dcde.png)

**Comment by cweijan** [comment]
I can display hidden files normally, this may be caused by your ftp server .

**Comment by washopilot** [comment]
> I can display hidden files normally, this may be caused by your ftp server .

Thats weird, same sever using FileZilla, show hidden files. Why???

![image](https://user-images.githubusercontent.com/69498743/137661172-ff618fd0-9957-43f8-941e-117b513b3378.png)
