### ISSUE TITLE
创建redis连接时，每次只能连接一个库

### ISSUE THREAD

**Issue by wen-gg** [cweijan/vscode-mysql#322]
![image](https://user-images.githubusercontent.com/17865026/136885752-bcf54788-5bd6-4e34-8d3d-2d68146122d2.png)
如图，当我不输入 Databases 时默认的是0，否则一个连接只能输入一个库

建议：能否可以一个连接一次查询出redis的所有库0-15,再在侧边栏选择相应的库做操作，而不是一个连接只能一个库

**Comment by cweijan** [comment]
等下次更新我把所有的数据库列出来

**Comment by wen-gg** [comment]
感谢！！

**Comment by kaiweixuxu** [comment]
非常期待这个功能~

**Comment by cweijan** [comment]
@fastfastgogo redis什么情况会用到多数据库呢, 不是一般都只用一个吗

**Comment by kaiweixuxu** [comment]
一般一个系统都是只用一个库，但是当有多个系统时或者运维redis服务器的时候，需要看到所有仓库的数据情况。

**Comment by kaiweixuxu** [comment]
> 还有，有时候会按不同的业务数据，分别存放在不同的数据库中。比如缓存数据存放一个库，用户数据存放一个库，订单数据存放一个库 这样的情况。

**Comment by cweijan** [comment]
新版本4.3.0会将所有有数据的数据库列出来, 如果所有的数据库都没数据, 则只显示数据库0.
