### ISSUE TITLE
[BUG] 关于数据表字段类型的错误显示

### ISSUE THREAD

**Issue by luxuncang** [cweijan/vscode-mysql#323]
- OS INFO : Win10 Pro 21H1
- VSC:  1.61.0 (user setup)
- Database-client: v4.1.6
- Mysql 8.0.21

**案例表**

```sql
CREATE TABLE `user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `email` varchar(64) NOT NULL,
  `password` varchar(64) NOT NULL,
  `settime` datetime DEFAULT NULL,
  `lasttime` datetime DEFAULT NULL,
  `face` varchar(256) DEFAULT NULL,
  `state` tinyint(1) DEFAULT NULL,
  `color` enum('ThemeIndigo','ThemeCyan','ThemeGreen','ThemeBlush','ThemeDark') DEFAULT NULL,
  `background` tinyint(1) DEFAULT NULL,
  `desktop` tinyint(1) DEFAULT NULL,
  `sound` tinyint(1) DEFAULT NULL,
  `type` enum('member','admin','adminpro') DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8
```

* 字段为枚举类型时的错误显示 **color** 字段类型显示为 **type** 字段类型 （enum类型）
![image](https://user-images.githubusercontent.com/70730964/137016906-ba7f1441-fddd-4712-84fb-768655b8d86a.png)
* 当查询个别字段时，字段类型没有发生变化，依旧按照完整字段的字段类型依次显示
![image](https://user-images.githubusercontent.com/70730964/137017052-0ba0c74b-2344-48b5-913e-7cd115c1fad2.png)
![image](https://user-images.githubusercontent.com/70730964/137017270-d1e21f1b-2195-4735-8d6f-0e6f4ff593f5.png)

ps：最后感谢**cweijan**的**vscode-database-client**，很方便的让我在vscode上进行开发

**Comment by cweijan** [comment]
我看不懂你这个问题, 你的类型不就是枚举吗, 哪里错了.

**Comment by luxuncang** [comment]
> 我看不懂你这个问题, 你的类型不就是枚举吗, 哪里错了.

**感谢回复**

- 问题一: `color`字段枚举类型应该是`'ThemeCyan','ThemeGreen','ThemeBlush','ThemeDark'`,但是显示的却是`type`字段的枚举类型`'member','admin','adminpro'`

- 问题二(当使用UI选择字段时):例如查询表最后三个字段时，字段类型显示的却是表的前三个字段的类型
  `desktop` tinyint(1) DEFAULT NULL,
  `sound` tinyint(1) DEFAULT NULL,
  `type` enum('member','admin','adminpro') DEFAULT NULL,
![image](https://user-images.githubusercontent.com/70730964/137659729-f4b071b3-1353-4477-bdd8-8b55fec12c75.png)

**Comment by luxuncang** [comment]
问题一：发生在**增加表字段时**，重新生成新表则不会出现该问题，但依旧会出现**问题二** （可能是缓存滞留的问题）

**Comment by cweijan** [comment]
在4.1.7版本修复了.
