### ISSUE TITLE
Make the table column title more visible by changing background color or text and dim the color of the word Filter.

### ISSUE THREAD

**Issue by shohagkhan** [cweijan/vscode-mysql#325]
Table column title is very important for every developer. We use PhpMyAdmin to understand the table structure. Please make a theme like PhpMyAdmin  so that we can understand the table structure and it's data very efficiently like PhpMyAdmin. Also, please make the font size of the word Filter smaller and change the color like a placeholder. It draws undue attention. 
Also, it will be helpful if there is an option to close / remove single database connection.

![image](https://user-images.githubusercontent.com/16593128/137120407-d8ee2712-0204-4165-9f07-a1a54899b87e.png)

At last, many many thanks for this nice extension. Now we can do all the things inside vscode.

**Comment by cweijan** [comment]
The filter color is indeed a good suggestion, I will improve it in the next version, I have never used PhpMyAdmin, so I don’t know what the table structure you are talking about

**Comment by shohagkhan** [comment]
@cweijan Thanks for your awesome extension. It's life saver. Now I can do everything inside my vscode. You don't need to make it like PhpMyAdmin. You already did a great job and it's much more nicer than anything. But please add an option to close / remove single database connection, so that I can work with only my desired databases.

**Comment by cweijan** [comment]
Right click can do it.
![image](https://user-images.githubusercontent.com/27798227/137659109-ba2c980b-c828-4d44-a41f-725c30d48562.png)

**Comment by cweijan** [comment]
Filter color has changed on version 4.1.7.
