### ISSUE TITLE
if possible add option to hide "▶ Run SQL" option in *.sql files

### ISSUE THREAD

**Issue by RaitKivinurm** [cweijan/vscode-mysql#327]
"▶ Run SQL" option i getting in the way to see bigger picture in *.sql files if writing longer procedure

**Comment by cweijan** [comment]
You can disable it on setting.
![image](https://user-images.githubusercontent.com/27798227/137491565-ab0aa8f9-9371-434d-b3fb-76d7b84f9527.png)
