### ISSUE TITLE
> I can display hidden files normally, this may be caused by your ftp server .

### ISSUE THREAD

**Issue by washopilot** [cweijan/vscode-mysql#328]
> I can display hidden files normally, this may be caused by your ftp server .

Thats weird, same sever using FileZilla, show hidden files.

![image](https://user-images.githubusercontent.com/69498743/137661172-ff618fd0-9957-43f8-941e-117b513b3378.png)

_Originally posted by @washopilot in https://github.com/cweijan/vscode-database-client/issues/321#issuecomment-945315210_

**Comment by cweijan** [comment]
You can try another hidden file, maybe because the ftp library used by the plugin is not compatible with your server, I can’t support it.
![image](https://user-images.githubusercontent.com/27798227/137665783-35721dcd-61c5-40d5-b0ec-5a2bff570519.png)

**Comment by washopilot** [comment]
> You can try another hidden file, maybe because the ftp library used by the plugin is not compatible with your server, I can’t support it. ![image](https://user-images.githubusercontent.com/27798227/137665783-35721dcd-61c5-40d5-b0ec-5a2bff570519.png)

The issue extends to folders too... But I tried with another ftp server, the folders shows!!! That is so anoying. I like the app so much....

![image](https://user-images.githubusercontent.com/69498743/137672391-2d2a2d8e-7944-4ad4-87d6-ee093e52719d.png)
(No hidden folders)

![image](https://user-images.githubusercontent.com/69498743/137672689-76130141-9ba4-4cfa-a4ab-499306283914.png)
(But.... another server, the folders and hidden files shows)

It is a real shame! 😥. Both serves in FileZilla show good. Back to FileZilla I guess

**Comment by cweijan** [comment]
It seems that the FTP library is incompatible with your server, I can't support it, so I need to close this issue.
