### ISSUE TITLE
redis stream打开空白

### ISSUE THREAD

**Issue by Albert556** [cweijan/vscode-mysql#329]
- OS INFO :
mac redis的stream键打开是空白的

**Comment by cweijan** [comment]
目前没有实现对stream的支持.

**Comment by li1234yun** [comment]
> 目前没有实现对stream的支持.

stream类型挺有用的，不知道作者是否打算实现呢 :-)

**Comment by cweijan** [comment]
在最新的5.0版本中支持了对stream类型的预览.

**Comment by Albert556** [comment]
使用了，感谢
* bug

相同前缀的key折叠后，右键重复显示delete
![image](https://user-images.githubusercontent.com/38153509/162126783-537b641a-278a-4131-af4c-ffa3d0001542.png)

**Comment by cweijan** [comment]
删除文件夹就是批量删除
