### ISSUE TITLE
[BUG]MySQL8  修改JSON类型字段值格式不正确

### ISSUE THREAD

**Issue by geekgao** [cweijan/vscode-mysql#331]
MySQL8  修改JSON类型字段值格式不正确。修改时得到错误：
```
EXECUTE FAIL:

UPDATE policy_rule SET condition='{"zone": {"excludeZoneId": ["string"], "specificZoneId": ["*"]}, "client": {"clientType": ["mac"]}, "member": {"groupId": ["string"], "memberId": ["string"], "allMember": true, "shouldMatch": {"value": "string", "operator": "string", "property": "string"}, "departmentId": ["string"], "excludeMemberId": ["1"]}}' WHERE id=21;

Message :

  You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'condition='{"zone": {"excludeZoneId": ["string"], "specificZoneId": ["*"]}, "cli' at line 1 
```

换用其他工具。找到原因，需要转义为：
UPDATE \`policy_rule\` SET \`condition\` = '{\\"zone\\": {\\"excludeZoneId\\": [\\"string\\"], \\"specificZoneId\\": [\\"*\\"]}, \\"client\\": {\\"clientType\\": [\\"mac\\"]}, \\"member\\": {\\"groupId\\": [\\"string\\"], \\"memberId\\": [\\"string\\"], \\"allMember\\": true, \\"shouldMatch\\": {\\"value\\": \\"string\\", \\"operator\\": \\"string\\", \\"property\\": \\"string\\"}, \\"departmentId\\": [\\"string\\"], \\"excludeMemberId\\": [\\"string\\"]}}' WHERE \`id\` = 21

**Comment by cweijan** [comment]
我用MySQL5.7是正常的, 又装了个MySQL8试了下JSON, 也是正常的.

**Comment by cweijan** [comment]
感觉JSON类型不太可能要求双引号需要转义, 转义双引号在PostgreSQL中属于非法字符.

**Comment by geekgao** [comment]
那就怪了，那我再看看吧。
btw 作者你的捐赠通道有问题，pp没法支付。之前支付失败了。

**Comment by geekgao** [comment]
> 感觉JSON类型不太可能要求双引号需要转义, 转义双引号在PostgreSQL中属于非法字符.

我利用 Navicat 修改观察输出的

**Comment by cweijan** [comment]
你的操作系统和MySQL版本号是多少, MySQL用转义双引号不会报错, 只是我认为理论上不转义应该不会有问题.

**Comment by geekgao** [comment]
> 你的操作系统和MySQL版本号是多少, MySQL用转义双引号不会报错, 只是我认为理论上不转义应该不会有问题.

mysql  Ver 8.0.27 for Linux on x86_64 (MySQL Community Server - GPL)
ubuntu

**Comment by cweijan** [comment]
是因为condition在MySQL中是关键字, 和转义字符没关系, 下版本调整.

**Comment by cweijan** [comment]
版本4.1.9已将condition设置为关键字, 可以正常编辑了.
