### ISSUE TITLE
希望优化连接 redis 时的策略

### ISSUE THREAD

**Issue by ritajie** [cweijan/vscode-mysql#340]
公司对 redis 做了些改造，不支持 `info` 命令，导致本插件连接失败：

![image](https://user-images.githubusercontent.com/26023242/139834780-28dbb0bc-adf6-4428-94c3-bbdd6981f751.png)

也许可以使用 `get` `set` 这些更通用的命令来验证连接状态。

**Comment by cweijan** [comment]
扩展的连接命令是由底层的ioredis发送的, 它发送的应该是ping命令, 没法改的.
