### ISSUE TITLE
Drop Procedure (remove/hide)

### ISSUE THREAD

**Issue by rchavezj** [cweijan/vscode-mysql#342]
I know I didn't write  'DROP PROCEDURE IF EXIST' in microsoft sql server management studio and now I see it in the first line of each store proc for this extension. I get scarred seeing this in all of my store procs and wish to hide it. Does this feature exist?

**Comment by cweijan** [comment]
Yes, the drop statement is generated by the extension to modify the stored procedure.

**Comment by rchavezj** [comment]
Is there a way to remove the generated drop statement code?

**Comment by cweijan** [comment]
Why remove? This extension never said that it behaves like other management tools.

**Comment by rchavezj** [comment]
I’m only interested in seeing the code I’ve written in the store proc. Both my code and drop procedure statement have “Run query” executable on top and I don’t want to accidentally click on the wrong button. You have done an incredible job with the UI but this is a feature in the future I hope gets added. On sql server, I can just right click on the store-proc/table on the side bar to remove it with a “double dare” warning if I’m sure.

**Comment by rchavezj** [comment]
Or is there a way to modify the template?

**Comment by cweijan** [comment]
You can disable codelen. the purpose of this function is to modify the stored procedure, not just to view the code.
![image](https://user-images.githubusercontent.com/27798227/140264715-5f9f4d96-8b9e-4d37-830d-29527d2adc73.png)

**Comment by rchavezj** [comment]
^ Didn't work for me
