### ISSUE TITLE
[BUG]strange font style

### ISSUE THREAD

**Issue by ijry** [cweijan/vscode-mysql#344]
- OS INFO : macOs 12 MBP2017
- how to fix font like this?
<img width="879" alt="iShot2021-11-04 14 52 39" src="https://user-images.githubusercontent.com/3102798/140270236-e2bbaf2d-9f77-4ba4-801c-b6c35d60f4e8.png">

**Comment by cweijan** [comment]
I will try to solve this problem in the next version.

**Comment by cweijan** [comment]
Fix at version 4.1.9.

**Comment by ijry** [comment]
it works,thanks. by the way,is there any plan provide sync of &nbsp;srv&amp;db config on different machines?



发自我的iPhone


------------------ Original ------------------
From: Chen WeiJian ***@***.***&gt;
Date: Thu,Nov 11,2021 10:07 PM
To: cweijan/vscode-database-client ***@***.***&gt;
Cc: jry ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [cweijan/vscode-database-client] [BUG]strange font style (Issue #344)






Fix at version 4.1.9.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cweijan** [comment]
You can click this button to generate a configuration file and paste it to other machines to save.
![image](https://user-images.githubusercontent.com/27798227/141317239-2b554f8b-2d64-4707-9035-c5cfe01a5694.png)
f
