### ISSUE TITLE
[BUG] Unreadable Font Style in Query Window

### ISSUE THREAD

**Issue by pmcl77** [cweijan/vscode-mysql#347]
- OS INFO : Mac OS Big Sur

The font in the query windows above the query results is a small serif font, which is very hard to read, see screenshot. It looks different from the screenshots in the readme, so I guess this is a bug. 

<img width="435" alt="Screenshot 2021-11-08 at 21 27 53" src="https://user-images.githubusercontent.com/57845954/140813999-e551efc5-f4ef-4918-bec9-f0d68c79aa2b.png">

**Comment by cweijan** [comment]
I don’t have a mac computer and I can’t adapt the best fonts. You can recommend suitable fonts to me.

**Comment by pmcl77** [comment]
I would suggest using the default VScode font families on Mac: Menlo, Monaco, monospace

Maybe it would be possible to link to the VSCode font setting? Or even have a separate font setting for the extension?

**Comment by cweijan** [comment]
Try version 4.1.9.

**Comment by pmcl77** [comment]
Perfect, looks much better. Thanks for the quick change!

<img width="445" alt="Screenshot 2021-11-11 at 15 13 45" src="https://user-images.githubusercontent.com/57845954/141312850-654d15d5-849e-4b01-86dd-c5b0167d642f.png">
