### ISSUE TITLE
redis command result does not auto scroll down

### ISSUE THREAD

**Issue by AmazingYuan** [cweijan/vscode-mysql#348]
- Client OS Info:
windows 10 10.0.18363
- Vscode: 
code-server v3.10.2 running on Centos 7.4

Thanks for the extension. I got a problem with redis command UI, the result panel does not auto scroll down when  a command is excuted.

**Comment by cweijan** [comment]
Redis terminal has stopped maintenance, when you install redis-cli, a vscode terminal will be created.
![image](https://user-images.githubusercontent.com/27798227/142972912-a5910295-34fd-40b3-90fe-25e64e4c8a0c.png)
