### ISSUE TITLE
Support for MongoDB SRV and Connection via String

### ISSUE THREAD

**Issue by ashutoshpw** [cweijan/vscode-mysql#351]
Generally we do have a simple connection string starting with MongoDB:// OR MongoDB+srv://
It would be great if there is an option to simply enter those details to create a MongoDB Connection.

**Comment by cweijan** [comment]
Try below.
![image](https://user-images.githubusercontent.com/27798227/141305867-dffcdf9e-2498-4047-9fad-aa0ad05e2a19.png)
