### ISSUE TITLE
[BUG] Can't update (fill) column with type enum manualy 

### ISSUE THREAD

**Issue by stoneC0der** [cweijan/vscode-mysql#352]
- OS INFO : Xubuntu 20.04
- vscode: v1.61.2
- Extension: v4.1.9

I unable to update a column with type enum

I have tried using the dropdown, double click on the column field no success

Step to reproduce:
- Open a database table with a column with type enum
- double click or use dropdown edit to fill or change the value to a valid enum of the column
- save

Expected result: column value updated
Current result: 

Execute sql fail : UPDATE transactions SET method=card WHERE id=1;
Error: Unknown column 'card' in 'field list'

**Comment by cweijan** [comment]
Fix at version 4.2.1.
