### ISSUE TITLE
Time formatting

### ISSUE THREAD

**Issue by codewithkyle** [cweijan/vscode-mysql#353]
When running queries on tables with hundreds of millions of records the time (cost) can become useless without googling the conversion. For example `67101ms` means less to me than `00:01:11`. It would be helpful if any cost value over 1000ms was displayed in a `HH:MM:SS` format.

**Comment by cweijan** [comment]
Time-consuming should not be displayed in the format of time, almost all database management tools are displayed as xx ms.
