### ISSUE TITLE
[BUG] PostgreSQL request not well formatted

### ISSUE THREAD

**Issue by NansD** [cweijan/vscode-mysql#356]
## Steps to reproduce
When going to my schema "public" and clicking one of the tables (e.g: Scenario), I get this error :

```
EXECUTE FAIL:

  SELECT * FROM Scenario LIMIT 100

Message :

  relation "scenario" does not exist
```
 
The code that was generated by the extension is this one :

```SQL
SELECT * FROM Scenario LIMIT 100
```

## Expected result
I believe the extension should have generated this query :

```SQL
SELECT * FROM pubic."Scenario" LIMIT 100
```

**Comment by cweijan** [comment]
I think you are using [postgresql-extension](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-postgresql-client2), it's a deprecate extension , you need uninstall it and install [Database Client](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2).

**Comment by NansD** [comment]
It works great, sorry for this wrong issue, and congratulations for this great extension!
