### ISSUE TITLE
Offline usage support

### ISSUE THREAD

**Issue by alexanderzjs** [cweijan/vscode-mysql#357]
Need to use it in an offline environment, but unfortunately, list table content functionality shows just empty.

Hope this critical functionality could be supported. I really like this extension and don't want to go to heavy client such as DataGrip and so on.

Thanks

**Comment by cweijan** [comment]
Change to internalServer or file.
![image](https://user-images.githubusercontent.com/27798227/142018539-3882089b-e978-44c9-86df-9c6f7f547070.png)

**Comment by yimiaoxiehou** [comment]
is this setting remove ？cannot find it on 7.2.7  @ext:cweijan.vscode-database-client2

**Comment by cweijan** [comment]
@yimiaoxiehou Yes, because it is no longer needed. If you encounter any problems, please open a new issue description.
