### ISSUE TITLE
redis explorer 不能完全显示所有的key[BUG]

### ISSUE THREAD

**Issue by 256kb** [cweijan/vscode-mysql#360]
- OS INFO :
当有非常多的Key，redis explorer 不能完全显示所有的key

**Comment by cweijan** [comment]
一次显示2000条, 你每点一次多增加2000

**Comment by 256kb** [comment]
对比两边的数据您就知道我描述的问题了，两边的key不一样




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cweijan/vscode-database-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月18日(星期四) 中午11:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cweijan/vscode-database-client] redis explorer 不能完全显示所有的key[BUG] (Issue #360)





 
一次显示2000条, 你每点一次多增加2000
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 256kb** [comment]
明白了，非常感谢回复。插件很牛逼，很好用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cweijan/vscode-database-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月18日(星期四) 中午11:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cweijan/vscode-database-client] redis explorer 不能完全显示所有的key[BUG] (Issue #360)





 
一次显示2000条, 你每点一次多增加2000
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by cweijan** [comment]
后续版本我会调整每次加载的数量.
