### ISSUE TITLE
[BUG] Filter doesn't escape more than 1 single quote

### ISSUE THREAD

**Issue by alexandernst** [cweijan/vscode-mysql#362]
If I try to use the "filter" feature in any column and I type more than 1 single quote, only the first single quote gets escaped (which leads to an error).
![sdfgsdfg](https://user-images.githubusercontent.com/89727/142760661-0d9baadf-2085-400c-bcab-cd9051ad3d8e.png)

**Comment by cweijan** [comment]
Fix at version 4.2.1.
