### ISSUE TITLE
[BUG] Filter doesn't work correctly on integer fields

### ISSUE THREAD

**Issue by alexandernst** [cweijan/vscode-mysql#363]
The "filter" feature is trying to filter integer fields using the `%%` operator, which leads to a wrong query.
![kjjhgkjhg](https://user-images.githubusercontent.com/89727/142760960-3ca6ed84-dffe-40a4-b480-6af8bc343683.png)

**Comment by cweijan** [comment]
Fix at version 4.2.1.
