### ISSUE TITLE
[BUG] - After initial DB connection the connection fails later.

### ISSUE THREAD

**Issue by jasonpberry** [cweijan/vscode-mysql#364]
- OS INFO :

Server: Localhost via UNIX socket
Server type: MySQL
Server connection: SSL is not being used Documentation
Server version: 5.7.34 - MySQL Community Server (GPL)
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

**Web server**
Apache/2.4.48 (Unix) mod_fastcgi/mod_fastcgi-SNAP-0910052141 OpenSSL/1.0.2u mod_wsgi/3.5 Python/2.7.13
Database client version: libmysql - mysqlnd 8.0.8
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 8.0.8

**Initial Connection:**
![image](https://user-images.githubusercontent.com/4844006/142797276-93cc874d-3bd2-4a6b-934e-4e2588f53234.png)

**After a bit of time (hours)**
![image](https://user-images.githubusercontent.com/4844006/142797195-76c41d0e-c2ec-4d0d-9aa6-b0df3e46f40e.png)

Feels like the Unix Socket Path gets wiped out.   The value on EDIT definitely is gone on connection [EDIT] screen.  Possibly by design. Not sure. 

Let me know if you need more info.  Thanks for the awesome solution!

Jason

**Comment by cweijan** [comment]
Fix at version 4.2.1.

**Comment by jasonpberry** [comment]
Impressive! Thanks @cweijan for the fix and an amazing response / new build time!
