### ISSUE TITLE
[BUG] "Not active es server found!"

### ISSUE THREAD

**Issue by rtsui-harmonicinc** [cweijan/vscode-mysql#365]
similar issue: #176 
- OS INFO :
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

![image](https://user-images.githubusercontent.com/11556527/142822066-2b56a38e-ae4b-410b-abc3-df5994c3a65b.png)
Note that on the left server 'es1' is active.

Having created an .es file for running custom queries, it'd never succeeded.

**Comment by cweijan** [comment]
Fix at version 4.2.1.
