### ISSUE TITLE
[BUG] Not able to select table. Only see the query tab and no table details. 

### ISSUE THREAD

**Issue by robertc11** [cweijan/vscode-mysql#366]
Hi, 

We are not able to select our tables starting this morning.   We are running React on CentOS 7 system.  See attached image. 

- OS INFO : CentOS 7

![Select Table Issue](https://user-images.githubusercontent.com/4958651/142900530-a672c458-4279-422a-98c6-cc79a4e40d99.PNG)

**Comment by cweijan** [comment]
Try to close the page and reopen it. The new version optimizes the cache usage, but it seems that there is a problem with the current logic.

**Comment by JaakkoRoponen** [comment]
I have the same problem. Can't figure out a solution. Even uninstalling and reinstalling the extension does not help.

**Comment by alexandernst** [comment]
I'm also experiencing this issue. This started happening after updating to 4.2.1

**Comment by JaakkoRoponen** [comment]
Yes, rolling back to 4.2.0 fixes the issue

**Comment by wangpengcheng** [comment]
Rolling back to 4.2.0 fixes this issue

**Comment by cweijan** [comment]
Have you tried to closing the result view in version 4.2.1 then reopen? the new version will be released in a few days, I think he can avoid this problem.

**Comment by JaakkoRoponen** [comment]
Yes. Also tried reinstall, but didn't help either.

**Comment by cweijan** [comment]
@JaakkoRoponen  Hi, try restart vscode, then query table and give feedback, it will be very helpful to me.

**Comment by JaakkoRoponen** [comment]
I just get an empty query tab without any content (as shown in the initial post). Nothing I do changes that (except rolling back to previous version).

**Comment by cweijan** [comment]
Do you use remote vscode? It is currently known that remote can cause this problem.

**Comment by alexandernst** [comment]
I do use remote vscode (and I'm having this issue)

**Comment by cweijan** [comment]
If it is caused by remote, it will be fixed in the next version.

**Comment by cweijan** [comment]
Try version 4.2.3.

**Comment by robertc11** [comment]
The latest version is working for me. I was using remote vs code. Thank you so much for quick response and help.
