### ISSUE TITLE
Let user choose what kind of filtering syntax is used (performance issues)

### ISSUE THREAD

**Issue by JaakkoRoponen** [cweijan/vscode-mysql#369]
Currently, when you filter, you get something like:

SELECT * FROM table WHERE column like '%1234%' LIMIT 100  ;

This is very slow when you have millions of rows (might take minutes when simple WHERE column = 1234 is almost instant). 

It would be nice to be able to choose between a few alternatives on filtering. For example, phpmyadmin has 
=, !=, <, >, <=, >=, LIKE, LIKE %..%, NOT LIKE, IN (...), NOT IN (..), BETWEEN, NOT BETWEEN, IS NULL, NOT IS NULL.

Of course you can always write this syntax by yourself, but it would be faster (and nicer) to be able to use the filter field.

**Comment by cweijan** [comment]
The purpose of filter is to search, so it is more reasonable to use like. If you want to search accurately, write SQL conditions in SqlPannel by yourself, I do not plan to modify this.
