### ISSUE TITLE
Connect postgresql via unix socket / connection string

### ISSUE THREAD

**Issue by dcarosone** [cweijan/vscode-mysql#371]
- OS Info: NixOS

My postgresql instances do not listen on TCP sockets, and only use unix sockets with integrated authentication (so mandatory username/password/database fields are also not appropriate).  There seems to be no connection option for this.  The client library supports connection strings, so that would be one way to support the more flexible / expert option.

There might be a way to do this directly in the config json, that doesn't need a lot of UI work - I'd be happy with that if it was documented somwhere? In my case, a connection string like `postgres://` is enough.

This is (approximately) the pgsql version of #267 (which I see was only a week ago, but I only started trying this extension today)

**Comment by cweijan** [comment]
Last week’s update only supports Mysql, not pg, I will try to add this option.

**Comment by cweijan** [comment]
Support at version 4.2.3.

**Comment by dcarosone** [comment]
Thankyou, it's working fine!

I had to go digging in the docs for the client library, it turns out this one has a different connect string syntax than the others I use, and it has to be `socket:/run/postgresql/`, and doesn't use the pg defaults.
