### ISSUE TITLE
[BUG] Blank query page on remote server because port 12315 is not forwarded

### ISSUE THREAD

**Issue by azuse** [cweijan/vscode-mysql#373]
I am getting a blank page when opened a query (design table works fine), and debug console shows several GET fail to 127.0.0.1:12315.
I don't remember when this started, but i think a vscode update has caused it (my code version is 1.62.3)
![图片](https://user-images.githubusercontent.com/22174280/143207234-c2fd62be-bc0b-4a63-b913-cf651f42bdc9.png)
![图片](https://user-images.githubusercontent.com/22174280/143207704-ba3ec779-df6d-4e5e-8928-af7e782ffe8d.png)

after manually forward remote port 12315, it works fine again:
![图片](https://user-images.githubusercontent.com/22174280/143208107-e3fe46f7-fdd5-4bd9-9470-dfc2e9c6a734.png)
![图片](https://user-images.githubusercontent.com/22174280/143208022-72d56380-5292-44d4-9c73-fb68039edea9.png)

- OS: Mac os 12.0.1
- Database Type: MySQL

**Comment by cweijan** [comment]
Thank you for helping me locate the problem, a new version will fix the problem soon.

**Comment by cweijan** [comment]
Fix at version 4.2.3.
