### ISSUE TITLE
Add "Database-client: Show Event" setting

### ISSUE THREAD

**Issue by TomJHGibbs** [cweijan/vscode-mysql#374]
- OS Info: Windows 10, MySQL

No setting to view database events in the database-client:
![image](https://user-images.githubusercontent.com/94061998/143282113-30e71c55-703a-44df-8786-a75a8d460459.png)

Currently unable to see events in the database-client:
![image](https://user-images.githubusercontent.com/94061998/143282029-08ed9bf3-34a6-4180-beaf-4e784130f154.png)

Compared to in HeidiSQL:
![image](https://user-images.githubusercontent.com/94061998/143281764-8ff123ac-a53d-46ae-ba8e-dc0e44e59a6f.png)

**Comment by cweijan** [comment]
I do not plan to support event.
