### ISSUE TITLE
Order of tables

### ISSUE THREAD

**Issue by paimfp** [cweijan/vscode-mysql#375]
The order of the tables is displaying tables starting with underline(_) in the end of the list, think it should be in the beginning as most sorting alphabetically ordering.

**Comment by cweijan** [comment]
The sorting rule of the database is to put the underscore at the end. You gave my extension a low score because of this. This is very disrespectful to me.

**Comment by cweijan** [comment]
Your rating makes me feel insulted.
![image](https://user-images.githubusercontent.com/27798227/143512509-442d906f-72a0-465e-a143-c4c5fcc4da88.png)

**Comment by paimfp** [comment]
I'm sorry you felt that way.
I am sure I was not disrespectful, it's just because this behavior is different from other software I'm used to. (And general ordering in my experience, even when I want to organize files to appear on top of folders I use underscore in the start).

Take this as a suggestion only, maybe a config to change that? Other than that, nice work on the extension!

Keep in piece!

**Comment by cweijan** [comment]
As long as you are harsh enough, you can find any reason to criticize any software.
I will modify the default collation in the next version.

**Comment by paimfp** [comment]
As long as you are immature enough, you can consider any comment or suggestion as a major criticism.
Appreciate it, have a nice one.

**Comment by cweijan** [comment]
I would love to receive suggestions, but you gave this software a low score because of the lack of required features. This is unfair. I think this extension is worthy of a 5-star rating.
I am a little angry because I received a low-score evaluation. This is a free and open source software. It hurts me to receive such evaluations.

**Comment by cweijan** [comment]
Your attitude is not worth me to change it, I suggest you use other better alternatives.
