### ISSUE TITLE
Is there any plan to support Apache HIVE Query like jdbc:hive2://xxxxxx in the future?

### ISSUE THREAD

**Issue by baiyyee** [cweijan/vscode-mysql#377]
This extension is great, and covered a very full db connections, for now, I need to query apache hive data as normal db, is there any plan to support HIVE Query like jdbc:hive2://xxxxxx in the future?

**Comment by cweijan** [comment]
This extension is connected to the database through the node program, not jdbc, so there is no way to support hive.

**Comment by baiyyee** [comment]
OK
