### ISSUE TITLE
What is the diff between this two extensions?  

### ISSUE THREAD

**Issue by thiagolucio** [cweijan/vscode-mysql#378]
Hi!. First, thank you for your great job!

I just have a question. What's the difference between these two extensions in the VSCode marketplace ?

https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2

I'm install both and have some strange duplicated elements. For example...double occurrence from same buttons. 
![Screenshot from 2021-11-27 09-12-28](https://user-images.githubusercontent.com/5756266/143680871-08da3ab2-2b0a-4090-96fa-b323718743f0.png)

Should be apparently are the same extension duplicated at the marketplace. I'm right?

Thanks again for this extension. It's very useful!

**Comment by cweijan** [comment]
You only need to install one. At first, only MySQL is supported, and other types of databases are supported later. In order to make it easier for vscode users to search, new extensions have been released.

**Comment by thiagolucio** [comment]
> You only need to install one. At first, only MySQL is supported, and other types of databases are supported later. In order to make it easier for vscode users to search, new extensions have been released.

Thanks for your answer and again thanks for your work!
