### ISSUE TITLE
[BUG] SqlServer can't connect because port is ignored when instance name is specified

### ISSUE THREAD

**Issue by SomeoneIsWorking** [cweijan/vscode-mysql#379]
I think because of this (If instance name is specified, the port config is ignored)
My connection doesn't work
All my connection strings have both the port number and the instance name
I don't understand why port is ignored when instance is specified

- OS: Windows 10 x64
- Database Type: MSSQL

**Comment by cweijan** [comment]
If you know your sqlserver port, you don't need to specify the instance name, because the instance name is used to communicate with SQL Server Browser Service to get the port.

**Comment by SomeoneIsWorking** [comment]
It works with only port but like I said my connection strings have both. Which made me to realize my connection strings are all wrong but have worked so far anyway. I've been using it wrong for many years.

So not a bug but can I ask, could this be changes so if you input both then the instance name should be ignored instead because that's how Microsoft handles it apparently?

**Comment by cweijan** [comment]
I am not familiar with sql server manager, but tedious, the sql server client used by this extension, requires this.
