### ISSUE TITLE
redis explorer 详情里，设置的分页数量不起作用[BUG]

### ISSUE THREAD

**Issue by 256kb** [cweijan/vscode-mysql#380]
- OS:linux
- Database Type: redis
redis explorer 详情里，设置的分页数量不起作用。
默认显示是100条每页，当我设置200条每页或300条每页，不起作用。点击了上面的刷新，一样不起作用。这个问题我很早之前就已经发现了。不知道是不是我操作的问题。

很感谢作者提供了个很牛逼的插件。感谢作者的付出！

**Comment by cweijan** [comment]
感谢支持, 分页确实有问题, 下版本修复.

**Comment by cweijan** [comment]
版本4.3.1修复了.
