### ISSUE TITLE
[BUG] json arrays broken in database output (square bracket changed to curly bracket)

### ISSUE THREAD

**Issue by obambrough** [cweijan/vscode-mysql#381]
- OS: MacOS
- Database Type: Postgres

This worked in Database Client 4.2.1. Its broken in 4.2.2 and above (4.3.0 is the current version.)

Arrays in json fields are broken. Database client is converting the square bracket into a curly bracket. This happens for all arrays within the json.
e.g. instead of getting `[{"name": "x"}]` its showing `{{"name": "x"}}`. 

![image](https://user-images.githubusercontent.com/1922249/144128437-d9d3bc51-1ee6-4dca-9e2a-73f317c60e21.png)

**Comment by cweijan** [comment]
Thanks for the feedback, the problem will be fixed in the next version。

**Comment by cweijan** [comment]
Fix at version 4.3.1.
