### ISSUE TITLE
[BUG]表结构更新后，插入数据（新字段）失败

### ISSUE THREAD

**Issue by daGaiGuanYu** [cweijan/vscode-mysql#382]
环境：mysql 5.7  
复现：
+ 使用 vscode-database-client（以下称 vdc） 创建连接
+ 打开 A 表
+ **在别处**添加一个字段到 A 表
+ 点击 vdc 的 “excute sql”按钮（像“播放按钮”那个），可以看到表结构已更新
+ 对新加字段设置值，```ctrl + s``` 保存失败（没反应）

应急解决方案：
![应急解决方案](https://user-images.githubusercontent.com/27003009/144159827-f1aecf46-b23d-406b-b01c-718b81e23767.png)

**Comment by cweijan** [comment]
结果页的表信息在打开时加载的， 你重新点击下表试试。

**Comment by cweijan** [comment]
哦不， 我看错了， 这是因为对表结构做了缓存， 你在别处修改就是需要点击刷新表结构。

**Comment by daGaiGuanYu** [comment]
我想，如果方便的话，可以在某些操作（比如查询）发生时，刷新一下表结构  
或者添加一个刷新表结构的按钮  
因为查询的数据显示表结构已经更新，但**数据更新操作执行不了**，有点出人预料  
感谢您提供这么好用的插件 @cweijan

**Comment by cweijan** [comment]
你用这个扩展执行就会自动刷新，你用别的工具就不行，以后我弄个设置禁用部分缓存。

**Comment by cweijan** [comment]
刷新表结构按钮是有的， 就是你截图的那个， 或者点击最顶层的刷新按钮， 刷新所有缓存。
![image](https://user-images.githubusercontent.com/27798227/144164959-e9c8db3c-9748-441e-811b-05ab49615658.png)

**Comment by daGaiGuanYu** [comment]
好的，了解
