### ISSUE TITLE
[BUG] Cannot see database even after a successful connection in gitpod vscode

### ISSUE THREAD

**Issue by rajkstats** [cweijan/vscode-mysql#383]
- OS: macos BigSur
- Database Type: Postgres
![image](https://user-images.githubusercontent.com/10900298/144183004-b990cb94-722d-44b3-9004-c0f4a51ad006.png)

**Comment by cweijan** [comment]
I have released multiple extensions, you only need to install one。
[Database Client](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2)

**Comment by rajkstats** [comment]
yes, I am using multiple now for the workaround. I have been using database client only. It's not working for me. I cannot see the database I'm connected to. This has been super useful for us. This is happening with other folks in my cohort as well. Probably, I'm missing something here.

**Comment by cweijan** [comment]
You have installed multiple extensions of mine, because the buttons are repeated, you need to uninstall them first and update the extensions to the latest version。
![image](https://user-images.githubusercontent.com/27798227/144184196-39fca082-e7ad-421f-8259-ec5fefa4eeda.png)

**Comment by rajkstats** [comment]
Awesome. Thanks for your help. It's working now. I couldn't have figured this out by myself.
