### ISSUE TITLE
[BUG] Wrong resulset when retrives columms with same name from differents tables

### ISSUE THREAD

**Issue by carrony** [cweijan/vscode-mysql#384]
Hi!.

I've found a problem when retrieving the resulset of a query, when there are two columns with the same name from different tables, the two columns show the same information.

<img width="796" alt="issue1" src="https://user-images.githubusercontent.com/33500700/144199187-7122d007-cd17-4638-998d-a234d72302e6.png">

To fix the resultset I have to add an alias for any of the column for change his name and then the problem fixes.

<img width="792" alt="issue2" src="https://user-images.githubusercontent.com/33500700/144199357-78380057-414f-467e-bb42-2bf05744763b.png">

Is it a performance feature for speed up the queries or save memory retrieving them?

- OS: Windows 10 Pro
- Database Type: MySQL
- Database client v4.3.0

**Comment by cweijan** [comment]
The extension is developed using javascript, and javascript does not support attributes with the same name, you need to use an alias.
