### ISSUE TITLE
[BUG] can't write a slash( \ ) in column by ui-table.

### ISSUE THREAD

**Issue by helpotcreator** [cweijan/vscode-mysql#385]
- OS: Window10 vscode
- Database Type: MariaDB (UTF8mb4)
- can't write a slash( \ ) in column by ui-table.
- ex) C:\windows\~~\~~\~~  --then-->  C:windows~~~~~~

Thanks.
Best regards.

**Comment by cweijan** [comment]
You need write \\\\.

**Comment by helpotcreator** [comment]
thanks.
But, there is an another issue.
if I update a column for remove another character.
then, all '\\' characters are disappear in column.
ex)  C:\windows\systems\fonts
-- update&save --> C:\windows\systems\cursors
-- disappear&save --> C:windowssystemscursors

**Comment by cweijan** [comment]
There is indeed a problem, the backslash is treated as an escape character, I will fix it in the next version

**Comment by helpotcreator** [comment]
Thank you for your contribution~!~ thanks.

**Comment by cweijan** [comment]
Fix on version 4.3.3.

**Comment by helpotcreator** [comment]
I checked it on V4.3.3.
But there is a little issue.

D:\가\youtube\나
-- I want -->>  D:\가\yobe\나
-- but -->> D:\가yobe나

I don't know, But the issue seems to be language code related.(korean)

**Comment by cweijan** [comment]
Yes, there are still problems, wait for the next version to fix.

**Comment by cweijan** [comment]
Try version 4.3.5.

**Comment by helpotcreator** [comment]
has been resolved.
this plugin will be very useful in my life.
thanks. xie xie!!
