### ISSUE TITLE
如图，希望对侧边栏连接名做调整优化

### ISSUE THREAD

**Issue by wen-gg** [cweijan/vscode-mysql#386]
![微信图片_20211202141027](https://user-images.githubusercontent.com/17865026/144367681-7fcb0269-d157-456e-9184-14adbda33337.png)
如图，当我填写有连接名称时，希望连接名称放在最前面（主机名之前）便于识别，而不是放在最后，如果主机名够长就看不见了也不便于识别

**Comment by cweijan** [comment]
勾选这个设置, 将使用连接名称替代主机名称
![image](https://user-images.githubusercontent.com/27798227/144376543-6702b16e-555d-4f7d-8de0-241547378841.png)

**Comment by wen-gg** [comment]
感谢！大意了
