### ISSUE TITLE
[FR] Filter table names

### ISSUE THREAD

**Issue by alexandernst** [cweijan/vscode-mysql#387]
It would be very useful if there was a way to filter the list of tables in the left bar (a simple text field with basic filtering capabilities would be more than enough imho).

**Comment by cweijan** [comment]
Vscode does not support the creation of input boxes, so there is no way.

**Comment by alexandernst** [comment]
@cweijan Do you happen to know if this is a design limitation or if maybe VS Code devs are willing to implement support for such a feature?

**Comment by cweijan** [comment]
You can go to vscode to search for related issues.
https://github.com/microsoft/vscode/issues/50062

**Comment by alexandernst** [comment]
I spent some time digging in the docs and the changelogs. Wouldn't this be possible to be implemented using the new tree widget? https://code.visualstudio.com/updates/v1_31#_new-tree-widget

It does seem to provide filtering capabilities

Also https://github.com/microsoft/vscode/pull/76407 for actual code

**Comment by cweijan** [comment]
I have marked this way on the readme.
![1](https://github.com/cweijan/vscode-database-client/raw/master/images/filter.gif)

**Comment by Dhenyson** [comment]
> I have marked this way on the readme. ![1](https://github.com/cweijan/vscode-database-client/raw/master/images/filter.gif)

In fact this is a solution, not friendly but it works. A specific research field would be ideal, I will keep an eye on possible solutions, but for now it will do.
