### ISSUE TITLE
Can't buy you a Coffee in China

### ISSUE THREAD

**Issue by Excited-ccccly** [cweijan/vscode-mysql#389]
This tool saves me and I would like to buy you a Coffee. But Paypal rejected my transaction due to legal reasons.

Can provide a Wechat Payment QR Code to bypass Paypal.

**Comment by cweijan** [comment]
Thanks for your support, you can use this QR code.
![89515cd1e20511ca36a76aad810197a](https://user-images.githubusercontent.com/27798227/144606745-9c4e354f-376d-481d-8597-63c6cb6e2000.jpg)
