### ISSUE TITLE
https scheme for elasticsearch

### ISSUE THREAD

**Issue by df-cgdm** [cweijan/vscode-mysql#390]
It would be good to be able to select the scheme (http/https) for ElasticSearch connection.

**Comment by cweijan** [comment]
You need to use the latest version.

**Comment by df-cgdm** [comment]
I have the latest version (4.3.2) but I do not see any button or check box for that:
![Screenshot 2021-12-07 100307](https://user-images.githubusercontent.com/7581646/144998923-47a874b1-76be-412b-a5f0-eed059bc261d.png)
at

**Comment by cweijan** [comment]
Using https://host:port.

**Comment by df-cgdm** [comment]
Thank you. It works
