### ISSUE TITLE
Sorting tables and views by name

### ISSUE THREAD

**Issue by saskiaNoir** [cweijan/vscode-mysql#391]
showTriggers(database: string): string {
        return `SELECT TRIGGER_NAME "TRIGGER_NAME" FROM information_schema.TRIGGERS WHERE trigger_schema = '${database}' ORDER BY TRIGGER_NAME ASC`;
    }
    showProcedures(database: string): string {
        return `SELECT ROUTINE_NAME "ROUTINE_NAME" FROM information_schema.routines WHERE ROUTINE_SCHEMA = '${database}' and ROUTINE_TYPE='PROCEDURE' order by ROUTINE_NAME ASC`;
    }
    showFunctions(database: string): string {
        return `SELECT ROUTINE_NAME "ROUTINE_NAME" FROM information_schema.routines WHERE ROUTINE_SCHEMA = '${database}' and ROUTINE_TYPE='FUNCTION' order by ROUTINE_NAME ASC `;
    }
    showViews(database: string): string {
        return `SELECT * FROM (SELECT table_name "name",'simple' "type" from information_schema.tables where table_schema='${database}' and table_type='VIEW' 
UNION ALL
SELECT matviewname "name",'material' "type" from pg_matviews
WHERE schemaname='${database}') v order by v."name" ASC`
    }

showTables(database: string): string {
        return `  SELECT t.table_name "name", pg_catalog.obj_description(pgc.oid, 'pg_class') "comment"
FROM information_schema.tables t
JOIN pg_catalog.pg_class pgc ON t.table_name = pgc.relname 
JOIN pg_catalog.pg_namespace pgn ON pgn.oid=pgc.relnamespace and pgn.nspname=t.table_schema
WHERE t.table_type='BASE TABLE'
AND t.table_schema='${database}' order by t.table_name;`
    }
    showDatabases() {
        return `SELECT datname "Database" FROM pg_database WHERE datistemplate = false order by datname ASC;`
    }
    showSchemas(): string {
        return `select catalog_name "Database",schema_name "schema" from information_schema.schemata order by schema_name ASC;`
    }

**Comment by anikadegreif** [comment]
#392

**Comment by anikadegreif** [comment]
Pull request #392

**Comment by cweijan** [comment]
Release on version 4.3.3.
