### ISSUE TITLE
Parametrs in Sql queryes

### ISSUE THREAD

**Issue by RavenSp** [cweijan/vscode-mysql#393]
Thank you for your product! He's wonderful. I would very much like to be able to add parameters of the ": value" type to the SQL query. This would allow developing ready-made queries for SqlAlchemy without overloading the query with time parameters. Thank you very much in advance!

**Comment by cweijan** [comment]
I do not plan to implement a function for a specific application.

**Comment by cweijan** [comment]
I have supported SQL parameters in version 5.2.2, note that strings need to be added with quotes.
![image](https://user-images.githubusercontent.com/27798227/165432752-c5c3eb09-9d81-44dc-bc5d-b65915dd3411.png)
