### ISSUE TITLE
list item name change

### ISSUE THREAD

**Issue by bgbruno** [cweijan/vscode-mysql#395]
would be great if I can change name in list of databases
means switch
{{cnn}} {{name}} -> {{name}} {{cnn}}
or even hide cnn
{{cnn}} {{name}} -> {{name}}

**Comment by cweijan** [comment]
The database name does not support modification, this is a limitation of the database.

**Comment by cweijan** [comment]
You can display only the databases you need.
![image](https://user-images.githubusercontent.com/27798227/145341071-e0670587-0fe4-4526-b7ce-06b16aa4c98b.png)

**Comment by bgbruno** [comment]
@cweijan this is not the same - it change nothing in list

I want order in my connections you know 🙂
you see one is "fs path" another "db cnn" - I want "my custome names of items" eg
- aws db1
- do db1
- pscale db1
- pscale db2

<img width="1281" alt="Screenshot 2022-03-05 at 00 32 45" src="https://user-images.githubusercontent.com/1760203/156856239-7c9e232e-e311-4414-8de0-713c85ce9570.png">

**Comment by cweijan** [comment]
Check it!
![image](https://user-images.githubusercontent.com/27798227/156861530-0038896c-5f40-476f-8bca-aa96fa10f14a.png)

**Comment by bgbruno** [comment]
cool cool it works through "vsc settings" `settings.json` thx
`"database-client.preferConnectionName" : true`

through "plugin gui" it doesn't
`Free account not support update option!`

![Screenshot 2022-03-05 at 05 24 20](https://user-images.githubusercontent.com/1760203/156867799-73c17394-26f1-4cc9-9133-9fa17b622eea.jpg)

**Comment by cweijan** [comment]
The new features in the future are only open to premium, you can set them through the settings that come with vscode.
![image](https://user-images.githubusercontent.com/27798227/156869413-6cda2dff-5b9a-4a8c-ba96-5b2249cb954a.png)
