### ISSUE TITLE
对于大数据量的表，计算 total 和分页耗时比较长，希望能提供选项关掉这个功能

### ISSUE THREAD

**Issue by tonghs** [cweijan/vscode-mysql#396]
![image](https://user-images.githubusercontent.com/2345536/145344271-adb4a3fa-ae6a-4fe5-81df-a79a118b27c7.png)

首先非常感谢能提供这么好用的工具。

我在使用时遇到的问题：
1. 执行一个大表查询 sql，有指定 limit，执行完好像会异步生成 total 和分页。
2. 在 total 和分页生成之前再执行另外一条 sql 时会 block 住，直到上一次结果的 total 和分页生成完成。

对于大表（千万级别）查询 total 耗时能再 10+秒，每次都等感觉好难……希望能提供选项关掉【生成 total 和分页】的功能。

后端开发对于 ts 不太熟悉，大概翻了翻代码还没搞清楚逻辑，如果能自己改我就发个 PR 上来。

🙏

**Comment by cweijan** [comment]
等下个版本我增加个选项禁用.

**Comment by cweijan** [comment]
版本4.3.3可以关闭了.
![image](https://user-images.githubusercontent.com/27798227/145587860-86afc898-3ec8-4640-ba80-4e3b4708edbe.png)
