### ISSUE TITLE
Select multiple redis keys and delete all

### ISSUE THREAD

**Issue by baojd42** [cweijan/vscode-mysql#398]
I would like to delete a batch of redis keys. But currently it seems I can only do it one by one.

![image](https://user-images.githubusercontent.com/33564834/145509419-e37d98a9-186e-40db-814a-a76d253e0d6d.png)
I found a issue related, but not totally fit my case, as I don't even have a grouped folder here. #143 

It would be nice if I can select multiple keys and delete them.

**Comment by cweijan** [comment]
Vscode does not support multiple selection, so it can’t. At present, the extension supports deleting folders. If your keys meet the rules of folders, you can delete them in batches.
![image](https://user-images.githubusercontent.com/27798227/145511310-6f7d12bb-455c-447f-8fa8-cf3d527aef78.png)

**Comment by baojd42** [comment]
@cweijan Thanks for you quick reply!

There is an API option, ['canSelectMany'](https://code.visualstudio.com/api/references/vscode-api#TreeViewOptions), however I am not sure if that is the entry to trigger the behaviour and didn't try it. Maybe that will be helpful?

**Comment by cweijan** [comment]
Does not have this option.

**Comment by baojd42** [comment]
Hi, I created a pull request to primitively implement the feature. It only works for redis and KeyNode. The folderNode and a mix of folderNodes/KeyNodes should also be considered later.

**Comment by cweijan** [comment]
Release on version 4.3.3.
