### ISSUE TITLE
[BUG] Illegal mix of collations

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#399]
- OS: Windows
- Database Type: MySQL 8.0.21

Dear Sir,

I use this extension for creating and managing functions and procedures in MySQL.   But in MySQL Version 8 onwards, I am getting the following error when a procedure is executed by my application:

Illegal mix of collations (utf8mb4_0900_ai_ci,COERCIBLE) and (utf8mb4_unicode_ci,COERCIBLE) for operation '='

The syntax in the package which creates this error is as follows:

IF DELIMITEDTEXT(GEXTDATA,'|',2) = '9' THEN

    -- Code to be executed

END IF;

If I write the query as follows, the error is not generated

IF BINARY(DELIMITEDTEXT(GEXTDATA,'|',2)) = '9' THEN

    -- Code to be executed

END IF;

The error with the first code arises only if I compile/update the procedure in VS Code, using this extension.

**If I update the procedure through CMD or my earlier IDE - DBForge for MySQL, this error is not getting generated.**

As now I am only using this extension for managing MySQL DB, this error creates a headache for me and my teammates.

Request your guidance on resolving this error

Thanks and Regards,

Franklin

**Comment by cweijan** [comment]
This seems to be an error returned by mysql server. Since I am not familiar with stored procedures and function, I cannot help you。

**Comment by cweijan** [comment]
https://stackoverflow.com/questions/44027987/illegal-mix-of-collations-utf8mb4-unicode-ci-implicit-and-utf8mb4-general-ci

**Comment by franklinkf** [comment]
Thanks.  I settled by placing the following declaration as the first line in my procedures and functions

SET NAMES utf8mb4;

Thank you once again
