### ISSUE TITLE
Error: ER_NO_SUCH_TABLE: Table 'mysql.proc' doesn't exist

### ISSUE THREAD

**Issue by pucicu** [cweijan/vscode-mysql#4]
I have connected to a database from MySQL ver. 8.0.19 (on macOS). Every time I start Code, I get a number of (identical) errors
`Error: ER_NO_SUCH_TABLE: Table 'mysql.proc' doesn't exist`
I do not know how solve this. I found some webpages, like this one: <https://stackoverflow.com/questions/51712260/error-table-mysql-proc-doesnt-exist-when-adding-mysql-data-source-to-visua>, but it is not helpful.

**Comment by cweijan** [comment]
Plugin get procedure info from table mysql.proc, mysql 8.0 is removed.
New version 1.6.35 has bean resolve this error.

**Comment by pucicu** [comment]
thank you very much for this superfast fix!
