### ISSUE TITLE
[BUG]无法提示表名，并且下面的Output会报错

### ISSUE THREAD

**Issue by 0reoo** [cweijan/vscode-mysql#400]
- OS: MacOs 12.1 Macbook Air M1
- Database Type: MySQL
- 插件版本：v4.3.2
- vscode版本：1.63.0
![image](https://user-images.githubusercontent.com/9780786/145552704-51889779-63f4-4e37-a0c7-d0d1b05fcec8.png)

**Comment by cweijan** [comment]
应该是当前没有激活的连接导致的。
![image](https://user-images.githubusercontent.com/27798227/145565943-ebb6f9be-b117-4d18-a528-c0425ca55e47.png)

**Comment by cweijan** [comment]
版本4.3.3修复了.

**Comment by 0reoo** [comment]
赞

**Comment by 0reoo** [comment]
为你的快速响应点赞👍🏻
但是我更新到4.3.3并且激活了数据库还是无法自动提示表名，Output依旧输出
`TypeError: Cannot read property 'getChildren' of undefined`
不过现在已经没有一直输出的问题了

**Comment by cweijan** [comment]
你试下这个, sql编写不能提示那肯定一堆反馈, 不太可能
![image](https://user-images.githubusercontent.com/27798227/145664203-662f5b37-d65b-4ed9-8069-3161bcd818bd.png)

**Comment by cweijan** [comment]
你是隐藏了存储过程这些吗

**Comment by 0reoo** [comment]
是的，这是我的设置
![image](https://user-images.githubusercontent.com/9780786/145665231-937a0ea7-b219-4673-a45d-ce3bc94c9f10.png)

**Comment by 0reoo** [comment]
试了下，重新勾上之后就好了😂

**Comment by cweijan** [comment]
试下版本4.3.5.
