### ISSUE TITLE
[BUG] JOINs with same column names lead to the first column values being overridden by the other column values in the result table

### ISSUE THREAD

**Issue by JaakkoRoponen** [cweijan/vscode-mysql#405]
If you join two tables and they have a column with the same name, then in the resulting table the first column's values are overridden by the other column's values.

example:

SELECT * FROM table1 JOIN table2 ON table1.id = table2.table1_id;

    id                                  |     id     |     table1_id        |      ...
    1                                         1                 1
    2                                         2                 1
    3                                         3                 2
    4                                         4                 2
    ^ value from here  ------> ^                 ^ correct value
...

- OS: Windows 10 WSL2 Ubuntu-20.04
- Database Type: MySql

**Comment by cweijan** [comment]
Yes, nodejs does not support duplicate name columns, you need to use aliases.

**Comment by JaakkoRoponen** [comment]
Could this be automatic somehow? Maybe you could alias these automatically in the table created by nodejs, for example, by prepending the table name? It's very slow to alias multiple columns when you really just need a simple SELECT *

**Comment by cweijan** [comment]
No, duplicate columns in sql query is an error.
