### ISSUE TITLE
Add padding to the add connect page (on sidebar expand)

### ISSUE THREAD

**Issue by bukitoka** [cweijan/vscode-mysql#407]
Hi, I think the connect page need some padding to add when sidebar is expanded. For the clear issues please see the difference between the screenshot. Have a great day!

![Screenshot (453)_LI](https://user-images.githubusercontent.com/47457477/147170851-8b55350b-8ac1-4ec5-853e-07778f9feba1.jpg)
![Screenshot (454)](https://user-images.githubusercontent.com/47457477/147170854-c3318d58-1f59-456d-b19f-b8bf7713f1a5.png)

**Comment by cweijan** [comment]
Enhance at version 4.3.6.

**Comment by bukitoka** [comment]
Thanks, great work!
