### ISSUE TITLE
[BUG]调整字段顺序导致字段属性丢失

### ISSUE THREAD

**Issue by pinyht** [cweijan/vscode-mysql#409]
- OS: MacOS 12.1
- Database Type: MySQL 8.0.26

展开数据表后的字段列表界面中,对字段进行上移下移调整顺序操作会造成字段原有属性丢失,例如not null,comment等, 希望这个操作能增加SQL语句预览和确认保存提示

**Comment by cweijan** [comment]
版本4.3.6已增加提示.

**Comment by pinyht** [comment]
尝试了最新版，当调整字段顺序后会丢失not null，default，comment等属性的问题仍然存在，麻烦有时间排查一下，谢谢

**Comment by cweijan** [comment]
只是增加了个提示, 丢失的信息没有调整.

**Comment by cweijan** [comment]
已在5.0.2版本中修复.
