### ISSUE TITLE
Option to Display Connection Name Before Host + Port

### ISSUE THREAD

**Issue by fpaguiar** [cweijan/vscode-mysql#410]
Not sure if this is already possible, but I would prefer to have the connections listed by the `Connection Name` field first, instead of `Host+Port` fields:

![image](https://user-images.githubusercontent.com/22917135/147364671-8ad52ca3-aa1f-4de5-81f2-7c1d6f14bf96.png)

Would you consider adding this enhancement for a future release?

Thanks!

**Comment by cweijan** [comment]
Hi, you can check this option.
![image](https://user-images.githubusercontent.com/27798227/147368374-c07bd7c1-af8a-4f69-8236-d44117be74e3.png)
