### ISSUE TITLE
[BUG] Update string column as \() failed.

### ISSUE THREAD

**Issue by a3626a** [cweijan/vscode-mysql#411]
- OS: Windows + WSL
- Database Type: MySQL

I modified "error_value" field as `\()` and `ctrl + s`. 
![image](https://user-images.githubusercontent.com/4434752/147475323-96a62c47-b00d-4bdd-8645-7dada039c6b6.png)

**Comment by cweijan** [comment]
This is because I parse the brackets into function calls, not occur by \\, and I will optimize this operation in future versions

**Comment by cweijan** [comment]
Fix at version 4.5.0.
