### ISSUE TITLE
trouble connecting to a postgres db

### ISSUE THREAD

**Issue by judell** [cweijan/vscode-mysql#412]
- OS: Windows/WSL2
- Database Type: Postgres

Thank you for making this excellent tool!

I have a Postgres db to which I can connect like so:

`psql "postgresql://user:pass@host:port/dbname"`

Case 1: Specifying settings individually, with SSL on:

`Connection error! unsupported startup parameter: statement_timeout`

Case 2: Using the connection string, and with SSL on:

`Connection error! unsupported startup parameter: SSL required`

My questions:

Why the different behaviors in these two cases?

Why in case 2, with the SSL switch on, does it still say SSL required?

**Comment by cweijan** [comment]
The first problem seems to be that your PostgreSQL version is lower and does not support statement_ Timeout parameter. 
The second problem is that if you use SSL, the connection string should be changed, https://stackoverflow.com/questions/22301722/ssl-for-postgresql-connection-nodejs

**Comment by judell** [comment]
For 1, it's Postgres 12.1 which does seem to support [statement_timeout](https://www.postgresql.org/docs/12/runtime-config-client.html#GUC-STATEMENT-TIMEOUT)

For 2, if I add `ssl=true` to the connection string, then it's "Connection error! unable to get local issuer certificate" -- looks like I'm supposed to fill in CA cert and client cert details?

**Comment by cweijan** [comment]
Issue2 You need to find more parameters by yourself, I am not familiar with them.

**Comment by cweijan** [comment]
Try version 4.4.0, I ignored the statement_timeout parameter if you didn't set it.

**Comment by judell** [comment]
That works, thanks so much!
