### ISSUE TITLE
[BUG] canceling statement due to statement timeout

### ISSUE THREAD

**Issue by onlySlient** [cweijan/vscode-mysql#413]
```
select count(*)
from abc
where length(aa::text) > 30000
```

> `aa` is jsonb type

error message:
> canceling statement due to statement timeout

**Comment by cweijan** [comment]
Try change request timeout.
![image](https://user-images.githubusercontent.com/27798227/147641841-48f9cd65-af66-4f40-a1f8-2ad2c322c85e.png)
