### ISSUE TITLE
[BUG] Executing a sql statement from the command line and clicking on 'run sql' in a sql statement does not give the same result in the box on the right

### ISSUE THREAD

**Issue by SYYANI** [cweijan/vscode-mysql#415]
- OS: macOS 12 / Windows 10
- Database Type: mysql
Executing a sql statement from the command line and clicking on 'run sql' in a sql statement does not give the same result in the box on the right

**Comment by SYYANI** [comment]
especially  'inner join' command
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/40732861/147900682-10f0ab3f-965c-43e8-b500-4e8143af590e.png">
<img width="418" alt="image" src="https://user-images.githubusercontent.com/40732861/147900692-724272b0-cb5f-4491-b212-2a8d87ef8e1e.png">

**Comment by cweijan** [comment]
The extension is developed using nodejs. Nodejs does not allow duplicate name attributes, so you need to avoid columns with the same name in your query, which is also the best practice of SQL.

**Comment by cweijan** [comment]
I have added the relevant description to the document, this issue cannot be supported.
