### ISSUE TITLE
[BUG]MongoDB Error: Method not implemented.

### ISSUE THREAD

**Issue by DanaCoding** [cweijan/vscode-mysql#416]
# 1. Failed - to create new database

![h4](https://user-images.githubusercontent.com/93444868/148109563-f05a9521-b3df-43e8-8d01-96b976b221e8.gif)

<hr/>

# 2. Failed - to insert data

```base
db.inventory.insertOne(
   { item: "canvas", qty: 100, tags: ["cotton"], size: { h: 28, w: 35.5, uom: "cm" } }
)
```

![image](https://user-images.githubusercontent.com/93444868/148122441-6cdee76d-4a1a-460b-82ac-f263c919fd62.png)

![h3](https://user-images.githubusercontent.com/93444868/148122244-bd6adab4-724b-4372-8802-9751f3377d21.gif)

<hr/>

# 3. Success - MongoDB official extension

![image](https://user-images.githubusercontent.com/93444868/148124687-5f477cf2-31c3-4b9e-a606-009139875d66.png)
![h6](https://user-images.githubusercontent.com/93444868/148123764-210b2a6b-646c-4b47-9123-779c076c4962.gif)

<hr/>

# 4. Success - enter via Terminal

![h1](https://user-images.githubusercontent.com/93444868/148146812-41f86bb2-7a0a-4130-9590-af213ab7eff8.gif)

<hr/>

- OS: Win10 Pro
- Database Type: MongoDB 5.0.5

**Comment by cweijan** [comment]
This extension does not have high support for mongodb, it is only recommended for browsing data.

**Comment by cweijan** [comment]
Mongodb stop maintenance.
