### ISSUE TITLE
No active database connection found!

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#420]
When I try to run a query,
The following error appears and I can not select any connection to run the query!

No active database connection found!

Can I select a connection for the query?

**Comment by cweijan** [comment]
Have you tried this?
![image](https://user-images.githubusercontent.com/27798227/148182708-e43f0d27-e125-4cb2-9deb-a941c5693d6f.png)

**Comment by mbtolou** [comment]
thanks

can you add icon to this point ?

![image](https://user-images.githubusercontent.com/6413705/148195130-aa3924c5-d758-47c6-8b31-e2a5b08eadd6.png)

**Comment by cweijan** [comment]
This is indeed a good idea.

**Comment by cweijan** [comment]
After experimenting, switching active databases at the connection node is not as flexible as through the right-click menu, so I canceled this plan.
