### ISSUE TITLE
Can you open the results window at the bottom by default ?, it will now open on the side

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#422]
Hi.
Can you open the results window at the bottom by default ?
it will now open on the side

![image](https://user-images.githubusercontent.com/6413705/148248070-a0e68fad-8073-4d91-bdb1-47191b4d8191.png)
![image](https://user-images.githubusercontent.com/6413705/148248081-55bde11f-de9b-4a30-93ae-f0757835647a.png)

**Comment by cweijan** [comment]
I will add an option to control it in the new version.

**Comment by cweijan** [comment]
Change at version 4.5.0.

**Comment by mbtolou** [comment]
thanks
