### ISSUE TITLE
formatter config

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#423]
Hi.

some feature for formatter config .

space after query.
indent space .
change keyword case (UPPER,lower,Mixed,None).
compact sql mode like :
```sql
compact mode
select aa.meter_no,aa.parent_meter_no,aa.apdu_size,aa.client
from ahe.tbl_meters aa
limit 100;

normal mode
select
  aa.meter_no,
  aa.parent_meter_no,
  aa.apdu_size,
  aa.client
from
  ahe.tbl_meters aa
limit
  100;
```

thanks

**Comment by cweijan** [comment]
The formatter is extracted from sql-formatter, and maintenance has been discontinued.

**Comment by mbtolou** [comment]
https://github.com/zeroturnaround/sql-formatter

demo : 
https://extendsclass.com/sql-formatter.html

**Comment by cweijan** [comment]
Sorry I didn’t look at your question carefully yesterday. I thought it was a feedback bug. I tried this demo. The compact mode is not friendly, and I don’t plan to configure upper and indent.
