### ISSUE TITLE
save config and history file in workspace folder.

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#424]
hi.
save config and history file in workspace folder.
Some features will be added to the system with this event.
For example, the ability to save and retrieve at the git , or work with vscode server , or remote development .

These files are now stored in the user's folder.

**Comment by cweijan** [comment]
The history record is just a remedy, I will not move it to the workspace, the configuration will be stored in the workspace in the branch workspace-config, when it is completed, it will be released in the new version.

**Comment by cweijan** [comment]
Version 3.5.2 has support for storing configuration to workspace
![image](https://user-images.githubusercontent.com/27798227/150482505-7954b800-760c-4386-baff-a7246412e179.png)
