### ISSUE TITLE
add limit to sql automatically

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#425]
Hi.

add limit to sql automatically (like dbeaver). 
If working with large tables, it is not possible to cancel the query, and it will cause the program to crash.

![image](https://user-images.githubusercontent.com/6413705/148252244-de5671d3-d81c-4cea-84e8-a04a92bc66d5.png)

**Comment by cweijan** [comment]
I’ve considered this before, but I think the extension should not interfere with the user’s behavior, so I won’t make this feature.

**Comment by mbtolou** [comment]
Can you consider an settings for this?

**Comment by cweijan** [comment]
I don’t plan this. If the database operated by the user already has a lot of data, then he should have a certain amount of database experience and should avoid full-table queries.
