### ISSUE TITLE
Better row insertion feature

### ISSUE THREAD

**Issue by dathoangnd** [cweijan/vscode-mysql#427]
Hello. Thank you for such an awesome plugin. Just one thing I think it should be much better. Can you please consider improving adding row feature like this:

- Click on "Add row" button.
- An empty row appear right at the bottom instead of showing popup (so we can easily see column type and copy value of existing rows).
- Click Run to commit the change.

Thank you again.

**Comment by cweijan** [comment]
Support at version 4.5.0.
