### ISSUE TITLE
[BUG]用AS关键字命名表名导致列名的自动补全失效

### ISSUE THREAD

**Issue by lpzzz** [cweijan/vscode-mysql#428]
- OS: Windows
- Database Type:  MySQL

### 有AS关键字的情况下：
+ 在SELECT后自动补全完全失效
![with_as_select](https://user-images.githubusercontent.com/27475628/148369003-aed32079-d49b-4086-8eae-8a51ef690ec6.png)
+ 在WHERE后自动补全需要用首字母触发
![with_as_where](https://user-images.githubusercontent.com/27475628/148369008-97cfabb1-2e7a-40fd-adfd-edbbc33c830d.png)

### 无AS关键字的情况下：
+ 在SELECT和WHERE后都可以正常触发补全
![without_as_select](https://user-images.githubusercontent.com/27475628/148369012-45ccf592-7257-45bc-890b-ed9936e3d672.png)
![without_as_where](https://user-images.githubusercontent.com/27475628/148369015-919a3b71-4873-4168-8f9d-d2d5321aab53.png)

**Comment by cweijan** [comment]
已在版本4.5.0修复
