### ISSUE TITLE
[BUG] 连接出错! All configured authentication methods failed

### ISSUE THREAD

**Issue by JavaHello** [cweijan/vscode-mysql#430]
- OS: MacOS Monterey 12.1
- Database Type: Mysql

## 问题
使用`SSH隧道`无法连接到数据库 error:
```txt
连接出错! All configured authentication methods failed
```
## 备注
使用终端可连接到服务器, 其它客户端可正常连接
```sh
 ssh xxx@xxx.xxx.xxx.xxx -p xxx
```

**Comment by cweijan** [comment]
ssh命令会自动读取你.ssh目录的私钥, 这个扩展不会, 你需要指定私钥位置
![image](https://user-images.githubusercontent.com/27798227/148503218-969075b3-5e3c-4558-bf3d-874aea3a7571.png)

**Comment by JavaHello** [comment]
谢谢解答，密码输入错误了
