### ISSUE TITLE
ssh跳板机连接

### ISSUE THREAD

**Issue by renewfan** [cweijan/vscode-mysql#431]
目前版本无法ssh跳板机连接

**Comment by cweijan** [comment]
你是通过ssh连接数据库还是要连到ssh服务器, 描述需要清晰点..

**Comment by renewfan** [comment]
就是阿里云ssh堡垒机连接服务器（登录ssh在进行二次短信验证），目前连接失败显示如图
![image](https://user-images.githubusercontent.com/28864739/148523389-d81b6201-2999-4be1-8de0-6ac94d4ab45f.png)
正常来说连接后应该是输入验证码的界面，比如下图
![image](https://user-images.githubusercontent.com/28864739/148524505-f4502b6e-2509-4de5-93b5-00ab8749c168.png)

**Comment by renewfan** [comment]
> 你是通过ssh连接数据库还是要连到ssh服务器, 描述需要清晰点..

[抱歉简单描述，具体描述如下](https://github.com/cweijan/vscode-database-client/issues/431#issuecomment-1007262850)

**Comment by cweijan** [comment]
这是阿里云自己的限制, node的ssh程序不支持这种, 你看能不能取消他这个验证, 或者改为私钥登录.
