### ISSUE TITLE
Hide Drop database option

### ISSUE THREAD

**Issue by dathoangnd** [cweijan/vscode-mysql#433]
Hi,

By any chance can you please add a setting to hide "Drop database". Some other apps like TablePlus don't allow to drop database, this option is too dangerous when you are connecting to a production database. I think it should only allow to remove the connection.

**Comment by cweijan** [comment]
No, when you delete the database, the extension will ask you to complete the database name, it is reasonable for a database management tool to provide management functions for the database.
