### ISSUE TITLE
[BUG] SSH 链接被错误放置在 NOSQL 下

### ISSUE THREAD

**Issue by tigerinus** [cweijan/vscode-mysql#435]
- OS: Ubuntu
- Database Type: SSH

添加 SSH 后出现在 NoSQL 下：

![image](https://user-images.githubusercontent.com/7172560/148663110-a8eb8bc3-c3ad-4ff8-9437-759742d4bace.png)

**Comment by cweijan** [comment]
SSH连接就是放在NoSQL的, 只有两个面板只能放这里

**Comment by tigerinus** [comment]
问题是我在 database 面板里点添加，结果 database 里什么都没有出现。直到下午才发现在 NoSQL 面板里多了一堆 SSH 链接。

建议弹一个信息出来告诉用户新的连接添加到哪里了

**Comment by cweijan** [comment]
这两个面板的添加按钮都是同一功能, 本来是想添加按钮后就聚焦到对应的面板, 但是vscode没有相关API.
