### ISSUE TITLE
Can you add SOCK/proxy support for SSH?

### ISSUE THREAD

**Issue by jsnhsu** [cweijan/vscode-mysql#438]
First of all, I just found that the Database Client is a wonderful tool.  Especially, it can tunneling so many db tool via ssh that helps me a lot.

However, I still have additional need just because of my dev environment.  I'm using the VSCode on my host box and a Windows vm which connects to my office via vpn.   And I installed both the squid and bitvise client with SOCKS/HTTP proxy forwarding enabled on that vm to provide proxy/sock service like a gateway.

So I hope your ssh can add make the connection via SOCKS/HTTP then the database connection can do via the ssh tunnel.

**Comment by cweijan** [comment]
The dependent library used by this extension cannot support such a function. I wonder why there is a need for socks proxy. As far as I know, most database management systems such as navicat and DataGrip do not support socks proxy.

I looked at your working environment, the solution is to install openssh server on your windows machine, see https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH.
