### ISSUE TITLE
[BUG] Problems typing tablenames

### ISSUE THREAD

**Issue by m-schwarzinger** [cweijan/vscode-mysql#439]
If I start typing a tablename I get the Error: 
```
TypeError: Cannot read property 'getChildren' of null
```
It leads to the loss of focus after every letter.

- OS: Xero Linux 5.10.88-2-lts
- Database Type: MySQL, SQLite

**Comment by cweijan** [comment]
Hi, two does you using newest extension version? And try using query file.
![image](https://user-images.githubusercontent.com/27798227/149727628-9eaa4de2-39aa-4ea0-baca-3331114ff758.png)

**Comment by m-schwarzinger** [comment]
I use v4.5.1
Yeah if I use Open Query I have to write my queries and exactly thats where I have my Problem

**Comment by cweijan** [comment]
I guess this only happens with sqlite, I have fixed it in version 3.5.2。

**Comment by m-schwarzinger** [comment]
Sadly not as I I said I already tried with MySQL and Postgres

**Comment by cweijan** [comment]
But I'm fine now, have you always been like this or just recently？

**Comment by m-schwarzinger** [comment]
I found this extension one and a half years ago so it was always like that

**Comment by m-schwarzinger** [comment]
Ah Update is out and it fixed it! thx
