### ISSUE TITLE
[BUG] Error: unknown command or invalid arguments:  "open". Enter ".help" for help

### ISSUE THREAD

**Issue by bonilalcp** [cweijan/vscode-mysql#440]
- OS: Centos  7.9.2009
- Database Type: SQLite 3

Getting `Error: unknown command or invalid arguments:  "open". Enter ".help" for help` on attempting to connect to database on Remote Server (Connected via VS Code remote development plugin)
Local OS : Windows 10
(SQLite connection works fine for local workspace on local file)

```
2022-01-17 07:15:29 Execute sql fail : SELECT name, type FROM sqlite_master WHERE type="view" AND name <> 'sqlite_sequence' AND name <> 'sqlite_stat1' ORDER BY type ASC, name ASC;
2022-01-17 07:15:29 Error: Error: unknown command or invalid arguments:  "open". Enter ".help" for help
```

What I found
https://code2care.org/pages/error-unknown-command-or-invalid-arguments-open-enter-help

**Comment by cweijan** [comment]
It seems that the open command is deprecated, I will switch the connection method in the next version.

**Comment by cweijan** [comment]
oh, only databases opened by open command can support Unicode, so I can't modify it, you need to modify your sqlite version.
