### ISSUE TITLE
Make convenient to use with existing .sql files

### ISSUE THREAD

**Issue by steffan-c** [cweijan/vscode-mysql#441]
It would be amazing if it was convenient to open an existing .sql file (stored on disk) and use it with this extension.

You can sort of do this by already by:

1. Open a new query file from the icon next to the relevant database - this sets the active connection.
2. Open an existing SQL file and use it with the current active connection.

However, I can find no way to set the active connection without opening a tab - which makes initially setting or changing the active connection somewhat painful.

Even better would be if an active connection was associated with a tab (so you could have different tabs to query different DBs at the same time). And/or associate a saved .sql file with a connection (so the connection is automatically activated when the file is opened). Or annotations in the .sql file to say which connection to use (like in SQLTools).

**Comment by cweijan** [comment]
Right click then choose change active connection.
![image](https://user-images.githubusercontent.com/27798227/149766684-e3c3a663-1d97-40c9-889e-0651256539b6.png)

**Comment by steffan-c** [comment]
Thanks. Clicking on that either has absolutely no effect or results in an error pop up saying "query file can not change active database" (I think no effect when clicking on a .sql file I have opened from disk, and the error pop up when clicking on a file that has been created by clicking on the "open query" icon next to the database name).

**Comment by cweijan** [comment]
The query file is bound to your connection, cannot be modified.

**Comment by cweijan** [comment]
If you only use query sql, the extension will automatically select the connection based on the query file.
