### ISSUE TITLE
Cannot read property 'getPrivatePEM' of undefined

### ISSUE THREAD

**Issue by EnterVPL** [cweijan/vscode-mysql#442]
Hi,
I have a problem with connect to DB with using ssh. I don't know where is problem, but this is my config:

![db config](https://i.ibb.co/Xy6VR5B/dberror.png)

The same params is working in the PhpStorm

- OS: Ubuntu 20.04 LTS
- Database Type: MySQL with SSH tunnel

**Comment by cweijan** [comment]
Hi, try to connect to the ssh tunnel with a password. If it can connect, it means that the extension cannot support your key format.

**Comment by EnterVPL** [comment]
I'm surprised - it works! 😀
Thanks for help

**Comment by cweijan** [comment]
Thanks for the test, if you need to use the key, you need to convert it to a more general format.
![image](https://user-images.githubusercontent.com/27798227/150308797-541b6d99-f0f9-4300-8cfe-37027460b99d.png)
