### ISSUE TITLE
[BUG] instance name for sql server does not work in combination with SSH tunneling

### ISSUE THREAD

**Issue by marknelissen** [cweijan/vscode-mysql#443]
I'm trying to connect to a SQL Server instance, by making use of the Instance Name based configuration. I need to combine this with SSH tunneling, since it is not exposed publicly. But I get an error. Strangely, the error message mentions 127.0.0.1 as the address of the database, instead of the actual ip address of the configuration.

- OS: macOS
- Database Type: SQL Server

**Comment by cweijan** [comment]
The instance name obtains the actual port through the browser service, so it cannot be connected through the ssh tunnel.
If you want to connect via ssh tunnel, you should specify the port.

**Comment by marknelissen** [comment]
Do you have a workaround how I can obtain the port to use in the configuration?

**Comment by cweijan** [comment]
Default port is 1433, try it.

**Comment by cweijan** [comment]
See more ways here https://stackoverflow.com/questions/12297475/how-to-find-sql-server-running-port。
