### ISSUE TITLE
code completion not work correctly !

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#446]
Hello .

in postgres driver code completion not work correctly !
and column list only show when  use alias .

![Animation (1)](https://user-images.githubusercontent.com/6413705/150513307-a813721e-8220-42b8-bde9-5543043255a1.gif)

**Comment by cweijan** [comment]
Thanks, did have this problem, will fix it in the future.

**Comment by mbtolou** [comment]
not fixed in 4.5.12 !

**Comment by cweijan** [comment]
@mbtolou  Version 4.5.12 I didn't fix this, fixed it in 4.6.0.

**Comment by mbtolou** [comment]
thanks 

auto completion fixed , but from table not work correctly!

select <= fixed
from  <= not fixed

**Comment by cweijan** [comment]
What's the problem with `from`?

**Comment by mbtolou** [comment]
![Animation](https://user-images.githubusercontent.com/6413705/154437014-3743bd7e-59ba-4797-b234-1f59cd2bdd06.gif)

**Comment by cweijan** [comment]
This seems to be the completion of the scheme, but I have canceled the completion of the scheme.

**Comment by cweijan** [comment]
Sorry I was wrong, I didn't cancel it, there should be a bug here.
