### ISSUE TITLE
replace * with column names like dbeaver

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#448]
hello.

One of the best features of dbeaver is replacing the asterisk with a list of columns by ctrl+space.

Can you add this feature to your product?

![Animation (2)](https://user-images.githubusercontent.com/6413705/150635579-0c50773c-5ce2-4c85-814f-b67adb15da70.gif)

**Comment by cweijan** [comment]
Since version 4.5.7, clicking the query button will automatically generate select sql for all columns, the operation you gave is not friendly.
![image](https://user-images.githubusercontent.com/27798227/152689357-8a46851a-0804-46f3-b8de-b327cff0941e.png)
