### ISSUE TITLE
[BUG] Can't delete selected items from mongodb database

### ISSUE THREAD

**Issue by imoxto** [cweijan/vscode-mysql#449]
# Can't delete selected items from mongodb database because of wrong query
- OS: Windows 10 pro
- Database Type: Mongodb

![image](https://user-images.githubusercontent.com/86479201/150636596-0d348aea-3112-4bf5-8880-11e49ce40bf7.png)
the query should be: 
`db('animeList').collection("users").deleteMany({_id:{$in:[ObjectID(' insert 1st id '),ObjectID(' insert 2nd id ')]}})`
instead of 
`db('animeList').collection("users").deleteMany({_id:{$in:['ObjectID(' insert 1st id ')','ObjectID(' insert 2nd id ')']}})`

**Comment by angeltonio** [comment]
I have the same error

**Comment by cweijan** [comment]
Fix at version 4.5.7.
