### ISSUE TITLE
[BUG] No active es server found!

### ISSUE THREAD

**Issue by tigerinus** [cweijan/vscode-mysql#450]
- OS: Debian Bullseye
- Database Type: ElasticSearch

成功创建 ElasticSearch connection 后，点击 Open Query，创建并尝试 Run Query，结果并不能执行任何请求。

弹出错误说：No active es server found!

![image](https://user-images.githubusercontent.com/7172560/150650453-f3af8500-81cd-40de-ac81-dca9d714d42e.png)

**Comment by cweijan** [comment]
这里确实有bug， 下版本修复， 你可以先点击index节点旁边的open query.

**Comment by cweijan** [comment]
最新版本修复了

**Comment by lz37** [comment]
# v5.2.4 还是有这个问题

vscode版本：
版本: 1.67.0
提交: 57fd6d0195bb9b9d1b49f6da5db789060795de47
日期: 2022-05-04T12:08:42.978Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.13.0-40-generic

使用的ESdocker版本，列表中能显示，但是无法查询

**Comment by cweijan** [comment]
@lz37 Hi, 我试了几次, 都是正常的呢, 你的nosql面板有没有激活呢, 建议新开个issue详细描述下.

**Comment by lz37** [comment]
> @lz37 Hi, 我试了几次, 都是正常的呢, 你的nosql面板有没有激活呢, 建议新开个issue详细描述下.

不好意思，多番测试下来才发现是我没有正确使用，浪费你的时间了
