### ISSUE TITLE
Open the current project path instead of opening the temporary path

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#451]
Hi.

can you open the current project path instead of opening the temporary path ?

**Comment by cweijan** [comment]
What temporary path?

**Comment by mbtolou** [comment]
path like this :

C:\Users\tolou-m\AppData\Roaming\Code\User\globalStorage\cweijan.vscode-mysql-client2\1641368657366@@10.0.0.138@8123@default@ahe#meter_history

**Comment by cweijan** [comment]
Sorry there is no such plan, you can use vscode "save as" to save it.

**Comment by mbtolou** [comment]
when I use vscode "save as" , this path show in dialog .
can you change this to project path ,
like this

workspace_folder/.

instead of path like this : 

C:\Users\tolou-m\AppData\Roaming\Code\User\globalStorage\cweijan.vscode-mysql-client2\1641368657366@@10.0.0.138@8123@default@ahe#meter_history

**Comment by cweijan** [comment]
This path is controlled by vscode, not an extension. You can also create a sql file directly in your project path, and then modify the active connection.
![image](https://user-images.githubusercontent.com/27798227/150706061-78f93252-97e4-412b-af35-467546bfc77c.png)
