### ISSUE TITLE
导出mysql 的sql文件有问题，关键字没有进行转义

### ISSUE THREAD

**Issue by HKMV** [cweijan/vscode-mysql#452]
- OS: Win11
- Database Type: mysql 5.28

导出mysql 的sql文件有问题，关键字没有进行转义
![image](https://user-images.githubusercontent.com/26456469/150716230-512e983f-2d2e-4725-a238-776f74f339ec.png)

这样咋在导入的时候就会报错

**Comment by cweijan** [comment]
你的电脑有装mysql的话把mysql_dump加到环境变量，就会使用mysql_dump进行备份了，自带的备份功能不够稳定，不再维护了。

**Comment by HKMV** [comment]
> 你的电脑有装mysql的话把mysql_dump加到环境变量，就会使用mysql_dump进行备份了，自带的备份功能不够稳定，不再维护了。

好吧谢谢,我没有
