### ISSUE TITLE
Support for username in redis connections

### ISSUE THREAD

**Issue by arihantdaga** [cweijan/vscode-mysql#454]
I teied to connect with my redis 6 instance which requires username and password. But i couldnt find option to input username for redis connection in this. So, i am unable to connect with my redis db. 
It throws error about Auth.

**Comment by cweijan** [comment]
Don't give this extension a low score because of this, when support for redis was implemented before, the ioredis used by this extension does not support acl.

**Comment by arihantdaga** [comment]
I am sorry @cweijan . I absolutely love this extension. I have updated my review also. I did it by mistake.

**Comment by cweijan** [comment]
Thanks, I will support redis acl in future versions.

**Comment by cweijan** [comment]
Support at version 4.5.7.
