### ISSUE TITLE
[BUG] Quotes missing when using GUI

### ISSUE THREAD

**Issue by DaveyJH** [cweijan/vscode-mysql#455]
Hi. Very new to postgreSQL so very possible I am missing something in the set up here! Apologies if that is the case.

Database layout:

![image](https://user-images.githubusercontent.com/80708826/151430027-551e39a7-9a75-40db-8396-43d24cd5cd36.png)

Original table:

![image](https://user-images.githubusercontent.com/80708826/151430056-97ae3f27-a906-403b-be56-5a01952f47f3.png)

Error:

- Note the missing quotes around "TrackId"
![image](https://user-images.githubusercontent.com/80708826/151430354-c89cf504-7534-47ee-9340-ef011f27e4d9.png)

Adding quotes in manually and using 'Execute Sql':

![image](https://user-images.githubusercontent.com/80708826/151430435-fb2a03fe-8106-45ba-b352-03b769cab384.png)

- OS: 
![image](https://user-images.githubusercontent.com/80708826/151429878-122dae81-0a56-47ba-9050-11fcfb9fcadb.png)

- Database Type: postgreSQL (local)

Many thanks

**Comment by cweijan** [comment]
This is a postgresql problem, not related to this extension.

**Comment by DaveyJH** [comment]
Is the GUI not part of the extension? Running the command manually works OK.

The error is displayed if I click the sorting arrow in the GUI, it was not a manual command. It appears to be generated by the extension. It also happens if I right click and edit.

https://user-images.githubusercontent.com/80708826/151550779-6b8fd73a-4ba8-4dae-bba7-c571c5c7a8c5.mp4


https://user-images.githubusercontent.com/80708826/151550784-fba8bf6c-b02a-4ec5-a0b4-23e3e6853c11.mp4

**Comment by cweijan** [comment]
Sorry I misunderstood you, fix at version 4.5.8.

**Comment by DaveyJH** [comment]
I wrote the bug out with more detail first then lost the draft! 
Happy that I could clarify, look forward to the new version. Brilliant extension

**Comment by cweijan** [comment]
The new version has been released.

**Comment by DaveyJH** [comment]
Works great. Really useful update, thanks!
