### ISSUE TITLE
Getting Terminal outputs when writing queries

### ISSUE THREAD

**Issue by pmcl77** [cweijan/vscode-mysql#457]
- OS: MacOS Big Sur
- Database Type: MariaDB

When I start writing queries, I constantly get terminal error, that take focus away from the editor, I cannot write queries like that. What is going wrong?

<img width="768" alt="Screenshot 2022-02-05 at 16 03 27" src="https://user-images.githubusercontent.com/57845954/152647342-0636b36f-e20a-4a43-ae63-74d16b9e3399.png">

**Comment by cweijan** [comment]
Try Version 4.5.7, I hide this error message, the problem will be solved in a future version.

**Comment by Elurr** [comment]
Hello! I'm using the 4.5.8 version and I'm getting a similar error message. Should I downgrade?

Edit: I downgraded from 4.5.8, the message still appears. I managed to identify the exact moment when it does, it seems to be everytime I write FROM.

**Comment by pmcl77** [comment]
I seem to have the same problems with 4.5.7. I just installed 4.5.10, hope it will be better

**Comment by cweijan** [comment]
@pmcl77  Yes, I fixed it in 4.5.10, is it ok now? Autocomplete will continue to improve the experience.

**Comment by pmcl77** [comment]
I will test it this weekend and give feedback!

**Comment by pmcl77** [comment]
Ok, it seems better, I can now normally type SQL without the focus being stolen... but sometimes I still get the OUTPUT Window to open with "2022-02-12 16:09:52 Error: connect ETIMEDOUT". Can this also be suppressed? The connection seems to work fine when I run queries.

**Comment by cweijan** [comment]
"connect ETIMEDOUT" Does this problem still exist now? This is caused by your unstable database connection.

**Comment by Enubia** [comment]
apparently this problem still exists when I'm executing Postgres queries
my query here is just a simple
```sql
select * from "customer_smss" order by id desc limit 10;
```

I get the results but for whatever reason it throws MySQL errors

![image](https://user-images.githubusercontent.com/44695100/154263022-8380bc60-1a51-4a8e-98f2-cf3cb194f1c9.png)
![image](https://user-images.githubusercontent.com/44695100/154263693-a209795d-c37f-401e-9b10-bbb4bac6fa2b.png)

**Comment by cweijan** [comment]
@Enubia  This is not the same problem, you are this because your sql is incorrect.

**Comment by Enubia** [comment]
> @Enubia This is not the same problem, you are this because your sql is incorrect.

this is my query
![image](https://user-images.githubusercontent.com/44695100/154264178-3a01e319-2ce3-465f-8897-aeca1f176481.png)

**Comment by cweijan** [comment]
@Enubia The error message has clearly described your error, you cannot use order after executing the aggregate function, you can find more detailed reasons from Google.

**Comment by Enubia** [comment]
i'm not executing an aggregate function here as you can see in my last answer

please read the query

**Comment by Enubia** [comment]
![image](https://user-images.githubusercontent.com/44695100/154264842-5ce55466-4140-42be-a503-9c52237bac06.png)

**Comment by Enubia** [comment]
the query works just fine, i get results, the error thrown here is wrong as you can see

**Comment by cweijan** [comment]
@Enubia Sorry, this is caused by the count statement automatically generated by this extension, I'll fix it in the next version.

**Comment by Enubia** [comment]
alright thanks

**Comment by pmcl77** [comment]
> 2022-02-12 16:09:52 Error: connect ETIMEDOUT

The problem still persists in 4.6.0. Is it possible to suppress this?

**Comment by cweijan** [comment]
I've enhanced completion in version 5.0.4, and now errors don't take the editor out of focus.
