### ISSUE TITLE
建议Mysql中双击表格快速浏览limit100时，加入mysql的转义符“`”

### ISSUE THREAD

**Issue by tianrongze** [cweijan/vscode-mysql#458]
建议Mysql中双击表格快速浏览limit100时，为字段名、表格名，自动加入mysql的转义符【\`】
因为关注到最新4.5.8后，Select * 被 “Select+所有字段" 取代了
如：SELECT from FROM 123 LIMIT 100; 字段名称是”from“，表格名称是”123“
变成：SELECT \`from\` FROM \`123\` LIMIT 100;
（现实当然不会出现这么逆天的字段名和表格名，我只是举个例子。如果使用了转义符，可以提升一点使用体验，至少可以在检查逆天表格时，不至于每次都要手动输入【\`】）

一点小建议，希望大佬能够采纳，非常感谢！

**Comment by cweijan** [comment]
不加转义符主要是会让sql看起来很丑, 之前我有创建规则当匹配到某些关键字就自动加上转义符, 不过这里确实忘了, 后续加上.

**Comment by cweijan** [comment]
4.5.12改回*了
