### ISSUE TITLE
Request for auto complete

### ISSUE THREAD

**Issue by Iftakharpy** [cweijan/vscode-mysql#459]
I think it will be great if the feature auto-complete table names and column names when writing an SQL query is added to this extension. 

I don't know how to start implementing this feature, if someone provides a guide or some idea I think I can start to implement the feature.

**Comment by cweijan** [comment]
Auto complete has already been implemented, there is a bug at present, try the latest version 4.5.9, which fixes this problem

**Comment by Iftakharpy** [comment]
I am currently using version 4.5.10, it is working for table name auto-complete but not for the column/attribute names.

**Comment by cweijan** [comment]
The completion of columns can be prompted by where or aliases, and I will continue to enhance the completion in subsequent versions.

**Comment by Iftakharpy** [comment]
But what about completion for column names after select keyword?

**Comment by cweijan** [comment]
Now only through aliases, later versions will support.

**Comment by Iftakharpy** [comment]
Ok. But there are some issues I want to mention here about the auto-complete.

1. The suggested attributes are not grouped together. *I think all the attributes should show at the beginning of the suggestion box.*
2. If I remove the **WHERE** clause and type **ORDER BY** or **GROUP BY** the suggestions for the attributes doesn't appear. *I think the attribute should appear for the table I mentioned after the **FROM** keyword.*

**Comment by cweijan** [comment]
1. Version 4.6.0 now provides completion for columns at any time.
2. I also think the column should be shown first, but this one seems like I can't control it.

**Comment by cweijan** [comment]
I found that the priority can be adjusted, will be implemented in the next version.

**Comment by Iftakharpy** [comment]
I think the table names of the active database should also be grouped together and brought at the beginning of the suggestion box.

**Comment by Iftakharpy** [comment]
When a query is formed using **JOIN**, the columns from the joined tables should also appear in the auto complete.

**Comment by cweijan** [comment]
The latest version already supports showing the columns of the join table, and I implemented the completion priority, but restricting it to only premium users.

**Comment by Iftakharpy** [comment]
Why can't it be open for everyone?

**Comment by cweijan** [comment]
Previously this extension was a free program, so I was very concerned about the reviews on the extension store, but I get bad reviews from time to time, which makes me sad, so it won't be available for free.
