### ISSUE TITLE
增加table名字和列名的自动提示，就很完美了。

### ISSUE THREAD

**Issue by jianweidai** [cweijan/vscode-mysql#460]
在编写SQL的时候如果能有table 名和列名的自动提示的话 就很完美了，我就可以替换我的主流的数据库软件了。

**Comment by cweijan** [comment]
你通过使用query文件和点击节点激活数据库连接后就有提示了, 你倒是先把文档看一遍.

**Comment by cweijan** [comment]
额, 这其实是一个bug, 我发布了最新的4.5.9版本修复这个问题.

**Comment by jianweidai** [comment]
我说我之前使用一直没有提示table名和列名的提示。最近更新到了4.5.10版本就没有问题了。

**Comment by cweijan** [comment]
好的, 谢谢支持.
