### ISSUE TITLE
[BUG] Generate Mock Data失败

### ISSUE THREAD

**Issue by Jinlixian** [cweijan/vscode-mysql#461]
执行 Generate Mock Data 提示 ： Table xxxx not found!

插件版本：V4.5.8
vscode版本：1.46.1
系统：MacOS 12.1

mock.json
{
    "table": "supply",
    "mockStartIndex": "auto",
    "mockCount": 10,
    "mockValueReference": "http://mockjs.com/examples.html#DPD",
    "mock": {
        "id": {
            "type": "int",
            "value": "$mockIndex"
        },
        "name": {
            "type": "varchar",
            "value": "@string('lower',5)"
        },
        "context": {
            "type": "longtext",
            "value": "@integer(1,1024)"
        },
        "images": {
            "type": "longtext",
            "value": "@integer(1,1024)"
        },
        "area": {
            "type": "longtext",
            "value": "@integer(1,1024)"
        },
        "Supplier_id": {
            "type": "bigint",
            "value": "@integer(1,1024)"
        },
        "created_user_id": {
            "type": "bigint",
            "value": "@integer(1,1024)"
        },
        "created_unix": {
            "type": "bigint",
            "value": "@integer(1,1024)"
        },
        "updated_unix": {
            "type": "bigint",
            "value": "@integer(1,1024)"
        }
    }
}

**Comment by cweijan** [comment]
在执行前需要修改活跃连接为要执行的数据库连接.

**Comment by cweijan** [comment]
这个问题已经是旧版本的一个识别bug ,现已修复.
