### ISSUE TITLE
Unable to drop database[BUG]

### ISSUE THREAD

**Issue by ghost** [cweijan/vscode-mysql#462]
- OS: Windows 10
- Database Type: MSSQL

Whenever I try to drop a database by doing a right-click on the db name, I get the following error:
**Cannot drop database "rithm_station_db" because it is currently in use.**

In other SQL tools this is handled with a confirmation window but here it simply throws this error and doesn't do anything.

**Comment by angeltonio** [comment]
Similar with Mongodb

**Comment by cweijan** [comment]
This is a limitation of postgres, and I can't change it. Since this software supports multiple databases, when you drop a database, the drop statement is executed by the current database connection, so it must not succeed.
I will add the notice in the next version.
