### ISSUE TITLE
[BUG] Unable to view table containing keywords as column names

### ISSUE THREAD

**Issue by emyasnikov** [cweijan/vscode-mysql#466]
I have couple of table where I use "key" keyword as column name. Query ends with "execution fail" error.

I think there are at least two ways how to solve the issue:
* Just getting all columns using wildcards ```SELECT * FROM <table> LIMIT <limit>;``` is good enough to quickly list entries
* Adding backquotes like ```SELECT `<column>` LIMIT <limit>;``` would work the same as now, but without errors

- OS: MacOS 12.1
- Database Type: MySQL

**Comment by cweijan** [comment]
I changed back to * in the latest version 4.5.12.

**Comment by emyasnikov** [comment]
Thank you :)
