### ISSUE TITLE
不规范的字段名称，导致插件出现致命错误[BUG]

### ISSUE THREAD

**Issue by free365** [cweijan/vscode-mysql#467]
这个查询字串是由排序自动生成
![image](https://user-images.githubusercontent.com/6037716/153706724-aea221d4-23a6-41c5-821f-2ff66c043946.png)

数据库、表、索引、列、别名等，应该强行添加转义字符  `

影响版本：4.5.12 （之前就有这问题）

正确情况下应该产生这样的查询语句
![image](https://user-images.githubusercontent.com/6037716/153707244-1482aa30-37fb-4fed-9061-75c4cf108d71.png)

**Comment by cweijan** [comment]
直接加转义字符太丑, 我目前是当匹配到为关键字就会加, 比如key、index这样的, system不是关键字, 我不知道你这个为啥会报错.

**Comment by cweijan** [comment]
查了下system是mysql8后加的字段, 下个版本将自动添加转义字符.

**Comment by cweijan** [comment]
版本4.6.0支持对system关键字自动加上转义符了.

**Comment by free365** [comment]
> 直接加转义字符太丑, 我目前是当匹配到为关键字就会加, 比如key、index这样的, system不是关键字, 我不知道你这个为啥会报错.

    我感觉规范才是最美的，程序健壮性才是第一位的。你这样匹配关键字的办法非常浪费精力和时间，通用性也不好，万一以后mysql又加入新的关键字，或者别的数据库加入了新关键字，你天天还要更盯着它们的更新来更新不是吗？
    所以我建议你用最简单的办法，一劳永逸的解决问题。或者退一步，增加一个选项来开启或关闭是否全部转意的选项（默认不开启）。

**Comment by cweijan** [comment]
@free365 这个软件对SQL高亮是很显眼的, 所以不加`更加符合人类阅读习惯, datagrip也是采用这种关键字匹配的形式加反引号的. 另外我认为一个优秀的程序员应该避免使用关键字作为列名, 所以对于MySQL我不计划实现对所有列名自动加上反引号.

**Comment by free365** [comment]
> 
首先你赢了。

其次我感觉，作为一个工具软件应该考虑大多数情况。另外作为优秀的程序员、也有对于历史代码或三方代码无可奈何的情况，关键字做为列名的并不少见。还有通过excel等其它途径转换得来的数据表、列名也不会考虑关键字的问题。
(以上为个人观点无需回复)

**Comment by cweijan** [comment]
issue关闭我一般就不会回复了, 但你这括号内的说明很膈应人.
