### ISSUE TITLE
[BUG] Lock Panel - Wrong Tooltip Text and Lock Symbol disappears

### ISSUE THREAD

**Issue by pmcl77** [cweijan/vscode-mysql#471]
Hi,

When hovering the "Lock Symbol" the tooltip shows "unlock this panel" instead of "lock this panel". 

Also, when I click the lock symbol to lock the panel, the lock symbol disappears (which is not a big problem as I can also just close the panel, but it might be good to actually see the "locked" lock-symbol when a panel is locked).

<img width="569" alt="Screenshot 2022-02-14 at 10 11 17" src="https://user-images.githubusercontent.com/57845954/153835135-1eab83fc-3c99-4844-9e33-34d058b07b3f.png">

<img width="494" alt="Screenshot 2022-02-14 at 10 13 44" src="https://user-images.githubusercontent.com/57845954/153835175-8440067f-7636-4e48-8f6a-76eb6279ed6a.png">

Thanks and keep up the good work!

- OS: MacOS Big Sur
- Database Type: MySQL / MariaDB

**Comment by cweijan** [comment]
This is a great suggestion.

**Comment by cweijan** [comment]
Support at version 4.6.0, now you can unlock any panel.

**Comment by pmcl77** [comment]
Cool, I can see the lock symbol does not disappear and unlocking is possible. 

But I think the tooltip and maybe the lock symbols are still the wrong way:

When I initially run a query, the panel is in "unlocked" state, but it shows like this:

symbol: locked
tooltip: "unlock this panel"

<img width="453" alt="Screenshot 2022-02-17 at 12 52 09" src="https://user-images.githubusercontent.com/57845954/154476662-c5fe47da-5c03-4567-83da-f3d7debc8ed8.png">

After I lock the panel, it shows like this:

symbol: unlocked
tooltip: "lock this panel"

<img width="441" alt="Screenshot 2022-02-17 at 12 53 51" src="https://user-images.githubusercontent.com/57845954/154476972-d0cb37bf-40f5-45e2-9aef-6a57fb1fd236.png">

So the tooltip is misleading, and depending on the personal view also the symbol is misleading.

In the initial **unlocked** state, the tooltip should either say "lock this panel" (action) or "this panel is unlocked" (state).

After locking the panel (**locked** state), the tooltip should either say "unlock this panel" (action) or "this panel is locked" (state).

Regarding the symbol it depends if you prefer to put focus on the **action** (what clicking the button does) or on the **state** (what the current state of the panel is).

My personal preference is: the tooltip should focus on the action, while the icon I prefer to show the current state of the panel. But others might see this differently, what do you think?

in initial/unlocked state:
symbol: unlocked
tooltip: "lock this panel"

in locked state:
symbol: locked
tooltip "unlock this panel"

**Comment by pmcl77** [comment]
just to clarify, the other option would be:

in initial/unlocked state:
symbol: locked
tooltip: "lock this panel"

in locked state:
symbol: unlocked
tooltip "unlock this panel"

**Comment by cweijan** [comment]
The default state is locked, because any query you run will be synchronized to this panel. 

Also, your original issue was saying that locking the icon is the same as locking the prompt, I thought that was really ambiguous, so I changed it, you're saying the opposite now.

**Comment by pmcl77** [comment]
Maybe there is a missunderstanding what a "locked" panel means, so sorry if I got this wrong.

I thought, locked means, the panel will not be "reused" or overwritten by any other query that will be run after. 

Basically, that's how I know it from other DB tools, though there it usually is called "pinning". Meaning a pinned tab/panel will stay and persist the data and any new query that is run will be opened in a new tab/panel. Basically a tab will always start unpinned and it's data will be replaced by consecutive queries until I decide I need to keep the data (e.g. for comparison) so then I would go an pin it. :)

**Comment by cweijan** [comment]
Yes, it looks like we have a different definition of lock, but now this feature works fine.

**Comment by cweijan** [comment]
I remember you used this extension for a while. I plan to commercialize it in the next version, restrict some features to be available only to advanced users, and add cloud sync, it will cost around $15, how do you think?

**Comment by pmcl77** [comment]
Hey @cweijan sorry for the late reply, didn't have much time to work on my software... I personally think it would be worth it, however you might think about offering for below 10$, just because of the psychological effect, like 9.90$ feels a lot cheaper than 10$ ;) But it's up to you... maybe you could conduct a poll among users?

Will also check the locked panel feature again.
