### ISSUE TITLE
Remove Error Message after Re-Running a Query Successfully

### ISSUE THREAD

**Issue by pmcl77** [cweijan/vscode-mysql#473]
When trying to run a query with an error, the error message shows above the (empty) query result, which is ok. If i then change the query or run another query without any errors, the window with the error message stays visible. It would be great to have the option to remove the previous error message, when a query is run without any errors.

**Comment by cweijan** [comment]
Fix at version 4.6.0.

**Comment by pmcl77** [comment]
perfect! :)
