### ISSUE TITLE
I can't connect to sqlserver

### ISSUE THREAD

**Issue by GabrielDSantos** [cweijan/vscode-mysql#474]
I don't have much experience on sqlserver so probably is my fault, i can't connect using this extension, but works just fine with mssql.
What i'm doing wrong, can someone help me fix that ?
![Screenshot_2](https://user-images.githubusercontent.com/99694457/153961673-4b3d4edd-5775-4579-a4c2-dd171bfb3aee.png)

**Comment by cweijan** [comment]
I think it's you using the wrong instance name, it is recommended to just use the port.
