### ISSUE TITLE
Option to save (or not save) password for each connection

### ISSUE THREAD

**Issue by pmcl77** [cweijan/vscode-mysql#475]
The reason for this is, that for a productive database, I want to use a read-only user with a saved password, but if I need to make changes to the db (dml/ddl) I would like another connection that does not save password but prompts for the password when connecting.

**Comment by cweijan** [comment]
This is a great proposal, I will implement it in a future version.

**Comment by cweijan** [comment]
Readonly connection is a better choice, it has been initially supported and will continue to be strengthened in the future.
![image](https://user-images.githubusercontent.com/27798227/159277632-e5553b69-b5db-4443-b8d2-7be2b26536f7.png)

**Comment by myatmin** [comment]
Read only and saving password of each connection are different things. 
It could be better if it provides an option to save or not to save the password of each connection.

**Comment by cweijan** [comment]
He created the issue to prevent data mishandling, and read-only mode is a better way to handle it.
Not saving passwords is usually a user's concern about password leaks, but I don't want to support this scenario.

**Comment by myatmin** [comment]
Created #536 with only focus on password saving option.
