### ISSUE TITLE
[BUG] select count(*) from <table> where <condition> delivers wrong result

### ISSUE THREAD

**Issue by wot0x4a** [cweijan/vscode-mysql#476]
- OS: Windows 10
- Database Type: MSSQL Server

when quering on an MSSQL database the number of rows in a results set, the response is always 1 which is incorrect:

Example using VSCODE with the Database Client:
![image](https://user-images.githubusercontent.com/95966732/154029252-4774c386-5a2c-430a-b67b-41f0b945739b.png)

Example from a different DB client:
![image](https://user-images.githubusercontent.com/95966732/154029357-8f2e6877-cbbe-4a20-99ed-2e6974dcb347.png)

I did not test it with other DBs as I currently have only MSSQL Server DBs to test with.

**Comment by cweijan** [comment]
Thanks for the feedback, fixed in version 4.8.6.
