### ISSUE TITLE
Error to delete mongodb database

### ISSUE THREAD

**Issue by angeltonio** [cweijan/vscode-mysql#478]
Execute sql fail : DROP DATABASE "name of my database"
SyntaxError: Unexpected identifier

I don't know why this happens, I put the name of the database or I just press enter and it's the same result

**Comment by cweijan** [comment]
Because I have not implemented mongo to delete the database before, it will be added in the next version.

**Comment by angeltonio** [comment]
> Because I have not implemented mongo to delete the database before, it will be added in the next version.

Hello tanks to reply, so when is the next version?

**Comment by cweijan** [comment]
I have released version 4.6.0, try it!

**Comment by angeltonio** [comment]
It's work!!!..thanks a lot!!!...amazing plugins..

**Comment by cweijan** [comment]
Thanks for support.
