### ISSUE TITLE
UPDATE row from a results cell causes  Invalid JSON text: "Invalid value."

### ISSUE THREAD

**Issue by vanderhoff** [cweijan/vscode-mysql#479]
RDS mysql 5.7.2

I have created a table using 
`CREATE TABLE castfriends.friends (
  `uid` int NOT NULL AUTO_INCREMENT COMMENT 'id',
  `crew` json DEFAULT NULL COMMENT 'supporting fields for parent',
  `nme` varchar(32) GENERATED ALWAYS AS (json_unquote(json_extract(`crew`,_utf8mb4'$.screen'))) VIRTUAL,
  `gu` varchar(32) GENERATED ALWAYS AS (json_unquote(json_extract(`crew`,_utf8mb4'$.guid'))) VIRTUAL,
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB AUTO_INCREMENT=49 DEFAULT CHARSET=utf8mb3;`

`insert into castfriends.friends (crew)  values  ( '{  "guid" : "d8930c49405242d5923362b8818b93ad", "screen": "Rachel" }')`

I get a results returned 
![image](https://user-images.githubusercontent.com/13752810/154236769-8da45220-9491-41fa-a656-1d61128764cc.png)
now updating the field in place 
{"guid": "d8930c49405242d5923362b8818b93ad", "screen": "BOB"}

returns error
```
EXECUTE FAIL:

  UPDATE friends SET crew='{"guid": "d8930c49405242d5923362b8818b93ad", "screen": "BOB"}' WHERE uid=44;

Message :

  Invalid JSON text: "Invalid value." at position 8 in value for column 'friends.crew'.
```
doing a straight copy paste into the sql query line
```
UPDATE friends SET crew='{"guid": "d8930c49405242d5923362b8818b93ad", "screen": "BOB"}' WHERE uid=44;
```
```
EXECUTE SUCCESS:

  UPDATE friends SET crew='{"guid": "d8930c49405242d5923362b8818b93ad", "screen": "BOB"}' WHERE uid=44;

AffectedRows : 1
```

**Comment by cweijan** [comment]
This problem has been fixed in the latest version.
