### ISSUE TITLE
可以问一下这里为什么要弄两个图标吗？可以合并为一个图标吗？

### ISSUE THREAD

**Issue by darrenliuwei** [cweijan/vscode-mysql#484]
![image](https://user-images.githubusercontent.com/10508248/154428432-71438bfa-f043-4352-9eb1-6fd503983647.png)

**Comment by cweijan** [comment]
可以长按其中一个面板直接拖到另一个里面, 之所以分开是因为有大多情况下需要同时查看数据库和nosql的数据, 不分开操作很麻烦.

**Comment by darrenliuwei** [comment]
> 可以长按其中一个面板直接拖到另一个里面, 之所以分开是因为有大多情况下需要同时查看数据库和nosql的数据, 不分开操作很麻烦.

还可以这样操作呀，已合并，感谢。

可能是我没有nosql的数据，所以体会不到这样的烦恼
