### ISSUE TITLE
add variable support .

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#487]
Hi.

Is it possible to add a variable to the query?
like this :

```sql
:device_id=123366445455;


select *
from device_list 
where  device_id=:device_id
```

**Comment by cweijan** [comment]
I don't have this plan, it's not an sql standard, usually a dialect of SQL implemented by programming frameworks.

**Comment by cweijan** [comment]
Have you registered [https://database-client.com](database-client)? To thank you for your contribution to this project, I will give you a year of premium.

**Comment by mbtolou** [comment]
thanks

**Comment by cweijan** [comment]
Please re-login to your account in vscode.

**Comment by cweijan** [comment]
Hi, I have implemented it in version 5.2.2 as many people have proposed this feature.
![image](https://user-images.githubusercontent.com/27798227/165432873-66afee03-ba3c-427b-a5c4-9cc6e53a0711.png)

**Comment by mbtolou** [comment]
Hello my friend

I am the one who added the ClickHose driver to your software.
Can I request you to renew my license for 5 years?

**Comment by cweijan** [comment]
Hi, I reviewed your contribution, I can only give you another 3 years license, if you accept this, please let me know your email.

**Comment by mbtolou** [comment]
Thank you.
my email is : 

mb.tolou@gmail.com

**Comment by cweijan** [comment]
I have renewed the premium for your account.
