### ISSUE TITLE
[BUG] SELECT JOIN only working properly when using Aliases.

### ISSUE THREAD

**Issue by ZaikoXander** [cweijan/vscode-mysql#488]
- OS: Windows 10
- Database Type: MySQL

### Seems to work normally:
![image](https://user-images.githubusercontent.com/80606136/155026207-b58ab7e0-6cd1-40ff-8c71-641bb08b4613.png)

### But when I remove the Aliases, the first column seems to copy the Technology Name's column:
![image](https://user-images.githubusercontent.com/80606136/155026142-21df1236-ca7c-4abd-991a-144e1f02f3e2.png)

#### I tested at MySQL Workbench and worked normally.

**Comment by cweijan** [comment]
Regarding this point, I have explained in the readme that the program developed by nodejs cannot recognize the data with the same name column.
![image](https://user-images.githubusercontent.com/27798227/156279825-6eaa6876-aef0-4b9f-927e-419260a5b0f9.png)

**Comment by ZaikoXander** [comment]
Oh sorry, I should've paid attention on that. Thank you for the clarification 😄

**Comment by cweijan** [comment]
I found that I could solve this by switching the api, but would require a major refactoring of the code. Will fix it in the future.

**Comment by ZaikoXander** [comment]
Understood, like I don't really know how it works, but I'm here tracking the progress 😁

**Comment by cweijan** [comment]
Hi, this issue has been fixed in version 4.8.3.

**Comment by ZaikoXander** [comment]
Thank you, I already test it out, is perfectly working. Good job! 👊👊😎

**Comment by cweijan** [comment]
Thank's your feedback😊!
