### ISSUE TITLE
[BUG] You haven't created any connections

### ISSUE THREAD

**Issue by 18211167516** [cweijan/vscode-mysql#489]
- OS: windows
- Database Type:  全部类型

left panel is not displayed connections  and prompts You haven't created any connections

![image](https://user-images.githubusercontent.com/21099213/155060210-710d369d-b299-4c7d-9d83-186bc810f1ce.png)

**Comment by cweijan** [comment]
如果你是使用ssh容器, 需要重新添加连接.

**Comment by 18211167516** [comment]
我反复添加了几次，实际上配置文件也有了，但是左侧就不展示
![image](https://user-images.githubusercontent.com/21099213/155060633-681dcb85-bfcb-4fb7-baaf-d37dfc2521b6.png)

**Comment by cweijan** [comment]
你用的扩展截图给我看看, 可能是版本问题, 我没遇到这种情况呢.

**Comment by 18211167516** [comment]
我卸载重新装了几次也不行，应该是最新的
v4.6.0

**Comment by 18211167516** [comment]
![image](https://user-images.githubusercontent.com/21099213/155061631-e4119a09-9aa6-4ddc-b6d7-20b0740870b7.png)

**Comment by cweijan** [comment]
在这个面板, 这扩展有两个面板.
![image](https://user-images.githubusercontent.com/27798227/155064729-9dfd83be-80d4-44bf-b796-22cb0a6d5e7e.png)

**Comment by 18211167516** [comment]
找到了，他跑到资源管理器里了，谢谢

**Comment by MaluNoPeleke** [comment]
I agree that it is irritating, that the sentence is displayed if I already have set up a working connection (PostgreSQL)
