### ISSUE TITLE
[BUG]can not insert new row from UI button 「插入行」的按钮用不了

### ISSUE THREAD

**Issue by zhangjiankui** [cweijan/vscode-mysql#491]
- OS: macos 11.6
- Database Type: mysql 5.7.34

点「插入行」的按钮，只会在列表底部多个全null的行；
这一行直接编辑也保存不了，右键「打开编辑窗」编辑了也update不了；
希望能做成和「打开编辑窗」类型的交互，填好各个字段之后再insert新行。
谢谢作者大大！

![image](https://user-images.githubusercontent.com/26133797/155658328-cca06e8f-5c56-40d3-bcb4-82b2703c3f09.png)

![image](https://user-images.githubusercontent.com/26133797/155658733-3087c486-c586-4aff-9b52-b5d35368c489.png)

**Comment by cweijan** [comment]
直接编辑然后ctrl+s保存.

**Comment by zhangjiankui** [comment]
ctrl+s成功保存了，之前保存不了是因为用了MacOS常用的command+s键来保存。

**Comment by cweijan** [comment]
@zhangjiankui 问下mac保存都是command+s吗, 我没用过mac, 以为mac的command就是对应windows的ctrl键.

**Comment by zhangjiankui** [comment]
@cweijan 是的mac保存都是command+s，类似地还有复制粘贴command+c,command+v。
command键功能类似于windows的ctrl键。
而且mac还有独立的ctrl键，ctrl+c是「中断终端跑的进程」但不是复制。

**Comment by cweijan** [comment]
@zhangjiankui 谢谢反馈.

**Comment by wayland3** [comment]
> 直接编辑然后ctrl+s保存.

能否区分系统，mac用户，保存都是cmd+s，唯独这个里面用ctrl+s，难以习惯
另外，执行当前语句和执行所有语句的快捷键能否支持配置
