### ISSUE TITLE
[BUG] auto-complete doesn't work

### ISSUE THREAD

**Issue by zahraaalizadeh** [cweijan/vscode-mysql#492]
- OS Info: Ubuntu 21.04
- Database: Postgres
- Version: 4.7.0
When writing SQL queries on the database level, auto-complete table names and column names feature doesn't work for me.
![Screenshot from 2022-03-01 19-44-50](https://user-images.githubusercontent.com/73332835/156143322-6859c170-6a5c-4b41-a222-23f9562c1619.png)

**Comment by cweijan** [comment]
Thanks for your feedback, but postgresql has two levels, different schemas can have tables with the same name, so you should open query on the schema.

**Comment by cweijan** [comment]
I will parse the database to public schma in the next version.

**Comment by cweijan** [comment]
Hi, I updated version 4.7.3, now database query will provide completion of public schema.
