### ISSUE TITLE
[BUG] execute "run " from .sql tab causes editor view to "flip layout"

### ISSUE THREAD

**Issue by nxgnme** [cweijan/vscode-mysql#494]
- OS INFO :
running vscode on windows connected to a linux EC2 
extension version: v4.7.4
vscode: 1.64.2

when using a .sql window and pressing the RUN button the editor layout is flipped each time
![image](https://user-images.githubusercontent.com/60792522/156559298-a34bd2a3-814a-4719-bb85-e7e64e150279.png)

same function as view->Editor Layout-> flip view (shift+alt+0)

**Comment by cweijan** [comment]
because in order to move the view down for display.

**Comment by nxgnme** [comment]
is there a user workplace setting to override this possible?

**Comment by cweijan** [comment]
Try change this.
![image](https://user-images.githubusercontent.com/27798227/156751221-5d7a126c-e6d8-4b05-9b78-afeb33e244cc.png)

**Comment by nxgnme** [comment]
Works great, thanks for the prompt feedback
