### ISSUE TITLE
wrap long lines / json

### ISSUE THREAD

**Issue by nxgnme** [cweijan/vscode-mysql#495]
May have missed it, but is it possible to wrap long lines and format JSON columns in a pretty format?

**Comment by cweijan** [comment]
What's mean long line? If it is json, even if it is a pretty format, the format will be lost when it is stored in the database, the pretty format is only used for human viewing.

**Comment by nxgnme** [comment]
Long lines means anything that extends beyond the default column width. For example long multi line text. 
What would be good by clicking in the cell it would become an auto word wrap cell.

for JSON, an example is thunder client, a json response is automatically JSON pretty printed. Could you use the cell type to apply a pretty print option in conjunction with a word wrap?

**Comment by cweijan** [comment]
I understand what you mean, I have this plan, but it will take a while.

**Comment by cweijan** [comment]
Supported in version 5.0, now you can hover over the column and click the magnifying glass button.
![image](https://user-images.githubusercontent.com/27798227/160324055-3034e1f4-3258-43ed-ad1d-162c0cae73b2.png)
![image](https://user-images.githubusercontent.com/27798227/160324158-b3ed8864-bd17-4a62-b06b-6a4eab94afe0.png)

**Comment by nxgnme** [comment]
> Supported in version 5.0, now you can hover over the column and click the magnifying glass button. ![image](https://user-images.githubusercontent.com/27798227/160324055-3034e1f4-3258-43ed-ad1d-162c0cae73b2.png) ![image](https://user-images.githubusercontent.com/27798227/160324158-b3ed8864-bd17-4a62-b06b-6a4eab94afe0.png)

thanks for the prompt update, really cool you got this done so fast, the json format is excellent.

Can you add to your back log the possibility to change/add data in this view? copy paste into an insert is easy now with this view but in place edit would be awesome.

have sent you some coffee in the past, now have purchased as well.

**Comment by cweijan** [comment]
This is an achievable feature, but I would consider making it a paid feature.

**Comment by nxgnme** [comment]
> This is an achievable feature, but I would consider making it a paid feature.

I think that is fair as it is an enhancement to productivity

**Comment by cweijan** [comment]
Save has been supported in version 5.0.4, available for free users.
