### ISSUE TITLE
[BUG] Can't find workspace connections in the side bar panel

### ISSUE THREAD

**Issue by pinkplus** [cweijan/vscode-mysql#497]
- OS INFO : Mac (connecting to a Linux machine via ssh)

I can't find db connections that are created for workspaces in the side bar panel.

Looking at the source code, this line is retrieving global connections twice: https://github.com/cweijan/vscode-database-client/blob/main/src/provider/treeDataProvider.ts#L92

Probably a bug?

**Comment by cweijan** [comment]
The latest code has been closed source, not for reference.
If you are connecting via remote ssh, then you need to recreate the connection.

**Comment by pinkplus** [comment]
This still doesn't seem to work for me. After I create a workspace connection, I can see datbase-client.json file being created in the workspace .vscode directory. However, still I can't see anything in the side bar panel.

**Comment by pinkplus** [comment]
I was able to fix this issue --

The `database-client.json` file on my remote machine looks like this:
```json
{
    "database.connectionsssh-remote": {
        "1646367448338": {
            ...
        }
    }
}
```

On my local machine the field is `database.connections` instead of `database.connectionsssh-remote`. After I changed the field name to `database.connections` I can see the connection in the side bar panel.

**Comment by cweijan** [comment]
Thanks for your feedback, I will try to fix it in the next version.

**Comment by cweijan** [comment]
Fix at version 4.7.5.

**Comment by pinkplus** [comment]
I can confirm this is fixed. Thank you!

**Comment by cweijan** [comment]
I limited the workspace connection to premium in version 4.7.6, you helped me find a bug, after you register at https://database-client.com I will send you Premium for 3 months.

**Comment by pinkplus** [comment]
Oh thanks! I've registered using email poppet-sashes-0t@icloud.com. (I'll remove this comment later so that the email address is not seen by other people).

Thank you for your great work again!

**Comment by cweijan** [comment]
hi, I have added 3 months to your account, please log in to your account in vscode.

**Comment by pinkplus** [comment]
Thanks!
