### ISSUE TITLE
[BUG] Text between "less than" and "more than" signs in jsonb field of postgreSQL is not shown

### ISSUE THREAD

**Issue by elkhasa** [cweijan/vscode-mysql#498]
OS: Ubuntu 21.10
Database: PostgreSQL

Rows in database client:
![image](https://user-images.githubusercontent.com/68211603/156703698-4b2a9024-afc7-4ea1-9ed0-a6d749e50f23.png)

Rows in database selected using "psql":
```
 id |                           la                            
----+---------------------------------------------------------
  1 | {"row": "Row <row_in_tags> another Row"}
  2 | {"row": "Row <row_in_tags> another Row <more in tags>"}
```

**Comment by cweijan** [comment]
Thanks feedback, fix at version 4.7.5.
