### ISSUE TITLE
[BUG] No data in query result with left join

### ISSUE THREAD

**Issue by morallys** [cweijan/vscode-mysql#499]
- OS INFO :
Manjaro Linux - Arch Linux
Database: MariaDB normal instalation and MySQL in Docker 

When executing the query with LEFT JOIN, I didn't understand the lack of data that should be present. I tested it in MySQL Workbench, and got the correct result. Prints below for verification.

- With INNER JOIN in the VSCode
![image](https://user-images.githubusercontent.com/44041037/156845296-02049ef2-d5cd-40d2-9382-d00fdadba306.png)

- With LEFT JOIN in the VSCode
![image](https://user-images.githubusercontent.com/44041037/156846030-08262449-1984-421d-a523-26c2e436b9f3.png)

- With LEFT JOIN in the MySQL Workbench
![image](https://user-images.githubusercontent.com/44041037/156846124-b40aa17b-5006-4d91-a6f6-5bdbf5fa1f59.png)

Notice that there are different results for the same query, in the VSCode extension, the data is omitted and I don't know if there is any correlation with some missing configuration.

Error also in RIGHT JOIN, 

- Query in all table customer.
![image](https://user-images.githubusercontent.com/44041037/156848532-d424699e-d394-41e8-b05c-283d0f5ec513.png)

- With RIGHT JOIN in VSCODE
![image](https://user-images.githubusercontent.com/44041037/156848853-e47f23e8-29ee-419a-b50f-c84ecd5c7ad9.png)

- With RIGHT JOIN in MySQL Workbench
![image](https://user-images.githubusercontent.com/44041037/156849017-c6d11dae-a83a-42e8-bbb9-ff7a0bfeeade.png)

Check once again that in addition to the data being incorrect in the VSCode extension, as in the case of the first_name in which SHIRLEY is not shown, the data is exchanged for the right table, and should not appear in the left table in first_name and last_name, only in situation of match results.

**Comment by cweijan** [comment]
Hi, I have explained on the readme, this program is developed using node.js, nodejs does not support column names with the same property name, so you need to avoid the same column name in your query.
![image](https://user-images.githubusercontent.com/27798227/156861687-0fc4901e-2711-4348-877e-9c86b9c2f966.png)

**Comment by cweijan** [comment]
I found that I could fix this by switching the api, but it would require a major refactoring of the code.
Will track progress here #488.

**Comment by cweijan** [comment]
This bug has been fix at version 4.8.3.
