### ISSUE TITLE
[BUG] Cannot edit Connections in Free edition

### ISSUE THREAD

**Issue by pmcl77** [cweijan/vscode-mysql#501]
- OS INFO : Mac OS Big Sur

Well... I was in the middle of doing a database migration and was stopped by the change to closed source... But I have only 3 connections, but I cannot use all of them. I cannot edit connections either.

**Comment by pmcl77** [comment]
It works when using the "console" button but not with right-click on the connection itself...

**Comment by cweijan** [comment]
I don't plan to modify this, you can delete the existing connection and create a new one, or edit connection configuration through the following steps.
![image](https://user-images.githubusercontent.com/27798227/156908309-0df6a2c6-4bbd-46a2-b7e7-7831543cc850.png)

![image](https://user-images.githubusercontent.com/27798227/156908300-4af43d8c-c982-4fd4-a855-1e08c607ba3e.png)

**Comment by pmcl77** [comment]
Thanks mate! I got premium now, would like to support your awesome work! keep going!

**Comment by cweijan** [comment]
Thank's your support!
