### ISSUE TITLE
[BUG] Redis SSH隧道在成功连接一段时间后报错：连接出错! connect ECONNREFUSED 127.0.0.1:12801

### ISSUE THREAD

**Issue by PetrusZ** [cweijan/vscode-mysql#502]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/4990592/157032214-23f7aea7-17be-48c8-8b1d-247894ecde23.png">

配置如上，一开始还能正常使用，但过一阵子再看后就报错了。重启vscode似乎可以临时解决该问题。

**Comment by PetrusZ** [comment]
不光是redis，貌似是使用SSH隧道的都有这个问题，而且在重启vscode后，private key path又被重置为默认的了，没有将原来使用的private key path保存下来。

**Comment by cweijan** [comment]
感谢反馈, 密钥路径会报错的, 但是在编辑时又去读取了下, 下版本优化隧道的稳定性.

**Comment by cweijan** [comment]
刚发布了4.7.6版本修复了编辑时密钥路径丢失的问题, 同时增加了ssh隧道的稳定性, 尝试一下呢.

**Comment by PetrusZ** [comment]
@cweijan 密钥路径问题应该是修复了，redis的ssh隧道好像也没问题了，但是es不管有没有用ssh隧道，过一阵子都会报错connect ECONNREFUSED。

**Comment by PetrusZ** [comment]
另外远程的使用ssh隧道的ES，在编辑连接里重连就能临时解决，但是本地的没有使用SSH隧道的却不行。

**Comment by PetrusZ** [comment]
哦，忘记了我本地ES没有启动，不好意思。

**Comment by cweijan** [comment]
感谢你的反馈, 版本4.7.8修复了ssh隧道创建的es连接断开后无法重连.

**Comment by PetrusZ** [comment]
Thanks @cweijan , forgot to reply and close this issue. Everything works fine now.
