### ISSUE TITLE
[BUG] Can't open edit connection

### ISSUE THREAD

**Issue by EnterVPL** [cweijan/vscode-mysql#504]
Hi,
I'm trying open Edit connecion but extension display plan menu and has error `Free accounts can only create 3 connections!` but I have only two connections. What is wrong?
![zrzutka20220309](https://user-images.githubusercontent.com/21365293/157435997-7f3319bb-de57-47ee-934b-5030a17cba1f.png)

**Comment by cweijan** [comment]
The total number of connections includes the nosql panel.

**Comment by EnterVPL** [comment]
In the nosql panel i have 0 connections
![image](https://user-images.githubusercontent.com/21365293/158966598-c3b5843d-ab2c-4310-abc7-0b1d66214f0b.png)

**Comment by mariocolque-peya** [comment]
The same weird issue here... No chance to edit with only two connections for SQL.

**Comment by cweijan** [comment]
Fixed in version 4.8.6.
