### ISSUE TITLE
Comment recognition

### ISSUE THREAD

**Issue by silverbullettruck2001** [cweijan/vscode-mysql#506]
In MySQL there are two different recognized single-line comment characters, (`--` or `#`).  However, currently when you use the `#` it is not color coded when used.  Only the `--` comments are styled differently.  Can it be changed so that both can be colored the same?  

Below is currently how it is handled:
![image](https://user-images.githubusercontent.com/26559157/157443733-de844fec-0805-453a-b403-985ae82ffcfe.png)

**Comment by cweijan** [comment]
This is a problem with vscode, vscode can only use a single-line comment rule.

**Comment by silverbullettruck2001** [comment]
@cweijan could there be a way to allow for a setting to change the single-line comment to use `#` instead of `--` since both can't be recognized at the same time?

**Comment by cweijan** [comment]
Vscode does not support it, refer to this issue https://github.com/microsoft/vscode/issues/64659.

**Comment by silverbullettruck2001** [comment]
@cweijan however,  if I change the config file as follows, shouldn't it color code the `#`?  I tried doing this, but it still doesn't color code the `#`.  Is there something else that needs to change to allow me to switch it so that it only uses and stylizes `#` instead of `--` as comments?

```{
"comments": {
	"lineComment": "#",
	"blockComment": [ "/*", "*/" ]
},
}

**Comment by cweijan** [comment]
Sorry I made a mistake about matching comment,  I will implement it in the next version.

**Comment by silverbullettruck2001** [comment]
@cweijan thanks for the clarification and for getting this addressed!

**Comment by cweijan** [comment]
hi, support for #line comments is supported in version 4.7.8.
