### ISSUE TITLE
[BUG] mongodb incorrectly modifies field to string

### ISSUE THREAD

**Issue by angeltonio** [cweijan/vscode-mysql#508]
- OS INFO : Windows 10 Pro

When you are working with MongodDB, and you want to change a field of the collection and you have a field ObjectID, and you change another element, it seems that at the time of saving I save all the fields in string and modify something of the objectID that later when doing populate when you need it it shows error. It happens as if the ObjectID you had is modified in something and it shows you an error

**Comment by cweijan** [comment]
Sorry I didn't understand what you mean, it's better to take a screenshot. ObjectID is an identifier for all data in mongodb, don't modify it.

**Comment by cweijan** [comment]
Closed because not enough information.
