### ISSUE TITLE
[BUG] Swaps second editor between horizontal/vertical

### ISSUE THREAD

**Issue by maslade** [cweijan/vscode-mysql#509]
- OS INFO : macOS 11.6.4

When I run the query with a single editor, it is split according to the opposite of how I most recently split the editor myself. Meaning if I had split my editor vertically into side-by-side editors most recently, then after running a query the results are displayed in the second pane *which has now moved to a top-bottom configuration*.

It happens inconsistently but most of the time.

**Comment by cweijan** [comment]
Disable this option.
![image](https://user-images.githubusercontent.com/27798227/158181034-1885c814-1990-4d2c-95e0-ab6848af1f0d.png)
