### ISSUE TITLE
[BUG] Order by column fail.

### ISSUE THREAD

**Issue by pmcl77** [cweijan/vscode-mysql#511]
- OS INFO : Mac OS BigSur
- Database Client: v4.8.4
- Database: MariaDB/MySQL

When using the carets to apply order by, it uses the wrong "column index number".

In the screenshot, I ordered by the first column which should result in "ORDER BY 1" instead of "ORDER BY 0".

<img width="386" alt="Screenshot 2022-03-16 at 22 57 13" src="https://user-images.githubusercontent.com/57845954/158698258-d59ddc30-1faf-4b95-bb72-a1ade751fc43.png">

**Comment by cweijan** [comment]
Thanks for your feedback, this bug has been fixed in version 4.8.5.
