### ISSUE TITLE
[BUG] -  MYSQL - Procedure and Function Update - New issue noticed from Today

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#513]
- OS INFO :Windows
- Database - MySQL
- Extension Version - v4.8.5

From today onwards while executing procedures/functions in MySQL, the result is not getting displayed. Instead working sign is getting displayed.  Till yesterday, there is no issue. I tried in my home laptop and office laptop, and I am having this issue in both laptops.  

A sample file is enclosed.  Normally, I select the full text and execute the command - MySQL : Run Selected SQL.  The result of the execution will get displayed in the data window.  Now, the procedure/function is getting updated in the DB internally.  But the result is not getting displayed.

Can you please check the issue and fix it. 

[BS DEVTEAM FUNCTION GET_SOLNAME.txt](https://github.com/cweijan/vscode-database-client/files/8288397/BS.DEVTEAM.FUNCTION.GET_SOLNAME.txt)

Thanks for the great extension

Regards

Franklin KF

**Comment by franklinkf** [comment]
![image](https://user-images.githubusercontent.com/8948123/158857990-f09baca2-2ea3-4394-a04d-10bff45d78b8.png)

Screenshot of the execution window enclosed

**Comment by franklinkf** [comment]
If I execute the file in three parts, I am getting the response correctly

(Refer Sample File inclosed in the bug report)

Part 1 - SET NAMES utf8mb4;
Part 2 - DROP FUNCTION IF EXISTS GET_SOLNAME;
Part 3 - CREATE FUNCTION .... block

This is for your information

**Comment by cweijan** [comment]
Thanks for your feedback, in the new version, the API was modified when fixing the major problem #488, which caused this bug, I will fix it in the next version.

**Comment by franklinkf** [comment]
Thank you very much Sir

**Comment by cweijan** [comment]
Fixed in version 4.8.6.
