### ISSUE TITLE
More infos about the columns in the tree view

### ISSUE THREAD

**Issue by trollfalgar** [cweijan/vscode-mysql#514]
It's possible to show more infos about the columns in the tree view, beside the type?
Would be very helpful to see easily: keys, indexes, not null indicators, so on.

Something like this:

![Tree view](https://i.imgur.com/C7MguYX.png)

Thanks!

**Comment by cweijan** [comment]
oh, I have this plan, it will come true in the future.

**Comment by trollfalgar** [comment]
> oh, I have this plan, it will come true in the future.

Thanks, I'll be waiting! :)

**Comment by cweijan** [comment]
Hi, I canceled this plan, the tree view looks clunky after grouping the index and column.
Consider using a design table.
![image](https://user-images.githubusercontent.com/27798227/163908970-b0630c98-946d-431a-b726-9e31640d8588.png)

**Comment by trollfalgar** [comment]
I see.
Oks, thanks!

**Comment by cweijan** [comment]
Hi, I have added the display of the index in version 5.2.1, I will continue to work here, your suggestions are welcome!
![image](https://user-images.githubusercontent.com/27798227/165015331-9ca03c5c-3e7f-4f1a-88d3-6a9e2c3b0eeb.png)

**Comment by trollfalgar** [comment]
Hello, first, thanks for the great work.

I'm facing this issue.

![image](https://user-images.githubusercontent.com/441455/165093204-cfe3fb4e-28ad-4914-9b9f-917753714a55.png)

I'll reinstall the extension and do some tests.

**Comment by cweijan** [comment]
What's your database server and version?

**Comment by trollfalgar** [comment]
> 

MySQL version 8.0.28.

**Comment by cweijan** [comment]
Hi, I have fixed this in version 5.2.2.

**Comment by trollfalgar** [comment]
It's working nicely now, thanks.

![image](https://user-images.githubusercontent.com/441455/165536757-ee84d959-c420-4421-bca6-084fc9ac6844.png)

One more sugestion.
Would be very nice to know visualy the nullable/required columns.
In the exemple below, the required fields have a little dot at the icon of the column.
So the columns that dosn't have, are nullables.

![image](https://user-images.githubusercontent.com/441455/165537455-0a138bb9-a352-4819-8989-14d384afbe90.png)

**Comment by cweijan** [comment]
This is an interesting proposal, I will show the non-nullable columns in red after the next update.

**Comment by cweijan** [comment]
hi, I'm releasing version 5.2.4, now it will show non-nullable columns in red.
![image](https://user-images.githubusercontent.com/27798227/165907603-af28bfe3-a1e5-427e-8a58-0ac049e92254.png)

**Comment by trollfalgar** [comment]
Great work, thanks.

Now, one more sugestion. But, it's just another visual convenience.

For foreign keys columns to show a diferente icon, like primary keys. I personaly think make sense, primary keys and foreign keys are related.

The information of foreign keys are show in the **index** part, but, again, a simple visual help with a icon is very nice.

**Comment by cweijan** [comment]
Thanks, I didn't think about foreign keys before, I will support it in the future.

**Comment by cweijan** [comment]
Hi, I have released version 5.7.4, and now you can set the display of foreign keys on the connection page. Since foreign keys will affect the speed of querying columns, I do not enable it by default.
![image](https://user-images.githubusercontent.com/27798227/186857168-d0a87469-9591-4506-bc8d-d9c67d255f9c.png)
![image](https://user-images.githubusercontent.com/27798227/186857231-c8cbf38f-09bf-4500-9750-c29a20ae1e53.png)

**Comment by cweijan** [comment]
This is the effect of showing foreign keys.
![image](https://user-images.githubusercontent.com/27798227/186857362-300f5a31-63a4-4543-9cb5-576b487375df.png)
