### ISSUE TITLE
[BUG]界面修改记录, 显示问题

### ISSUE THREAD

**Issue by neozxy** [cweijan/vscode-mysql#515]
当我在界面上修改了某条记录,但是并没有commit, 然后把滚动条向右滑动,我修改的那个值会跟着界面滑动

**Comment by cweijan** [comment]
Hi, 因为web的性能不够, 这里是使用了虚拟表格, 当滚动的时候数据就会修改, 后续我尝试在滚动的时候将编辑状态移除.

**Comment by cweijan** [comment]
发布了4.8.6版本, 在滚动时会将编辑状态移除.
