### ISSUE TITLE
Why are there two extensions? Which of both should I download?

### ISSUE THREAD

**Issue by Eptagone** [cweijan/vscode-mysql#517]
[MySQL](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2) or [Database client](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2)

**Comment by cweijan** [comment]
These two extensions are the same, originally it was just a mysql extension, so it was named mysql, and later other types of databases were added.
