### ISSUE TITLE
[BUG]执行脚本后会强行将右侧tab页移动到下侧

### ISSUE THREAD

**Issue by zhangjiankui** [cweijan/vscode-mysql#518]
- OS INFO : macos 11.6

在sql文件的编辑界面上Run SQL，已知会在下侧新建tab展示查询结果，但是这样会把右侧的tab页移动下侧。
如下图，开始右侧有两个tab页，但是Run SQL后这两个tab页被移到了下侧：
![image](https://user-images.githubusercontent.com/26133797/159205236-2ef78b2f-1d8d-4e5c-885f-7e6723eccdd1.png)
![image](https://user-images.githubusercontent.com/26133797/159205292-27ad2db3-709f-4b13-98d5-57d3d80d389b.png)

**Comment by cweijan** [comment]
修改这个设置呢.
![image](https://user-images.githubusercontent.com/27798227/159205892-2d2b2511-e8f3-48c4-9c62-d3df8efda6f5.png)

**Comment by zhangjiankui** [comment]
可以了，关掉配置就能直接在右侧出结果tab，谢谢
