### ISSUE TITLE
Use SSH config for ProxyJump

### ISSUE THREAD

**Issue by dmca-glasgow** [cweijan/vscode-mysql#519]
Hi,

I've just been evaluating your database client.

However it doesn't have a feature I need for work, and I wonder if it is possible or not:

I connect to production databases via SSH tunnel.  The production servers are behind a VPN, however there is a bastion host which I can use to "ProxyJump" to my production server without connecting to the VPN.

I have an SSH config file located on my Mac at `~/.ssh/config` which stores this configuration:

```
Host bastion-host.my-work.com
  IdentityFile ~/.ssh/work_identity_file

Host production-server-behind-vpn.my-work.com
  IdentityFile ~/.ssh/work_identity_file
  ProxyJump myuser@bastion-host.my-work.com
```

Using ssh cli, if I connect to `myuser@production-server-behind-vpn.my-work.com` it uses this configuration and passes through the bastion host server.

Can this be done with this project?

Thanks.

**Comment by cweijan** [comment]
According to your description, you need a three-level jump to connect to the database.
This means that no client can support it, you can only support it if you switch to a secondary jump, which is not the scope of this software.

**Comment by dmca-glasgow** [comment]
Thanks for the reply @cweijan.

I have just read the `ssh2` package does [not support](https://github.com/mscdex/ssh2/issues/70) reading the users `.ssh/config` file.

I'm not 100% sure what you mean about jumps, but I think you're right no other client supports it.  I've found other Postgres users [discussing this](https://github.com/jakob/Postico/issues/532), maybe you can consider it one day in the future, as personally I can perform all my other tasks except database maintenance without manually connecting to the VPN!

**Comment by cweijan** [comment]
"Jump" mean port forward. This is not relevant for any database client, you need to forward the database port out of your bastion host.

When you forward the database port from the bastion host, any database software will work fine.

**Comment by moon548834** [comment]
my ~/.ssh/config:
``` 
Host jump
         HostName jump_server_hostname
         Port jump_server_port
         User jump_server_user
Host target
        HostName target_server_hostname 
        Port target_server_port
        User target_server_user
```
this do the forward thing(run on the local machine):
`ssh -o ServerAliveInterval=60 -fNL {local_port}:localhost:3306 target`
then:
`mysql -P {local_port} -h 127.0.0.1 -u {target_server_mysql_username} -p`
> the local port can be any port that is not using.

and enter the password, then you can connect the prod db in local development.

You can add that database config in the vscode plugin as well, hope it can help.
