### ISSUE TITLE
支持mac cammand键

### ISSUE THREAD

**Issue by wayland3** [cweijan/vscode-mysql#521]
你好！感谢不断的升级和维护。
在使用过程中，作为mac用户，几乎所有windows的control键都是用的mac的command
希望能更新一下映射，因为经常要转化一下，不太习惯

执行语句的快捷键，在mac上control+enter 为 command+enter，执行所有语句command+shift+enter
编辑行后保存，在mac上control+s 为 command+s

谢谢

**Comment by cweijan** [comment]
感谢反馈, 会在下版本增加.

**Comment by cweijan** [comment]
已经在版本5.0支持了.

**Comment by zhangjiankui** [comment]
@cweijan 我当前的版本是5.0.1，系统macos，在查询结果的表格界面，点击单元格编辑，还是只能用ctrl+s保存，cmd+s不行
![image](https://user-images.githubusercontent.com/26133797/160575635-8e2a738c-ba72-444c-ba4c-b9681182e81c.png)

**Comment by cweijan** [comment]
@zhangjiankui 代码看起来没啥问题, 不行可以使用回车键进行保存, 这个更方便.

**Comment by wayland3** [comment]
感谢，我试了，是可以的，已经升级到v5.0.2，有一个地方，如图，这里执行查询语句时，还是用的coontrol+enter，麻烦也支持一下，谢谢
![image](https://user-images.githubusercontent.com/23661071/160838668-57201984-8fc3-42c8-b8e2-d088ebc8afaa.png)

**Comment by cweijan** [comment]
Hi, 尝试5.3.3版本, 现在应该能够正常使用cmd键了.
