### ISSUE TITLE
[BUG]sql文件的「运行选择sql」的快捷键「command+回车」与vs code的「插入新行」快捷键冲突，容易引起误操作

### ISSUE THREAD

**Issue by zhangjiankui** [cweijan/vscode-mysql#522]
- OS: macos
- Database Type: mysql

作为vscode用户，习惯性地使用「command+回车」来换行。
在编辑sql文件的时候也同样。但是此时会直接执行光标所在的sql语句块，即使此时并没有「选中」任何sql语句。

如果意外执行的是删除更新之类的语句，将会导致严重后果。
希望处理一下这种操作习惯上的冲突。
或者直接地如果不选中sql语句，则不会自动执行光标所在的代码块。

**Comment by cweijan** [comment]
是在issue#521 中有人建议将command键绑定到SQL执行的.
现在的逻辑就是有选中就执行选中, 没有选中就执行当前光标SQL, 实际上没有选中是更常见的, 这个快捷键也是为了这个而服务.

**Comment by zhangjiankui** [comment]
这里和是不是mac用command键无关。
在windows上vscode也会惯用「ctrl+回车」来换行，这里也和插件的执行sql命令相同。
这种情况下，就会出现编辑sql时想换行，但是却直接执行sql语句的问题。
能快捷操作是好事，但是如果新的快捷操作和现有的快捷操作冲突，还可能会造成不可挽留的后果（不小心执行delete语句），就应该斟酌一下处理了。

**Comment by cweijan** [comment]
ctrl+enter其实也是之前的用户建议的, 我觉得这个建议很不错, 就改了. 我自定义了新行的快捷键, 所以不知道和vscode自带的快捷键冲突了, 下个版本会将cmd+enter取消, 但我对ctrl+enter执行SQL这个快捷键很满意, 不打算修改, 你有需要可自己在vscode的快捷键中自行映射成别的.

**Comment by zhangjiankui** [comment]
希望可以做个可以关闭「未选中时自动执行光标所在sql语句」的开关配置，这样就不需要改快捷键也不会误执行了。

**Comment by cweijan** [comment]
这是个特殊需求场景, 我不会考虑这种情况, 如果你是付费用户, 我可为此增加一个选项.

**Comment by zhangjiankui** [comment]
我是付费用户，确实需要这个选项，「cmd+回车」键可以保留，但是需要「未选中」的开关

**Comment by cweijan** [comment]
ok, 会在下版本增加.

**Comment by cweijan** [comment]
发布新版本5.0.2了, 取消勾选这个选项后可以得到你要的效果.
![image](https://user-images.githubusercontent.com/27798227/160737745-f88ad264-ee17-4166-8994-62381602c578.png)

**Comment by zhangjiankui** [comment]
已经用了，就是这样的效果，感谢
