### ISSUE TITLE
[BUG] 输出channal 不断的输出并占用界面的焦点

### ISSUE THREAD

**Issue by heartacker** [cweijan/vscode-mysql#523]
名称: SSH Client
ID: cweijan.vscode-ssh
说明: SSH Client and Database manager for MySQL/MariaDB, PostgreSQL, SQLite, Redis and ElasticSearch.
版本: 5.0.2
发布者: cweijan
VS Marketplace 链接: https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-ssh

不断的输出，占用焦点
![image](https://user-images.githubusercontent.com/1876302/160577574-d22d60f1-62d0-4195-b051-d2b07f09c786.png)

**Comment by cweijan** [comment]
你有创建什么连接吗, 程序不涉及到python, 这个输出看起来很奇怪.

**Comment by heartacker** [comment]
我没有创建任何连接。

**Comment by cweijan** [comment]
你把扩展卸载重装试一试.

**Comment by cweijan** [comment]
Hi,  我之前拦截了全局错误, 这个错误是其他扩展导致的, 被这个扩展拦截到了, 我已在新版本5.0.3中取消.
