### ISSUE TITLE
JSONB object is not displayed.

### ISSUE THREAD

**Issue by RollingTL** [cweijan/vscode-mysql#524]
- OS: MacOS
- Database Type: psql (PostgreSQL) 14.2

Json build displays correctly only arrays objects. Objects are not displayed as if field is empty:
[{type:1}] - displays correctly.
{type:1} - display empty field.

**Comment by cweijan** [comment]
Thanks for the feedback, I will enhance the support for jsonb in next version.

**Comment by cweijan** [comment]
I think you are using https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-postgresql-client2, you need uninstall it and install https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2.

**Comment by RollingTL** [comment]
Thanks. JSONB works now. Great job and great tool.
