### ISSUE TITLE
[BUG] 两个图标大小不一致

### ISSUE THREAD

**Issue by heartacker** [cweijan/vscode-mysql#526]
![image](https://user-images.githubusercontent.com/1876302/160881773-2337cb0b-ad95-458a-ab24-dd20037826d5.png)
 图标大小不一致。

**Comment by cweijan** [comment]
你这让我有点绷不住🥲, 没人规定他们大小要一样啊.

**Comment by heartacker** [comment]
> 你这让我有点绷不住🥲, 没人规定他们大小要一样啊.

是没规定。不过看起来不舒服😂

**Comment by cweijan** [comment]
没有专业的设计师, 就不管这个了.

**Comment by cweijan** [comment]
找到个不错的icon, 下版本会更新.

**Comment by cweijan** [comment]
已在版本5.0.4中更新了容器icon
