### ISSUE TITLE
[BUG] Among all the VSCode extensions, vscode-database-client is the slowest in terms of activation time

### ISSUE THREAD

**Issue by tigerinus** [cweijan/vscode-mysql#527]
- OS: WSL2
- Database Type:

![image](https://user-images.githubusercontent.com/7172560/161267056-c5c8aebe-9274-4530-8279-bd55646b96ee.png)

This extension takes more than `2000ms` to get activated in general, 3~4x slower than the 2nd slowest extension, GitHub Copilot (`600ms`), in my test, while most other 40+ extensions get activated less than `300ms`.

**Comment by cweijan** [comment]
Try using extension mysql and uninstall database-client, although their code is exactly the same, but mysql startup seems to be faster, vscode does not provide a detailed analysis report, which cannot be processed here.
![image](https://user-images.githubusercontent.com/27798227/161289598-24b4ad2f-4613-4ae6-be94-642f243ccb05.png)

**Comment by tigerinus** [comment]
Could it be some kind of eager initialization at boot time? Can it be switched to lazy initialization?

**Comment by cweijan** [comment]
I can only control when the extension is activated, but it doesn't make much sense.
