### ISSUE TITLE
SQL Parameters

### ISSUE THREAD

**Issue by bklogic** [cweijan/vscode-mysql#528]
Does the database client currently support parameters in SQL?

We often have statements like:
`select * from customers where customer_name = :customerName`
in application, and like to test it directly in the database client.
In Oracle SQL developer, it will pop up a wizard and let you specify a value when you run it.  
This feature is useful if you don't have it yet.

**Comment by cweijan** [comment]
Well, enough users have mentioned this feature now that I will try to implement it in the future.

**Comment by bklogic** [comment]
Thanks for quick response. Looking forward to it.

**Comment by cweijan** [comment]
I have supported SQL parameters in version 5.2.2, note that strings need to be added with quotes.
![image](https://user-images.githubusercontent.com/27798227/165432752-c5c3eb09-9d81-44dc-bc5d-b65915dd3411.png)

**Comment by bklogic** [comment]
Thank you for the quick turnaround.  It is adding a whole lot of value to users.  Here is a test I did with my SQL:
![image](https://user-images.githubusercontent.com/20359767/165544504-736a7601-8377-4aa1-9bb7-bbf80535dc43.png)

I have tested with a number, a string and a date string.  It works really well, and easy to use.  On the quotes for string part, it makes sense from SQL perspective that you make user responsible for the quotes; however, from UX perspective, it just feels better not having to quote a value.  I read your notes and I knew that I needed single-quote the staring value, but I still missed it on my first try.  That is why I am shifting from SQL per perspective to UX perspective.  Maybe you want to give a bit more thoughts on this part.  Nonetheless, the value is there.  Thanks for the good and quick job.

**Comment by bklogic** [comment]
On a separate note, I love the way that you have the "virtual" Run SQL button in the SQL file, but the running SQL and the result in a separate pane, so that you can test the SQL without disturbing the SQL file.  To me that is exactly what I want.  However, I notice that you cannot resize the query section in the running pane.  I feel it can be awkward if the query is large.  For enterprise application, it is not uncommon to have a large number of large to huge queries.  Just another thing for you to look at.
I like your extension and I am going to get your premium version to try.

**Comment by cweijan** [comment]
Hi, I am currently concatenating strings. Only when I use prepared statements, the user does not need to enter single quotes.
But this extension didn't consider using prepared statements in the first place, so I wouldn't change it for this feature.

**Comment by cweijan** [comment]
For the code input box of the result page, I limit its maximum height. The purpose of this input box is to let the user know what the SQL of the last query was run. Editing here is not recommended. I will try to make the input box accessible by dragging Drag to change height.

**Comment by bklogic** [comment]
It is good to concatenate the strings to form a neat SQL statement.  However, you can single-quote the string, or anything other than numbers, before you concatenate. Then you still get the same thing, but save the user from the work. The work is not that important but the experience is.

For the code input box of the result page, it makes good sense to me now.  The user actually has no problem to view the whole query because of the scroll bar.  However,  if you can make the box re-sizable by dragging, it will give the user a sense of control, I guess.
