### ISSUE TITLE
[BUG] Unformatted JSON string in Redis

### ISSUE THREAD

**Issue by aswinkumar863** [cweijan/vscode-mysql#529]
JSON formatting and theme-specific code highlighting seems broken in a recent release
![image](https://user-images.githubusercontent.com/32381261/161431447-b5f93dc3-168d-4ff9-a498-0e4426e0434a.png)

- OS: Windows 10
- Database Type: Redis

**Comment by cweijan** [comment]
JSON formatting is indeed canceled, I will improve it in the next version.
The code highlighting is still effective, just the color is modified.

**Comment by aswinkumar863** [comment]
@cweijan I mentioned about native look and feel of code highlighting that added in  https://github.com/cweijan/vscode-database-client/pull/283.

No problem if it is removed with knowledge.

**Comment by cweijan** [comment]
The reason for this is because I integrated codemirror in the new version, so some of the previous code was deleted.

**Comment by aswinkumar863** [comment]
Great. Consider [Monaco Editor](https://microsoft.github.io/monaco-editor/) which contains all vscode features and won't be a problem if the major design change arrives to vscode.

**Comment by cweijan** [comment]
I have tried it, but because monaco requires service worker, and vscode webview does not support it. And monaco is too heavy, it is not suitable for integration in the extension.

**Comment by cweijan** [comment]
I have automatically formatted json in version 5.0.8 and made it compatible with vscode dark theme.
