### ISSUE TITLE
Gitpod: Connect to database automatically

### ISSUE THREAD

**Issue by carstenjaksch** [cweijan/vscode-mysql#531]
I use Gitpod to set up a Laravel dev environment and use this plugin to connect to the local database.

This process is fully automated, except the database connection.

Laravel uses environment variables to store database credentials. Would it be possible that this plugin looks for such variables and attempts to connect on startup?

These variable key names are fairly generic, I think. For example (.env):

```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=laravel
DB_USERNAME=sail
DB_PASSWORD=password
```

**Comment by cweijan** [comment]
The extension supports doing this, but only open for premium users.
When a workspace level connection is created, the configuration information will be saved in the current directory.
![image](https://user-images.githubusercontent.com/27798227/161720907-95b71b99-dfa1-4af0-b95e-f34aac78e332.png)

**Comment by carstenjaksch** [comment]
I know developing such an extension is hard work but even if I pay for it ...

Every time a Gitpod workspace is launched, I would need to manually login for the premium features to be available, right?

**Comment by cweijan** [comment]
No need to log in if the connection is already saved in your workspace. The connection is saved like this.
![image](https://user-images.githubusercontent.com/27798227/161739151-19ea68a1-d517-420c-a79e-eee79852c16e.png)

**Comment by cweijan** [comment]
hi, if you are a free user, you can also create database-client.json manually to achieve the workspace level conneciton.
