### ISSUE TITLE
MariaDB 10.6 ssl-mode [BUG]

### ISSUE THREAD

**Issue by Indribell** [cweijan/vscode-mysql#532]
- OS: Linux (WSL2)
- Database Type: MariaDB 10.6 (latest stable)

Running the db dump on a mariaDB database, resulting in the following error:

> mysqldump: unknown variable 'ssl-mode=DISABLED'
> mysqldump -h 127.0.0.1 -P 3306 -u xxxxxxx -pxxxxxxx --ssl-mode=DISABLED --skip-add-locks --no-data DBName >/home/xxxxxx/Golang/xxxxxx/xxxxxx_2022-04-05_222626.sql

"ssl-mode=DISABLED" replaces "ssl" in MySQL 5.6 but MariaDB does not support "ssl-mode=DISABLED".

And it looks like they are not going to implement it.

https://jira.mariadb.org/browse/MDEV-22129

By default ssl-mode is disabled for MySQL when no connection can be made.

MySQL manual:

> [--ssl-mode=mode](https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#option_general_ssl-mode)
> This option specifies the desired security state of the connection to the server. These mode values are permissible, in order of increasing strictness:
> PREFERRED: Establish an encrypted connection if the server supports encrypted connections, falling back to an unencrypted connection if an encrypted connection cannot be established. **This is the default if [--ssl-mode]) is not specified.**

Removing ssl-mode fixes the issue for the backup, as you only need to provide a SSL mode when you really want to use SSL.

**Comment by cweijan** [comment]
The reason for adding this option is because in mysql_dump above mysql8, ssl_mode is enabled by default. I will detection of mysql_dump version in future version, remove this option in older versions.

**Comment by cweijan** [comment]
Hi, I have removed this option for older versions in 5.1.0.
