### ISSUE TITLE
增加多个tab

### ISSUE THREAD

**Issue by wayland3** [cweijan/vscode-mysql#533]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/23661071/161892978-865db771-1cb8-4b4c-ac39-1be0b8ebcd63.png">
如图中1：增加多个tab, 避免点开后覆盖
如图中2：执行语句时，mac应使用command+enter
感谢

**Comment by cweijan** [comment]
多标签有两种方式, 1. 点击表旁边的按钮, 2. 点击结果视图的锁头解锁
![image](https://user-images.githubusercontent.com/27798227/161893821-507d04e0-e219-4dd6-ac17-06f075d2665d.png)
![image](https://user-images.githubusercontent.com/27798227/161893843-6e421cf5-7104-4b07-b2b3-53eb5933a5c1.png)

**Comment by wayland3** [comment]
3q
