### ISSUE TITLE
[BUG] Database lost connection after commit changes

### ISSUE THREAD

**Issue by dawsondong** [cweijan/vscode-mysql#534]
- OS: Windows x86
- Database Type: postgresql v14
- After submitting sql updates, result pannel cannot return response but with waitting status forever. Refreshing database will get "connect time out". Restarting vscode mannually, then everything looks normal.

**Comment by cweijan** [comment]
Some SQL execution result parsing failed, I am working on it.

please tell me more info help me solve it.
1. Specific execution type of SQL
2. Have you executed multiple update statements?

**Comment by dawsondong** [comment]
sql I wrote is like:
drop table if exists xxxxx;
CREATE Table xxxxx (
    .......
);

I tried some times. If I execute single sentence no mater drop or create, both will run ok. If I run them together, then connection will be lost, although everything runs correctly in background. Same thing happen when I execute single insert and multi insert sentence.

**Comment by cweijan** [comment]
Hi, I have fixed this in 5.1.0.

**Comment by dawsondong** [comment]
Verify it fixed on 5.1.2.
