### ISSUE TITLE
redis无法修改zset的score

### ISSUE THREAD

**Issue by wayland3** [cweijan/vscode-mysql#535]
- OS: mac
- Database Type: redis
如图：添加时没有输入score的地方, 另期望有修改score和value的地方
<img width="750" alt="image" src="https://user-images.githubusercontent.com/23661071/161920569-7f8fb1ce-ef24-457f-980a-365ef909b911.png">

**Comment by cweijan** [comment]
已在5.1.6版本支持.

**Comment by wayland3** [comment]
您好！您的邮件已收到，谢谢！
