### ISSUE TITLE
Option to save/not to save password for each connection

### ISSUE THREAD

**Issue by myatmin** [cweijan/vscode-mysql#536]
To offer an option to save or not to save the password of each connection in `Connection Configuration`.

**Comment by cweijan** [comment]
At the end of issue #475 I have stated my opinion, I do not intend to implement this feature.
> Not saving passwords is usually a user's concern about password leaks, but I don't want to support this scenario.

**Comment by myatmin** [comment]
Even in the premium plan?

**Comment by cweijan** [comment]
If you are a premium user, I can add this option for this feature.

**Comment by cweijan** [comment]
Support in version 5.1.8.
![image](https://user-images.githubusercontent.com/27798227/163907577-5ff13d4d-8042-43f5-8af2-bf1baa1c1ff3.png)
