### ISSUE TITLE
Data Output Window - Provision to hide query box and toolbar Ribbon

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#538]
Dear Sir,

I use this extension for working on my MySQL Database and now I ditched all my IDEs previously used for MySQL.  I normally execute queries from a SQL File and this extension displays the query result in a different window.  But along with data, the window displays the query and the toolbar ribbon, which totally reduces the space for real output.  The query box is not required as the query is lying in my SQL file and I have not used any option in the toolbar ribbon till date.  Hence I request you to provide an option in the settings to Hide both the Query Box and Toolbar ribbon.

Screenshot of existing output window is like this:

![image](https://user-images.githubusercontent.com/8948123/162139925-646b2647-a56b-40c0-ae89-3b0b75f11311.png)

Screenshot of desired output window is like this:

![image](https://user-images.githubusercontent.com/8948123/162140014-e9bc92b1-6d20-46d0-885b-b000b9617733.png)

Request you to please consider the above requirement.

Thank you once again for a great extension.  I have already purchased the extension.  Totally worth it.

Regards,

Franklin

**Comment by cweijan** [comment]
Thanks for your support, I will add an option to hide it in future versions.

**Comment by franklinkf** [comment]
Thank you Sir

**Comment by cweijan** [comment]
Hi, I have added these two options in version 5.1.0, I recommend you to set it to auto, so that when you view the table, the toolbar will still show.
![image](https://user-images.githubusercontent.com/27798227/162604384-d5075051-61c2-4a6c-807d-36254eb600d5.png)

**Comment by franklinkf** [comment]
Thanks for integrating the requested feature.  In the ShowSQLPanel settings, if I make the settings as Hide, it is hiding both the SQL Panel and the Result Panel.  Hiding the result panel will remove the option to know the error in case of errors. Hence I request you to hide only the SQL Panel under this settings.  Result panel can be displayed.  A scenario is given below:

![image](https://user-images.githubusercontent.com/8948123/166664206-193a874e-0e3c-417f-8777-71d2f1d66f96.png)

If I option to hide the ShowSQLPanel, the both the SQL and result panel is getting hidden.  Instead, the result panel to be displayed

![image](https://user-images.githubusercontent.com/8948123/166664393-db3b659e-e8f5-4c71-a965-efa4f5b44624.png)

Request you to please consider the change.

**Comment by franklinkf** [comment]
May I place one more request for your consideration.

Scenario:

1. I execute a SELECT command.   Extension displays the result in the result view.

![image](https://user-images.githubusercontent.com/8948123/166665860-67cedede-9021-445a-9b4e-f4678afb63a1.png)
I
2. Then I execute non SELECT command.
3. System not clearing the result view of the first command

![image](https://user-images.githubusercontent.com/8948123/166666040-0e32bddb-c902-45d3-b34c-ac39e902ae68.png)

Can you please clear the result view of the previous command, when a new command is executed.

Thanking you

**Comment by cweijan** [comment]
The result should really be cleared after executing the SQL, I'll fix it in the future.

**Comment by franklinkf** [comment]
Thank you Sir

**Comment by cweijan** [comment]
hi, I have fixed this in version 5.2.6.

**Comment by franklinkf** [comment]
Thanks a lot. Now works fine

**Comment by franklinkf** [comment]
Can you please consider the enhancement requested under

https://github.com/cweijan/vscode-database-client/issues/538#issuecomment-1117160411

**Comment by cweijan** [comment]
Hi, I didn't notice your  this comment, I will fix it in the next version.

**Comment by cweijan** [comment]
hi, I have [#538](https://github.com/cweijan/vscode-database-client/issues/538#issuecomment-1117160411) in 5.3.0.

**Comment by franklinkf** [comment]
Thank you very much Sir

It is perfect
