### ISSUE TITLE
Supporting redshift.

### ISSUE THREAD

**Issue by jdeheza69** [cweijan/vscode-mysql#539]
Client was closed and is not queryable

**Comment by jdeheza69** [comment]
I have a redshift database, it connect successfully, when I try to execute a query, show "Client was closed and is not queryable"

**Comment by cweijan** [comment]
redshift is not compatible with postgresql, this is caused by redshift not recognizing the dialect used by the extension。

**Comment by cweijan** [comment]
I added the support of redshift to the new version 5.2.1.
![image](https://user-images.githubusercontent.com/27798227/165014089-012857c8-0d98-4ec9-ab2f-4680a3c2d156.png)

**Comment by jdeheza69** [comment]
> I added the support of redshift to the new version 5.2.1. ![image](https://user-images.githubusercontent.com/27798227/165014089-012857c8-0d98-4ec9-ab2f-4680a3c2d156.png)

Thank you very much cweijan. I made a connection to Redshift database and it works perfectly. Just a simple detail, when I click on "Execute Sql", it is necessary to press "Stop Execute" to finish.

**Comment by jdeheza69** [comment]
> > I added the support of redshift to the new version 5.2.1. ![image](https://user-images.githubusercontent.com/27798227/165014089-012857c8-0d98-4ec9-ab2f-4680a3c2d156.png)
> 
> Thank you very much cweijan. I made a connection to Redshift database and it works perfectly. Just a simple detail, when I click on "Execute Sql", it is necessary to press "Stop Execute" to finish.

![Captura de Pantalla 2022-05-10 a la(s) 20 15 20](https://user-images.githubusercontent.com/53541180/167739833-ce1dd49b-c6c3-4ea9-836b-de000d1077b7.png)
