### ISSUE TITLE
[BUG]「设计表」编辑列之后，会把列的CHARACTER SET吞掉

### ISSUE THREAD

**Issue by zhangjiankui** [cweijan/vscode-mysql#540]
- OS: macos
- Database Type: mysql
使用「设计表」的功能，编辑了列，会把列原有的CHARACTER SET吞掉。
![image](https://user-images.githubusercontent.com/26133797/162363966-9b56a9a8-0c1f-46b7-ab1b-30079350520f.png)
![image](https://user-images.githubusercontent.com/26133797/162363995-03a826d9-e4da-4f26-9827-ed3793003d11.png)
如图，上图是原来的DDL，编辑列，仅修改列类型为varchar(256)之后，新DDL的CHARACTER SET被吞了

**Comment by cweijan** [comment]
Hi, 我在5.1.6版本做了字符集处理, 你试试看.
