### ISSUE TITLE
[BUG] user in database 

### ISSUE THREAD

**Issue by sennpy** [cweijan/vscode-mysql#541]
- OS: OSX
- Database Type: Postgres

I have a user table in my database and while the columns are being shown in the table exploration column, but when I open the table, it's showing me the database users and not my user table. 

The other features work for the table, just not the query and database explorer

**Comment by cweijan** [comment]
Sorry I didn't read your issue, what happened when you opened the table?

**Comment by Dysron** [comment]
You have to replace `user` in your query with `"user"` so that it knows you're referencing that users table and not the database users

**Comment by cweijan** [comment]
Thanks @Dysron, it works, I'm already wrapping in version 5.1.4.
