### ISSUE TITLE
Logging in with Github fails for VScode

### ISSUE THREAD

**Issue by Dysron** [cweijan/vscode-mysql#542]
- OS: Mac
- Database Type: Postgres

I purchased the premium version and followed these steps:
1. Log out of my account on the database-client.com website
2. Reload VScode

I was met with this message when attempting to log in with Github:
![image](https://user-images.githubusercontent.com/22123705/162588867-56f3aa0c-c8cb-4ecc-86b8-d81a6693de6b.png)

**Comment by cweijan** [comment]
If you are in a remote development environment, the login will fail, and you need to log in with a password.
![image](https://user-images.githubusercontent.com/27798227/162602238-36f6b1ba-49da-4d24-ba15-f7833a2ad4dc.png)
![image](https://user-images.githubusercontent.com/27798227/162602247-f58f6025-faa1-4619-9fa6-1f70cea091d6.png)

**Comment by Dysron** [comment]
Thanks that worked!

**Comment by igorfontenele** [comment]
I have the same issue and when I try to keep an empty password I get the message bellow 
<img width="350" alt="Screenshot 2022-11-21 at 21 05 21" src="https://user-images.githubusercontent.com/56636804/203182726-64b77038-df19-47b6-8500-c0b468059875.png">

**Comment by williamwallace79** [comment]
Hello everybody. I get a "Connect to account server fail!" error...
