### ISSUE TITLE
[BUG] Can't change active database.

### ISSUE THREAD

**Issue by silverbullettruck2001** [cweijan/vscode-mysql#543]
I am currently on 5.1.5 and it has stopped allowing me to change database by right clicking and clicking on `Change Active Database`.  When I click on `Change Active Database` it prompts for the server connection, but then it does not prompt for the databases on the server I want to select like it used to.  Can you please look into this so that this functionality can be restored?  Thanks!

- OS: MacOS
- Database Type: MySQL

**Comment by cweijan** [comment]
Thanks for your feedback, I recently refactored some old code that caused this problem, I will fix it in the next version.

**Comment by cweijan** [comment]
Hi, fix in version 5.1.6.
