### ISSUE TITLE
[BUG] Connect time out.

### ISSUE THREAD

**Issue by PetrusZ** [cweijan/vscode-mysql#544]
<img width="177" alt="image" src="https://user-images.githubusercontent.com/4990592/162772502-a0b65cf7-602e-4ae2-ac0b-620e5b7c8dea.png">

vscode输出：`2022-04-06 21:56:07 Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.`

redis是通过SSH隧道连接的。报错Connect time out后只能手动关闭连接后，再重新打开才能继续正常使用。

- OS: macos
- Database Type: redis

**Comment by cweijan** [comment]
显示连接超时可以点刷新按钮来重连, 同时你看下扩展版本是不是最新的5.1.5, 旧版本有连接bug, 可能是你还没用最新版本.
![image](https://user-images.githubusercontent.com/27798227/162857088-67ac854d-a7f1-463b-b55c-9d1feff7fec7.png)

**Comment by PetrusZ** [comment]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/4990592/162997859-257fbcd5-9c20-4057-9024-1e7a9fd4d7ba.png">

已经升级到5.1.5了，依旧有bug，而且点击刷新还是不能重连。

**Comment by cweijan** [comment]
我试了几次都没发现这个问题呢, 你用别的工具可以连接吗.

**Comment by PetrusZ** [comment]
成功连接后放了一段时间后就出了这个问题。我用tableplus试下，晚点反馈结果。

另外我还遇到了另外一个问题，不知道是不是跟5.1.6有关系，但之前是的确没有这个问题的，今天刚刚发现。
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/4990592/163133686-818f4bc1-89f3-4019-bced-22d4daeb87fd.png">
连接mysql数据成功，但无法在左侧打开数据库。

**Comment by cweijan** [comment]
可能和你的redis连接有关系, 或许网络不太稳定.
第二个问题我也遇到过, 这是vscode的bug, 你点击上方的刷新按钮让他重新加载.

**Comment by PetrusZ** [comment]
第二个问题点了刷新没用呢，点过好多遍了。

**Comment by cweijan** [comment]
@PetrusZ 那可能是你的mysql里面没有数据库, 尝试切换这个选项.
![image](https://user-images.githubusercontent.com/27798227/163144087-419d11ac-9ccc-479b-bd1a-eef09dc47f01.png)

**Comment by PetrusZ** [comment]
有的啊，不是这些低级错误，切换了这个选项也没有用。我前两天还用的好好的呢。这两天我记得的唯一变化就是升级了扩展的版本，从不知道多少，升级到5.1.6。

**Comment by PetrusZ** [comment]
看了一下我上次发issue时的版本是4.7.8，有可能是从这里升级过来的。

**Comment by cweijan** [comment]
那你这好久没更新了, 尝试把旧的删除掉, 重新连接下.

**Comment by PetrusZ** [comment]
好的，删除以前的连接的确解决了这个问题。

**Comment by PetrusZ** [comment]
tableplus上redis也是通过ssh隧道连接，挂了一天，也没有出现类似connect time out或重试次数太多无法连接的问题。

**Comment by cweijan** [comment]
你这个连接稳定吗, 现在这个扩展如果连接超过5秒会不断重试, 可能是这个导致的.

**Comment by PetrusZ** [comment]
我想起来SSH的确因为NAT的问题不太稳定，但是我在.ssh/config中添加了配置`ServerAliveInterval 60`解决了该问题。也许扩展在通过SSH连接时也需要类似的功能。但我ES也是通过SSH隧道连接的，就没有碰到该问题。

**Comment by cweijan** [comment]
我是指连接会不会很久, 我会在下版本取消超时重试功能.

**Comment by PetrusZ** [comment]
是会很久，我不确定取消这个功能是不是一个好主意

**Comment by cweijan** [comment]
Hi, 我在5.1.8版本中取消了自动重试功能. 另外, 你的连接比较慢的话调整一下Connect Timeout.
![image](https://user-images.githubusercontent.com/27798227/163908485-ffa9c970-075e-4368-9059-9c723f906af1.png)
