### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by silverbullettruck2001** [cweijan/vscode-mysql#545]
On version 5.1.5 it opens up the `Payment Instructions` tab and popups a notification saying `Free account not support table source!` just by hovering over a table name.  No clicking, just hovering.  Could you make it so that it only does that if you try to view the table source as it is pretty disruptive to prompt for that when you aren't even trying to use the feature.

- OS: MacOS
- Database Type: MySQL

**Comment by cweijan** [comment]
This really shouldn't pop up, my intention is to show a tooltip.

**Comment by icecream8086** [comment]
having similar trouble

**Comment by cweijan** [comment]
Fixed in version 5.1.6.
