### ISSUE TITLE
希望能够通过配置参数关闭sql文件的自动格式化

### ISSUE THREAD

**Issue by msdemt** [cweijan/vscode-mysql#546]
我发现使用插件后，在编辑sql文件，保存时会自动进行格式化，希望有参数能关闭保存时自动格式化

**Comment by cweijan** [comment]
没有把, 这个扩展只是提供了格式化功能, 自动格式化应该是你自己设置的.

**Comment by msdemt** [comment]
vscode 开启了保存时自动进行格式化，我不希望保存时自动格式化sql文件，这个格式化sql文件的功能是这个插件实现的，希望能有配置关闭这个插件的sql格式化功能

**Comment by cweijan** [comment]
你自己配置自动格式化时别格式化SQL就行了.

**Comment by msdemt** [comment]
vscode里的自动格式化配置中，没找到指定忽略sql文件的配置。。。

**Comment by cweijan** [comment]
stackoverflow了解一下, https://stackoverflow.com/a/44831631/8872638
```json
"[sql]": {
    "editor.formatOnSave": false
}
```

**Comment by msdemt** [comment]
> stackoverflow了解一下, https://stackoverflow.com/a/44831631/8872638
> 
> ```json
> "[sql]": {
>     "editor.formatOnSave": false
> }
> ```

感谢！！(●'◡'●)
