### ISSUE TITLE
[BUG]Redis 键值显示不全，

### ISSUE THREAD

**Issue by pro911** [cweijan/vscode-mysql#547]
- OS: win11 x64 am dcpu   vscode:version1.66.1  插件version 5.1.6
- Database Type: Redis
- 
![image](https://user-images.githubusercontent.com/28957658/162936336-22322bf3-6d72-4e3d-b011-2e8b982ce01b.png)
![image](https://user-images.githubusercontent.com/28957658/162936562-b60098ec-87f4-4799-a9e1-2521f4227cfc.png)

**Comment by cweijan** [comment]
Hi, 这是为了加快速度, 目前每次只会加载3000条, 点击更多可以加载更多.
![image](https://user-images.githubusercontent.com/27798227/162943703-6968aecb-44c1-4343-99df-88905044b1af.png)

**Comment by pro911** [comment]
点击了加载更多，依然无法出现。但是在RESP客户端上是可以的。
![image](https://user-images.githubusercontent.com/28957658/162950024-13909d3d-9d95-400d-8923-c341f0594093.png)

**Comment by pro911** [comment]
点击了加载更多依然无效。
![image](https://user-images.githubusercontent.com/28957658/162950247-5d37845f-ac13-4260-ae0c-19a5d17491f3.png)

**Comment by cweijan** [comment]
现在是每次加载3000条数据, 你100多w条得点很多次呢, 等之后的版本我增加个选项来调整每次的分页数量.

**Comment by pro911** [comment]
好的！希望可以加到前缀`user:`  上，`user:login:` 刷新单个也挺好。

**Comment by cweijan** [comment]
发布了新版本5.1.8, 现在可设置每次加载的key数量, 默认为1万.
![image](https://user-images.githubusercontent.com/27798227/163905820-a67538cc-8643-41a6-ad6a-c6b789ecb84a.png)
