### ISSUE TITLE
[clickhouse] auto complete not working when using schema.  

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#548]
hi.
auto complete not working when using schema.  

![Animation](https://user-images.githubusercontent.com/6413705/163250305-ce2b6687-11b3-4c8b-9389-8b1c4b613277.gif)

**Comment by cweijan** [comment]
It looks like you are not using the latest version.

**Comment by mbtolou** [comment]
I am using version v5.1.6.
this problem only appears on Clickhouse scripts!
with Postgres schema work correctly.

**Comment by cweijan** [comment]
Fixed in version 5.1.7.
