### ISSUE TITLE
以前打开table的时候 有个按钮是在新窗口打开table, 现在怎么没了.每次打开table都是覆盖掉原来的

### ISSUE THREAD

**Issue by neozxy** [cweijan/vscode-mysql#549]

**Comment by neozxy** [comment]
open new panel

**Comment by cweijan** [comment]
现在默认隐藏了, 可通过勾选这个选项显示.
![image](https://user-images.githubusercontent.com/27798227/163310387-baa15c99-0401-451a-89ba-2f0150e84e02.png)
