### ISSUE TITLE
无法手动增删table

### ISSUE THREAD

**Issue by Tracker647** [cweijan/vscode-mysql#551]
![GIF](https://user-images.githubusercontent.com/54085641/163320681-39dd77e8-d0e3-4046-b5f5-833778aaeca2.gif)

**Comment by Tracker647** [comment]
![GIF](https://user-images.githubusercontent.com/54085641/163321041-03956629-80eb-4640-b34b-8c9912cb5e63.gif)

**Comment by cweijan** [comment]
这是什么类型的数据库呢, 应该是因为首名字大写导致的错误.

**Comment by cweijan** [comment]
删除数据的是要求表必须有主键. 

添加数据的话, 你先试下激活数据库面板, 你这个是新建的, 我用了缓存的数据, 这里加载不到, 我会在后续版本优化.
