### ISSUE TITLE
表名右侧的「新tab查询」按钮换成了「新建列」，希望换回来

### ISSUE THREAD

**Issue by zhangjiankui** [cweijan/vscode-mysql#552]
当前的版本是5.1.6。发现之前的「新tab查询」按钮换成「新建列」按钮。
![image](https://user-images.githubusercontent.com/26133797/163405967-a016cf86-fff4-4c8f-af0c-9bb23ba29346.png)
之前的打开新tab查询窗口的按钮更常用，「新建列」反而很少能用上。
而且现在也找不到能新建tab查询的方式了。希望能将之前的按钮换回来。

**Comment by zhangjiankui** [comment]
找到了在配置页了可以勾选出来

**Comment by cweijan** [comment]
嗯, 我在新版本隐藏了新标签, 这个按钮其实是给少数用户服务的, 多数人用不到.
