### ISSUE TITLE
[BUG] Cannot edit a field when displayed value is same as current value

### ISSUE THREAD

**Issue by michaelthoreau** [cweijan/vscode-mysql#553]
- OS: mac
- Database Type: sqlite

Steps to reproduce:
1.    select * from table;
2.   (update a field via python)
3.    type in a field in table view (reflecting data before update)
4.     press return .... no result

Seems like you cannot edit a field to be the same value that it currently shows (even if it is different in the database)

**Comment by cweijan** [comment]
Yes, editing will only happen if the data is different from the previous data.

**Comment by michaelthoreau** [comment]
If this is as-intended, lets close the issue?
