### ISSUE TITLE
[BUG]Can't see all databases when I leave the show database field blank

### ISSUE THREAD

**Issue by greysave** [cweijan/vscode-mysql#554]
- OS:  macOS
- Database Type: Postgres

I have an instance of Postgres where I can see all of the databases.  Using the exact same settings trying to connect to the same database, when I leave the show databases blank no databases show up.  I have tried this on several computers.

**Comment by cweijan** [comment]
Thanks for your feedback, this is a known bug, I have released version 5.1.7 to fix it.
