### ISSUE TITLE
Color Code Groups

### ISSUE THREAD

**Issue by queejie** [cweijan/vscode-mysql#555]
We recently moved from JetBrains IDE's to VS Code, and I just purchased a license for this extension.  Thank you!  

One of the nice things about the database tool in JetBrains (and NaviCat) is the ability to set the background colors for connections.  That way I can mark production with a red/pink background, staging with orange, and dev with green.  It can save some serious mistakes.  Wondering if you might be able to add that feature.  I think it would be helpful to others as well

![tmp](https://user-images.githubusercontent.com/1616827/164089874-e2bad618-b66f-4d36-b0bb-6791a7893543.jpg)
.

**Comment by cweijan** [comment]
Hi, thank you for your support, VSCode does not support changing the background color of tree nodes.

For the connection in the production environment, you can consider modifying the group of the connection and setting the connection to readonly. After you create a group, you can modify the group of the connection by dragging and dropping.
![image](https://user-images.githubusercontent.com/27798227/164161125-38612b83-5e5b-47a6-b3e6-869a8a08323c.png)

**Comment by queejie** [comment]
I know you don’t support it, currently.  That’s why it was a feature request.  I’m hoping you will consider it, in the future.

Thank you,
-dqj

David Quinn-Jacobs, M.S. |  Chief Technology Officer
PLS 3rd  Learning
Educators elevated.
678 Main Street, Buffalo, New York 14202
Mobile: 607.227.7351
***@***.******@***.***>  |  PLS3rdLearning.com<http://www.pls3rdlearning.com/>

On Apr 20, 2022, at 2:03 AM, WeiJian Chen ***@***.******@***.***>> wrote:



Hi, thank you for your support, VSCode does not support changing the background color of tree nodes.

For the connection in the production environment, you can consider modifying the group of the connection and setting the connection to readonly. After you create a group, you can modify the group of the connection by dragging and dropping.
[image]<https://user-images.githubusercontent.com/27798227/164161125-38612b83-5e5b-47a6-b3e6-869a8a08323c.png>

**Comment by cweijan** [comment]
Hi, although this is indeed a worthwhile proposition.

However, the background color of the highlighted node will not conform to the design style of vscode. I don't think the vscode team will develop this feature in the future.

Instead, you should consider grouping connections or setting connection names.

If the vscode team supports setting the background color in the future, I will implement it😊.
