### ISSUE TITLE
multiple tab

### ISSUE THREAD

**Issue by u007** [cweijan/vscode-mysql#556]
hi, 

is it possible to reintroduce back new tab?
very difficult for me to check multilpe issues with same table

thank you

**Comment by cweijan** [comment]
Hi, you can check this option.
![image](https://user-images.githubusercontent.com/27798227/164281740-be5e03eb-5f4a-4ce9-a06d-08dda9bc7e78.png)

**Comment by u007** [comment]
ohh didnt know have these options. thank you
