### ISSUE TITLE
[BUG] Get socket hang up issue when I am trying to connect to Clickhouse

### ISSUE THREAD

**Issue by EliranRe** [cweijan/vscode-mysql#557]
Hi,

I am new to the extension.
I am trying to connect to ClickHouse, and I get error connection:
"socket hang up"

- OS: Windows 10
- Database Type: ClickHouse

**Comment by cweijan** [comment]
This error means that the program is not connected to the clickhouse network, you should check your firewall.

**Comment by EliranRe** [comment]
I can connect trough DBeaver to Clickhouse on my PC.
So I dont think it's firewall.

**Comment by cweijan** [comment]
Sorry, I read it wrong, "socket hang up" means the server refused the client's connection.
"socket hang up" is a generic error, I can think of several possibilities to cause this error:
1. Your user password is wrong
2. Your clickhouse service is https.

Need to look at clickhouse's error log to locate what's really happening.

**Comment by EliranRe** [comment]
The service is https, What can I do to connect?

**Comment by cweijan** [comment]
I think I need to upgrade the client to support https, please wait for a future version.

**Comment by EliranRe** [comment]
Thanks a lot!

**Comment by cweijan** [comment]
The use of https protocol is supported in the latest version 5.2.2.
![image](https://user-images.githubusercontent.com/27798227/165433177-8a0911c5-8cf1-4582-b889-c768567acb53.png)

**Comment by EliranRe** [comment]
It works thanks!
I will do subscription

**Comment by cweijan** [comment]
Thank's for your support.
