### ISSUE TITLE
Schema filter

### ISSUE THREAD

**Issue by aar0nsky** [cweijan/vscode-mysql#558]
I connect to a server with many databases and inside them many many schemas. I have not found a way to only show selected schemas for a given database name.

**Comment by cweijan** [comment]
I don’t support it yet, I will support it in the future.

**Comment by cweijan** [comment]
Supported in version 5.2.2.
![image](https://user-images.githubusercontent.com/27798227/165433053-b4d2ea10-3a03-42ad-a850-25cda0e8076e.png)
