### ISSUE TITLE
[BUG] Client was closed and is not queryable

### ISSUE THREAD

**Issue by aar0nsky** [cweijan/vscode-mysql#559]
- OS: MAC OS Catalina 10.15.7
- Database Type: Postgres(greenplum)

I am getting this error when trying to view any of the tables or views of schemas in this database connection. I am using the generic postgresql driver in DBeaver with the same connection details without issue.

**Comment by aar0nsky** [comment]
this may be a duplicate of https://github.com/cweijan/vscode-database-client/issues/539 but I am not querying redshift just postgres driver should work.

**Comment by cweijan** [comment]
Try connect by redshift, I use the set schema statement in postgresql, it seems that greenplum does not support this statement..
![image](https://user-images.githubusercontent.com/27798227/165125526-58e2f9c8-be99-4096-87f9-519bef1a8224.png)
