### ISSUE TITLE
how to pay?

### ISSUE THREAD

**Issue by jinzishuai** [cweijan/vscode-mysql#560]
There is a mention of paid/premium versions but I haven't seen any information on how to get on the paid version. Thanks

**Comment by cweijan** [comment]
Please check out this issue, https://github.com/cweijan/vscode-database-client/issues/542.
This is a website to buy premium https://database-client.com/#/.

**Comment by ruslaniv** [comment]
This site is down. The issue you linked has no information on how to pay whatsoever.

**Comment by cweijan** [comment]
Hi @ruslaniv, please check out this issue #676.
