### ISSUE TITLE
[BUG] Message displayed in Chinese instead of English

### ISSUE THREAD

**Issue by silverbullettruck2001** [cweijan/vscode-mysql#562]
When executing a statement that returns no results it displays Chinese instead of English (`暂无数据` instead of 
`No data available`)  Can you make it return the proper translation based on the culture language settings?  Here is a screenshot:
![image](https://user-images.githubusercontent.com/26559157/165347847-9ef154e7-7bff-4d86-8784-26f36b33d2e5.png)

- OS: MacOS
- Database Type: mysql

**Comment by cweijan** [comment]
The rendering data of the table doesn't have i18n built in, and it's out of maintenance, which means I can't modify it.

**Comment by silverbullettruck2001** [comment]
what component/library is out of maintenance?

**Comment by cweijan** [comment]
Table is render by [umy-ui](https://github.com/u-leo/umy-ui), but it doesn't matter, I will remove the no data prompt in the next version.

**Comment by cweijan** [comment]
Empty data tips have been removed from the latest version 5.2.2.
