### ISSUE TITLE
[BUG] Postgres tree view flooded with temp table schemas

### ISSUE THREAD

**Issue by gaberoffman** [cweijan/vscode-mysql#564]
- OS: Mac
- Database Type: Postgres

With the latest release, I'm now seeing all of these temp schemas in my Postgres tree view.  It is not useful to see them and totally overwhelms seeing the public schemas.

![Untitled](https://user-images.githubusercontent.com/2151662/165524176-aeffd1a7-506e-4d5d-90b6-bf8a0ebdfa9a.png)

**Comment by cweijan** [comment]
I did modify the query method of schemas in the new version, do you know how these temporary schemas are generated?
You can use the filter schema function to display what you need.
![image](https://user-images.githubusercontent.com/27798227/165526078-65a25ca3-0fe6-46c0-b883-55ebda96883f.png)

**Comment by gaberoffman** [comment]
I do not know how the schemas are generated.  But a query of 
`SELECT *
FROM pg_namespace
`
shows they all have a nspowner of 10 which must be an internal owner since it must be set up at install.  Unlike schemas that were made by us where the nspowner is 5 digits.

![Screen Shot 2022-04-27 at 10 03 00 AM](https://user-images.githubusercontent.com/2151662/165536670-2eb3ce25-ad07-45cc-bcf3-9c0f48896720.png)

**Comment by gaberoffman** [comment]
according to the pg_user table, this is a user created by our hosting provider, compose.io.  So this is specific to our setup so I'll close this ticket.  Just wondering if there is a permissions level or something that was preventing these from showing up in your previous schema that would be easy to add as an option to "hide private schemas" or something like that
