### ISSUE TITLE
defaultSelectLimit not limiting results [BUG]

### ISSUE THREAD

**Issue by silverbullettruck2001** [cweijan/vscode-mysql#565]
Maybe I am misunderstanding the setting, but I have the `defaultSelectLimit` config setting set to `5000` but when I do a `SELECT` statement and the table contains more than `5000` records, it returns all records instead of limiting it to only `5000` records.  Please let me know if I am misunderstanding the purpose of this setting.  Thanks!

- OS: mac
- Database Type: mysql

**Comment by cweijan** [comment]
No, this is just to set the data that will be loaded by default when the table is clicked.
![image](https://user-images.githubusercontent.com/27798227/165660057-62f8d096-ed88-4979-9938-694183df5de3.png)
