### ISSUE TITLE
mysql USE statement not working [BUG]

### ISSUE THREAD

**Issue by silverbullettruck2001** [cweijan/vscode-mysql#566]
If I connect to a mysql database, let's call it `database_a` and on the same server it also has `database_b`.  On both databases there is a table called `myUsers`.  The tables are completely separate and contents are different.

I connect to `database_a` and run the following statements together as one selected statement:

```
use database_b;
select * from myUsers;
```

What I expect is the results of `myUsers` from `database_b` but instead, what I get back are the results from `database_a`.  It seems like it's not respecting the `USE` statement syntax for MySQL.

- OS: mac
- Database Type: mysql

**Comment by cweijan** [comment]
This is considering the performance of the database. MySQL only uses one connection to manage all databases. When you switch the active database or use a query file, it will automatically execute a use statement before executing SQL.

**Comment by cweijan** [comment]
If you are only in the same SQL file and don't switch the active database, it won't cause this problem, so I'm not going to change this.

**Comment by silverbullettruck2001** [comment]
bummer.  It's convienent if you are changing tables across many databases on the same server to be able to quickly run one statement rather than having to constantly switch between databases between each execution.  It'd be great if there was someway to do this quicker on large database servers.

**Comment by cweijan** [comment]
Hi, I have released version 5.4.7 which supports binding connections to sql files, I think it can solve your problem.
![image](https://user-images.githubusercontent.com/27798227/175344937-26450d94-ab9c-4fee-9649-2f23bbbcde13.png)
