### ISSUE TITLE
[BUG] when entering data on row level, scrolling horizontally will scramble up the cells and positioned wrongly with header

### ISSUE THREAD

**Issue by u007** [cweijan/vscode-mysql#567]
- OS: popos 21.10
- Database Type: postgresql

**Comment by cweijan** [comment]
I don't understand what you are talking about, you need to provide screenshots. 

If you are editing long texts, I suggest you right click row and choose `open edit dialog`.

**Comment by u007** [comment]
entering group_id, 

![2022-04-28_14-34](https://user-images.githubusercontent.com/388813/165691871-c906db62-d04b-4d96-a53f-0944d1876b8c.png)

when scroll to the right, it shifted to the left column

![2022-04-28_14-34_1](https://user-images.githubusercontent.com/388813/165692010-4f0f6763-a1b6-4c1f-a141-db36914ff2b0.png)

**Comment by cweijan** [comment]
Try the following extension, the focus of the cell will be removed after rolling in the latest version, I think you have used outdated extensions.
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2

**Comment by u007** [comment]
ive installed this package and im not logged in
when i login, it states my account is not paid , but ive paid for the other extension (mysql client extension), can you help me to check under james@mercstudio.com?

**Comment by cweijan** [comment]
If you are using an old version of the extension,  it will not be able to parse the data returned by the current login server, please stop using the old version of the extension.

**Comment by u007** [comment]
hi, which one is new? im confused

**Comment by cweijan** [comment]
Sorry, this issue you mentioned makes me think you are using an older version, if you are using [mysql](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2), then it is up to date.

Now back to the issue, you provided two screenshots, but each row of data is the same, I don't see where the error is.

**Comment by u007** [comment]
hi, it stil happen on the mysql extension

**Comment by cweijan** [comment]
But in the screenshot you provided, the data is the same. I think I didn't understand your issue.
![image](https://user-images.githubusercontent.com/27798227/165872723-baab3188-a1bc-48b6-b5b9-fac27349a7d5.png)

**Comment by u007** [comment]
yes same , but the group_id can see moved to created_at column when scroll

**Comment by cweijan** [comment]
Everything works fine for me here, and the screenshot you provided doesn't indicate this.

**Comment by cweijan** [comment]
I found this problem, it only happens on new row.

**Comment by cweijan** [comment]
hi, I have fixed this in version 5.2.6.

**Comment by u007** [comment]
thank you :+1:

**Comment by u007** [comment]
oh sorry got the credit back

**Comment by u007** [comment]
hi

paypal charged twice to my card even thou its not successful

**Comment by cweijan** [comment]
Hi, I have not received any payment so far. Try to contact paypal's official phone number.

**Comment by cweijan** [comment]
https://www.paypal.com/c2/smarthelp/contact-us

**Comment by u007** [comment]
hi

no worries, it was refunded as "credit"

best regards,
James Tan
Merc Studio
eMail: ***@***.***
www: www.mercstudio.com

**Comment by u007** [comment]
hi

my plan still on free
<img width="1025" alt="Screenshot 2022-10-12 at 12 01 14 AM" src="https://user-images.githubusercontent.com/388813/195142527-d669cf9b-83f0-4c18-a1f0-a0cba3a847f1.png">


best regards,
James Tan
Merc Studio
eMail: ***@***.***
www: www.mercstudio.com

**Comment by cweijan** [comment]
My email is cweijan@163.com Please send it here with your email and let me check your account.
