### ISSUE TITLE
duplicate record

### ISSUE THREAD

**Issue by u007** [cweijan/vscode-mysql#568]
hi,

it would be lovely to have ways to duplicate a row and let us modify before inserting

thank you

**Comment by cweijan** [comment]
Hi, right click row and choose open copy dialog.
![image](https://user-images.githubusercontent.com/27798227/165690216-0e112dc4-8e73-4bfc-bd8f-f051ffdf2dad.png)

**Comment by u007** [comment]
ohh nice thank you
