### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by izzycode** [cweijan/vscode-mysql#569]
- OS: WSL2 / Ubuntu / Windows 10
- Database Type: MySQL & Postgres

Attempted to login via Github and got same error as [Issue #542](https://github.com/cweijan/vscode-database-client/issues/542).
![Screenshot 2022-04-28 115106](https://user-images.githubusercontent.com/16438391/165793705-5f36a1ff-b310-4359-a185-3ac893e552eb.png)
Next I tried leaving passwords blank as suggested in Issue #542 resolution and got this error:
![Screenshot 2022-04-28 115320](https://user-images.githubusercontent.com/16438391/165793906-3d92d725-62dd-46f2-8fed-42a62813a64e.png)
Next I tried changing the password and got this error:
![Screenshot 2022-04-28 115343](https://user-images.githubusercontent.com/16438391/165793997-478eb22d-0ed4-4ad2-829e-8422f235d7eb.png)

I wonder if there's a way of changing the login method from github to email/password. 
Appreciate any help.

**Comment by cweijan** [comment]
Hi, keep current password empty, new password is not empty.

**Comment by cweijan** [comment]
![image](https://user-images.githubusercontent.com/27798227/165871076-183271b4-6235-467c-aed3-f8492f1e4441.png)
