### ISSUE TITLE
sql数据导出XLSX时候设置在第二个sheet加上查询的sql

### ISSUE THREAD

**Issue by 1092522920** [cweijan/vscode-mysql#570]
sql数据导出XLSX时候设置在第二个sheet加上查询的sql,这对业务运维人员特别重要,可以通过xlsx文件查到当时的查询方法,可以参照datagrip的功能,
![image](https://user-images.githubusercontent.com/65692318/165882690-0b0da914-9b7e-4816-804c-bbfd6bdef3db.png)

**Comment by cweijan** [comment]
确实是个不错的功能, 我会在下版本实现.

**Comment by cweijan** [comment]
已发布5.2.4版本, 现在会将sql填充到第二个sheet
