### ISSUE TITLE
充值后链接不稳定,特别慢

### ISSUE THREAD

**Issue by 1092522920** [cweijan/vscode-mysql#571]
充值前,链接还是挺稳定的,充值之后,打开vscode,加载数据库特别慢,一直转圈圈,换台电脑也这样,重启vscode不知道是为什么
![image](https://user-images.githubusercontent.com/65692318/165891090-3dbac79b-d582-44f9-9a05-d433dc5c0cb5.png)

**Comment by cweijan** [comment]
看日志是报错了, 试下把连接删除掉重新连接, 还有问下你安装的是哪个扩展.

**Comment by 1092522920** [comment]
我试试重新建链接,扩展是这个






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cweijan/vscode-database-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月29日(星期五) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cweijan/vscode-database-client] 充值后链接不稳定,特别慢 (Issue #571)





 
看日志是报错了, 试下把连接删除掉重新连接, 还有问下你安装的是哪个扩展.

**Comment by 1092522920** [comment]
我的数据库是阿里云分析型数据库mysql版,官网是这个云原生数据仓库AnalyticDB MySQL版 (aliyun.com),兼容mysqljdbc驱动,同一台电脑,用navicat,datagrip,dbeaver都可以,用咱们的插件就链接不上,能看下啥情况吗,下面是datagrip的驱动版本








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cweijan/vscode-database-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月29日(星期五) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cweijan/vscode-database-client] 充值后链接不稳定,特别慢 (Issue #571)





 
看日志是报错了, 试下把连接删除掉重新连接, 还有问下你安装的是哪个扩展.

**Comment by cweijan** [comment]
你要看下你的连接配置是否一样，错误的信息你也没给出





--
发自我的网易邮箱手机智能版



在 2022-05-01 11:35:16，1092522920 ***@***.***> 写道：


我的数据库是阿里云分析型数据库mysql版,官网是这个云原生数据仓库AnalyticDB MySQL版 (aliyun.com),兼容mysqljdbc驱动,同一台电脑,用navicat,datagrip,dbeaver都可以,用咱们的插件就链接不上,能看下啥情况吗,下面是datagrip的驱动版本








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cweijan/vscode-database-client" ***@***.***&gt;;
发送时间:&nbsp;2022年4月29日(星期五) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cweijan/vscode-database-client] 充值后链接不稳定,特别慢 (Issue #571)






看日志是报错了, 试下把连接删除掉重新连接, 还有问下你安装的是哪个扩展.

**Comment by 1092522920** [comment]
配置信息完全一样,测试链接也是成功的,不报错,就是一直转圈,就很奇怪,也不知道啥原因,我主要想知道,这个是插件适配的问题,还是说数据库有啥特殊的要求,看看怎么弄才能不转圈了







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cweijan/vscode-database-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月1日(星期天) 下午3:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cweijan/vscode-database-client] 充值后链接不稳定,特别慢 (Issue #571)





 你要看下你的连接配置是否一样，错误的信息你也没给出
 
 
 
 
 
 --
 发自我的网易邮箱手机智能版
 
 
 
 在 2022-05-01 11:35:16，1092522920 ***@***.***&gt; 写道：
 
 
 我的数据库是阿里云分析型数据库mysql版,官网是这个云原生数据仓库AnalyticDB MySQL版 (aliyun.com),兼容mysqljdbc驱动,同一台电脑,用navicat,datagrip,dbeaver都可以,用咱们的插件就链接不上,能看下啥情况吗,下面是datagrip的驱动版本
 
 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "cweijan/vscode-database-client" ***@***.***&amp;gt;;
 发送时间:&amp;nbsp;2022年4月29日(星期五) 下午2:11
 ***@***.***&amp;gt;;
 ***@***.******@***.***&amp;gt;;
 主题:&amp;nbsp;Re: [cweijan/vscode-database-client] 充值后链接不稳定,特别慢 (Issue #571)
 
 
 
 
 
 
 看日志是报错了, 试下把连接删除掉重新连接, 还有问下你安装的是哪个扩展.

**Comment by cweijan** [comment]
协议兼容的话那肯定是可以连的，你试下勾选use ssl





--
发自我的网易邮箱手机智能版



在 2022-05-01 16:08:46，1092522920 ***@***.***> 写道：


配置信息完全一样,测试链接也是成功的,不报错,就是一直转圈,就很奇怪,也不知道啥原因,我主要想知道,这个是插件适配的问题,还是说数据库有啥特殊的要求,看看怎么弄才能不转圈了







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cweijan/vscode-database-client" ***@***.***&gt;;
发送时间:&nbsp;2022年5月1日(星期天) 下午3:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cweijan/vscode-database-client] 充值后链接不稳定,特别慢 (Issue #571)





你要看下你的连接配置是否一样，错误的信息你也没给出





--
发自我的网易邮箱手机智能版



在 2022-05-01 11:35:16，1092522920 ***@***.***&gt; 写道：


我的数据库是阿里云分析型数据库mysql版,官网是这个云原生数据仓库AnalyticDB MySQL版 (aliyun.com),兼容mysqljdbc驱动,同一台电脑,用navicat,datagrip,dbeaver都可以,用咱们的插件就链接不上,能看下啥情况吗,下面是datagrip的驱动版本








------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人: "cweijan/vscode-database-client" ***@***.***&amp;gt;;
发送时间:&amp;nbsp;2022年4月29日(星期五) 下午2:11
***@***.***&amp;gt;;
***@***.******@***.***&amp;gt;;
主题:&amp;nbsp;Re: [cweijan/vscode-database-client] 充值后链接不稳定,特别慢 (Issue #571)






看日志是报错了, 试下把连接删除掉重新连接, 还有问下你安装的是哪个扩展.

**Comment by cweijan** [comment]
现在连接还正常吗
