### ISSUE TITLE
[BUG] does not work with code-server with safari

### ISSUE THREAD

**Issue by myneid** [cweijan/vscode-mysql#573]
- OS: macos
- Database Type:mysql

this extension when installed in code-server does not work in safari. when i click plus the connect tab opens but the page is blank. it does work fine in chrome

**Comment by cweijan** [comment]
Thanks for the feedback, I will try to fix this.

**Comment by cweijan** [comment]
Hi, tried version 5.2.9, I did some compatibility code, but I'm not sure if it will work. (I don't have a mac).

**Comment by cweijan** [comment]
Hi, this issue is caused by the security restrictions of vscode, extensions using webview will only work when you use localhost or https to access.
https://github.com/microsoft/vscode/issues/146045

**Comment by myneid** [comment]
i use only localhost with code-server. i tried https as well with localhost.
the error that i am getting is
SyntaxError: Invalid regular expression: invalid group specifier name in app.js on line 2. it is difficult since it is minimized to see where the issue lies.

**Comment by cweijan** [comment]
Thanks for your feedback, I'm still having trouble locating this issue.

**Comment by myneid** [comment]
if there is a way that i can un-minimize that app.js and run it in there, let me know. perhaps i can find the line with the issue. it works great in any other browser, just not safari (and so will not work on my ipad)

**Comment by cweijan** [comment]
Hi, I packaged an extension without minification, you can try it (change the suffix from zip to vsix).
[vscode-mysql-client2-5.3.0.zip](https://github.com/cweijan/vscode-database-client/files/8741933/vscode-mysql-client2-5.3.0.zip)

**Comment by myneid** [comment]
the error is on line 6190
  const srvRegex = /(?<=mongodb\+).+?(?=:\/\/)/;

from stackoverflow, it seems that safari does not support look behind
https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

**Comment by cweijan** [comment]
Thanks, very helpful, I will fix it in the next version.

**Comment by cweijan** [comment]
I packaged a new version with this regex removed.
[vscode-mysql-client2-5.3.0.zip](https://github.com/cweijan/vscode-database-client/files/8742276/vscode-mysql-client2-5.3.0.zip)

**Comment by myneid** [comment]
this works! thank you
