### ISSUE TITLE
Support for nosql view

### ISSUE THREAD

**Issue by lit26** [cweijan/vscode-mysql#574]
This extension is great for sql database. Can this extension add a view for nosql data (pretty formatting, ex: https://codemirror.net/)

**Comment by cweijan** [comment]
What is the nosql data you are referring to? And I don't understand the connection between the view and the codemirror.

**Comment by lit26** [comment]
I am using mongoDb. For some cells, maybe json format is more readable with line breaks (https://codemirror.net/mode/javascript/json-ld.html). Codemirros is just a package that will format the code for the frontend (implement suggestion).

**Comment by cweijan** [comment]
Try click this button.
![image](https://user-images.githubusercontent.com/27798227/167247237-3646113a-a401-4e4e-a6bc-4df251278137.png)

**Comment by lit26** [comment]
Yup, I mean the code in `Open Edit Dialog` and `Open Copy Dialog` in Preview. Currently, I think it is just one line.

**Comment by cweijan** [comment]
Ok, I will consider using codemirror in the dialog in the future.

But I need to remind that this extension does not support mongodb very well, you should consider using the mongodb official extension.
https://marketplace.visualstudio.com/items?itemName=mongodb.mongodb-vscode

**Comment by lit26** [comment]
I know this extension and I didn't feel that is better. I personally like yours (UI part). Codemirror is just a suggestion and/or sample.

**Comment by cweijan** [comment]
Already supported in version 6.3.1, columns can be edited within Codemirror by clicking the button next to them.
![image](https://user-images.githubusercontent.com/27798227/228460326-ce942081-6f9e-4b7e-9363-0c453113df87.png)
