### ISSUE TITLE
Bad schemas in PostgreSQL database [BUG]

### ISSUE THREAD

**Issue by heptau** [cweijan/vscode-mysql#576]
- OS: Linux (Ubuntu edge)
- Database Type: PostgreSQL  (12.6 and 13.5)
- VSCode: 
        Version: 1.67.0
        Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
        Date: 2022-05-04T12:08:42.978Z
        Electron: 17.4.1
        Chromium: 98.0.4758.141
        Node.js: 16.13.0
        V8: 9.8.177.13-electron.0
        OS: Linux x64 5.4.0-109-generic snap
- Extension: Database Client v5.2.4

If I add a server with multiple databases that have different schemas, the schemas used in the database that is listed in the connection string or from the first database are always displayed (if there is no database in the connection string). I tried refresh, but it doesn't help either.

**Comment by cweijan** [comment]
If you need to operate multiple databases, don't use connection string. When you use connection string, the program cannot know which database you need to use.
