### ISSUE TITLE
[BUG]调整表中字段顺序导致字段属性错误丢失

### ISSUE THREAD

**Issue by pinyht** [cweijan/vscode-mysql#577]
- OS: macos 12.3.1
- Database Type: mysql 8.0.26

展开数据表后的字段列表界面中,对字段进行上移下移调整顺序操作还是会造成属性的错乱,比如我第一个字段的注释是 "主键id", 第二个字段的注释是 "分类id", 当把第一个字段往下移动时没问题, 新的顺序变为  "分类id","主键id", 再次把"主键id"上移后开始出现bug, 变为 "主键id", "主键id" , 原有的字段注释被自动更改了, AUTO_INCREMENT 属性也消失了

**Comment by cweijan** [comment]
感谢反馈, 我会在下版本修复.

**Comment by cweijan** [comment]
Hi, 已经发布了5.2.6版本修复了这个问题.

**Comment by pinyht** [comment]
现在正常了,谢谢
