### ISSUE TITLE
[BUG] query sorting is opposite

### ISSUE THREAD

**Issue by u007** [cweijan/vscode-mysql#578]
- OS: PopOS 22.04
- Database Type: postgresql

hi, i ordered by id desc, but it seems to be the opposite.
asc become desc and desc become asc
![2022-05-10_17-12](https://user-images.githubusercontent.com/388813/167594069-12009c20-e03a-4536-a412-14ef6571e0a7.png)

**Comment by cweijan** [comment]
Did the SQL get executed?

**Comment by u007** [comment]
yes executed and listed

**Comment by cweijan** [comment]
Hi, I have fixed this in version 5.3.1.

**Comment by u007** [comment]
thank you, will test
