### ISSUE TITLE
Support for LDAP Connection Type.

### ISSUE THREAD

**Issue by pdeol01** [cweijan/vscode-mysql#580]
Can support for LDAP connection type be made available ?

**Comment by cweijan** [comment]
What database are you referring to?

**Comment by pdeol01** [comment]
Oracle

**Comment by cweijan** [comment]
I released version 5.2.8 with support for custom jdbc api, trying to use jdbc with ldap.
![image](https://user-images.githubusercontent.com/27798227/168232809-f7dc7aa8-884f-4fe9-a9cd-29354b58fe93.png)

**Comment by pdeol01** [comment]
awesome anychance you can add fields for the following info to be entered for LDAP settings.

![image](https://user-images.githubusercontent.com/104864562/168387955-e765f99e-4857-48be-afa1-86272f9866ad.png)

THis is straight from sql devloper, new connection settings.

Just the bottom settings are required.

**Comment by cweijan** [comment]
Hi, an ldap jdbc is like this, `jdbc:oracle:thin:@ldap:<IP_address>/ADTEST,cn=OracleContext,DC=oracle,
dc=support,dc=com`
refer to https://www.ibm.com/docs/en/tivoli-netcoolimpact/6.1.1.4?topic=sdds-connecting-oracle-data-source-using-jdbc-ldap-url

I'm not familiar with ldap, so I won't add extra settings for it.
