### ISSUE TITLE
[BUG] Data Tab Cannot Display Numerical Infinity

### ISSUE THREAD

**Issue by Adrastopoulos** [cweijan/vscode-mysql#581]
- OS: Windows
- Database Type: Postgres

I have `float4` columns in the db with some values being Infinity: 

![image](https://i.imgur.com/MqRwRHN.png)

However when displayed in the VScode editor those same values are `(Null)`

![image](https://i.imgur.com/SyWKJXX.png)

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix this issue in the next version.

**Comment by cweijan** [comment]
Hi, try version 5.2.8, I have improved the data display of float4 and float8.

**Comment by Adrastopoulos** [comment]
Perfect, thanks.

![img](https://i.imgur.com/Qfcnnx0.png)
