### ISSUE TITLE
command 'mysql2.refresh' not found

### ISSUE THREAD

**Issue by WangChao233** [cweijan/vscode-mysql#582]
所有按钮均无法使用
command 'mysql2.refresh' not found
command 'mysql.connection.add' not found

**Comment by WangChao233** [comment]
![952157892f21e879a9f74fde1](https://user-images.githubusercontent.com/52311702/168202404-0ae1f034-ade7-4231-b505-7693218d8709.png)
安装的第一个版本，vscode也是最新的

**Comment by cweijan** [comment]
安装第一个，其他的卸载掉，然后重启vscode

**Comment by WangChao233** [comment]
> 安装第一个，其他的卸载掉，然后重启vscode

照做了，还是不行额

**Comment by cweijan** [comment]
你检查下你已安装的扩展

**Comment by WangChao233** [comment]
> 你检查下你已安装的扩展
![image](https://user-images.githubusercontent.com/52311702/168212875-fa862211-8a19-47be-98d8-329d1a958f27.png)
确认都卸载了
只有一个扩展，就是上述安装的mysql

**Comment by cweijan** [comment]
这个不对把, 好久之前的版本了 ![image](https://user-images.githubusercontent.com/27798227/168213612-c14bdcef-ccdb-4233-9781-41773cddbbc2.png)
