### ISSUE TITLE
Support for IBM Db2

### ISSUE THREAD

**Issue by macjabeth** [cweijan/vscode-mysql#583]
Hello! I just recently stumbled upon this extension and my experience with it thus far has been nothing short of outstanding. I went so far as to buy a license!

Notably absent from the feature set however is Db2 connectivity, at least based on what was visible in the connections list. This would be incredibly helpful for those of us who work for companies that use this database software (which is very prevalent with banks and insurance).

Thank you!

**Comment by cweijan** [comment]
Thank you for your support. I will consider supporting ibm db2 in a future version.

**Comment by cweijan** [comment]
Sorry guys, I tried IBM db2, it's old and clunky and I'm not going to support it.
