### ISSUE TITLE
[BUG] it only shows me single result when there are multiple results

### ISSUE THREAD

**Issue by Libra-Jiang** [cweijan/vscode-mysql#584]
- OS: win10
- Database Type: mysql

after i add a procedure which contains multiple select statements to a table and call it, those select statements should all be run and get some results, but i can only get one single result in the result view, see it as 
![image](https://user-images.githubusercontent.com/58113012/168770203-8bcd958c-ce6d-4f27-89a8-a373c0f03da1.png)

and btw i can't use the page key for it was locked
![image](https://user-images.githubusercontent.com/58113012/168770929-5e227b9c-03f7-4270-8384-361661c58537.png)

**Comment by cweijan** [comment]
Results pages have always been designed for single results, I have no plans to support multiple results at this time.

**Comment by Libra-Jiang** [comment]
> Results pages have always been designed for single results, I have no plans to support multiple results at this time.

alright, so is there any other method for me to see all the results at the same time

**Comment by Libra-Jiang** [comment]
and what are the `<` and `>` page keys designed for? the results view show me there's `Total 1` but actually there are two results?

**Comment by cweijan** [comment]
It is used to paginate the results.
![image](https://user-images.githubusercontent.com/27798227/168780773-dec41cce-4e78-4731-9078-911c2e520248.png)

**Comment by Libra-Jiang** [comment]
lol, okok, i got it, then may you provide me a method to solve my problem please, orz

**Comment by cweijan** [comment]
Multiple result have been supported in version 6.1.4.
