### ISSUE TITLE
Oracle Integration

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#588]
Thank you very much for integrating Oracle in this extension.  I do work in  both Oracle and MySQL.  At present, I am only using this extension for managing MySQL

Today only I saw the information about Oracle integration.  I got the configuration and connection perfect.  Let me bring the following into your notice, after exploring Oracle for 30 minutes using the extension:

1. Database Client - Change Active Connection Option

> System displays the Oracle Connection Name. On selection, the connection is not getting established.  If I run any command from a SQL file, the command is not getting executed.  (Error - No active database connection found)

> To get the connection established, I need to browse for a table under the database tree and get the data displayed.  After then commands executed from the SQL file is getting displayed.  Again the details of connection is not displayed in the bottom bar

2.  Most of my code is residing in Oracle Packages, which is not displayed in the tree view.  Can you please include list of packages in the tree view

![image](https://user-images.githubusercontent.com/8948123/169230052-0e1a8150-718b-4d82-afd4-7c4bffc97105.png)

3. I can create/modify functions and procedures from a SQL File.  But generates error while doing so for a package.  A sample package is enclosed. As all my codes exists in Oracle package, this is major hurdle for me.  A sample package is enclosed for your perusal. 

[Package.txt](https://github.com/cweijan/vscode-database-client/files/8726117/Package.txt)

These are my first hand view on the Oracle part of the extension.  Request you to consider the same

Regards

Franklin KF

**Comment by cweijan** [comment]
Thanks for your feedback, it's helpful, I'll implement these features in the future.

**Comment by franklinkf** [comment]
Thank you so much

**Comment by franklinkf** [comment]
Dear Sir, 

This is with reference with the following comment:

https://github.com/cweijan/vscode-database-client/issues/588#issue-1241332442

Of which, first point (Database Client - Change Active Connection Option) got rectified and is working fine

Second point is partially enabled.  Now I can see the Packages list in the tree view.  But the sql view is not getting opened on selection

Third option - This is my most important requirement as all my interactions with Oracle database happens through Packages

Can you please consider rectifying the issue under Point No - 3

Thanks you Sir

**Comment by franklinkf** [comment]
Also in tree view, the items are displayed in descending order (under Packages, Procedures and Functions).  Items are displayed correctly (in ascending order) under Tables.

Can you please arrange the items in the ascending order under Packages, Procedures and Functions

**Comment by cweijan** [comment]
Thank you for your feedback, I am still a learner for the oracle package, I will gradually improve the support.
Does the oracle package mean that both functions and stored procedures are grouped by package?

**Comment by cweijan** [comment]
The third point you said, do you mean the code already starts with `/`?

**Comment by franklinkf** [comment]
> Thank you for your feedback, I am still a learner for the oracle package, I will gradually improve the support. Does the oracle package mean that both functions and stored procedures are grouped by package?

Yes Sir.  We can bundle both procedures and functions within a package

**Comment by franklinkf** [comment]
> The third point you said, do you mean the code already starts with `/`?

Every package contains a package header and package body.  In the sample file provided the following block comprises of the package header

```
CREATE OR REPLACE PACKAGE PKGFRANKLIN AS

    PROCEDURE PROCESS                   (GSOLID         VARCHAR2);

END;
/
```

and the remaining block contains the package body

```
CREATE OR REPLACE PACKAGE BODY PKGFRANKLIN IS

PROCEDURE PROCESS               (GSOLID         VARCHAR2) IS

    GASON                           DATE1;

BEGIN

    RETURN;

END PROCESS;

END;
/
```
We can update the package header and package body together or one by one in the database.  

If we update package header alone without the last line /, the code is getting executed.  Similarly if we update the package body omitting the last two lines (END; /), the code is getting executed.  

But we normally preserve both header and body in a single file and update it together.  Here we face the issue.

Hope I have given a clarity on the issue.

Thank you

**Comment by cweijan** [comment]
You can select SQL, then execute the selected SQL, Pl/SQL seems flexible, I think it will take me a long time to support.
![image](https://user-images.githubusercontent.com/27798227/170989060-779c6d86-75a8-48f9-82fe-75457f6f3f4e.png)

**Comment by franklinkf** [comment]
No problem.  I will proceed as mentioned.

Thanks for your prompt response

Thank you once again for this nice extension

**Comment by cweijan** [comment]
Hi, I added the parsing of oracle package in version 5.7.6, maybe you can try it.
