### ISSUE TITLE
[BUG] Automatic selection of tables not working in specific cases

### ISSUE THREAD

**Issue by SuperDasher** [cweijan/vscode-mysql#590]
- OS: Windows 10
- Database Type: MySQL

I feel like this needs to be addressed: there needs to be backticks around the names of the tables and fields in the automatic selection of table views.

E.g: I have a database with a table named "character", and since that's a keyword in SQL it gives me an error if not surrounded with backticks
![image](https://user-images.githubusercontent.com/72823509/169792474-25a5cb74-dd14-48be-aacb-37a03f9d4366.png)

**Comment by cweijan** [comment]
Thanks for your feedback, now I add ` based on keywords, I will add support for character in the next version, not all by default because it will make SQL ugly.

**Comment by SuperDasher** [comment]
> Thanks for your feedback, now I add ` based on keywords, I will add support for character in the next version, not all by default because it will make SQL ugly.

Alright. Well in that case I want to point out that there might be other keywords that might create the same kind of conflicts, that's why I was suggesting the use of the backtick in any case.
I just though that it would be a hastle to look for every keyword that create the error.

**Comment by cweijan** [comment]
Hi, I have released version 5.3.3, which now adds escape characters to CHARACTER.

I think developers should avoid keywords as object names, if I added ` by default, it means everyone else is going to suffer from bad SQL because of someone else's mistake.

I plan to add an option in the future to add ` by default to object names.

**Comment by SuperDasher** [comment]
Ok, thanks for solving the issue, I think adding a feature like that could definitely benefit then.

**Comment by cweijan** [comment]
Hi, I added a new option in version 5.3.4, all object names will be escaped when checked.
![image](https://user-images.githubusercontent.com/27798227/170427617-5f5e7b4a-130f-4f58-84ca-325576a38c02.png)
