### ISSUE TITLE
[BUG] Paid version cannot use client in remote ssh

### ISSUE THREAD

**Issue by wststone** [cweijan/vscode-mysql#591]
Paid Version cannot login in, displays free account even though i am a paid user
Also, the redis extension doesn't show
<img width="734" alt="image" src="https://user-images.githubusercontent.com/42225395/170176433-fb8cd05a-8f0e-48c8-b04c-fc94a2366058.png">
Also the redis extension doesn't show, when installed
<img width="791" alt="image" src="https://user-images.githubusercontent.com/42225395/170176755-59751258-de9f-4ea4-a261-df6c1a1e4944.png">

- OS: macOS Monetery 12.2.1
- Database Type: redis

**Comment by cweijan** [comment]
Hi, please uninstall redis, you don't need to use it now, its functionality is merged into database-client.

Do not install multiple extensions that I have released, they will not work at the same time.
