### ISSUE TITLE
[BUG] SQL-Error

### ISSUE THREAD

**Issue by maruerru** [cweijan/vscode-mysql#592]
MySQL throws an error because the columns are not escaped with ` .

- OS: Windows
- Database Type: MySQL

![image](https://user-images.githubusercontent.com/46706901/170286352-29c45cbb-3f56-4373-ba78-49d460d44934.png)
![image](https://user-images.githubusercontent.com/46706901/170286467-df8ceec2-0e14-4863-a43c-6bb1b896940e.png)

P.S. Nice Extension. I like it. Keep going!

**Comment by cweijan** [comment]
Hi, please update to version 5.3.4, I have added the detection of the condition keyword, and also added a new option, all object names will be escaped.
![image](https://user-images.githubusercontent.com/27798227/170427519-b9ea9038-bf48-4771-8945-8516a86eb3df.png)
