### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mrzhangxd** [cweijan/vscode-mysql#593]
- OS: windows
- Database Type: mysql
- 数据库表显示的数据条数跟count 查出来的条数不一致
- 
![image](https://user-images.githubusercontent.com/16274179/170427664-fce0c9c9-d702-42b9-82b7-fec6bd761653.png)
![image](https://user-images.githubusercontent.com/16274179/170427665-72b8f4e5-0081-4f1f-8576-5abe3b1505e9.png)

**Comment by cweijan** [comment]
Hi, 在表旁边的只是一个大概的数字, 不是实时变化的, 尽管不准确, 但这个数字可以直观的看到一个表的数据量级别.

**Comment by Mrzhangxd** [comment]
我一直以为是准确的数字，这两天在研究flink cdc导数据，发现实际导进去的数据比插件边上线上的数据大好多，我还以为我自己导数据导出问题了
