### ISSUE TITLE
[BUG] Doesn't save row

### ISSUE THREAD

**Issue by AndrewRayCode** [cweijan/vscode-mysql#594]
- OS: Mac OS
- Database Type: MySQL

See video, updating row and re-opening it shows the update didn't save:

https://user-images.githubusercontent.com/79215/170619174-beda20cb-8ac6-41b0-acdc-64a792ce2f72.mov

Works fine on the CLI though: 
```
update schema_migrations set version = 1, dirty = 0;
```

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix this issue in the next version.

**Comment by cweijan** [comment]
Hi, I have fixed this bug in 5.3.6.

**Comment by AndrewRayCode** [comment]
Out of curiosity, what was the issue here? Wouldn't not being able to save data affect all users of this plugin?

**Comment by cweijan** [comment]
In the previous version, when you modified the data of the primary key, it could not be saved correctly, the new version has been fixed.
