### ISSUE TITLE
[BUG] Select all rows > delete shows error saying to select at least one row

### ISSUE THREAD

**Issue by AndrewRayCode** [cweijan/vscode-mysql#595]
1. Open a database table
2. click the select all rows box at the top left, which selects all rows
3. press delete
4. Error message: "You need to select at least one row of data!"

- OS: Mac OS
- Database Type: MySQL

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix this issue in the next version.

**Comment by cweijan** [comment]
Hi, I have fixed this bug in 5.3.6.
