### ISSUE TITLE
[SUGGESTION] Minify button

### ISSUE THREAD

**Issue by danielrdrigues** [cweijan/vscode-mysql#596]
The contrary of format button, would minify data (JSON).

**Comment by cweijan** [comment]
What format button? please describe your problem in detail.

**Comment by danielrdrigues** [comment]
> What format button? please describe your problem in detail.


![image](https://user-images.githubusercontent.com/10256444/172454895-433aa700-7a1b-43de-a8c4-63ca15ed2182.png)

**Comment by cweijan** [comment]
This button is used to beautify the JSON display, it works fine for me.

**Comment by danielrdrigues** [comment]
It would be a suggestion of feature, not a bug, cause in a project I would like to see the data formated, but store it minified.

**Comment by cweijan** [comment]
This is a feature of mysql, when the format is json, no matter what format you store it in, it will eventually be compressed.

The format button here is just for user viewing.
