### ISSUE TITLE
[BUG] Deleting Row(s) brings up Error

### ISSUE THREAD

**Issue by AbhijeetMankani** [cweijan/vscode-mysql#597]
### 2.  Clicked the Delete Button

The error comes up:
``SQL:  DELETE FROM `users` WHERE `Public_Key`=64093fb9e24242f8d3ad59ae4cdb87981a1bb2c99a93f6dc5ea7003d93340ac5
Unknown column '64093fb9e24242f8d3ad59ae4cdb87981a1bb2c99a93f6dc5ea7003d93340ac5' in 'where clause'``

### I could fix it manually by copying the command and adding quotes around the value

- OS: Windows
- Database Type: MySQL

**Comment by cweijan** [comment]
Thanks for the feedback, it seems that I detected a certain type as a value by mistake, please tell me what the type of `public_key` is.

**Comment by AbhijeetMankani** [comment]
> Thanks for the feedback, it seems that I detected a certain type as a value by mistake, please tell me what the type of `public_key` is.

The type of field `public_key` is `char(64)` and it is the `Primary Key` of the Table.


#### One thing that might help. It might be an issue because the string starts with a number. I haven't tried it with a string that starts with a character, but I suspect that might be a part of the issue, hope it helps.

**Comment by cweijan** [comment]
Whether to put quotes or not depends on your data type, your public_key is incorrectly detected as a numeric value by extension, so you need to tell me what the type of public_key is.

**Comment by AbhijeetMankani** [comment]
> Whether to put quotes or not depends on your data type, your public_key is incorrectly detected as a numeric value by extension, so you need to tell me what the type of public_key is.

Yes, as I mentioned in my earlier reply, the type of the `public_key` field is `char(64)`. It is a string, that's why I needed to put the quotes around it.
It might have mis-recognized it as a number, because the string starts with a number as a 1st character

**Comment by cweijan** [comment]
Thanks for your feedback, I've released version 5.3.7 to fix this bug.

**Comment by AbhijeetMankani** [comment]
> Thanks for your feedback, I've released version 5.3.7 to fix this bug.

Thank You!😊
Glad I could help! 😊
