### ISSUE TITLE
安装扩展后出现两套按钮，并且不显示连接名称[BUG]

### ISSUE THREAD

**Issue by waterlovevip** [cweijan/vscode-mysql#598]
- OS:Windows 11
- Database Type:
![1653878971(1)](https://user-images.githubusercontent.com/5491552/170908282-9cc946d8-54f2-4ae1-91ff-ecb384b10678.png)

**Comment by cweijan** [comment]
你安装了我发布的多个扩展, 卸载掉只保留一个呢.

**Comment by waterlovevip** [comment]
可以了，谢谢



在 2022-05-30 10:52:59，"WeiJian Chen" ***@***.***> 写道：

你安装了我发布的多个扩展, 卸载掉只保留一个呢.
