### ISSUE TITLE
[BUG] Text selection in the SQL query field is not highlighted

### ISSUE THREAD

**Issue by ppseprus** [cweijan/vscode-mysql#600]
- OS: macOS Monterey (12.3.1)
- Database Type: SQL

**Steps to Reproduce**
1. Click on any table from you open connection
2. Try to select any text in the SQL query text area (The fault should be something like `SELECT * FROM YourTable LIMIT 100;`

**Expected Behaviour**
Text selection is correctly highlighted.

**Actual Behaviour**
Text selection is not visible.

https://user-images.githubusercontent.com/1323285/171603743-a2a47198-6bbc-419d-ace9-52ee62b8a742.mov

**Comment by cweijan** [comment]
Thanks for your feedback, the current color is based on the theme, it doesn't seem to support your current theme, , I will try to adjust the selected text color.

**Comment by cweijan** [comment]
Hi, Version 5.4.0 has updated the background color of the selected font.
