### ISSUE TITLE
[BUG] extension is not using `~/.sqliterc` configurations

### ISSUE THREAD

**Issue by JonatasAmaral** [cweijan/vscode-mysql#603]
- OS: W10 20H2
- Database Type: SQLite3

I've set on the `.sqliterc` file in my user's folder, a `PRAGMA foreign_keys = ON;`, so this configuration persists for each connection.
When using the `sqlite.exe` on extension folder, it does work normally

Like in this example of referencing a non-existing foreign_key
![image](https://user-images.githubusercontent.com/8677724/171771391-87ecc3f8-4463-4d03-a3df-8ca948f4a8c1.png)

However, the extension ignores this configurations, and can set "invalid" queries, as if foreign_keys was OFF.
![Code_V8mQTIqmAP](https://user-images.githubusercontent.com/8677724/171771738-e8d6fccc-c277-40e5-83d6-2a42778dc788.gif)

**Comment by cweijan** [comment]
Hi, thanks for your feedback, I will try to upgrade sqlite in the next version/

**Comment by cweijan** [comment]
I have supported reading sqliterc in version 5.3.9.

**Comment by JonatasAmaral** [comment]
That's great!
thankyou once more
