### ISSUE TITLE
索引不能选多个构成组合索引，索引名称可以让用户来自定义嘛

### ISSUE THREAD

**Issue by miaokela** [cweijan/vscode-mysql#605]
索引不能选多个构成组合索引，索引名称可以让用户来自定义嘛

**Comment by cweijan** [comment]
点击这里用sql模板自己写, 设计表那里支持度不高.
![image](https://user-images.githubusercontent.com/27798227/171879602-ae2767a5-08e0-492e-a923-31e5c7fdef56.png)
