### ISSUE TITLE
Could you add cryptocurrency payment?

### ISSUE THREAD

**Issue by mirkadev** [cweijan/vscode-mysql#606]
Hi! Just want to say it would be nice if you added cryptocurrency payment. I'm from Russia and unfortunately, I cannot buy the client using any type of bank card.

**Comment by cweijan** [comment]
I am not familiar with the payment process of cryptocurrency, do I need to connect to a third-party platform or do you transfer cryptocurrency directly to me?

**Comment by cweijan** [comment]
Sorry for not being able to get support.
