### ISSUE TITLE
redis cluster模式连接超时

### ISSUE THREAD

**Issue by fujun3** [cweijan/vscode-mysql#607]
使用了ssh隧道，非cluster是可以连接成功的，cluster模式连接超时

![image](https://user-images.githubusercontent.com/25153558/172086045-4f12e5cf-4acb-4b7e-8923-615398025746.png)

**Comment by cweijan** [comment]
cluster是有多个redis服务的, 而通过隧道只能访问到连接的服务, 所以没办法通过ssh隧道连接redis cluster.

**Comment by cweijan** [comment]
参考了下AnotherRedisDesktopManager, 他是对所有节点都开了端口转发, 看来也是可以实现的, 等我后续实现哈.

**Comment by fujun3** [comment]
期待，另外这个插件提示free account不支持remote-ssh模式，支持是要另外付费？

**Comment by cweijan** [comment]
是的.

**Comment by cweijan** [comment]
5.4.0版本支持了

**Comment by fujun3** [comment]
给力
