### ISSUE TITLE
table fields mixed up when select * is used with a join

### ISSUE THREAD

**Issue by mobilemkm** [cweijan/vscode-mysql#608]
- OS:SUSE Linux
- Database Type: MySQL

Scenario: when joining two tables where the tables have common field names, the values for all the fields with the same names
does not come from both tables even though the field or fields are displayed twice.

**Comment by cweijan** [comment]
This problem has been fixed, is your version 5.3.9?

**Comment by mobilemkm** [comment]
![Screenshot_20220606_170821](https://user-images.githubusercontent.com/106983616/172200438-c4c3fe4f-47b8-49a8-864c-25176393f030.png)

**Comment by cweijan** [comment]
You need to upgrade your vscode to be able to use the latest version.
