### ISSUE TITLE
[BUG]SSH with very small font

### ISSUE THREAD

**Issue by NightmareZero** [cweijan/vscode-mysql#609]
- OS:windows 11
- Database Type:ssh
![Screenshot 2022-06-08 111553](https://user-images.githubusercontent.com/17422155/172524086-a54dd14a-e982-4567-b68a-534742690431.png)

**Comment by NightmareZero** [comment]
do you need some logs??

**Comment by cweijan** [comment]
You need to upgrade the extension version, install this and uninstall other.
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2

**Comment by NightmareZero** [comment]
![Screenshot 2022-06-08 143358](https://user-images.githubusercontent.com/17422155/172548618-9bc75e30-c5c8-4bf3-8327-e3286f4aebe4.png)
i used the latest version

**Comment by cweijan** [comment]
Try to modify the settings `editor.fontFamily`, the font of the terminal uses your settings.

**Comment by NightmareZero** [comment]
not work
![Screenshot 2022-06-08 163517](https://user-images.githubusercontent.com/17422155/172571360-5b986486-28ff-41bf-b759-b59d260881a7.png)

**Comment by NightmareZero** [comment]
another extensions “XPLOT” terminal is fine
![Screenshot 2022-06-08 163716](https://user-images.githubusercontent.com/17422155/172572211-1fa8a7eb-d3fd-4a07-8925-edc59f092364.png)

**Comment by cweijan** [comment]
I have released version 5.4.0, now you can use `terminal.integrated.fontFamily` to control the font of the terminal, but this does not mean the same as vscode's terminal display, you need to check the font you configured.
An example of a configuration.
```json
{
"terminal.integrated.fontFamily": "Consolas",
}
```

**Comment by NightmareZero** [comment]
it's work,thank you
