### ISSUE TITLE
[BUG] No change in data after performing an update.

### ISSUE THREAD

**Issue by codigoymass** [cweijan/vscode-mysql#610]
No Update the row when i open the dialog and then update the data. And i read the message "Update Success"

- OS: Linux Mint 20
- Database Type: MySQL

**Comment by cweijan** [comment]
Whether the update SQL is displayed when you edit?
![image](https://user-images.githubusercontent.com/27798227/172765934-e0f66dd8-f0d1-4a48-a38c-5a6bc5990ce7.png)

**Comment by codigoymass** [comment]
Yes, and i try to copy and paste in the document query but it doesn't work for me. Thanks for answering.

**Comment by cweijan** [comment]
I don't understand. If sql is executed, the data will definitely be updated..
