### ISSUE TITLE
[BUG] Connect Timeout

### ISSUE THREAD

**Issue by Antardas** [cweijan/vscode-mysql#612]
- OS: Windows 10
- Database Type: MongoDB
![image](https://user-images.githubusercontent.com/62651654/172768538-05321a05-6256-434e-a0e1-c38089c81f0f.png)

**Comment by cweijan** [comment]
If the mongo can connect normally, you can modify the timeout here.
![image](https://user-images.githubusercontent.com/27798227/172773115-639c11fc-a207-4bc2-87de-a11d4b4e7c0c.png)

**Comment by hadyrashwan** [comment]
same issue for me for postgres connecting locally works but when I try to connect through a tunnel that I already opened in a terminal it gives me timeout. 

using a new terminal psql  connection-string works

**Comment by hansadevelopers** [comment]
same issue mongo

**Comment by cweijan** [comment]
Can you guys tell me your mongodb version? Or do you use cloud service? I tried all mongodb versions and it works fine.

**Comment by cweijan** [comment]
Hi, I released version 5.7.0 to optimize connection stability, I think it works fine now.
