### ISSUE TITLE
SSH Authantication Type

### ISSUE THREAD

**Issue by abnershang** [cweijan/vscode-mysql#614]
Hi,

Wondering if it's possible to add an SSH authentication method that simultaneously applies both "Password" and "Private Key.

It could be a third option alongside the other two:
![CleanShot 2022-06-10 at 09 41 11](https://user-images.githubusercontent.com/75654486/172973297-639bd42f-10fb-4ac5-80ae-11102511e783.png)

The same concept from another database tool:
![CleanShot 2022-06-10 at 09 43 46@2x](https://user-images.githubusercontent.com/75654486/172973486-5f76e40f-19bb-4c74-be81-081420d445c5.png)

**Comment by cweijan** [comment]
Thanks for your feedback, I will try to support it.

**Comment by cweijan** [comment]
Support at version 5.4.1.
