### ISSUE TITLE
Code styling additions

### ISSUE THREAD

**Issue by sraajboy** [cweijan/vscode-mysql#615]
Certain keywords are not getting colored in VS Code.

- NOW
- DATABASES
- TABLES
- DESCRIBE
- COLUMNS
- FIELDS

![image](https://user-images.githubusercontent.com/101339903/173183213-22286a5b-d832-4d36-b1f8-70f165cee40a.png)

**Comment by cweijan** [comment]
Hi, thanks for your feedback, I will support Now and DESCRIBE in the next version, the others should not be used as keywords.
