### ISSUE TITLE
Adding one-time password input entry

### ISSUE THREAD

**Issue by abnershang** [cweijan/vscode-mysql#618]
Hi,

Thank you for adding the "Private Key and Password" option to the SSH tunnel. It helps a lot. 

I wonder if it's possible to add an entry to input a one-time password generated by the OTP authenticator. Like a popup window after clicking "Connect."

One of my environments uses a private key and OTP(use as a password) to verify SSH connections.

**Comment by cweijan** [comment]
This is your own special case, I don't think the database client should implement this feature.
