### ISSUE TITLE
please add setting for enable or disable wrap sql command .

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#619]
Hi.

please add setting for enable or disable wrap sql command .

![image](https://user-images.githubusercontent.com/6413705/173626962-da0e8336-143e-46fd-bfce-b3b4658260d2.png)

**Comment by cweijan** [comment]
I didn't understand what you meant.

**Comment by mbtolou** [comment]
![image](https://user-images.githubusercontent.com/6413705/173637882-9b1233f5-e51f-4491-a6c1-0d2322b73632.png)

When I run a query. A large part of the page is occupied by that query and there is no place left to display records.

**Comment by cweijan** [comment]
If you mean to hide the sql panel, you can try to modify this setting to auto
![image](https://user-images.githubusercontent.com/27798227/173715672-53131ace-4e4d-4638-ae63-b339968f20b4.png)
