### ISSUE TITLE
[BUG] Command mongo not exists in path!

### ISSUE THREAD

**Issue by yalattas** [cweijan/vscode-mysql#620]
## OS:
Windows 11 running WSL2 with Ubuntu distribution
```
user@my-pc:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

- Database Type: `mongoDB` 
- I was able to connect to mongoDB via _Ubuntu terminal_ on the same machine inside/outside `vs` code
Yet, tool is throwing time out error 

## context
I also added the following line to my `.bash_profile`
```
PATH=$PATH:/usr/bin/mongo
```
And it didn't work, nether `mongod`

## output
`Command mongo not exists in path!`

**Comment by yalattas** [comment]
mogno version

```
MongoDB shell version v5.0.9
Build Info: {
    "version": "5.0.9",
    "gitVersion": "6f7dae919422dcd7f4892c10ff20cdc721ad00e6",
    "openSSLVersion": "OpenSSL 1.1.1f  31 Mar 2020",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "ubuntu2004",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}
```

**Comment by cweijan** [comment]
Hi, consider adding `PATH=$PATH:/usr/bin/mongo` to /etc/profile, bash_profile is only for interactive shells.

**Comment by cweijan** [comment]
I noticed that you also raised a timeout, please tell me your mongodb version, and have you tried modifying the connection timeout?
![image](https://user-images.githubusercontent.com/27798227/173756071-2a618b7c-4589-4619-976c-fa6634e43b16.png)

**Comment by yalattas** [comment]
That's didn't resolve my issue
