### ISSUE TITLE
Disable inline "Execute"

### ISSUE THREAD

**Issue by danube** [cweijan/vscode-mysql#621]
Dunno if there is already a solution. I tried to find one in the docs and the settings, but couldn't find one. Please close this issue and guide me, If I overlooked something. I have a file with extension .sql, containing several commands. Above each one, "Execute" is displayed. Now I look for a possiblilty to have that behaviour turned off. It's my personal preference, to fire commands with CTRL-ENTER, which works well, and so the inline Execute link (again, for me personally) is not needed.

hugs, tom

**Comment by cweijan** [comment]
Can be closed, but only open to paid users.
![image](https://user-images.githubusercontent.com/27798227/173834650-eb26dd2f-114b-458a-b0b2-3221238d6843.png)
