### ISSUE TITLE
[BUG] "Execute" button disappears on use of apostrophe

### ISSUE THREAD

**Issue by abdul380-git** [cweijan/vscode-mysql#622]
- OS: MacOs
- Database Type: mySQL

Hi thanks for the amazing RSDM tool you have created and efforts frequently updating it.

I noticed that when I listed items in brackets and one of the items has an apostrophe e.g ("football", "Bell's Pepper", "yellow")
the "execute" button disappears for subsequent queries. However when I delete the apostrophe it comes back. Further, this only affects the current database/table and does not affect another table in another database.

I'm not sure if this is deliberate or a bug, and I wish it was it would be possible to continue using the "execute" button even with the use of apostrophe.

Feels free to reach out for further clarification.

**Comment by cweijan** [comment]
I have been improving the extension's SQL parsing capabilities over the past year, and I believe this issue has been resolved in the latest version.
