### ISSUE TITLE
[BUG] - Row not deleting

### ISSUE THREAD

**Issue by abdul380-git** [cweijan/vscode-mysql#623]
- OS: MacOs
- Database Type: MySQL

DELETE FROM invoices
WHERE client_id = (
    SELECT state
    FROM clients
    WHERE state = 'OR'
)

for the query above;
- there are two tables 'invoices' and 'clients'
- I want to delete the entire row from 'invoices' using a subquery of  a row item from 'clients' which matches the 'client_id' from 'invoices' - in this case 'state'
- there is no syntax error but it say rows affected '0' and won't delete the row
- also, if I provide the exact 'client_id' from the 'invoices' table it deletes.

hope this helps.

cheers!

**Comment by cweijan** [comment]
This is a data issue and has nothing to do with extension.
