### ISSUE TITLE
[BUG] cannot update on press enter or ctrl+enter

### ISSUE THREAD

**Issue by u007** [cweijan/vscode-mysql#624]
- OS: popos 22.04
- Database Type: postgresql

i think this is ui triggering update giving error
![2022-06-16_13-44](https://user-images.githubusercontent.com/388813/174000016-dc37fdda-8440-45ee-a42f-dd97b9bdba0a.png)

**Comment by cweijan** [comment]
Hi, I will fix this problem in the next version, for now you can temporarily solve it by disabling the filter.
![image](https://user-images.githubusercontent.com/27798227/174000558-ecac1661-c2ce-454b-bb41-0ac2441c97c5.png)

**Comment by u007** [comment]
hi 

was already checked
![2022-06-16_14-09](https://user-images.githubusercontent.com/388813/174003199-22f6fddf-a5b7-476c-8d30-f8eb3d4281f1.png)

**Comment by cweijan** [comment]
I mean uncheck it.

**Comment by cweijan** [comment]
Hi, I released version 5.4.2 to fix it.

**Comment by u007** [comment]
okay thank you
