### ISSUE TITLE
[BUG] SQL Commands not working after some time if connected to SSH

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#625]
- OS: Windows
- Database Type: MySQL

I connect my test environment via SSH and access the MySQL DB installed in that system.  After today's update, connection to database becomes unresponsive after some time.  To work again, I need to reload VS Code again and connect to database again.

Later only I came to know about the update and I tried by restoring the previous version of the extension.  Now everything works fine.

Request you to please look into the issue

Regards

Franklin KF

**Comment by cweijan** [comment]
Thanks for your feedback, but I haven't changed this part of the code in the latest version, try to install the latest version of the extension and restart vscode.

**Comment by cweijan** [comment]
Hi, try the latest 5.4.5 version, I think I have fixed it.

**Comment by franklinkf** [comment]
Thank you Sir
