### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ahmedhakil** [cweijan/vscode-mysql#626]
- Issue Type: `Bug`
- Extension Name: `vscode-mysql-client2`
- Extension Version: `5.4.4`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by cweijan** [comment]
Please describe what happened to you, if there is no details I will close it。
