### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Vedia-JerezDaniel** [cweijan/vscode-mysql#627]
- OS: Linux Kubuntu 22.04
- Database Type: MySQL 

I have the latest version, if  I made any mistake in the query, it returns:
"No active connection found!"

Then I have to connect again to run the query.

I think with the previous version I did't get that error.

Please solve it, I think it is the best app for SQL databases available for VSCODE.

Thanks.

**Comment by Vedia-JerezDaniel** [comment]
One last question, when I log-in under my email account, it appears the date 
"2022-05-11 -> EXPIRE"

That it means my account is expired? I have a Free account.

Thanks again.

**Comment by Vedia-JerezDaniel** [comment]
![Screenshot_20220620_140223](https://user-images.githubusercontent.com/20303549/174597694-cc07a432-6498-499d-af4a-f112802d577e.png)

**Comment by cweijan** [comment]
Hi, thank you very much for your feedback, I have released version 5.4.5 to fix this issue.

**Comment by cweijan** [comment]
The account shows expired because the newly registered account will get 7 days of premium.
