### ISSUE TITLE
Support earlier version of Clickhouse 

### ISSUE THREAD

**Issue by icceey** [cweijan/vscode-mysql#629]
I'm using clickhouse v19.16.10.44, after successfully connecting, an error occurred while loading the database information.

![image](https://user-images.githubusercontent.com/33692766/174946283-87bd6d7d-8192-4b80-94ad-634bd6b57d1f.png)

some logs:

```
Execute sql fail : SELECT name as Database FROM system.databases where name not ilike '%information_schema%' order by name ASC
Syntax error: failed at position 62: ilike '%information_schema%' order by name ASC FORMAT JSON. Expected one of: BETWEEN, LIKE, IN (version 19.16.10.44)
```

It seems that `ilike` operator was added at version [20.6.3.28](https://clickhouse.tech/docs/en/whats-new/changelog/#clickhouse-release-v20-6-3-28-stable).

So, could you please support the earlier version?

**Comment by cweijan** [comment]
Thanks for your feedback, I've released version 5.4.7 with the like statement removed.

**Comment by icceey** [comment]
Thanks for solving the problem so quickly.
Now I can successfully load databases, but fail to load tables and functions.
<img width="778" alt="image" src="https://user-images.githubusercontent.com/33692766/175453065-dec6a4ea-e33e-462a-a6fa-b492ce9dce1e.png">

Here are some logs:
```
Execute sql fail : select name, engine as type, comment from system.tables where database='oncall' and engine <> 'View' ORDER BY name
Missing columns: 'comment' while processing query: 'SELECT name, engine AS type, comment FROM system.tables WHERE (database = 'oncall') AND (engine != 'View') ORDER BY name ASC', required columns: 'engine' 'comment' 'name' 'database', source columns: 'storage_policy' 'primary_key' 'partition_key' 'engine_full' 'dependencies_table' 'sorting_key' 'dependencies_database' 'metadata_modification_time' 'database' 'name' 'engine' 'is_temporary' 'create_table_query' 'metadata_path' 'sampling_key' 'data_paths' (version 19.16.10.44)

Execute sql fail : select name as "ROUTINE_NAME" from system.functions  where origin !='System'
Missing columns: 'origin' while processing query: 'SELECT name AS ROUTINE_NAME FROM system.functions WHERE origin != 'System'', required columns: 'name' 'origin', source columns: 'alias_to' 'case_insensitive' 'name' 'is_aggregate' (version 19.16.10.44)
```

**Comment by cweijan** [comment]
Looks like clickhouse 19 and 20 have changed a lot, I will try to start an older version of clickhouse.

**Comment by icceey** [comment]
ok, thanks for your support

**Comment by cweijan** [comment]
hi, I already support earlier clickhouse in the latest version 5.5.2.

**Comment by icceey** [comment]
It works! Thanks a lot!
