### ISSUE TITLE
[BUG] Command Not Found when attempting to add Connection v5.4.8

### ISSUE THREAD

**Issue by kentm** [cweijan/vscode-mysql#630]
- OS: macOS Monterey
- Database Type: Mysql or any really

I performed a fresh install of version v5.4.8 this morning and I'm receiving the errors in the screenshot when trying to add a database.  I installed v5.4.6 on another mac last night and it is working as expected.

<img width="1222" alt="Capture_2022-06-24_08-43-17_am" src="https://user-images.githubusercontent.com/4055648/175427393-34084594-a9e8-436b-a7c6-a939bcd93f03.png">

**Comment by cweijan** [comment]
Very sorry, I released 5.4.9 to fix this bug.

**Comment by kentm** [comment]
Thanks, this is resolved in 5.4.9
