### ISSUE TITLE
Free account not support work in remote ssh

### ISSUE THREAD

**Issue by QicongWang** [cweijan/vscode-mysql#633]
I get the below message on the database panel. I am working on the remote machine and trying to connect to the database on the same machine.
![image](https://user-images.githubusercontent.com/37811985/176944522-025f3106-cbf3-43e2-9694-b7476907023d.png)

**Comment by cweijan** [comment]
Remote-ssh has restrictions and must be paid for use.

**Comment by cweijan** [comment]
Hi, I have now restored support for remote-ssh free use.

**Comment by canadiannomad** [comment]
Leading me not to want to buy, because I cant test it out... catch 22?
I need it, so I will, but I'll also be very quick to regret it if it doesn't work.

**Comment by cweijan** [comment]
Hi, Version 6.6.0 removes this limitation, now it is possible to create three connections.
