### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by geocheats2** [cweijan/vscode-mysql#634]
First of all great work with this app, it was well worth the 20$

I think i stumbled upon a bug or something like that and thought i should mention it

I am working on a db over ssh and after closing the lid of the laptop and opening it i have to close the connection and open it again in order to prevent some kind of caching on the table i am working on in vscode

i can write on the sqlite file but for some reason pressing play on the default sql query (SELECT * FROM settings LIMIT 100;) it doesn't fetch the updated data.

Just a heads up 
Keep up the good work

**Comment by cweijan** [comment]
For the table structure, you can click the refresh button at the top of the panel to refresh the cache.
![image](https://user-images.githubusercontent.com/27798227/177030024-ee36150a-94ae-4b24-be75-59d821467614.png)

But I didn't cache the table data, I think you need to test again.
