### ISSUE TITLE
[BUG] MySQL - Display of table properties

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#635]
- OS: Windows
- Database Type: MySQL

Now I am facing an issue.  Table properties are displayed in template.sql file when I focus the mouse pointer on table name with control key pressed.  This causes inconvenience  whenever I select the table name for copying or replacing the same.

Request you to please change the key options for displaying table properties or provision to disable the option in settings.

Thanks and Regards

Franklin KF

**Comment by cweijan** [comment]
yes this is a bug, i will fix it in the next version.

**Comment by franklinkf** [comment]
Thank you very much Sir
