### ISSUE TITLE
Use SSH-Agent (from system env, e.g. SSH_AUTH_SOCK) for DB connection through SSH Tunnel

### ISSUE THREAD

**Issue by ppenguin** [cweijan/vscode-mysql#636]
When using "SSH Tunnel" in connection settings, allow for "private key without password" if SSH agent is running and known to the environment.
Should probably support a few well known env vars (e.g. for vanilla SSH-Agent and gnome-keyring, etc(?)....

**Comment by cweijan** [comment]
"private key without password" is supported, it doesn't force you to enter a password when you try  connect by private key.

Do you mean the extension should automatically read the Passphrase about the key?

**Comment by cweijan** [comment]
I went to read about SSH-Agent, I don't think the database client should support it.
