### ISSUE TITLE
Enable Safe Mode

### ISSUE THREAD

**Issue by yersonperez** [cweijan/vscode-mysql#637]
I don't know if this request is done, but, is usefull if we can use a safe mode by default to avoid delete entire columns.

**Comment by cweijan** [comment]
Hi, what's mean "delete entire columns"? do you mean `delete from <table>` without any conditions?

**Comment by yersonperez** [comment]
I mean safe mode in SQL relative with error code 1175. When i use `delete from <table> where <column>='Doe' (E.g.)` in your extension this command DELETE all columns entry; if the SQL safe mode is on, show _Error 1175_ when i execute `delete from <table> where <column>='Doe' (E.g.)` .

**Comment by cweijan** [comment]
Thanks for your feedback, I will support it in the future.

**Comment by cweijan** [comment]
Hi, version 5.6.0 already supports safe mode (the safe is wrongly written as save, which will be fixed in the next version).
![image](https://user-images.githubusercontent.com/27798227/179173762-49f73956-dda7-4e77-98d2-8c8a253a6ab5.png)
