### ISSUE TITLE
Cannot export data table

### ISSUE THREAD

**Issue by thebenkahn** [cweijan/vscode-mysql#640]
- OS: Windows 10 10.0.19044
- Database Type: MySQL, MariaDB

For the last week, anytime I try to export the results of a query by clicking export data, I get the Export option dialogue box but when a choose an export type and click Export it just spins forever.

https://www.youtube.com/watch?v=OOZ0fO10_j8

I have tried clean uninstall of VS Code and reinstall the plugin and still get the same issue.

Any help would be appreciated.

**Comment by cweijan** [comment]
Hi, thanks for your feedback, I released 5.6.2 to fix this.

**Comment by thebenkahn** [comment]
Wow, that was fast. Thanks! I updated and the issue is resolved.
