### ISSUE TITLE
SQL Server don't show results if previous query has many results and you navigated to a higpage result

### ISSUE THREAD

**Issue by seixaserick** [cweijan/vscode-mysql#641]
How to reproduce the bug:

1) Click over a table.
2) Auto select top 100 * from table1 runs automaticly
3) Change to "select top 1000 * from table1" and run it
4) Navigate to page 7
5) Change the query again for something more restrictive like "select top 1000 * from table1 where city = 'LAX'; "
6) If result has less then 7 pages (example:  8 rows)  the grid doesn't show any row because it tries to show the page 7 (it should show the page 1 if the query was changed)

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix this issue in the next version.

**Comment by cweijan** [comment]
Hi, this problem has been fixed in the latest version.
