### ISSUE TITLE
[BUG] SQL becomes incomplete after formatting

### ISSUE THREAD

**Issue by gzy02** [cweijan/vscode-mysql#643]
当含有concat(xxx, "%")语句时，出现格式化错误
(Formatting error occurs when concat (XXX, "%") statement is included)

例子(Example):

格式化前(Before formatting)
![image](https://user-images.githubusercontent.com/67055520/180483361-145aa012-67e0-4590-bc5d-1f57ba0a543a.png)
![image](https://user-images.githubusercontent.com/67055520/180483501-94cb1dc3-f84a-4c31-80f1-fcc2f0287c60.png)

格式化后(After formatting)
![image](https://user-images.githubusercontent.com/67055520/180483718-99df6bd8-ecc5-4800-a3cc-2b7be57e244e.png)
![image](https://user-images.githubusercontent.com/67055520/180483683-83026f22-2300-4d60-9a40-7024f5160808.png)

- OS: Windows10
- Database Type: MySQL

**Comment by cweijan** [comment]
哥们你用的是下面这个扩展吗? 我试了很多次都没遇到你这个情况, 你的源sql能不能发我下.
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2

**Comment by gzy02** [comment]
> 哥们你用的是下面这个扩展吗? 我试了很多次都没遇到你这个情况, 你的源sql能不能发我下. https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql-client2

使用扩展及其版本
![image](https://user-images.githubusercontent.com/67055520/184290228-8f24c4bb-42c8-485e-bbfd-83e1c3e281b8.png)
格式化前:
![image](https://user-images.githubusercontent.com/67055520/184290253-78bf64d9-8e6a-4157-a483-b1238668a8f2.png)
格式化后:
![image](https://user-images.githubusercontent.com/67055520/184290287-423462d5-2228-4332-862b-080e5c97a7d4.png)

test1.sql
`
create view view_inner_zj_devunreg as
select
    branch1_id as bid1,
    branch1_name as `name`,
    devunreg
from
    branch1 natural
    join(
        select
            branch1_id,
            count(branch1_id) as devunreg
        from
            (
                select
                    max(branch1_id) as branch1_id,
                    devid,
                    devno
                from
                    branch1,
                    (
                        select
                            devstate_base_devid as devid,
                            devstate_base_devno as devno
                        from
                            devstate_base
                        where
                            devstate_base.devstate_base_devid not in (
                                select
                                    devorg.devorg_id
                                from
                                    devorg
                            )
                    ) as out_devid
                where
                    devid like concat(branch1_id, "%")
                group by
                    devid,
                    devno
            ) as tep_table
        group by
            branch1_id
    ) as tep2_table
;
`

test2.sql
`
create view view_inner_zj_devdup as
select
    branch1_id as bid1,
    branch1_name as `name`,
    count(devstate_base_devid) - count(distinct devstate_base_devid) as devdup
from
    branch1
    join(
        select
            max(branch1_id) as branch1_id,
            devstate_base_devid,
            devstate_base_devno
        from
            branch1,
            devstate_base
        where
            devstate_base_devid like concat(branch1_id, "%")
        group by
            devstate_base_devid,
            devstate_base_devno
    ) as tep_table using (branch1_id)
group by
    branch1_id,
    branch1_name
having
    devdup > 0
;
`

**Comment by cweijan** [comment]
谢谢提供.

**Comment by cweijan** [comment]
Hi, 已发布5.7.6版本修复.
