### ISSUE TITLE
[BUG] mysql编辑表结构不能正确显示某些配置

### ISSUE THREAD

**Issue by graysheeep** [cweijan/vscode-mysql#647]
![图片](https://user-images.githubusercontent.com/4529986/181168799-91d60241-9b1f-46fb-b69f-f76fc161d8e3.png)
如图，选了NOT NULL生效了，但是图中没有打✅

- OS: macOS
- Database Type: mysql

**Comment by cweijan** [comment]
谢谢反馈, 这里是会刷新的, 应该是报错了, 需要麻烦你打开下开发者工具看看错误日志.
![image](https://user-images.githubusercontent.com/27798227/181170233-93f0a877-3281-426a-894f-12c23822d900.png)

**Comment by cweijan** [comment]
Hi, 是因为之前白色主题的颜色不对, 导致勾选的颜色也是白色的, 5.7.0版本修复了.
