### ISSUE TITLE
[BUG] clickhouse show table DDL failed

### ISSUE THREAD

**Issue by chroniflux** [cweijan/vscode-mysql#648]
- OS:
- Database Type: Clickhouse

I want to get clickhouse table DDL, but it didn't worked. I find query sql is:
SELECT create_table_query as "Create Table",name as table_name,'definition' as view_definition from system.tables WHERE database='system' and table='metric_log'

It is not right, system.tables does not has `table` column, should be:
SELECT create_table_query as "Create Table",name as table_name,'definition' as view_definition from system.tables WHERE database='system' and name='metric_log'

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Hi, I forgot to notice you that the conditional column table has been changed to name, and now the ddl can be displayed normally.
