### ISSUE TITLE
[BUG] Loading indicator is displayed at wrong row

### ISSUE THREAD

**Issue by ppseprus** [cweijan/vscode-mysql#649]
- OS: MacOS
- Database Type: PostgreSQL + MySQL
- Extension Version: 5.6.6

Sometimes, the loading indicator is spinning at the wrong connection (they share the same ssh tunnel config)... Maybe, somehow the configs are conflicting? 🤔 

I observed this during https://github.com/cweijan/vscode-database-client/issues/642 

https://user-images.githubusercontent.com/1323285/181011092-7457164c-72fd-4f4a-8db1-ed9b956ff13e.mov

**Comment by cweijan** [comment]
This is really unfortunate news, everything is working fine for me, can you try to recreate the connection?

**Comment by cweijan** [comment]
Hi, I released version 5.7.0 to optimize connection stability, I think it works fine now
