### ISSUE TITLE
Handshake failed: no matching key exchange algorithm

### ISSUE THREAD

**Issue by wilen5** [cweijan/vscode-mysql#650]
Any idea what causing this i can ssh few days ago but now i'm having this error. I tried to connect with other ssh app and its working just fine.
![Capture](https://user-images.githubusercontent.com/18680420/181489944-ed292a5c-671c-48e0-a484-a5348c01685d.JPG)

**Comment by cweijan** [comment]
hi, try newest version 5.6.7, in the previous version I used wrong key exchange algorithm, which caused some ssh servers to fail to connect.

**Comment by wilen5** [comment]
> hi, try newest version 5.6.7, in the previous version I used wrong key exchange algorithm, which caused some ssh servers to fail to connect.

That fix it thanks.
