### ISSUE TITLE
[BUG] No active connection found!

### ISSUE THREAD

**Issue by donglianyou** [cweijan/vscode-mysql#651]
我创建了mysql连接之后开始可以执行sql，第二天执行的报错：‘No active connection found!’,
这是bug吧，还是什么原因？

**Comment by cweijan** [comment]
你看下文档的使用流程，sql文件要和连接绑定才能查询

**Comment by Zhaopudark** [comment]
@donglianyou  在文档最上方要选一下activation 

<img width="774" alt="image" src="https://user-images.githubusercontent.com/44562106/190917339-cc65376d-9563-4230-8393-8bd1e6275d1b.png">
