### ISSUE TITLE
[BUG] UI went wrong: duplication icons and not showing saved database

### ISSUE THREAD

**Issue by DeathKing** [cweijan/vscode-mysql#652]
- OS: Windows
- Database Type: /

I'm quite sure that I've added some valid database connection configurations, but the UI keeps asking me to 'create connection' even if I restart VsCode. Besides, the icons are duplicated somehow.

![微信截图_20220804160939](https://user-images.githubusercontent.com/895809/182798997-63f44855-7c05-43ff-8acf-35de5481e400.png)

**Comment by cweijan** [comment]
hi, you have installed multiple extensions published by me, please uninstall the duplicate ones.

**Comment by DeathKing** [comment]
@cweijan Yeap, I figured out that I installed MySQL v5.6.7 a long ago, which caused the duplication. Bug fixed by uninstalled that plugin.

So what's the difference between MySQL(vscode-mysql-client2) and Database Client(vscode-database-client2)?

**Comment by cweijan** [comment]
At the beginning, this extension only supports mysql, so the name is still kept as mysql, and it released under the new name, and these two extensions will be updated synchronously.
