### ISSUE TITLE
Allow specifying sql_mode

### ISSUE THREAD

**Issue by silverbullettruck2001** [cweijan/vscode-mysql#653]
Can you make a setting to allow users to provide a comma separate value to be used as the `sql_mode` parameter on MySQL connections?  The setting would take values like these:

`ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION`
or could just be one if you only wanted to specify a single `sql_mode` value:
`STRICT_TRANS_TABLES`

**Comment by cweijan** [comment]
Thanks for your suggestion, but why do you need to set sql_mode on the client side? Usually it is set on the server.

**Comment by silverbullettruck2001** [comment]
We have it set on the server, but when we create functions or stored procedures the client creates the object with object specific `sql_mode` which overrides the server or session level values.  So for instance if we have our global `sql_mode` set to:
`STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION`

And then we create or modify a stored procedure with VSCode using this plugin the `sql_mode` is not set using what is the global or even the session level settings.  We have noticed this with other SQL tools as well but the other tools, like MySQL Workbench, have a setting in the preferences where you can specify the default `sql_mode` to use that allows this to be used on all commands.  Which is why I am requesting this so we can do the same using your plugin.

**Comment by silverbullettruck2001** [comment]
Oh, also, the importance of this is if the function or proc is created with the incorrect `sql_mode` the way that the queries within the proc are not correct and inconsistent with the database, so it is very important that we have the ability to control this as it causes serious query differences.

**Comment by cweijan** [comment]
Hi, I have released version 5.7.4, now you can set sql_mode on the connection page.
![image](https://user-images.githubusercontent.com/27798227/186856170-7c744a96-3be8-4fb7-b512-ac39d70e2645.png)
![image](https://user-images.githubusercontent.com/27798227/186856195-ac23f3c0-7618-45f6-afae-50435a616712.png)

**Comment by silverbullettruck2001** [comment]
Thanks!
