### ISSUE TITLE
ASCII View

### ISSUE THREAD

**Issue by silverbullettruck2001** [cweijan/vscode-mysql#654]
When clicking on the magnifying glass on a field in the results could you add an option in the dropdown for `ASCII` that would show the results in ASCII encoding instead of utf8?  Or provide some other way of returning the results in ASCII instead of utf8?

**Comment by cweijan** [comment]
utf8 is a superset of ASCII, which means that the result of ASCII encoding is the same as utf8.

**Comment by cweijan** [comment]
Maybe you mean to display ASCII code in decimal, but this is not the function of database client, you should use other tools to achieve it.

**Comment by silverbullettruck2001** [comment]
Sounds good, thanks!
