### ISSUE TITLE
It would be great to have ability create foreign keys to the database columns

### ISSUE THREAD

**Issue by lexexpert** [cweijan/vscode-mysql#655]

**Comment by cweijan** [comment]
Thanks for your feedback, I will add support for foreign keys in the future.

**Comment by cweijan** [comment]
Hi, I released version 6.0.0, which improved foreign key management.
![image](https://user-images.githubusercontent.com/27798227/205896748-9b396547-6feb-4594-9eec-3f9fa104fbaa.png)
![image](https://user-images.githubusercontent.com/27798227/205896782-bd1d3b7e-5cb2-49bd-8fcb-88c84f2ded7e.png)

**Comment by lexexpert** [comment]
Nice work, @cweijan .
Thank you so much.
Another one improvement could be ability to create a unique index for multiple columns.
<img width="1324" alt="Screenshot 2022-12-06 at 9 19 52 AM" src="https://user-images.githubusercontent.com/13494499/205937221-d795b2d3-ab34-49ba-be53-50a32fd2963d.png">
<img width="1091" alt="Screenshot 2022-12-06 at 9 20 26 AM" src="https://user-images.githubusercontent.com/13494499/205937224-a8363232-a9e7-42b1-8526-73a8623ac202.png">

**Comment by cweijan** [comment]
Thanks for the feedback, this feature is nice, I will implement it in future versions.

**Comment by cweijan** [comment]
Thanks for the feedback, this feature is nice, I will implement it in future versions.

**Comment by cweijan** [comment]
Thanks for the feedback, this feature is nice, I will implement it in future versions.
