### ISSUE TITLE
[BUG] Decryption error when request a reset code

### ISSUE THREAD

**Issue by Natblow** [cweijan/vscode-mysql#656]
- OS: Windows 11
- Database Type: MySQL

Whether it's to create a new account or reset a password, when we want to "send reset code" there is always the same error message "Decryption Error". It doesn't say much if I need to put a different password...

![image](https://user-images.githubusercontent.com/85266997/183961746-9133f86b-8f7a-4f19-b3b3-bfffff76987c.png)

**Comment by cweijan** [comment]
Thanks a lot for your feedback, I have fixed this.

**Comment by Natblow** [comment]
Ok it works now, thank you!
