### ISSUE TITLE
[BUG] esConnection doesnt support expired SSL certificates

### ISSUE THREAD

**Issue by rcelestino** [cweijan/vscode-mysql#657]
esConnection doesn't support expired certificate cases.

redis and the other connection already support, probably adding the below lines would be enough.

```
        if(node.useSSL){
            config.tls={
                rejectUnauthorized: false,
                ca: (node.caPath) ? fs.readFileSync(node.caPath) : null,
                cert: ( node.clientCertPath) ? fs.readFileSync(node.clientCertPath) : null,
                key: ( node.clientKeyPath) ? fs.readFileSync(node.clientKeyPath) : null,
                minVersion: 'TLSv1'
            }
        }
```
- OS: *
- Database Type: ElasticSearch

**Comment by cweijan** [comment]
Hi, the extension is now released here, I don't think it will verify the certificate of es connection.
https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-database-client2
