### ISSUE TITLE
[BUG]当vscode为浅色主题时，复选框内的 √ 为白色，无法识别是否处于选中状态

### ISSUE THREAD

**Issue by CWenTeng** [cweijan/vscode-mysql#658]
如图：
![16602864748453](https://user-images.githubusercontent.com/29345716/184300793-0874d21e-5a70-4423-a0a1-defbc81e3c0e.png)
![1660286390(1)](https://user-images.githubusercontent.com/29345716/184300796-2feca389-c22f-4969-a2ea-bcf0c636ee00.jpg)
希望可以改成辨识度较高的颜色

**Comment by cweijan** [comment]
谢谢反馈, 会在下版本修复

**Comment by cweijan** [comment]
Hi, 已经发布了5.7.0版本修复了

**Comment by CWenTeng** [comment]
好的，升了最新版本已经可以了，谢谢！
