### ISSUE TITLE
String literal support

### ISSUE THREAD

**Issue by shiro** [cweijan/vscode-mysql#661]
A big feature that makes DB queries easy to use in and IDE is the support for string literals (using SQL statements inside of strings, i.e. in a JS file).  
It would be great if your extension supported running statements in string literals in the same way it does in SQL only files right now (showing the "execute" bubble, adding the "run" command when cursor is on the statement).

![Screenshot_20220813_093518](https://user-images.githubusercontent.com/13651492/184460769-7fb69d40-fa70-4c8c-bcd6-98762dffbed5.png)

**Comment by cweijan** [comment]
Sorry, I don't plan to implement it, there is no way to know which connections are currently active in the code, usually you need to open another editor.
In addition, parsing non-SQL documents also affects the performance of vscode.
