### ISSUE TITLE
[BUG] Premium expired error?

### ISSUE THREAD

**Issue by wilen5** [cweijan/vscode-mysql#663]
- OS:W10
- Database Type:MySql
- I can't open my database remotely now not sure what is causing this.
![Capture](https://user-images.githubusercontent.com/18680420/185060623-5c5f5920-1d33-437c-a894-9d1d4aa9f2cf.JPG)

**Comment by cweijan** [comment]
Hi sir, please log in again.
![QQ截图20220817074812](https://user-images.githubusercontent.com/27798227/185061079-c7f247a5-87d4-4317-9946-1849a6181cac.png)
