### ISSUE TITLE
[BUG] Premium plan expired before one year

### ISSUE THREAD

**Issue by Trashimi** [cweijan/vscode-mysql#665]
- OS: MacOS
- Database Type: SQL

Hello, I've paid for the premium plan a couple months ago, now the plugin says that my premium expired on 2022-08-16 but I think it should be 2023.
<img width="210" alt="image" src="https://user-images.githubusercontent.com/102296190/185415626-6c0a9ff0-499b-465a-9d7d-404f3b17b1f1.png">
Could you help me address this issue please ?

Thanks a lot for your time and attention

**Comment by cweijan** [comment]
Hi, does your paypal purchase record still exist? The email address you use has not purchased before.

Another possibility is that you were using github login before.
![image](https://user-images.githubusercontent.com/27798227/185417009-c461d991-9f4e-437c-9d88-bd08d6a5b3d8.png)

**Comment by cweijan** [comment]
Any idea? If you are concerned about privacy issues, you can send it to my email cweijan@163.com.
