### ISSUE TITLE
Persian language is not supported!

### ISSUE THREAD

**Issue by Sajjad-Arjmand** [cweijan/vscode-mysql#666]
# Persian language is not supported!
Hi! Thanks for your really useful extension.
Please add support for showing UTF8_unicode_ci collation.
Currently the characters which are written in Persian language are shown as '??????'

**Comment by cweijan** [comment]
I think you need to modify the charset of the database, this extension is not involved in encoding.

**Comment by Sajjad-Arjmand** [comment]
OK. I got it!
but the main problem is that I can't store Persian characters in database if I change the charset. it has to be 'UTF8_unicode_ci' or 'UTF8_persian_ci'.

**Comment by cweijan** [comment]
Again, the client is not involved in the encoding of strings, you should seek help from the mysql community.

Try to create table by specifying charset. and insert data.
```sql
CREATE TABLE test(  
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary Key',
    content VARCHAR(255) COMMENT 'content'
) CHAR set utf8;
```

**Comment by Sajjad-Arjmand** [comment]
OK thanks!
