### ISSUE TITLE
[BUG] It is not possible to obtain the schema of the functions and procedures

### ISSUE THREAD

**Issue by manfran1011** [cweijan/vscode-mysql#668]
- OS: Mac OS 
- Database Type: Postgresql
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/6050660/186435311-a9f01488-9759-4c78-b190-cd27abc556b4.png">

**Comment by cweijan** [comment]
Hi, thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Hi, this problem is because there is no compatibility with older versions of pg, I released version 5.7.4 to solve it.
