### ISSUE TITLE
Group tables and save

### ISSUE THREAD

**Issue by WayneDK** [cweijan/vscode-mysql#669]
when working with a large MySQL database, 300 plus tables, it would be useful to be able to group a set of tables you are working with and save that grouping as a sub-set you could display. 

Often you are working on less that 10 tables for a specific feature, but there isn't an easy way we can see to group those tables, save the grouping and display that group.

It maybe this feature already exists or can be done another way, but we couldn't find it in the docs or a way to achieve this at the moment.

**Comment by cweijan** [comment]
If there is grouping, some tables must have the same prefix. Are there other clients that support table grouping?  

Also in the tree view, you can search the table with ctrl+f.

**Comment by WayneDK** [comment]
Hi, yes we are aware you can group using table prefixes and we do that, but sometimes you want to work with a group of tables with multiple prefixes, which is where a grouping feature would come in very handy at times.

I think Datagrip has this feature, but I'm not 100% sure, we appreciate it would be an unusual, but nonetheless very useful feature when working with large and complex databases. 

Hope that helps :) 

Database Client is a very good plugin by the way, miles ahead of anything else on VSC. Personally I stopped trying to use Datagrip, when I found Database Client. Very nice work, and well done. Worth every cent you are charging for it.

**Comment by cweijan** [comment]
Hi, I added options in version 5.7.6, supports grouping tables with the same prefix when the total number of tables exceeds a threshold.
I'll look for more conditions for grouping.
![image](https://user-images.githubusercontent.com/27798227/187477487-0d769948-cadc-434c-a8bb-56d88b182c26.png)
![image](https://user-images.githubusercontent.com/27798227/187477561-5a95b181-df23-458e-9b68-0b37d4a41af0.png)

**Comment by WayneDK** [comment]
That's great very responsive support. We do think this concept of being able to group tables is very useful when working with a big DB. Very glad you've taken this on, DataGrip is going to get a hiding from this plugin, you are doing a great job :)
