### ISSUE TITLE
Rename Server Type

### ISSUE THREAD

**Issue by silverbullettruck2001** [cweijan/vscode-mysql#670]
In the Connection screen you have a server type listed as `达梦` would it be appropriate to translate that to `Dameng` for English?  I am not familiar with `达梦` but I just noticed it and thought it might be good for consistency.

**Comment by cweijan** [comment]
Hi, "达梦" is a Chinese database that is only popular in China, I don't think anyone uses it except China.

**Comment by silverbullettruck2001** [comment]
I figured that, but I made the suggestion because it seems odd to have everything else translated on that screen.

**Comment by cweijan** [comment]
You are right, I will change it in the next version, it will only show Chinese when using Chinese language pack..

**Comment by cweijan** [comment]
Hi, I have renamed and released to version 5.7.6.

**Comment by silverbullettruck2001** [comment]
You could probably also update the `README.md` file so that it references `Dameng` instead of `达梦`
