### ISSUE TITLE
Multiple trigger scripts throw error [BUG]

### ISSUE THREAD

**Issue by silverbullettruck2001** [cweijan/vscode-mysql#671]
- OS: Mac
- Database Type: MySql

When updating multiple triggers in a single script file the following error is thrown:

```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '; drop trigger if exists trigger_name_here ; create trigger trigger_name_here' at line 1
```

I am not sure if doesn't like the `delimiter ~` that's needed to make it work for multiple statements in a single execution?  The exact same script works fine in MySql Workbench.

**Comment by cweijan** [comment]
Yes, there is no good support for delimiter, delimiter is implemented on the client side, mysql does not support this syntax.

**Comment by silverbullettruck2001** [comment]
but delimiter works fine when dealing with stored procedures and multiple statements, it just seems to have issues with triggers.  Could you see why triggers can't be handled similarly in the extension?

**Comment by cweijan** [comment]
Thanks for your feedback, I will strengthen support for triggers.

**Comment by cweijan** [comment]
Can you provide an example that doesn't work?

**Comment by silverbullettruck2001** [comment]
Here you go:
First create this test table:
```
create table test_table2 (test_data varchar(1));
```
Then run these statements:

```
delimiter ~
drop trigger if exists test_table2_trigger_before_insert ~
create trigger         test_table2_trigger_before_insert before insert on test_table2
  for each row
this_trigger:
  begin
    set @a = 1;
  end;
  ~

drop trigger if exists test_table2_trigger_after_insert ~
create trigger         test_table2_trigger_after_insert after insert on test_table2
  for each row
this_trigger:
  begin
    set @a = 1;
  end;
  ~

drop trigger if exists test_table2_trigger_before_update ~
create trigger         test_table2_trigger_before_update before update on test_table2
  for each row
this_trigger:
  begin
    set @a = 1;
  end;
  ~

drop trigger if exists test_table2_trigger_before_delete ~
create trigger         test_table2_trigger_before_delete before delete on test_table2
  for each row
this_trigger:
  begin
    set @a = 1;
  end;
  ~
delimiter ;
```

**Comment by cweijan** [comment]
Thanks.

**Comment by cweijan** [comment]
Hai, this is because you have the delimiter twice,
![image](https://user-images.githubusercontent.com/27798227/187959842-65d5a8f1-126f-4fcd-ab9c-078e273cdcc0.png)
Try modifying the sql to the following example.
Source:
```sql
begin
    set @a = 1;
  end;
  ~
```
To: 
```sql
begin
    set @a = 1;
  end~
```

**Comment by silverbullettruck2001** [comment]
I get that, but that is acceptable MySql syntax.  If I run that same statement in MySql Workbench it works just fine.

**Comment by cweijan** [comment]
No, this is not a syntax supported by mysql, whether you use the mysql command line or workbench, they process your sql on the client side, another similar command is source <sql_file>.

**Comment by cweijan** [comment]
I don't want to interfere with the user's SQL, so I don't think I can support it.

**Comment by silverbullettruck2001** [comment]
I am confused why you are saying you need to interfere with the user's SQL.  As I said, this works perfectly well with MySql Workbench.  I tried the exact statement in workbench and it did exactly what it was supposed to do, without error.

**Comment by cweijan** [comment]
Workbench is also just a mysql client. When you run sql, it will perform special processing on the delimiter and will not be sent to the server.

**Comment by silverbullettruck2001** [comment]
Oh, so you are just saying you are refusing to do the "special processing"?

**Comment by cweijan** [comment]
I have already done processing once for delimter. If I want to support your syntax above, it will affect the user's sql, which is risky.

` end; ~` will eventually be processed as `end;;`, and mysql does not support the existence of multiple;

**Comment by cweijan** [comment]
Your above sql will eventually be transformed into the following sql in database-client, which cannot be supported by mysql.
```sql
SELECT * FROM table_name3;;
SELECT * FROM table_name3;
```
![image](https://user-images.githubusercontent.com/27798227/188124814-8edee867-5ac6-4851-8eb4-d79d0f566756.png)

So if you use database-client, you cannot use multiple endings.

**Comment by cweijan** [comment]
If you want to execute it in database-client, it must be modified to the following SQL.
```sql
begin
    set @a = 1;
  end;
  ~
```
```sql
begin
    set @a = 1;
  end~
```
