### ISSUE TITLE
Extension Setting Name Incorrect[BUG]

### ISSUE THREAD

**Issue by silverbullettruck2001** [cweijan/vscode-mysql#673]
- OS: Mac
- Database Type: MySql

I noticed that one of the settings for this extension are spelled wrong.  In the screenshot below the word should probably be `Completion` instead of `Complection`:
![image](https://user-images.githubusercontent.com/26559157/187667197-ee90d239-a24c-42b4-a6a4-7023a2b9b5f3.png)

**Comment by cweijan** [comment]
Thank you for your feedback, I will correct it in the next version.

**Comment by cweijan** [comment]
Fix typo at version 5.7.8.
