### ISSUE TITLE
[BUG] After the query is stopped, it is still executed on the server.

### ISSUE THREAD

**Issue by sousagaspar** [cweijan/vscode-mysql#674]
- OS:Ubuntu 20.04
- Database Type:MySQL 5.7

When you run SQL statements that take a long time to execute, one can cancel the execution by pressing the "power off" button 
![image](https://user-images.githubusercontent.com/36577801/187895768-66fd8de6-884e-42ba-8741-c116c82295bc.png)
Although in the UI the execution of the statement was apparently stopped the execution is still alive in the database.
One can check it by executing: 

**SELECT * FROM INFORMATION_SCHEMA.PROCESSLIST WHERE USER = '<your_username_here>' ORDER BY TIME DESC;**

It would make sense that this _poweroff_ button, could retrieve the ID of the statement that is being stopped and kill it, i.e. by executing **KILL <_ID_>** where the **ID** is got from the PROCESSLIST table.

**Comment by cweijan** [comment]
Thanks for your feedback, but the client cannot cancel the executing SQL.

**Comment by sousagaspar** [comment]
Thank you for your feedback!

**Comment by sousagaspar** [comment]
@cweijan, I believe that client can do this. If the trash icon is clicked, under the woods it would execute:
1. SELECT id FROM INFORMATION_SCHEMA.PROCESSLIST WHERE USER = '<user_name>'  AND INFO = '<sql_statement_to_close>';
2. KILL id ; //got from previous statement

**Comment by cweijan** [comment]
Yes, but needs to create a new connection to close when the stop button is clicked, I will try to implement it in the future.

**Comment by cweijan** [comment]
I released the 5.9.3 version, and now it can correctly close the executing mysql connection.
