### ISSUE TITLE
Add RedisJSON support

### ISSUE THREAD

**Issue by CrazySky2121** [cweijan/vscode-mysql#675]
Hello! Please add [RedisJSON](https://redis.io/docs/stack/json/) support for Redis

**Comment by cweijan** [comment]
Thanks for your feedback, I will try to support it in future versions.

**Comment by cweijan** [comment]
Hi, I have released version 5.7.9, which now supports viewing of RedisJSON data, and I do not plan to provide operation RedisJSON.
![image](https://user-images.githubusercontent.com/27798227/188860387-a1cea1f8-5920-4e3a-98bb-e6480a79fa35.png)
