### ISSUE TITLE
Side feedback

### ISSUE THREAD

**Issue by cweijan** [cweijan/vscode-mysql#676]
@ruslaniv Hi sir, I see that the website is still accessible, can you tell me the situation on your side?

![image](https://user-images.githubusercontent.com/27798227/188572978-1aa94bb7-8fb4-43de-a3a6-fb37dbe62126.png)

**Comment by ruslaniv** [comment]
Hi! 
I was getting ERR_CONNECTION_RESET error, but now the site is back online

**Comment by cweijan** [comment]
Thanks for your feedback.
