### ISSUE TITLE
[BUG] The "path" argument must be of type string. Received an instance of Object

### ISSUE THREAD

**Issue by Xialuo781** [cweijan/vscode-mysql#677]
- OS: [debain](debian:10)
- Database Type: redis

**Comment by cweijan** [comment]
When did this error occur?

**Comment by Xialuo781** [comment]
> 

when i try to connect redis db

**Comment by cweijan** [comment]
Can you provide a screenshot so I can see the details? I can successfully connect to redis.
![image](https://user-images.githubusercontent.com/27798227/188859823-1d6d53ee-68da-49e2-8e61-57688617e7af.png)

**Comment by Xialuo781** [comment]
> Can you provide a screenshot so I can see the details? I can successfully connect to redis. ![image](https://user-images.githubusercontent.com/27798227/188859823-1d6d53ee-68da-49e2-8e61-57688617e7af.png)

![image](https://user-images.githubusercontent.com/39551241/188869071-54efa7f2-ecac-4319-8a21-d3e2310e92e7.png)

**Comment by cweijan** [comment]
Thanks for your feedback, I released 5.7.10 to fix this.
