### ISSUE TITLE
[BUG] Can't see my header column because of a UI glitch

### ISSUE THREAD

**Issue by PoloSherpas** [cweijan/vscode-mysql#679]
- OS: MacOs
- Database Type: MariaDB
My headers column of every table take random data values wich make the table unreadable.

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/84392413/190394652-8bb416d5-09d0-4f11-a01b-283e5f8f9979.png">

**Comment by cweijan** [comment]
Unfortunately, this is a bug caused by the official mariadb driver, I can't solve it.

@alejandro-du any idea?

**Comment by cweijan** [comment]
I suggest you use mysql to connect.

**Comment by alejandro-du** [comment]
That's strange. How is this caused by the driver? I've been using it and it always shows the header correctly.

**Comment by cweijan** [comment]
https://gist.github.com/cweijan/8c5982c699e57bef4ad857fba3d4f5fd

Look at line 53, meta returns wrong column data after queries.

**Comment by alejandro-du** [comment]
@cweijan - do you also get the incorrect headers?

**Comment by alejandro-du** [comment]
Have you discarded an encoding configuration issue? I'm not able to reproduce this behavior.

**Comment by cweijan** [comment]
It's weird that I can't reproduce it now, even switching back to an older version.
