### ISSUE TITLE
[BUG] cant configure multiple ftp accounts with my version

### ISSUE THREAD

**Issue by libiob** [cweijan/vscode-mysql#681]
- OS: Windows 11
- Database Type: Mysql / FTP editor

**Comment by cweijan** [comment]
If you mean to create multiple ftp connections, you need to click the create button multiple times, each connection page can only create one connection.
![image](https://user-images.githubusercontent.com/27798227/190537051-6f017164-ebdd-4f3e-8852-7d4f9b101110.png)
