### ISSUE TITLE
[BUG] Columns no longer show in tree view

### ISSUE THREAD

**Issue by gaberoffman** [cweijan/vscode-mysql#682]
- OS: MacOS Monterey 12.5.1
- Database Type: Postgres

In tree view, under columns, it now always reads "column pa.attidentity does not exist"

![Screen Shot 2022-09-20 at 4 55 37 PM](https://user-images.githubusercontent.com/2151662/191363118-e8faf704-4270-44a5-a876-d09c2ff4d5de.png)

**Comment by cweijan** [comment]
Can you show me a screenshot of your postgres version? I use 12.5 and it works fine.
![image](https://user-images.githubusercontent.com/27798227/191390481-77c65f67-35a8-494b-be4d-73fe9ca3056a.png)
If you want to connect to an older version of postgres, you need to choose redshfit.
![image](https://user-images.githubusercontent.com/27798227/191390630-e7afe44a-3d73-46ed-92b0-fe4e547791af.png)

**Comment by cweijan** [comment]
I released version 5.9.2 for compatibility with older versions of pg.
