### ISSUE TITLE
可否增加 mock 历史文件树

### ISSUE THREAD

**Issue by waset** [cweijan/vscode-mysql#683]
目前 mock 执行后切换表进行 mock 时会重置文件，每次都需要重新编写 mock 语法，可否增加 `按表保存 mock 文件,并增加历史文件树` 功能

**Comment by cweijan** [comment]
谢谢反馈, 下个版本优化

**Comment by cweijan** [comment]
Hi, 版本6.8.0已经将mock配置独立于每个表, 且重新点击时不会进行覆盖.
