### ISSUE TITLE
[BUG] 无法打开数据库终端

### ISSUE THREAD

**Issue by zhangjiankui** [cweijan/vscode-mysql#684]
- OS: MacOS 11.6
- Database Type: MySQL 5.7
- vscode: 1.68.1
- 版本：v5.8.0
点「打开终端」，不是直接打开已连接数据库的终端，而只是打印了要执行的命令
<img width="397" alt="image" src="https://user-images.githubusercontent.com/26133797/192960072-2e7aab3b-19af-4999-b6b3-73ff8aee7d0c.png">
<img width="469" alt="image" src="https://user-images.githubusercontent.com/26133797/192960361-7ec65cdc-7002-448b-97bc-f2b5a257032e.png">

**Comment by cweijan** [comment]
谢谢反馈, 已经发布5.8.1修复, 另外终端icon加载不出来是vscode的bug.
