### ISSUE TITLE
[BUG] redis refresh explore tree , can't get keys

### ISSUE THREAD

**Issue by zengLH1981** [cweijan/vscode-mysql#685]
- OS: windows 10
- Database Type: redis

1. click fresh icon after a node, it has some keys .
![image](https://user-images.githubusercontent.com/16136238/193038248-0ebcc2df-d12e-4b96-bd49-ae5d50183b76.png)

2. and then the keys are lost. and can't get back them ,even click more times
![image](https://user-images.githubusercontent.com/16136238/193038513-1ffbfc12-8924-4182-9c22-05f8d4f30f7b.png)

3. reconnection the redis. can then keys again
 
![image](https://user-images.githubusercontent.com/16136238/193038882-5eaa4ff1-efac-4aac-9411-37be905b4c43.png)

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Hi, I have released version 5.8.2 to fix.
