### ISSUE TITLE
[BUG] redis: missing the keys after edit its value

### ISSUE THREAD

**Issue by zengLH1981** [cweijan/vscode-mysql#686]
- OS: windows 10
- Database Type: redis

1. select a key in a folder, and then click [save]
![image](https://user-images.githubusercontent.com/16136238/193039359-86f99a8f-fa1c-4ff6-a28e-f87fbeb194f5.png)

2. all the keys in the folder are missing.
![image](https://user-images.githubusercontent.com/16136238/193039500-5cfddd6e-ad2a-4997-8202-3b2aa2e4fc16.png)

**Comment by cweijan** [comment]
Hi, I have released version 5.8.2 to fix.
