### ISSUE TITLE
[BUG] SQLite file can not be selected!

### ISSUE THREAD

**Issue by raad-altaie** [cweijan/vscode-mysql#687]
Using the path works fine, but the UI doesn't work (grayed out).
Thanks!
- OS: MacOS
- Database Type: SQLite 
<img width="1187" alt="Screen Shot 2022-09-30 at 4 35 57 PM" src="https://user-images.githubusercontent.com/28949554/193359821-a49b50ca-c45a-445f-b9d7-1a08cc8bfe50.png">
<img width="1060" alt="Screen Shot 2022-09-30 at 4 36 39 PM" src="https://user-images.githubusercontent.com/28949554/193359823-3e7da8cc-4e5b-41df-861e-6d52fd9aabea.png">

**Comment by cweijan** [comment]
Thanks for the feedback, does this happen with a new connection or an edited connection? I'll try to fix it as soon as possible.

**Comment by raad-altaie** [comment]
@cweijan it happens on both.
thanks!

**Comment by raad-altaie** [comment]
same problem with Windows 10; I believe you only allowed `.db` file extensions to be selected.

![Screenshot 2022-10-04 160836](https://user-images.githubusercontent.com/28949554/193929900-06181ada-c229-4b8e-95fd-11c350dd9cbf.png)

**Comment by cweijan** [comment]
Yes, I have limited support to select files with .db suffix only, I will remove this restriction in the next version.

**Comment by cweijan** [comment]
Hi sir, after 5.8.6, the selection of non-.db suffix has been supported.

**Comment by jar145** [comment]
Hi this problem is still present on macos.
