### ISSUE TITLE
[BUG] Connexion never opens

### ISSUE THREAD

**Issue by chrisptree** [cweijan/vscode-mysql#688]
- OS: CentOS Linux release 7.9.2009 (Core)
- Database Type: MariaDB
- Connexion over a ssh tunnel using a key
I'm using the free version.

Look a the output log:
```
2022-10-05 11:18:17 Reqeust to creating ssh tunnel for 1664977075618
2022-10-05 11:18:17 Creating ssh tunnel for <my jump ssh server>... remote:<db server ip>:3306, local port:12338 
2022-10-05 11:18:17 Create ssh tunnel success
2022-10-05 11:18:17 Creating connection for 1664977075618
```
Even after a very long period, the connexion is still in refresh mode:

![image](https://user-images.githubusercontent.com/8090476/194098869-00cd47c8-e2f9-4d7d-b30e-bb07c74cb312.png)

**Comment by cweijan** [comment]
Thanks for the feedback, I did not limit ssh connections for the free version, can you try using mysql to connect?

**Comment by chrisptree** [comment]
PS /home/cpoirier/psscripts> $sshSession.Session.ForwardedPorts

```
BoundHost : 127.0.0.1
BoundPort : 34325
Host      : <my database ip server>
Port      : 3306
IsStarted : True

PS /home/cpoirier/psscripts> mysql -h 127.0.0.1 -u <my username>-p -P $portNumber <db name>
Enter password: 
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 47068909
Server version: 10.1.38-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [<db name>]> 
```

**Comment by cweijan** [comment]
Hi sir, I mean using mysql server type.
![image](https://user-images.githubusercontent.com/27798227/194105470-96272a1d-8ba1-4e9d-b233-8df38651e382.png)

**Comment by chrisptree** [comment]
I have the same problem with the MySQL. I am using the SimplySql PowerShell module and it works fine with the same parameters.

**Comment by cweijan** [comment]
Sorry for this troble, I will try to fix it as soon as possible.

**Comment by cweijan** [comment]
I used the same mariadb version but it works fine.

Could you please open the developer tools? There may be other error logs here.
![image](https://user-images.githubusercontent.com/27798227/194226795-fc5a7d04-712f-4981-bcba-5e8ccba762c8.png)

**Comment by chrisptree** [comment]
When I click on the MySql button in status bar,
![image](https://user-images.githubusercontent.com/8090476/194365825-102d5082-4efe-49f5-9be5-6cd678c2e911.png)

And then I choose the connexion and the database
![image](https://user-images.githubusercontent.com/8090476/194351365-f7dfca95-0d51-4fbc-b5b7-ecabfc5348b5.png)

And then after the selection of the database, I have
![image](https://user-images.githubusercontent.com/8090476/194381430-2bac3085-68bf-46b4-8f3f-91f273a02741.png)
```
2022-10-06 13:36:39 Reqeust to creating ssh tunnel for 1664984903041
2022-10-06 13:36:39 Creating ssh tunnel for linux-util.teluq.ca... remote<db server ip>:3308, local port:10431 
2022-10-06 13:36:39 Create ssh tunnel success
2022-10-06 13:36:39 Creating connection for 1664984903041
```
And then, when I clique on >, I have this
![image](https://user-images.githubusercontent.com/8090476/194383818-55feb882-9613-400c-922b-49db4c6f3810.png)

There wasn't error in console log of the development tool.

I also tried with a small local database (without passing over a ssh tunnel), and it does the same.

When I try to close the connection, I have this log
`2022-10-06 14:01:08 Cannot read properties of undefined (reading 'provider')`

**Comment by cweijan** [comment]
Sorry sir, I think you are using remote-ssh, which I disabled in the free version.
