### ISSUE TITLE
Support vertical results view layout

### ISSUE THREAD

**Issue by macjabeth** [cweijan/vscode-mysql#691]
It would be nice if tables with many columns could be displayed vertically so we could scroll up and down rather than left and right.

![2022-10-11 at 14 31 05@2x](https://user-images.githubusercontent.com/8473052/195182787-9be67e67-7751-40b6-864d-f924c01b00de.png)

**Comment by cweijan** [comment]
What is the benefit of this feature? It can be implemented and I will adding it in future versions.

**Comment by macjabeth** [comment]
> What is the benefit of this feature?

It's a little easier (and quicker) to parse in some cases where there are lots of columns on a table. Especially because the columns are fixed width and sometimes I have to expand columns to see the full name of the column.

**Comment by cweijan** [comment]
Thanks for your description.

**Comment by cweijan** [comment]
I have released version 5.8.15, the data can be reversed by:
1. Check configuration to enable reverse switch.
![image](https://user-images.githubusercontent.com/27798227/199692167-77f71340-49aa-4978-9dfd-5c41ac12b263.png)
2. Toggles in the results view.
![image](https://user-images.githubusercontent.com/27798227/199692580-6b646264-a083-469a-be89-176cf151ca0d.png)
