### ISSUE TITLE
[BUG] Updating row with modified select statement

### ISSUE THREAD

**Issue by justinsvetlik** [cweijan/vscode-mysql#692]
When viewing a table, if you edit the SQL from `SELECT * FROM my_table` to `SELECT my_column FROM my_table` and then edit a column in a single row, all rows will update to that value. This issue occurs when editing in the grid or when selecting *Edit Row* from the context menu. The *Edit Row* dialog does show the id as unidentified. 

- OS: Windows 10
- Database Type: MySQL
- Extension Version: v5.8.6

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
I released version 5.8.7, now the update will not trigger when the primary key is null.

**Comment by justinsvetlik** [comment]
Thanks for taking care of this so quickly!
