### ISSUE TITLE
[BUG]  _isNewPush undefined

### ISSUE THREAD

**Issue by u007** [cweijan/vscode-mysql#694]
cannot update a enum field

<img width="630" alt="Screenshot 2022-10-17 at 1 41 11 PM" src="https://user-images.githubusercontent.com/388813/196098207-152c4ad1-a6f5-467f-8873-96bd56732e1b.png">

- OS: macos 12.6
- Database Type: postgresql
- Extension Version: v5.8.8

**Comment by u007** [comment]
perhaps u have some kind of unit test to test before release? thank you

**Comment by cweijan** [comment]
Thank you for your feedback, I have plans to add unit tests in the future, this bug is caused by filters, I released version 5.8.9 to fix it.
