### ISSUE TITLE
Quoting identifiers option

### ISSUE THREAD

**Issue by ExtraPawn** [cweijan/vscode-mysql#696]
The SQL standard states that identifiers are not case sensitive unless they are quoted. As a consequence, there are 2 database naming conventions concerning case sensitivity for database object identifiers :
- case insensitive : example : snake_case
- case sensitive : example : "MixedCase"  

But if you go for the case sensitive approach, you generally come up with the rule to *always* quote the identifier (even if the identifier is wholly in low case) to enforce consistency and tackle corner cases (conflicting names).

This extension takes care of quoting identifiers only if the identifier actually has mixed cases. Examples :
- firstName transforms to "firstName"
- name stays name

Is it possible to have an option to *always* quote the identifier ?

Such option would also handle table.column autocompletion : 
User.name would transform to "User"."name"

**Comment by cweijan** [comment]
Try configuring the options below:
`"database-client.escapedAllObjectName": true`

**Comment by ExtraPawn** [comment]
I saw that option, but it doesn't work (no change at all). My earlier example stays the same : 
- firstName transforms to "firstName"
- name stays name

I'm using the "Postgresql v5.8.6" extension on an ubuntu 22 machine.

**Comment by cweijan** [comment]
Did you mean columns or other objects? Now this option only works for table and database names.

**Comment by ExtraPawn** [comment]
I tested it and you're right, it works for tables and databases/schemas, but not columns.
It would be great if it was extended for columns though.
One thing I noticed also is that when a table name is quoted, there is no longer intellisense to pick its columns.

**Comment by cweijan** [comment]
Thanks for your feedback, I will enhance that in future versions.

**Comment by cweijan** [comment]
Support at version 2.8.13.

**Comment by lpzzz** [comment]
Another issue with setting "database-client.escapedAllObjectName": true.
- It would quote table names like
![image](https://user-images.githubusercontent.com/27475628/202658062-5f7ade08-ecbb-49ef-acc8-7f414c265378.png)
causing an error for MySql in my case.
- Switching this option to false would make it work only for mixed case object while lower case stays unquoted.

So, are there options
- excluding those table names.
- for case insensitive users that does not quote any object.

**Comment by cweijan** [comment]
Thanks for your feedback, I will add options to control it in future versions.
