### ISSUE TITLE
[BUG] Execution time shown incorrectly (easy to fix)

### ISSUE THREAD

**Issue by mudor-mt-dm** [cweijan/vscode-mysql#698]
When i start to resolve the query, the time is going ok: {seconds}s {miliseconds} ms
<img width="127" alt="image" src="https://user-images.githubusercontent.com/74766730/197773474-14ba2f00-a5ef-48e9-a8d7-e0b62b648300.png">
but then after minute it becomes failed: and seems like: {minutes}m {miliseconds} s
<img width="253" alt="image" src="https://user-images.githubusercontent.com/74766730/197772866-41619688-c31a-4eef-bc64-01524aef3c5c.png">
So i can't understand after minute what time spended to for execution, and also it looks like a terrible mistake, which is easy to fix.

- OS: WIndows 10
- Database Type: psotgesql
- Extension Version: v5.8.10

**Comment by cweijan** [comment]
Thanks for your feedback! I will fix it in the next version.

**Comment by mudor-mt-dm** [comment]
Wow, you replied so rapidly. Thank you for your labour 👍

**Comment by cweijan** [comment]
Fix at version 2.8.13.
