### ISSUE TITLE
Stop saving DB credentials in plain text in config.json

### ISSUE THREAD

**Issue by nikiluk** [cweijan/vscode-mysql#700]
I was surprised to see that database password was stored in the plain text of the `config.json`

This is not a secure way and this approach creates a potential vulnerability to anyone using the plugin.

![2022-10-25 1120x476 miFfj](https://user-images.githubusercontent.com/6605974/197806807-65aac233-bd74-4522-b95f-c66f8abff580.png)

**Comment by cweijan** [comment]
This configuration file is temporarily generated when you edit the configuration file, it will be deleted when you save it.

**Comment by nikiluk** [comment]
Thank you, @cweijan . Indeed, I can see that the file is being deleted. 
Where is this data saved then?

**Comment by cweijan** [comment]
The configuration is stored in the extension context provided by vscode, and only this extension can read it.

**Comment by sevetseh28** [comment]
> The configuration is stored in the extension context provided by vscode, and only this extension can read it.

Is it possible to store the configuration within `settings.json` ? I don't mind the password being in plain text because it's a development environment (`devcontainer`). Thanks!
