### ISSUE TITLE
[BUG] Sort indicator is not reset when switching to other collection

### ISSUE THREAD

**Issue by muhammadyusuf-kurbonov** [cweijan/vscode-mysql#701]
- OS: Fedora 36
- Database Type: MongoDB
- Extension Version: 5.8.11

I'm sorting items in the `partners` collection
![image](https://user-images.githubusercontent.com/45625440/198315069-c117b681-268f-429a-b5aa-48355a4ff672.png)

Then I switch to collection 'users' and see 
![image](https://user-images.githubusercontent.com/45625440/198315365-dc3c1d47-1c50-41ac-a407-99f08696decd.png)
The indicator is showing sort order desc, but no sorting. 

I think it should be reset (indicator set to default)

**Comment by cweijan** [comment]
Thanks for the feedback, the sort status here should be cleared, I'll fix it in the next version.

**Comment by cweijan** [comment]
Fix at version 2.8.13.
