### ISSUE TITLE
[BUG] - Export data from a table and Import data - Character ' not escaped 

### ISSUE THREAD

**Issue by ArmandArthur** [cweijan/vscode-mysql#703]
- OS: WSL2 Ubuntu
- Database Type: Mysql8
- Extension Version: Don't know

When you export the data from a table, the character ' is not escaped in the data.
So, it's generate error in import data.

Do you confirm it?

**Comment by cweijan** [comment]
Sir, consider installing mysqldump, when mysqldump is available, the extension uses it for export.

**Comment by ArmandArthur** [comment]
What is mysqldump? Extension vscode or php?

**Comment by cweijan** [comment]
It is a tool that comes with mysql installed. If you do not have mysql installed locally, you need to wait for me to support escaped object names later.
![image](https://user-images.githubusercontent.com/27798227/198882591-85de8294-7b39-4a41-b4e7-d55b504eee11.png)

**Comment by ArmandArthur** [comment]
I'm on Ubuntu 20.04 Windows WSL2.

**Comment by ArmandArthur** [comment]
sudo apt install mysql-client did the job.

**Comment by cweijan** [comment]
Yes, is the sql you can export now normal?

**Comment by ArmandArthur** [comment]
I think it's works if you do:

Right click on table => Export Data

But if you double click on the table and use the blue button export, it's not escaped.

**Comment by cweijan** [comment]
The export of the result page is not using mysqldump, thank you for your feedback, I will improve the exported sql in the future.

**Comment by ArmandArthur** [comment]
Thanks and good luck.

**Comment by cweijan** [comment]
When exporting, I will only escape table names that contain common keywords, if you want to escape all tables, please check this configuration.
![image](https://user-images.githubusercontent.com/27798227/199691584-990e7cce-5c72-4f3e-b2d5-b23b70dc708b.png)
