### ISSUE TITLE
[BUG] display does not support nested fields in Elasticsearch

### ISSUE THREAD

**Issue by NCG-Christof** [cweijan/vscode-mysql#704]
- OS: macOS
- Database Type: ElasticSearch
- Extension Version: v5.8.14

Our indexes in Elasticsearch contain nested fields. When connecting to the index only the root fields are displayed.
When exporting the data all fields are included.

[Screenshot](https://actualtransformation.com/wp-content/uploads/2022/10/CleanShot-2022-10-31-at-15.53.32.png)

`[
  {
    "_id": "rCCVLoQBen2zkLcWBE77",
    "_score": 1,
    "device.type": "Air Quality",
    "device.model": "SE-200P",
    "device.deployed": "2022-09-19T00:00:00.000Z",
    "device.removed": "2200-01-01T00:00:00.000Z",
    "device.platform": "Kaiterra",
    "device.uid": "854647fa-7231-443b-a5b0-6926b6d93344",
    "device.status": "true",
    "tags": "[\"kaiterra\",\"test\"]",
    "meta.floor": "Ground Floor",
    "meta.customer": "HIDDEN",
    "meta.coordinates": "{\"lat\":HIDDEN,\"lon\":HIDDEN}",
    "meta.lat": HIDDEN,
    "meta.long": HIDDEN,
    "meta.building": "HIDDEN",
    "meta.name": "Canteen",
    "meta.department": "department",
    "meta.location": "location",
    "reset.required": "false",
    "reset.send": "false",
    "reset.sku": "sku",
    "reset_required": "false",
    "reset_send": "false",
    "sku": "sku"
  }
]`

**Comment by cweijan** [comment]
Thanks for your feedback, I will support it in future versions.

**Comment by NCG-Christof** [comment]
Thanks, do you know how long it could take to include? We have a platform update that uses nested fields heavily. It would be helpful to retain management through your app

**Comment by cweijan** [comment]
I think I can get it done by the end of the week, if you could provide a config for an index and a row of data that would help me solve it better

**Comment by alejandrojn-ncg** [comment]
Hi,

Here's the index template for the example posted in the first message:

`PUT _index_template/metadata
{
  "index_patterns": [
    "*metadata"
  ],
  "template": {
    "settings": {
      "index": {
        "number_of_shards": "2",
        "auto_expand_replicas": "0-1"
      }
    },
    "mappings": {
      "properties": {
        "device.deployed": {
          "type": "date"
        },
        "device.removed": {
          "type": "date"
        },
        "device.status": {
          "type": "boolean"
        },
        "device.id": {
          "type": "keyword"
        },
        "device.model": {
          "type": "keyword"
        },
        "device.uid": {
          "type": "keyword"
        },
        "device.type": {
          "type": "keyword"
        },
        "device.platform": {
          "type": "keyword"
        },
        "meta.building": {
          "type": "keyword"
        },
        "meta.customer": {
          "type": "keyword"
        },
        "meta.department": {
          "type": "keyword"
        },
        "meta.floor": {
          "type": "keyword"
        },
        "meta.location": {
          "type": "keyword"
        },
        "meta.name": {
          "type": "keyword"
        },
        "meta.coordinates": {
          "type": "geo_point"
        },
        "meta.lat": {
          "type": "float"
        },
        "meta.long": {
          "type": "float"
        },
        "reset.sku": {
          "type": "keyword"
        },
        "reset.required": {
          "type": "boolean"
        },
        "reset.created": {
          "type": "boolean"
        },
        "reset.monitorid": {
          "type": "keyword"
        },
        "reset.send": {
          "type": "boolean"
        }
      }
    }
  },
  "composed_of": [
    "strings",
    "id-as-keywords"
  ],
  "priority": 4
}`

Here are the index settings:

`GET prod-metadata/_settings
{
  "prod-metadata": {
    "settings": {
      "index": {
        "routing": {
          "allocation": {
            "include": {
              "_tier_preference": "data_content"
            }
          }
        },
        "number_of_shards": "2",
        "auto_expand_replicas": "0-1",
        "provided_name": "prod-metadata",
        "creation_date": "1667228828696",
        "number_of_replicas": "1",
        "uuid": "My0lXJBjTjeNBKjFUHi9fA",
        "version": {
          "created": "8040199"
        }
      }
    }
  }
}`

And here is an document example:

`POST prod-metadata/_doc
{
  "device.type": "Air Quality",
  "device.model": "SE-200P",
  "device.deployed": "2022-09-19T00:00:00.000Z",
  "device.removed": "2200-01-01T00:00:00.000Z",
  "device.platform": "Kaiterra",
  "device.uid": "854647fa-7231-443b",
  "device.status": "true",
  "tags": [
    "kaiterra",
    "test"
  ],
  "meta.floor": "Ground Floor",
  "meta.customer": "customer",
  "meta.coordinates": {
    "lat": 13.45474956505959,
    "lon": 16.203807478831122
  },
  "meta.lat": 13.45474956505959,
  "meta.long": 16.203807478831122,
  "meta.building": "building",
  "meta.name": "name",
  "meta.department": "department",
  "meta.location": "location",
  "reset.required": "false",
  "reset.send": "false",
  "reset.sku": "sku",
  "reset_required": "false",
  "reset_send": "false",
  "sku": "sku"
}`

Please let us know if you need more information.

Thanks!

**Comment by cweijan** [comment]
Sir, I have found the reason, it will support display after the next version update.

It cannot be displayed now because the index is not declared as nested type. If nested is declared, it is supported to display, refer to the link below.

https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html

**Comment by NCG-Christof** [comment]
Thank you, we will look at that. Appreciate it.

**Comment by alejandrojn-ncg** [comment]
Hi, 

We are not interested in nested fields, we want object fields: https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html#object

Please ignore the document from my previous message, here's the correct document we want to visualise with the object fields:
```
POST prod-metadata/_doc
{
  "device": {
    "type": "Air Quality",
    "model": "SE-200P",
    "deployed": "2022-09-19T00:00:00.000Z",
    "removed": "2200-01-01T00:00:00.000Z",
    "platform": "Kaiterra",
    "uid": "854647fa-7231-443b",
    "status": "true"
  },
  "tags": [
    "kaiterra",
    "test"
  ],
  "meta": {
    "floor": "Ground Floor",
    "customer": "customer",
    "coordinates": {
      "lat": 13.45474956505959,
      "lon": 16.203807478831123
    },
    "lat": 13.45474956505959,
    "long": 16.203807478831123,
    "building": "building",
    "name": "name",
    "department": "department",
    "location": "location"
  },
  "reset": {
    "required": "false",
    "send": "false",
    "sku": "sku"
  }
}
```

And here's what this document looks like on VSCode: [Screenshot](https://actualtransformation.com/wp-content/uploads/2022/11/CleanShot-2022-11-02-at-11.56.33.png)

We'd like to have each field from the object field on a separate column.

Let us know if you need more information.

Thanks in advance.

**Comment by cweijan** [comment]
Shows like this, right?
![image](https://user-images.githubusercontent.com/27798227/199486165-10a71527-c573-467a-a7d0-0d120839279b.png)

**Comment by alejandrojn-ncg** [comment]
Yes, exactly, that's what we need, it's looking great!

**Comment by cweijan** [comment]
I have released version 5.8.15 to support it.

**Comment by NCG-Christof** [comment]
We have updated our version but the fields within the objects are not being displayed. See below
![CleanShot 2022-11-03 at 11 19 27@2x](https://user-images.githubusercontent.com/87822627/199708285-a508d887-b12a-47ab-8dfd-6b4f6a46e707.png)

**Comment by cweijan** [comment]
If you have specified the type as object for the field, it will indeed display like this.

Only data added via the following methods is supported.
![image](https://user-images.githubusercontent.com/27798227/199709461-294df005-78af-4980-92d8-9ec986bde627.png)
