### ISSUE TITLE
[BUG] Database Explorer icon disappears from VS Code sidebar on 5.8.15

### ISSUE THREAD

**Issue by bamill88** [cweijan/vscode-mysql#705]
- OS: Windows 10, 21H2
- Database Type: Any
- Extension Version: 5.8.15

I have been using this extension for several days now, all has been fine. I was using my laptop this morning until about 10:30 EST, with the extension working fine. I moved to my desktop where VS Code had just installed updates, and the Database Explorer icon disappeared. The NoSQL icon is still present.

![image](https://user-images.githubusercontent.com/549684/199753658-135cb397-b671-4826-aadc-33c4a665a8f3.png)

I checked that the extension icon was not hidden by the UI:
![image](https://user-images.githubusercontent.com/549684/199753801-e2036476-006f-4769-9d0c-4a0e4ecc2486.png)

It looks like this version (5.8.15) was pushed today, perhaps it introduced this bug?

Thanks

**Comment by cweijan** [comment]
Hi, can you try restarting vscode? It working for me.

**Comment by bamill88** [comment]
I have restarted VS Code several times. I disabled/enabled the extension, I also tried uninstalling and reinstalling the extension. The icon is still missing.

I'll try restarting Windows to see if that makes any difference.

**Comment by bamill88** [comment]
Not sure if this will help at all:
![image](https://user-images.githubusercontent.com/549684/199755131-0b88ba8d-b22a-4d48-bb0e-f76f3b190f95.png)

**Comment by cweijan** [comment]
I am also using 1.73.0, need to see if other people have this situation too.

Please try opening the developer tools and let me see if there is any error message, open command palette, then:
![image](https://user-images.githubusercontent.com/27798227/199755915-2988ddc8-af76-4db2-a450-f7959abf07cb.png)
![image](https://user-images.githubusercontent.com/27798227/199756171-ac7d25f6-7be3-4b44-adc3-021d488a23f3.png)

**Comment by bamill88** [comment]
This error only occurs when the MySQL extension is enabled:
![image](https://user-images.githubusercontent.com/549684/199758911-826616df-8c55-4532-be2c-1fa67e4886f2.png)

**Comment by cweijan** [comment]
It is not caused by this error, I think it is because the database panel was accidentally dragged to another place and closed, please try to create a new database connection.

Create from nosql panel.
![image](https://user-images.githubusercontent.com/27798227/199760454-8cb6e6bf-d00e-4875-9f56-2371e2935bfc.png)

**Comment by bamill88** [comment]
> It is not caused by this error, I think it is because the database panel was accidentally dragged to another place and closed, please try to create a new database connection.

This is exactly what happened, except it wasn't an accident. I moved the database window to the bottom half of the sidebar. I did not realize this removed the icon from the sidebar navigation.

I apologize for the false alarm, and I appreciate your quick and thorough responses. Thanks for making a great product!
