### ISSUE TITLE
When executing selected SQL statement automaticly erasing any other statment 

### ISSUE THREAD

**Issue by Andre-Lopes13** [cweijan/vscode-mysql#706]
Hello, i would like to know if its possible to run a selected SQL line without automaticly erase others lines written on my sql text box .

**Comment by cweijan** [comment]
Not currently supported, but it's a good idea and I'll support it in a future version.

**Comment by cweijan** [comment]
I have released 5.8.16 version support, pay attention to the shortcut key of ctrl(cmd)+enter.
