### ISSUE TITLE
介绍信息太多的时候 显示有问题[BUG]

### ISSUE THREAD

**Issue by miaokela** [cweijan/vscode-mysql#707]
<img width="467" alt="1" src="https://user-images.githubusercontent.com/30903265/199927384-1da3bf72-7abb-472f-9301-801d56f96aa0.png">

**Comment by miaokela** [comment]
不对，是comment中包含空格，显示就会有问题

**Comment by cweijan** [comment]
好, 谢谢反馈哈, 我下版本优化下.

**Comment by cweijan** [comment]
已发布版本5.8.16修复.
