### ISSUE TITLE
添加果中显示字段的类型

### ISSUE THREAD

**Issue by joyous-coder** [cweijan/vscode-mysql#708]
如题 有的时候需要查看sql结果字段的类型。如果功能不集成，就需要打开每个表格去查看类型，很是不方便。
![image](https://user-images.githubusercontent.com/42910684/200116147-aff0470a-3275-4fe4-a9a1-20220a318798.png)
dbeaver 中会使用图标在字段上表示，希望扩展也能支持这个功能。   已付费支持

**Comment by cweijan** [comment]
你是指多表吗。单表现在有显示的

**Comment by joyous-coder** [comment]
多表

**Comment by cweijan** [comment]
嗯，在后续版本逐步支持

**Comment by cweijan** [comment]
已发布版本5.8.16支持.
