### ISSUE TITLE
Has the search been deleted?

### ISSUE THREAD

**Issue by mirkadev** [cweijan/vscode-mysql#709]
Hi! Today I find that the search by the result is lacking. Did you remove it?

**Comment by cweijan** [comment]
can you give me a screenshot?

**Comment by mirkadev** [comment]
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/45996373/200285761-a752a2b9-0dd2-47c1-ac95-73a4baa015ab.png">

**Comment by cweijan** [comment]
I didn't remove it, but there is a display bug in the old version, what is your extension version?

**Comment by mirkadev** [comment]
Oh, I updated it and it works now. Thanks

**Comment by cweijan** [comment]
Thanks your feedback.
