### ISSUE TITLE
[BUG] Incorrect encoding for coordinates

### ISSUE THREAD

**Issue by mirkadev** [cweijan/vscode-mysql#710]
- OS: macOS Monterey 12.6
- Database Type: MySQL
- Extension Version: v5.8.16

Hi! I have incorrect encoding for coordinates

<img width="351" alt="image" src="https://user-images.githubusercontent.com/45996373/200286419-038711bb-a085-419e-b7ec-bdfb342609ff.png">

**Comment by cweijan** [comment]
What type is this column? Usually it depends on your table or column definition, please try other tools to see if it can display properly.

**Comment by mirkadev** [comment]
This is a `point` [type](https://dev.mysql.com/doc/refman/5.7/en/gis-data-formats.html#:~:text=MySQL%20supports%20geometry%20types%20of,geometry%20types%20are%20not%20supported.) 

Yes, in the `Beekeeper Studio` app it shows ok for me

**Comment by mirkadev** [comment]
How I see it in another app
<img width="334" alt="image" src="https://user-images.githubusercontent.com/45996373/200288064-bdef1a75-47db-4425-827e-5167a840262e.png">

**Comment by cweijan** [comment]
Thanks for your feedback, I will support point in the next version.

**Comment by cweijan** [comment]
I released version 5.9.0 to support display point.

**Comment by mirkadev** [comment]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/45996373/200850664-12124f91-c897-4ec2-84b9-a5d5eccd1b52.png">
amazing! Big thank you!
