### ISSUE TITLE
[BUG] 2 copies of each icon in explorer view column

### ISSUE THREAD

**Issue by nxgnme** [cweijan/vscode-mysql#711]
- OS: vscode remote ec2 linux connected from windows10 
- Database Type: rds mysql
- Extension Version: v5.8.16

In explorer column view I have duplicate icons showing for 
setting, sync, history, refresh, collapse all, new connection

all sub row icons also duplicate 
open in new panel, select table 

- 
![image](https://user-images.githubusercontent.com/60792522/200302962-2665f153-cc28-4559-99a2-7259c6352f2b.png)

**Comment by cweijan** [comment]
Hi sir, I have released extensions with different names but the same function, please uninstall the duplicate ones.
