### ISSUE TITLE
[BUG] last update errors with SSH

### ISSUE THREAD

**Issue by gzlo** [cweijan/vscode-mysql#712]
Last update do nit let me conect to my dropplets in DO ... i set everything but cant reach the server .... it is not working ... i test it uot directly for my console and works fine

**Comment by cweijan** [comment]
Did you mean that the latest version update caused the connection to fail?

This extension is not able to connect to all ssh servers.

**Comment by gzlo** [comment]
Yes, just 30 minutes ago i was updating all my ssh connections, and i saw the update and "reload required" in the vscode extensions menu just right after the update it closes everything  ... and said "All configured authentication methods failed" .... so i check connecting via other method to my server and every works fine ... i checked the "remote SSH" extension to be sure that it was not my config setting, but everything seems to be working with that ... so that's why i'm reporting the issue ... i really linke you extension, thats why i paid for it to support your work .... it a very nice job !!!!

**Comment by cweijan** [comment]
This is weird, I can get it to work, what is the error the extension is showing now?

Also try clicking install back to the old version.
![image](https://user-images.githubusercontent.com/27798227/200351884-8d9e46cd-cf7d-4bee-b10a-c280a37f0571.png)

**Comment by cweijan** [comment]
In addition, please open the developer tools and see what the error message in the console is.

![image](https://user-images.githubusercontent.com/27798227/200352680-0aae285e-676f-42a5-b7af-7b61e2823006.png)

**Comment by gzlo** [comment]
![image](https://user-images.githubusercontent.com/69698682/200353649-f6d8ac7d-7f7b-4e7c-af91-f7ef5feb6d5a.png)

**Comment by cweijan** [comment]
I think it may be related to your ssh configuration, the configuration file is not saved properly when updating.

Do you have backup configuration files?

**Comment by gzlo** [comment]
yes, i have one ... but it weird ... last time i set my dropplets and add the ssh config setting works fine and i'm using the same ssh key to all my stuff. 
just know when i roll back one of my connections works fine

**Comment by cweijan** [comment]
I have no work involving ssh in the latest version, can you try to recreate the connection?

**Comment by gzlo** [comment]
i recreate all 3 connections, nothing works ... i guess it's me but i had a connections using only pass words and no results

**Comment by cweijan** [comment]
Have you recently modified your key format? Some ssh key formats are not available with this extension.

**Comment by gzlo** [comment]
i just use the command  ssh-keygen without passphrase, using the comand line ... and generating te id_rsa and id_rsa.pub files

**Comment by cweijan** [comment]
This means that the connection is not due to a version update, but the key has been modified. The ssh command is usually compatible with different keys, but this extension does not.

I'm not an expert on ssh and can't help you, please consider regenerating ssh keys by other methods.

**Comment by gzlo** [comment]
nothing eork .... i'll let you know if something changes

**Comment by cweijan** [comment]
Is it still working normally now? This may be related to the location of the key, try to manually select the location of the key.

![image](https://user-images.githubusercontent.com/27798227/201977368-65382c52-d8e0-48f4-8539-d3926fae1a5b.png)

**Comment by cweijan** [comment]
Hi, I have confirmed that this is a problem caused by the key format. The new version of openssh no longer supports the default ssh-rsa key. You need to use `ssh-keygen -t ed25519` to generate the ed25519 key.

Refer to the following issue, https://github.com/cweijan/vscode-database-client/issues/737.
