### ISSUE TITLE
[BUG] Cannot use single quotes when modifying data.

### ISSUE THREAD

**Issue by pedrodiassousa** [cweijan/vscode-mysql#713]
- OS: Windows 10
- Database Type: MY SQL
- Extension Version: 8.0.26

I have the need to use queries inside cells in databases, a JSON like format, the thing is, after yesterday 10/11/2022, I lost the ability to use ' ' in my queries, appear has a Syntax Error, for example:

{
    "commands": [
        {
            "command": {
                "query": {
                    "rawFields": " CDM_CustomerBalances.CustomerID AS F1, CDM_CustomerBalances.OpeningDebitBalance AS F2, CDM_CustomerBalances.ClosingDebitBalance as F3, CDM_CustomerBalances.SelfBillingIndicator, CDM_CustomerBalances.ParentID AS FKID",
                    "from": "CDM_CustomerBalances",
                    "where": " CDM_CustomerBalances.OpeningDebitBalance NOT REGEXP '^[+-]\?([0-9]{1,18}.[0-9]{1,2})' "
                }
            }
        }
    ]
}

'^[+-]\?([0-9]{1,18}.[0-9]{1,2})' the carathers ' ' nesting the REGEXP are returning the following error:

SQL:  UPDATE `Nc_Rules` SET `Content`='{ "commands": [ { "command": { "query": { "rawFields": " CDM_CustomerBalances.CustomerID AS F1, CDM_CustomerBalances.OpeningDebitBalance AS F2, CDM_CustomerBalances.ClosingDebitBalance as F3, CDM_CustomerBalances.SelfBillingIndicator, CDM_CustomerBalances.ParentID AS FKID", "from": "CDM_CustomerBalances", "where": " CDM_CustomerBalances.OpeningDebitBalance NOT REGEXP '^[+-]\\?([0-9]{1,18}.[0-9]{1,2})' " } } } ] }' WHERE `ID`=1029;

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[+-]\\?([0-9]{1,18}.[0-9]{1,2})' " } } } ' at line 8 

Please help! <3

**Comment by cweijan** [comment]
Sorry for the trouble , I have released version 5.9.1 to fixed.
