### ISSUE TITLE
[BUG] license switch to free after 5 days

### ISSUE THREAD

**Issue by spham** [cweijan/vscode-mysql#714]
license issue after some days use
how to get offline license ?

**Comment by cweijan** [comment]
Hi, what is the status of your current premium? It is possible that you have used the wrong email to log in.

You can provide the machine id, and I will provide you with the offline activation code.
![image](https://user-images.githubusercontent.com/27798227/201951067-b2ac2b86-ac96-442a-abe0-843f6c18e376.png)
