### ISSUE TITLE
[BUG] The blob column cannot be queried 

### ISSUE THREAD

**Issue by wangbocai1997** [cweijan/vscode-mysql#715]
- OS:windows10
- Database Type: oracle 12c
- Extension Version:v5.9.1
- 

create table tlob(c1 clob, c2 blob);
insert into tlob values('1', '1');
select * from tlob;

Following the preceding steps, the following error occurs

SQL:  select * from tlob;

socket hang up

**Comment by cweijan** [comment]
Thank you for your feedback, I released the database-client-jdbc1.2.1 version, and now it can return data normally when it contains blob type. You need to close the Java program after updating, if you don't know how to close it, please restart your computer.

But it still does not support the operation of blob data, and I will gradually support the support for binary data in the future.

**Comment by wangbocai1997** [comment]
不会报错了，但是查询结果会提示不支持blob

**Comment by cweijan** [comment]
已发布版本6.8.9支持blob的16进制显示, 需要更新dbclient-jdbc到1.3.0版本, 如果无法正常工作则重启下计算机.
