### ISSUE TITLE
Replication support (reader and writer endpoint)

### ISSUE THREAD

**Issue by aprilmintacpineda** [cweijan/vscode-mysql#716]
So we run a aurora-mysql database cluster and it has 2 endpoints, one endpoint is for `read`, e.g., `select * from table` and the other endpoint is for `write`, e.g., `insert into table ...values`, can you please add support for that? Here's a useful docs of the library we use in our NodeJS app https://sequelize.org/docs/v6/other-topics/read-replication/

**Comment by cweijan** [comment]
I will not support it, the database that supports write operations also supports reading, this extension will only create a connection for mysql, and will not affect the database.
