### ISSUE TITLE
The connection screen does not open.

### ISSUE THREAD

**Issue by SouL-H** [cweijan/vscode-mysql#718]
Hello, I was using the app very well before. But for a few days, when I want to add a new link, the page is blank. I uninstalled the app and reinstalled it but it didn't work. Can you help with the solution?

![Screenshot 2022-11-21 at 10 53 43](https://user-images.githubusercontent.com/26456702/202996989-f529fc5b-e54f-41a0-a975-7b42da37e0d4.png)

**Comment by cweijan** [comment]
This is strange, please let me see the error log by following the steps below:
![image](https://user-images.githubusercontent.com/27798227/202997538-b38525b9-8c63-4a3d-bdf5-07053d1998ce.png)
![image](https://user-images.githubusercontent.com/27798227/202997489-9cfee98d-1e98-4dc6-815d-0449424e11c2.png)
![image](https://user-images.githubusercontent.com/27798227/202997675-891e2a79-b4d9-41d8-9344-0ff1fe749c65.png)

**Comment by SouL-H** [comment]
Sure:

![Screenshot 2022-11-21 at 11 17 24](https://user-images.githubusercontent.com/26456702/202999061-f9c60a18-9792-4d07-962e-8357a711f527.png)

**Comment by cweijan** [comment]
Thank you, this seems to be an incompatibility problem caused by vscode upgrade, I will release a compatible version soon.

**Comment by SouL-H** [comment]
Thank you very much for your quick turnaround. I manually imported your previous version 5.8.14. But I had the same problem again, I would like to inform you.

**Comment by cweijan** [comment]
Hi, I released version 5.9.2, to see if it works.

**Comment by SouL-H** [comment]
Thanks, the problem fixed 👌

![Screenshot 2022-11-21 at 12 03 37](https://user-images.githubusercontent.com/26456702/203009250-54309ca8-6646-47dc-aab1-6c44b3742ee8.png)

**Comment by cweijan** [comment]
Thanks your feedback.
