### ISSUE TITLE
隐式连接后数据库设置别名后只有第一个别名有字段提示, 剩下的别名都没有[FEATURE]

### ISSUE THREAD

**Issue by izilongwan** [cweijan/vscode-mysql#720]
- OS: 1.662
- Database Type:MySQL
- Extension Version:5.92
希望所有别名都有字段提示

**Comment by cweijan** [comment]
你说的数据库别名是什么? 表别名是可以正常显示字段的.

**Comment by izilongwan** [comment]
> 你说的数据库别名是什么? 表别名是可以正常显示字段的.

只有设置的第一个表的别名有字段提示，第2个之后就都没有，但是用原表名可以访问

**Comment by cweijan** [comment]
我这里是正常的, 你再试试看?

**Comment by izilongwan** [comment]
> 我这里是正常的, 你再试试看?
![image](https://user-images.githubusercontent.com/48234072/203789545-3255e25e-4b58-4a24-abf8-add57e2a5dc1.png)
能看到吗

**Comment by izilongwan** [comment]
> > 我这里是正常的, 你再试试看?
> > ![image](https://user-images.githubusercontent.com/48234072/203789545-3255e25e-4b58-4a24-abf8-add57e2a5dc1.png)
> > 能看到吗

而且别名和字段都爆红了

**Comment by cweijan** [comment]
哦哦, 是因为不支持这种隐式join, 只支持显式join的补全.

**Comment by izilongwan** [comment]
> 哦哦, 是因为不支持这种隐式join, 只支持显式join的补全.

而且别名和字段都爆红了也是这个原因吗

**Comment by cweijan** [comment]
爆红只是你的主题把这些显示成了红色.

**Comment by izilongwan** [comment]
> 爆红只是你的主题把这些显示成了红色.

![B1130C12-D017-46ED-BBCA-4E805451F52C](https://user-images.githubusercontent.com/48234072/203791614-f5724783-b50a-4cfc-8bf1-05696c22aaf3.png)
好吧，设置别名后是另一种高亮

**Comment by izilongwan** [comment]
> 

这个弄起来困难吗

**Comment by izilongwan** [comment]
> 哦哦, 是因为不支持这种隐式join, 只支持显式join的补全.

这个弄起来困难吗

**Comment by cweijan** [comment]
我试试看能不能支持下.

**Comment by izilongwan** [comment]
> 我试试看能不能支持下.

好的，加油大佬

**Comment by cweijan** [comment]
在版本6.0.6之后已经支持.
