### ISSUE TITLE
[BUG] poostgresql generate mock data，Run Mock get error "function max(uuid) does not exist"

### ISSUE THREAD

**Issue by Eden-Harris** [cweijan/vscode-mysql#722]
<img width="644" alt="image" src="https://user-images.githubusercontent.com/28903167/203462017-dc8d58f0-1063-468d-a850-2c160b0422e2.png">

- OS: macos 12.6 (21G115)
- Database Type: postgresql 13
- Extension Version: 5.9.2 2022-11-21

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Fix at version 5.9.3.
