### ISSUE TITLE
postgres的sql代码提示

### ISSUE THREAD

**Issue by LimLLL** [cweijan/vscode-mysql#723]
请问后续会添加更多的postgres的sql代码提示咩，比如 over (partition by) 或者 json_array_elements这种

**Comment by cweijan** [comment]
会的, 只是我不知道有哪些常用的, 你说的这两个我会去调研.

**Comment by izilongwan** [comment]
> 会的, 只是我不知道有哪些常用的, 你说的这两个我会去调研.

![image](https://user-images.githubusercontent.com/48234072/203788368-9240c7e5-79d6-4e88-b7bb-ba0c8b29c0f1.png)
这2个咋没高亮
