### ISSUE TITLE
[BUG] Cannot Save Changes to Data

### ISSUE THREAD

**Issue by pedrodiassousa** [cweijan/vscode-mysql#724]
- OS: Windows 10
- Database Type: MySQL
- Extension Version: 8

**Comment by cweijan** [comment]
Can you provide error messages and screenshots?

**Comment by pedrodiassousa** [comment]
![image](https://user-images.githubusercontent.com/114767425/204020151-68146110-47a8-4553-96f2-3e9bd4555ca7.png)

When I make a query, and go in to change values, the save button is missing or even if I change change values and press Enter the value doesn't save

**Comment by cweijan** [comment]
I think your table does not have a primary key, and currently only supports editing tables with primary keys.

**Comment by pedrodiassousa** [comment]
![image](https://user-images.githubusercontent.com/114767425/204020726-8a1736e0-f062-44e6-8007-3fbcdce48818.png)
Hmm, do you refer to the first column?

**Comment by cweijan** [comment]
It seems that your table does not have the id column as a primary key. 

Consider creating primary key by following SQL.
`ALTER TABLE Nc_Rules ADD PRIMARY KEY (ID);`

**Comment by pedrodiassousa** [comment]
Issue was only happening in that specific query, dont know why, thank you for your time anyways

**Comment by cweijan** [comment]
Hi, I have released version 6.0.0 to support deleting data for tables without primary keys.

**Comment by pedrodiassousa** [comment]
Thanks man, great work you are doing

Weijan Chen ***@***.***> escreveu no dia terça, 6/12/2022
à(s) 11:10:
