### ISSUE TITLE
[BUG] 插件在Remote SSH登录服务器后不会不显示任何结果

### ISSUE THREAD

**Issue by LimLLL** [cweijan/vscode-mysql#725]
- OS: Windows 10
- Database Type: Postgres
- Extension Version: Newest Version

vscode用remote ssh进入远程服务器后（远程服务器也安装个database client插件），点击table不显示任何内容（有时候会显示，概率非常小），同时运行图片里的代码也不会显示任何结果（同样非常小概率会显示），不太清楚是remote ssh问题还是咱们插件问题诶。在本地端没有任何问题，就是使用remote ssh后出现的问题
![9466055b3b7fba3a05353894406cf9d](https://user-images.githubusercontent.com/59259075/204084301-e28758a4-d37c-4140-a3d2-946e9525baef.png)

**Comment by cweijan** [comment]
应该是扩展自动更新了, 重启一下VSCode.

**Comment by LimLLL** [comment]
> 应该是扩展自动更新了, 重启一下VSCode.

不行诶，还是有这个问题

**Comment by cweijan** [comment]
有时候会显示.. 那有可能是你这服务器带宽问题. 视图资源文件还没加载完成.

如果还是不行, 尝试打开开发者工具,  把错误日志给我看看.
![image](https://user-images.githubusercontent.com/27798227/204085000-54dd6b35-abb9-4c7b-85bf-b273bfad76f4.png)
![image](https://user-images.githubusercontent.com/27798227/204084993-ff3e70f2-5535-41fd-9896-0fd8e2799a8e.png)

**Comment by LimLLL** [comment]
> 有时候会显示.. 那有可能是你这服务器带宽问题. 视图资源文件还没加载完成.
> 
> 如果还是不行, 尝试打开开发者工具, 把错误日志给我看看. ![image](https://user-images.githubusercontent.com/27798227/204085000-54dd6b35-abb9-4c7b-85bf-b273bfad76f4.png) ![image](https://user-images.githubusercontent.com/27798227/204084993-ff3e70f2-5535-41fd-9896-0fd8e2799a8e.png)

![Quicker_20221126_185214](https://user-images.githubusercontent.com/59259075/204085238-094b636c-5f9a-4f58-9f28-c82497804ceb.png)
这个是我服务器连接vscode extension market失败的原因嘛

**Comment by cweijan** [comment]
看起来没有因为这个扩展导致的错误, 方便加下我qq吗, 1443931123.

**Comment by cweijan** [comment]
Hi, 尝试最新发布的2.9.3版本, 我对界面做了些优化, 但不知道是否能够解决你这个问题.

**Comment by LimLLL** [comment]
> Hi, 尝试最新发布的2.9.3版本, 我对界面做了些优化, 但不知道是否能够解决你这个问题.

好的，我现在测试一下，感谢

**Comment by LimLLL** [comment]
> Hi, 尝试最新发布的2.9.3版本, 我对界面做了些优化, 但不知道是否能够解决你这个问题.

问题还是存在诶，第一次remote连接上后第一次运行代码可以正常显示，把结果窗口关了以后，第二次运行代码还是会出现上述情况

**Comment by cweijan** [comment]
由于不是扩展引起的, 关闭该问题.
