### ISSUE TITLE
select * from XXX 的时候不会默认分页吗？

### ISSUE THREAD

**Issue by joyous-coder** [cweijan/vscode-mysql#726]
如题，好像一次把全表查出来了，大表会很慢。 之前有用过其他数据库客户端，往往会默认查询1000条，然后带着页码的方式

**Comment by cweijan** [comment]
不会分页. 我看有没有办法优化, 最好还是你自己带上分页限制.

**Comment by joyous-coder** [comment]
这个还是挺有用的，自动分页并带上页码会极大提升查询体验

**Comment by cweijan** [comment]
已在版本6.2.6自动对SQL分页.
