### ISSUE TITLE
[BUG] Elasticsearch doesn't filter properly by context menu.

### ISSUE THREAD

**Issue by zengLH1981** [cweijan/vscode-mysql#727]
- OS: Windows
- Database Type: ElasticSearch
- Extension Version: v5.9.3

Right click a cell
select filter by xxx > 1 , xxx is NULL, xxx like 
alll generate eqls are equal

![image](https://user-images.githubusercontent.com/16136238/205281123-28782f98-9657-4c98-b690-b4934f24b042.png)

**Comment by cweijan** [comment]
Thanks for the feedback, I will fix it in a future version.

**Comment by cweijan** [comment]
The bug has been fixed.
