### ISSUE TITLE
[BUG] 无法选择记录！！

### ISSUE THREAD

**Issue by zty012** [cweijan/vscode-mysql#728]
- OS:windows10
- Database Type:sqlite3
- Extension Version:5.9.3

![image](https://user-images.githubusercontent.com/89395757/205647911-9f0d73e4-1f13-4c72-bc0c-7c2f45b187f1.png)
↑如图，没有复选框

**Comment by cweijan** [comment]
Hi, 你的表应该没有主键, 下版本会支持没有主键表的操作.

**Comment by zty012** [comment]
``

**Comment by zty012** [comment]
> Hi, 你的表应该没有主键, 下版本会支持没有主键表的操作.

thanks，（刚才不小心点到close了sorry
