### ISSUE TITLE
error occured in code-server on my rpi

### ISSUE THREAD

**Issue by june4432** [cweijan/vscode-mysql#729]
hi. 
i have a problem using your extension with code-server on raspberrypi4.
i have installed your extension and extension was launched.
then i got a message like this.
![image](https://user-images.githubusercontent.com/39511671/206342158-5894e531-95dd-4646-b035-8344e1139418.png)

when i using vscode desktop, there was no any other problem.

would you check this out?

**Comment by cweijan** [comment]
I built a code-server, but it can work fine. Try to restart the code-server, and check whether the files in the following paths exist.

![image](https://user-images.githubusercontent.com/27798227/206354586-7e25bdab-69e8-4db2-8524-497547a7a1ad.png)

**Comment by 8treenet** [comment]
同样的问题。
