### ISSUE TITLE
云同步具体咋咋用

### ISSUE THREAD

**Issue by Carson-yy** [cweijan/vscode-mysql#733]
作者说下云同步下的Key文件有哪些创建方式，怎么来！

**Comment by cweijan** [comment]
任意一个纯文本文件都可以，我一般是使用ssh-keygen命令生成密钥对，使用其中的私钥

**Comment by yaegar** [comment]
> 

懂了！感谢

**Comment by Carson-yy** [comment]
> 任意一个纯文本文件都可以，我一般是使用ssh-keygen命令生成密钥对，使用其中的私钥 Message ID: ***@***.***>

懂了 感谢
