### ISSUE TITLE
[BUG]NoSQL showing IP instead of the terminal name.

### ISSUE THREAD

**Issue by wilen5** [cweijan/vscode-mysql#735]
- OS: Windows 10
- Database Type: MySql
- Extension Version:6.0.4
![cap1](https://user-images.githubusercontent.com/18680420/208811078-dbd2ad10-6f30-4732-b353-923e5abb2c99.JPG)

Not sure what happen but this keeps returning to IP address instead of the terminal name.

**Comment by cweijan** [comment]
Sorry, this is a bug in the previous version, closing the connection in the previous version will cause the connection name to be cleared. 

You can only restore it through the backup file, or reconfigure the name.

**Comment by wilen5** [comment]
> Sorry, this is a bug in the previous version, closing the connection in the previous version will cause the connection name to be cleared.
> 
> You can only restore it through the backup file, or reconfigure the name.

I reconfigure the name but once i drag and drop to move it in a different order they will return to IP address all of them.

**Comment by wilen5** [comment]
> Sorry, this is a bug in the previous version, closing the connection in the previous version will cause the connection name to be cleared.
> 
> You can only restore it through the backup file, or reconfigure the name.

It seems the update fix it thanks.

**Comment by cweijan** [comment]
Thank you for your feedback.
