### ISSUE TITLE
SSH: All configured authentication methods failed.

### ISSUE THREAD

**Issue by cweijan** [cweijan/vscode-mysql#737]
Update: This issue has been resolved in version 6.6.0, please update the extension.

---
This error may occur when you connect using a key.

openssh no longer supports the ssh-rsa algorithm after openssh version 8.8, and you use the ssh-rsa key, so the server refuses the connection, there are two ways to solve this problem.

- Execute the following commands on the server to support the ssh-rsa algorithm.
`sed  -i '1i PubkeyAcceptedKeyTypes=+ssh-rsa\nPubkeyAcceptedAlgorithms +ssh-rsa' /etc/ssh/sshd_config && service ssh restart`

- Generate ed25519 key pair, and connect using the new key pair.
`ssh-keygen -t ed25519`

**Comment by yxm9264** [comment]
不能在扩展这边解决这个问题嘛，操作服务器是比较麻烦的事情。😭

**Comment by cweijan** [comment]
@yxm9264 使用`ssh-keygen -t ed25519`生成键值对, 然后把公钥授权到服务器就是比较轻量的方式.

**Comment by ghost** [comment]
It doesn't work for me, 
each client works fine, ms, as usual, doesn't work at all

**Comment by cweijan** [comment]
Sorry, but I have no control over it, you can only save a connection using native mode.

**Comment by jstilwell** [comment]
Hello, my private key works fine using the same configuration in Datagrip, so I'm not sure why it wouldn't work within this extension if the problem is OpenSSH.

Edit: Sorry, this was 100% user error. On the SSH connection, I was using the wrong username by mistake. My RSA key works fine with the correct username, for what it's worth. It's possible someone else is making the same mistake.

**Comment by cweijan** [comment]
Hi @jstilwell, Datagrip is implemented in Java, and this extension uses node.js. Their implementation methods are different, and the node runtime provided by VSCode removes some security algorithms, which makes some ssh algorithms unable to work normally.

Sorry I couldn't solve this problem, please consider using password or change your key.

**Comment by cweijan** [comment]
@Shawn-Huang-Tron 可以麻烦你试下旧版本吗, 最近的版本都没涉及到ssh鉴权, 很奇怪

**Comment by Shawn-Huang-Tron** [comment]
vscode插件还可以安装旧版本啊。涨姿势了。。。我去折腾折腾看看

**Comment by Shawn-Huang-Tron** [comment]
@jstilwell 使用ssh私钥登录连接数据库时候，会报：SSH error: Timed out while waiting for handshake。
我多拿了几个版本试了下，6.5.5的版本是OK的，之后的版本就不行了。。。

**Comment by Shawn-Huang-Tron** [comment]
#870

**Comment by cweijan** [comment]
@jstilwell HI, this issue has been resolved in version 6.6.0, and it is now possible to connect without any modifications.
