### ISSUE TITLE
[BUG] Mongodb doesn't filter properly by context menu in ObjectId

### ISSUE THREAD

**Issue by payamomrani** [cweijan/vscode-mysql#738]
- OS: Ubuntu 22
- Database Type: mongodb
- Extension Version:v6.0.7

Right click a cell
select filter by _id = ObjectID('id string')

you should remove single quotation from query

your find query is : {_id:'ObjectID('628e1e8472849146de4bdbd2')'}
but it should like this : {_id:ObjectID('628e1e8472849146de4bdbd2')}

![image](https://user-images.githubusercontent.com/8416066/209482372-7351c180-1118-449d-809c-ee5b90139d0a.png)

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed at version 6.0.9.
