### ISSUE TITLE
[BUG] Change Active Connection

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#741]
- OS: Windows
- Database Type: MySQL
- Extension Version: 6.0.8

After the latest update the above option is gone from the command pallet.  Can you please restore the same

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Thank you for your feedback, I removed the redundant command in the latest version, this command should not be removed, I will restore it in the next version.

**Comment by franklinkf** [comment]
Thank you Sir

**Comment by cweijan** [comment]
Fixed at version 6.0.9.
