### ISSUE TITLE
[BUG] Problems in SSH

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#742]
- OS: Windows
- Database Type: MySQL
- Extension Version: 6.0.8

After the last update, I am facing lot of issues when I try to connect MySQL through SSH.  A message is coming from VS Code that duplicate database client extension exists.  I uninstalled both MySQL and Database client extension and reinstalled only Database client extension.  Still I am getting the message.

Then I uninstalled database client again

![image](https://user-images.githubusercontent.com/8948123/210324082-831f2015-773b-4588-9c1d-c25accf346dc.png)

But the database icon is still present and I am getting options of an older MySQL extensions version in the command pallete

![image](https://user-images.githubusercontent.com/8948123/210324228-395a62c4-96bc-472d-ac99-ad530cad6c4f.png)

I think this old extension might be the reason for this duplication message.

As both the extensions are uninstalled, how I can get ride of the old version of MySQL?

**Comment by cweijan** [comment]
Hi, maybe you have installed other extensions I posted, please check your installed extensions.

**Comment by franklinkf** [comment]
Thank you Sir.  I have earlier installed you extension for MSSQL which caused this issue. I uninstalled the same and the error got rectified
