### ISSUE TITLE
[BUG] When exporting, file path button should read Export not Import.

### ISSUE THREAD

**Issue by Gasman2014** [cweijan/vscode-mysql#743]
- OS:MacOS
- Database Type: MariaDB
- Extension Version: 
- 
When you EXPORT from the extension, the file selector dialogue button is titled  "IMPORT File Path"  but it should read "EXPORT File Path".  Not a major problem but worth correcting.

<img width="484" alt="Screenshot 2023-01-05 at 19 57 22" src="https://user-images.githubusercontent.com/8401593/210869290-fbc1aa46-54e3-4ad7-99c2-6c0b06494272.png">

**Comment by cweijan** [comment]
Thanks feedback! I will fix it in next version.

**Comment by cweijan** [comment]
Fix at version 6.1.1.
