### ISSUE TITLE
[BUG] Can't create account, no email with verification code

### ISSUE THREAD

**Issue by karolzlot** [cweijan/vscode-mysql#744]
- OS: Win10, Chrome
- Database Type: ----
- Extension Version: ----

I would like to create account. 
I prefer to have account with password instead of GitHub login.

When I click "Send Verify Code", I get information that it was sent, but so far I didn't receive any email.

![chrome_NtSyybeaCU](https://user-images.githubusercontent.com/11590960/211234589-95cc2897-2f2c-49af-9b11-4d65fdeb1048.png)

**Comment by cweijan** [comment]
I checked the mail sending service, it is normal, what is your mail service provider? Maybe it rejected the mail.

**Comment by karolzlot** [comment]
Fastmail

**Comment by karolzlot** [comment]
I tried multiple times, still doesn't work.

**Comment by cweijan** [comment]
Unfortunately, I checked the service provider's log, because fastmail rejected the mail service provider I used(Tencent Cloud), please consider using another mail.

**Comment by karolzlot** [comment]
I notified Fastmail about this problem and it is already working ok, I registered successfully.

**Comment by cweijan** [comment]
Thanks!
