### ISSUE TITLE
[BUG] Redis can't list keys

### ISSUE THREAD

**Issue by zengLH1981** [cweijan/vscode-mysql#745]
- OS: Windows 10
- Database Type: redis
- Extension Version:  v6.1.0

can't list key in the tree
![image](https://user-images.githubusercontent.com/16136238/211237009-5f08f63b-1b2d-4ad6-9dd3-622cc6e935eb.png)

use console list keys is ok

![image](https://user-images.githubusercontent.com/16136238/211237092-a37296e8-3981-46d2-81c4-a0b0034baff9.png)

**Comment by cweijan** [comment]
Thank you for your feedback, can you open the developer tools and let me see the error log?
![image](https://user-images.githubusercontent.com/27798227/211237421-848a5408-3f3b-4924-a6f4-524b796683b7.png)

**Comment by cweijan** [comment]
I think I have found the reason, please try the latest 6.1.1 version.

**Comment by zengLH1981** [comment]
It's fixed so quickly. 
👍👍👍
