### ISSUE TITLE
[BUG] No english translation

### ISSUE THREAD

**Issue by n-r-w** [cweijan/vscode-mysql#749]
- Operating system: Manjaro KDE
- Database type and version: postgresql 14.5

![image](https://user-images.githubusercontent.com/38435980/212421286-0a5cced4-824e-4473-9fe6-6b780974716c.png)

**Comment by cweijan** [comment]
Thanks, I will fix it in the next version.

**Comment by cweijan** [comment]
This problem has been fixed.
