### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:3306

### ISSUE THREAD

**Issue by frizzo01Project** [cweijan/vscode-mysql#750]
Hello, I am unable to connect the database in vscode.
I have check all the firewall and proxies there is not problem but unfortunately I cannot connect this connect server application either online or inside vs code.
could I have any advise to fix this matter?
<img width="664" alt="Screenshot 2023-01-13 at 22 16 11" src="https://user-images.githubusercontent.com/93917746/212433469-881e9557-c428-4638-a418-107426fc7a4f.png">

**Comment by cweijan** [comment]
The error indicates that the MySQL port of 127.0.0.1 is not open, there are two possibilities:
1. You want to connect to the remote MySQL, not the local 127.0.0.1
2. Your MySQL is not bound to port 3306.

If your machine is Linux, try to click to connect using Socket.

![image](https://user-images.githubusercontent.com/27798227/212433962-16e80641-360a-43e4-985e-38577288efbb.png)

**Comment by frizzo01Project** [comment]
> The error indicates that the MySQL port of 127.0.0.1 is not open, there are two possibilities:
> 
> 1. You want to connect to the remote MySQL, not the local 127.0.0.1
> 2. Your MySQL is not bound to port 3306.
> 
> If your machine is Linux, try to click to connect using Socket.
> 
> ![image](https://user-images.githubusercontent.com/27798227/212433962-16e80641-360a-43e4-985e-38577288efbb.png)

thank you for replying I am using MacBook
