### ISSUE TITLE
Why can't I change the foreign_keys setting with PRAGMA?

### ISSUE THREAD

**Issue by yuzokamoto** [cweijan/vscode-mysql#752]
### The query `PRAGMA foreign_keys = ON;` is executed successfully:
![image](https://user-images.githubusercontent.com/29845719/213245415-0ceb50e7-31a3-43d4-b8bc-a01eccefef92.png)

<hr />

### But it stays off:
![image](https://user-images.githubusercontent.com/29845719/213245217-fd9c323e-7e76-4a20-9f07-2081aded8c93.png)

**Comment by cweijan** [comment]
Now every time SQLite is executed, a new process will be created, so the PRAGMA statement is not working. I'll try to support persistent sessions in future versions.

If you want to support PRAGMA, you need to create ~/.sqliterc, and write the PRAGMA statement in it.

**Comment by yuzokamoto** [comment]
To those that have the same problem, just run the following command on the bash terminal:
`echo "PRAGMA foreign_keys = ON;" >> ~/.sqliterc`

That will create a .sqliterc file with the PRAGMA configuration on the suggested folder. Works like a charm!
