### ISSUE TITLE
[BUG] Screen hangs

### ISSUE THREAD

**Issue by SouL-H** [cweijan/vscode-mysql#753]
Hi, the screen hangs when manually adding data in the sql table.

![screen_1](https://user-images.githubusercontent.com/26456702/214498260-cbf0f83e-4f3c-4b30-83b8-1a4837e40855.png)

![screen_2](https://user-images.githubusercontent.com/26456702/214498333-5601dd3f-d5e5-4b17-b1ab-31f81811b734.png)

- Operating system: Apple M1 
- Database type and version: Sqlite - v6.1.3

**Comment by cweijan** [comment]
Thanks for the feedback, this looks like a SQLite version compatibility issue, I'll try to fix it.
