### ISSUE TITLE
Connection error! All configured authentication methods failed

### ISSUE THREAD

**Issue by vldanch** [cweijan/vscode-mysql#754]
Here's the [problem](https://ibb.co/DKqCRPb).
When adding a virtual machine with this plugin does not pass authorization by private key, what to do?
Previously installed on the machine sshd daemon setting only authorization by key, without password.

**Comment by cweijan** [comment]
The server rejected your key format, the extension cannot handle this case, please refer to [this issue](https://github.com/cweijan/vscode-database-client/issues/737).

**Comment by vldanch** [comment]
@cweijan You won't believe it, but setting up on the ubuntu 22.04.1 LTS `PubkeyAcceptedKeyTypes=+ssh-rsa` in file `/etc/ssh/sshd_config`, and after that the connection was made by the key.
