### ISSUE TITLE
[BUG] MongoDB 资料内容无法正常显示

### ISSUE THREAD

**Issue by papple23g** [cweijan/vscode-mysql#756]
- Operating system: Windows 10
- Database type and version: MongoDB 5.0.6
- Extension Version: v6.0.8 (以上)

MongoDB 里的 Arrays 栏位內容原本可以正常显示(图一)，更新至版本 6.0.8 以后就无法正常显示了(图二)
![230201_091724](https://user-images.githubusercontent.com/28220061/215922336-ff272e1f-c222-46c1-843a-f45422909e81.png) 
![230201_091618](https://user-images.githubusercontent.com/28220061/215922341-df1f369c-27ab-4942-aef3-71c80c2fff22.png)

**Comment by cweijan** [comment]
谢谢反馈, 我会在下版本修复.

**Comment by cweijan** [comment]
已发布6.1.6版本修复.
