### ISSUE TITLE
[BUG] webview is missing index.html

### ISSUE THREAD

**Issue by code-n-go** [cweijan/vscode-mysql#758]
Error: ENOENT: no such file or directory, stat '/home/vscode/.vscode-server/extensions/cweijan.vscode-database-client2-6.1.7/out/webview/index.html'

That's when visiting http://localhost:8828/.

If you go to the directory, you can see the assets... and the only two html files are the app.html and result.html.

- Operating system: Linux
- Database type and version: N/A (irrelevant)

**Comment by cweijan** [comment]
Hi, this is an HTTP server created to speed up the loading of extensions, it is only used internally.

**Comment by sunhs** [comment]
您好，请问是否能配置关闭这个 HTTP server？我是远程到开发服务器上用的，公司的安全组扫描到服务器上对外监听这个端口，暂时不让用这插件
