### ISSUE TITLE
Can you add the possibility to run ssh with arguments?

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#759]
Hi.
Can you add the possibility to run ssh with arguments?

like this:
```bash
ssh - R 1234:localhost:1234 root@sys1
or
ssh -L 1234:localhost:1234 root@sys1

```

**Comment by cweijan** [comment]
When did this happen?

**Comment by mbtolou** [comment]
for local or remote port forwarding or other options like gateway , keepalive interval , ....

**Comment by cweijan** [comment]
The port forwarding provided by the extension is implemented by nodejs, not the ssh command, there is no such option.
