### ISSUE TITLE
希望支持hive

### ISSUE THREAD

**Issue by tensor-tech** [cweijan/vscode-mysql#762]
如题

**Comment by cweijan** [comment]
会尝试在以后的版本支持.

**Comment by cweijan** [comment]
Hive连接库太笨重了, 不适合在本扩展支持.

**Comment by wonb168** [comment]
hive有1个很小的jar包啊，18m，dbeaver都用这个连的

**Comment by cweijan** [comment]
Hi, 在最新版本6.9.0支持连接Hive了
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/92bdc787-0775-4781-8b27-c2d41c109dd9)
