### ISSUE TITLE
case when then 这种流程没提示吗，when，then也没有提示

### ISSUE THREAD

**Issue by izilongwan** [cweijan/vscode-mysql#766]

**Comment by cweijan** [comment]
你是指相关的关键字补全吗

**Comment by izilongwan** [comment]
> 你是指相关的关键字补全吗

如果可以的话直接补全流程函数，最少关键字要有吧

**Comment by cweijan** [comment]
函数现在有补全的

**Comment by izilongwan** [comment]
> 函数现在有补全的

<img width="616" alt="image" src="https://user-images.githubusercontent.com/48234072/217838377-f9a88cdc-7b5d-4ec8-be52-d8b7ff8149b8.png">
没看到啊

**Comment by cweijan** [comment]
你用case是想补全什么函数呢? 函数列表按空格后就有补全.
![image](https://user-images.githubusercontent.com/27798227/217839280-f5c99124-90f5-42de-9f83-891f6e031df3.png)

**Comment by izilongwan** [comment]
<img width="526" alt="image" src="https://user-images.githubusercontent.com/48234072/217840124-6c6bb17f-bf14-40f4-80ab-df5d82b4d9bf.png">

我的意思是补全流程关键字

**Comment by cweijan** [comment]
那就是指的关键字, 不是函数, 这几个关键字目前限制在了存储过程, 等我下版本优化.

**Comment by izilongwan** [comment]
<img width="399" alt="image" src="https://user-images.githubusercontent.com/48234072/217842143-bfa4b00b-179a-4ca6-984e-dd3eec83eb61.png">
<img width="507" alt="image" src="https://user-images.githubusercontent.com/48234072/217842451-941c8c0d-45f7-48ad-835f-308b5aca9041.png">


最好打case 可以选到这个补全，另外几个关键字也要有提示可以大写when then end

**Comment by cweijan** [comment]
嗯嗯,  明白你的意思.

**Comment by cweijan** [comment]
已发布6.2.0版本支持.
