### ISSUE TITLE
How to display multiple databases under a connection

### ISSUE THREAD

**Issue by zahraaalizadeh** [cweijan/vscode-mysql#767]
Hi!

I work with multiple postgres dbs on the same server at the same time. How can I display all of those databases on the same connection? 

I tried Advanced Option >> showed databases, and provided list of databases' names separated by comma (e.g. `foo, bar`) but it didn't work.

**Comment by cweijan** [comment]
Click this button, it will list all databases, then you can check the databases you want to display.

![image](https://user-images.githubusercontent.com/27798227/217979176-a6af373d-84e0-4941-bc2c-681dd4709cfb.png)

**Comment by zahraaalizadeh** [comment]
Cool! thank you for the quick response!
