### ISSUE TITLE
Export to markdown table

### ISSUE THREAD

**Issue by elgs** [cweijan/vscode-mysql#768]
As of now v6.1.9, the export supports xlsx, csv, json and sql. Would be great if markdown table could be added to the list. Thanks.

**Comment by cweijan** [comment]
Cool idea! I'll try to implement it in a future release.

**Comment by cweijan** [comment]
Supported in version 6.2.1.

![image](https://user-images.githubusercontent.com/27798227/219292323-c7c4146e-7e59-40f6-8203-cdac9dd9ad8f.png)
