### ISSUE TITLE
[BUG] oracle 表字段类型的精度丢失

### ISSUE THREAD

**Issue by Pumaly** [cweijan/vscode-mysql#769]
oracle表的number字段，不管精度是什么都直接显示number，比如number(1)显示的是number(22)
- Operating system:
- Database type and version:

**Comment by cweijan** [comment]
谢谢反馈, 已在6.2.3版本修复.

**Comment by Pumaly** [comment]
辛苦了，但是今天又发现一个与精度相关的，现在19位的Id查询出来后两位为0，需要像plsql一样对Number型做to_char处理

**Comment by cweijan** [comment]
后两位为0什么意思呢? 自动填充0吗

**Comment by Pumaly** [comment]
1065545810435002370变成了1065545810435002400

**Comment by Pumaly** [comment]
在plsql中也会有同样的问题，不过在plsql中可以通过勾选to_char解决

**Comment by cweijan** [comment]
将dbclient-jdbc升级到1.2.3版本后可解决大数字精度问题.
