### ISSUE TITLE
Add ways to check and manage Could Sync contents

### ISSUE THREAD

**Issue by qazwsxedckll** [cweijan/vscode-mysql#770]
Most importantly, I want to delete what I have uploaded.

**Comment by cweijan** [comment]
Thanks for the feedback, I have no plan on providing management cloud sync content. But delete should be provided, I will support delete cloud sync content in future versions.

**Comment by cweijan** [comment]
Hi, I released version 6.2.2, now you can click remove button in the console to delete cloud data.

![image](https://user-images.githubusercontent.com/27798227/220812840-f2356563-4b99-45a5-8168-034afea5225a.png)
