### ISSUE TITLE
Add option to hide "Execute"

### ISSUE THREAD

**Issue by karolzlot** [cweijan/vscode-mysql#771]
I would like to be able to hide "Execute" lines:

![image](https://user-images.githubusercontent.com/11590960/220025974-e11691d4-bca7-4208-8480-44aa9975eab5.png)

**Comment by cweijan** [comment]
Hi, the options below can be disabled, but currently only available for premium accounts.

![image](https://user-images.githubusercontent.com/27798227/220812970-5d0b7ecf-8d5a-40bb-85b7-618a060149c4.png)

**Comment by cweijan** [comment]
Hi, I released version 6.2.5, now the configurations will no longer have premium restrictions, you can disable the code len by checking below option.
![image](https://user-images.githubusercontent.com/27798227/224908788-40025b39-f51b-482f-a7ea-b0a6de297be5.png)
