### ISSUE TITLE
[BUG]Error when connecting to SQLite.

### ISSUE THREAD

**Issue by sinh927** [cweijan/vscode-mysql#772]
When connecting to SQLite, the following error occurs
```
2023-02-23 10:25:47 Execute sql fail : SELECT name, type FROM sqlite_master WHERE type="table" ORDER BY type ASC, name ASC;
2023-02-23 10:25:47 Parse error near line 3: no such column: table
  SELECT name, type FROM sqlite_master WHERE type="table" ORDER BY type ASC, nam
                                    error here ---^
```

- Operating system:
  - OS : Windows 11 Home 22H2
   - VSCode : 1.75.1

- Database type and version:
  - sqlite-dll-win64-x64-3410000

**Comment by cweijan** [comment]
Thanks for the feedback, try the latest version 6.2.2, I think this problem has been solved.
