### ISSUE TITLE
建议增加根据分组名和连接名排序，连接多了很混乱

### ISSUE THREAD

**Issue by DittCy** [cweijan/vscode-mysql#774]
增加根据分组名和连接名排序，连接多了很混乱

**Comment by cweijan** [comment]
默认是最后添加的在最下面, 可以通过长按拖动的方式修改排序.

**Comment by DittCy** [comment]
“默认是最后添加的在最下面”这个可能是有bug，我添加的都是乱的，有时候会跑到最上面
长按拖动排序确实可以，多谢
