### ISSUE TITLE
SSH Client插件和这个插件不能共存，那么SSH甚至是每一种数据库，是否可以增加是否独立显示侧边栏图标

### ISSUE THREAD

**Issue by DittCy** [cweijan/vscode-mysql#775]
SSH甚至是每一种数据库，可以增加是否独立显示侧边栏图标，就像Database和NoSQL分开俩个侧边栏图标一样

**Comment by cweijan** [comment]
肯定不会这样子设计, 配置分组就好了.. 
![image](https://user-images.githubusercontent.com/27798227/221733585-dbbea56c-3d42-45b6-99e7-886ddc2f1393.png)

**Comment by DittCy** [comment]
ssh ftp 和数据库放在一起实在是不优雅

**Comment by cweijan** [comment]
设计成两个容器主要是为了区分数据库和非数据库, 便于操作数据库时还能做其他操作, 不是单纯为连接类型分类.
