### ISSUE TITLE
[BUG]如图，鼠标滑过功能图标时的提示文案，遮挡且看不清

### ISSUE THREAD

**Issue by DittCy** [cweijan/vscode-mysql#777]
- Operating system:
- Database type and version:
![image](https://user-images.githubusercontent.com/8243961/221733258-3221db5f-e68b-4820-897d-3cc5d44336ab.png)

**Comment by cweijan** [comment]
看看新版本6.2.3正常吗.

**Comment by DittCy** [comment]
![image](https://user-images.githubusercontent.com/8243961/221811774-0ab18892-8356-4ee9-ae32-530581442b81.png)
实际上 效果不太好…

**Comment by cweijan** [comment]
看起来是背景色的问题, 背景色在你这个主题是半透明的

**Comment by DittCy** [comment]
其实可以让气泡完全不透明，覆盖下面的文字就可以，毕竟鼠标会滑走

**Comment by cweijan** [comment]
这个和主题色有关, 不是我弄透明的.

**Comment by cweijan** [comment]
你看下最新版还正常不, 还有移除就把主题名发一下.

**Comment by DittCy** [comment]
没问题了👍
