### ISSUE TITLE
Database Client does not allow connection to MariaDB Server 10.6.11-MariaDB

### ISSUE THREAD

**Issue by ghost** [cweijan/vscode-mysql#778]
When connecting to a server running MariaDB Server 10.6.11-MariaDB , the follow error is generated:

"Server requests authentication using unknown plugin dialog. See TODO: add plugins doco here on how to configure or author authentication plugins."

Note that there are no issues when connecting to this server using DBeaver Community Edition 22.3.5

- Windows 10 Pro 19045.2486
- Visual Studio Code 
Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
- Database Client
v6.2.3
Last updated 3/1/2023, 17:39:20

**Comment by cweijan** [comment]
Thanks for the feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Try version 6.2.4.

**Comment by ghost** [comment]
Apologies for the delay. I have tried again using Database Client v6.2.4, and the same error occurs. Please note that a server running 10.3.17-MariaDB connects perfectly:

![image](https://user-images.githubusercontent.com/126643751/223579830-e0becfa7-010e-4577-ad73-538589cfdd19.png)

**Comment by cweijan** [comment]
Thanks feedback, it seems to be related to your mariadb configuration, I created MariaDB Server 10.6.11, but he can connect normally, I will keep looking for a solution.

**Comment by cweijan** [comment]
The mariadb you are connected to uses an authentication plugin that the client cannot support, please execute `SELECT User,plugin FROM mysql.user  WHERE User='<userName>'` to let me know what the plugin is, or you modify the authentication plugin to "caching_sha2_password"

**Comment by ghost** [comment]
I am unable to modify the authentication plugin that we use. The plugin is:
mysql_native_password

**Comment by cweijan** [comment]
Hi, try the latest version 6.2.6.

![image](https://user-images.githubusercontent.com/27798227/225800335-2e3bfaca-0ea3-46ae-bacb-05dc61ec7f7d.png)

**Comment by ghost** [comment]
Everything is working perfectly now. Thank you for sorting this out!
