### ISSUE TITLE
[BUG] Failed to parse [geo_point] Elastic

### ISSUE THREAD

**Issue by NCG-Christof** [cweijan/vscode-mysql#779]
macOS Ventura 13.2.1
Code v1.75.1
ElasticSearch 8.6.0

When attempting to update or create a document into an index which contains a field type geo_point the POST fails.

Error message

SQL:  POST /metadata/_doc/rhasnYYBrlbqiSGbrKQR {"device.deployed":"2023-03-01T14:46:29.027Z","device.platform":"XXXXXXXX","device.status":false,"meta.coordinates":"[-115.81035458335873,37.24515957709032]","meta.lat":37.24515957709032,"device.type":"COUNTING","meta.customer":"XXXXXXX","meta.building":"XXXXXXXXX","reset.send":false,"meta.long":-115.81035458335873,"meta.identity":"XXXXX","meta.location":"Unknown","device.guid":"S7Ah-w8kQrShLLAUpvWBFA","device.model":"Unknown","meta.department":"Unknown","meta.name":"Area21","meta.floor":"Basement","device.removed":"1971-01-01T00:00:00.000Z"}

failed to parse field [meta.coordinates] of type [geo_point]

**Comment by cweijan** [comment]
Thank you for feedback, I will support Geo_point type in the next version.

**Comment by cweijan** [comment]
Fixed in version 6.2.4.
