### ISSUE TITLE
[feature-request]: plugin for intellij

### ISSUE THREAD

**Issue by FaiyazMujawar** [cweijan/vscode-mysql#780]
Hi there,

I've been using vscode for a long time and really loved your extension for backend development.

However, I had to recently shift to Intellij Idea for Java and require an extension for database navigation. As far as I've hunted, no extension in Intellij marketplace can come even close to this masterpiece. Can we have a similar extension for Intellij as well?

Would be of great help to many Java devs like me! 😉

**Comment by cweijan** [comment]
The Intellij plugin is not compatible with this vscode extension, Intellij ultimate has an official database connection plugin.
