### ISSUE TITLE
Make it compatible with "PostgreSQL Language Server" extension

### ISSUE THREAD

**Issue by karolzlot** [cweijan/vscode-mysql#783]
I use "vscode-database-client" extension.
I would like to use also this extension:

https://marketplace.visualstudio.com/items?itemName=uniquevision.vscode-plpgsql-lsp

More precisely I would like to use Postgres highlighting which is provided by this extension (it is better because it is Postgres-specific, contrary to default highlighting).
However when I switch syntax highlighting to Postgres, I can't use "vscode-database-client" feautures.

How can I use both at the same time? If it is a bug, please fix it :)

**Comment by cweijan** [comment]
This extension has registered a new language, and it takes over the language function. I cannot compat with it. You can try to configure the shortcut key binding.
```json
{
        "command": "mysql.runSQL",
        "key": "ctrl+enter",
        "mac": "cmd+enter",
        "when": "editorLangId == postgres"
}
```
