### ISSUE TITLE
建议增加字段的创建的ALTER语句生成

### ISSUE THREAD

**Issue by miaokela** [cweijan/vscode-mysql#784]

**Comment by cweijan** [comment]
什么意思.

**Comment by miaokela** [comment]
单个字段的SQL Generator
<img width="473" alt="image" src="https://user-images.githubusercontent.com/30903265/222949302-8aff7ace-8d21-45ae-9c03-5a34d8e8eee6.png">

**Comment by cweijan** [comment]
你可通过设计表功能, 或者在列分组点击加号.
![image](https://user-images.githubusercontent.com/27798227/222951735-0eb59ca2-4bb2-49b4-8798-546659d22195.png)
![image](https://user-images.githubusercontent.com/27798227/222951740-d374ae96-1a4b-4b9e-a842-f3a846bf5374.png)
