### ISSUE TITLE
How to disable foreign key checks 

### ISSUE THREAD

**Issue by Niko7133** [cweijan/vscode-mysql#785]
Good morning, I am using this extension for school use and I should find a way to disable foreign key checking when uploading a sql code, how can I do it?

**Comment by cweijan** [comment]
Foreign key check is provided by the database server, the extension is only responsible for the execution of SQL.

https://stackoverflow.com/questions/15501673/how-can-i-temporarily-disable-a-foreign-key-constraint-in-mysql
