### ISSUE TITLE
Use custom name in tab

### ISSUE THREAD

**Issue by mirkadev** [cweijan/vscode-mysql#786]
Hey!

Currently, I see the same names in tabs if I have 3 connections (local, dev, and staging). It's very confusing:

<img width="139" alt="image" src="https://user-images.githubusercontent.com/45996373/223179515-c7c42f40-42c4-4204-a6fe-b3a3380319cf.png">
<img width="236" alt="image" src="https://user-images.githubusercontent.com/45996373/223180255-8c47e0b3-59ae-4a90-8fd8-a627dc666059.png">

It would be much better if it had custom name from the connection settings page:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/45996373/223180040-0d7ce48c-ec33-4b18-bd1a-7ed98e7735a3.png">

**Comment by cweijan** [comment]
Hi, you can create a SQL file with any name and click "Active connection" to bind the connection to the SQL file.

![image](https://user-images.githubusercontent.com/27798227/223293840-1e500076-7bf7-4255-a32e-9e9de0e5ce34.png)

**Comment by mirkadev** [comment]
I've tried it, but I don't have tips anymore.

<img width="448" alt="image" src="https://user-images.githubusercontent.com/45996373/223404010-3290a76a-b13a-4c34-b031-ca13bf2bca67.png">

now I need to write database name, then schema name and then table name to get tips :(

<img width="760" alt="image" src="https://user-images.githubusercontent.com/45996373/223404142-c44630dd-e230-47e2-ac9e-8e94fcdde221.png">

**Comment by cweijan** [comment]
The extension does not support completion through the database, you need to bind the database for the SQL file.

**Comment by mirkadev** [comment]
I did it. Actually, it works ok (queries execute), but I just don't see tips. My steps:

1. Create a new sql file

2. Tap `active connection` and select needed db

3. Now queries work, but tips don't - only on the way I show above

**Comment by cweijan** [comment]
Thanks for the feedback, there is a bug, currently it needs to be bind to the schema, I will fix it in the next version.

**Comment by mirkadev** [comment]
Thank you!
