### ISSUE TITLE
Usage of extension in devcontainer

### ISSUE THREAD

**Issue by ItsReddi** [cweijan/vscode-mysql#787]
Is it possible to configure database parameters via devcontainer customizations?

**Comment by cweijan** [comment]
What do you mean by "database parameters"?

**Comment by ItsReddi** [comment]
I mean any setting that we could set via interface for a corresponding connection.
![grafik](https://user-images.githubusercontent.com/3147888/223625856-433a0546-794a-4d20-a1f5-b462069413ed.png)

Goal: 
No one that is using the dev container needs to setup the connections manually.
Since we are able to set connections via `devcontainer.json` => `customizations`

**Comment by cweijan** [comment]
The extension can save the connection to the current folder, this feature is only available for premium.
![image](https://user-images.githubusercontent.com/27798227/223629637-9ad9f33a-6acb-4e9c-8364-6ac2ad238de7.png)

**Comment by Eboubaker** [comment]
Fine I will look for another extension
