### ISSUE TITLE
[BUG] Oracle 分页问题

### ISSUE THREAD

**Issue by joyous-coder** [cweijan/vscode-mysql#788]
- Operating system: windows
- Database type and version: 6.2.4
![image](https://user-images.githubusercontent.com/42910684/223437091-c6d6dd3b-e1a6-49ae-bdc5-8723b408d7ee.png)
数万的数据分页total显示只有1页，共100条。   不能向后点击

**Comment by joyous-coder** [comment]
还有oracle数据库的查询速度好慢

**Comment by cweijan** [comment]
谢谢反馈, 我会在下版本修复, 查询慢是因为第一次查询表时会去加载列, 加载后会缓存就快了.

**Comment by joyous-coder** [comment]
已购买会员支持，希望扩展越做越好

**Comment by cweijan** [comment]
已在版本6.2.6修复.
