### ISSUE TITLE
优化SQL格式化效果

### ISSUE THREAD

**Issue by izilongwan** [cweijan/vscode-mysql#790]
现在：
![image](https://user-images.githubusercontent.com/48234072/224476360-d8102de6-f9f5-4793-9f8d-63c826536dd4.png)

想要：
![image](https://user-images.githubusercontent.com/48234072/224476405-a231de4f-a1ef-44ac-9b84-b450e1da5456.png)

**Comment by cweijan** [comment]
格式化程序都不会把逗号放在下一行的开始的, 建议手动调整.
