### ISSUE TITLE
[BUG] Plugin crashes VSC after executing query.

### ISSUE THREAD

**Issue by Brandon-Gottshall** [cweijan/vscode-mysql#791]
- Operating system: Mac OS Ventura 13.2.1 - Intel-based
- Database type and version: Postgres@14

VSCode crashes when executing queries inline.

**Comment by cweijan** [comment]
May I ask what happened to the crash?

**Comment by Brandon-Gottshall** [comment]
It hangs indefinitely with a pinwheel blocking any further interaction with VSC. It shows the successful query results though. Just left having to restart VSC to continue using it.

**Comment by cweijan** [comment]
Does this problem occur every time you execute a query? If so, please let me look at your SQL.

If it happens by accident, it may be a bug of VS Code.

**Comment by Brandon-Gottshall** [comment]
It happens regardless of my query.

Two queries it's happened on thus far:

SELECT * FROM plane;

SELECT name, city FROM airport WHERE country = 'Portugal';

**Comment by cweijan** [comment]
Thanks for the feedback, your SQL doesn't look special, I will check if there is an infinite loop in the extension.

**Comment by cweijan** [comment]
Please try the latest version 6.2.6, and update VSCode to the latest version.

**Comment by Brandon-Gottshall** [comment]
Works 👍
