### ISSUE TITLE
sub-item for partitions

### ISSUE THREAD

**Issue by gunreio** [cweijan/vscode-mysql#792]
Hello Weijan Chen,

a suggestion from my side. I think it would be very nice and would help for the sake of clarity if there would be a sub-item for partitions in addition to the sub-categories (columns, index, triggers).

<img width="233" alt="Screenshot 2023-03-13 124658" src="https://user-images.githubusercontent.com/76681985/224694574-ddeb5d45-7b32-432d-af9c-7df2a24f4d70.png">

Thanks a lot, good job

**Comment by cweijan** [comment]
Do you mean table partition?

**Comment by gunreio** [comment]
Of course, yes. Sorry

**Comment by cweijan** [comment]
Thanks for the feedback, there is no table partition now because I think this feature is not used frequently, I will support it in the future.

**Comment by gunreio** [comment]
That is nice to here! Go ahead with your good job.

**Comment by cweijan** [comment]
Table partitioning has been shown in version 6.2.6.

![image](https://user-images.githubusercontent.com/27798227/225800891-82227aff-1c85-4619-a85d-c64ec53871e8.png)
