### ISSUE TITLE
[BUG] Premium plan not carried to my vsCode

### ISSUE THREAD

**Issue by rafaelzochling** [cweijan/vscode-mysql#793]
Hello team, I found your project very good and bought a premium subscription, however, when I went to download my cloud sync. I have 2 computers that I want to sync and I just bought my subscription. In the extension page I even see it as `unlocked`, however, when I click in `download` I get prompted to the webpage to buy the premium plan again. 
I created my account via github with `rafaelzochling@gmail.com` email.

Thanks in advance

- Operating system: MacOs
- Database type and version: N/A

**Comment by cweijan** [comment]
You need to log in again on the new computer, please check your email, there is an email on how to activate premium.
