### ISSUE TITLE
Add support for Redis Time Series (TSDB-TYPE)

### ISSUE THREAD

**Issue by dave-knight** [cweijan/vscode-mysql#794]
When attempting to view a Redis Time Series, an error is displayed stating "Unsupport type TSDB-TYPE!":
<img width="345" alt="image" src="https://user-images.githubusercontent.com/11647007/225862084-c1f646e1-190a-4c7b-b9bf-9e1e49b92062.png">
More information about Redis Time Series can be found on the Redis website:
https://redis.io/docs/stack/timeseries

**Comment by cweijan** [comment]
Thanks for the feedback, I will support it in future versions.

**Comment by cweijan** [comment]
Sorry sir, after my research, RedisTimeSeries is used for OLAP, it has to do calculation and filtering, can't query directly, I can't support it.
