### ISSUE TITLE
Oracle 数据库分页优化

### ISSUE THREAD

**Issue by joyous-coder** [cweijan/vscode-mysql#796]
![Snipaste_2023-03-18_16-37-37](https://user-images.githubusercontent.com/42910684/226095106-ae92702c-cf5c-4d65-ac46-e15e49a90579.png)
看了一下现在的分页，只给了小于一个索引号。这种情况下会出现越是查询靠后的分页速度越慢。18000左右的数据，最后一页不到100条数据加载时间长达1分4秒
建议替换为下图的分页方法。查询时间可以缩短到不到一秒
![image](https://user-images.githubusercontent.com/42910684/226095330-576c11ce-8891-4cb1-8b59-f771303e7ef3.png)

**Comment by cweijan** [comment]
Oracle分页太麻烦了, 用这种方式SQL检测会出现问题, 没办法.

**Comment by joyous-coder** [comment]
这个也是标准的sql啊，为什么会检测出问题呢？？

**Comment by cweijan** [comment]
现在的分页是对SQL进行处理替换页码的, 所以不能使用复杂的分页SQL. 我现在已经有思路优化分页性能了, 等以后更新.

**Comment by joyous-coder** [comment]
好的

**Comment by cweijan** [comment]
已经在版本6.3.1优化分页性能, 需要同时更新dbclient-jdbc到1.2.6版本, 更新后需要杀死dbclient-jdbc的Java进程(如果不知道怎么关闭则重启计算机).

**Comment by joyous-coder** [comment]
辛苦
