### ISSUE TITLE
[BUG] 分页切换时会出现空白

### ISSUE THREAD

**Issue by joyous-coder** [cweijan/vscode-mysql#797]
- Operating system:
- Database type and version:
![image](https://user-images.githubusercontent.com/42910684/226095486-4cdf944b-23f4-47c2-af97-1d8c73cac67b.png)

**Comment by joyous-coder** [comment]
Oracle 数据库，扩展版本6.2.8，Vscode版本1.76.2

**Comment by cweijan** [comment]
这个没法处理, 为了性能这里的表格渲染用了虚拟滚动,  不然渲染所有数据页面会卡死.
