### ISSUE TITLE
Font Size Adjustment

### ISSUE THREAD

**Issue by stymsaw** [cweijan/vscode-mysql#799]
there should be separate size adjustment for the console / display.
other than vscode default ctrl + '+' / '-' size controller.

**Comment by cweijan** [comment]
Thanks for feedback, where would you like to adjust the font?

**Comment by stymsaw** [comment]
![Screenshot (15)](https://user-images.githubusercontent.com/85004499/226533569-0df12199-810f-4249-86f9-f29cac750f3a.png)
![Screenshot (14)](https://user-images.githubusercontent.com/85004499/226533582-687113fa-515b-409e-82d8-828d022c7429.png)

look at those two pics.
result tab covers almost all the space.
instead, what i wish is if this all can fit in a small window

<img width="771" alt="ss" src="https://user-images.githubusercontent.com/85004499/226534247-6f71d6c9-0f5a-48c4-a8db-df1cd351cb0d.png">

something like this.

**Comment by cweijan** [comment]
It looks like you mean line height? This has nothing to do with the font size, but the spacing.

![image](https://user-images.githubusercontent.com/27798227/226536501-f6a1be6f-dff6-430d-9cbb-cdaffc7c6ed5.png)

**Comment by stymsaw** [comment]
Yes, can you please fix this.
Those who have single screen,
are facing inconvenience in using your extension.

Thank you ❤️

**Comment by cweijan** [comment]
I will add options to modify it in future versions.

**Comment by cweijan** [comment]
The latest version 6.3.0 already supports adjusting row height.

![image](https://user-images.githubusercontent.com/27798227/227701364-a4bdd36d-5287-450c-ae7e-fe8f395e7fe8.png)

**Comment by stymsaw** [comment]
Thank You

**Comment by vavrecan** [comment]
This should be re-opened. The style is wrong and overrides default vscode font size and family. It should be using 
    font-family: var(--vscode-font-family);
    font-weight: var(--vscode-font-weight);
    font-size: var(--vscode-font-size);
    ....
