### ISSUE TITLE
I have a problem with postgres connection

### ISSUE THREAD

**Issue by nschuz** [cweijan/vscode-mysql#800]
I am triying to connect with my remote databases but i had this error:
Connection error!no pg_hba.conf entry for host "IP", user "username", database "DB", no encryption

**Comment by cweijan** [comment]
This error is a problem with your postgres configuration, the client cannot handle it.
https://stackoverflow.com/questions/1406025/no-pg-hba-conf-entry-for-host

You could also try connecting through an ssh tunnel, maybe it saves you from having to configure postgres.
![image](https://user-images.githubusercontent.com/27798227/226688898-0e746125-314d-4698-bc3e-731a4576dfc9.png)

**Comment by xerohome-dipen** [comment]
Turn On `SSH Tunnel` toggle to connect with my remote databases

**Comment by dipenparmar12** [comment]
Turn On `SSH Tunnel` toggle to connect remote databases
