### ISSUE TITLE
[BUG] Duplicate paste in command input when keyboard is on Hebrew

### ISSUE THREAD

**Issue by johny1122** [cweijan/vscode-mysql#801]
- Operating system: Ubuntu 20.04.6 LTS
- Database type and version: PostrgeSQL 15.1

When I paste text from clipboard into the command input while the keyboard is on Hebrew, it will paste the text twice (doest matter if the text is in Hebrew or English). When keyboard is on English the paste is working fine.
Added a screenrecord showing the bug. I used ctrl+v to paste in both cases

https://user-images.githubusercontent.com/58553700/227159992-bdb62ea1-8c54-4d4b-9441-3d89025d33fe.mp4

**Comment by cweijan** [comment]
Thanks for the feedback, if you continue pasting without switching the keyboard, will it repeat twice? And will this happen in other software?

**Comment by johny1122** [comment]
yes, it keeps pasting twice and I checked and it doesnt happen in gedit and Chrome

https://user-images.githubusercontent.com/58553700/227165878-6ec5dfdb-e0b2-4012-b23d-af6a8714e768.mp4

**Comment by cweijan** [comment]
Thanks, I'll try to fix it.

**Comment by johny1122** [comment]
Thanks! Great extension :)

**Comment by cweijan** [comment]
Fix in version 6.3.0.
