### ISSUE TITLE
FTP delete files at the same time

### ISSUE THREAD

**Issue by ftorrens** [cweijan/vscode-mysql#802]
Hello, I really liked your extension for visual studio code. I only have one question, in an FTP connection there is a way to select several files at the same time within the same folder, it is to delete them. Right now I can only remove them one by one, I'm working on a MAC in Laravel. I would be very grateful if you could help me.
Greetings

![Laravel](https://user-images.githubusercontent.com/23470742/227204968-5b335528-b336-40c2-9461-bb127e9c629f.png)

**Comment by cweijan** [comment]
Thanks for feedback, I will support batch deletion in the next version.

**Comment by ftorrens** [comment]
Thank you very much, good extension.

**Comment by cweijan** [comment]
Now it supports batch deletion of files. You click on a node first, then hold down the ctrl key or select key, then click on other nodes, and then right-click to delete.

**Comment by ftorrens** [comment]
Very good, I already tried it, thank you very much!
