### ISSUE TITLE
[BUG] MongoDB Atlas Connection Error

### ISSUE THREAD

**Issue by tdortman** [cweijan/vscode-mysql#803]
- Operating system:
  Windows 11
- Database type and version:
  MongoDB v6.2.1

When I try to connect to my MongoDB instance I get the following error: 
![Screenshot_26](https://user-images.githubusercontent.com/57221600/227401107-8b908eb3-1004-4982-89ca-3b8a5e3dfdf9.png)

The database is hosted on their Atlas platform under the 'Serverless' tier if that's relevant.

**Comment by cweijan** [comment]
Thanks for the feedback, I will support it in the next version.

**Comment by tdortman** [comment]
Thanks, appreciate it a lot!

**Comment by cweijan** [comment]
Please try version 6.3.0, I have upgraded the Mongodb connection library.
