### ISSUE TITLE
[BUG] 无法连接低版本SQLServer

### ISSUE THREAD

**Issue by langyo** [cweijan/vscode-mysql#804]
- Operating system: Windows 11 22H2
- Database type and version: Microsoft SQLServer 2012

按理说这问题其实是上游依赖 OpenSSL 的问题，提示为：

```
连接出错! Failed to connect to 10.168.1.196:1433 - 17455368:error:100000f0:SSL 
routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL:../../third_party/boringssl/src/ssl/handshake_client.cc:697:
```

（这里的 IP 地址为临时的局域网地址，无需担心泄露问题）

我查了一下这个报错，应该可以确定是服务端那边的 OpenSSL 所用协议版本太旧、插件使用的 OpenSSL 3.0 不认账导致的错误。

我不知道插件所使用的是否为系统自带的 OpenSSL，也不知道插件所用 OpenSSL 的配置放到哪里了，所以来问下有没有解决方案。

**Comment by cweijan** [comment]
我下版本试下升级连接库看能不能解决.

**Comment by cweijan** [comment]
之前看错了, 我用的连接库就是最新的.. 你试下在连接面板去掉加密勾选看还能不能连, 如果不能连也没法了, vscode的node运行时不支持部分安全协议算法.

![image](https://user-images.githubusercontent.com/27798227/227699940-bf28c1af-fd16-4887-b76d-1098c448f4a0.png)

**Comment by langyo** [comment]
> 之前看错了, 我用的连接库就是最新的.. 你试下在连接面板去掉加密勾选看还能不能连, 如果不能连也没法了, vscode的node运行时不支持部分安全协议算法.
> 
> ![image](https://user-images.githubusercontent.com/27798227/227699940-bf28c1af-fd16-4887-b76d-1098c448f4a0.png)

关掉加密选项后可以连接了，感谢

**Comment by vitash** [comment]
还真是这样，又拯救了一次我的连接。 @cweijan 能不能处理这个异常，提示用户尝试关闭 encrypt，我是直接翻找 issues 才找到解决办法的
