### ISSUE TITLE
Export Data to Clipboard

### ISSUE THREAD

**Issue by franklinkf** [cweijan/vscode-mysql#806]
In the export option placed in the toolbar, is it possible to provide an option to export the data to clipboard?

**Comment by cweijan** [comment]
No, it doesn't make sense to export to the clipboard, I think you can export to csv first, and then copy what you need.

**Comment by cweijan** [comment]
Hi, I added support for copying data to clipboard in 6.5.0 due to many users requesting this.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/17ac402e-be0f-4c54-a20a-eda12575e413)

And you can also export to a new editor when exporting data.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/81e227c9-136c-40d3-9ebd-463d6d8900cc)

**Comment by franklinkf** [comment]
Sir,

My current version is 6.5.10.  But I am not seeing the new options.

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/aed6e044-f950-4e1d-a73f-e9d2e67a3c5a)

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/669c5915-8568-4ca1-af75-9dc5ac2930a2)

![image](https://github.com/cweijan/vscode-database-client/assets/8948123/3d951edc-4635-4cdc-8bea-928afe994971)

Can you please check on this?

**Comment by cweijan** [comment]
Please switch to csv, the excel file is not a plain text file.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/671facae-2e35-41b3-8642-8e3deccb7442)

**Comment by franklinkf** [comment]
Thanks.  Got it.  

Also got the option - Copy to Clipboard option.  It is visible only when we select records.

Great Work. Thank you

**Comment by franklinkf** [comment]
Sir,

We are actively using MySQL and Oracle Databases for our developments.

In case of MySQL, we are using this extension for all purposes except for debugging functions and procedures

In case of Oracle, we are using this extension for querying and data updations.

One of the main use case we feel missing is the facility to update packages.  Earlier also, I have taken up this issue.  We use Package as the container for procedures and functions.  When we update package using Control + enter (same key we use to update MySQL Procedures and Functions), the system generates error.  I don't know the workload/complications to fix this, but if this got fixed I can say all our use cases in Oracle will be dealt by this extension (apart from debugging of procedures and functions)

We will be very grateful if this issue is taken care off.

Thanks once again

**Comment by cweijan** [comment]
Hi, I have not been able to parse the package syntax due to its complexity. You can select the code needed to create the package and execute it.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/cbb3c66c-6688-4693-8975-ea8d000d2081)

**Comment by franklinkf** [comment]
> Hi, I added support for copying data to clipboard in 6.5.0 due to many users requesting this. ![image](https://user-images.githubusercontent.com/27798227/244244275-17ac402e-be0f-4c54-a20a-eda12575e413.png)
> 
> And you can also export to a new editor when exporting data.
> 
> ![image](https://user-images.githubusercontent.com/27798227/244244327-81e227c9-136c-40d3-9ebd-463d6d8900cc.png)

I think the users will  not come to know about these features with the current setup.  My suggestions in this regard is given below:

1. Icon for copying data to clipboard:

This can be made visible all time.  When the user clicks the same, display a prompt to select the required records

2. Export to editor

This can be made visible all time.  When the user clicks the same, display a prompt saying that this option is applicable only if CSV is selected.  Or you can add this option against the Type

Thanks

**Comment by cweijan** [comment]
Great proposal, I will support it in the next version!

**Comment by franklinkf** [comment]
Thanks
