### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by EdnaldoLuiz** [cweijan/vscode-mysql#807]
- Operating system: Zorin OS 16 Lite
- Database type and version: all and v6.3.1

The version 6.3.0 still works, I downloaded it while the version 6.3.1 is like this

The extension is there, but it becomes invisible, as if it is not there
![issue1](https://user-images.githubusercontent.com/112354693/228688289-3d34bca9-2f84-4ef4-b222-4055e0b4865b.png)

when I click on "create connection", nothing happens
![issue2](https://user-images.githubusercontent.com/112354693/228688521-2dd52e8e-b8e4-42e8-a87e-ecc4fc154639.png)

or when I try to click on one of those icons in the top corner I get the following error message, for every icon I click I get this message with the name of the icon
![issue3](https://user-images.githubusercontent.com/112354693/228688599-1dba4ac6-aa95-4110-8399-e49af4476636.png)

I would also like to say that I'm a big fan of this extension, when I found it I couldn't believe it really does exist lol, I even told all my college friends how much I liked it
it's the most complete extension I've found to work with MySQL inside Vscode, keep up the great work! :)

**Comment by cweijan** [comment]
Sorry for the trouble caused by the new version, I need your help, please open the developer tools and show me the error log.

![image](https://user-images.githubusercontent.com/27798227/228695133-a7f0fd84-0b69-4a5a-a094-fa708f5a7d3b.png)
![image](https://user-images.githubusercontent.com/27798227/228695243-81d9a927-ec41-4310-8ea0-017b7bbc26a7.png)

**Comment by EdnaldoLuiz** [comment]
I was in college, sorry for the delay in replying, I've been very busy these days, but I just entered vscode and it looks like the bug has been resolved!

**Comment by cweijan** [comment]
Thanks for the feedback, VS Code sometimes has exceptions, causing the extension to fail to load, usually it will work normally after you restart VS Code.

**Comment by EdnaldoLuiz** [comment]
I restarted it like 5 times yesterday and uninstall it many times, but nothing worked, so I downloaded the v6.3.0, but today it started working after I updtaed to v6.3.1, If the problem returns I will tell you, and thanks!
