### ISSUE TITLE
Connection error! This RDS Proxy requires TLS connections

### ISSUE THREAD

**Issue by abrehman55** [cweijan/vscode-mysql#808]
Trying to connect to an Amazon Database vis SSH Tunnel.

**Comment by cweijan** [comment]
Check use ssl.
![image](https://user-images.githubusercontent.com/27798227/228830569-0940870a-74a1-4685-82a2-7b77b505bfd2.png)

**Comment by abrehman55** [comment]
It was successful. Great Support. Thanks.
