### ISSUE TITLE
Hex-blob

### ISSUE THREAD

**Issue by abrehman55** [cweijan/vscode-mysql#809]
Hex-blob flag for dumping data is necessary when you want to import and export databases which contains binary data like Point or Polygon.

**Comment by abrehman55** [comment]
There could be a checkbox in the settings page to turn flag on or off.

**Comment by cweijan** [comment]
Thanks for the feedback, I will implement it in the next version.

**Comment by cweijan** [comment]
The --hex-blob flag has been added in the latest version 6.3.2.

**Comment by abrehman55** [comment]
How to use this?

**Comment by cweijan** [comment]
Now dump will bring this flag.
