### ISSUE TITLE
SQL语句分段问题，

### ISSUE THREAD

**Issue by Oneupupup** [cweijan/vscode-mysql#810]
这样一条语句不应该分段执行，但是插件中进行了分段
```sql
create function fun1(n int)
returns int DETERMINISTIC
begin
    declare total int default 0;
    while n>0 do
        set total := total + n;
        set n := n - 1;
    end while;
    return total;
end;
```
![image](https://user-images.githubusercontent.com/54873903/229069665-3617308b-52df-4aed-951e-77d85c602639.png)

**Comment by cweijan** [comment]
谢谢反馈, 目前SQL解析还无法涵盖存储过程和函数, 未来会持续优化.

**Comment by cweijan** [comment]
Hi, 已在6.6.8版本优化了SQL的检测逻辑, 请查看是否还有异常情况.

**Comment by Oneupupup** [comment]
非常感谢，经测试已经没有问题了
