### ISSUE TITLE
[BUG] Unable to upload file in FTP

### ISSUE THREAD

**Issue by AppSync-ai** [cweijan/vscode-mysql#812]
When i upload file using FTP, it says file uploaded successfully and also shows time of upload. But file is not being uploaded on server in folder. Other file sync and save is working fine. Only issue while uploading files (images, txt files, php files, etc).
What may the issue?
- Operating system: Windows
- Database type and version: FTP issue

**Comment by cweijan** [comment]
Thanks for the feedback, I will try to fix it in the next version.

**Comment by cweijan** [comment]
Fixed in latest version 6.3.2.
