### ISSUE TITLE
[BUG] Duplicate tables' count info on the tab.

### ISSUE THREAD

**Issue by langyo** [cweijan/vscode-mysql#813]
- Operating system: Win11 22H2
- Database type and version: MariaDB 10.10.2 (Docker on Ubuntu 22.04)

![bug](https://user-images.githubusercontent.com/23103705/229347676-b3813fb0-6636-4a4c-92b0-b746aed58490.gif)

如图所示，当我刷新标签栏里的 tables 信息时，数量信息直接追加到原信息的末尾而非直接修改

我不确定这个问题是否出现在所有类型的数据库，不过作者最好也检查一下其它数据库的 tables 标签页是否也有这种情况

（写英文标题是为了方便他人搜索，没别的意思）

**Comment by cweijan** [comment]
谢谢反馈, 我会在下版本修复.

**Comment by cweijan** [comment]
已发布版本6.3.2修复.
