### ISSUE TITLE
Download multiple folders or files with ftp

### ISSUE THREAD

**Issue by gabeLon** [cweijan/vscode-mysql#814]
Hello, can you select multiple files or folders and download them simultaneously while connected to a remote server by FTP?
By now I am only able to do this with just one file or folder at once.
Thanks.

**Comment by cweijan** [comment]
You can download files in batches through the following steps: click a file, hold down ctrl and select another file, and finally right click to download.

**Comment by gabeLon** [comment]
Thank you.
