### ISSUE TITLE
Double click result header to resize to longest entry

### ISSUE THREAD

**Issue by tdortman** [cweijan/vscode-mysql#816]
I was wondering if it was possible to be able to instead of having manually resize a column width by dragging it around, also just double click where you would click to drag and and width automatically adjusts to the length of the longest entry in that column? Similar to how programs like excel do it.

Some default limit for this would probably make sense to avoid having a column that's absurdly wide ruin everything.

**Comment by cweijan** [comment]
The default is to automatically fit the width of the column, but I limited it to a maximum width of 150px. Now the width is not enough to display your data?

**Comment by tdortman** [comment]
I don't know if it's the fact that my display is running at 1440p, but 150px really doesn't feel like much at all to be honest. Double that or so would be perfect for me but I also realise that'd make things very bad for a lot of other people, hence me asking for the ability for it to auto resize for me when double clicking the header

There's another thing that's been bothering me and that's the fact that when switching between tables, the column width doesn't get reset. So I want to just quickly check some things I'll end up having to manually resize the column

**Comment by cweijan** [comment]
Thanks for the feedback, I will adjust the width in the next version and add options to control the maximum width.

When the table is switched, the column width will be automatically reset, but if you drag to adjust the width, it will not work.

**Comment by tdortman** [comment]
Ah, that'd explain why it didn't reset. Thanks for the quick reply!

**Comment by cweijan** [comment]
Hi, I have added options in version 6.3.2 to control it.
![image](https://user-images.githubusercontent.com/27798227/229701004-d8b2ed64-b2e0-453c-8402-66f32296adf6.png)
