### ISSUE TITLE
MySQL-interfaced PlanetScale Vitesse Database can open and run sql, but...

### ISSUE THREAD

**Issue by tobkle** [cweijan/vscode-mysql#819]
...database and tables in table tree view remains empty.

Would it be a big deal, to get that working?
Thought, as it is a MySQL interfaced database.

[PlanetScale](https://planetscale.com)

**Comment by cweijan** [comment]
Thanks for the feedback, I'll try to make it compatible in future versions.

**Comment by cweijan** [comment]
I created a planetscale connection and it works fine, what is the problem you are having?

![image](https://user-images.githubusercontent.com/27798227/231365315-764610cc-b640-4d8f-a6ef-5327d3c2e4dc.png)

**Comment by tobkle** [comment]
Strange, for me it looks like that. Do you use branches in your database? I use a prod and a dev branch of my database, can that be the reason? That's something, which is special to PlanetScale/Vitess. On the left you see the tree, on the right you see the tables of my database. 

<img width="650" alt="image" src="https://user-images.githubusercontent.com/2720700/231373460-6869aa3c-2cbe-4aa9-814e-08ccddda7c43.png">

**Comment by tobkle** [comment]
Oh, I'm sorry. My mistake. Somehow the first connection wasn't setup correct. I thought that I was connected as I was able to send SQL commands. However, the tree wasn't connected. All fine now. Sorry for bothering you.

<img width="312" alt="image" src="https://user-images.githubusercontent.com/2720700/231375733-4c6f86c0-8662-420f-8d81-729682ceb3a2.png">
