### ISSUE TITLE
Result SQL

### ISSUE THREAD

**Issue by aradovan** [cweijan/vscode-mysql#820]
If you first open  a table, that table name appear on tab, but once you run some SQL, that tab name dissapear and instead of it it's named as "Result". It was useful to be able to see over which table was ran the SQL as sometimes we can handle many tabs at the same time and it's annoying every single tab named as "Result". I can't find in settings how to avoid this...

**Comment by cweijan** [comment]
Thanks for the feedback, I will optimize the display of the name in the next version.

**Comment by cweijan** [comment]
Hi, this is actually a bug, I fixed it in version 6.3.7.

**Comment by aradovan** [comment]
Hi, Thank you very much! Yes it was a bug because it were working fine
before.

Thanks for your super-fast response,

Antonio

**Comment by aradovan** [comment]
Hello again Weijan, how are you?

I'm writting to you just to give you 1 idea about your database extension
for vscode. This is not important at all.
As I work using an ultrawide screen I would like to be able to "stretch"
the SQL editor textarea and make it larger to make better use of the space :

[image: image.png]

I repeat, it's not something important, just a comment in case it's an easy
task. Thank you very much, and again, congratulations on your work. It
helps me a lot in my job.

Regards,

Antonio

**Comment by cweijan** [comment]
Your picture is not showing.

**Comment by aradovan** [comment]
[image: Untitled-2.jpg]

**Comment by cweijan** [comment]
Still the same, I guess replying via email doesn't show your picture.

**Comment by aradovan** [comment]
I've attached the file now...

Antonio
