### ISSUE TITLE
Have an "Attribute" dropdown in column form

### ISSUE THREAD

**Issue by devag-al** [cweijan/vscode-mysql#823]
Would be nice to have an extra dropdown to define an "attribute" to a field (for MySQL at least).

Coming from PHPMyAdmin, I can set those values to a field:

- binary
- unsigned
- unsigned zerofill
- on update CURRENT_TIMESTAMP

Would be faster than typing those attributes in the "type" field each time it is needed.

And it would have the benefit to avoid overwriting the existing attribute on a field update (right now, if a "int unsigned" is edited, it will convert to "int" unless you type back "int unsigned" in the type field).

Thanks ! Continue the good work !

**Comment by cweijan** [comment]
Thanks for the feedback, I will support it in future versions.

**Comment by cweijan** [comment]
Supported in version 6.8.7.
