### ISSUE TITLE
File Type Not Available in Dropdown

### ISSUE THREAD

**Issue by abrehman55** [cweijan/vscode-mysql#825]
This is small update which improve user experience.

- When we click export button from any table, select a file type E.g  .xlsx, windows folder browswer is opened but it does not save the file in required extension. Also it does not allow selecting the required file type from the drop down.
- Although we can type file extension manually in the name field and it works fine.
- But having it available in the dropdown and make it preselected according to the file type chosen earlier would be much nice.

![image](https://user-images.githubusercontent.com/61405290/232761110-3ae6d2dd-d213-4bcb-8ace-18c3f03927b6.png)

**Comment by cweijan** [comment]
Export files only support one format, you should not modify the extension.
