### ISSUE TITLE
Be able to disable auto-formatting of SQL file

### ISSUE THREAD

**Issue by devag-al** [cweijan/vscode-mysql#826]
Hi,

  It would be very useful to be able to disable the auto-formatting of SQL files.

  I want this plugin for the database feature, but not the SQL formatting, which it messed-up more than anymore to my projects standard.

  And even more, for "CREATE TRIGGER", it change to upper-case the trigger name and database name.

  So an option to toggle in the settings if we want or not the formatter would be much appreciated !

Thanks for the good work !

**Comment by cweijan** [comment]
This extension only provides formatting SQL feature, automatic formatting depends on your VS Code settings.

**Comment by devag-al** [comment]
@cweijan But as soon as this extension is installed, it is used to format SQL files.

I'm not aware of any way to make it not format SQL files, unless I change the type to "Plain Text", which also remove the coloring.

I had to add a language feature in my settings that doesn't format SQL file to overwrite the formatting of this plugging.

```json
  "[sql]": {
    "editor.defaultFormatter": "vscode.php-language-features"
  },
```

I thought it would make more sense to simply be able to ask the plugin to not-format SQL files ? The big feature of this plugin (to me at least) being the database connection/interaction, not the formatting.

Or am I getting something wrong here ?  Please advise !

**Comment by cweijan** [comment]
In fact, you can easily find the answer through Google.

https://stackoverflow.com/questions/44831313/how-to-exclude-file-extensions-and-languages-from-format-on-save-in-vscode/44831631#44831631

**Comment by devag-al** [comment]
Looks like I was not looking for the right terms in my search, sorry about that !

Maybe having a section about this in the README could help someone else ?

Thanks for the link !
