### ISSUE TITLE
mongodb json viewer

### ISSUE THREAD

**Issue by melihkucuknazli** [cweijan/vscode-mysql#827]
Hello,

Can you develop an option to display MongoDB query responses in JSON format?

**Comment by cweijan** [comment]
Thanks feedback, I will try support it in future.

**Comment by cweijan** [comment]
Hi, I misunderstood what you mean before, the json viewer has existed before, when you hover to the column, you can view the json after clicking the magnifying glass.

![image](https://user-images.githubusercontent.com/27798227/233934695-21205199-9dbe-47a3-a8fe-199f747034b9.png)
