### ISSUE TITLE
LevelDB key-value store

### ISSUE THREAD

**Issue by aheissenberger** [cweijan/vscode-mysql#828]
Dear Vscode-database-client Team,

Please add support for the key-value store [LevelDB](https://github.com/Level/abstract-level) from Google to the extension. This will allow developers to manage Level databases within the Vscode-database-client interface, making it even more powerful and versatile. Thank you for your consideration.

Sincerely,
Andreas

**Comment by cweijan** [comment]
I'll consider supporting it in the future.

**Comment by cweijan** [comment]
Sorry, since the official nodejs module depends on node-gyp, this doesn't work properly across platforms, I can't support it

**Comment by aheissenberger** [comment]
> Sorry, since the official nodejs module depends on node-gyp, this doesn't work properly across platforms, I can't support it

Thank you for checking - I did not expected a binary dependency as it also runs in the browser
