### ISSUE TITLE
增加关闭代码提示的动能

### ISSUE THREAD

**Issue by zgaaaa** [cweijan/vscode-mysql#830]
希望可以增加一个关闭sql提示的功能，我只是写个逗号或空格就会冒出提示，导致我想换行都不方便
<img width="396" alt="image" src="https://user-images.githubusercontent.com/62388612/236515031-9c033185-4b91-4a87-9bb5-faee9c58d46c.png">

**Comment by cweijan** [comment]
可以配置触发键.
![image](https://user-images.githubusercontent.com/27798227/236515945-5cf78a1c-8991-46ef-8e2f-23765e3181da.png)

**Comment by zgaaaa** [comment]
![image](https://user-images.githubusercontent.com/62388612/236521011-827577d4-0def-453f-9827-c322f15784e9.png)
<img width="544" alt="image" src="https://user-images.githubusercontent.com/62388612/236522718-73856325-4286-4724-9e6f-4207db0d0514.png">
并不管用

**Comment by cweijan** [comment]
需要重启vscode哈, 忘说了
