### ISSUE TITLE
关于ssh的Private Key Path能否支持 "~"

### ISSUE THREAD

**Issue by NightmareZero** [cweijan/vscode-mysql#831]
可以以~开头， 从用户$HOME目录为开头读取文件，
有多台服务器，但是不一定是同一个用户，所以能否支持相对路径？？

**Comment by cweijan** [comment]
如果是$home/.ssh/id_rsa, 那现在就是支持的, 不是这个路径就得等我下版本处理.

**Comment by NightmareZero** [comment]
![Quicker_20230506_171558](https://user-images.githubusercontent.com/17422155/236615230-ec14af0b-2221-480b-867a-348d48a06020.png)
我试过了 $HOME 和 $home 在我这都不起作用

而且如果在windows下面，$home这个还起作用么？？

**Comment by cweijan** [comment]
我说的是密钥的路径, 不是说有$home这个变量. 你的密钥名不是id_rsa, 所以现在还不能支持.

**Comment by NightmareZero** [comment]
> 我说的是密钥的路径, 不是说有$home这个变量. 你的密钥名不是id_rsa, 所以现在还不能支持.

好吧，那就只能等你下个版本了，主要是现在rsa很多地方都不支持了，所以换成了ed25519

**Comment by cweijan** [comment]
已在6.4.3版本支持.
