### ISSUE TITLE
Exporting very slow, and it re-running the query instead of using the data that already retrived

### ISSUE THREAD

**Issue by Aminadav** [cweijan/vscode-mysql#832]
I'm a premium user, why when exporint we need to wait and re-run the query.
Assuming that I made a query and saw the result, I want to export the same results to CSV, without re-run.
Please allow when exporting query without pagination to export the current results from the table (in VS Code cache)

**Comment by cweijan** [comment]
Thank you for your feedback, may I ask if the SQL you originally executed was very slow?

The paging will be removed when exporting, so it will be executed again, and I will make adjustments in the next version. If the paging is not removed, the current data will be used for export.

**Comment by Aminadav** [comment]
I will explain. It is very slow because of my data and complex query. But I do not need it to be executed again when click export. In my case the original was without pagination, so I want to export same data.
Also if there was pagination, I would like to export it without re-run automatically. Let me decide if to re-run, or export the current data.

**Comment by cweijan** [comment]
Thank you for your clarification, I will support it in the next version.

**Comment by cweijan** [comment]
Hi, I have supported this function in the latest version 6.4.4. If you don’t check remove pagination data, the current data will be directly used for export.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/144b89b9-2d46-4471-94a5-634e5ae8ddd7)
