### ISSUE TITLE
[BUG]pgSQL，使用窗口函数，再点击排序按钮，会导致查询错误

### ISSUE THREAD

**Issue by zgaaaa** [cweijan/vscode-mysql#833]
- Operating system: macOS
- Database type and version:v6.4.3
- 连接pgSQL，使用窗口函数是正常查询的，如下图
![image](https://user-images.githubusercontent.com/62388612/236686574-e0b72645-a9ce-4fc4-ba9a-d8bdba4324a8.png)
但是如果点击排序按钮，会将查询语句over里的order by 删掉，导致查询错误
<img width="603" alt="image" src="https://user-images.githubusercontent.com/62388612/236686675-4144e7a8-3ba8-446f-a224-b4401a975ec4.png">

**Comment by cweijan** [comment]
谢谢反馈, 我会在下版本修复它.

**Comment by cweijan** [comment]
已在6.4.4版本修复.
