### ISSUE TITLE
[BUG] Unable to display symbol &

### ISSUE THREAD

**Issue by lzq2357** [cweijan/vscode-mysql#836]
the db string  is '...&timestamp...' , but the query result show '...×tamp...'
the other mysql client , show the right string  '...&timestamp...'

- Operating system: macos 13.3.1
- Database type and version: mysql 5.7.22.22-log

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Fix at version 6.4.6.
