### ISSUE TITLE
[BUG] Search works strange

### ISSUE THREAD

**Issue by mirkadev** [cweijan/vscode-mysql#837]
I have only id column and search works very strange. And if I have more columns - the same. Very bad search last time.

<img width="653" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/45996373/5ff981a6-3c91-4659-9530-7ace6777bb43">

- Operating system: last macOs
- Database type and version: Postgres 13

**Comment by cweijan** [comment]
Did your query include other columns? Now the search will not ignore your hidden columns.

**Comment by mirkadev** [comment]
Hmm, no, only one. I used the following request:

`select DISTINCT id from my_table;`

The table certainly has other columns, but I guess it doesn't matter if there is only one column in my select query, right?

**Comment by cweijan** [comment]
Hi, try the latest version 6.4.6, I think I have fixed it.

**Comment by mirkadev** [comment]
Hi! Yep, it's much better
<img width="219" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/45996373/3a7194f6-c4b8-412e-a3e5-93288dffa170">

Thank you
