### ISSUE TITLE
Error: Timeout: Request failed to complete in 15000ms

### ISSUE THREAD

**Issue by waterlovevip** [cweijan/vscode-mysql#838]
sql执行超过15秒，提示错误超时了，配置了 "connectTimeout": 1800000,"requestTimeout": 1800000也没有生效
<img width="609" alt="1684468188837" src="https://github.com/cweijan/vscode-database-client/assets/5491552/0e1629db-296a-4098-832f-78254cfea066">

**Comment by cweijan** [comment]
谢谢反馈, 我会在下版本修复.

**Comment by cweijan** [comment]
哥们你试下重新创建连接试试, 我本地无论查询多久都不会中断.

**Comment by waterlovevip** [comment]
重新创建了,一样的,插件卸载重装了 还是提示Error: Timeout: Request failed to complete in 15000ms



在 2023-05-19 16:34:20，"Weijan Chen" ***@***.***> 写道：

哥们你试下重新创建连接试试, 我本地无论查询多久都不会中断.

**Comment by waterlovevip** [comment]
哥们这个问题好像恢复了又可以了，很奇怪，早两天死活不行













在 2023-05-19 16:34:20，"Weijan Chen" ***@***.***> 写道：

哥们你试下重新创建连接试试, 我本地无论查询多久都不会中断.

**Comment by cweijan** [comment]
这.. 我也不清楚什么情况, 很奇怪.

**Comment by cweijan** [comment]
那我就关闭issue了
