### ISSUE TITLE
[BUG] Deletes comments!  The extension remove comments from the script when executing the script!!!

### ISSUE THREAD

**Issue by mshakurov** [cweijan/vscode-mysql#839]
- Operating system: Windows 10 x 84
- Database type and version: PostgreSQL 14.0, compiled by Visual C++ build 1925, 64-bit

Why does your extension remove comments from the script when executing the script? 
What are you doing? Do normal people do that?

Scenario:
1) Connect to DB 
2) Select schema and function - the script of the selected function will be opened
3) Immediately execute the script
4) Check the text of the function with any tool, including your extension - all comments will be deleted in the script!!! 

**What are you doing?**

**Comment by cweijan** [comment]
The database does not store comments when you create functions or stored procedures.

**Comment by mshakurov** [comment]
> The database does not store comments when you create functions or stored procedures.

Are you kidding me? Which DBMS does not store comments? Did you come from the moon? My message clearly states the DBMS - PostgreSQL 14.0. Or are you just scammers who are trying to hack a PC through your extension, and that's why you have such gross mistakes and you don't solve them, and give such fake answers? What kind of answer did you give?
