### ISSUE TITLE
macros to automate execution of current statement and cursor down one line

### ISSUE THREAD

**Issue by myusrn** [cweijan/vscode-mysql#840]
Does this extension support mysql.runQuery and mysql.runQueryAllOrSelection commands that would allow you to setup ctrl+shift and ctrl+shift+enter keyboard shortcuts as outlined below?  I thought this extension allowed me to enable the shift+enter one as shown below but doesn't seem to work with the current install of extension.

1. add @name:macros @publisher:geddski extension and then f1 |  prefrences: open keyboard shortcuts (json) | add 

"macros": { "mysqlRunQueryAndCursorDown": [ "mysql.runQuery", "cursorDown" ]  } 

2. f1 | preferences: open user settings (json) | add
 
 { "key": "shift+enter", "command": "macros.mysqlRunQueryAndCursorDown", "when": "editorTextFocus && editorLangId == 'sql'" } 
 // runs statement under cursor or current selection and then cursors down to next line

{ "key": "ctrl+shift+enter", "command": "mysql.runQueryAllOrSelection", "when": "editorTextFocus && editorLangId == 'sql'" } 
// run all or selection if/when this command support is added to extension

**Comment by cweijan** [comment]
Hi, the mysql.query command will execute the selected SQL when you have selected SQL, and run the SQL of the current cursor if you do not select it, and you don’t need to modify anything.

**Comment by myusrn** [comment]
Thanks for the response.  When you say " . . . and you don't need to modify anything." are you referring to fact that there is already a ctrl+enter keyboard shortcut hooked up to that command? I'm looking to enable shift+enter to execute that command and then cursor down to the next line of sql. Something i thought mysql workbench used to do but doesn't in current release so maybe it never did and im mixing it up with another language ide shortcut.

**Comment by cweijan** [comment]
I mean that mysql.query supports running the SQL of the current cursor, or executing the currently selected SQL.

For moving the cursor to the next line after executing SQL, this function is not provided. If you want to use other extensions, you need to create an issue in their repository.

**Comment by myusrn** [comment]
Thanks for clarifications and additional details.  

It appears the first issue was fact that i was using "mysql.runQuery" command in macros extension settings and not the "mysql.query" command supported by your mysql extension.

With that correction in place using keyboard shortcut i define to call macro extension setting that executes `"mysqlQueryAndCursorDown": [ "mysql.query", "cursorDown" ]` doesn't execute line of sql that cursor is on, or selected sql, but does complete the cursorDown step.  

As you suggested i'll open an issue that macros extension repository to see why it appears to not be successfully executing the first step.
