### ISSUE TITLE
无法更新字段

### ISSUE THREAD

**Issue by izilongwan** [cweijan/vscode-mysql#841]
Type: <b>Bug</b>

当存在列类型为blob时，修改出现如图问题

![image](https://github.com/cweijan/vscode-database-client/assets/48234072/fc6c47fb-d8ff-409d-8b4a-da8858bd83f8)

Extension version: 6.4.5
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:19:37.325Z)
OS version: Darwin x64 20.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 6, 6|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id 27686d5b-a59e-48da-9b9f-61e3336d4b9e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyonecf:30548226
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
azdwalk:30721579
pythonms35:30701012
pythonfmttext:30731395
pythoncmv:30739700
fixshowwlkth:30730052
pythongtdpath:30739704

```

</details>

**Comment by cweijan** [comment]
谢谢反馈, 我会在下版本修复.

**Comment by izilongwan** [comment]
> 谢谢反馈, 我会在下版本修复.

好的

**Comment by izilongwan** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/48234072/a6682252-b9d5-47f5-8d7b-0b9de846a815)
![image](https://github.com/cweijan/vscode-database-client/assets/48234072/3d86bf18-a712-4343-8e42-f452ab23581c)
为啥弹窗背景是全黑的，怪怪的🤨

**Comment by cweijan** [comment]
你用的什么主题, 我这边是正常的.

**Comment by izilongwan** [comment]
<img width="429" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/48234072/ff607116-3c80-4978-a46b-9126382a1497">
还和主题有关系吗

**Comment by cweijan** [comment]
颜色是自适应的.

**Comment by izilongwan** [comment]
这个是白色主题啊

**Comment by cweijan** [comment]
颜色是自适应的, 有的第三方主题没调好就会有异常, 不过我使用了你这个主题, 是正常的, 不知道你那里为什么背景变黑了.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/3041eed0-2844-4cac-bdd4-bf54bb402913)

**Comment by izilongwan** [comment]
哦， 好吧

**Comment by izilongwan** [comment]
<img width="905" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/48234072/5e5f9e8d-8f0a-474d-9b8f-7caa06dc0e48">
偶尔正常。。

**Comment by cweijan** [comment]
你这个修改不了不是因为有blob字段, 是因为你的表没有主键.

**Comment by izilongwan** [comment]
> 你这个修改不了不是因为有blob字段, 是因为你的表没有主键.

有主键，只是列名类型改成blob就是那个提示

**Comment by izilongwan** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/48234072/af26f9ae-5205-48e1-a22d-8bf72280041e)
能否都加上查看全部的手势，有的内容太长
