### ISSUE TITLE
[BUG] Deletes comments! The extension remove comments from the script when executing the script!!!

### ISSUE THREAD

**Issue by mshakurov** [cweijan/vscode-mysql#842]
In the previous bug issue #839 , you answered that:
< The database does not store comments when you create functions or stored procedures. >
Do you think there are only schoolchildren here? Who are you kidding?
I use a lot of sql tools with MS SQL and PostgreSQL, and none of them removes comments! 
Neither a tool nor a DBMS!

**BUG**

Your extension remove comments from the script when executing the script.

- Operating system: Windows 10 x 84
- Database type and version: PostgreSQL 14.0, compiled by Visual C++ build 1925, 64-bit

Scenario:

    Connect to DB
    Select schema and function - the script of the selected function will be opened
    Immediately execute the script
    Check the text of the function with any tool, including your extension - all comments will be deleted in the script!!!

**Comment by cweijan** [comment]
Sorry, please stay calm. This is my fault. In order to prevent the comment from causing SQL execution failure, I deleted the comment. I will release a version to fix it as soon as possible.

**Comment by mshakurov** [comment]
I apologize for the nervous reaction. I just lost a lot of lines of very important comments in a large function, and I spent two hours restoring them from backups.
**Your extension seems very convenient and functional, I thought it was the best.** 
But this bug made me angry. I apologize again.

**Comment by cweijan** [comment]
Sorry for the extra work for you.

**Comment by cweijan** [comment]
Hi, comments will no longer be removed in the latest version 6.4.6.
