### ISSUE TITLE
Select table columns for copy

### ISSUE THREAD

**Issue by mirkadev** [cweijan/vscode-mysql#843]
Hi!

Now if I want to select all ids in the columns - I can't do it - only the first one.
It would be great to have an opportunity to select all columns in a column - as it happens in Excel, for example.

<img width="127" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/45996373/44a1d0ea-0340-489c-838e-a640764e168b">

Thanks.

**Comment by cweijan** [comment]
Hi, you can right click on the header row.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/8ff01e9b-d590-49f4-89ae-dba43a7ec65f)
