### ISSUE TITLE
> 你这个修改不了不是因为有blob字段, 是因为你的表没有主键.

### ISSUE THREAD

**Issue by izilongwan** [cweijan/vscode-mysql#844]
> 你这个修改不了不是因为有blob字段, 是因为你的表没有主键.

有主键，只是列名类型改成blob就是那个提示

_Originally posted by @izilongwan in https://github.com/cweijan/vscode-database-client/issues/841#issuecomment-1563870644_

**Comment by cweijan** [comment]
有主键的话列前面会有个红*, 你确认下.. 我试了加个blob列是正常的
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/720516d1-8001-4e81-8702-c57d4e048b32)

**Comment by izilongwan** [comment]
新加的好像没问题，我之前是改某列的类型就不行

**Comment by cweijan** [comment]
你看看你之前那个表还正常不, 和blob列无关, 是因为没有检测到主键, 可能是刚好因为网络问题导致列信息没有加载出来.

**Comment by izilongwan** [comment]
好吧，那可能是正常的

**Comment by izilongwan** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/48234072/bb176532-9599-482d-98f3-8b13549b4b03)
这个 查看全部能都加上吗

**Comment by cweijan** [comment]
你指什么呢, 描述清楚点, 现在不是已经显示了放大镜

**Comment by izilongwan** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/48234072/ec054019-aa9e-4e4d-84b7-a8a1bee92c09)

这个没有

**Comment by cweijan** [comment]
你右键Edit row看看有没有, 这个我去看看怎么回事
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/a79ef102-fcc9-4bc1-bf77-58ce60418b00)
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/b5497805-d463-4a93-b7b7-18cbf8d86301)

**Comment by izilongwan** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/48234072/c856e3c6-6e46-4ba8-b683-3bdd70bfbc5e)

临时表都没有吧

**Comment by cweijan** [comment]
我下版本优化下

**Comment by izilongwan** [comment]
![v2-6958db523a94b94e04f3071a3e733d80_720w](https://github.com/cweijan/vscode-database-client/assets/48234072/722bc6d5-89d0-459f-9261-de26eb3458cf)
