### ISSUE TITLE
[BUG] Login with Github fails on Mac OS

### ISSUE THREAD

**Issue by dselman** [cweijan/vscode-mysql#845]
I purchased a subscription using my Github account.

- Operating system: Mac OS
Version: 1.78.2 (Universal)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z (2 wks ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.3.0
Sandboxed: No

When I attempt to login using Github is fails to authenticate the VSCode extension:

![image](https://github.com/cweijan/vscode-database-client/assets/623108/182f7d11-c4a4-4c89-9e0f-0fea3ba1e272)

Errors inside Safari Version 16.3 (18614.4.6.1.6):

![image](https://github.com/cweijan/vscode-database-client/assets/623108/4ea9b861-91d3-43ac-bf8a-0a4a0991133e)

**Comment by cweijan** [comment]
Hi, go to the URL below, and click Login in VScode.

https://database-client.com/#/plan?source=8828_cweijan.vscode-mysql-client2

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/1688d4b9-c0b8-465a-9473-0b5298fc09e8)

**Comment by dselman** [comment]
Interesting - that seemed to work, but it prompted me to install another VSCode extension, called MySQL. So I now have two extensions installed: MySQL and Database Client. Which should I be using?

**Comment by cweijan** [comment]
Hi, these two extensions are the same, please keep either one.

**Comment by cweijan** [comment]
If it is Database Client, the url you need to visit is https://database-client.com/#/plan?source=8828_cweijan.vscode-database-client2
