### ISSUE TITLE
Automatically resize columns in result pane to fit data

### ISSUE THREAD

**Issue by mmcintyre123** [cweijan/vscode-mysql#846]
Currently, when I execute a query, the width of the columns in the result pane is too small, cutting off the data.  
My request would be to either (in order of preference)
1) automatically resize columns in the result pane to fit the data immediately after a result is returned, or 
2) create a button to resize the columns to fit the data
![image](https://github.com/cweijan/vscode-database-client/assets/12388285/2681aeb9-37bb-49e2-bc3e-159d8b574c5a)

Or perhaps both 1 and 2 - then if the auto-resizing fails for some reason you can click the button to try again.

**Comment by cweijan** [comment]
Hi, the width is automatically adapted, but the maximum value is limited, you can modify this option in the console.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/d320b371-3eac-4825-87a1-e8867f126aa6)

**Comment by mmcintyre123** [comment]
I see - thank you!
