### ISSUE TITLE
[BUG] An object or column name is missing or empty.

### ISSUE THREAD

**Issue by quocvinzw** [cweijan/vscode-mysql#848]
When I Update Data,Insert,And Delete Data then an errors occurs.

![image](https://github.com/cweijan/vscode-database-client/assets/52127564/52f04a18-192a-492a-97f4-f1d6f39c972d)

I think it might be because of the latest version v6.4.8, it makes the Title with a "" wrap a table name.

![image](https://github.com/cweijan/vscode-database-client/assets/52127564/a60c7b16-0e08-4a48-8b95-6f6ef5a9b36a)

In Console Execute: 
![image](https://github.com/cweijan/vscode-database-client/assets/52127564/97c0d263-f0b9-42db-92ba-742783713537)

When I Use OldVersion v6.4.7,it's really good and no errors.
Old Version:
![image](https://github.com/cweijan/vscode-database-client/assets/52127564/89eae472-2a87-4230-8be3-d56d781a886c)

Update:
![image](https://github.com/cweijan/vscode-database-client/assets/52127564/245cb459-f830-4d66-ab4b-db245b1e08a1)

- Operating system: last Windows 10
- Database type and version: MSSQ

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it as soon as possible.

**Comment by cweijan** [comment]
I have released version 6.4.9 to fix.
