### ISSUE TITLE
Connection error!self signed certificate in certificate chain

### ISSUE THREAD

**Issue by spdf36** [cweijan/vscode-mysql#849]
when ever i try to connect with my database i get this error : Connection error!self signed certificate in certificate chain

- Operating system:
- MacOS Ventura
- Database type and version:
- Latest

**Comment by cweijan** [comment]
What is the type of database you are connected to? And try to adjust the following settings.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/50e1c8f1-b576-4ee5-aec6-3101a335a775)
