### ISSUE TITLE
Feature request: Export to new editor (without saving a file)

### ISSUE THREAD

**Issue by Aminadav** [cweijan/vscode-mysql#850]
I'm a premium user, and I really needs the option to export to clipbaord instead of file.
It will save much time I believe for other users also. I don't need a file just the data. 
<img width="495" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/3584317/a10c322d-2331-4d90-9a91-df254d9edf68">

Alternativly, instead of asking the user for filename, just had an option to open a new blank unsaved editor, with the data.

**Comment by Aminadav** [comment]
I mean around here I believe:

https://github.com/cweijan/vscode-database-client/blob/559f9a70aceb49f7a9a5ef164e36d95145eb69b7/src/service/export/exportService.ts#L14

To do something like that:


```typescript
vscode.window.createTextEditor().then(editor => {
    editor.edit(editBuilder => {
      editBuilder.insert(new vscode.Position(0, 0), context);
    }).then(() => {
      editor.show();
    });
  });
  ```
  
  That way I don't need to provide a file path, and can start directly use the text (JSON/MARKDOWN....)

**Comment by cweijan** [comment]
Thank you for your feedback, exporting to clipboard is planned and will be implemented in the next version.

**Comment by Aminadav** [comment]
I mean maybe instead (or in addition to clipboard), exporting to blank file it will be very helpfull.
In addition, when exporting to CSV on Mac the default folder it root (/) and it outside of the project, so it make it long process to save to directory in the current project workspace.

While working on it, I suggest keep the settings persitence, so if I choose save to blank file, to keep the settings, until changed it.

Thanks you for everything! awesome project.

**Comment by cweijan** [comment]
Thank you, these are indeed issues worthy of attention, I will support them in the next version.

**Comment by cweijan** [comment]
Hi, in the latest version 6.5.0 you can directly copy data or export data to the editor.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/17ac402e-be0f-4c54-a20a-eda12575e413)

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/81e227c9-136c-40d3-9ebd-463d6d8900cc)

**Comment by Aminadav** [comment]
Thank you. I Confirm that it's working. Your the best!
