### ISSUE TITLE
How to install the Launch Code

### ISSUE THREAD

**Issue by lexman1958** [cweijan/vscode-mysql#851]
Hi,

I just purchased a license and I received a Launch Code. How do i install the Launch Code and get it activated?

**Comment by cweijan** [comment]
Please check this link, premium is activated by logging into your account.

https://database-client.com/#/loginGuide

**Comment by cweijan** [comment]
You did not receive the activation email probably because it was marked as spam. Please check your spam.

**Comment by lexman1958** [comment]
It was not receive. I am premium. I just login into my account and presses the Login VS Code. I get this page:

![Screenshot_3](https://github.com/cweijan/vscode-database-client/assets/127527088/aeea0405-bdb2-4d25-a39c-f5447ec22a42)

**Comment by cweijan** [comment]
Yes, displaying this page means that it has been activated, and your VS Code has now unlocked premium.

**Comment by lexman1958** [comment]
Ok thank you.
