### ISSUE TITLE
Universal table search

### ISSUE THREAD

**Issue by iamlazyjoe** [cweijan/vscode-mysql#852]
How about using Cmd+P to search & enter db_name.table_name to show candidates, and then click to go to the select result of that table(like what phpstorm does)?
It would definitely save devs tons of time!!

**Comment by cweijan** [comment]
Thank you for your attention, this operation is not supported yet, I will consider implementing it in the future.

**Comment by cweijan** [comment]
Data search is supported in version 7.0.6.

<img width="613" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/27798227/2e0958fc-858d-403c-b9e4-52b871c9cd6f">
