### ISSUE TITLE
[BUG] Viewing Long Text in Redis Hash Illegible

### ISSUE THREAD

**Issue by canadiannomad** [cweijan/vscode-mysql#853]
- Operating system:
MacOS 12.6.3
VS Code Insiders 1.80.0

- Database type and version:
Redis 6.2.6

Looking at a Redis Hash, eg
```
HSET somekey id "012345678" content '{"some":"long", "json": "blob"}'
```

I can't see the entire json blob in the viewer.  If i hover over the value of the field, it shows the complete json, but with a clear background and running off the edge of the screen.  (Or doesn't show at all if it is very long)
<img width="951" alt="Screen Shot 2023-06-13 at 2 11 51 PM" src="https://github.com/cweijan/vscode-database-client/assets/236513/16feedf7-b975-46af-af2b-abf4722b1503">

Clicking Edit on the field gives a small text box where you can only see a small portion of the blob.
<img width="930" alt="Screen Shot 2023-06-13 at 2 05 44 PM" src="https://github.com/cweijan/vscode-database-client/assets/236513/a10824ea-9772-4a53-8622-bdcfe0642958">

Ideally there would be a way to see the full json nicely formatted and highlighted... But at least there should be a better modal box for long text in that view. 
eg:
<img width="928" alt="Screen Shot 2023-06-13 at 2 15 35 PM" src="https://github.com/cweijan/vscode-database-client/assets/236513/43887c4f-8740-497c-8952-b58ac262bbe0">

**Comment by cweijan** [comment]
Thank you for your feedback, I will be compatible with long strings in the next version.

**Comment by cweijan** [comment]
Has been supported in version 6.5.5.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/bcea90d5-6423-4ee1-ad2e-1b57899dbf6a)

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/85cf2744-69a6-4611-89d6-6c96cbaaec6b)
