### ISSUE TITLE
[BUG] tinyint is missing the width, expected tinyint(1)

### ISSUE THREAD

**Issue by alekkha** [cweijan/vscode-mysql#854]
- Operating system: Windows, 
- Database type and version: MySQL/MariaDB
- VS Code extension MySQL v6.5.2
 The type tinyint is expected to be shows including the width, e.g. tinyint(1) or tinyint(4), but is show just tinyint without the width. In older versions of the extension It was tinyint(1)
![image](https://github.com/cweijan/vscode-database-client/assets/136616173/cfc4ab5e-21c2-4259-97c5-4c258e75e3a6)

**Comment by cweijan** [comment]
Thanks for your feedback, I'll look into it.

**Comment by cweijan** [comment]
Hi, this is not a bug. In the new version, I adjusted the loading method of the type so that it can load the length of text. Although tinyint is set to (1), it actually has no effect, and the value range is still -128 to 127.

**Comment by alekkha** [comment]
Right, it does not affect the value range, but it does affect the display width, i.e. the type can be (1) or (2) or (4) yet the extension does not show whether the type was (1) or (2) or (4). See [https://stackoverflow.com/a/40938860](url)

**Comment by cweijan** [comment]
Ok, this is interesting, I will support his display in the next version.
