### ISSUE TITLE
[BUG] The connection timeout cannot be saved.

### ISSUE THREAD

**Issue by NightmareZero** [cweijan/vscode-mysql#855]
- Operating system:
  - Windows11
  - Fedora38

- Database type and version:
  - ssh

"Connect Timeout" can not save, it always  "5000"

save button only applies to the currently open "edit connection" page, the next time you open it, it will be restored to "5000".

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed in version 6.5.3.
