### ISSUE TITLE
[BUG] Changing the query does not actually take affect

### ISSUE THREAD

**Issue by ppseprus** [cweijan/vscode-mysql#856]
- Operating system: MacOS 13.3.1
- Database type and version: multiple (MariaDB, PostgreSQL, etc.) on `v.6.5.2`

**Steps to Reproduce**
1. Write a simple query and run it
2. Wait for the query to finish and then change the query (eg. type `EXPLAIN` in front of it)
3. Run the new query

**Expected Behaviour**
Results for new query appear. Query text stays unchanged.

**Actual Behaviour**
**Query texts reverts to previous query**, and that query is then ran.
The results are for that previous query, not the new.

https://github.com/cweijan/vscode-database-client/assets/1323285/0c38f03a-2976-4326-9569-8f104e0892cb

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed in version 6.5.3.

**Comment by ppseprus** [comment]
Thanks!
