### ISSUE TITLE
[BUG] Tables not opening

### ISSUE THREAD

**Issue by abrehman55** [cweijan/vscode-mysql#857]
- Operating system: Windows
- Database type and version: MYSQL

when click on any of the tables in a mysql database following error appears 

`Actual command not found, wanted to execute mysql.table.find/16`

The issue is not database dependant, tried with several datbase from different mysql versions. 
![image](https://github.com/cweijan/vscode-database-client/assets/61405290/c3ba5e7e-f119-461c-894a-d8e31261a49b)

**Comment by cweijan** [comment]
Yes, this is a problem after vscode version 1.75, please click the refresh button to refresh.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/0ada0c56-d9d3-4bb2-ab4e-9fdd1fe9b712)
