### ISSUE TITLE
[BUG] SFTP support is missing

### ISSUE THREAD

**Issue by pmathbliss** [cweijan/vscode-mysql#858]
- Operating system: Windows 10
- Database type and version: SFTP

I am on the paid version. An actual sFTP connection is missing from the connection options. An ssh and sftp connection are different types of connections. You could add this to the FTP connection.

**Comment by cweijan** [comment]
I will not create a separate connection for sftp, there are too many connection types now.

Note that although ftp and sftp have similar names, their implementation methods are completely different, so they cannot be placed in the same panel.

**Comment by pmathbliss** [comment]
I'll do it. Thanks.
