### ISSUE TITLE
Dump data需要安装mysql-client，但是我本地已经安装mysql了，可以选择本地的mysqldump么？

### ISSUE THREAD

**Issue by miaokela** [cweijan/vscode-mysql#859]
- Operating system: Macos m2
- Database type and version: 10.3.36 maraiadb

Dump data需要安装mysql-client，但是我本地已经安装mysql了

**Comment by cweijan** [comment]
dump依赖mysqldump, , 你应该是没有加到环境变量, 在~/.bash_profile配置的不算环境变量.

**Comment by miaokela** [comment]
which mysqldump是可以输出路径的，建议提示一个插件默认加载的命令路径，并且允许修改

**Comment by cweijan** [comment]
扩展提供配置和去配置环境变量没什么区别, 这个扩展有很多依赖外部的, 不会考虑去加这些路径的配置. 
环境变量通常是配置在/etc/profile
