### ISSUE TITLE
[BUG] Dump data fails with "version mismatch"

### ISSUE THREAD

**Issue by Pictor13** [cweijan/vscode-mysql#860]
Hello, I just purchased the Premium plan and I'm trying to dump data from my db, but it's failing.

- Operating system:
```
$ pg_dump --version
pg_dump (PostgreSQL) 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1)
```
- (Remote) Database type and version:
PostgreSQL 15.1 on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0, 64-bit

Steps:
- successfully connect to a database connection
- right click on database name, select "Dump Data"

Results:
```
pg_dump -h db.gebpdqlhztphupzrbmrq.supabase.co -w -p 5432 -U postgres postgres >'/home/myuser/project/customers/_backups/myproject/postgres_2023-06-28_051914'
pg_dump: error: server version: 15.1; pg_dump version: 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1)
pg_dump: error: aborting because of server version mismatch
```

The `postgres_2023-06-28_051914` is empty.

How can I resolve and dump my data?

**Comment by Pictor13** [comment]
Ok, the VSCode extension doesn't know what version of the postgres-client is available on user's OS.

In my case Ubuntu default repository provide the library only until PS version 14, but my remote database is version 15.

To resolve I followed this official guide (https://www.postgresql.org/download/linux/ubuntu/) to add APT repositories, so to make the version 15 available.

Maybe the script that runs the `apt-get install postgres-client` could be wrapped to add an additional check and suggest to visit `https://www.postgresql.org/download/linux/ubuntu/`, in case they get failure with "version mismatch" during execution.

**Comment by cweijan** [comment]
Yes, the pg_dump of the lower version cannot dump the new version of psotgresql, thank you for your experience!
