### ISSUE TITLE
[BUG] postgresql 无法导出表结构和表数据

### ISSUE THREAD

**Issue by zhangjiankui** [cweijan/vscode-mysql#861]
- Operating system: MacOS 
- Database type and version: postgresql 15.3 Docker部署

点导出时，会打开新终端尝试安装 postgresql-client，然后因为包不存在而中断
<img width="668" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/26133797/3138e54f-0db9-48e2-a4e0-8ae92101f67f">

与之相对的，导出MySQL时能直接生成sql文件

**Comment by cweijan** [comment]
你好, 由于我个人没有使用mac系统, 可以麻烦你参考下面的连接使用libpq吗.

https://stackoverflow.com/questions/44654216/correct-way-to-install-psql-without-full-postgres-on-macos

**Comment by zhangjiankui** [comment]
不行，安装libpq后还是直接走安装postgresql-client这一步

**Comment by cweijan** [comment]
安装libpq还需要配置到环境变量(/etc/profile)扩展才能识别, 等下个版本我检测下安装路径.

**Comment by zhangjiankui** [comment]
哪个环境变量？我可以直接加？

**Comment by zhangjiankui** [comment]
是否可以不走psql客户端，直接用插件已有的连接来查询并生成sql语句文件？用Docker部署或者远程的话本地就没有客户端了

**Comment by cweijan** [comment]
配置环境变量应该是这样的, `echo 'export PATH="/usr/local/opt/libpq/bin:$PATH"' >> /etc/profile`

扩展内有实现一个导出, 但是不能百分百还原数据, 所以在新版本去掉了, 等我下版本还原下吧, 使用官方的客户端主要是导出的数据更加完整准确.

**Comment by zhangjiankui** [comment]
重启vscode后可以了。应该是环境变量要重启才能刷新。但是导出的sql文件的数据段不是用insert语句而是 COPY table FROM stdin语句，希望可以增加可选项选择用不用insert语句
<img width="917" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/26133797/dc1c1f39-1ddc-429b-8d27-03be5a80df8e">

**Comment by cweijan** [comment]
你可以试下先查询表, 然后再导出为SQL.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/a39a34b2-2186-4dd9-ac70-b253aef38eb8)

**Comment by zhangjiankui** [comment]
可以，这个正是我需要的功能

**Comment by zhangjiankui** [comment]
为何我这里没有【导出到编辑器】的按钮？
<img width="436" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/26133797/da85248e-a8a4-4cd1-a4d7-cebbf5aac3df">

**Comment by cweijan** [comment]
显示的逻辑有点问题, 下版本修复.

**Comment by zhangjiankui** [comment]
ok, 谢谢

**Comment by cweijan** [comment]
已在6.5.8版本优化细节.
