### ISSUE TITLE
[BUG] postgresql 「打开终端」时，使用了mysql客户端

### ISSUE THREAD

**Issue by zhangjiankui** [cweijan/vscode-mysql#862]
- Operating system: MacOS
- Database type and version:postgresql 15.3 Docker

本地已经安装好psql了，但是使用了mysql客户端
<img width="735" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/26133797/59a39a52-ee98-45a4-a0e5-b7531aec38e8">

**Comment by cweijan** [comment]
谢谢反馈, 我会在下版本修复.

**Comment by cweijan** [comment]
已在版本6.5.8修复
