### ISSUE TITLE
[BUG]与NuGet Package Manager GUI插件不兼容

### ISSUE THREAD

**Issue by Realittttty** [cweijan/vscode-mysql#863]
- Operating system:Windows10
- Database type and version:MariaDB 10.11

启用此扩展会导致[NuGet Package Manager GUI](https://marketplace.visualstudio.com/items?itemName=aliasadidev.nugetpackagemanagergui)不可用，禁用后恢复正常，对.net开发人员来说挺伤的，希望能修一下。
启用时
![image](https://github.com/cweijan/vscode-database-client/assets/43271921/b445a9b6-e7b8-4a3a-af8a-fb9149cf58c5)
禁用后
![image](https://github.com/cweijan/vscode-database-client/assets/43271921/19ed8e8f-9d02-4f72-b64a-181e28f3f320)

**Comment by cweijan** [comment]
怎么个不可用法?

**Comment by Realittttty** [comment]
我在github上传了图片，主要的问题是会让nuget package manager gui这个扩展用不了，无限卡在加载页面，nuget package manager gui这个插件对.net开发人员来说是很方便的，以前这两个插件同时启用没有任何问题，但是现在只能二选一真的很难受。

**Comment by cweijan** [comment]
好的, 我去看看什么情况

**Comment by Realittttty** [comment]
具体的复现方法：电脑里面需要有.net sdk，任意版本应该都可以，新建一个文件夹然后通过vscode打开，在vscode中安装nuget package manager gui扩展，在vscode的终端中输入并执行dotnet new console，这将创建一个空的.net的控制台程序，然后ctrl+shift+p打开nuget package manager gui，此时如果database client扩展是启用状态，nuget package manager gui会一直卡在加载页面；而如果将database client扩展禁用并重启vscode，nuget package manager gui则可以正常工作。我测试的时候已经将与.net开发无关的扩展都禁用/卸载了，也尝试过删除vscode的缓存，不过我也只在自己的电脑上测试过，暂时没有其它电脑可供测试，如果这个问题无法复现那只能怪我太菜了，这是个好插件，谢谢。

**Comment by Realittttty** [comment]
啊，大佬太强了，一个晚上就更新修复好了，已经用上了，感谢！

**Comment by cweijan** [comment]
嗯, 因为有其他问题也要修复, 就更新了.
