### ISSUE TITLE
[BUG] Console ui issue

### ISSUE THREAD

**Issue by ilteoood** [cweijan/vscode-mysql#864]
- Operating system: OS X Ventura 13.4.1
- Database type and version: v6.5.8

In the console UI, the logo is overlapping with the tabs:
![image](https://github.com/cweijan/vscode-database-client/assets/6383527/e9924814-e832-4a16-9a8c-92a12f5bf01b)

**Comment by cweijan** [comment]
Thank you for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed in version 6.5.12
