### ISSUE TITLE
[BUG] redis list数据显示问题

### ISSUE THREAD

**Issue by SPCDTS** [cweijan/vscode-mysql#865]
- Operating system: win11
- Database type and version: redis_version:7.0.8

## 使用商店的扩展 List 内容无法正常显示
<img width="657" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/29391120/3062416d-4e48-43f2-9736-801878a233a2">

## 使用插件带的xterm的查询结果
<img width="210" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/29391120/f844e5f2-9666-459a-bb57-0f4a0ec1adb3">

_似乎因为key有两个冒号？导出数据也只能导出空的JSON_

## 使用仓库当前分支的最新代码是能正确显示的
<img width="891" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/29391120/87d71918-dc41-4bf2-939e-2b2278a65135">

**Comment by cweijan** [comment]
谢谢反馈, 我会尽快修复.

**Comment by cweijan** [comment]
已发布6.5.9版本修复.

**Comment by SPCDTS** [comment]
感谢 😘
