### ISSUE TITLE
[BUG] mongo queries not loading

### ISSUE THREAD

**Issue by Enubia** [cweijan/vscode-mysql#866]
- Operating system: OSX Ventura 13.2.1
- Database type and version: MongoDB latest/Database Client v6.5.9

Queries are loading indefinitely

I know that it was working just fine a few days ago.

Official Mongo extension loads the documents correctly as can be seen in the provided screenshot

![Screenshot 2023-06-29 at 12 47 12 PM](https://github.com/cweijan/vscode-database-client/assets/44695100/b8d8a143-c530-4df8-ae26-a2e4e5940673)

## UPDATE

Installed v6.5.7 and this one works. v6.5.8 is also broken

![image](https://github.com/cweijan/vscode-database-client/assets/44695100/bb4270d4-9b12-4e9f-8b0c-f95b724e1461)

**Comment by cweijan** [comment]
Can you try disabling other extensions? everything works fine for me.

**Comment by Enubia** [comment]
Tried it right now and same result with the latest version

If it was due to another extension I would assume that previous versions wouldn't work either but as mentioned 6.5.7 works just fine

EDIT:

The database itself is fine since it doesn't work with my production connection either

**Comment by cweijan** [comment]
This is strange, please help to report the error log:
1. Press f12 on the result page
2. Open output

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/78d6699f-5e4d-41ed-b894-1a2eab55e392)

**Comment by Enubia** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/44695100/87deff72-2670-415a-be79-bde8c4876df7)

![image](https://github.com/cweijan/vscode-database-client/assets/44695100/bb63d6c6-5fd9-4941-9745-77c72eebd7c3)

**Comment by cweijan** [comment]
Thanks for the feedback, I have released version 6.5.10 to fix it.

**Comment by Enubia** [comment]
Thanks a lot, works perfectly fine again!
