### ISSUE TITLE
[BUG] Dump data report error on macos 13

### ISSUE THREAD

**Issue by DDDHuang** [cweijan/vscode-mysql#868]
- Operating system:
- Database type and version: MySQL.
<img width="670" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/44492639/61f372f2-edde-4dd8-aa40-86183d419242">
</br>
Required mysql-client. But in previous version. It works good.
PS:
I has a table name is `groups`. I know it conflicts with system keywords . But I cannot change it. This table name created by my customer. When i click this table, The SQL will crash. 
Worked good after manually adding symbols. "SELECT * FROM `groups`". 
It is recommended to add single quotes to the table name.

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Hi, I restored the dump of the old version in version 6.5.11, and I didn't notice the groups keyword, I will automatically add escape characters for it in the next version.

You can also add escape characters to all objects by checking the following options.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/82b8b64d-237e-46d9-acef-adc85f8f9b27)
