### ISSUE TITLE
[BUG] Double spaces in the Result tab

### ISSUE THREAD

**Issue by GTonehour** [cweijan/vscode-mysql#869]
Great extension, happy to pay for it.

Double spaces (and carriage returns) are well rendered in the "View on Dialog" window, but not directly in the Result tab. For instance if I SELECT the value `a     b` (with five spaces between a and b), the Result tab will display `a b` (with only one space).

(Extension 6.5.11, Windows, PostgreSQL 15)

![Bug double spaces](https://github.com/cweijan/vscode-database-client/assets/86954612/15534d79-e4e5-44c0-b713-59223d7a7a1a)

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed in version 6.5.12

**Comment by GTonehour** [comment]
It works indeed. Thank you !
