### ISSUE TITLE
[BUG] SSH error: Timed out while waiting for handshake

### ISSUE THREAD

**Issue by Shawn-Huang-Tron** [cweijan/vscode-mysql#870]
- Operating system: mac os arm64 Ventura13.4
- Database type and version: 

这个插件6.5.1版本之后貌似就没法用ssh私钥的方式去连接远程的数据了，我之前版本用的好好的，更新版本后就连接不上去了，一直报：SSH error: Timed out while waiting for handshake
但是我回退到6.5.5版本后就OK了

**Comment by cweijan** [comment]
但是关于ssh连接的代码并没有修改... 从6.5.6开始有这个问题吗

**Comment by Shawn-Huang-Tron** [comment]
我刚刚又试了下，6.5.5的也是会有间歇性的问题，我又回退到了6.5.1就比较好了

**Comment by Shawn-Huang-Tron** [comment]
我还在想，是不是你的连接超时时间设置得过短的原因？

**Comment by cweijan** [comment]
那这和版本无关, 是你的服务器本来连接就慢, 你调整下超时时间.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/66661673-7417-4896-b2e4-ecb14e2bd823)

**Comment by Shawn-Huang-Tron** [comment]
那我试试吧

**Comment by Shawn-Huang-Tron** [comment]
还是有问题，有时候可以有时候不可以，但是我发现，好像配置这个连接超时的时间并不生效。我配了15S，结果没等几秒钟就给我说超时了，这个好像是tcp连接握手阶段的超时，和这个超时不是同一个？

**Comment by cweijan** [comment]
这个超时时间我去排查下, 可能没有成功应用, 等我下版本修复.

**Comment by cweijan** [comment]
已在版本6.5.12修复超时时间不生效的问题.
