### ISSUE TITLE
I found a weird query in my db log

### ISSUE THREAD

**Issue by amoilmomcode** [cweijan/vscode-mysql#871]
I've been using your MySQL extension at my work. However, as soon as I implemented the extension, We've been seeing a weird query that goes like: 

SELECT COUNT ( * ) `count` FROM ( SELECT * FROM `tbl` ) `temp`

Though this is a valid query, it has been locking our db as it is making a new table `temp`. 

I am wondering if this is from the extension as I would love to use the extension for work.

**Comment by cweijan** [comment]
I didn't create a table for it, I think it was created by the MySQL server, you can try it with other clients.

**Comment by amoilmomcode** [comment]
Sorry, I meant temporary table (it does not stay on DB). I am just wondering that if extension would use any query like that query.

**Comment by cweijan** [comment]
I said that no table was created, and of course the temporary table is also included.

**Comment by amoilmomcode** [comment]
Okay. Thank you.

**Comment by leonyu879** [comment]
Found the same SQL logs that do not appear in history. It seems they are executed automatically when the connection is lost and then reconnected.
<img width="1776" height="618" alt="Image" src="https://github.com/user-attachments/assets/02b35ae5-70e1-4a3e-809a-f88045a981b7" />

**Comment by leonyu879** [comment]
<img width="2386" height="1184" alt="Image" src="https://github.com/user-attachments/assets/f9b4248b-284c-4bf8-aa35-eea011b963ed" />

**Comment by leonyu879** [comment]
<img width="1024" height="138" alt="Image" src="https://github.com/user-attachments/assets/1f0d93bb-aecb-4e11-a975-8920e2e74dba" /> 👌🏻
