### ISSUE TITLE
[BUG] Update stored procedure is not supported

### ISSUE THREAD

**Issue by Shivam-Asija** [cweijan/vscode-mysql#872]
Changes not saving to remote connection

**Comment by cweijan** [comment]
What Changes? Please provide more detailed information.

**Comment by Shivam-Asija** [comment]
I am trying to edit a stored function.
But not able to save the changes i made in my vs code extension to the
database

**Comment by cweijan** [comment]
This is because the extension does not provide the feature of directly saving stored procedures, you need to manually delete and recreate it, I will plan to support directly saving stored procedures in the future.

**Comment by cweijan** [comment]
Hi, in version 6.7.0 there will be an additional drop DDL that you can use to drop and recreate stored procedures.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/68f254cd-2dc4-4d79-b6ce-59023d3985cc)
