### ISSUE TITLE
[BUG] SQL文件全选执行时，会生成大量Result标签页

### ISSUE THREAD

**Issue by zhangjiankui** [cweijan/vscode-mysql#873]
- Operating system: MacOS 13.3
- Database type and version: PostgreSQL 15.3

SQL文件中有多个SQL语句，全选执行后，会生成大量Result标签页，大概是和SQL语句数量一样。
<img width="1025" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/26133797/b73acbc3-1ab1-4297-9e0d-6a6db38284f0">

**Comment by cweijan** [comment]
谢谢反馈, 这个是用来处理多select结果集的情况, 我会在下版本修复.

**Comment by cweijan** [comment]
Hi, 这个是因为truncate被错误检测成了select, 我已发布版本6.6.0修复.
