### ISSUE TITLE
[BUG] PostgreSQL查看DDL时多个索引语句之间有残留变量占位符

### ISSUE THREAD

**Issue by zhangjiankui** [cweijan/vscode-mysql#875]
- Operating system: MacOS 13
- Database type and version: PostgreSQL 15.3
如图：

<img width="594" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/26133797/8a9a9c0c-0a57-4503-beb8-f9006fc6c6f9">
<img width="308" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/26133797/6dea24b1-a96d-46c6-8a3a-06c07574d008">

**Comment by cweijan** [comment]
谢谢反馈, 我会在下版本修复.

**Comment by cweijan** [comment]
已在版本6.6.1修复
