### ISSUE TITLE
[BUG] PostgreSQL查看DDL时没有对关键词同名列名做双引号处理

### ISSUE THREAD

**Issue by zhangjiankui** [cweijan/vscode-mysql#876]
- Operating system: MacOS 13
- Database type and version: PostgreSQL

如图：

<img width="633" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/26133797/76b86bf2-3f68-4117-bcfd-20f61a928412">

pg_dump导出DDL时是能处理到的：

<img width="509" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/26133797/ca94d3d4-ecc2-46b6-9db0-c2398915e377">

诚然实践上是不应该使用和SQL关键词同名的列名，但是历史数据没办法

**Comment by cweijan** [comment]
已在版本6.6.1修复
