### ISSUE TITLE
Feature request: Influxdb2

### ISSUE THREAD

**Issue by dexin-peng** [cweijan/vscode-mysql#878]
`Influxdb2` 是一个开源时间序列数据库
请求加入 `Influxdb` 的第二个大版本 `Influxdb2` 的支持

**Comment by cweijan** [comment]
我去调研下是否要支持这种数据库, 短时间内不会支持.

**Comment by dexin-peng** [comment]
> 我去调研下是否要支持这种数据库, 短时间内不会支持.

好的，谢谢

**Comment by cweijan** [comment]
调研了下Influxdb, 这个通常是需要图形化展示的, 而且在8086端口开放了web UI, 不适合集成到这个扩展.

**Comment by dexin-peng** [comment]
好的 谢谢
这个数据库虽然是结构化的，但是跟其他结构化数据库区别极大，第三方支持会很困难
当时我调研的时候调研的不是很全面，在这里误开了个issue，抱歉

flux语法跟传统的关系型数据库差异极大，支持的话困难会很多，甚至它官方的vscode插件功能都没实现全，它的docker镜像按doc来操作bug也存在bug（rentention
policy相关的问题）
除了和服务端一同启动的web UI，目前支持influxdb2的第三方数据库客户端我只看到了dbeaver（ee/ue）一家
但是瑕不掩瑜，毫秒级订单数据（相比行式mysql及列式clickhouse）用这个读写实在是太快了，硬盘占用也低，甚至没用官方推荐的给时间序列打tag的方式就实现性能倍增了

以上，谢谢
