### ISSUE TITLE
[BUG] Password containing special characters makes import/export fail

### ISSUE THREAD

**Issue by StefanRickli** [cweijan/vscode-mysql#880]
- Operating system: Windows 11, WSL2 Ubuntu 22.04 LTS
- VS Code 1.80.1, connected to project inside WSL
- Database type and version: MariaDB inside WSL docker container (`mariadb:10.11`)

The password contains special characters. Upon data import or export, Database Client tries to run for example
`mysql -h MyIp -P MyPort -u MyUser -pPasswordContainsSpecialCharacters --default-character-set=utf8 DbName <'/path/to/file'`

This fails because the password leads to a bash syntax error. 

The correct usage would be
`mysql -h MyIp -P MyPort -u MyUser -p'PasswordContainsSpecialCharacters' --default-character-set=utf8 DbName <'/path/to/file'`

The problem is connected to all actions that call mysql on the command line, e.g. database dump, table import/export, etc.

**Comment by cweijan** [comment]
Please check the extension you installed is the latest (6.6.x), this issue was fixed long time ago.

**Comment by cweijan** [comment]
Sorry for not noticing that you said mariadb, I have released version 6.6.2 to fix it.

**Comment by StefanRickli** [comment]
Cool, thanks for fixing! Tested on a dump command and it works. ❤️
