### ISSUE TITLE
开启了自动分页后 select * 较大量级的数据仍然会卡死

### ISSUE THREAD

**Issue by bbuuhhoott** [cweijan/vscode-mysql#881]
这几天用vscode发现这个神仙插件，太好用太爽了/(ㄒoㄒ)/~~
数分一枚，在工作场景中比较多的涉及到一定体量数据的查询，目前查询结果数据量大于10w基本上就无响应了，内存和cpu占用很低，开启自动分页也一样卡死。
同样的场景 navicat能展现全部数据直到内存用尽，datagrip会默认自动分页不写limit也不会卡死。
不知道这个小点能不能优化下

**Comment by cweijan** [comment]
这个没办法哦, 扩展的视图是web, 大数据量的情况下必然会卡.. 一般查询结果是用来看的, 你查10w也看不过来啊.

**Comment by bbuuhhoott** [comment]
> 这个没办法哦, 扩展的视图是web, 大数据量的情况下必然会卡.. 一般查询结果是用来看的, 你查10w也看不过来啊.

好的明白了。主要是想偷个懒省一个写limit的步骤，看了是我习惯太差了😂。谢谢回复~

**Comment by cweijan** [comment]
现在自动分页对你的查询不生效吗, 自动分页就是自动加上limit

**Comment by bbuuhhoott** [comment]
> 现在自动分页对你的查询不生效吗, 自动分页就是自动加上limit

目前的自动分页功能失效了，我select *的话 第一页会展示全部数据，这也是卡死的原因

**Comment by cweijan** [comment]
你查一下数据量少的表, 拉升结果后看显示的SQL有没有limit, 不知道为什么自动分页没生效.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/12795233-1d78-47a1-aa74-1183dbd1c893)
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/6f2c8f26-3439-4822-a559-63f5605095ff)

**Comment by bbuuhhoott** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/50479549/ffeb3e82-1aae-46d1-967a-a1317aec2282)
自动分页没有起效，我开启自动分页查一个3W行的表，他第一页就展现了全部数据

**Comment by cweijan** [comment]
我知道了, 可能你是选择了SQL执行, 你手动选择SQL是不会自动分页的, 通过ctrl+enter快捷键或者codelen才会自动分页.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/a3a8c504-c5ec-47b3-8e3c-8c57f82ff956)

**Comment by bbuuhhoott** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/50479549/3337706f-6a8d-492a-9b4d-a93f7f2b431f)

我是通过ctrl+enter执行的，目前在Query里面执行的sql都不会走自动分页，只有点进Full Result View执行sql才会走自动分页

**Comment by bbuuhhoott** [comment]
哦 明白了，现在在query页面用ctrl+enter会走分页，但是如果选择了sql在用ctrl+enter就不会走分页

**Comment by cweijan** [comment]
对, 按下ctrl+enter会自动检测当前的SQL, 不需要选择, 选择SQL不自动分页是特意做成这样的.
