### ISSUE TITLE
[BUG] Create or edit field in Mongo DB transforms ObjectId in string

### ISSUE THREAD

**Issue by rafaelzochling** [cweijan/vscode-mysql#882]
Hello,
I haven't found any issue open for that so I'm reporting because this can be of help. When using the interface instead of CLI to create a new row or even to edit one, whenever the field is an `ObjectId`, even when editing the query generated by the tool, it sends the information as a text field, like in the example  of the screen shot:

![image](https://github.com/cweijan/vscode-database-client/assets/40503886/e9d6846b-3cc5-4946-ae64-5df7add76013)

Also, a small detail but it's using `ObjectID` with capital `D` instead of `ObjectId`

- Operating system: MacOs Ventura 13.4.1
- Database type and version:MongoDB server version: 4.4.5

Thanks!

**Comment by cweijan** [comment]
Thanks for the feedback, I'll try to fix it in a future version.

**Comment by cweijan** [comment]
Fixed in version 6.6.1.
