### ISSUE TITLE
Raw output support

### ISSUE THREAD

**Issue by mercurykd** [cweijan/vscode-mysql#883]
Add support raw data output in editor, for example after `select 1 \G`
Add support \G notation for mysql

**Comment by cweijan** [comment]
Hi, I have supported \G in version 6.6.5, which is not "raw data output" in mysql-cli, which will reverse the rows and columns of the data.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/b9d4a3fe-26af-42a0-8019-97fe7eaf5f4a)

**Comment by mercurykd** [comment]
<img src='https://github.com/cweijan/vscode-database-client/assets/30900414/6df31f82-8550-477b-95f4-b58d311db773' width="300">

hello, when trying to select from multiple tables, the values ​​are displayed as NULL

in fact, when creating an issue, I did not know about the "reverse button" option, it was more convenient than \G-notation, I'm sorry, is it possible to return it?

**Comment by cweijan** [comment]
Hi, I removed the reverse button because it makes the toolbar ugly when enabled, I will redesign it in a future release.
