### ISSUE TITLE
[BUG] Grouping table not work

### ISSUE THREAD

**Issue by boelchan** [cweijan/vscode-mysql#885]
- Operating system: Windows 10
- Database type and version: maria db

Grouping table not work.  since version 6.5.5 until 6.6.2
![image](https://github.com/cweijan/vscode-database-client/assets/38100527/10bdf280-dbbc-432f-9bd1-c2ac71a78770)

**Comment by cweijan** [comment]
Thanks for the feedback, I will fix it in the next version

**Comment by boelchan** [comment]
thanks for fixed
