### ISSUE TITLE
Shell Env Supports

### ISSUE THREAD

**Issue by dongyuanxin** [cweijan/vscode-mysql#886]
- 问题描述：是否支持设置环境变量（env vars）？
- 场景：公司内部在使用工具连接redis时，需要设定特殊的env

**Comment by cweijan** [comment]
设置变量和连接有什么关系?

**Comment by dongyuanxin** [comment]
> 设置变量和连接有什么关系?

走redis-cli命令行连接的话，通过export注入env特定变量后，比如`IS_INTERNAL_IP=1`，则可以连接到redis。
