### ISSUE TITLE
Support executing SQL snippets inside other programming language

### ISSUE THREAD

**Issue by ViliamKopecky** [cweijan/vscode-mysql#887]
I believe it should be possible to show Execute button when SQL code is inside another file / another syntax. Sometimes we have SQL snippets in TypeScript code like this and it would be great to have Execute button there.

```ts
const sql = /* sql */ `
SELECT * FROM foobar
`
```

**Comment by cweijan** [comment]
Sorry, this is not a high-frequency feature, and it will affect the performance of VSCode, I don't consider supporting it.

**Comment by ViliamKopecky** [comment]
Sure, thanks anyway. Good extension :)
