### ISSUE TITLE
Mongo response need JSON

### ISSUE THREAD

**Issue by melihkucuknazli** [cweijan/vscode-mysql#888]
MongoDB query response should be directly output JSON tree response.

Example (Stundio 3T Editor Response):
<img width="1256" alt="Ekran Resmi 2023-07-31 12 45 18" src="https://github.com/cweijan/vscode-database-client/assets/22034296/0fec5386-4b18-43dc-91fe-f69c438f8d04">

**Comment by cweijan** [comment]
Have you tried MongoDB [official extension](https://marketplace.visualstudio.com/items?itemName=mongodb.mongodb-vscode)? If you prefer JSON, it will be the best choice.

**Comment by melihkucuknazli** [comment]
But I want to use this plugin. In programs such as Datagrip and DBeaver, the data source has display options. For example Table, JSON, Text. I think it would be great if there was such an option in the plugin.

**Comment by cweijan** [comment]
Hi, I added the execution codelen that returns JSON in MongoDB js.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/2429e327-7876-411f-bfc6-58612ff5ea99)
