### ISSUE TITLE
Mock数据时可不可以增加跳过重复值的功能？

### ISSUE THREAD

**Issue by MarioYoo** [cweijan/vscode-mysql#889]
在对有唯一性的列(比如，手机号)进行Mock数据时，当有重复值时会导致整个Mock过程不会执行(数据表中没有生成任何数据)。
进行大量数据mock时会浪费时间。
能不能增加一个功能，可以选择在Mock数据时是否跳过重复值？

**Comment by cweijan** [comment]
谢谢反馈, 我会去修复这个问题.

**Comment by cweijan** [comment]
Hi, 试下版本6.6.8, 现在改为insert ignore, 应该是不会冲突了.
