### ISSUE TITLE
Name of connection in statusBar instead of ip

### ISSUE THREAD

**Issue by mercurykd** [cweijan/vscode-mysql#892]
![image](https://github.com/cweijan/vscode-database-client/assets/30900414/6964d2e7-f1bb-4365-9df7-7483f0706318)

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by mercurykd** [comment]
with display of the group if it exists (if possible)

**Comment by mercurykd** [comment]
> with display of the group if it exists (if possible)

<img src="https://github.com/cweijan/vscode-database-client/assets/30900414/05c9ef74-dae4-4ccf-b021-f1a108265d3b" width="300">
 
additional info in hover view, like ip, group and other

**Comment by cweijan** [comment]
Support in version 6.6.8.
