### ISSUE TITLE
Selection options for columns

### ISSUE THREAD

**Issue by mercurykd** [cweijan/vscode-mysql#893]
<img src="https://github.com/cweijan/vscode-database-client/assets/30900414/0bdac289-dad5-4963-9c97-42c2131610f4" width="300">

there are many columns and clicking each one is tiring
- add option 'select/unselect all'

**Comment by cweijan** [comment]
This sounds good, I will support it in a future.

**Comment by cweijan** [comment]
I have added a select all checkbox in version 6.7.0.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/1ceee8c9-7854-4941-a683-884a5d294ad3)
