### ISSUE TITLE
Export filtered table in sqldump format

### ISSUE THREAD

**Issue by mercurykd** [cweijan/vscode-mysql#894]
<img src="https://github.com/cweijan/vscode-database-client/assets/30900414/09019a4e-701b-4ad8-81a2-b64ffcef1328"  width="300">

Exporting a filtered table in sqldump format produces a dump with a different table name than the original table name. Is this a bug or is it meant to be?
![image](https://github.com/cweijan/vscode-database-client/assets/30900414/42008ca8-8efa-41bd-94e0-89424c45794d)

**Comment by cweijan** [comment]
Hi, this is intentional, using the dump mode will create a temporary table using the current SQL, which means that any SQL can be exported.
