### ISSUE TITLE
 ERR 'crypto.subtle' is not available so webviews will not work in  coder-server (vs code for web)

### ISSUE THREAD

**Issue by qq897425998** [cweijan/vscode-mysql#895]
- Operating system: coder-server (vs code for web)
- Database type and version: all version

 chrome console 's error info 
 ERR 'crypto.subtle' is not available so webviews will not work. This is likely because the editor is not running in a secure context (https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts).: Error: 'crypto.subtle' is not available so webviews will not work. This is likely because the editor is not running in a secure context (https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts).

**Comment by cweijan** [comment]
This is a limitation of VS Code, if you want to use this extension on the web, you must use https.
