### ISSUE TITLE
[BUG] Querying on a locked panel opens the result on another locked panel. 

### ISSUE THREAD

**Issue by juliuscanoy** [cweijan/vscode-mysql#896]
Steps to reproduce:
1. Open DB Connection using MySQL and use SSH Tunnel
2. Click some tables and lock each panel.
3. Re-run the query in one of the locked panels.
4. Locked Panel that you rerun will be stuck and open the results to another locked panel.

![image](https://github.com/cweijan/vscode-database-client/assets/88019754/19766916-0809-48f6-92fd-ccff6be22c41)
![image](https://github.com/cweijan/vscode-database-client/assets/88019754/213a7436-be55-4b8e-9694-725445ec5a54)

- Operating system: Windows 11
- Database type and version: MySQL 8

**Comment by cweijan** [comment]
Thanks for feedback, I will fix this in the next version.

**Comment by GautamMakadia** [comment]
it's also happening  with normal localhost mysql connection.

Steps To Reproduce(After Creating Connection to localhost:3306):
1. Open Table-A  by clicking on it.  
>![1](https://github.com/cweijan/vscode-database-client/assets/69979317/095334a8-bd3e-4de6-93fe-098c1aa3ceea)

2. Then open another Table-B using " open in new panel".
3.  It will open another " Result " tab stuck with loading of Table-B and opens Table-B in previously open tab of Table-A. (Table-B replaces Table-A instead of opening in new Tab.)

> ![2](https://github.com/cweijan/vscode-database-client/assets/69979317/c57f8e72-a86e-4743-8130-b4339cbdd2f9)

**Comment by roa-sh** [comment]
> it's also happening with normal localhost mysql connection.
> 
> Steps To Reproduce(After Creating Connection to localhost:3306):
> 
> 1. Open Table-A  by clicking on it.
> 
> > ![1](https://user-images.githubusercontent.com/69979317/259326974-095334a8-bd3e-4de6-93fe-098c1aa3ceea.png)
> 
> 2. Then open another Table-B using " open in new panel".
> 3. It will open another " Result " tab stuck with loading of Table-B and opens Table-B in previously open tab of Table-A. (Table-B replaces Table-A instead of opening in new Tab.)
> 
> > ![2](https://user-images.githubusercontent.com/69979317/259326987-c57f8e72-a86e-4743-8130-b4339cbdd2f9.png)

Getting the same behavior since like a week ago (Maybe 5 days). Thanks in advance for any fix.

**Comment by cweijan** [comment]
I have released version 6.6.9 to fix it, please check if it works.

**Comment by juliuscanoy** [comment]
@cweijan  Confirmed working. Thanks!!
![image](https://github.com/cweijan/vscode-database-client/assets/88019754/042a9ee1-e6ba-47fb-8829-44e67ece8e7b)

**Comment by roa-sh** [comment]
Awesome @cweijan thanks!
