### ISSUE TITLE
[BUG] Is possible to drop columns on Read Only mode 

### ISSUE THREAD

**Issue by JoseDelPino** [cweijan/vscode-mysql#898]
- Operating system: macOS Ventura 13.5
- Database type and version: PostgreSQL 13.3

On Read Only connection you can't insert or update rows but you can drop columns which I think is a potentially dangerous behaviour

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed in verison 6.7.0.
