### ISSUE TITLE
[BUG] Cannot set properties of undefined (setting 'type')

### ISSUE THREAD

**Issue by jazzroutine** [cweijan/vscode-mysql#900]
- Operating system: Windows 11
- Database type and version: N/A

SSH Client v6.6.8

I'm unable to edit old connections(any type). Getting `Cannot set properties of undefined (setting 'type')` in Output console. 

No problem with fresh connections. Old ones are usable, but not editable. 
![image](https://github.com/cweijan/vscode-database-client/assets/187896/ac51a957-1ee6-4340-abb2-ec49e293c085)

**Comment by cweijan** [comment]
Thanks feedback, I will fix it in next version.

**Comment by cweijan** [comment]
Hi, try version 6.6.9, this version should be able to edit normally.

**Comment by jazzroutine** [comment]
Super! Everything is working just fine. Thank you!
