### ISSUE TITLE
Paste inside SSH connection

### ISSUE THREAD

**Issue by jazzroutine** [cweijan/vscode-mysql#902]
When inside SSH connection and not in vim editor – paste function works very strange.
It breaks the lines etc. 
 
As I can understand, it's made for vim only, but I usually use other editors. 

Is it possible to change that behavior? To return to normal paste? 

Example:
plain text file:
![4](https://github.com/cweijan/vscode-database-client/assets/187896/66452484-eb4a-45d1-9127-707b4e9bb644)

I want to add 6 string in the middle of it:
![3](https://github.com/cweijan/vscode-database-client/assets/187896/46f5dad4-3183-49ca-a1c9-c7af5f868238)

What I expect:
![2](https://github.com/cweijan/vscode-database-client/assets/187896/f096f475-dd11-4344-8df5-e3fda525d348)

What I get after real pasting:
![1](https://github.com/cweijan/vscode-database-client/assets/187896/a24a7521-a5b8-43f1-98b9-3261dba30b92)

Please help. 
I really like this extension, but I really tired to copy and paste one line at a tine.

**Comment by cweijan** [comment]
This is indeed a strange problem, I will try to fix it.

**Comment by jazzroutine** [comment]
I think it's try to paste like in VIM style, because in VIM everything works fine. 
Maybe it's possible to add some switch in settings or in the top bar to use VIM paste method, or standard paste method? 

Additional info: after paste in NANO, it's try to justify whole paragraph of the document. In NANO it's "^J" command. Maybe it will help. 
![image](https://github.com/cweijan/vscode-database-client/assets/187896/def1141a-e931-4af9-9fb9-49174730d4fe)

**Comment by cweijan** [comment]
Even with nano, I can get normal paste results, I don't know how this happens, maybe your nano editor automatically adds blank lines for you.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/4e153eb4-4b89-4737-9d45-04daf2ef1812)

**Comment by jazzroutine** [comment]
hmm, it's not server related. I've got the same issue at any server I have. 
Maybe something inside VScode settings? 
Thank you for testing, I will try to google it and double check the VScode settings

**Comment by jazzroutine** [comment]
After some testing I was able to find what if I use CTRL+V - everything is fine.
If I use right mouse button, got the issue from screenshot above. 

How did you paste during your test?

**Comment by cweijan** [comment]
Hi, I used ctrl+v and shift+insert to test before, if I use the right button to paste, the situation you said will indeed appear, thank you for your feedback, I will fix it in the next version..

**Comment by jazzroutine** [comment]
Thank you! If I can help you somehow, please let me know.

**Comment by cweijan** [comment]
Fixed in verison 6.7.0.

**Comment by jazzroutine** [comment]
Everything is working fine! 
Thank you so much!!!
