### ISSUE TITLE
It is recommended that the connection name be displayed in the open query instead of the connecting host

### ISSUE THREAD

**Issue by my57575757** [cweijan/vscode-mysql#903]
It is recommended that the connection name be displayed in the open query instead of the connecting host
![image](https://github.com/cweijan/vscode-database-client/assets/60951130/460af914-9c0a-4729-af65-632a8f14c3ab)

**Comment by cweijan** [comment]
This mark is used to identify the connection and cannot be changed. I plan to display the connection name on the right side of the mark in the next version.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/6e20b4a8-6bfa-4abe-b306-2dce51929ab1)

**Comment by my57575757** [comment]
Thank you and look forward to your next release

**Comment by cweijan** [comment]
Sorry, the right side of the mark is also not acceptable, if the text is dynamic, it will cause performance problems, please use the status bar to view the current connection name.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/83d94496-de1a-4aaa-8dfe-9702a0fcbbff)

**Comment by my57575757** [comment]
ok,i had found it
