### ISSUE TITLE
[BUG] Inconsistence pagination

### ISSUE THREAD

**Issue by kdiogenes** [cweijan/vscode-mysql#906]
- Operating system: Linux 6.1.44-1-MANJARO SMP PREEMPT_DYNAMIC x86_64 GNU/Linux
- Database type and version: Postgres 15.1

I run some queries that fetch the results according to the option "Default Select Limit"; after this, the result is paginated, but some queries never get paginated and the "Default Select Limit" must be tweaked to fetch all the rows.

I found this inconsistency annoying. Is there a way to know when one behavior or the other will be used? Is there anything that can be done to make it always use pagination?

**Comment by cweijan** [comment]
If you select SQL manually, then pagination will not work, it only applies to automatically recognized SQL.

**Comment by kdiogenes** [comment]
This didn't make a difference to me. The queries that get paginated are still paginated when selected. I also double-checked that I wasn't selecting the queries that aren't being paginated. I will try to generate a minimum database that reproduces this.

**Comment by cweijan** [comment]
I think you are used to select SQL first, and then execute it, so this problem is caused (this extension recommends that you use ctrl+enter to execute directly, without select). This is really confusing, I will make them consistent in the next version.

**Comment by kdiogenes** [comment]
No, I never select the SQL that I want to execute. I was used with dbeaver, which separates SQLs by an empty new line and also doesn't need you to select the SQL. While using your extensions, in the beginning, I get used to adding `;` to the end of the SQL, so the editor can properly handle the SQL separation and I also don't need to select the SQL.

I love the feature of not having to select the SQL to execute it.

**Comment by cweijan** [comment]
What SQL did you execute and the pagination failed, can you give an example?

**Comment by cweijan** [comment]
I have removed the judgment logic in version 6.7.0, now it will always pagination.
