### ISSUE TITLE
Cannot update changes in python functions back to postgres server

### ISSUE THREAD

**Issue by laosanlyu** [cweijan/vscode-mysql#907]
I tried to edit the python function/stored procedure with this extension in vscode, but I cannot save the changes back to postgre server. when I refresh the connection, all the changes made in vscode are gone 

so do I set up the configuration or this extension doesn't have this feature(edit functions/stored procedure) currently?

**Comment by cweijan** [comment]
The extension does not automatically save stored procedures/functions, please execute drop first, and then re-execute create.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/a7007a45-433a-4eac-929f-2b4eb021d1c9)

**Comment by laosanlyu** [comment]
> 

Thanks, It's working now
