### ISSUE TITLE
Minify JSON button in the Edit Data dialog

### ISSUE THREAD

**Issue by SaifAqqad** [cweijan/vscode-mysql#910]
Would be really handy to have a button in the Edit Data dialog to Minfy the JSON, so we can format -> edit -> minify and save
![image](https://github.com/cweijan/vscode-database-client/assets/47293197/ae0b5ca7-24e1-4cc7-8628-ddab2e9930a9)

**Comment by cweijan** [comment]
This is unnecessary, if you use the JSON type, the newline characters will not be preserved after you save.
