### ISSUE TITLE
Automatically call related row on click on relation

### ISSUE THREAD

**Issue by Giuliano1993** [cweijan/vscode-mysql#912]
When clicking on a value on a column that contains a foreign key, that would be nice to have the possibility to directly run the query and find that row. 
I haven't seen this feature, maybe I'm missing it; Otherwise I'd be happy to help with that, if you think that this is a nice feature to have

**Comment by cweijan** [comment]
That sounds good, I'll try to implement it in the future.

**Comment by oliverflyttsmart** [comment]
This sounds great, kinda like how prisma studio works.

**Comment by IShungite** [comment]
+1

**Comment by cweijan** [comment]
Supported in version 7.3.3.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/5a8443a1-d33d-4390-8efe-d586a96fd164)
