### ISSUE TITLE
Сolumn selection is saved in the query

### ISSUE THREAD

**Issue by mercurykd** [cweijan/vscode-mysql#913]
<img src="https://github.com/cweijan/vscode-database-client/assets/30900414/0154dafc-7923-432d-9f9c-629c7c8d565a" width="300">

Now when you update the filter, the column selection is reset. Need to reselect columns

**Comment by cweijan** [comment]
Thanks for feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed in version 6.7.1.
