### ISSUE TITLE
Possible to rotate results table 90 degrees? (swap rows/columns)

### ISSUE THREAD

**Issue by hi2u** [cweijan/vscode-mysql#914]
Some SQL clients like DBeaver + DataGrip have a key you can press to toggle the layout to show each row as a vertical column, instead of normal horizontal rows.

e.g. here's a thread about the feature in DBeaver :  https://github.com/dbeaver/dbeaver/issues/7014

Does this vscode extension have this feature?  I looked, but didn't find anything on the subject.

**Comment by cweijan** [comment]
Hi, you can reverse the data by adding \G after the SQL, and the next version will add a new tool button to support reverse data.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/269b0cfe-f8a3-47d4-9a06-139f1eaf1aa4)
