### ISSUE TITLE
[BUG] MS SQL rowversion type not displayed correctly

### ISSUE THREAD

**Issue by SaifAqqad** [cweijan/vscode-mysql#915]
The datatype [`rowversion`](https://learn.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql?view=sql-server-ver16) is an 8-byte number, while it is a synonym for the type `timestamp` in ms sql, it's not an actual timestamp, and should be displayed as a normal number (maybe in hex format)

database-client:
![image](https://github.com/cweijan/vscode-database-client/assets/47293197/8fe6ed6c-9ad1-4632-9fba-9c0e4c99e96f)

Azure Data Studio:
![image](https://github.com/cweijan/vscode-database-client/assets/47293197/0a5e084b-f11d-4119-8ad7-0215e5e52392)

- Operating system: Windows 10 22H2 (19045.3324)
- Database type and version: Azure SQL Database (MS SQL server v12.0.2000.8)

**Comment by cweijan** [comment]
Thanks for your feedback, I will try to be compatible with this type.

**Comment by SaifAqqad** [comment]
Thank you so much, works like a charm on v6.7.2
![image](https://github.com/cweijan/vscode-database-client/assets/47293197/475916e8-5aed-47c1-8350-a4158c428a3e)
