### ISSUE TITLE
[BUG] 一次删除多个表，如果存在外建，主表无法删除。

### ISSUE THREAD

**Issue by NingGelin** [cweijan/vscode-mysql#918]
- Operating system: macOS
- Database type and version: pg14 vs-code plugin version: v6.7.1

**Comment by NingGelin** [comment]
两个表循环引用就都删除不了了

**Comment by cweijan** [comment]
谢谢反馈,  我会在下版本支持删除有外键的表, 你现在可以先在设计表内删除外键.

**Comment by cweijan** [comment]
已在版本6.7.3支持.

**Comment by NingGelin** [comment]
好像还是不行哎。  drop table table_name CASCADE;  手动这么删可以删除 @cweijan

**Comment by cweijan** [comment]
我没注意你是pg, 这次是支持了MySQL😂, 我下版本支持下.

**Comment by NingGelin** [comment]
嗯嗯 好的 感谢
