### ISSUE TITLE
Allow external extensions to create connections

### ISSUE THREAD

**Issue by biati-digital** [cweijan/vscode-mysql#921]
Hi, I'm the developer behind a VSCode extension called [DDEV Manager](https://marketplace.visualstudio.com/items?itemName=biati.ddev-manager). DDEV is a Docker-based development environment, the extension already interacts with other extensions like PHP Intelephense or PHP by DEVSENSE but would love to be able to integrate your extension to make VSCode more like an IDE like PHP Storm, Web Storm, etc.

The user already can create a terminal that connects to the database container and also there's an action to launch a visual GUI database client that connects automatically to the database, this can be configured by the user (phpMyAdmin, Sequel Ace, Tableplus, etc.) What I want to accomplish is to be able to open the database with your extension automatically when the user clicks that action. This way the user does not need to rely on external apps or services.

I was wondering if there is a way for external extensions to create connections dynamically for example:

`vscode.commands.executeCommand('yourExtension.connectToDatabase', 'Connection Name', 'database', 'user', 'password', 'port');`

And if there's no option would you consider adding a way to make this possible? of course users would have the same limitations that comes with the free version or can pay if they require more connections, etc.

![image](https://github.com/cweijan/vscode-database-client/assets/1219228/6e014e3b-66ea-45c3-8195-2470a51222d9)

You have a great extension, hopefully we can work something out.

**Comment by cweijan** [comment]
Creating a connection requires complex options, and jumping from one tree view to another will only make things more complicated for the user, so I won't consider your proposal.
