### ISSUE TITLE
Access database explorer from editor

### ISSUE THREAD

**Issue by GTonehour** [cweijan/vscode-mysql#922]
Always impressed by your work on this extension !

Sorry if my question is naïve, but is there a way to access a specific table (or view) in the database explorer directly from the editor ?

For instance in other database administration tools (like DBeaver or SQL Developer), you can ctrl+click the table in the SQL editor to show it in the database explorer.

**Comment by cweijan** [comment]
Thank you for your feedback, I will try to support it in future versions.

**Comment by cweijan** [comment]
Hi, I have supported access in version 6.8.7. But can only access the nodes loaded in the database view.

**Comment by GTonehour** [comment]
Perfect, it seems to work fine. Thanks!
