### ISSUE TITLE
[BUG] "Execute" button above individual queries doesn't appear if there's a comment above with an unclosed quote

### ISSUE THREAD

**Issue by sam8457** [cweijan/vscode-mysql#923]
- Operating system:  Windows 11
- Database type and version: MySQL version 8.0.34

When writing several queries, I noticed the 'Execute' button that typically appears above each one doesn't show if there's an unclosed single or double quote in a comment before the query.

For example, here's what it normally looks like:
![image](https://github.com/cweijan/vscode-database-client/assets/64925821/408e170e-6de1-4e90-877f-735314782c3f)

And here's what it looks like with an unclosed quote:
![image](https://github.com/cweijan/vscode-database-client/assets/64925821/e8d2b547-112e-4651-8f8b-aa3dd54ad8a5)

But if you then close the quote again, it works:
![image](https://github.com/cweijan/vscode-database-client/assets/64925821/06b702ae-8e8c-43c1-b64f-15bfd1545c4e)

To replicate, open any database in VS code and select the 'Open Query' option under the 'Query' section. Write any query and put a comment above them that contains either an unclosed single quote `'` or double quote `"`.

Not a super high priority issue but just so you're aware.

**Comment by cweijan** [comment]
Thanks for feedback, this is because I don't support the "#" comment, I will support it in the future.

**Comment by cweijan** [comment]
Fixed in version 6.7.3.
