### ISSUE TITLE
Where can I find stored passwords?

### ISSUE THREAD

**Issue by ablaszkiewicz** [cweijan/vscode-mysql#924]
I am using this extension to connect to a database which rotates passwords every 20 minutes.
I have to manually input this password to connect to the database.

I want to automate it so the question is - where are connection details stored? Can I edit them externally (outside of vscode through some script)?

**Comment by cweijan** [comment]
For security reasons, the configuration does not exist as a file. It is saved in the extended context provided by vscode and you cannot operate it.

**Comment by ablaszkiewicz** [comment]
Is it something that could be changed in the future? I think this is a pretty popular case for people to have their dbs rotate passwords

**Comment by cweijan** [comment]
No, I wouldn't do that for security reasons, and most database clients I know don't store configuration in plain text.

**Comment by cweijan** [comment]
If you are a paid user, you can choose to save the configuration in the workspace, which will be a plain text file.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/b36a3747-63a5-47d3-ac7d-c4ae500d2751)

**Comment by ablaszkiewicz** [comment]
I am a paid user. Could you elaborate on this `Workspace` option? What does it do? Where would it be stored?

**Comment by cweijan** [comment]
The vscode folder you are currently opening.
