### ISSUE TITLE
[BUG] File download

### ISSUE THREAD

**Issue by cristianjcdigital** [cweijan/vscode-mysql#925]
Hello,

I have been migrating a wordpress and I download the files using the plugin. The problem is that it does NOT download the TOTAL of all files and folders (and internal files) in full.

It only seems to download the first level.
It is important to correct it because it seems that you have downloaded EVERYTHING and it turns out that it is not, so it produces errors that are difficult to notice until you don't dig into each folder.

Best regards,
Cristian.

Translated with www.DeepL.com/Translator (free version)

**Comment by cweijan** [comment]
What type of file service are you operating?

**Comment by cristianjcdigital** [comment]
All the files that a Wordpress has

**Comment by cweijan** [comment]
My extension only provides three file services: ftp, sftp, and s3, but not wordpress.

**Comment by cristianjcdigital** [comment]
We don't seem to understand each other.

What I mean is that when I have tried to download files, it does NOT download the TOTAL files if there is more than one level of folders.


In the screenshot you will see that there are different files and folders. I mean it does not download the entire contents of the folders.


![Captura2](https://github.com/cweijan/vscode-database-client/assets/75582513/2818bd7f-e3f8-4224-9ef2-4cc7cd16243f)

**Comment by cweijan** [comment]
I understand you said you can't download, but I need to know what your current connection type.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/da56e0e4-7257-4850-870c-1bbb3459d6f8)

**Comment by cristianjcdigital** [comment]
FTP

**Comment by cweijan** [comment]
Fixed in version 6.7.3.
