### ISSUE TITLE
[BUG] fields original structure was change at the JSON fields update in elasticsearch client 

### ISSUE THREAD

**Issue by dm2box** [cweijan/vscode-mysql#926]
- Operating system: Server is elasticsearch docker image 
- Database type and version:  8.4.0

![image](https://github.com/cweijan/vscode-database-client/assets/15945127/248af262-96ed-42b3-8a9e-63f1658c5976)

for the above image illustrate . the id:0 data is the original data example . the id:2 is  error data example when  kind of id:0 click edit data and click update  .

obvious the lables and digests field has changed ,  original type is JSON new type is String. is it bug?

**Comment by cweijan** [comment]
Sorry for this bug, I will fix it as soon as possible.

**Comment by cweijan** [comment]
Hi, what is the type displayed below your field? If it is object, the extension can handle it correctly.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/9f53dbc2-5226-474c-8176-25077dc5ed17)

**Comment by dm2box** [comment]
the lables type is keyword , because i need this column use for exact matching . other digests column is text.

![image](https://github.com/cweijan/vscode-database-client/assets/15945127/f405e624-f8b1-4e2d-80ca-5244696ca882)

**Comment by cweijan** [comment]
What is your es version? In my test, if the field type is keyword, the field cannot save the object value.

**Comment by dm2box** [comment]
version is 8.4.  i use the spring es repository and the restful service process  data save ,  it submit the http request illustrate is  below 


------------------


23-10-2023 23:30:00.867 [http-nio-18010-exec-5] TRACE o.s.data.elasticsearch.client.WIRE.logRequest - [25ee1dd7] Sending request
PUT /skill/_doc/3?refresh=false
Parameters: 
Headers: [User-Agent: elastic-java/7.17.9 (Java/17.0.8.1), Accept: application/vnd.elasticsearch+json; compatible-with=7, X-SpringDataElasticsearch-Client: imperative, X-Elastic-Client-Meta: es=7.17.9,jv=17,hl=2,t=7.17.9,hc=4.1.5,kt=1.6, Authorization: *****, Content-Length: 344, Content-Type: application/vnd.elasticsearch+json; compatible-with=7, Host: localhost:9200, Connection: Keep-Alive]
Request body: {"_class":"org.gorilla.tp.ai.domain.SkillInfoDomain","title":"open order status query","lables":["生活服务","业务查询"],"digests":["当客户希望查询外卖订单状态时使用"],"instruction":"webView","instructionParam":{"url":"http://www.baidu.com"},"name":"takeOutOrderState","id":3,"i18n":{"zh":{"title":"外卖订单查询"}}}
23-10-2023 23:30:00.882 [I/O dispatcher 661] TRACE o.s.data.elasticsearch.client.WIRE.logRawResponse - [25ee1dd7] Received response: 200 OK

**Comment by cweijan** [comment]
Thanks for the addition, I will try this.

**Comment by cweijan** [comment]
I've released version 6.8.1 to fix it.

**Comment by dm2box** [comment]
good
