### ISSUE TITLE
[BUG] Trying to update a column called primary

### ISSUE THREAD

**Issue by jonnovaretti** [cweijan/vscode-mysql#927]
I have a table with the following script running in postgresql.

```
CREATE TABLE email_addresses(
    id SERIAL NOT NULL,
    employee_id bigint NOT NULL,
    value character varying NOT NULL,
    primary boolean
)
```

When I try to update the primary column to false or true, using the table mode view, I get:

_syntax error at or near "primary"_

- Operating system: MacOS
- Database type and version: Postgres 16

**Comment by cweijan** [comment]
I released version 6.7.3 and included primary in the keyword library. If you encounter other situations, consider setting up to escape all objects.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/6c41f347-a1a2-4386-99a2-94731a1fca7b)
