### ISSUE TITLE
Stange behaviors when change/delete rows when using SELECT * FROM table;

### ISSUE THREAD

**Issue by tuga49** [cweijan/vscode-mysql#928]
If you write a query in a .sql file, for example "SELECT * FROM table;" and modify the data on the shown result, for example, when deleting a row, if I select and click on delete, the query that appears is "DELETE FROM "table" WHERE". It's not complete for some reason. If changing values instead of delete, it changes all rows because gives you a warning "no primary key found". In other hand, if instead of change values on the result of the query I ran ("SELECT * FROM table;"), if I double click the table to select the results and change there, then it works...

- Operating system: Windows 11 Pro 64-bit
- Database type and version: PostgreSQL 12.13, compiled by Visual C++ build 1914, 64-bit

**Comment by cweijan** [comment]
I don't understand what you mean. Does your table have a primary key? It's best to give me a screenshot so I can see the situation.

**Comment by tuga49** [comment]
Sure, look at this example:

1 - Run this query:
![image](https://github.com/cweijan/vscode-database-client/assets/17064445/a98144fa-8983-4f99-af5c-880400cb5efe)

2 - I get this output:
![image](https://github.com/cweijan/vscode-database-client/assets/17064445/94d1bfde-c4ba-4b3d-b9ad-34cedee1c0c7)

3- Try to delete one row (here, look at the query that will run, it's incorrect):
![image](https://github.com/cweijan/vscode-database-client/assets/17064445/6e1c3e56-1c1d-49c5-9012-e092835a6827)

4 - After click confirm, i get this error:
![image](https://github.com/cweijan/vscode-database-client/assets/17064445/2eebfe5c-938a-466e-a437-0d34a5d96eaa)

Here is my table:
![image](https://github.com/cweijan/vscode-database-client/assets/17064445/53a2987e-af41-4fea-b24e-b018e5019667)

Hope it helps, thanks

**Comment by cweijan** [comment]
Thanks for the feedback, this is indeed strange, I will try to find out the reason.

**Comment by cweijan** [comment]
Hi, I think it's because you executed the SQL query before the database view was loaded. I fixed it in version 6.8.7, please try it.
