### ISSUE TITLE
How to not treat empty lines as query separators

### ISSUE THREAD

**Issue by hi2u** [cweijan/vscode-mysql#930]
If a query has some empty lines in it, e.g lines 2, 8, 10, 12, 16:

![image](https://github.com/cweijan/vscode-database-client/assets/9689599/28b2bf8f-9965-4f54-8e09-91719eba1f43)

...then this extension seems to treat the blocks separated by empty lines as totally separate SQL queries. 

If I put my cursor on line 1 in the screenshot, and hit ctrl-enter (without any text selected), then it simply executes query:

    SELECT;

...and ignores everything below.  

Also note all the other `> Execute` buttons there below each empty line.  It thinks I have 6 separate queries, when I only have one.

How can I make the plugin just work like normal SQL queries, and include everything below as part of the query until it finds a `;` to mark the end of the query?

I had a look through the settings and github issues here, but couldn't find anything on the topic.

**Comment by cweijan** [comment]
I released version 6.7.3, which supports disabling SQL splitting by two newlines.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/fa205579-0d3b-4172-b745-614809bd2cea)

**Comment by hi2u** [comment]
Awesome, thanks!
