### ISSUE TITLE
change open terminal command?

### ISSUE THREAD

**Issue by Gaebuh** [cweijan/vscode-mysql#931]
I only use local mysql for school and the open terminal button on the database isn't running the command in my MySQL bin so powershell just says command not found. is there a way to change the directory it tries to run the command in? and can I add a ./ to the command?
![image](https://github.com/cweijan/vscode-database-client/assets/77945882/a802e9dd-0707-4fe3-9ab7-3ae7c5ceab72)

**Comment by cweijan** [comment]
After you add the MySQL bin directory to the environment variable, the mysql command can be used normally.
