### ISSUE TITLE
Foreign Table Support

### ISSUE THREAD

**Issue by vld-sys** [cweijan/vscode-mysql#932]
Hello,

I appreciate this tool.

Ideally, it would be nice to make the following improvements in Postgres:

1. Group foreign tables in the tree as a separate folder, such as "Functions":
   Foreign Tables
            -> Tables 
                   -> Columns 
                   -> Indexes

2. Organize all partition tables under a parent table in a "Partitions" folder:
   Table 
       -> Partitions
               ............
Thank you

**Comment by cweijan** [comment]
Thanks feedback, I will try to support it in the future.

**Comment by cweijan** [comment]
Hi, the new version already supports displaying foreign tables. You need to enable configuration in the console. Partitions will be supported in the future.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/41dcd936-4917-4906-adf1-75e9b799375a)

**Comment by cweijan** [comment]
After version 7.3.2, foreign table can be enabled on the connection page.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/86db84a1-edb0-4596-8516-35c053359d94)
