### ISSUE TITLE
Error position in SQL query

### ISSUE THREAD

**Issue by GTonehour** [cweijan/vscode-mysql#934]
When SQL query is wrong and execution fails, you correctly display the error (for instance `column "e" of relation "mvt" does not exist`).
![image](https://github.com/cweijan/vscode-database-client/assets/86954612/ac9bec50-2baa-4cd6-8c65-59b61a58a9ef)

But some SQL clients also give at the position where the error was. For instance, DBeaver moves the cursor to the "error position".
![image](https://github.com/cweijan/vscode-database-client/assets/86954612/9bf9d90e-bf7a-4066-8879-106ffb62fe75)

Do you think it would be feasible ?

- v6.7.4
- PostgreSQL 15
- DBeaver 23.1

**Comment by cweijan** [comment]
This impossible, the node-pg extension used does not return the position of the error.
