### ISSUE TITLE
[BUG] :parameters are not replaced, when a query is selected

### ISSUE THREAD

**Issue by PatrickJahner** [cweijan/vscode-mysql#936]
- Operating system: Windows 10
- Database type and version: postgresql 14.9

When I Run a File with a query, for each paramter with a colon ":" a promt is opened, asking me for the value of that parameter. I Love that!

When I mark a query and run the selected the query, it tries to run the query directly without the promt, and if the query contains colon-parameters i get a syntax error because the :parameters are not replaced.

**Comment by cweijan** [comment]
Fixed in version 6.7.5.
