### ISSUE TITLE
[BUG] Cannot connect to any DB

### ISSUE THREAD

**Issue by HamedOsama** [cweijan/vscode-mysql#939]
- Operating system: Windows
- Database type and version: any

### The extension telling me that I have reached the max connections which are 3 DB connections but I have zero connections.
**How can I solve this**

![image](https://github.com/cweijan/vscode-database-client/assets/77761661/0243e792-ea21-46d0-b815-cda2929538c1)

**Comment by cweijan** [comment]
I think you created a NOSQL connection before, please find the NoSQL panel.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/30ead7e1-1d24-4ef8-bfe9-132f643fc6c6)
