### ISSUE TITLE
Support entire table dump in export data function

### ISSUE THREAD

**Issue by cdong8812** [cweijan/vscode-mysql#940]
Hi I use the export data feature a lot and like it very much, however this feature won't be useful at all when you work with a large table due to the limit on the number of results shown on one page from select, it's also impossible to export data from each page one by one, it'd be great to just add a simple checkbox to dump entire table ignoring the limit and still support all different formats

**Comment by cweijan** [comment]
You can export all data by checking below checkbox.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/5ac9681b-4c23-42ef-a290-9dbd02e56535)

**Comment by cdong8812** [comment]
@cweijan thank you just tried it works will close this issue
