### ISSUE TITLE
[BUG] Editing column ignores primary key

### ISSUE THREAD

**Issue by AnaraLLC** [cweijan/vscode-mysql#941]
Selected a single record from a table by id,

```sql
select * from user_profile_table
where id = 123456
```

edited a single column called display_name, clicked save
Record primary key was ignored and all record `display_name` were updated to the edited name

- Operating system:
Mac Os Senoma

- Database type and version:
postrgres version 11.19

**Comment by cweijan** [comment]
Hi, does the ID column have the following red mark?

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/4745f9d3-5980-4f81-9824-84f2a2610766)

**Comment by AnaraLLC** [comment]
No it does not

**Comment by cweijan** [comment]
I think it is because the column was not loaded successfully. Sorry for causing trouble to you, I will take security precautions against in the next version.

**Comment by cweijan** [comment]
Have you disabled the configuration "Fetch columns when open table"? This configuration is used to control whether to load columns.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/196bc63f-d586-460c-81b5-e38ea7b0d808)

And whether this pop-up window appears when you save, which is used to prompt updates that may affect the data. I think the prompt is not written clearly enough.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/50ff7d1f-ac5b-4471-b9fd-6aced044f846)

**Comment by AnaraLLC** [comment]
No I haven't disabled  "Fetch columns when open table"?

what's interesting is a co-worker installed the extension and loaded the same table, the primary keys were loaded just fine and the query worked properly for him. Even after his test when I load it, the keys aren't loaded....

I did see the popup but it wasn't clear enough for me to not click ok, Maybe make it more alerting

e.g.

"STOP!!!! No primary Key Found, this change might affect more records than expected. Are you SURE you want to save this modification? Have you taken a recent backup?"

**Comment by cweijan** [comment]
Hi, try version 6.7.9, I have enhanced SQL parsing capabilities.

**Comment by cweijan** [comment]
Hi, I think it's because you executed the SQL query before the database view was loaded. I fixed it in version 6.8.7, please try it.

**Comment by attila-kun** [comment]
I'm still seeing this happening on v6.9.0 but I have a workaround:
1. In the database browser on the left hand side, right click on your DB and click "Close Connection".
<img width="318" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/1922756/839e286d-1644-48fc-8bd0-2d0e33ff43d9">

2. Open a new query tab for the DB. Now it should work.

I agree with @AnaraLLC that the error message should be more clear. I've accidentally updated all the rows in my prod DB. It was luckily recoverable, but I didn't expect this outcome.

**Comment by cweijan** [comment]
Thanks for the feedback, I will enhance the tips in the next version.
