### ISSUE TITLE
[BUG] Failed to import CSV data

### ISSUE THREAD

**Issue by NaheemAdio** [cweijan/vscode-mysql#942]
I just bought the premium version. I'm trying to import a CSV file into a table and I'm now getting this error message.

>  Error: Cannot insert explicit value for identity column in table [tableName] when IDENTITY_INSERT is set to OFF

I set the INDENTITY_INSERT to ON and I'm still getting the issue. Do you know what might be the issue here? Or how best should I format my CSV file? Thanks!

- Operating system: MacOS
- Database type and version: SQL Server 2019 Express

**Comment by cweijan** [comment]
Thanks for the feedback, I have released version 6.7.5 to support importing data with primary keys.
