### ISSUE TITLE
[BUG] The checkbox for unsigned cannot be deselected once it has been selected.

### ISSUE THREAD

**Issue by lvjiaxuan** [cweijan/vscode-mysql#943]
The checkbox for unsigned cannot be deselected once it has been selected.

I want to send a pull request, but I am unable to find the code on the main branch. How can I contribute to your repository?

![image](https://github.com/cweijan/vscode-database-client/assets/11309921/8f5566c3-61e0-46ad-84b0-3eaa59c04bd7)

![image](https://github.com/cweijan/vscode-database-client/assets/11309921/33d7adf1-5571-427a-a34c-f5192dc3b61d)

- Operating system:win10
- Database type and version: mysql8.x

**Comment by cweijan** [comment]
Thank you for your feedback. I will fix it in the next version. The latest version of the extension has been closed source.

**Comment by cweijan** [comment]
Fixed in version 6.7.5.
