### ISSUE TITLE
[BUG] Weird font in docker terminal

### ISSUE THREAD

**Issue by mieczkowski** [cweijan/vscode-mysql#944]
When I click `Open Terminal` in docker containers list (on remote machine) I get weird font :

![image](https://github.com/cweijan/vscode-database-client/assets/3045505/7b6dd1d0-04a9-4d6f-993d-9198068daa08)

Is there any config value that I could change to set different font?

System: macos

To compare: font in terminal in vscode:

![image](https://github.com/cweijan/vscode-database-client/assets/3045505/36c5049f-51d1-4ef1-85e9-bb90c0cea0a7)

**Comment by cweijan** [comment]
Hi, now extended fonts read fonts in the following order:
1. terminal.integrated.fontFamily
2. editor.fontFamily

**Comment by mieczkowski** [comment]
Well, in terminal font DejaVuSansMono Nerd Font looks good, and in docker terminal looks ugly:

![image](https://github.com/cweijan/vscode-database-client/assets/3045505/d80eead8-a14b-44e8-87d1-047bb6968ad6)

With default terminal font it looks ok, but I would still use custom font.

![image](https://github.com/cweijan/vscode-database-client/assets/3045505/cff0cd41-842d-4fa0-b4cf-53aff7b8987f)

Any idea why it happens?

**Comment by cweijan** [comment]
It seems that the font you use "DejaVuSansMono Nerd Font" cannot be recognized in webview. I will make it compatible with this situation in the next version.

**Comment by mieczkowski** [comment]
Thank you :-) 

Btw one of the best plugins for vscode!

**Comment by cweijan** [comment]
Fixed in version 6.7.8.

**Comment by mieczkowski** [comment]
@cweijan  unfortunately in version 6.7.9 font is still ugly :-(

![image](https://github.com/cweijan/vscode-database-client/assets/3045505/f16d42af-0d99-404d-97f7-7d85b5376028)

**Comment by cweijan** [comment]
I'm sorry that I missed a part, I will release a new version as soon as possible to fix it.

**Comment by cweijan** [comment]
Fixed in version 6.8.0.

**Comment by mieczkowski** [comment]
Looks better now, thank you :-)
