### ISSUE TITLE
[BUG]开启插件后，导致路径穿越漏洞

### ISSUE THREAD

**Issue by WSure00** [cweijan/vscode-mysql#945]
- Operating system: ubuntu 20.04
- Database type and version:  mysql v6.7.7
安装插件之后，每次运行vscode。会自动监听8828等端口(*:8828)。存在路径穿越的漏洞
实测通过使用`curl "http://xx.xxx.xxx.xx:8828/../../../../../../../../etc/passwd" --path-as-is` 命令可以拿到系统敏感数据。
这个漏洞等级还是很高危的，希望引起重视尽快处理，感谢。

**Comment by cweijan** [comment]
谢谢反馈, 我下版本限制下路径范围, 这个服务是用来防止VS Code缓存大量webview数据的.

**Comment by WSure00** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by WSure00** [comment]
> 谢谢反馈, 我下版本限制下路径范围, 这个服务是用来防止VS Code缓存大量webview数据的.

好的，辛苦啦

**Comment by cweijan** [comment]
已发布版本6.7.8修复.
