### ISSUE TITLE
[BUG]Oracle数据查询带视图（数据量大），导致崩溃。

### ISSUE THREAD

**Issue by mxtao12345** [cweijan/vscode-mysql#947]
- Operating system:
- Database type and version:
oracle数据库如果简单，单表查询可以正常使用，优先展示100条，但是当语句复杂化，就会卡死，而且貌似读取渲染了全部数据。
![image](https://github.com/cweijan/vscode-database-client/assets/137036616/3098b073-d401-4a3f-8036-0e5054045830)

**Comment by cweijan** [comment]
我去检查下分页是不是出问题了

**Comment by mxtao12345** [comment]
我刚又仔细验证了以下，是因为V_DM_HG_CJB_XS_DETAIL 这张表是一个明细视图，数据量较大，如果单查这个表没事，但是如果翻页查询第二页，就会卡死。

**Comment by mxtao12345** [comment]
> 我去检查下分页是不是出问题了

昨天有点晚了，我刚又验证了一下，应该如你所说是分页出了问题，如果只读这个视图表，初次加载可以，但是点击第二页就会继续卡死。

**Comment by kongdd** [comment]
我在用mariadb，也碰到了相似的问题。
对于比较大的数据库（5Gb作用），第一次打开很快，第二次打开会卡很久（2-3 mins）。

**Comment by mxtao12345** [comment]
我今天看了下这个分页的问题，就单表查询来看 如果sql写到一行，可以正确分页，但是如果分成多行，就无法正确分页，比如下图：
![image](https://github.com/cweijan/vscode-database-client/assets/137036616/f9a533e3-d0aa-439b-a143-b1b8caa3f12c)

**Comment by cweijan** [comment]
已发布版本6.7.8修复.
