### ISSUE TITLE
Can we use with cockroachdb

### ISSUE THREAD

**Issue by htphuocdl** [cweijan/vscode-mysql#950]
https://cockroachlabs.cloud/

`unknown function: pg_relation_size(): function undefined`

![image](https://github.com/cweijan/vscode-database-client/assets/13588794/d7851632-7419-4c95-8ac1-36ff06f85e77)

**Comment by cweijan** [comment]
Postgresql is currently not compatible with older versions, try using redshift to connect.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/44039d28-e95e-4509-b4da-47f361166315)

**Comment by htphuocdl** [comment]
it worked, thank you so much
