### ISSUE TITLE
[BUG] sqlite is not installed and install sqlite button not working

### ISSUE THREAD

**Issue by felipeapp** [cweijan/vscode-mysql#952]
When SQLite is selected, the extension shows the message "sqlite is not installed" and the button "Install Sqlite" does not work. The message disappears if I manually download sqlite3 and add it to the PATH environment variable.

- Operating system: Windows 11
- Database type and version: SQLite3

**Comment by cweijan** [comment]
When you click to install sqlite, the extension will start downloading sqlite3 from the link below. Can you try to see if you can access it normally?
https://dbclient-release.oss-cn-hongkong.aliyuncs.com/dbclient/sqlite3.exe

**Comment by felipeapp** [comment]
> When you click to install sqlite, the extension will start downloading sqlite3 from the link below. Can you try to see if you can access it normally? https://dbclient-release.oss-cn-hongkong.aliyuncs.com/dbclient/sqlite3.exe

Yes, I can download it from the link. Where does the extension save the sqlite file? As a workaround, will it work if I copy the file manually?

**Comment by cweijan** [comment]
After you click the download button, it will automatically disappear after the download is completed. Maybe the download was not successful due to network problems.

If you add sqlite3 to the environment variable, the extension will use the sqlite3 you configured. Will it work normally?

**Comment by felipeapp** [comment]
> After you click the download button, it will automatically disappear after the download is completed. Maybe the download was not successful due to network problems.
> 
> If you add sqlite3 to the environment variable, the extension will use the sqlite3 you configured. Will it work normally?

Yes, setting the environment variable works.

**Comment by TechQuery** [comment]
> Maybe the download was not successful due to network problems.

@cweijan This Axios-based extension failed to download SQLite (my GFW proxy was running), so I installed it manually and succeed. This may be help for @felipeapp:

```powershell
winget install SQLite.SQLite
```
