### ISSUE TITLE
Questions about storage of connections

### ISSUE THREAD

**Issue by jjnxpct** [cweijan/vscode-mysql#953]
I am new to this extension and have some basic questions: about how / where the connections are saved / used:

- Are the connection we created connected / linked / saved  to the project we have openend? I think not, I think they are 'global' in the sense that the connection can be opend from any project we are workin on? It would be nice to tie a connection to a project 9using the vscode folder?) so we only see / use that connection when we are working on that specific project. Would that be possible?

- I have two workplaces, so also two computers. Will the connections synced by the VScode 'Settings Sync'? That would be great. But I noticed  the 'Clous sync' option in the extension settings. How would I use this to sync my connections between multiple computers? Are the upload / download button 'sync' actions or wil upload override all items in the cloud and will download override all connecton on the computer? What would be the best way to keep two computers in sync?

**Comment by jjnxpct** [comment]
Well, I think I can answer my own first question: I have save a connection to the 'workspace' (not global) and I think now the connection is only visible / usabale when I op this project. The connection does not show up when I open a diufferent project (folder). So this would ean I can store a database connection to a specific project. If I am not right about this, please correct me ;-)

**Comment by cweijan** [comment]
Hi, workspace connection and cloud sync are supported, but they are paid features.

1. Workspace connection:
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/612a6669-b764-4fea-85a7-796b2b7311ee)

2. You can choose to merge the same configuration as before during cloud synchronization download, so there is no need to worry.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/6a8d70ad-836f-41ad-9538-862a03c43337)

**Comment by cweijan** [comment]
Yes, workspace connections are determined based on the root path.

**Comment by jjnxpct** [comment]
Thanks cweijan! I did pay for the extension so I can access the wokspace feature. Excellent! 

Also I will check out the cloud sync feature.  think the merge feuture will help.

So no information about the connection(s) is stored in the .vscode folder?

**Comment by jjnxpct** [comment]
Oh wait, I do see a file showing up there: database-client-config.json

**Comment by cweijan** [comment]
Yes.

**Comment by jjnxpct** [comment]
So I can also share this file between computers to have the connection on mulltiple PC's?

**Comment by cweijan** [comment]
Yes, but note that you must log in to a paid account for it to take effect.

**Comment by jjnxpct** [comment]
Can I use the same account for multiple PC ( I already have one) or do I need different accounts for different computers?
