### ISSUE TITLE
Press ctrl+enter  does not work well in SQLBook file [BUG]

### ISSUE THREAD

**Issue by Big-Dao** [cweijan/vscode-mysql#955]
- Operating system: windows 11
- Database type and version: MySQL 8.0.13

Open a SQLBook file, and press ctrl+enter on any SQL statement. It won't execute but popup "select kernel" window.

![image](https://github.com/cweijan/vscode-database-client/assets/35797992/cf6b9ac4-4009-498f-94c3-8e00465169d8)

**Comment by cweijan** [comment]
Please check whether the ctrl+enter shortcut key is occupied.

**Comment by Big-Dao** [comment]
I don't think that is why.
When I press Ctrl+Enter in a .SQL file created in query as following pic. The corresponding statement will execute.  
![image](https://github.com/cweijan/vscode-database-client/assets/35797992/2e2cfed8-7451-45eb-92cf-3f83b982c63e)

**Comment by cweijan** [comment]
The VS Code shortcut keys do not always behave the same in different file types. The shortcut keys not taking effect means that there is something else occupying the notebook's ctrl+enter shortcut key. This is not something I can handle.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/b22e436c-7ae4-45e2-9fd6-beff3e2131b8)
