### ISSUE TITLE
[BUG] Run two selected queries

### ISSUE THREAD

**Issue by GTonehour** [cweijan/vscode-mysql#956]
I select two queries, then I try to run them using ctrl+Enter. I expect the first query to run and then the second, but only the last one executes.

For instance here, `SELECT nextval('test_seq');` never executes :

![2023-10-24_18h44_37](https://github.com/cweijan/vscode-database-client/assets/86954612/5a979094-5be4-4b80-859f-f4e1b45fe6fc)

- v6.8.0
- PostgreSQL 15
- vscode 1.83.1

I'm tagging this as a bug, because I think it was working a few weeks ago.

**Comment by cweijan** [comment]
Thanks feedback, I've released the 6.8.1 fix.
