### ISSUE TITLE
Code Completion with schema for Stored Functions

### ISSUE THREAD

**Issue by PatrickJahner** [cweijan/vscode-mysql#958]
Right now, code completion only works with tables and views.

When i enter a schema-name, the stored functions of the schema are not in autocomplete.

e.G.:
-- Active: 1695804856484@@my_db_server@5432@my_db_name@public
now code completion will show all Functions in schema "public"

but when i type the schema name "global." code completion will not show me the stored functions i have stored in the "global" schema. There is no way for me to access them without changing the connections default schema.

**Comment by cweijan** [comment]
Thanks feedback, I will support it in the next version.

**Comment by cweijan** [comment]
Supported in version 6.8.4.
