### ISSUE TITLE
变量占位符可以加引号吗

### ISSUE THREAD

**Issue by wonb168** [cweijan/vscode-mysql#959]
比如日期变量的查询
`select * from tb where dt='${dt}'`
这样不支持，不会替换变量，只支持不带单引号的dt={dt}, 传参时把单引号也带进去，如'2023-02-02'
但上面带单引号的方式跟python中的变量替换是一致的，经常要在python和sql两种环境下运行命令，前者sql不能做任何改动，
请问，有办法支持吗？

**Comment by cweijan** [comment]
谢谢反馈, 我会在下版本处理

**Comment by cweijan** [comment]
抱歉, 字符串的解析优先级是高于变量的, 这个需求不会得到支持.

**Comment by wonb168** [comment]
如果字符串中有${}它就是变量啊，dbeaver数据库客户端就是这样，但它每段sql不会自动分段且没有前面的执行按钮，执行起来复杂，不如你这个方便，两个同时在用，来回替换这里的变量表达方式，很不方便

**Comment by cweijan** [comment]
因为我实现了SQL解析器, 才能够进行分段, 支持字符串内变量会对解析器造成干扰, 没办法.

**Comment by wonb168** [comment]
就差这个点，不然就可以全面取代掉dbeaver了
