### ISSUE TITLE
[BUG] Do not add backticks (`) for table and column name

### ISSUE THREAD

**Issue by Aminadav** [cweijan/vscode-mysql#960]
I'm a paid user, when I autocomplete and press tab, it's adding:
```
`
```
It's making issues when copy code to JavaScript.
<img width="283" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/3584317/cd8e10f2-60bb-41ed-baad-2aee329b6472">

Please remove the backtick if not needed or adding this configurable by settings.

**Comment by cweijan** [comment]
Please check if you checked "Escaped all object name".


![image](https://github.com/cweijan/vscode-database-client/assets/27798227/4e573141-c52d-4b3d-bd94-8d4fa25ada92)

**Comment by Aminadav** [comment]
I changed it in the vscode settings ui to "never" and now it's works.
