### ISSUE TITLE
希望增加对duckdb的支持

### ISSUE THREAD

**Issue by coloraven** [cweijan/vscode-mysql#961]
如题

**Comment by cweijan** [comment]
Hi, 在6.8.3版本支持了DuckDB, 你试试看.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/9ea42c32-88e9-4e9c-89f7-eb67db44be57)

**Comment by coloraven** [comment]
辛苦辛苦，这么快就支持了，我刚刚试了下，首先提示duckdb is not installed，右侧有install按钮，点了无效，于是去官方下了最新的（0.91）命令行的duckdb客户端，丢进任意path中，发现可以连了，但是会提示“duckdb version must be >= 3.9”，注我的数据库也是用0.91版本的Python库建立的。

BTW，选择duckdb数据库文件对话框，默认的格式是db，但官方默认后缀是duckdb，当然，这个后缀仅仅是习惯，不会实质影响。
另外，如果duckdb的引擎是命令行客户端，那么要是能够自己选择引擎程序那就更加美滋滋，这样可以选择自己需要的版本的引擎。
![282507432-236679f6-3058-44f7-8dca-38ee88f2d523](https://github.com/cweijan/vscode-database-client/assets/5030800/cb5197cd-c363-425e-b38b-b2992f6f292c)

**Comment by cweijan** [comment]
谢谢反馈, 我会在下个版本优化, 你说的引擎程序是指什么? 现在是直接使用path下的命令.

**Comment by coloraven** [comment]
> 谢谢反馈，我会在下个版本优化，你说的引擎程序是指什么？现在是直接使用 path 下的命令.

引擎程序是指duckdb的命令行客户端：
https://github.com/duckdb/duckdb/releases/download/v0.9.1/duckdb_cli-windows-amd64.zip

**Comment by cweijan** [comment]
Hi, 目前版本你可以先将duckdb程序放在这个用户路径内, 同时不要加到path, 修复这个问题的新版本预计下载发布

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/139d2b86-1d06-47e8-9c0d-29bb5f46affb)

**Comment by coloraven** [comment]
从path目录移动至.dbcllient后，可以连接了，具体使用有待进一步进行。

**Comment by cweijan** [comment]
已在版本6.8.5修复不支持duckdb命令.
