### ISSUE TITLE
[BUG] SQL Server version 16, Database not found

### ISSUE THREAD

**Issue by lexiddie** [cweijan/vscode-mysql#962]
- Operating system: Windows 11 Pro
- Database type and version: SQL Server 16.0.4085.2 Developer Edition

![sql-server-16-not-found](https://github.com/cweijan/vscode-database-client/assets/37273428/70c619fe-02c7-4754-b3bd-57ab63958504)

**Comment by cweijan** [comment]
Hi, click the filter button to select the database you want to display.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/ad2a53c5-6f0a-49ab-9fbc-3db5ed0d89cb)

**Comment by lexiddie** [comment]
Aww, it works, thank you
