### ISSUE TITLE
[BUG] Doesn't detect end of query

### ISSUE THREAD

**Issue by GTonehour** [cweijan/vscode-mysql#963]
Thanks for all your work on this extension !

Small bug : my cursor is on the first query. I'm trying to run it, but your extension fails on the second query (that I didn't intend to run).

![image](https://github.com/cweijan/vscode-database-client/assets/86954612/5eea8812-d9b3-4630-972a-243f14af3d39)

- v6.8.2
- PG 15
- Windows

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version, you now need to add a space after $function$.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/47113336-5d80-464c-94ba-844ccaff84b9)

**Comment by cweijan** [comment]
Hi, supporting dollar signs and function bodies will cause interference to the SQL parser, so they will not be supported. Please keep spaces between them.
