### ISSUE TITLE
[BUG] After editing one row for next row I get "No table found" 

### ISSUE THREAD

**Issue by vladanan** [cweijan/vscode-mysql#964]
After editing one row for edit of next row I get "No table found!" popup and no editing is possible no matter what I do in the tab. So I need to close tab, open table again in new tab, do the query and sort, edit, and again to close tab and do everything again for each row.

- Operating system: Fedora Linux 38
- Database type and version: mysql  Ver 8.0.34 for Linux on x86_64 (Source distribution)

**Comment by cweijan** [comment]
Sorry for bringing you a bad experience. Please tell me what SQL you are querying. I will improve it in future versions.

**Comment by vladanan** [comment]
On the top of plugin it says: MySql local 8.0.32

Query: SELECT * FROM orders ORDER BY `id` desc LIMIT 100

After successful editing I get: UPDATE orders SET `date`='2023-11-03' WHERE `id`=25448;
AffectedRows : 1

After right click on next row and selecting "Edit row" I get popup "No table found!"

**Comment by cweijan** [comment]
Fixed in version 6.8.4.

**Comment by vladanan** [comment]
Yes it works now. Great work! I'm glad I helped so we get extension to work better.
