### ISSUE TITLE
[BUG]有外键约束的情况下，依然可以进行更新和删除

### ISSUE THREAD

**Issue by K332** [cweijan/vscode-mysql#965]
mysql创建表有外键关联时，约束不起作用，依然可以通过sql语句或操作按钮进行删除/更新
- Operating system: windows
- Database type and version:vscode/database-client v6.8.2

**Comment by cweijan** [comment]
你试试其他客户端会不, 我这边试了下是正常的.

**Comment by K332** [comment]
> 你试试其他客户端会不, 我这边试了下是正常的.

好的谢谢，解决了，database-client不行，mysql可以
(另外就是sql语句缺少GREATEST/LEAST提示)

**Comment by cweijan** [comment]
我知道了, 是删除表的时候我关闭了外键约束, 没有恢复过来, 我会在下版本修复.

**Comment by K332** [comment]
> 我知道了, 是删除表的时候我关闭了外键约束, 没有恢复过来, 我会在下版本修复.
外键这里的bug还有一些，比如我的子表设置了set null，但是删除主表对应的关联值后，子表里关联的数据没有变成null，
子表设置cascade一样的，主表更新子表没有同步。麻烦作者修改下了。

**Comment by cweijan** [comment]
已在版本6.8.4修复.
