### ISSUE TITLE
[BUG]查询看不到数据，但是按放大按钮可以正常观测到数据

### ISSUE THREAD

**Issue by mengdalida** [cweijan/vscode-mysql#966]
- Operating system:
- Extension version:
- Database type and version:
<img width="1168" alt="截屏2023-11-07 下午3 48 51" src="https://github.com/cweijan/vscode-database-client/assets/104249502/a6ab1097-79d4-4e40-886f-bd5771f7ff68">

**Comment by cweijan** [comment]
什么操作会出现这种情况呢

**Comment by mengdalida** [comment]
> 会出现这种情况呢

连接到数据库后，直接查询，没有其他操作

**Comment by cweijan** [comment]
那挺奇怪的, 之前没人遇到过这个情况, 麻烦在页面内按下F12, 看看有没有红色的错误日志.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/e30f762e-cc37-4435-9daf-b7715bd81944)

**Comment by mengdalida** [comment]
> 那挺奇怪的, 之前没人遇到过这个情况, 麻烦在页面内按下F12, 看看有没有红色的错误日志.
> ![image](https://user-images.githubusercontent.com/27798227/280969338-e30f762e-cc37-4435-9daf-b7715bd81944.png)

我是在vscode里，用的是mac电脑，没有F12需要怎么操作

**Comment by cweijan** [comment]
执行下这个命令
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/88ffc306-7b19-4242-851d-9319f57eac11)

**Comment by mengdalida** [comment]
我知道问题了，配置里的33px我改成了33，就会导致这个问题

**Comment by cweijan** [comment]
好的谢谢反馈
