### ISSUE TITLE
mongo无法方便地指定 authenticationDatabase

### ISSUE THREAD

**Issue by fuyaozs9wl** [cweijan/vscode-mysql#967]
如下对比图所示
![image](https://github.com/cweijan/vscode-database-client/assets/132030377/72851086-b25b-4e3e-926d-92436d9ef77f)
![image](https://github.com/cweijan/vscode-database-client/assets/132030377/69a342e9-54ee-4dcc-a35a-6a170dff3f43)
希望能支持该特性，感谢！

**Comment by cweijan** [comment]
谢谢反馈, 我会在下版本支持.

**Comment by fuyaozs9wl** [comment]
感谢支持

**Comment by cweijan** [comment]
已在版本6.8.4支持配置认证数据库.
