### ISSUE TITLE
[BUG] All icons are there three times

### ISSUE THREAD

**Issue by BenBernhardG** [cweijan/vscode-mysql#968]
- Operating system: ubunto ssh connection on windows
- Database type and version: MySQL

Screen Shots:
![Screenshot 2023-11-11 091822](https://github.com/cweijan/vscode-database-client/assets/138679020/8a51e738-a3b2-44b1-96eb-f4199ed62714)
![Screenshot 2023-11-11 091915](https://github.com/cweijan/vscode-database-client/assets/138679020/d8b4445a-7e89-407a-abcb-c058efaa84df)
![Screenshot 2023-11-11 091952](https://github.com/cweijan/vscode-database-client/assets/138679020/f7bfe1f2-a323-43d1-b170-ba704f117fca)

**Comment by cweijan** [comment]
I have released multiple extensions with duplicate functions, please uninstall the others and keep only one.
