### ISSUE TITLE
[BUG] Create auto filter by filter row in nvarchar columns

### ISSUE THREAD

**Issue by mahdi-hajian** [cweijan/vscode-mysql#970]
- Operating system: windows
- Database type and version: 6.8.3

When I enable switchbox for showing filter row, I set filter for a nvarchar column and a new filter was created like this "SELECT TOP 100 * FROM "HR"."Personnel" WHERE "FirstName" like '%ام%'"
but FirstName is nvarchar column and must be change to "SELECT TOP 100 * FROM "HR"."Personnel" WHERE "FirstName" like N'%ام%'"

Tanks

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
The N prefix has been added to nvarchar in version 6.8.6.
