### ISSUE TITLE
[BUG]SSH连接部分linux服务器报超时，其他工具可以连接，例如xshell，open-ssh

### ISSUE THREAD

**Issue by Bohechacha** [cweijan/vscode-mysql#971]
- Operating system:Win10
- Database type and version:v6.8.4

**Comment by cweijan** [comment]
你的服务器连接稳定吗, 默认是5秒超时

**Comment by Bohechacha** [comment]
测试了，是因为连接速度原因，公司连接服务器是用wifi，加上不同vlan之间跳转，导致连接时间有点长，使用网上的方案
修改服务器ssh配置文件的dns反向解析，GSSAPI，
database-client已可以连接成功
但是我觉得5秒超时写的有点死，时间预留有点短，可以参考SecureCrt，xshell等工具ssh连接的处理方式，参数等。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cweijan/vscode-database-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 上午10:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cweijan/vscode-database-client] [BUG]SSH连接部分linux服务器报超时，其他工具可以连接，例如xshell，open-ssh (Issue #971)





 
你的服务器连接稳定吗, 默认是5秒超时

**Comment by cweijan** [comment]
可以在面板上方修改超时时间.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/d9505240-3694-49c7-a716-3e8454e80b5e)

**Comment by Bohechacha** [comment]
单纯的增加超时时间好像并不能解决问题。（我加了个0，这个时间应该足够长了，没到50000毫秒就已经报这个错了），所以，有时间可以进一步排查下，是不是还有地方参数要改^_^




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cweijan/vscode-database-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cweijan/vscode-database-client] [BUG]SSH连接部分linux服务器报超时，其他工具可以连接，例如xshell，open-ssh (Issue #971)





 
可以在面板上方修改超时时间.

**Comment by Bohechacha** [comment]
我只知道改这个可以解决或者开始是回避这个问题，但是并不清楚原因

改服务器里面的那两个参数，就可以用database连接了，超时时间默认5000毫秒就行，不改这两个参数，那就超时。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cweijan/vscode-database-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cweijan/vscode-database-client] [BUG]SSH连接部分linux服务器报超时，其他工具可以连接，例如xshell，open-ssh (Issue #971)





 
Closed #971 as completed.

**Comment by cweijan** [comment]
你连的是数据库还是ssh服务器呢? 如果是SSH隧道连接超时是在下半区配置的.

**Comment by Bohechacha** [comment]
ssh服务器
下半区啥意思，除了你上次说的延时设置输入框，没有别的设置延时的地方了啊







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cweijan/vscode-database-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 下午2:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cweijan/vscode-database-client] [BUG]SSH连接部分linux服务器报超时，其他工具可以连接，例如xshell，open-ssh (Issue #971)





 
你连的是数据库还是ssh服务器呢? 如果是SSH隧道连接超时是在下半区配置的.

**Comment by cweijan** [comment]
如果是SSH隧道是在这里配置的.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/305f54cb-da8a-4284-b6d7-e4bf576a23a9)

**Comment by Bohechacha** [comment]
嗯，谢谢您的解答，找到了，展开的话界面看起来有点奇怪，上下两个填host、密码的地方
而且找个时间我刚才也设置试过了，奇怪的是，增加这个超时时间，并不能解决我的问题，下面这个超时时间设成一个很大的值（50000），工具还是提示连接超时而失败。。。蚌埠住了，非要我用别的工具登到服务器上，改了那两个ssh参数才行。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cweijan/vscode-database-client"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cweijan/vscode-database-client] [BUG]SSH连接部分linux服务器报超时，其他工具可以连接，例如xshell，open-ssh (Issue #971)





 
如果是SSH隧道是在这里配置的.

**Comment by cweijan** [comment]
我想你理解错我的意思了, 你上面提到了数据库, 我以为你是在使用ssh隧道, 如果你没用到ssh隧道, 那你就不用改这个. 超时我会去排查下是否某处代码有问题, 导致超时不生效.
