### ISSUE TITLE
Cant create a new connection

### ISSUE THREAD

**Issue by lospetitos** [cweijan/vscode-mysql#972]
I have done the update for the version 6.8.3 and after this update when i try to create a new connection to database i got this error and i dont understand why. Can i have have some help pls ? I tried to install old versions but even with the old versions i cant create new connection.
![image](https://github.com/cweijan/vscode-database-client/assets/79666666/a91d219c-d495-4033-b44a-df41d84f371d)

**Comment by cweijan** [comment]
Please restart VS Code.
