### ISSUE TITLE
Support for Firebase Firestore Database

### ISSUE THREAD

**Issue by giuvincenzi** [cweijan/vscode-mysql#973]
I would like to propose the addition of Firestore Database integration. 
Currently, are support various database connections, and incorporating Firestore would be a valuable addition.

**Comment by cweijan** [comment]
Thank you for your propose, I will check out the service you mentioned.

**Comment by cweijan** [comment]
I looked into firestore and its API is hugely different from existing connections, so I don't plan to support it.
