### ISSUE TITLE
CONSOLE ERROR : ENOENT: no such file or directory ....

### ISSUE THREAD

**Issue by gzlo** [cweijan/vscode-mysql#975]
hi! just a few minutes ago i was workin no problem and just not letme opened files from FTP ... it is possible to work from the terminal, but not from the file browser. any ideas? 

 ENOENT: no such file or directory, mkdir 'c:\Users\gzlon\AppData\Roaming\Code\User\globalStorage\cweijan.vscode-database-client2\temp\dbclient\PROD || AMSI\'

**Comment by cweijan** [comment]
Thank you for your feedback. In recent versions, the connection name will be used as the temporary file path. Please delete the "|" in the connection name. I will fix this problem in the next version.

**Comment by gzlo** [comment]
thanks, that will fix it !!

**Comment by cweijan** [comment]
Fixed in version 6.8.5.
