### ISSUE TITLE
Multiple tabs for tables

### ISSUE THREAD

**Issue by gzlo** [cweijan/vscode-mysql#976]
This is just an idea, I don't know if actually it is possible to open 2 tables at the same time, because when I select a table all the results goes to the same tab, shouldbe cool to open more than 1 table at the same time

**Comment by cweijan** [comment]
There are two ways to open multiple tabs:

1. ![image](https://github.com/cweijan/vscode-database-client/assets/27798227/7a9dc4d5-013b-4613-901a-5afd55428ff1)
2. 
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/35134d74-6d2e-472c-aa6c-9b60af9fa94a)
3. In version 6.9.1, added configuration to create new views for each query.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/4942ba7a-bc4d-4032-bdca-39f0c4b089ce)

**Comment by gzlo** [comment]
you arw awesome !! thats why i paid for this !!! thanks
