### ISSUE TITLE
[BUG] Execute按钮消失

### ISSUE THREAD

**Issue by K332** [cweijan/vscode-mysql#977]
![image](https://github.com/cweijan/vscode-database-client/assets/52175621/b91db710-ad80-454f-b2a0-04723460bece)

 
- Operating system: Windows
- Database type and version: Mysql v6.8.4

**Comment by cweijan** [comment]
你打开控制台页面看是不是禁用了.

**Comment by K332** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/52175621/f5f655b0-e69a-450e-a41b-5c79c682475e)
没看到有什么报错

**Comment by cweijan** [comment]
我是说你禁用了codelen, 这是扩展的设置.

**Comment by K332** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/52175621/1149cb1f-3084-498b-ac67-93138271040b)
没有设置过

**Comment by K332** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/52175621/dd0287df-4f55-46a2-a46b-d782f5489a8e)
测试了下老的开源版本没有消失，新的不行，不知道是什么问题

**Comment by cweijan** [comment]
很奇怪, 麻烦你打开下开发者工具, 看控制面板有没有错误日志.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/4317e084-4721-469c-9501-ed936bb2208e)
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/fefc9988-93df-4098-b82e-567746d76788)

**Comment by K332** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/52175621/74803b0f-a7b1-400e-8d7d-d85f0063ba6e)
这个吗，vscode的sqlite插件为什么导致这个按钮消失呢

**Comment by cweijan** [comment]
可能SQL编辑器被其他扩展接管了, 你试试把其他数据库相关的扩展禁用.

**Comment by K332** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/52175621/ead6c1fa-338c-46fa-9ab5-68e4256a10e3)
禁用了这个插件没问题了

**Comment by cweijan** [comment]
好
