### ISSUE TITLE
Support pgsql file extensions

### ISSUE THREAD

**Issue by geekox86** [cweijan/vscode-mysql#978]
Hello. Thank you for this great tool.

I am currently using your extension with PostgreSQL Language Server extension to get intellisense (syntax highlighting and type/reference checking). The problem is that your extension does not show the in-editor commands when opening *.pgsql files (Postgres language association) and the PG LS extension does not work with *.sql files unless I change the language association to Postgres but then your extension stops working on these files.

Is there a way to use both extensions at the same time?

**Comment by cweijan** [comment]
I will try to be compatible with this extension you mentioned.

**Comment by cweijan** [comment]
Already compatible with version 6.8.5, supporting codelen and ctrl/meta+enter shortcut keys.
