### ISSUE TITLE
[BUG] after placing a column in select the result is filtered

### ISSUE THREAD

**Issue by brunolamegolino** [cweijan/vscode-mysql#979]
![image](https://github.com/cweijan/vscode-database-client/assets/25511732/2234254c-47cb-4de3-a56d-8b7b31c7f177)
![image](https://github.com/cweijan/vscode-database-client/assets/25511732/a06ab190-c0f9-4f77-ba27-324d70496676)

In the database when I use the same queries the returns are correct
![image](https://github.com/cweijan/vscode-database-client/assets/25511732/ff192d70-8baa-43fa-8926-3b915e6d2b68)
![image](https://github.com/cweijan/vscode-database-client/assets/25511732/47c135b0-c832-4f41-bbcd-2165efadcbb9)

- Operating system: docker - php:7.4.33-apache
- Database type and version: mysql - 5.6.51

**Comment by cweijan** [comment]
I can't understand what you are talking about? Do you mean the total number obtained is incorrect?

**Comment by brunolamegolino** [comment]
Well, that.
The resulting total rows are different when I select an additional column.

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed in version 6.9.0.
