### ISSUE TITLE
Search in columns selection

### ISSUE THREAD

**Issue by mirkadev** [cweijan/vscode-mysql#981]
<img width="1462" alt="image" src="https://github.com/cweijan/vscode-database-client/assets/45996373/afa33f5c-ea62-4539-8d63-d7b193fe6a3c">

Hi! Would be nice to have search + filter here

**Comment by cweijan** [comment]
A column search input has been added in version 6.8.6.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/365ebbbc-0d44-4afe-a82f-f2cf43c37b1b)

**Comment by mirkadev** [comment]
Thank you!
