### ISSUE TITLE
[BUG] Performance issues with large sql Files

### ISSUE THREAD

**Issue by PatrickJahner** [cweijan/vscode-mysql#983]
I have massive Performance issues (i think since Version 6.8.4 2023-11-13)

I have a big SQL File where we store our Querys. The File has 60.000 Lines and is abou 3 MB big.

It is virtually impossible to work in the file. Every keystroke has an input lag of about 2 Seconds. As soon as i change the Language to PlainText or disable your plugin, the file works well. Before that release, I had no such issues.

I am not dependent on code completion within the file, since I am pretty sure it wouldn't work seamlessly anyway, since it would not know where to divide the querys (we use "//--------------------------------------------------------//" as divider), so i would take any workaround you can give me

I know the hardware is not the latest state of art, and i well get an new Machine by the end of the year. But I would guess there is some performance problem with the plugin.

Thank you for your wonderful work!

- Operating system: Windows
- Database type and version: PostgreSQL 14
- CPU I7 4790K 
- 16 MB RAM
- Harddisc: 512GB Samsung SSD 860 PRO

**Comment by cweijan** [comment]
Thank you for your feedback. In this version, the limit of SQL parsing rows has been increased from 5000 to 20000. I will call it back and add option control in the next version.

**Comment by cweijan** [comment]
Restored parsing line numbers in version 6.8.7.

**Comment by PatrickJahner** [comment]
I am sorry, but it is still virtually impossible for me to work in large SQL Files :\

I use version 6.8.9

**Comment by cweijan** [comment]
Hi, how big is your file?

**Comment by cweijan** [comment]
Hi, try the latest version 6.9.2, now the SQL parser will be disabled when editing large files.

**Comment by PatrickJahner** [comment]
Looks good!

Just for your information: I think with an older Version code completion ran fine even in large files without problems.

**Comment by PatrickJahner** [comment]
Sorry, I still have trouble with an SQL File. it is 1200 kb big.

**Comment by cweijan** [comment]
Hi, are you still using this extension? I have improved the SQL parsing performance in the latest version 7.3.6.

At the same time, it also supports disabling completion.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/7fdae71c-ecf3-4c4b-85d9-a227439cadba)

**Comment by PatrickJahner** [comment]
I am still experimenting with it. I do not have much time to care about it. But I will test it within the next Weeks and come back to you again. Thanks for your Support!

Mit freundlichen Grüßen
Patrick Jahner

Von: Weijan Chen ***@***.***>
Gesendet: Montag, 13. Mai 2024 09:57
An: cweijan/vscode-database-client ***@***.***>
Cc: Patrick Jahner ***@***.***>; State change ***@***.***>
Betreff: Re: [cweijan/vscode-database-client] [BUG] Performance issues with large sql Files (Issue #983)


Hi, are you still using this extension? I have improved the SQL parsing performance in the latest version 7.3.6.

At the same time, it also supports disabling completion.
image.png (view on web)<https://github.com/cweijan/vscode-database-client/assets/27798227/7fdae71c-ecf3-4c4b-85d9-a227439cadba>

**Comment by cweijan** [comment]
It doesn't matter, you can ignore it, as long as it doesn't affect your use.

**Comment by PatrickJahner** [comment]
My device Specs have updated
Intel(R) Core(TM) i7-14700K   3.40 GHz
48 gb Ram

With this and your updates it seems to run much better now.
