### ISSUE TITLE
[BUG]redis无法切换数据库

### ISSUE THREAD

**Issue by K332** [cweijan/vscode-mysql#984]
![image](https://github.com/cweijan/vscode-database-client/assets/52175621/3054df77-6c4e-445b-8b74-6e6696ce3421)
无法切换数据库
- Operating system:Windows
- Database type and version: mysql-6.8.6 (vscode)

**Comment by cweijan** [comment]
你需要先set一个key进去, 列表只会列出有数据的数据库, 为空则只显示数据库0.
