### ISSUE TITLE
可以加个关键字大写的设置吗？

### ISSUE THREAD

**Issue by Dradows** [cweijan/vscode-mysql#985]

**Comment by cweijan** [comment]
关键字默认就是大写的, 你是指格式化后的关键字吗?

**Comment by Dradows** [comment]
对的，格式化后将关键字大写

**Comment by cweijan** [comment]
谢谢反馈, 我会尝试在下版本支持.

**Comment by cweijan** [comment]
已在版本6.8.7支持.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/1bf62abf-6959-450c-9799-f2ab20e2a363)
