### ISSUE TITLE
内网环境怎么使用Dump Data和Dump Struct？

### ISSUE THREAD

**Issue by Dradows** [cweijan/vscode-mysql#986]
点了之后输出Start downloading zlib1.dll，然后就超时中止了。如果自己下载的话，这个dll该放在哪个路径？还需要其他dl吗？

**Comment by cweijan** [comment]
无法联网的话需要自行下载pg客户端并加到环境变量哈, 为了节省内存扩展没有捆绑这些应用.
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/f7936ff8-d98a-468b-aca8-c2dc486bf497)
