### ISSUE TITLE
[BUG] Can't use the extension with table names that contains `.`

### ISSUE THREAD

**Issue by luislhsc** [cweijan/vscode-mysql#988]
Hello team! Thank you for this awesome extension, it has been pretty useful for me!

At work, we use tables prefixed with **domain** `.` **table_name** 
Like this: `messaging.conversations`
But the domain isn't a schema in DB, it is just a prefix that we created to make it easier for us track who owns each table.

When using the extension, I get this error:
![image](https://github.com/cweijan/vscode-database-client/assets/16543685/a70818c3-ba5a-48c8-8586-336ccd333f8a)

If I wrap the whole table name into double quotes, it does work: 
![image](https://github.com/cweijan/vscode-database-client/assets/16543685/a978235c-8363-4d41-8674-5924f086e3cc)

The problem is that each table that I open, each record that I try to edit, the extension always try to use the table without quotes.
I enabled a settings called "Escaped all object name", but it spreads the table name into two parts, like: "messaging"."conversations"
![image](https://github.com/cweijan/vscode-database-client/assets/16543685/30f629bf-1679-4075-b9ab-ff6207026338)

And it doesn't work, like the image above.

On other tools like DataGrip, it works pretty well, by adding the quotes around the whole table name (even in suggestions or generated queries) 

Is it possible to have a similar behavior on the extension? Just escape the table name, but not splitting it into 2 parts. 

Thank you in advance!

**Comment by cweijan** [comment]
Thanks for the feedback, I will try to make it compatible.

**Comment by cweijan** [comment]
Hi, I have supported table names with "." in version 6.8.7, but due to its special, the extension does not provide completion when crossing databases or schemas.
