### ISSUE TITLE
The Redis icon is  not clear

### ISSUE THREAD

**Issue by lmovse** [cweijan/vscode-mysql#989]
Redis
![image](https://github.com/cweijan/vscode-database-client/assets/19148311/6c528b9a-bfbe-4581-9fa9-8f1c2096f952)

Other
![image](https://github.com/cweijan/vscode-database-client/assets/19148311/766f5c3a-199f-49b2-8e37-a3bf0653579b)

**Comment by cweijan** [comment]
Thank you for your feedback, I will modify it in the next version.
