### ISSUE TITLE
[BUG] 8 Times on 10, Search Results does not work

### ISSUE THREAD

**Issue by blk-raffy** [cweijan/vscode-mysql#990]
- Database type and version:
Postgres (With postgis) 15.2

Sometimes the "Search result" input field inside an opened table doesn't update the table results.
The selected table is unlocked, 2 weeks ago it was working fine, after few updates it broke. 
I already re-installed the extension. I Have the paid plan.

**Comment by cweijan** [comment]
Thanks for your feedback, I recently refactored the code in order to better maintain the view, but the result filter was missing. I released version 6.8.8 to fix it.

**Comment by blk-raffy** [comment]
It works, thank you very much
