### ISSUE TITLE
[BUG] schema not automatically applied on query execution

### ISSUE THREAD

**Issue by Enubia** [cweijan/vscode-mysql#991]
- Database type and version: Postgres | DB client version v6.8.8

Previously when executing a query the selected schema was taken into account automatically.

Now the schema is ignored and it needs to be explicitly specified when executing queries.

See examples below:

without schema:
![Screenshot 2023-11-28 at 10 02 28 AM](https://github.com/cweijan/vscode-database-client/assets/44695100/daea9b37-2475-4e94-ac6e-ffd7703870b1)

with schema:
![Screenshot 2023-11-28 at 10 08 57 AM](https://github.com/cweijan/vscode-database-client/assets/44695100/8dc685a7-3202-4e01-9da5-a8d5d8ee30c4)

**Comment by cweijan** [comment]
This is weird, I can work fine, please execute the following SQL to see the current schema
```
SELECT CURRENT_SCHEMA();
```

**Comment by Enubia** [comment]
this is returned, can it be a postgres only issue?

![Screenshot 2023-11-28 at 10 21 12 AM](https://github.com/cweijan/vscode-database-client/assets/44695100/c14279b3-0dbc-49ac-a7d4-fbf0e6ab61a7)

**Comment by cweijan** [comment]
It seems that your postgresql does not have a default schema. Please downgrade to version 4.8.6 first. I will fix it in the next version.

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/2ade8d56-984a-4912-aa5c-0aa1c19b611c)

**Comment by Enubia** [comment]
version downgrade fixed it, will wait with the upgrade for your fix

thanks

**Comment by cweijan** [comment]
Hi, please try the latest version 6.8.9.

**Comment by Enubia** [comment]
> Hi, please try the latest version 6.8.9.

The issue persists with the newest version unfortunately

EDIT: PostgreSQL 13.6 is what I'm using if that's of any help

**Comment by cweijan** [comment]
sad, I installed postgresql13.6 and it works fine. If you click on the table in the tree view, will it be able to query?

![image](https://github.com/cweijan/vscode-database-client/assets/27798227/a89ca4a5-70c9-4167-9344-d5917567ef79)

**Comment by Enubia** [comment]
yes the query works when i click on the tree view

**Comment by Enubia** [comment]
Ok so I've opened another query file and now the queries are working as expected

**Comment by Enubia** [comment]
could it be that the connection/query execution is different based on when the query file was created? I usually pin them in my editor since I have a bunch of queries saved

**Comment by Enubia** [comment]
![287237604-81ed9b55-14c9-4c4b-bcaf-849ad4ae54b5](https://github.com/cweijan/vscode-database-client/assets/44695100/414c6194-53e3-4dad-8587-352424998ee1)

**Comment by cweijan** [comment]
The creation time does not affect them. After restarting VS Code, the connection needs to be re-created. Maybe this affects it.
You can try switching different query files on the same connection to see if it works properly.

**Comment by Enubia** [comment]
It seems like I found a difference,

the old file had a trailing whitespace after the connection string whereas the new file doesn't

If I try to execute a query with the old connection string (which was auto-created) it shows the aforementioned error

If I switch the version to v6.8.6 it works just fine with this trailing space

I assume this is a very special edge case

**Comment by cweijan** [comment]
Thanks for the feedback. I had the same problem when I added a space after the connection string. I will fix it in the next version.

**Comment by cweijan** [comment]
Fixed in version 6.9.0.
