### ISSUE TITLE
ARRAY TYPE lost Postgresql [BUG]

### ISSUE THREAD

**Issue by roby4711** [cweijan/vscode-mysql#992]
- Database type and version: Postgresql 16 Windows
- It looks like table columns of type e.g. SQL integer Array resp. integer[] loose their type and turn into Array only (integer gets somehow lost)

by the way this is a fantastic extension.

**Comment by cweijan** [comment]
Thanks for your feedback, I will support display array type in the future.

**Comment by cweijan** [comment]
Fixed in version 6.8.9.

**Comment by roby4711** [comment]
awesome thank you 🥇 👍

**Comment by roby4711** [comment]
... works for integer[], double precision[]
but unfortunately not for
text[]
which in case of a text array still only shows plain (non array) text type.

**Comment by cweijan** [comment]
Thanks for your feedback, I will fix it in the next version.
