### ISSUE TITLE
Redis: HASH names

### ISSUE THREAD

**Issue by andrey-vrn** [cweijan/vscode-mysql#994]
When i use a HASH names like "flags:need_restart", in tree view HASH name is "flags:need_restart" instead of "need_restart".
In RedisInsight this situation diaplays more user likely.
![image](https://github.com/cweijan/vscode-database-client/assets/72127211/f5a7e5d8-54fa-4b8d-865e-56da6cff539a)
![image](https://github.com/cweijan/vscode-database-client/assets/72127211/8c8e45bf-7a7f-4533-8743-adbefce44e32)

**Comment by cweijan** [comment]
For tree views, it is better to display the full name of the key. Removing the prefix will cause confusion for keys with the same name.
