### ISSUE TITLE
can i add rustdesk to extention ?

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#995]
Would it be possible for me to add rustdesk connection to the software features?

I have already done this for the ClickHouse driver.

**Comment by cweijan** [comment]
rustdesk is remote desktop software, how do you create a connection? And the extension is now closed source, I will not disclose the code.

**Comment by mbtolou** [comment]
https://rustdesk.com/docs/en/dev/build/web/

**Comment by cweijan** [comment]
I looked at this page, rustdesk web runs a web client locally via a docker container, I don't think the extension is able to support it.
