### ISSUE TITLE
[BUG] port forwarding problem .

### ISSUE THREAD

**Issue by mbtolou** [cweijan/vscode-mysql#996]
Hi
When I try to do port forwarding for ssh I run into a problem.

Connection error! { "reason": 2 }

**Comment by mbtolou** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/6413705/e4661103-da72-41b8-8773-f1ab0b78cd6a)

**Comment by cweijan** [comment]
Hi, port forwarding has been refactored in version 7.0.1, please check if it works for you.
