### ISSUE TITLE
Run Mock按钮消失

### ISSUE THREAD

**Issue by K332** [cweijan/vscode-mysql#998]
excute生成按钮这些还在，但是模拟数据的这个没了，看官网介绍是有这个按钮的，不知道是什么问题
![image](https://github.com/cweijan/vscode-database-client/assets/52175621/9f96cf52-cff9-43d3-8eb4-b3f7c8b9ef14)
![image](https://github.com/cweijan/vscode-database-client/assets/52175621/69dcb915-b36d-4fb8-b0cb-d44612c32839)
![image](https://github.com/cweijan/vscode-database-client/assets/52175621/36bfd717-31a4-4829-9b42-ea51dbf80e7f)

**Comment by cweijan** [comment]
你这个文件的结尾是*-mock.json不, 按钮显示只有这个判断逻辑

**Comment by cweijan** [comment]
另外的可能就是被其他扩展给覆盖了.

**Comment by K332** [comment]
右键生成随机数据弹出的界面，后缀名没有问题，这次看控制台也没有报错，扩展没有开其他数据库相关的了

**Comment by cweijan** [comment]
Hi, 你看看右下角的语言是不是非json, 目前是限定json
![image](https://github.com/cweijan/vscode-database-client/assets/27798227/6f67d020-14cd-4def-b1a7-33a4c2f776f2)

**Comment by K332** [comment]
![image](https://github.com/cweijan/vscode-database-client/assets/52175621/dc62e791-2f08-403b-bbdd-f85b37f10328)
这样的可以吗

**Comment by cweijan** [comment]
你是将所有json默认都设置为jsonc吗? 你用jsonc写注释的话扩展是不支持的, 建议你改回来.

**Comment by K332** [comment]
嗯，默认都是jsonc

**Comment by cweijan** [comment]
已发布版本6.9.0支持在jsonc中显示mock按钮.
