### ISSUE TITLE
Cant see the mysql.user table

### ISSUE THREAD

**Issue by tgrassmee** [cweijan/vscode-mysql#999]
Hi,

first off all thanks for this nice extension, but i have a issue with the user table in the mysql db.... The extension shows only 30 tables without the user table in the treeview. Within the console all works well. Where is the issue here? both login with the same rights-> root. Any suggestions,

Best regards from Berlin

**Comment by tgrassmee** [comment]
![Bildschirmfoto vom 2023-12-07 13-25-52](https://github.com/cweijan/vscode-database-client/assets/4252871/b6f3995f-ef58-4e39-b4bc-45c10fbaf206)
The Select Statment SELECT * FROM mysql.user works well and shows the expected result but the table not will shown in the treeview

**Comment by cweijan** [comment]
Maybe the version of mysql you are using hides the user table, or maybe it becomes a view.

**Comment by cweijan** [comment]
You can try using other tools to see if the user table is displayed.

**Comment by tgrassmee** [comment]
it becomes a view.... Thanks for the hint....
